/**
 * @file scripts/etl/ambiente/gerar-barragens-mundiais.mts
 * @description ETL gerador do acervo de Grandes Barragens Mundiais (água, energia, mineração).
 *
 * Papel no portal:
 * Gera o acervo compacto em apps/web/data/ambiente/barragens-mundiais.compact.json
 * e a camada GeoJSON apps/web/public/terras/globo/dados/camadas/barragens-mundiais-destaque.geojson
 * para visualização geoespacial no Globo 3D Terras e no portal cívico.
 *
 * Fontes oficiais consultadas:
 * - ICOLD (International Commission on Large Dams — World Register of Dams)
 * - Global Tailings Portal (GRID-Arendal / UNEP / Church of England Pensions Board)
 * - USACE NID (United States Army Corps of Engineers — National Inventory of Dams)
 * - ANM / SIGBM (Agência Nacional de Mineração — Sistema Integrado de Gestão de Segurança de Barragens de Mineração)
 * - ANA (Agência Nacional de Águas e Saneamento Básico — Relatório de Segurança de Barragens - RSB)
 * - MITECO (Ministério para a Transição Ecológica da Espanha)
 * - BC Ministry of Energy, Mines and Low Carbon Innovation (Canadá)
 *
 * Conformidade e segurança:
 * - Zero dados pessoais / sem CPFs (AGENTS.md §5.2).
 * - Coordenadas precisas em datum WGS84 [longitude, latitude].
 * - Padrão das Seis Qualidades do Controle Popular (AGENTS.md §8).
 * - Compactação de tabela versionada por esqueleto + rótulos internados (compactar.ts).
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compactar } from "../../../apps/web/lib/estatico/compactar.js";

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const DIR_DATA_OUT = path.join(RAIZ, "apps", "web", "data", "ambiente");
const DIR_GEOJSON_OUT = path.join(
  RAIZ,
  "apps",
  "web",
  "public",
  "terras",
  "globo",
  "dados",
  "camadas"
);

export type TipoBarragem =
  | "rejeitos_mineracao"
  | "hidreletrica"
  | "abastecimento_multiuso"
  | "controle_cheias";

export type StatusOperacional =
  | "em_operacao"
  | "desativada_descaracterizacao"
  | "rompida_historico"
  | "em_construcao";

export interface BarragemMundialBruta {
  id: string;
  nome: string;
  tipoBarragem: TipoBarragem;
  tipoEstrutura: string;
  pais: string;
  continente:
    | "América do Sul"
    | "América do Norte"
    | "Europa"
    | "Ásia"
    | "África"
    | "Oceania";
  rioOuBacia: string;
  alturaMetros: number;
  volumeCapacidadeMm3: number;
  operador: string;
  classificacaoRiscoOuHazard: string;
  statusOperacional: StatusOperacional;
  anoConclusao: number;
  latitude: number;
  longitude: number;
  resumoCivico: string;
  orgaoReguladorOuBase: string;
  linkFonteOficial: string;
  tags: string[];
}

/**
 * Acervo curado com mais de 50 grandes barragens emblemáticas em todo o mundo.
 * Cobre barragens de rejeitos (com histórico de rompimento e monitoramento crítico),
 * grandes hidrelétricas mundiais e reservatórios multiuso estratégicos.
 */
export const BARRAGENS_MUNDIAIS_BRUTAS: BarragemMundialBruta[] = [
  // ==========================================
  // REJEITOS DE MINERAÇÃO (TAILINGS)
  // ==========================================
  {
    id: "BAR-BR-FUNDAO",
    nome: "Barragem de Fundão",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Alteamento a Montante",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Bacia do Rio Doce / Rio Gualaxo do Norte",
    alturaMetros: 55,
    volumeCapacidadeMm3: 50.0,
    operador: "Samarco Mineração (Vale S.A. / BHP Billiton)",
    classificacaoRiscoOuHazard: "Dano Potencial Crítico (Rompida)",
    statusOperacional: "rompida_historico",
    anoConclusao: 2008,
    latitude: -20.2036,
    longitude: -43.4681,
    resumoCivico: "Rompimento em 05/11/2015 liberou 50 Mm³ de lama de rejeitos na Bacia do Rio Doce.",
    orgaoReguladorOuBase: "ANM / SIGBM (Brasil)",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "samarco", "vale", "bhp", "rio-doce", "mariana", "rompimento", "desastre"],
  },
  {
    id: "BAR-BR-FEIJAO-B1",
    nome: "Barragem B1 — Córrego do Feijão",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Alteamento a Montante",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Bacia do Rio Paraopeba / Rio São Francisco",
    alturaMetros: 86,
    volumeCapacidadeMm3: 12.7,
    operador: "Vale S.A.",
    classificacaoRiscoOuHazard: "Dano Potencial Crítico (Rompida)",
    statusOperacional: "rompida_historico",
    anoConclusao: 1976,
    latitude: -20.1197,
    longitude: -44.1194,
    resumoCivico: "Rompimento por liquefação em 25/01/2019 vitimou 272 pessoas em Brumadinho.",
    orgaoReguladorOuBase: "ANM / SIGBM (Brasil)",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "vale", "brumadinho", "paraopeba", "liquefacao", "rompimento"],
  },
  {
    id: "BAR-BR-FORQUILHA-3",
    nome: "Barragem Forquilha III",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Alteamento a Montante",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Bacia do Rio das Velhas / São Francisco",
    alturaMetros: 77,
    volumeCapacidadeMm3: 19.3,
    operador: "Vale S.A.",
    classificacaoRiscoOuHazard: "Nível 3 de Emergência (Risco Iminente / DPA Alto)",
    statusOperacional: "desativada_descaracterizacao",
    anoConclusao: 1982,
    latitude: -20.2522,
    longitude: -43.7667,
    resumoCivico: "Estrutura sob Nível 3 com remoção de comunidades na mancha de inundação e descaracterização em curso.",
    orgaoReguladorOuBase: "ANM / SIGBM (Brasil)",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "vale", "ouro-preto", "rio-das-velhas", "nivel-3", "descaracterizacao"],
  },
  {
    id: "BAR-BR-DOUTOR",
    nome: "Barragem Doutor",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Alteamento a Montante",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Bacia do Rio das Velhas",
    alturaMetros: 74,
    volumeCapacidadeMm3: 35.8,
    operador: "Vale S.A.",
    classificacaoRiscoOuHazard: "Dano Potencial Alto (CRI/DPA - SIGBM)",
    statusOperacional: "desativada_descaracterizacao",
    anoConclusao: 1978,
    latitude: -20.3069,
    longitude: -43.8344,
    resumoCivico: "Descaracterização de grande volume de rejeito de minério de ferro em Ouro Preto.",
    orgaoReguladorOuBase: "ANM / SIGBM (Brasil)",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "vale", "ouro-preto", "descaracterizacao"],
  },
  {
    id: "BAR-BR-SUL-SUPERIOR",
    nome: "Barragem Sul Superior",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Alteamento a Montante",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio São João / Bacia do Rio Doce",
    alturaMetros: 85,
    volumeCapacidadeMm3: 6.0,
    operador: "Vale S.A.",
    classificacaoRiscoOuHazard: "Nível 3 de Emergência (Risco Crítico)",
    statusOperacional: "desativada_descaracterizacao",
    anoConclusao: 1983,
    latitude: -19.9575,
    longitude: -43.4889,
    resumoCivico: "Nível 3 com evacuação da comunidade de Socorro em Barão de Cocais em 2019.",
    orgaoReguladorOuBase: "ANM / SIGBM (Brasil)",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "vale", "barao-de-cocais", "nivel-3", "evacuacao"],
  },
  {
    id: "BAR-BR-GERMANO",
    nome: "Barragem de Germano",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Linha de Centro / Aterro Jusante",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Bacia do Rio Doce",
    alturaMetros: 180,
    volumeCapacidadeMm3: 129.0,
    operador: "Samarco Mineração",
    classificacaoRiscoOuHazard: "Dano Potencial Alto (CRI/DPA - SIGBM)",
    statusOperacional: "desativada_descaracterizacao",
    anoConclusao: 1977,
    latitude: -20.2242,
    longitude: -43.4739,
    resumoCivico: "Maior barragem de rejeitos da Samarco contígua a Fundão, sob constante reforço estrutural.",
    orgaoReguladorOuBase: "ANM / SIGBM (Brasil)",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "samarco", "mariana", "rio-doce"],
  },
  {
    id: "BAR-BR-CORREGO-SITIO-2",
    nome: "Barragem Córrego do Sítio II (CDS II)",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Aterro / Jusante",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio Conceição / Bacia do Rio Doce",
    alturaMetros: 58,
    volumeCapacidadeMm3: 10.2,
    operador: "AngloGold Ashanti",
    classificacaoRiscoOuHazard: "Dano Potencial Alto (CRI/DPA - SIGBM)",
    statusOperacional: "em_operacao",
    anoConclusao: 1989,
    latitude: -19.9881,
    longitude: -43.4111,
    resumoCivico: "Armazenamento de rejeitos de mineração de ouro em Santa Bárbara com monitoramento intensivo.",
    orgaoReguladorOuBase: "ANM / SIGBM (Brasil)",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "ouro", "anglogold", "santa-barbara"],
  },
  {
    id: "BAR-BR-CASA-DE-PEDRA",
    nome: "Barragem Casa de Pedra",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Enrocamento e Linha de Centro",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio Paraopeba / Bacia do São Francisco",
    alturaMetros: 76,
    volumeCapacidadeMm3: 50.0,
    operador: "CSN Mineração",
    classificacaoRiscoOuHazard: "Dano Potencial Alto (Área Urbana Adjacente)",
    statusOperacional: "em_operacao",
    anoConclusao: 1980,
    latitude: -20.4831,
    longitude: -43.8569,
    resumoCivico: "Grande estrutura de rejeitos vizinha a bairros urbanos densamente povoados de Congonhas.",
    orgaoReguladorOuBase: "ANM / SIGBM (Brasil)",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "csn", "congonhas", "zona-urbana"],
  },
  {
    id: "BAR-BR-MARAVILHAS-3",
    nome: "Barragem Maravilhas III",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Aterro a Jusante e Linha de Centro",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Bacia do Rio das Velhas",
    alturaMetros: 90,
    volumeCapacidadeMm3: 108.0,
    operador: "Vale S.A.",
    classificacaoRiscoOuHazard: "Dano Potencial Alto (CRI/DPA - SIGBM)",
    statusOperacional: "em_operacao",
    anoConclusao: 2014,
    latitude: -20.2183,
    longitude: -43.8761,
    resumoCivico: "Principal complexo de disposição de rejeitos moderno da Vale no Quadrilátero Ferrífero.",
    orgaoReguladorOuBase: "ANM / SIGBM (Brasil)",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "vale", "itabirito", "rio-das-velhas"],
  },
  {
    id: "BAR-BR-HYDRO-ALUNORTE",
    nome: "Bacia de Depósito de Resíduos DRS-2 (Hydro Alunorte)",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Bacia de Depósito em Aterro Compactado",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Bacia do Rio Murucupi / Baía do Marajó",
    alturaMetros: 15,
    volumeCapacidadeMm3: 8.5,
    operador: "Norsk Hydro Alunorte",
    classificacaoRiscoOuHazard: "Dano Potencial Alto (Poluição Hídrica / SEMAS)",
    statusOperacional: "em_operacao",
    anoConclusao: 2016,
    latitude: -1.5422,
    longitude: -48.7183,
    resumoCivico: "Bacia de rejeitos de bauxita/alumina envolvida em denúncias de vazamento em Barcarena em 2018.",
    orgaoReguladorOuBase: "ANM / SEMAS Pará",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "bauxita", "norsk-hydro", "barcarena", "para"],
  },
  {
    id: "BAR-CA-MOUNT-POLLEY",
    nome: "Mount Polley Tailings Dam",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Enrocamento com Alteamentos Sucessivos",
    pais: "Canadá",
    continente: "América do Norte",
    rioOuBacia: "Bacia do Rio Fraser / Quesnel Lake",
    alturaMetros: 40,
    volumeCapacidadeMm3: 24.0,
    operador: "Imperial Metals",
    classificacaoRiscoOuHazard: "Rompida (Falha de Fundação Glaciolacustre)",
    statusOperacional: "rompida_historico",
    anoConclusao: 1997,
    latitude: 52.5489,
    longitude: -121.5978,
    resumoCivico: "Rompimento em 04/08/2014 liberou 24 Mm³ de água e rejeitos em lago glacial da Colúmbia Britânica.",
    orgaoReguladorOuBase: "Global Tailings Portal / BC MEMPR",
    linkFonteOficial: "https://tailing.grida.no/",
    tags: ["rejeitos", "canada", "imperial-metals", "rompimento", "quesnel-lake"],
  },
  {
    id: "BAR-PG-OK-TEDI",
    nome: "Ok Tedi Tailings Impoundment",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Enrocamento (Colapso durante Construção)",
    pais: "Papua-Nova Guiné",
    continente: "Oceania",
    rioOuBacia: "Bacia dos Rios Ok Tedi e Fly",
    alturaMetros: 50,
    volumeCapacidadeMm3: 60.0,
    operador: "Ok Tedi Mining Ltd (OTML)",
    classificacaoRiscoOuHazard: "Crítico / Despejo Direto em Rios",
    statusOperacional: "rompida_historico",
    anoConclusao: 1984,
    latitude: -5.2014,
    longitude: 141.1444,
    resumoCivico: "Colapso do projeto de contenção em 1984 levou ao despejo de 2 bilhões de toneladas no rio Fly.",
    orgaoReguladorOuBase: "Global Tailings Portal / UNEP",
    linkFonteOficial: "https://tailing.grida.no/",
    tags: ["rejeitos", "papua-nova-guine", "desastre-ambiental", "fly-river"],
  },
  {
    id: "BAR-RO-BAIA-MARE",
    nome: "Baia Mare Bozanta Dam",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Dique de Terra para Lixiviação de Cianeto",
    pais: "Romênia",
    continente: "Europa",
    rioOuBacia: "Bacia do Rio Tisza / Rio Danúbio",
    alturaMetros: 10,
    volumeCapacidadeMm3: 0.1,
    operador: "Aurul SA (Esmeralda Exploration / Remin)",
    classificacaoRiscoOuHazard: "Rompida (Desastre Transfronteiriço por Cianeto)",
    statusOperacional: "rompida_historico",
    anoConclusao: 1999,
    latitude: 47.6389,
    longitude: 23.4972,
    resumoCivico: "Rompimento em 30/01/2000 contaminou o rio Tisza e o Danúbio com 100 toneladas de cianeto.",
    orgaoReguladorOuBase: "Global Tailings Portal / UNEP",
    linkFonteOficial: "https://tailing.grida.no/",
    tags: ["rejeitos", "romenia", "cianeto", "danubio", "tisza", "rompimento"],
  },
  {
    id: "BAR-ES-AZNALCOLLAR",
    nome: "Balsa de Rejeitos de Aznalcóllar (Los Frailes)",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Enrocamento com Alteamentos",
    pais: "Espanha",
    continente: "Europa",
    rioOuBacia: "Rio Guadiamar / Bacia do Guadalquivir",
    alturaMetros: 28,
    volumeCapacidadeMm3: 15.0,
    operador: "Boliden Apirsa",
    classificacaoRiscoOuHazard: "Rompida (Ameaça ao Parque de Doñana)",
    statusOperacional: "rompida_historico",
    anoConclusao: 1978,
    latitude: 37.5133,
    longitude: -6.2625,
    resumoCivico: "Rompimento em 25/04/1998 vazou 5 Mm³ de lamas tóxicas até as margens do Parque Nacional de Doñana.",
    orgaoReguladorOuBase: "MITECO Espanha / ICOLD",
    linkFonteOficial: "https://www.miteco.gob.es/",
    tags: ["rejeitos", "espanha", "boliden", "donana", "guadiamar", "rompimento"],
  },
  {
    id: "BAR-IT-STAVA",
    nome: "Stava Fluorite Tailings Dams",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Alteamento a Montante em Cascata",
    pais: "Itália",
    continente: "Europa",
    rioOuBacia: "Rio Stava / Bacia do Rio Ádige",
    alturaMetros: 50,
    volumeCapacidadeMm3: 0.3,
    operador: "Prealpi Mineraria",
    classificacaoRiscoOuHazard: "Rompida (Catástrofe de Stava / 268 Mortos)",
    statusOperacional: "rompida_historico",
    anoConclusao: 1969,
    latitude: 46.3117,
    longitude: 11.5186,
    resumoCivico: "Duas barragens sobrepostas romperam em 19/07/1985 em Tesero, provocando 268 mortes.",
    orgaoReguladorOuBase: "Fondazione Stava 1985 / ICOLD",
    linkFonteOficial: "https://www.stava1985.it/",
    tags: ["rejeitos", "italia", "stava", "liquefacao", "catastrofe"],
  },
  {
    id: "BAR-ZA-MERRIESPRUIT",
    nome: "Merriespruit Tailings Dam 4",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Alteamento a Montante",
    pais: "África do Sul",
    continente: "África",
    rioOuBacia: "Rio Sand / Bacia do Rio Vaal",
    alturaMetros: 31,
    volumeCapacidadeMm3: 1.2,
    operador: "Harmony Gold",
    classificacaoRiscoOuHazard: "Rompida (Liquefação / 17 Mortos)",
    statusOperacional: "rompida_historico",
    anoConclusao: 1978,
    latitude: -28.0617,
    longitude: 26.8653,
    resumoCivico: "Rompimento por liquefação em 22/02/1994 soterrou parte da cidade de Virginia com lama de ouro.",
    orgaoReguladorOuBase: "DWS África do Sul / Global Tailings Portal",
    linkFonteOficial: "https://tailing.grida.no/",
    tags: ["rejeitos", "africa-do-sul", "ouro", "merriespruit", "rompimento"],
  },
  {
    id: "BAR-ZA-JAGERSFONTEIN",
    nome: "Jagersfontein Diamond Tailings Dam",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Aterro de Resíduos de Diamante",
    pais: "África do Sul",
    continente: "África",
    rioOuBacia: "Rio Riet / Bacia do Rio Orange",
    alturaMetros: 25,
    volumeCapacidadeMm3: 4.5,
    operador: "Jagersfontein Developments",
    classificacaoRiscoOuHazard: "Rompida (Rompimento em Setembro/2022)",
    statusOperacional: "rompida_historico",
    anoConclusao: 2011,
    latitude: -29.7633,
    longitude: 25.4317,
    resumoCivico: "Rompimento em 11/09/2022 destruiu dezenas de casas e contaminou cursos de água no Free State.",
    orgaoReguladorOuBase: "DWS África do Sul / Global Tailings Portal",
    linkFonteOficial: "https://tailing.grida.no/",
    tags: ["rejeitos", "africa-do-sul", "diamante", "rompimento", "2022"],
  },
  {
    id: "BAR-US-KINGSTON-ASH",
    nome: "Kingston Coal Ash Slurry Impoundment",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Dique de Terra para Cinzas Úmidas de Carvão",
    pais: "Estados Unidos",
    continente: "América do Norte",
    rioOuBacia: "Bacia do Rio Emory / Rio Clinch",
    alturaMetros: 18,
    volumeCapacidadeMm3: 4.1,
    operador: "Tennessee Valley Authority (TVA)",
    classificacaoRiscoOuHazard: "Rompida (Maior Desastre de Cinzas dos EUA)",
    statusOperacional: "rompida_historico",
    anoConclusao: 1954,
    latitude: 35.9125,
    longitude: -84.5167,
    resumoCivico: "Rompimento em 22/12/2008 derramou 4,1 Mm³ de lodo com metais pesados em rios do Tennessee.",
    orgaoReguladorOuBase: "US EPA / USACE NID",
    linkFonteOficial: "https://nid.sec.usace.army.mil/",
    tags: ["rejeitos", "eua", "carvao", "tva", "tennessee", "rompimento"],
  },
  {
    id: "BAR-AU-CADIA",
    nome: "Cadia Northern Tailings Facility",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Linha de Centro / Aterro Rochoso",
    pais: "Austrália",
    continente: "Oceania",
    rioOuBacia: "Bacia Murray-Darling / Cadiangullong Creek",
    alturaMetros: 42,
    volumeCapacidadeMm3: 28.0,
    operador: "Newcrest Mining (Newmont)",
    classificacaoRiscoOuHazard: "Alto Risco de Deformação / Em Reforma",
    statusOperacional: "desativada_descaracterizacao",
    anoConclusao: 1998,
    latitude: -33.4542,
    longitude: 148.9958,
    resumoCivico: "Colapso parcial de talude em 09/03/2018 gerou paralisação e plano emergencial de contenção.",
    orgaoReguladorOuBase: "NSW Resources Regulator / Global Tailings Portal",
    linkFonteOficial: "https://tailing.grida.no/",
    tags: ["rejeitos", "australia", "ouro", "cobre", "deformacao"],
  },
  {
    id: "BAR-FI-TALVIVAARA",
    nome: "Talvivaara Gypsum Pond (Terrafame)",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Bacia de Gesso e Resíduos Químicos",
    pais: "Finlândia",
    continente: "Europa",
    rioOuBacia: "Bacia de Oulujoki / Lagos de Sotkamo",
    alturaMetros: 12,
    volumeCapacidadeMm3: 4.0,
    operador: "Terrafame Ltd (antiga Talvivaara)",
    classificacaoRiscoOuHazard: "Alto Risco Químico / Histórico de Vazamentos",
    statusOperacional: "em_operacao",
    anoConclusao: 2008,
    latitude: 63.9725,
    longitude: 27.9861,
    resumoCivico: "Série de vazamentos em 2012-2013 liberou sulfatos, níquel e urânio em ecossistemas árticos protegidos.",
    orgaoReguladorOuBase: "SYKE / Tukes Finlândia",
    linkFonteOficial: "https://www.syke.fi/",
    tags: ["rejeitos", "finlandia", "niquel", "vazamento-quimico"],
  },
  {
    id: "BAR-CA-SULLIVAN",
    nome: "Sullivan Mine Tailings Complex",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Enrocamento Zonado com Drenagem Ácida",
    pais: "Canadá",
    continente: "América do Norte",
    rioOuBacia: "Mark Creek / Bacia do Kootenay",
    alturaMetros: 35,
    volumeCapacidadeMm3: 45.0,
    operador: "Teck Resources",
    classificacaoRiscoOuHazard: "Monitoramento Perpétuo / DPA Alto",
    statusOperacional: "desativada_descaracterizacao",
    anoConclusao: 1950,
    latitude: 49.7042,
    longitude: -115.9817,
    resumoCivico: "Centenária mina de chumbo e zinco sob perpétuo tratamento de drenagem ácida de rocha.",
    orgaoReguladorOuBase: "BC MEMPR / Global Tailings Portal",
    linkFonteOficial: "https://tailing.grida.no/",
    tags: ["rejeitos", "canada", "teck", "chumbo-zinco", "monitoramento-perpetuo"],
  },
  {
    id: "BAR-BR-FEIJAO-B6",
    nome: "Barragem B6 — Córrego do Feijão",
    tipoBarragem: "rejeitos_mineracao",
    tipoEstrutura: "Terra e Enrocamento",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Bacia do Rio Paraopeba",
    alturaMetros: 21,
    volumeCapacidadeMm3: 1.0,
    operador: "Vale S.A.",
    classificacaoRiscoOuHazard: "Soterrada no Rompimento da B1 (2019)",
    statusOperacional: "rompida_historico",
    anoConclusao: 1980,
    latitude: -20.1242,
    longitude: -44.1167,
    resumoCivico: "Estrutura de sedimentação destruída e soterrada pelo colapso da barragem B1 em Brumadinho.",
    orgaoReguladorOuBase: "ANM / SIGBM (Brasil)",
    linkFonteOficial: "https://app.anm.gov.br/SIGBM/Publico/GerenciarBarragem",
    tags: ["rejeitos", "brasil", "vale", "brumadinho", "soterrada"],
  },

  // ==========================================
  // HIDRELÉTRICAS E ENERGIA (HYDROPOWER)
  // ==========================================
  {
    id: "BAR-CN-THREE-GORGES",
    nome: "Barragem das Três Gargantas (Three Gorges)",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Gravidade em Concreto",
    pais: "China",
    continente: "Ásia",
    rioOuBacia: "Rio Yangtze (Chang Jiang)",
    alturaMetros: 181,
    volumeCapacidadeMm3: 39300.0,
    operador: "China Three Gorges Corporation (CTG)",
    classificacaoRiscoOuHazard: "Dano Potencial Extremo / Alto Controle de Cheias",
    statusOperacional: "em_operacao",
    anoConclusao: 2012,
    latitude: 30.8267,
    longitude: 111.0078,
    resumoCivico: "Maior usina hidrelétrica do planeta em capacidade instalada (22.500 MW) e controle de cheias.",
    orgaoReguladorOuBase: "ICOLD / CTG China",
    linkFonteOficial: "https://www.ctg.com.cn/",
    tags: ["hidreletrica", "china", "yangtze", "tres-gargantas", "megaobra"],
  },
  {
    id: "BAR-BR-PY-ITAIPU",
    nome: "Usina Hidrelétrica de Itaipu Binacional",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Gravidade de Concreto, Enrocamento e Contrafortes",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio Paraná (Bacia do Prata)",
    alturaMetros: 196,
    volumeCapacidadeMm3: 29000.0,
    operador: "Itaipu Binacional (Brasil / Paraguai)",
    classificacaoRiscoOuHazard: "Infraestrutura Crítica Nacional / DPA Alto",
    statusOperacional: "em_operacao",
    anoConclusao: 1984,
    latitude: -25.4086,
    longitude: -54.5889,
    resumoCivico: "Segunda maior geradora histórica global com 14.000 MW compartilhados entre Brasil e Paraguai.",
    orgaoReguladorOuBase: "ANA / ANEEL / ICOLD",
    linkFonteOficial: "https://www.itaipu.gov.br/",
    tags: ["hidreletrica", "brasil", "paraguai", "itaipu", "rio-parana"],
  },
  {
    id: "BAR-BR-BELO-MONTE",
    nome: "UHE Belo Monte (Sítio Pimental e Belo Monte)",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Terra e Enrocamento com Turbinas a Fio d'Água",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio Xingu / Bacia Amazônica",
    alturaMetros: 35,
    volumeCapacidadeMm3: 2069.0,
    operador: "Norte Energia S.A.",
    classificacaoRiscoOuHazard: "Dano Potencial Alto / Monitoramento Socioambiental",
    statusOperacional: "em_operacao",
    anoConclusao: 2019,
    latitude: -3.1258,
    longitude: -51.7778,
    resumoCivico: "Maior usina 100% brasileira com 11.233 MW, foco de amplo debate com povos indígenas da Volta Grande.",
    orgaoReguladorOuBase: "ANA / ANEEL / IBAMA",
    linkFonteOficial: "https://www.norteenergiasa.com.br/",
    tags: ["hidreletrica", "brasil", "xingu", "amazonia", "belo-monte", "povos-indigenas"],
  },
  {
    id: "BAR-BR-TUCURUI",
    nome: "UHE Tucuruí",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Terra, Enrocamento e Concreto de Gravidade",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio Tocantins / Bacia Tocantins-Araguaia",
    alturaMetros: 78,
    volumeCapacidadeMm3: 50300.0,
    operador: "Eletrobras Eletronorte",
    classificacaoRiscoOuHazard: "Dano Potencial Alto (CRI/DPA - ANA)",
    statusOperacional: "em_operacao",
    anoConclusao: 1984,
    latitude: -3.8328,
    longitude: -49.6464,
    resumoCivico: "Potência de 8.370 MW gerando energia para indústria eletrointensiva e o Sistema Interligado Nacional.",
    orgaoReguladorOuBase: "ANA / ANEEL / ICOLD",
    linkFonteOficial: "https://www.eletrobras.com/",
    tags: ["hidreletrica", "brasil", "tucurui", "rio-tocantins", "eletrobras"],
  },
  {
    id: "BAR-US-HOOVER",
    nome: "Hoover Dam",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Arco-Gravidade de Concreto",
    pais: "Estados Unidos",
    continente: "América do Norte",
    rioOuBacia: "Rio Colorado / Lake Mead",
    alturaMetros: 221,
    volumeCapacidadeMm3: 35200.0,
    operador: "US Bureau of Reclamation (USBR)",
    classificacaoRiscoOuHazard: "High Hazard Potential (USACE NID)",
    statusOperacional: "em_operacao",
    anoConclusao: 1936,
    latitude: 36.0156,
    longitude: -114.7378,
    resumoCivico: "Ícone da engenharia de 1936 represa o Lake Mead para regulação hídrica do sudoeste dos EUA.",
    orgaoReguladorOuBase: "USBR / USACE NID",
    linkFonteOficial: "https://www.usbr.gov/lc/hooverdam/",
    tags: ["hidreletrica", "eua", "colorado-river", "hoover-dam", "lake-mead"],
  },
  {
    id: "BAR-US-GRAND-COULEE",
    nome: "Grand Coulee Dam",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Gravidade em Concreto Maciço",
    pais: "Estados Unidos",
    continente: "América do Norte",
    rioOuBacia: "Rio Columbia / Franklin D. Roosevelt Lake",
    alturaMetros: 168,
    volumeCapacidadeMm3: 11900.0,
    operador: "US Bureau of Reclamation (USBR)",
    classificacaoRiscoOuHazard: "High Hazard Potential (USACE NID)",
    statusOperacional: "em_operacao",
    anoConclusao: 1942,
    latitude: 47.9575,
    longitude: -118.9817,
    resumoCivico: "Maior usina hidrelétrica dos Estados Unidos com 6.809 MW instalados no noroeste do Pacífico.",
    orgaoReguladorOuBase: "USBR / USACE NID",
    linkFonteOficial: "https://www.usbr.gov/pn/grandcoulee/",
    tags: ["hidreletrica", "eua", "columbia-river", "grand-coulee"],
  },
  {
    id: "BAR-VE-GURI",
    nome: "Central Hidroeléctrica Simón Bolívar (Represa de Guri)",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Mista de Gravidade de Concreto e Terra",
    pais: "Venezuela",
    continente: "América do Sul",
    rioOuBacia: "Rio Caroní / Bacia do Orinoco",
    alturaMetros: 162,
    volumeCapacidadeMm3: 135000.0,
    operador: "Corpoelec (Venezuela)",
    classificacaoRiscoOuHazard: "Infraestrutura Crítica Nacional / DPA Alto",
    statusOperacional: "em_operacao",
    anoConclusao: 1986,
    latitude: 7.7667,
    longitude: -62.9989,
    resumoCivico: "Capacidade de 10.235 MW abastecendo grande parte da rede elétrica nacional venezuelana.",
    orgaoReguladorOuBase: "ICOLD / MPPEE Venezuela",
    linkFonteOficial: "http://www.corpoelec.gob.ve/",
    tags: ["hidreletrica", "venezuela", "guri", "rio-caroni"],
  },
  {
    id: "BAR-RU-SAYANO-SHUSHENSKAYA",
    nome: "Sayano-Shushenskaya Hydroelectric Plant",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Arco-Gravidade de Concreto",
    pais: "Rússia",
    continente: "Europa",
    rioOuBacia: "Rio Yenisei / Sibéria",
    alturaMetros: 242,
    volumeCapacidadeMm3: 31300.0,
    operador: "RusHydro",
    classificacaoRiscoOuHazard: "Alto Risco Sísmico / Recuperada de Acidente",
    statusOperacional: "em_operacao",
    anoConclusao: 1985,
    latitude: 52.8272,
    longitude: 91.3686,
    resumoCivico: "Com 6.400 MW, é a maior usina da Rússia; sofreu grave acidente na casa de força em 2009 com 75 mortos.",
    orgaoReguladorOuBase: "RusHydro / ICOLD",
    linkFonteOficial: "http://www.rushydro.ru/",
    tags: ["hidreletrica", "russia", "siberia", "yenisei", "acidente-2009"],
  },
  {
    id: "BAR-CN-XILUODU",
    nome: "Xiluodu Dam",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Arco Duplo de Concreto",
    pais: "China",
    continente: "Ásia",
    rioOuBacia: "Rio Jinsha / Bacia do Yangtze",
    alturaMetros: 285,
    volumeCapacidadeMm3: 12670.0,
    operador: "China Three Gorges Corporation (CTG)",
    classificacaoRiscoOuHazard: "Dano Potencial Extremo / Alto Risco Sísmico",
    statusOperacional: "em_operacao",
    anoConclusao: 2013,
    latitude: 28.2589,
    longitude: 103.6481,
    resumoCivico: "Terceira maior geradora do mundo com 13.860 MW e arco de concreto de 285 metros de altura.",
    orgaoReguladorOuBase: "ICOLD / CTG China",
    linkFonteOficial: "https://www.ctg.com.cn/",
    tags: ["hidreletrica", "china", "jinsha", "xiluodu"],
  },
  {
    id: "BAR-CN-BAIHETAN",
    nome: "Baihetan Dam",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Arco Duplo de Concreto",
    pais: "China",
    continente: "Ásia",
    rioOuBacia: "Rio Jinsha / Alto Yangtze",
    alturaMetros: 289,
    volumeCapacidadeMm3: 20630.0,
    operador: "China Three Gorges Corporation (CTG)",
    classificacaoRiscoOuHazard: "Dano Potencial Extremo / Tecnologia Ultra-Alta",
    statusOperacional: "em_operacao",
    anoConclusao: 2022,
    latitude: 27.2247,
    longitude: 102.9017,
    resumoCivico: "Complexo de 16.000 MW com 16 geradores de 1.000 MW cada, segundo maior do mundo.",
    orgaoReguladorOuBase: "ICOLD / CTG China",
    linkFonteOficial: "https://www.ctg.com.cn/",
    tags: ["hidreletrica", "china", "jinsha", "baihetan", "16000mw"],
  },
  {
    id: "BAR-BR-ILHA-SOLTEIRA",
    nome: "UHE Ilha Solteira",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Mista de Terra, Enrocamento e Concreto",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio Paraná (São Paulo / MS)",
    alturaMetros: 74,
    volumeCapacidadeMm3: 21200.0,
    operador: "CTG Brasil",
    classificacaoRiscoOuHazard: "Dano Potencial Alto (CRI/DPA - ANA)",
    statusOperacional: "em_operacao",
    anoConclusao: 1973,
    latitude: -20.3831,
    longitude: -51.3639,
    resumoCivico: "Capacidade de 3.444 MW na calha principal do Rio Paraná conectada ao canal Pereira Barreto.",
    orgaoReguladorOuBase: "ANA / ANEEL",
    linkFonteOficial: "https://www.ctgbr.com.br/",
    tags: ["hidreletrica", "brasil", "ilha-solteira", "rio-parana"],
  },
  {
    id: "BAR-BR-JIRAU",
    nome: "UHE Jirau",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Enrocamento com Núcleo Asfáltico e Vertedouro",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio Madeira / Bacia Amazônica",
    alturaMetros: 63,
    volumeCapacidadeMm3: 2747.0,
    operador: "Energia Sustentável do Brasil (ESBR / Engie)",
    classificacaoRiscoOuHazard: "Dano Potencial Alto / Monitoramento de Sedimentos",
    statusOperacional: "em_operacao",
    anoConclusao: 2016,
    latitude: -9.2647,
    longitude: -64.6467,
    resumoCivico: "Usina a fio d'água de 3.750 MW operando com 50 turbinas bulbo no complexo do Rio Madeira.",
    orgaoReguladorOuBase: "ANA / ANEEL / IBAMA",
    linkFonteOficial: "https://www.energiasustentaveldobrasil.com.br/",
    tags: ["hidreletrica", "brasil", "jirau", "rio-madeira", "amazonia"],
  },
  {
    id: "BAR-BR-SANTO-ANTONIO",
    nome: "UHE Santo Antônio",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Concreto Compactado a Rolo e Enrocamento",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio Madeira / Rondônia",
    alturaMetros: 60,
    volumeCapacidadeMm3: 2810.0,
    operador: "Santo Antônio Energia (Eletrobras Furnas)",
    classificacaoRiscoOuHazard: "Dano Potencial Alto / Adjacente a Porto Velho",
    statusOperacional: "em_operacao",
    anoConclusao: 2012,
    latitude: -8.8028,
    longitude: -63.9514,
    resumoCivico: "Capacidade de 3.568 MW próxima ao perímetro urbano de Porto Velho sob rigoroso controle de cheias.",
    orgaoReguladorOuBase: "ANA / ANEEL / IBAMA",
    linkFonteOficial: "https://www.santoantonioenergia.com.br/",
    tags: ["hidreletrica", "brasil", "santo-antonio", "rio-madeira", "porto-velho"],
  },
  {
    id: "BAR-CA-CHURCHILL-FALLS",
    nome: "Churchill Falls Generating Station",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Complexo de 88 Diques e Aterros em Enrocamento",
    pais: "Canadá",
    continente: "América do Norte",
    rioOuBacia: "Churchill River / Smallwood Reservoir",
    alturaMetros: 36,
    volumeCapacidadeMm3: 32640.0,
    operador: "Churchill Falls (Labrador) Corp / Nalcor",
    classificacaoRiscoOuHazard: "High Consequence (CDA Guidelines)",
    statusOperacional: "em_operacao",
    anoConclusao: 1974,
    latitude: 53.5317,
    longitude: -64.3167,
    resumoCivico: "Casa de força subterrânea de 5.428 MW alimentada pelo imenso reservatório Smallwood.",
    orgaoReguladorOuBase: "CDA / ICOLD / Nalcor",
    linkFonteOficial: "https://www.hydro.mb.ca/",
    tags: ["hidreletrica", "canada", "churchill-river", "labrador"],
  },
  {
    id: "BAR-CA-ROBERT-BOURASSA",
    nome: "Robert-Bourassa Dam (La Grande-2)",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Enrocamento com Núcleo Morênico",
    pais: "Canadá",
    continente: "América do Norte",
    rioOuBacia: "La Grande River / Bacia da Baía de James",
    alturaMetros: 162,
    volumeCapacidadeMm3: 61700.0,
    operador: "Hydro-Québec",
    classificacaoRiscoOuHazard: "Infraestrutura Estratégica Norte-Americana",
    statusOperacional: "em_operacao",
    anoConclusao: 1981,
    latitude: 53.7853,
    longitude: -77.4525,
    resumoCivico: "Maior usina subterrânea da América do Norte com 5.616 MW instalados no norte do Québec.",
    orgaoReguladorOuBase: "Hydro-Québec / CDA",
    linkFonteOficial: "https://www.hydroquebec.com/",
    tags: ["hidreletrica", "canada", "hydro-quebec", "baia-de-james"],
  },
  {
    id: "BAR-CA-DANIEL-JOHNSON",
    nome: "Daniel-Johnson Dam (Manic-5)",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Múltiplos Arcos e Contrafortes em Concreto",
    pais: "Canadá",
    continente: "América do Norte",
    rioOuBacia: "Manicouagan River / Cratera Manicouagan",
    alturaMetros: 214,
    volumeCapacidadeMm3: 141800.0,
    operador: "Hydro-Québec",
    classificacaoRiscoOuHazard: "High Consequence (CDA / ICOLD)",
    statusOperacional: "em_operacao",
    anoConclusao: 1968,
    latitude: 50.6406,
    longitude: -68.7236,
    resumoCivico: "A mais alta barragem de arcos múltiplos do mundo, represando o colossal olho de Manicouagan.",
    orgaoReguladorOuBase: "Hydro-Québec / ICOLD",
    linkFonteOficial: "https://www.hydroquebec.com/",
    tags: ["hidreletrica", "canada", "manicouagan", "arcos-multiplos"],
  },
  {
    id: "BAR-CH-GRANDE-DIXENCE",
    nome: "Barrage de la Grande Dixence",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Gravidade em Concreto Maciço",
    pais: "Suíça",
    continente: "Europa",
    rioOuBacia: "Dixence / Bacia do Ródano (Alpes Valaisanos)",
    alturaMetros: 285,
    volumeCapacidadeMm3: 400.0,
    operador: "Grande Dixence SA",
    classificacaoRiscoOuHazard: "Alto Risco Alpino / Monitoramento Sísmico",
    statusOperacional: "em_operacao",
    anoConclusao: 1961,
    latitude: 46.0806,
    longitude: 7.4042,
    resumoCivico: "Barragem de gravidade mais alta do planeta (285m), captando degelo de 35 geleiras nos Alpes suíços.",
    orgaoReguladorOuBase: "SFOE Suíça / ICOLD",
    linkFonteOficial: "https://www.grande-dixence.ch/",
    tags: ["hidreletrica", "suica", "alpes", "grande-dixence", "recorde-altura"],
  },
  {
    id: "BAR-TJ-NUREK",
    nome: "Nurek Dam",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Terra e Enrocamento com Núcleo Central de Argila",
    pais: "Tajiquistão",
    continente: "Ásia",
    rioOuBacia: "Rio Vakhsh / Bacia do Amu Dária",
    alturaMetros: 300,
    volumeCapacidadeMm3: 10500.0,
    operador: "Barki Tojik (Tajiquistão)",
    classificacaoRiscoOuHazard: "Alto Risco Sísmico (Cordilheira Pamir)",
    statusOperacional: "em_operacao",
    anoConclusao: 1980,
    latitude: 38.3714,
    longitude: 69.3478,
    resumoCivico: "Uma das mais altas barragens de aterro do mundo com 300 metros de altura e 3.015 MW de energia.",
    orgaoReguladorOuBase: "ICOLD / World Bank",
    linkFonteOficial: "https://www.worldbank.org/",
    tags: ["hidreletrica", "tajiquistao", "vakhsh", "nurek", "300m"],
  },
  {
    id: "BAR-TJ-ROGUN",
    nome: "Rogun Dam",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Enrocamento com Núcleo de Argila",
    pais: "Tajiquistão",
    continente: "Ásia",
    rioOuBacia: "Rio Vakhsh / Cordilheira Pamir",
    alturaMetros: 335,
    volumeCapacidadeMm3: 13300.0,
    operador: "Rogun HPP OJSC / Webuild",
    classificacaoRiscoOuHazard: "Alto Risco Sísmico e Geopolítico / Em Obras",
    statusOperacional: "em_construcao",
    anoConclusao: 2028,
    latitude: 38.6833,
    longitude: 69.8833,
    resumoCivico: "Megaobra em construção projetada para ser a mais alta do planeta (335 metros) e gerar 3.600 MW.",
    orgaoReguladorOuBase: "ICOLD / World Bank",
    linkFonteOficial: "https://www.worldbank.org/",
    tags: ["hidreletrica", "tajiquistao", "rogun", "recorde-mundial", "construcao"],
  },
  {
    id: "BAR-ZM-ZW-KARIBA",
    nome: "Kariba Dam",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Arco de Concreto Duplo",
    pais: "Zâmbia",
    continente: "África",
    rioOuBacia: "Rio Zambeze (Fronteira Zâmbia / Zimbábue)",
    alturaMetros: 128,
    volumeCapacidadeMm3: 180600.0,
    operador: "Zambezi River Authority (ZRA)",
    classificacaoRiscoOuHazard: "Alto Risco de Erosão na Fundação / Em Reforma",
    statusOperacional: "em_operacao",
    anoConclusao: 1959,
    latitude: -16.5217,
    longitude: 28.7619,
    resumoCivico: "Represa o maior reservatório artificial em volume de água do planeta, sob obras de reforço no dissipador.",
    orgaoReguladorOuBase: "ZRA / ICOLD / World Bank",
    linkFonteOficial: "https://www.zambezira.org/",
    tags: ["hidreletrica", "zambia", "zimbabue", "zambeze", "kariba", "maior-volume"],
  },
  {
    id: "BAR-EG-ASWAN-HIGH",
    nome: "Aswan High Dam (Represa Alta de Assuã)",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Enrocamento com Núcleo Argiloso e Injeções",
    pais: "Egito",
    continente: "África",
    rioOuBacia: "Rio Nilo / Lago Nasser",
    alturaMetros: 111,
    volumeCapacidadeMm3: 132000.0,
    operador: "Egyptian Electricity Holding Company",
    classificacaoRiscoOuHazard: "Segurança Nacional / Controle Histórico do Nilo",
    statusOperacional: "em_operacao",
    anoConclusao: 1970,
    latitude: 23.9700,
    longitude: 32.8800,
    resumoCivico: "Regula as cheias do Nilo, irriga o Egito e fornece 2.100 MW a partir do colossal Lago Nasser.",
    orgaoReguladorOuBase: "MWRI Egito / ICOLD",
    linkFonteOficial: "https://www.mwri.gov.eg/",
    tags: ["hidreletrica", "egito", "nilo", "assua", "lago-nasser"],
  },
  {
    id: "BAR-MZ-CAHORA-BASSA",
    nome: "Barragem de Cahora Bassa",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Arco de Concreto de Dupla Curvatura",
    pais: "Moçambique",
    continente: "África",
    rioOuBacia: "Rio Zambeze / Província de Tete",
    alturaMetros: 171,
    volumeCapacidadeMm3: 55800.0,
    operador: "Hidroeléctrica de Cahora Bassa (HCB)",
    classificacaoRiscoOuHazard: "Infraestrutura Crítica Regional / DPA Alto",
    statusOperacional: "em_operacao",
    anoConclusao: 1974,
    latitude: -15.5833,
    longitude: 32.7000,
    resumoCivico: "Quarta maior represa da África com 2.075 MW alimentando Moçambique, África do Sul e Zimbábue.",
    orgaoReguladorOuBase: "HCB / ICOLD",
    linkFonteOficial: "https://www.hcb.co.mz/",
    tags: ["hidreletrica", "mocambique", "zambeze", "cahora-bassa"],
  },
  {
    id: "BAR-AR-PY-YACYRETA",
    nome: "Represa Hidroeléctrica de Yacyretá",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Aterro de Terra e Enrocamento com Concreto",
    pais: "Argentina",
    continente: "América do Sul",
    rioOuBacia: "Rio Paraná (Fronteira Argentina / Paraguai)",
    alturaMetros: 43,
    volumeCapacidadeMm3: 21000.0,
    operador: "Entidad Binacional Yacyretá (EBY)",
    classificacaoRiscoOuHazard: "Infraestrutura Crítica Binacional",
    statusOperacional: "em_operacao",
    anoConclusao: 1994,
    latitude: -27.4811,
    longitude: -56.7389,
    resumoCivico: "Complexo com 67 km de coroamento gerando 3.200 MW entre Ituzaingó e Ayolas.",
    orgaoReguladorOuBase: "EBY / ICOLD",
    linkFonteOficial: "https://www.yacyreta.org.ar/",
    tags: ["hidreletrica", "argentina", "paraguai", "rio-parana", "yacyreta"],
  },
  {
    id: "BAR-BR-SOBRADINHO",
    nome: "UHE Sobradinho",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Terra e Enrocamento com Vertedouro em Concreto",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio São Francisco (Bahia)",
    alturaMetros: 41,
    volumeCapacidadeMm3: 34116.0,
    operador: "CHESF / Eletrobras",
    classificacaoRiscoOuHazard: "Dano Potencial Alto / Pulmão Hídrico do Nordeste",
    statusOperacional: "em_operacao",
    anoConclusao: 1979,
    latitude: -9.4319,
    longitude: -40.8267,
    resumoCivico: "Maior lago artificial do Brasil em área (4.214 km²), regulador essencial do Velho Chico e 1.050 MW.",
    orgaoReguladorOuBase: "ANA / ANEEL / CHESF",
    linkFonteOficial: "https://www.chesf.com.br/",
    tags: ["hidreletrica", "brasil", "sobradinho", "rio-sao-francisco", "chesf"],
  },
  {
    id: "BAR-BR-FURNAS",
    nome: "UHE Furnas",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Enrocamento com Núcleo Central de Argila",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio Grande / Bacia do Paraná (Minas Gerais)",
    alturaMetros: 127,
    volumeCapacidadeMm3: 22950.0,
    operador: "Furnas Centrais Elétricas / Eletrobras",
    classificacaoRiscoOuHazard: "Dano Potencial Alto (CRI/DPA - ANA)",
    statusOperacional: "em_operacao",
    anoConclusao: 1963,
    latitude: -20.6694,
    longitude: -46.3194,
    resumoCivico: "O 'Mar de Minas' com 1.216 MW e papel crucial como caixa d'água reguladora do Sudeste.",
    orgaoReguladorOuBase: "ANA / ANEEL / Furnas",
    linkFonteOficial: "https://www.furnas.com.br/",
    tags: ["hidreletrica", "brasil", "minas-gerais", "furnas", "rio-grande"],
  },

  // ==========================================
  // ABASTECIMENTO, CONTROLE DE CHEIAS E MULTIUSO
  // ==========================================
  {
    id: "BAR-US-OROVILLE",
    nome: "Oroville Dam",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Aterro de Terra e Enrocamento Zonado",
    pais: "Estados Unidos",
    continente: "América do Norte",
    rioOuBacia: "Feather River / Bacia do Sacramento (Califórnia)",
    alturaMetros: 235,
    volumeCapacidadeMm3: 4364.0,
    operador: "California Department of Water Resources (DWR)",
    classificacaoRiscoOuHazard: "High Hazard Potential / Evacuação de 180.000 em 2017",
    statusOperacional: "em_operacao",
    anoConclusao: 1968,
    latitude: 39.5392,
    longitude: -121.4886,
    resumoCivico: "Barragem mais alta dos EUA (235m); vertedouro sofreu erosão crítica em 2017 forçando evacuação em massa.",
    orgaoReguladorOuBase: "USACE NID / California DWR",
    linkFonteOficial: "https://water.ca.gov/Programs/State-Water-Project/SWP-Facilities/Oroville",
    tags: ["abastecimento", "eua", "california", "oroville", "vertedouro", "evacuacao"],
  },
  {
    id: "BAR-PK-TARBELA",
    nome: "Tarbela Dam",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Terra e Enrocamento Zonado com Núcleo Central",
    pais: "Paquistão",
    continente: "Ásia",
    rioOuBacia: "Rio Indo (Khyber Pakhtunkhwa)",
    alturaMetros: 143,
    volumeCapacidadeMm3: 13690.0,
    operador: "WAPDA (Paquistão)",
    classificacaoRiscoOuHazard: "Dano Potencial Extremo / Alto Assoreamento",
    statusOperacional: "em_operacao",
    anoConclusao: 1976,
    latitude: 34.0883,
    longitude: 72.6978,
    resumoCivico: "Maior barragem de aterro em volume de material da história (106 Mm³ no aterro) para irrigação e 4.888 MW.",
    orgaoReguladorOuBase: "WAPDA / ICOLD",
    linkFonteOficial: "http://www.wapda.gov.pk/",
    tags: ["abastecimento", "paquistao", "rio-indo", "tarbela", "irrigacao"],
  },
  {
    id: "BAR-US-GLEN-CANYON",
    nome: "Glen Canyon Dam",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Arco de Concreto Maciço",
    pais: "Estados Unidos",
    continente: "América do Norte",
    rioOuBacia: "Rio Colorado / Lake Powell (Arizona)",
    alturaMetros: 216,
    volumeCapacidadeMm3: 33300.0,
    operador: "US Bureau of Reclamation (USBR)",
    classificacaoRiscoOuHazard: "High Hazard Potential / Severa Crise Hídrica",
    statusOperacional: "em_operacao",
    anoConclusao: 1966,
    latitude: 36.9367,
    longitude: -111.4842,
    resumoCivico: "Represa o Lake Powell sob severo estresse hídrico pela megasseca histórica da Bacia do Colorado.",
    orgaoReguladorOuBase: "USBR / USACE NID",
    linkFonteOficial: "https://www.usbr.gov/uc/rm/crsp/gc/",
    tags: ["abastecimento", "eua", "colorado-river", "lake-powell", "seca"],
  },
  {
    id: "BAR-TR-ATATURK",
    nome: "Atatürk Dam",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Enrocamento com Núcleo Central de Argila",
    pais: "Turquia",
    continente: "Ásia",
    rioOuBacia: "Rio Eufrates (Anatólia)",
    alturaMetros: 169,
    volumeCapacidadeMm3: 48700.0,
    operador: "DSI State Hydraulic Works (Turquia)",
    classificacaoRiscoOuHazard: "Alto Impacto Geopolítico e Transfronteiriço",
    statusOperacional: "em_operacao",
    anoConclusao: 1992,
    latitude: 37.4789,
    longitude: 38.3189,
    resumoCivico: "Coração do Projeto GAP da Turquia irrigando 1,7 milhão de hectares e gerando 2.400 MW no Eufrates.",
    orgaoReguladorOuBase: "DSI Turquia / ICOLD",
    linkFonteOficial: "https://www.dsi.gov.tr/",
    tags: ["abastecimento", "turquia", "eufrates", "irrigacao", "gap"],
  },
  {
    id: "BAR-IT-VAJONT",
    nome: "Diga del Vajont (Barragem de Vajont)",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Arco de Concreto de Dupla Curvatura",
    pais: "Itália",
    continente: "Europa",
    rioOuBacia: "Rio Vajont / Bacia do Piave (Dolomitas)",
    alturaMetros: 262,
    volumeCapacidadeMm3: 168.0,
    operador: "SADE / Enel (Itália)",
    classificacaoRiscoOuHazard: "Desativada (Megadeslizamento / 1.917 Mortos)",
    statusOperacional: "desativada_descaracterizacao",
    anoConclusao: 1960,
    latitude: 46.2672,
    longitude: 12.3278,
    resumoCivico: "Em 09/10/1963 o Monte Toc desabou no lago criando onda de 250m que destruiu Longarone; a barragem ficou intacta.",
    orgaoReguladorOuBase: "Fondazione Vajont / ICOLD",
    linkFonteOficial: "https://www.fondazionevajont.org/",
    tags: ["desastre", "italia", "vajont", "deslizamento", "longarone"],
  },
  {
    id: "BAR-FR-MALPASSET",
    nome: "Barrage de Malpasset",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Arco Ultrafino de Concreto",
    pais: "França",
    continente: "Europa",
    rioOuBacia: "Rio Reyran / Côte d'Azur",
    alturaMetros: 66,
    volumeCapacidadeMm3: 48.0,
    operador: "Département du Var",
    classificacaoRiscoOuHazard: "Rompida (Falha Geológica / 423 Mortos)",
    statusOperacional: "rompida_historico",
    anoConclusao: 1954,
    latitude: 43.5133,
    longitude: 6.7578,
    resumoCivico: "Rompimento repentino em 02/12/1959 por foliação da rocha destruiu Fréjus matando 423 pessoas.",
    orgaoReguladorOuBase: "CFBR França / ICOLD",
    linkFonteOficial: "https://www.barrages-cfbr.eu/",
    tags: ["abastecimento", "franca", "malpasset", "frejus", "rompimento"],
  },
  {
    id: "BAR-US-TETON",
    nome: "Teton Dam",
    tipoBarragem: "controle_cheias",
    tipoEstrutura: "Aterro de Terra Zonal",
    pais: "Estados Unidos",
    continente: "América do Norte",
    rioOuBacia: "Teton River / Bacia do Snake River (Idaho)",
    alturaMetros: 93,
    volumeCapacidadeMm3: 355.0,
    operador: "US Bureau of Reclamation (USBR)",
    classificacaoRiscoOuHazard: "Rompida (Falha por Piping no Primeiro Enchimento)",
    statusOperacional: "rompida_historico",
    anoConclusao: 1975,
    latitude: 43.9097,
    longitude: -111.5386,
    resumoCivico: "Rompimento em 05/06/1976 durante o primeiro enchimento causou 11 mortes e reformulou normas nos EUA.",
    orgaoReguladorOuBase: "USBR / USACE NID",
    linkFonteOficial: "https://www.usbr.gov/history/teton.html",
    tags: ["controle_cheias", "eua", "idaho", "teton-dam", "piping", "rompimento"],
  },
  {
    id: "BAR-CN-BANQIAO",
    nome: "Banqiao Dam (Represa de Banqiao)",
    tipoBarragem: "controle_cheias",
    tipoEstrutura: "Aterro de Terra e Argila (Reconstruída em Concreto/Terra)",
    pais: "China",
    continente: "Ásia",
    rioOuBacia: "Rio Ru / Bacia do Rio Huai (Henan)",
    alturaMetros: 50,
    volumeCapacidadeMm3: 492.0,
    operador: "Ministério de Recursos Hídricos da China (MWR)",
    classificacaoRiscoOuHazard: "Rompida em 1975 (Maior Tragédia de Barragens da História)",
    statusOperacional: "em_operacao",
    anoConclusao: 1993,
    latitude: 32.9817,
    longitude: 113.5628,
    resumoCivico: "Colapso em 08/08/1975 sob o Tufão Nina causou mais de 26.000 mortes diretas; foi reconstruída em 1993.",
    orgaoReguladorOuBase: "MWR China / ICOLD",
    linkFonteOficial: "http://www.mwr.gov.cn/",
    tags: ["controle_cheias", "china", "banqiao", "tufao-nina", "catastrofe-1975"],
  },
  {
    id: "BAR-BR-CANTAREIRA-JAGUARI",
    nome: "Represa Jaguari-Jacareí (Sistema Cantareira)",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Aterro de Terra e Enrocamento",
    pais: "Brasil",
    continente: "América do Sul",
    rioOuBacia: "Rio Jaguari / Bacia PCJ (São Paulo / MG)",
    alturaMetros: 63,
    volumeCapacidadeMm3: 1047.0,
    operador: "SABESP (São Paulo)",
    classificacaoRiscoOuHazard: "Dano Potencial Alto / Abastecimento de 7+ Milhões",
    statusOperacional: "em_operacao",
    anoConclusao: 1974,
    latitude: -22.9067,
    longitude: -46.4258,
    resumoCivico: "Principal reservatório do Sistema Cantareira garantindo segurança hídrica da Grande São Paulo.",
    orgaoReguladorOuBase: "ANA / DAEE SP / SABESP",
    linkFonteOficial: "https://www.sabesp.com.br/",
    tags: ["abastecimento", "brasil", "cantareira", "sao-paulo", "sabesp", "seguranca-hidrica"],
  },
  {
    id: "BAR-PT-ALQUEVA",
    nome: "Barragem de Alqueva",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Arco-Gravidade em Concreto",
    pais: "Portugal",
    continente: "Europa",
    rioOuBacia: "Rio Guadiana (Alentejo)",
    alturaMetros: 96,
    volumeCapacidadeMm3: 4150.0,
    operador: "EDIA (Portugal)",
    classificacaoRiscoOuHazard: "Infraestrutura Crítica Nacional / DPA Alto",
    statusOperacional: "em_operacao",
    anoConclusao: 2002,
    latitude: 38.1969,
    longitude: -7.4958,
    resumoCivico: "Maior lago artificial da Europa Ocidental com 250 km² garantindo irrigação agrícola e 520 MW.",
    orgaoReguladorOuBase: "EDIA / APA Portugal / ICOLD",
    linkFonteOficial: "https://www.edia.pt/",
    tags: ["abastecimento", "portugal", "alqueva", "guadiana", "alentejo"],
  },
  {
    id: "BAR-AU-GLENMAGGIE",
    nome: "Glenmaggie Dam",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Gravidade em Concreto com Contrafortes e Comportas",
    pais: "Austrália",
    continente: "Oceania",
    rioOuBacia: "Macalister River / Bacia de Gippsland (Victoria)",
    alturaMetros: 37,
    volumeCapacidadeMm3: 177.0,
    operador: "Southern Rural Water (Austrália)",
    classificacaoRiscoOuHazard: "High Hazard (ANCOLD Guidelines)",
    statusOperacional: "em_operacao",
    anoConclusao: 1929,
    latitude: -37.8986,
    longitude: 146.7583,
    resumoCivico: "Infraestrutura essencial para o Distrito de Irrigação de Macalister com 14 comportas radiais.",
    orgaoReguladorOuBase: "Southern Rural Water / ANCOLD",
    linkFonteOficial: "https://www.srw.com.au/",
    tags: ["abastecimento", "australia", "victoria", "glenmaggie", "irrigacao"],
  },
  {
    id: "BAR-IN-TEHRI",
    nome: "Tehri Dam",
    tipoBarragem: "hidreletrica",
    tipoEstrutura: "Enrocamento e Terra com Núcleo Impermeável",
    pais: "Índia",
    continente: "Ásia",
    rioOuBacia: "Rio Bhagirathi / Bacia do Ganges (Himalaia)",
    alturaMetros: 260,
    volumeCapacidadeMm3: 4000.0,
    operador: "THDC India Ltd",
    classificacaoRiscoOuHazard: "Extremo Risco Sísmico (Falha do Himalaia) / DPA Alto",
    statusOperacional: "em_operacao",
    anoConclusao: 2006,
    latitude: 30.3789,
    longitude: 78.4806,
    resumoCivico: "Barragem mais alta da Índia (260m) em área de alta sismicidade fornecendo 2.400 MW e água para Déli.",
    orgaoReguladorOuBase: "CEA Índia / ICOLD",
    linkFonteOficial: "https://thdc.co.in/",
    tags: ["hidreletrica", "india", "ganges", "himalaia", "tehri", "sismico"],
  },
  {
    id: "BAR-IN-SARDAR-SAROVAR",
    nome: "Sardar Sarovar Dam",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Gravidade em Concreto Maciço",
    pais: "Índia",
    continente: "Ásia",
    rioOuBacia: "Rio Narmada (Gujarat)",
    alturaMetros: 163,
    volumeCapacidadeMm3: 9500.0,
    operador: "Sardar Sarovar Narmada Nigam Ltd (SSNNL)",
    classificacaoRiscoOuHazard: "Alto Impacto Social e Deslocamento Humano",
    statusOperacional: "em_operacao",
    anoConclusao: 2017,
    latitude: 21.8317,
    longitude: 73.7489,
    resumoCivico: "Canaliza irrigação para 1,8 milhão de hectares em Gujarat e 1.450 MW após décadas de protestos sociais.",
    orgaoReguladorOuBase: "SSNNL / CWC Índia / ICOLD",
    linkFonteOficial: "https://sardarsarovardam.org/",
    tags: ["abastecimento", "india", "narmada", "irrigacao", "sardar-sarovar"],
  },
  {
    id: "BAR-US-SHASTA",
    nome: "Shasta Dam",
    tipoBarragem: "abastecimento_multiuso",
    tipoEstrutura: "Arco-Gravidade de Concreto Curvo",
    pais: "Estados Unidos",
    continente: "América do Norte",
    rioOuBacia: "Sacramento River (Norte da Califórnia)",
    alturaMetros: 183,
    volumeCapacidadeMm3: 5615.0,
    operador: "US Bureau of Reclamation (USBR)",
    classificacaoRiscoOuHazard: "High Hazard Potential (USACE NID)",
    statusOperacional: "em_operacao",
    anoConclusao: 1945,
    latitude: 40.7183,
    longitude: -122.4178,
    resumoCivico: "Chave mestra do Central Valley Project irrigando milhões de hectares agrícolas na Califórnia.",
    orgaoReguladorOuBase: "USBR / USACE NID",
    linkFonteOficial: "https://www.usbr.gov/mp/ncao/shasta/",
    tags: ["abastecimento", "eua", "california", "shasta", "central-valley"],
  },
  {
    id: "BAR-US-FORT-PECK",
    nome: "Fort Peck Dam",
    tipoBarragem: "controle_cheias",
    tipoEstrutura: "Aterro Hidráulico de Terra",
    pais: "Estados Unidos",
    continente: "América do Norte",
    rioOuBacia: "Rio Missouri (Montana)",
    alturaMetros: 76,
    volumeCapacidadeMm3: 23100.0,
    operador: "US Army Corps of Engineers (USACE)",
    classificacaoRiscoOuHazard: "High Hazard Potential (USACE NID)",
    statusOperacional: "em_operacao",
    anoConclusao: 1940,
    latitude: 48.0069,
    longitude: -106.4178,
    resumoCivico: "Maior barragem por aterro hidráulico dos EUA, construída na década de 1930 sob o New Deal.",
    orgaoReguladorOuBase: "USACE NID",
    linkFonteOficial: "https://www.nwo.usace.army.mil/Missions/Dam-and-Lake-Projects/Missouri-River-Dams/Fort-Peck/",
    tags: ["controle_cheias", "eua", "missouri-river", "fort-peck", "usace"],
  },
];

/**
 * Converte o tipo interno em rótulo em português acessível.
 */
function rotuloTipo(tipo: TipoBarragem): string {
  switch (tipo) {
    case "rejeitos_mineracao":
      return "Rejeitos de Mineração";
    case "hidreletrica":
      return "Hidrelétrica & Energia";
    case "abastecimento_multiuso":
      return "Abastecimento & Multiuso";
    case "controle_cheias":
      return "Controle de Cheias";
    default:
      return tipo;
  }
}

/**
 * Converte o status operacional em rótulo em português.
 */
function rotuloStatus(status: StatusOperacional): string {
  switch (status) {
    case "em_operacao":
      return "Em Operação";
    case "desativada_descaracterizacao":
      return "Descaracterização / Desativada";
    case "rompida_historico":
      return "Rompida (Histórico)";
    case "em_construcao":
      return "Em Construção";
    default:
      return status;
  }
}

/**
 * Executa o ETL gerando o acervo compacto e a camada GeoJSON.
 */
export async function executar(): Promise<void> {
  console.log(`Iniciando ETL de Barragens Mundiais (${BARRAGENS_MUNDIAIS_BRUTAS.length} estruturas)...`);

  // 1. Garantir diretórios de saída
  if (!fs.existsSync(DIR_DATA_OUT)) {
    fs.mkdirSync(DIR_DATA_OUT, { recursive: true });
  }
  if (!fs.existsSync(DIR_GEOJSON_OUT)) {
    fs.mkdirSync(DIR_GEOJSON_OUT, { recursive: true });
  }

  // 2. Compactação do JSON de dados
  const tabelaCompacta = compactar(BARRAGENS_MUNDIAIS_BRUTAS as unknown as Record<string, unknown>[]);
  const caminhoCompactJson = path.join(DIR_DATA_OUT, "barragens-mundiais.compact.json");
  fs.writeFileSync(caminhoCompactJson, JSON.stringify(tabelaCompacta), "utf-8");

  const tamanhoKb = (Buffer.byteLength(JSON.stringify(tabelaCompacta), "utf-8") / 1024).toFixed(1);
  console.log(`✅ Arquivo compacto salvo: ${caminhoCompactJson} (${tamanhoKb} KB)`);

  // 3. Montagem e gravação da camada GeoJSON WGS84 para o Globo 3D
  const distribuicaoTipos: Record<string, number> = {};
  for (const b of BARRAGENS_MUNDIAIS_BRUTAS) {
    distribuicaoTipos[b.tipoBarragem] = (distribuicaoTipos[b.tipoBarragem] || 0) + 1;
  }

  const features = BARRAGENS_MUNDIAIS_BRUTAS.map((barragem) => ({
    type: "Feature",
    id: barragem.id,
    geometry: {
      type: "Point",
      coordinates: [barragem.longitude, barragem.latitude], // WGS84 [lon, lat]
    },
    properties: {
      id: barragem.id,
      nome: barragem.nome,
      tipo: barragem.tipoBarragem,
      tipoRotulo: rotuloTipo(barragem.tipoBarragem),
      tipoEstrutura: barragem.tipoEstrutura,
      pais: barragem.pais,
      continente: barragem.continente,
      rioOuBacia: barragem.rioOuBacia,
      alturaMetros: barragem.alturaMetros,
      volumeCapacidadeMm3: barragem.volumeCapacidadeMm3,
      operador: barragem.operador,
      risco: barragem.classificacaoRiscoOuHazard,
      status: barragem.statusOperacional,
      statusRotulo: rotuloStatus(barragem.statusOperacional),
      ano: barragem.anoConclusao,
      resumo: barragem.resumoCivico,
      orgaoRegulador: barragem.orgaoReguladorOuBase,
      linkOficial: barragem.linkFonteOficial,
      tags: barragem.tags,
    },
  }));

  const geojson = {
    type: "FeatureCollection",
    metadata: {
      fonte: "Controle Popular — Observatório Global de Grandes Barragens (ICOLD, Global Tailings Portal, USACE NID, ANM/SIGBM)",
      dataAtualizacao: "2026-10-01",
      totalFeicoes: features.length,
      distribuicaoTipos,
      aviso: "Coordenadas georreferenciadas oficiais WGS84 compiladas a partir de registros estatais e cadastros públicos.",
    },
    features,
  };

  const caminhoGeojson = path.join(DIR_GEOJSON_OUT, "barragens-mundiais-destaque.geojson");
  fs.writeFileSync(caminhoGeojson, JSON.stringify(geojson, null, 2), "utf-8");

  const tamanhoGeojsonKb = (Buffer.byteLength(JSON.stringify(geojson), "utf-8") / 1024).toFixed(1);
  console.log(`✅ Camada GeoJSON salva: ${caminhoGeojson} (${tamanhoGeojsonKb} KB)`);
  console.log(`✅ Total de grandes barragens mundiais geradas: ${features.length}`);
}

// Execução direta via CLI
if (process.argv[1] && process.argv[1].endsWith("gerar-barragens-mundiais.mts")) {
  executar().catch((erro) => {
    console.error("❌ Erro fatal ao gerar acervo de barragens mundiais:", erro);
    process.exit(1);
  });
}
