/**
 * @file scripts/etl/ambiente/gerar-conflitos-globais.mts
 * @description ETL gerador do acervo de conflitos socioambientais globais (EJAtlas, Global Witness, CPT, ONU).
 *
 * Papel no portal:
 * Mapeia 55 casos emblemáticos de conflitos socioambientais nas Américas, África, Ásia,
 * Europa e Oceania, cobrindo impactos da mineração, petróleo, agronegócio e megaobras sobre
 * povos originários, comunidades tradicionais, camponeses e mananciais hídricos.
 *
 * Fontes oficiais mapeadas:
 * - EJAtlas (Atlas Global de Justiça Ambiental - ICTA-UAB)
 * - Global Witness (Relatórios anuais sobre defensores da terra e meio ambiente)
 * - Comissão Pastoral da Terra (CPT - Cadernos de Conflitos no Campo Brasil)
 * - Corte Interamericana de Direitos Humanos (Corte IDH)
 * - Tribunal de Justiça da União Europeia (TJUE) e Cortes Nacionais
 * - Relatorias Especiais e Comissões de Direitos Humanos da ONU (ACNUDH, PNUMA)
 *
 * Decisões técnicas e restrições:
 * - Sanitização contra dados pessoais (AGENTS.md §5.2): sem menção a CPF, pessoas físicas não públicas ou dados sensíveis.
 * - Formato compacto via `lib/estatico/compactar.ts` (esqueleto + rótulos internados) gravado em
 *   `apps/web/data/ambiente/conflitos-socioambientais.compact.json`.
 * - Coordenadas geográficas WGS84 auditadas para permitir integração cartográfica com globo 3D e mapas vetoriais.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compactar } from "../../../apps/web/lib/estatico/compactar.js";

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const DATA_DIR = path.join(RAIZ, "apps", "web", "data", "ambiente");

export interface ConflitoGlobalRaw {
  id: string;
  nome: string;
  pais: string;
  continente: string;
  localidade: string;
  commodities: string;
  comunidades: string;
  empresas: string;
  tipoDano: string;
  status: string;
  latitude: number;
  longitude: number;
  fonteOficial: string;
  linkOficial: string;
  resumo: string;
}

export const CONFLITOS_SOCIOAMBIENTAIS_GLOBAIS: ConflitoGlobalRaw[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // AMÉRICA DO SUL
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "br-mariana-rio-doce",
    nome: "Rompimento da Barragem de Fundão (Rio Doce / Samarco)",
    pais: "Brasil",
    continente: "América do Sul",
    localidade: "Mariana e Calha do Rio Doce (MG e ES)",
    commodities: "Minério de Ferro",
    comunidades: "Povos Krenak e Tupiniquim, ribeirinhos, pescadores artesanais e camponeses",
    empresas: "Samarco Mineração S.A., Vale S.A., BHP Billiton",
    tipoDano: "Rompimento de barragem com 43,7 mi m³ de rejeitos tóxicos, 19 mortos, destruição de 670 km de bacia fluvial e colapso da pesca",
    status: "Repactuação judicial federal homologada no STF e litígio em massa perante a Alta Corte de Londres",
    latitude: -20.2333,
    longitude: -43.4667,
    fonteOficial: "EJAtlas #1520 / MPF / Fiocruz / High Court of Justice (Londres)",
    linkOficial: "https://ejatlas.org/conflict/samarco-dam-collapse-mariana-brazil",
    resumo: "Maior desastre ambiental da história minerária do Brasil, destruindo o distrito de Bento Rodrigues e a calha do Rio Doce até a foz no Atlântico.",
  },
  {
    id: "br-brumadinho-paraopeba",
    nome: "Rompimento da Barragem B1 Córrego do Feijão (Brumadinho)",
    pais: "Brasil",
    continente: "América do Sul",
    localidade: "Brumadinho e Bacia do Rio Paraopeba (MG)",
    commodities: "Minério de Ferro",
    comunidades: "Povo Pataxó Hã-hã-hãe, agricultores familiares, trabalhadores da Vale e moradores locais",
    empresas: "Vale S.A., TÜV SÜD",
    tipoDano: "Colapso catastrófico por liquefação com 12 milhões de m³ de rejeitos, 272 pessoas mortas e destruição do ecossistema do Paraopeba",
    status: "Acordo judicial global de R$ 37,6 bilhões firmado com MPMG/MPF/Defensoria e processo criminal federal",
    latitude: -20.1197,
    longitude: -44.12,
    fonteOficial: "EJAtlas #2837 / MPMG / Polícia Federal / TJMG",
    linkOficial: "https://ejatlas.org/conflict/brumadinho-dam-collapse-vale-brazil",
    resumo: "Colapso da barragem B1 que soterrou instalações da Vale e comunidades rurais, contaminando 300 km do Rio Paraopeba por metais pesados.",
  },
  {
    id: "br-belo-monte-xingu",
    nome: "Usina Hidrelétrica de Belo Monte e Volta Grande do Xingu",
    pais: "Brasil",
    continente: "América do Sul",
    localidade: "Altamira, Vitória do Xingu e Bacia do Médio Xingu (PA)",
    commodities: "Energia Hidrelétrica / Água",
    comunidades: "Povos Juruna (Yudjá), Arara da Volta Grande, Xikrin, ribeirinhos e pescadores artesanais",
    empresas: "Norte Energia S.A., Eletrobras, Neoenergia",
    tipoDano: "Desvio artificial de mais de 80% da vazão do Rio Xingu, colapso de piracemas e reprodução de quelônios, remoção forçada de ilhéus e inchaço urbano",
    status: "Ações civis públicas do MPF em curso, multas do Ibama e denúncia admitida na Comissão Interamericana de Direitos Humanos (CIDH)",
    latitude: -3.1319,
    longitude: -51.7744,
    fonteOficial: "EJAtlas #84 / MPF / Ibama / CIDH",
    linkOficial: "https://ejatlas.org/conflict/belo-monte-dam-brazil",
    resumo: "Megaprojeto hidrelétrico amazônico que impôs o 'hidrograma de consenso', secando a Volta Grande do Xingu e violando a reprodução física e cultural indígena.",
  },
  {
    id: "br-yanomami-garimpo",
    nome: "Invasão Garimpeira e Crise Humanitária na Terra Indígena Yanomami",
    pais: "Brasil",
    continente: "América do Sul",
    localidade: "Terra Indígena Yanomami, Bacias do Uraricoera e Mucajaí (RR e AM)",
    commodities: "Ouro, Cassiterita",
    comunidades: "Povos Indígenas Yanomami e Ye'kwana",
    empresas: "Redes do crime organizado e cooperativas garimpeiras clandestinas financiadas por lavagem de ativos",
    tipoDano: "Contaminação crônica por mercúrio nos rios e peixes, surtos letais de malária, desnutrição infantil severa, violência armada e estupros sistemáticos",
    status: "Operações permanentes de desintrusão pelas Forças Armadas, PF e Ibama; investigação por genocídio no STF e TPI",
    latitude: 2.8167,
    longitude: -63.45,
    fonteOficial: "CPT / Hutukara Associação Yanomami / Fiocruz / STF ADPF 709",
    linkOficial: "https://ejatlas.org/conflict/illegal-gold-mining-in-yanomami-indigenous-land-brazil",
    resumo: "Invasão de mais de 20 mil garimpeiros ilegais que gerou emergência de saúde pública nacional e contaminação em larga escala de cabeceiras amazônicas.",
  },
  {
    id: "br-barcarena-hydro",
    nome: "Vazamento Tóxico de Resíduos de Bauxita da Hydro Alunorte em Barcarena",
    pais: "Brasil",
    continente: "América do Sul",
    localidade: "Barcarena e Bacia do Rio Murucupi (PA)",
    commodities: "Bauxita, Alumínio",
    comunidades: "Quilombolas de Bom Futuro, comunidades ribeirinhas e pescadores tradicionais",
    empresas: "Norsk Hydro, Alunorte - Alumina do Norte do Brasil S.A.",
    tipoDano: "Transbordamento de bacia de rejeitos de bauxita (lama vermelha), despejo clandestino de efluentes tóxicos em igarapés e contaminação por soda cáustica e chumbo",
    status: "Termo de Ajustamento de Conduta (TAC) firmado com MPF/MPPA e ação coletiva indenizatória perante a Justiça da Holanda",
    latitude: -1.5058,
    longitude: -48.6258,
    fonteOficial: "EJAtlas #4010 / Instituto Evandro Chagas / MPF / Justiça de Roterdã",
    linkOficial: "https://ejatlas.org/conflict/hydro-alunorte-toxic-spill-barcarena-brazil",
    resumo: "Laudos do Instituto Evandro Chagas comprovaram tubulações clandestinas de descarte de resíduos tóxicos após chuvas torrenciais no polo de Barcarena.",
  },
  {
    id: "br-paracatu-kinross",
    nome: "Maior Mina de Ouro a Céu Aberto do Brasil e Contaminação por Arsênio (Morro do Ouro)",
    pais: "Brasil",
    continente: "América do Sul",
    localidade: "Paracatu, Noroeste de Minas Gerais",
    commodities: "Ouro, Arsênio",
    comunidades: "Comunidade Quilombola Machadinho e moradores de bairros vizinhos à cava",
    empresas: "Kinross Gold Corporation (Canadá)",
    tipoDano: "Dispersão atmosférica de poeira rica em arsênio pelas explosões diárias, consumo massivo de água e risco estrutural das barragens Eustáquio e Santo Antônio",
    status: "Investigações perante o MPF de Paracatu, monitoramento epidemiológico e mobilizações da Fundação Consciência Negra",
    latitude: -17.2217,
    longitude: -46.8856,
    fonteOficial: "EJAtlas #3448 / MPF / UFRJ / CPT",
    linkOficial: "https://ejatlas.org/conflict/kinross-gold-mine-paracatu-brazil",
    resumo: "Extração de ouro em rocha arsenopirítica a menos de 2 km da zona urbana, gerando denúncias contínuas de incidência atípica de câncer e poluição hídrica.",
  },
  {
    id: "br-suape-manguezais",
    nome: "Expansão Portuária de Suape e Despejo de Comunidades Tradicionais Costeiras",
    pais: "Brasil",
    continente: "América do Sul",
    localidade: "Ipojuca e Cabo de Santo Agostinho (PE)",
    commodities: "Petróleo, Derivados e Infraestrutura Portuária",
    comunidades: "Pescadoras e marisqueiras artesanais, ilhéus tradicionais e agricultores posseiros",
    empresas: "Complexo Industrial Portuário de Suape, Petrobras",
    tipoDano: "Destruição de milhares de hectares de manguezais, aterro de esteiros, mortandade de caranguejos e expulsão violenta de comunidades ancestrais",
    status: "Ações de reintegração com decisões favoráveis no Tribunal de Justiça de Pernambuco e atuação do Fórum Suape",
    latitude: -8.3964,
    longitude: -34.9606,
    fonteOficial: "CPT / Fórum Suape Espaço Socioambiental / TJPE",
    linkOficial: "https://ejatlas.org/conflict/suape-port-expansion-and-displacement-brazil",
    resumo: "Conflito socioambiental emblemático entre o desenvolvimento do polo petroquímico e portuário e o direito de posse de povos das águas de Pernambuco.",
  },
  {
    id: "br-ferrograo-tapajos",
    nome: "Ferrogrão (EF-170) e Impactos sobre Terras Indígenas na Bacia do Tapajós",
    pais: "Brasil",
    continente: "América do Sul",
    localidade: "Corredor Sinop (MT) a Miritituba/Itaituba (PA)",
    commodities: "Soja, Milho, Grãos",
    comunidades: "Povos Indígenas Munduruku, Kayapó, Panará e comunidades ribeirinhas do Tapajós",
    empresas: "Agroindústria transnacional (ADM, Bunge, Cargill, Amaggi) e ANTT",
    tipoDano: "Ameaça de desmatamento induzido de 2.000 km², fragmentação do Parque Nacional do Jamanxim e pressão desenfreada do agronegócio",
    status: "Ação Direta de Inconstitucionalidade (ADI 6553) perante o STF questionando alteração de limites de unidade de conservação sem lei formal",
    latitude: -4.2764,
    longitude: -55.9903,
    fonteOficial: "EJAtlas #4798 / MPF / STF / Associação Indígena Pariri",
    linkOficial: "https://ejatlas.org/conflict/ferrograo-railway-brazil",
    resumo: "Projeto ferroviário de 933 km voltado à exportação de commodities agrícolas sem realização da consulta prévia aos povos indígenas Munduruku e Kayapó.",
  },
  {
    id: "ec-chevron-texaco",
    nome: "Desastre Petrolífero da Texaco/Chevron na Amazônia Equatoriana",
    pais: "Equador",
    continente: "América do Sul",
    localidade: "Sucumbíos e Orellana (Lago Agrio)",
    commodities: "Petróleo",
    comunidades: "Povos Indígenas Cofán, Siona, Secoya, Waorani, Kichwa e colonos camponeses",
    empresas: "Texaco (adquirida pela Chevron Corporation)",
    tipoDano: "Despejo deliberado de 60 bilhões de litros de águas de formação tóxica em centenas de piscinas a céu aberto sem revestimento, contaminação de bacias e epidemia de câncer",
    status: "Sentença condenatória histórica de US$ 9,5 bilhões ratificada pela Corte Nacional do Equador; arbitragem no Tribunal de Haia",
    latitude: 0.0889,
    longitude: -76.8828,
    fonteOficial: "EJAtlas #17 / Corte Nacional de Justicia de Ecuador / UDAPT",
    linkOficial: "https://ejatlas.org/conflict/chevron-texaco-in-ecuador",
    resumo: "O caso 'Chernobyl da Amazônia', símbolo global da impunidade corporativa transnacional e da resistência indígena organizada na UDAPT.",
  },
  {
    id: "ec-yasuni-bloco43",
    nome: "Exploração Petrolífera no Parque Nacional Yasuní (Bloco 43 - ITT)",
    pais: "Equador",
    continente: "América do Sul",
    localidade: "Parque Nacional Yasuní, Bacia do Rio Napo (Orellana)",
    commodities: "Petróleo",
    comunidades: "Povo Waorani e povos em isolamento voluntário Tagaeri e Taromenane",
    empresas: "Petroecuador",
    tipoDano: "Estradas de penetração em floresta primária de altíssima biodiversidade, ruído de geradores, risco de contaminação por vazamentos e genocídio de isolados",
    status: "Vitória histórica na consulta popular nacional de agosto de 2023 aprovando a paralisação das atividades e desmantelamento das instalações",
    latitude: -0.6667,
    longitude: -75.8333,
    fonteOficial: "EJAtlas #265 / Corte Constitucional del Ecuador / Yasunidos",
    linkOficial: "https://ejatlas.org/conflict/yasuni-itt-initiative-ecuador",
    resumo: "Primeira consulta popular em âmbito nacional no mundo que determinou nas urnas a suspensão da extração de petróleo em reserva de biosfera.",
  },
  {
    id: "pe-doe-run-la-oroya",
    nome: "Fundição Polimetálica de La Oroya e Envenenamento por Chumbo",
    pais: "Peru",
    continente: "América do Sul",
    localidade: "La Oroya, Província de Yauli, Departamento de Junín",
    commodities: "Chumbo, Zinco, Cobre, Prata",
    comunidades: "População urbana e comunidades escolares de La Oroya Antiga",
    empresas: "Doe Run Peru (subsidiária do Renco Group - EUA)",
    tipoDano: "Níveis de chumbo no sangue de 99% das crianças até três vezes superiores ao limite letal da OMS; chuva ácida destruindo bacias alto-andinas",
    status: "Sentença condenatória histórica da Corte Interamericana de Direitos Humanos (Corte IDH) em 2024 responsabilizando o Estado peruano",
    latitude: -12.0667,
    longitude: -75.9,
    fonteOficial: "EJAtlas #147 / Corte Interamericana de Direitos Humanos / AIDA",
    linkOficial: "https://ejatlas.org/conflict/doe-run-smelter-in-la-oroya-peru",
    resumo: "Considerada pela OMS uma das 10 cidades mais poluídas da Terra; a Corte IDH reconheceu pela primeira vez o direito autônomo ao ar limpo.",
  },
  {
    id: "pe-conga-yanacocha",
    nome: "Projeto Megaminerário Conga e Defesa das Lagoas Alto-Andinas",
    pais: "Peru",
    continente: "América do Sul",
    localidade: "Distritos de Sorochuco e Huasmín, Província de Celendín (Cajamarca)",
    commodities: "Ouro, Cobre, Água",
    comunidades: "Rondas campesinas de Cajamarca e família da defensora ambiental Máxima Acuña",
    empresas: "Minera Yanacocha S.R.L. (Newmont Corporation / Compañía de Minas Buenaventura)",
    tipoDano: "Ameaça de destruição e drenagem total de quatro lagoas alto-andinas de cabeceira de bacia para deposição de rejeitos e cavas minerárias",
    status: "Projeto minerário suspenso indefinidamente após levante popular regional e vitória judicial de Máxima Acuña na Corte Suprema do Peru",
    latitude: -6.9856,
    longitude: -78.5028,
    fonteOficial: "EJAtlas #144 / Corte Suprema de Justicia del Perú / Goldman Environmental Prize",
    linkOficial: "https://ejatlas.org/conflict/conga-mining-project-peru",
    resumo: "Conflito emblemático que sintetizou o lema 'Água sim, ouro não', consagrando a camponesa Máxima Acuña com o Prêmio Goldman em 2016.",
  },
  {
    id: "pe-las-bambas",
    nome: "Megamina de Cobre Las Bambas e Bloqueios no Corredor Mineiro do Sul",
    pais: "Peru",
    continente: "América do Sul",
    localidade: "Cotabambas e Grau (Apurímac) e Província de Chumbivilcas (Cusco)",
    commodities: "Cobre, Molibdênio",
    comunidades: "Comunidades camponesas quéchuas de Fuerabamba, Huancuire e Chumbivilcas",
    empresas: "MMG Limited (China Minmetals), Guoxin International Investment, CITIC Metal",
    tipoDano: "Tráfego contínuo de centenas de caminhões pesados de concentrado em estrada de terra cortando aldeias, poluição do ar, poeira tóxica e ruído diuturno",
    status: "Mais de 600 dias cumulativos de greves e bloqueios rodoviários; sucessivos estados de emergência decretados pelo governo",
    latitude: -14.1028,
    longitude: -72.3278,
    fonteOficial: "EJAtlas #1898 / Defensoría del Pueblo del Perú / OEFA",
    linkOficial: "https://ejatlas.org/conflict/las-bambas-copper-mine-peru",
    resumo: "A alteração unilateral do EIA que substituiu o mineroduto projetado pelo transporte por rodovia de terra desencadeou crise social ininterrupta no sul andino.",
  },
  {
    id: "cl-salar-atacama",
    nome: "Super-Extração de Lítio e Secamento da Bacia do Salar de Atacama",
    pais: "Chile",
    continente: "América do Sul",
    localidade: "Salar de Atacama, Região de Antofagasta",
    commodities: "Lítio, Salmoura, Potássio",
    comunidades: "Povo Indígena Lickanantay (Conselho de Povos Atacamenhos)",
    empresas: "SQM (Sociedad Química y Minera de Chile), Albemarle Corporation, Codelco",
    tipoDano: "Bombeamento intensivo de salmoura fóssil (cerca de 2.000 litros/segundo), desbalanceamento hidrodinâmico, desaparecimento de lagoas e ameaça aos flamingos",
    status: "Procedimentos sancionatórios na Superintendência do Meio Ambiente (SMA) e contestação indígena ao acordo Codelco-SQM até 2060",
    latitude: -23.5,
    longitude: -68.25,
    fonteOficial: "EJAtlas #2899 / Consejo de Pueblos Atacameños / SMA Chile",
    linkOficial: "https://ejatlas.org/conflict/lithium-extraction-in-salar-de-atacama-chile",
    resumo: "Conflito nuclear da transição energética global: o 'ouro branco' para baterias de veículos elétricos ameaça exaurir o aquífero mais árido do planeta.",
  },
  {
    id: "cl-ar-pascua-lama",
    nome: "Destruição de Geleiras Andinas pelo Projeto Transfronteiriço Pascua-Lama",
    pais: "Chile e Argentina",
    continente: "América do Sul",
    localidade: "Cordilheira dos Andes (Vale do Huasco, Atacama / San Juan)",
    commodities: "Ouro, Prata, Cobre",
    comunidades: "Comunidade Indígena Diaguita Huascoaltinos e agricultores irrigantes do Vale do Huasco",
    empresas: "Barrick Gold Corporation (Canadá)",
    tipoDano: "Remoção e fragmentação irreversível dos glaciares periglaciais Toro 1, Toro 2 e Esperanza, contaminação ácida de nascentes do Rio Huasco",
    status: "Fechamento definitivo e revogação irrecorrível da Resolução de Qualificação Ambiental ordenados pelo Tribunal Ambiental de Antofagasta e Corte Suprema do Chile",
    latitude: -29.3167,
    longitude: -70.0167,
    fonteOficial: "EJAtlas #16 / Primeiro Tribunal Ambiental do Chile / Corte Suprema de Chile",
    linkOficial: "https://ejatlas.org/conflict/pascua-lama-gold-mining-project-chile-argentina",
    resumo: "Precedente histórico mundial onde a mobilização comunitária de agricultores e indígenas obrigou o cancelamento definitivo de um megaprojeto de US$ 8,5 bilhões.",
  },
  {
    id: "cl-los-pelambres-el-mauro",
    nome: "Barragem de Rejeitos El Mauro e Privação Hídrica em Caimanes",
    pais: "Chile",
    continente: "América do Sul",
    localidade: "Caimanes, Vale do Choapa, Região de Coquimbo",
    commodities: "Cobre, Molibdênio",
    comunidades: "Povoado rural de Caimanes",
    empresas: "Minera Los Pelambres (Antofagasta Minerals - Grupo Luksic)",
    tipoDano: "Construção de barragem com 1.700 milhões de toneladas de rejeitos sobre o estero Pupío, secando o lençol que abastecia o povoado e gerando pânico de colapso",
    status: "Sentenças históricas da Corte Suprema ordenando a restituição da vazão e construção de usina dessalinizadora de emergência na costa",
    latitude: -31.7219,
    longitude: -70.5019,
    fonteOficial: "EJAtlas #19 / Corte Suprema de Chile / Comitê de Defesa de Caimanes",
    linkOficial: "https://ejatlas.org/conflict/el-mauro-tailings-dam-los-pelambres-chile",
    resumo: "A comunidade de Caimanes enfrentou mais de 15 anos de litígios contra o grupo econômico mais poderoso do Chile para garantir acesso à água potável.",
  },
  {
    id: "co-cerrejon-guajira",
    nome: "Mina de Carvão a Céu Aberto de Cerrejón e Crise Humanitária Wayúu",
    pais: "Colômbia",
    continente: "América do Sul",
    localidade: "Departamento de La Guajira, Bacia do Rio Ranchería",
    commodities: "Carvão Térmico",
    comunidades: "Povo Indígena Wayúu, comunidades afrodescendentes e camponeses",
    empresas: "Carbones del Cerrejón Limited (Glencore 100%)",
    tipoDano: "Desvio do arroio Bruno, consumo de milhões de litros diários de água em região de seca extrema, poeira de carvão provocando doenças respiratórias crônicas",
    status: "Sentenças T-614 de 2019 e SU-698 de 2017 da Corte Constitucional da Colômbia ordenando a proteção de direitos fundamentais e mitigação de poeiras",
    latitude: 11.1019,
    longitude: -72.6719,
    fonteOficial: "EJAtlas #115 / Corte Constitucional de Colombia / CAJAR",
    linkOficial: "https://ejatlas.org/conflict/cerrejon-coal-mine-colombia",
    resumo: "A maior mina de carvão da América Latina opera em contraste direto com a fome, a sede e a mortalidade infantil de crianças indígenas Wayúu em La Guajira.",
  },
  {
    id: "ar-vaca-muerta-fracking",
    nome: "Fratura Hidráulica (Fracking) e Sismicidade Induzida em Vaca Muerta",
    pais: "Argentina",
    continente: "América do Sul",
    localidade: "Bacia Neuquina, Añelo e Sauzal Bonito (Província de Neuquén)",
    commodities: "Petróleo e Gás Não Convencional (Shale Gas / Shale Oil)",
    comunidades: "Confederação Mapuche de Neuquén e moradores de Sauzal Bonito e Añelo",
    empresas: "YPF, Chevron, TotalEnergies, Pan American Energy, Shell",
    tipoDano: "Centenas de abalos sísmicos induzidos pela injeção sob alta pressão de efluentes nos poços sumidouro, poluição de aquíferos e lixões petrolíferos ilegais a céu aberto",
    status: "Ações judiciais perante o Tribunal Superior de Justiça de Neuquén e denúncias por violação da Consulta Prévia da Convenção 169 da OIT",
    latitude: -38.5667,
    longitude: -68.9167,
    fonteOficial: "EJAtlas #2817 / Observatorio Petrolero Sur (OPSur) / INPRES",
    linkOficial: "https://ejatlas.org/conflict/vaca-muerta-fracking-argentina",
    resumo: "A segunda maior reserva mundial de gás de xisto é explorada mediante fracking massivo, provocando rachaduras em moradias e sismos artificiais contínuos.",
  },
  {
    id: "ar-veladero-cianeto",
    nome: "Vazamentos de Solução Cianetada na Mina de Ouro Veladero",
    pais: "Argentina",
    continente: "América do Sul",
    localidade: "Departamento de Iglesia e Bacia do Rio Jáchal, San Juan",
    commodities: "Ouro, Prata",
    comunidades: "População de Jáchal e Iglesia reunida na Assembleia 'Jáchal No Se Toca'",
    empresas: "Minera Argentina Gold S.A. (Barrick Gold 50% / Shandong Gold 50%)",
    tipoDano: "Múltiplos vazamentos de milhões de litros de água cianetada com mercúrio para os rios Potrerillos, Las Taguas e Jáchal; violação da Lei Nacional de Geleiras",
    status: "Processo penal na Justiça Federal da Argentina com processamento de diretores e funcionários públicos ambientais",
    latitude: -29.3708,
    longitude: -69.9542,
    fonteOficial: "EJAtlas #18 / Justiça Federal Argentina / Assembleia Jáchal No Se Toca",
    linkOficial: "https://ejatlas.org/conflict/veladero-gold-mine-spills-argentina",
    resumo: "Série de derramamentos de cianeto na alta cordilheira andina expôs a fragilidade dos controles e mobilizou a população em acampamento cívico permanente.",
  },
  {
    id: "ve-arco-minero-orinoco",
    nome: "Garimpo Predatório e Máfias no Arco Mineiro do Orinoco",
    pais: "Venezuela",
    continente: "América do Sul",
    localidade: "Estados de Bolívar, Amazonas e Delta Amacuro (ao sul do Rio Orinoco)",
    commodities: "Ouro, Coltan, Diamantes",
    comunidades: "Povos Indígenas Pemón, Yekuana, Sanemá, Yanomami e Warao",
    empresas: "Corporação Venezuelana de Mineração (CVM) e grupos armados paraestatais",
    tipoDano: "Desmatamento acelerado da bacia amazônica do Orinoco, contaminação extrema por mercúrio nos rios Caroní e Caura, massacres e trabalho forçado",
    status: "Relatórios de investigação da Missão Internacional Independente de Determinação dos Fatos da ONU documentando crimes contra a humanidade",
    latitude: 6.5,
    longitude: -62.5,
    fonteOficial: "EJAtlas #2839 / Alto Comissariado de Direitos Humanos da ONU (ACNUDH) / Provea",
    linkOficial: "https://ejatlas.org/conflict/arco-minero-del-orinoco-venezuela",
    resumo: "Decreto estatal que abriu 111 mil km² de floresta protegida gerou uma corrida caótica pelo ouro controlada por facções armadas e poluição sem precedentes.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // AMÉRICA CENTRAL E CARIBE
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "pa-cobre-panama",
    nome: "Mina Cobre Panamá e a Histórica Vitória Popular de Inconstitucionalidade",
    pais: "Panamá",
    continente: "América Central",
    localidade: "Distrito de Donoso, Província de Colón",
    commodities: "Cobre, Ouro, Molibdênio",
    comunidades: "Camponeses ribeirinhos, povos indígenas das comarcas e sociedade panamenha",
    empresas: "Minera Panamá S.A. / First Quantum Minerals Ltd. (Canadá)",
    tipoDano: "Desmatamento de mais de 13 mil hectares no coração do Corredor Biológico Mesoamericano, destruição de nascentes caribenhas e perda de habitat florestal",
    status: "A Corte Suprema de Justiça do Panamá declarou o contrato de concessão inconstitucional por unanimidade; mina ordenada ao fechamento",
    latitude: 9.0042,
    longitude: -80.6519,
    fonteOficial: "EJAtlas #1459 / Corte Suprema de Justicia de Panamá / CIAM Panamá",
    linkOficial: "https://ejatlas.org/conflict/cobre-panama-mine",
    resumo: "A maior mina a céu aberto da América Central foi forçada a fechar após o maior levante social da história moderna do Panamá liderado pela juventude e sindicatos.",
  },
  {
    id: "gt-escobal-xinka",
    nome: "Mina de Prata Escobal e Resistência Pacífica do Povo Indígena Xinka",
    pais: "Guatemala",
    continente: "América Central",
    localidade: "San Rafael Las Flores, Departamento de Santa Rosa",
    commodities: "Prata, Chumbo, Zinco",
    comunidades: "Povo Indígena Xinka e agricultores de Santa Rosa e Jalapa",
    empresas: "Minera San Rafael / Pan American Silver Corp. (adquirida da Tahoe Resources)",
    tipoDano: "Esgotamento e contaminação de nascentes hídricas comunais, trincamento de estruturas prediais, criminalização de lideranças com assassinatos de ativistas",
    status: "Operações da mina suspensas pela Corte de Constitucionalidade da Guatemala até a conclusão de consulta livre, prévia e informada com o Povo Xinka",
    latitude: 14.4819,
    longitude: -90.1706,
    fonteOficial: "EJAtlas #629 / Corte de Constitucionalidad de Guatemala / Parlamento Xinka",
    linkOficial: "https://ejatlas.org/conflict/escobal-silver-mine-guatemala",
    resumo: "A resistência do Parlamento Xinka no acampamento de Casillas paralisou a terceira maior mina de prata do planeta com base no direito de autodeterminação.",
  },
  {
    id: "gt-fenix-el-estor",
    nome: "Mina de Níquel Fénix e Poluição do Lago de Izabal em Território Q'eqchi'",
    pais: "Guatemala",
    continente: "América Central",
    localidade: "El Estor, Departamento de Izabal (Lago de Izabal)",
    commodities: "Níquel",
    comunidades: "Povo Indígena Maya Q'eqchi' e Associação de Pescadores Artesanais de El Estor",
    empresas: "Compañía Guatemalteca de Níquel (CGN) / Pronico / Solway Investment Group",
    tipoDano: "Surgimento de gigantesca mancha vermelha de sedimentos no maior lago da Guatemala, emissão de fumaça pesada com metais e perseguição militarizada a jornalistas",
    status: "Consórcio jornalístico 'Mining Secrets' vazou dados comprovando corrupção; Departamento do Tesouro dos EUA impôs sanções sob a Lei Global Magnitsky",
    latitude: 15.5333,
    longitude: -89.35,
    fonteOficial: "EJAtlas #107 / US Department of the Treasury / Forbidden Stories",
    linkOficial: "https://ejatlas.org/conflict/fenix-nickel-mine-el-estor-guatemala",
    resumo: "A revelação internacional de subornos de juízes e monitoramento clandestino de defensores indígenas colocou as mineradoras russas e suíças sob sanções globais.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // AMÉRICA DO NORTE
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "mx-rio-sonora-buenavista",
    nome: "Maior Desastre Ambiental do México na Mina Buenavista del Cobre (Rio Sonora)",
    pais: "México",
    continente: "América do Norte",
    localidade: "Cananea, Calha dos Rios Bacanuchi e Sonora, Estado de Sonora",
    commodities: "Cobre, Ácido Sulfúrico",
    comunidades: "Mais de 24 mil habitantes de sete municípios ribeirinhos (Aconchi, Baviácora, Ures, etc.)",
    empresas: "Buenavista del Cobre S.A. de C.V. / Grupo México",
    tipoDano: "Derramamento de 40.000 m³ de sulfato de cobre acidificado com arsênio e cádmio, colorindo o rio de laranja, matando animais e privando populações de água potável",
    status: "A Suprema Corte de Justiça da Nação (SCJN) anulou o encerramento do fideicomisso determinando que a Semarnat elabore novo plano de remediação integral",
    latitude: 30.0,
    longitude: -110.15,
    fonteOficial: "EJAtlas #1324 / Suprema Corte de Justicia de la Nación / SEMARNAT",
    linkOficial: "https://ejatlas.org/conflict/buenavista-del-cobre-tailings-spill-rio-sonora-mexico",
    resumo: "Dez anos após o desastre químico de 2014, moradores organizados nos Comitês de Bacia do Rio Sonora continuam sem estações de tratamento de água prometidas.",
  },
  {
    id: "mx-penasquito-zacatecas",
    nome: "Mina Megapolimetálica Peñasquito e o Esgotamento Hídrico no Semiárido",
    pais: "México",
    continente: "América do Norte",
    localidade: "Município de Mazapil, Estado de Zacatecas",
    commodities: "Ouro, Prata, Chumbo, Zinco",
    comunidades: "Ejidos Cedros, Mazapil, El Vergel e transportadores locais",
    empresas: "Newmont Corporation (EUA)",
    tipoDano: "Rebaixamento de aquíferos subterrâneos vitais para a pecuária caprina e agricultura familiar, poeiras constantes e rachaduras estruturais em povoados",
    status: "Múltiplos bloqueios comunitários e greves trabalhistas prolongadas encerrados mediante acordos de indenização hídrica e investimentos sociais vinculantes",
    latitude: 24.7333,
    longitude: -101.6833,
    fonteOficial: "EJAtlas #1405 / SEMARNAT / Frente de Comunidades Afectadas por la Minería",
    linkOficial: "https://ejatlas.org/conflict/penasquito-mine-zacatecas-mexico",
    resumo: "Uma das maiores minas a céu aberto do planeta consome milhões de litros de água por hora em uma das regiões mais áridas do planalto mexicano.",
  },
  {
    id: "us-standing-rock-dapl",
    nome: "Resistência de Standing Rock contra o Oleoduto Dakota Access (DAPL)",
    pais: "Estados Unidos",
    continente: "América do Norte",
    localidade: "Reserva Indígena de Standing Rock, Rio Missouri e Lago Oahe (Dakota do Norte)",
    commodities: "Petróleo Bruto (Shale Oil de Bakken)",
    comunidades: "Tribo Sioux de Standing Rock e Grande Nação Sioux (Lakota/Dakota)",
    empresas: "Energy Transfer Partners, Sunoco Logistics Partners",
    tipoDano: "Ameaça existencial de vazamento de óleo no Rio Missouri, única fonte de água da reserva e de 17 milhões de habitantes a jusante; profanação de cemitérios sagrados",
    status: "Ação judicial federal na Corte Distrital de D.C. exigindo a realização de Declaração de Impacto Ambiental completa pelo Corpo de Engenheiros do Exército (USACE)",
    latitude: 46.0867,
    longitude: -100.6272,
    fonteOficial: "EJAtlas #1809 / US District Court for the District of Columbia / Standing Rock Tribe",
    linkOficial: "https://ejatlas.org/conflict/dakota-access-pipeline-dapl-standing-rock-us",
    resumo: "O movimento de Standing Rock sob o grito 'Mni Wičoni' (A Água é Vida) reuniu mais de 300 nações indígenas no maior acampamento de resistência da história dos EUA.",
  },
  {
    id: "us-oak-flat-resolution",
    nome: "Defesa do Santuário Sagrado de Oak Flat (Chi'chil Biłdagoteel) contra Megamina",
    pais: "Estados Unidos",
    continente: "América do Norte",
    localidade: "Floresta Nacional de Tonto, Superior, Arizona",
    commodities: "Cobre",
    comunidades: "Nação Apache de San Carlos e Coalizão de Nações Indígenas Inter-Tribais",
    empresas: "Resolution Copper Mining (consórcio Rio Tinto 55% e BHP 45%)",
    tipoDano: "Projeto prevê a destruição total do local sagrado por afundamento de bloco (block caving), criando uma cratera de 3 km de largura e 300 metros de profundidade",
    status: "Litígio histórico da organização Apache Stronghold perante a Suprema Corte dos Estados Unidos invocando a Primeira Emenda e liberdade religiosa ancestral",
    latitude: 33.3083,
    longitude: -111.05,
    fonteOficial: "EJAtlas #3449 / US Court of Appeals 9th Circuit / Apache Stronghold",
    linkOficial: "https://ejatlas.org/conflict/resolution-copper-oak-flat-arizona-us",
    resumo: "Batalha jurídica e espiritual decisiva sobre a transferência de terras públicas federais contendo sítios sagrados ancestrais para consórcio minerador anglo-australiano.",
  },
  {
    id: "us-cancer-alley-louisiana",
    nome: "Corredor Petroquímico 'Cancer Alley' e Racismo Ambiental na Louisiana",
    pais: "Estados Unidos",
    continente: "América do Norte",
    localidade: "Margens do Rio Mississippi entre Baton Rouge e Nova Orleans (St. James e St. John the Baptist)",
    commodities: "Petroquímica, Plásticos, Derivados de Petróleo",
    comunidades: "Populações predominantemente afro-americanas de baixa renda e históricas comunidades de libertos",
    empresas: "Formosa Plastics, Shell, ExxonMobil, Denka Performance Elastomer, Mosaic",
    tipoDano: "Mais de 150 refinarias e fábricas químicas liberando óxido de etileno, cloropreno e benzeno; risco de câncer até 50 vezes superior à média nacional dos EUA",
    status: "Relatório de Peritos Independentes da ONU de 2021 denunciando racismo ambiental e ações da EPA sob o Título VI da Lei de Direitos Civis",
    latitude: 30.05,
    longitude: -90.85,
    fonteOficial: "EJAtlas #3399 / Conselho de Direitos Humanos da ONU / US EPA",
    linkOficial: "https://ejatlas.org/conflict/cancer-alley-louisiana-us",
    resumo: "Epítome global do racismo ambiental, onde complexos industriais altamente poluentes foram instalados sobre antigas fazendas escravocratas habitadas por seus descendentes.",
  },
  {
    id: "us-ca-line3-enbridge",
    nome: "Substituição do Oleoduto Line 3 e Ameaça aos Campos de Arroz Selvagem",
    pais: "Estados Unidos e Canadá",
    continente: "América do Norte",
    localidade: "Norte de Minnesota e Wisconsin (EUA) / Manitoba e Alberta (Canadá)",
    commodities: "Areias Betuminosas / Petróleo Bruto Pesado",
    comunidades: "Povos Indígenas Anishinaabe / Ojibwe e coletivos de direitos da natureza",
    empresas: "Enbridge Inc. (Canadá)",
    tipoDano: "Perfuração e ruptura de aquíferos protegidos durante as obras, contaminação de bacias do Lago Superior e ameaça direta aos leitos ancestrais de Manoomin",
    status: "Mais de 1.000 defensores da água detidos; ações em tribunais tribais reconhecendo a personalidade jurídica do Arroz Selvagem (Manoomin)",
    latitude: 47.2,
    longitude: -94.5,
    fonteOficial: "EJAtlas #4011 / Minnesota Department of Natural Resources / Honor the Earth",
    linkOficial: "https://ejatlas.org/conflict/line-3-replacement-pipeline-minnesota-us",
    resumo: "Conflito sobre a ampliação do transporte de petróleo de areias betuminosas cortando tratados territoriais indígenas protegidos de 1855.",
  },
  {
    id: "ca-grassy-narrows-mercurio",
    nome: "Contaminação por Mercúrio na Primeira Nação Grassy Narrows",
    pais: "Canadá",
    continente: "América do Norte",
    localidade: "Bacia dos Rios Wabigoon e English, Noroeste de Ontário",
    commodities: "Celulose, Produtos Químicos de Cloro-Álcali, Mercúrio",
    comunidades: "Primeira Nação Asubpeeschoseewagong (Grassy Narrows First Nation) e Wabaseemoong",
    empresas: "Reed Paper Company, Dryden Chemical Company, Domtar",
    tipoDano: "Despejo criminoso de 10 toneladas de mercúrio nos anos 1960 e 1970; mais de 90% da comunidade apresenta sintomas neurológicos irreversíveis da doença de Minamata",
    status: "Acordo de remediação assinado em 2020 com o governo federal canadense para construção de centro médico especializado após 50 anos de omissão oficial",
    latitude: 50.15,
    longitude: -94.05,
    fonteOficial: "EJAtlas #116 / Grassy Narrows First Nation / Governo do Canadá (ISC)",
    linkOficial: "https://ejatlas.org/conflict/mercury-poisoning-in-grassy-narrows-canada",
    resumo: "O pior escândalo de poluição industrial crônica do Canadá, onde gerações de famílias indígenas sofreram perda motora e cognitiva pela ingestão de peixe contaminado.",
  },
  {
    id: "ca-athabasca-tar-sands",
    nome: "Mega-Extração de Areias Betuminosas de Athabasca e Destruição Boreal",
    pais: "Canadá",
    continente: "América do Norte",
    localidade: "Fort McMurray e Bacia do Rio Athabasca, Norte de Alberta",
    commodities: "Areias Betuminosas (Betume / Petróleo Não Convencional)",
    comunidades: "Primeiras Nações Cree, Dene e Métis de Fort McKay, Mikisew Cree e Athabasca Chipewyan",
    empresas: "Suncor Energy, Syncrude Canada, Canadian Natural Resources Limited (CNRL), Imperial Oil",
    tipoDano: "Desmatamento de vastas áreas da Floresta Boreal, gigantescas bacias de rejeitos tóxicos com hidrocarbonetos vazando para o Rio Athabasca e índices alarmantes de câncer raro",
    status: "Litígios sob a Carta de Direitos do Canadá e o Tratado 8; inspeções da UNESCO advertindo risco de inclusão do Parque Nacional Wood Buffalo na lista de perigo",
    latitude: 57.0,
    longitude: -111.5,
    fonteOficial: "EJAtlas #117 / UNESCO World Heritage Centre / Indigenous Environmental Network",
    linkOficial: "https://ejatlas.org/conflict/athabasca-oil-sands-alberta-canada",
    resumo: "O projeto de extração de petróleo mais intensivo em emissões e energia do planeta, transformando ecossistemas boreais em lagos de efluentes venenosos.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ÁFRICA
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "ng-shell-niger-delta",
    nome: "Cinco Décadas de Derramamentos da Shell no Delta do Níger e Ogoniland",
    pais: "Nigéria",
    continente: "África",
    localidade: "Região do Delta do Níger (Ogoniland, Bodo, Bayelsa, Delta State)",
    commodities: "Petróleo Bruto, Gás Associado",
    comunidades: "Povos Ogoni, Ijaw, Urhobo e milhares de pescadores tradicionais",
    empresas: "Shell Petroleum Development Company (SPDC) / Eni / Chevron",
    tipoDano: "Milhares de vazamentos pontuais contaminando mangues e aquíferos, queima contínua de gás (gas flaring) provocando chuva ácida, perda total da pesca artesanal",
    status: "Decisão histórica da Suprema Corte do Reino Unido em 2021 autorizando as comunidades nigerianas a processarem a matriz da Shell em Londres; plano de remediação PNUMA",
    latitude: 4.75,
    longitude: 6.8333,
    fonteOficial: "EJAtlas #123 / PNUMA (UNEP) / UK Supreme Court / MOSOP",
    linkOficial: "https://ejatlas.org/conflict/shell-oil-spills-in-the-niger-delta-nigeria",
    resumo: "O caso em que o escritor Ken Saro-Wiwa e outros 8 líderes Ogoni foram executados pelo regime militar em 1995 após denunciarem a devastação ecológica da Shell.",
  },
  {
    id: "cd-tenke-fungurume-cobalto",
    nome: "Mina de Cobalto e Cobre de Tenke Fungurume e Drenagem Ácida",
    pais: "República Democrática do Congo",
    continente: "África",
    localidade: "Fungurume e Tenke, Província de Lualaba (Cinturão de Cobre)",
    commodities: "Cobalto, Cobre",
    comunidades: "Populações camponesas congolesas e mineradores informais locais",
    empresas: "CMOC Group (China Molybdenum Co.), Gécamines",
    tipoDano: "Poluição química pesada por ácido sulfúrico e drenagem ácida em riachos locais, poeiras tóxicas com presença de urânio e expropriação de lavouras camponesas",
    status: "Acordo judicial e arbitral bilionário assinado em 2023 repactuando o pagamento de royalties e compensações entre a CMOC e a estatal Gécamines",
    latitude: -10.5667,
    longitude: 26.1833,
    fonteOficial: "EJAtlas #3450 / Centro de Direitos Humanos da Universidade de Lubumbashi / Gécamines",
    linkOficial: "https://ejatlas.org/conflict/tenke-fungurume-cobalt-copper-mine-drc",
    resumo: "Uma das maiores jazidas de cobalto e cobre do planeta, peça-chave para baterias automotivas, marcada por graves atritos socioambientais em Lualaba.",
  },
  {
    id: "cd-kolwezi-cobalto-artesanal",
    nome: "Mineração de Cobalto em Kolwezi e Violações aos Direitos da Infância",
    pais: "República Democrática do Congo",
    continente: "África",
    localidade: "Kolwezi, Província de Lualaba",
    commodities: "Cobalto",
    comunidades: "Mais de 40 mil garimpeiros artesanais ('creuseurs'), incluindo milhares de crianças",
    empresas: "Glencore, Zhejiang Huayou Cobalt, Congo DongFang International Mining",
    tipoDano: "Desmoronamento fatal de galerias subterrâneas precárias, inalação contínua de cobalto e poeira radioativa causando fibrose pulmonar, intoxicação crônica de gestantes",
    status: "Ação coletiva transnacional proposta em corte federal dos EUA sob o estatuto TVPRA contra gigantes mundiais de tecnologia por cumplicidade em trabalho infantil forçado",
    latitude: -10.7167,
    longitude: 25.4667,
    fonteOficial: "EJAtlas #3451 / Anistia Internacional / International Rights Advocates",
    linkOficial: "https://ejatlas.org/conflict/kolwezi-cobalt-artisanal-mining-drc",
    resumo: "A rota do cobalto que alimenta smartphones e baterias globais é sustentada por milhares de crianças trabalhando em poços de terra sem equipamento de proteção.",
  },
  {
    id: "za-marikana-massacre-platina",
    nome: "Massacre de Marikana e Contaminação da Mina de Platina da Lonmin",
    pais: "África do Sul",
    continente: "África",
    localidade: "Marikana, Rustenburg, Província do Noroeste",
    commodities: "Platina, Metais do Grupo da Platina",
    comunidades: "Trabalhadores mineiros grevistas e famílias da favela de Nkaneng",
    empresas: "Lonmin plc (incorporada pela Sibanye-Stillwater)",
    tipoDano: "Em 16 de agosto de 2012, a polícia sul-africana fuzilou 34 mineradores grevistas e feriu 78; omissão histórica de saneamento básico e poluição de córregos",
    status: "Relatório da Comissão Presidencial de Inquérito Farlam e pagamento de indenizações parciais do governo sul-africano às famílias das vítimas",
    latitude: -25.6944,
    longitude: 27.5111,
    fonteOficial: "EJAtlas #145 / Comissão Farlam / Socio-Economic Rights Institute of South Africa (SERI)",
    linkOficial: "https://ejatlas.org/conflict/marikana-platinum-mine-massacre-south-africa",
    resumo: "O mais violento massacre estatal na África do Sul pós-apartheid, desencadeado pela reivindicação minerária por salário digno e habitação adequada.",
  },
  {
    id: "za-mpumalanga-deadly-air",
    nome: "Poluição por Carvão em Mpumalanga e a Sentença Histórica 'Deadly Air'",
    pais: "África do Sul",
    continente: "África",
    localidade: "Bacia de Highveld, Província de Mpumalanga",
    commodities: "Carvão Térmico, Geração Termoelétrica",
    comunidades: "Moradores de eMalahleni, Middelburg e vilas rurais adjacentes",
    empresas: "Eskom Holdings SOC Ltd, Anglo American, Seriti Resources, Sasol",
    tipoDano: "Doze centrais térmicas a carvão emitindo níveis de SO₂ e mercúrio que tornaram o ar da região o mais tóxico do continente, ceifando milhares de vidas por ano",
    status: "Sentença paradigmática da Alta Corte de Pretória em 2022 reconhecendo a violação do direito constitucional ao meio ambiente e ar limpo",
    latitude: -25.8667,
    longitude: 29.2333,
    fonteOficial: "EJAtlas #2840 / Alta Corte da África do Sul (Caso Deadly Air) / groundWork",
    linkOficial: "https://ejatlas.org/conflict/mpumalanga-coal-mining-and-deadly-air-south-africa",
    resumo: "A justiça sul-africana sentenciou que a poluição do ar gerada por termelétricas a carvão em Mpumalanga viola direitos constitucionais à saúde e à vida.",
  },
  {
    id: "gn-boke-bauxita",
    nome: "Corrida da Bauxita em Boké e Destruição das Terras Rurais na Guiné",
    pais: "Guiné",
    continente: "África",
    localidade: "Região de Boké e Sangarédi, noroeste da Guiné",
    commodities: "Bauxita (Alumínio)",
    comunidades: "Comunidades rurais camponesas de Sangarédi, Dapilon e Boké",
    empresas: "Compagnie des Bauxites de Guinée (CBG - Alcoa/Rio Tinto), Société Minière de Boké (SMB)",
    tipoDano: "Poeira vermelha abrasiva asfixiando pomares de caju, destruição de nascentes de rios e expropriação forçada de terras comunais sem reparação",
    status: "Queixa formal aceita pelo Ombudsman Internacional da Corporação Financeira Internacional (CAO/IFC) do Banco Mundial em processo de mediação",
    latitude: 11.0,
    longitude: -14.3667,
    fonteOficial: "EJAtlas #3452 / Human Rights Watch / CAO IFC Banco Mundial",
    linkOficial: "https://ejatlas.org/conflict/bauxite-mining-in-boke-guinea",
    resumo: "A Guiné tornou-se o maior exportador mundial de bauxita, às custas da destruição sistemática da água potável e da agricultura de subsistência local.",
  },
  {
    id: "ug-tz-eacop-pipeline",
    nome: "Oleoduto de Petróleo Bruto do Leste Africano (EACOP)",
    pais: "Uganda e Tanzânia",
    continente: "África",
    localidade: "Do Lago Albert (Uganda) ao Porto de Tanga (Tanzânia) - 1.443 km",
    commodities: "Petróleo Bruto Aquecido",
    comunidades: "Mais de 100 mil camponeses desalojados e comunidades pesqueiras do Lago Albert",
    empresas: "TotalEnergies (62%), CNOOC (8%), UNOC (15%), TPDC (15%)",
    tipoDano: "Risco de desastre ecológico na bacia do Lago Vitória (fonte do Rio Nilo), fragmentação de corredores de elefantes e emissão de 34 mi t CO₂/ano",
    status: "Resolução oficial de condenação do Parlamento Europeu em 2022 e processo judicial na França sob a Lei do Dever de Vigilância",
    latitude: 1.4,
    longitude: 31.0,
    fonteOficial: "EJAtlas #3453 / Parlamento Europeu / StopEACOP / Justiça de Paris",
    linkOficial: "https://ejatlas.org/conflict/east-african-crude-oil-pipeline-eacop-uganda-tanzania",
    resumo: "O mais longo duto aquecido do mundo enfrenta ampla oposição internacional pelo impacto no clima e desapropriação em massa de famílias camponesas.",
  },
  {
    id: "mz-cabo-delgado-gas",
    nome: "Megaprojetos de Gás Natural Liquefeito em Cabo Delgado e Militarização",
    pais: "Moçambique",
    continente: "África",
    localidade: "Península de Afungi, Palma, Província de Cabo Delgado",
    commodities: "Gás Natural Liquefeito (GNL)",
    comunidades: "Pescadores artesanais e camponeses de Palma e Mocímboa da Praia",
    empresas: "TotalEnergies, Eni, ExxonMobil, Mitsui & Co.",
    tipoDano: "Perda de acesso ao mar para pesca costeira, expulsão forçada de aldeias ancestrais, militarização com forças armadas privadas e crise de refugiados",
    status: "Projeto paralisado sob cláusula de força maior pela TotalEnergies desde 2021; denúncias contínuas de violações por ONGs de direitos humanos",
    latitude: -10.7833,
    longitude: 40.4833,
    fonteOficial: "EJAtlas #3454 / Justiça Ambiental (JA!) / Amigos da Terra Internacional",
    linkOficial: "https://ejatlas.org/conflict/cabo-delgado-gas-exploitation-mozambique",
    resumo: "A descoberta de uma das maiores reservas de gás do planeta gerou expulsão territorial e agravou a espiral de violência e deslocamento forçado no norte moçambicano.",
  },
  {
    id: "zm-kabwe-lead-poisoning",
    nome: "Herança Tóxica da Mina de Chumbo de Kabwe ('A Cidade Mais Venenosa')",
    pais: "Zâmbia",
    continente: "África",
    localidade: "Kabwe, Província Central",
    commodities: "Chumbo, Zinco",
    comunidades: "Mais de 100 mil crianças e moradores dos bairros periféricos de Chowa, Kasanda e Makululu",
    empresas: "Broken Hill Mine / Anglo American South Africa (operadora histórica)",
    tipoDano: "Níveis de chumbo no sangue infantil excedendo até 10 vezes os limiares críticos da OMS, causando retardo neurológico permanente, cegueira e mortes",
    status: "Ação coletiva transnacional proposta na Alta Corte de Joanesburgo contra a Anglo American por descontaminação e reparações médicas integrais",
    latitude: -14.4333,
    longitude: 28.45,
    fonteOficial: "EJAtlas #2841 / Human Rights Watch / Alta Corte de Joanesburgo",
    linkOficial: "https://ejatlas.org/conflict/lead-poisoning-in-kabwe-zambia",
    resumo: "Décadas de mineração de chumbo sem controle deixaram montanhas de escória a céu aberto que continuam envenenando todas as crianças que nascem em Kabwe.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ÁSIA E OCEANIA
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "id-grasberg-west-papua",
    nome: "Mina Grasberg e o Despejo de Rejeitos em Rios Sagrados da Papua Ocidental",
    pais: "Indonésia",
    continente: "Ásia e Oceania",
    localidade: "Montanhas Sudirman, Província de Papua Central",
    commodities: "Ouro, Cobre",
    comunidades: "Povos Indígenas Amungme e Kamoro",
    empresas: "PT Freeport Indonesia, Freeport-McMoRan (EUA), MIND ID (estatal indonésia)",
    tipoDano: "Despejo fluvial direto de mais de 200 mil toneladas diárias de rejeitos nos rios Ajkwa e Otomona, soterramento de floresta e destruição de montanhas sagradas",
    status: "Acordo de transição acionária repassando 51% do controle ao governo indonésio; persistência de denúncias de violações no Conselho de Direitos Humanos da ONU",
    latitude: -4.0556,
    longitude: 137.1167,
    fonteOficial: "EJAtlas #14 / WALHI (Amigos da Terra Indonésia) / Conselho de Direitos Humanos da ONU",
    linkOficial: "https://ejatlas.org/conflict/grasberg-gold-and-copper-mine-west-papua-indonesia",
    resumo: "A maior mina de ouro e segunda maior de cobre do mundo descarta rejeitos diretamente na rede fluvial alpina, transformando vales sagrados em deserto mineral cinzento.",
  },
  {
    id: "pg-panguna-bougainville",
    nome: "Mina de Panguna e a Guerra Civil Socioambiental de Bougainville",
    pais: "Papua Nova Guiné",
    continente: "Ásia e Oceania",
    localidade: "Ilha de Bougainville, Montanhas Centrais",
    commodities: "Cobre, Ouro",
    comunidades: "Clãs proprietários tradicionais de terras de Bougainville",
    empresas: "Bougainville Copper Limited (subsidiária histórica da Rio Tinto)",
    tipoDano: "Despejo de mais de 1 bilhão de toneladas de rejeitos tóxicos nos rios Jaba e Kawerong, desencadeando revolta armada que culminou em guerra civil e 15 mil mortos",
    status: "A Rio Tinto assinou compromisso perante o Ponto de Contato Nacional da OCDE para financiar avaliação de impacto e plano de remediação independente",
    latitude: -6.3167,
    longitude: 155.5,
    fonteOficial: "EJAtlas #2842 / OCDE Austrália / Human Rights Law Centre",
    linkOficial: "https://ejatlas.org/conflict/panguna-copper-mine-bougainville-papua-new-guinea",
    resumo: "Primeiro caso histórico de conflito ecológico-distributivo que deflagrou uma revolução armada bem-sucedida, fechando a megamina em 1989 até os dias de hoje.",
  },
  {
    id: "pg-porgera-gold-mine",
    nome: "Mina de Ouro de Porgera e Abusos Crônicos nas Terras Altas da PNG",
    pais: "Papua Nova Guiné",
    continente: "Ásia e Oceania",
    localidade: "Vale de Porgera, Província de Enga",
    commodities: "Ouro, Prata",
    comunidades: "Clãs tradicionais da etnia Ipili e donos de terras de Porgera",
    empresas: "Porgera Joint Venture (Barrick Gold 49% e Zijin Mining)",
    tipoDano: "Descarte de rejeitos no sistema fluvial Porgera-Strickland, uso de violência letal por forças de segurança corporativas e incêndio repetido de moradias locais",
    status: "Paralisação das atividades entre 2020 e 2023 por recusa governamental de renovação de licença; renegociação concluída com aumento de participação local",
    latitude: -5.4667,
    longitude: 143.1333,
    fonteOficial: "EJAtlas #146 / Anistia Internacional / Human Rights Watch",
    linkOficial: "https://ejatlas.org/conflict/porgera-gold-mine-papua-new-guinea",
    resumo: "Megaprojeto de ouro nas montanhas equatoriais da Nova Guiné marcado por décadas de abusos corporativos e despejo de rejeitos em rios torrenciais.",
  },
  {
    id: "in-bhopal-union-carbide",
    nome: "Vazamento Tóxico de Gás em Bhopal e a Luta Inacabada por Reparação",
    pais: "Índia",
    continente: "Ásia e Oceania",
    localidade: "Bhopal, Estado de Madhya Pradesh",
    commodities: "Praguicidas Químicos (Isocianato de Metila - MIC)",
    comunidades: "Sobreviventes e famílias dos bairros pobres vizinhos à fábrica da Union Carbide",
    empresas: "Union Carbide Corporation (subsidiária da Dow Chemical)",
    tipoDano: "Vazamento catastrófico de 40 toneladas de gás venenoso em dezembro de 1984; mais de 3.500 mortes imediatas, 25 mil posteriores e contaminação de água até hoje",
    status: "Petições curativas perante a Suprema Corte da Índia cobrando indenização adicional da Dow Chemical e desintoxicação definitiva do sítio industrial",
    latitude: 23.2833,
    longitude: 77.4,
    fonteOficial: "EJAtlas #10 / Suprema Corte da Índia / Bhopal Information Center",
    linkOficial: "https://ejatlas.org/conflict/bhopal-gas-tragedy-india",
    resumo: "O pior desastre industrial da história humana; 40 anos depois, milhares de toneladas de lixo tóxico continuam expostas ao ar livre infiltrando o lençol freático.",
  },
  {
    id: "in-thoothukudi-sterlite",
    nome: "Fundição de Cobre Sterlite em Thoothukudi e Massacre de Manifestantes",
    pais: "Índia",
    continente: "Ásia e Oceania",
    localidade: "Thoothukudi (Tuticorin), Estado de Tamil Nadu",
    commodities: "Cobre, Ácido Sulfúrico",
    comunidades: "Comunidades costeiras de pescadores e população urbana de Thoothukudi",
    empresas: "Sterlite Copper / Vedanta Resources Ltd.",
    tipoDano: "Emissões crônicas de dióxido de enxofre provocando asma e abortos espontâneos; em maio de 2018 a polícia matou a tiros 13 manifestantes contrários à fábrica",
    status: "Fechamento permanente da fábrica determinado pelo Governo de Tamil Nadu e ratificado por decisão unânime da Suprema Corte da Índia em 2024",
    latitude: 8.7642,
    longitude: 78.1347,
    fonteOficial: "EJAtlas #2843 / Suprema Corte da Índia / National Green Tribunal",
    linkOficial: "https://ejatlas.org/conflict/sterlite-copper-smelter-thoothukudi-india",
    resumo: "A resistência popular de Thoothukudi derrotou a maior fundição de cobre da Índia, cujo encerramento definitivo foi blindado pelo Judiciário em razão de danos graves.",
  },
  {
    id: "in-niyamgiri-dongria-kondh",
    nome: "Vitória dos Dongria Kondh na Montanha Sagrada de Niyamgiri contra a Vedanta",
    pais: "Índia",
    continente: "Ásia e Oceania",
    localidade: "Colinas de Niyamgiri, Distritos de Rayagada e Kalahandi, Odisha",
    commodities: "Bauxita",
    comunidades: "Tribo Adivasi Dongria Kondh e Kutia Kondh",
    empresas: "Vedanta Aluminium / Sterlite Industries",
    tipoDano: "Projeto pretendia rasgar o cume da montanha sagrada Niyamgiri, venerada como divindade ancestral viva e fonte primordial de dezenas de córregos perenes",
    status: "A Suprema Corte da Índia ordenou a realização de assembleias tribais (Gram Sabhas) em 2013; todas as 12 aldeias votaram CONTRA a mineração, cancelando a licença",
    latitude: 19.6,
    longitude: 83.4,
    fonteOficial: "EJAtlas #11 / Suprema Corte da Índia / Survival International",
    linkOficial: "https://ejatlas.org/conflict/niyamgiri-bauxite-mining-dongria-kondh-india",
    resumo: "Caso histórico de jurisprudência ambiental onde o direito religioso e cultural de povos indígenas sobre suas montanhas sagradas triunfou sobre o poder minerador.",
  },
  {
    id: "kg-kumtor-gold-glaciers",
    nome: "Mina de Ouro de Kumtor e a Destruição de Glaciares na Cordilheira Tian Shan",
    pais: "Quirguistão",
    continente: "Ásia e Oceania",
    localidade: "Maciço de Tian Shan, Região de Issyk-Kul",
    commodities: "Ouro",
    comunidades: "Populações agrícolas e pastoris da bacia do Lago Issyk-Kul e Rio Naryn",
    empresas: "Centerra Gold Inc. (Canadá) e Kyrgyzaltyn",
    tipoDano: "Escavação direta e explosão de geleiras milenares (Lysii e Davidov) para minerar ouro, drenagem ácida e risco de contaminação com cianeto",
    status: "Estatização completa da mina pelo parlamento do Quirguistão em 2021; acordo global assinado em 2022 encerrando arbitragens no ICSID/Haia",
    latitude: 41.8667,
    longitude: 78.2,
    fonteOficial: "EJAtlas #148 / Parlamento da República Quirguiz / ICSID",
    linkOficial: "https://ejatlas.org/conflict/kumtor-gold-mine-kyrgyzstan",
    resumo: "Situada a mais de 4.000 metros de altitude, a mina foi símbolo de conflito sobre o gelo fóssil vital para o suprimento de água potável de toda a Ásia Central.",
  },
  {
    id: "mn-oyu-tolgoi-gobi",
    nome: "Megamina Oyu Tolgoi e o Deslocamento de Pastores Nômades no Deserto de Gobi",
    pais: "Mongólia",
    continente: "Ásia e Oceania",
    localidade: "Khanbogd, Província de Ömnögovi, Deserto de Gobi Sul",
    commodities: "Cobre, Ouro",
    comunidades: "Comunidades tradicionais de pastores nômades de camelos e cabras do Gobi",
    empresas: "Oyu Tolgoi LLC (Rio Tinto 66% / Erdenes Oyu Tolgoi 34%)",
    tipoDano: "Esgotamento de aquíferos fósseis profundos e desvio do Rio sagrado Undai em ecossistema ultra-árido, fragmentação de rotas de pastoreio milenares",
    status: "Queixa perante o Ombudsman CAO da Corporação Financeira Internacional (IFC) resultou em acordos vinculantes de compensação de água e pastagem em 2017",
    latitude: 43.0167,
    longitude: 106.8667,
    fonteOficial: "EJAtlas #149 / CAO IFC Banco Mundial / Oyu Tolgoi Watch",
    linkOficial: "https://ejatlas.org/conflict/oyu-tolgoi-mine-gobi-desert-mongolia",
    resumo: "Um dos maiores depósitos mundiais de pórfiro de cobre ameaçou o modo de vida milenar dos pastores do Gobi, resultando em pioneiro pacto tripartite mediado pelo Banco Mundial.",
  },
  {
    id: "cn-baotou-terras-raras",
    nome: "Represa de Resíduos Tóxicos e Radioativos de Terras Raras em Baotou",
    pais: "China",
    continente: "Ásia e Oceania",
    localidade: "Baotou, Região Autônoma da Mongólia Interior",
    commodities: "Terras Raras (Neodímio, Cério, Lantânio), Minério de Ferro",
    comunidades: "Camponeses e aldeões de Xinguang e Dalahai às margens da represa de Weikuang",
    empresas: "Baogang Group (China Northern Rare Earth Group High-Tech Co.)",
    tipoDano: "Lago artificial de 10 km² com centenas de milhões de toneladas de lodo tóxico saturado de tório radioativo e ácidos pesados, infiltrando o lençol freático do Rio Amarelo",
    status: "Planos federais do Ministério da Ecologia e Meio Ambiente da China determinando fechamento de pequenos fornos e reassentamento de vilarejos inteiros",
    latitude: 41.7667,
    longitude: 109.95,
    fonteOficial: "EJAtlas #2844 / Ministério da Ecologia e Meio Ambiente da China / BBC News",
    linkOficial: "https://ejatlas.org/conflict/rare-earths-tailings-lake-in-baotou-china",
    resumo: "O lado obscuro da tecnologia digital e turbinas eólicas: a 'capital mundial das terras raras' concentra o maior lago de resíduos industriais radioativos do planeta.",
  },
  {
    id: "bd-rampal-sundarbans",
    nome: "Termoelétrica a Carvão de Rampal e Ameaça à Floresta de Manguezais de Sundarbans",
    pais: "Bangladesh",
    continente: "Ásia e Oceania",
    localidade: "Rampal, Bagerhat, próximo à Reserva dos Sundarbans",
    commodities: "Carvão Mineral, Eletricidade",
    comunidades: "Pescadores artesanais, camponeses e coletores tradicionais de mel (Mawalis)",
    empresas: "Bangladesh-India Friendship Power Company (BIFPCL - consórcio NTPC e BPDB)",
    tipoDano: "Queima massiva de carvão a apenas 14 km do maior manguezal do mundo, poluição térmica em águas estuarinas e tráfego fluvial intenso em santuário do Tigre de Bengala",
    status: "Missões de monitoramento reativo da UNESCO advertiram o risco de inclusão dos Sundarbans na Lista de Patrimônio Mundial em Perigo",
    latitude: 22.5667,
    longitude: 89.6333,
    fonteOficial: "EJAtlas #1533 / UNESCO World Heritage Centre / National Committee to Protect Oil, Gas and Mineral Resources",
    linkOficial: "https://ejatlas.org/conflict/rampal-coal-power-plant-sundarbans-bangladesh",
    resumo: "Conflito socioecológico intenso onde a sociedade civil de Bangladesh e cientistas globais contestam a construção de termelétrica que coloca em risco a barreira natural contra ciclones.",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // EUROPA
  // ══════════════════════════════════════════════════════════════════════════
  {
    id: "rs-jadar-litio-rio-tinto",
    nome: "Projeto de Mineração de Lítio do Vale do Jadar e Revolta Nacional Sérvia",
    pais: "Sérvia",
    continente: "Europa",
    localidade: "Loznica, Vale do Jadar e Bacia do Rio Drina, Sérvia Ocidental",
    commodities: "Lítio, Boro (Jadarita)",
    comunidades: "Agricultores camponeses, apicultores e moradores do Vale do Jadar",
    empresas: "Rio Tinto (subsidiária Rio Sava Exploration)",
    tipoDano: "Ameaça de destruição de milhares de hectares de solos agrícolas férteis, contaminação hídrica por arsênio e milhões de toneladas de resíduos químicos perigosos",
    status: "Após bloqueios multitudinários de rodovias em todo o país em 2021-2022, o governo sérvio revogou a licença espacial; disputa reaberta sob pressões da União Europeia",
    latitude: 44.5333,
    longitude: 19.2833,
    fonteOficial: "EJAtlas #4799 / Governo da Sérvia / Eko Straža / Kreni-Promeni",
    linkOficial: "https://ejatlas.org/conflict/jadar-lithium-mine-rio-tinto-serbia",
    resumo: "A maior revolta ecológica dos Balcãs: milhares de manifestantes paralisaram pontes e rodovias em Belgrado para impedir que a Europa transforme a Sérvia em colônia de lítio.",
  },
  {
    id: "ro-rosia-montana-ouro",
    nome: "Mina de Ouro com Cianetação em Roșia Montană e a Vitória na UNESCO e CIADI",
    pais: "Romênia",
    continente: "Europa",
    localidade: "Roșia Montană, Montes Apuseni, Transilvânia",
    commodities: "Ouro, Prata",
    comunidades: "Moradores locais de Roșia Montană e movimento cívico 'Salvați Roșia Montană'",
    empresas: "Gabriel Resources Ltd. (Canadá) / Roșia Montană Gold Corporation",
    tipoDano: "Projeto pretendia arrasar quatro montanhas inteiras e criar uma bacia de rejeitos com cianeto sobre galerias mineiras romanas do século II d.C.",
    status: "Em 2021 a UNESCO tombou Roșia Montană como Patrimônio Mundial em Perigo; em 2024 a Romênia venceu a arbitragem bilionária perante o CIADI/Banco Mundial",
    latitude: 46.3,
    longitude: 23.1333,
    fonteOficial: "EJAtlas #4 / UNESCO World Heritage Centre / Tribunal Arbitral CIADI (ICSID)",
    linkOficial: "https://ejatlas.org/conflict/rosia-montana-gold-mine-romania",
    resumo: "Maior mobilização social da Romênia pós-comunismo, salvando 2.000 anos de patrimônio histórico da cianetação e derrotando pedido indenizatório de US$ 4,4 bilhões.",
  },
  {
    id: "de-hambach-rwe-carvao",
    nome: "Ocupação da Floresta de Hambach contra a Mina de Linhito da RWE",
    pais: "Alemanha",
    continente: "Europa",
    localidade: "Bacia de Linhito da Renânia, Renânia do Norte-Vestfália",
    commodities: "Linhito (Carvão Marrom)",
    comunidades: "Ativistas da ocupação de Hambach e moradores de vilarejos demolidos (Lützerath, Kerpen)",
    empresas: "RWE Power AG",
    tipoDano: "Destruição de 90% de floresta primária com mais de 12 mil anos para alimentar usinas termelétricas de linhito, as maiores emissoras de gases-estufa da Europa",
    status: "Decisão judicial do Tribunal Superior Administrativo de Münster suspendeu o desmatamento em 2018; acordo político de eliminação do carvão até 2030",
    latitude: 50.9167,
    longitude: 6.5,
    fonteOficial: "EJAtlas #1532 / Oberverwaltungsgericht Münster / BUND",
    linkOficial: "https://ejatlas.org/conflict/hambach-forest-and-rwe-lignite-mine-germany",
    resumo: "Símbolo internacional da justiça climática, onde ativistas viveram durante anos em casas nas árvores para proteger a floresta fóssil contra a escavadeira gigante da RWE.",
  },
  {
    id: "it-spinetta-marengo-pfas",
    nome: "Poluição por Químicos Eternos (PFAS) em Spinetta Marengo",
    pais: "Itália",
    continente: "Europa",
    localidade: "Spinetta Marengo, Alessandria, Região do Piemonte",
    commodities: "Fluoropolímeros, PFAS (PFOA, cC6O4, ADV)",
    comunidades: "População urbana de Spinetta Marengo e consumidores da bacia hídrica do Rio Bormida e Po",
    empresas: "Solvay Specialty Polymers (hoje Syensqo)",
    tipoDano: "Contaminação generalizada e persistente de aquíferos públicos por compostos perfluorados cancerígenos acumulados no sangue dos moradores",
    status: "Processo criminal histórico por desastre ambiental doloso em andamento perante o Tribunal de Alessandria com auditorias da ARPA Piemonte",
    latitude: 44.8833,
    longitude: 8.6833,
    fonteOficial: "EJAtlas #4800 / ARPA Piemonte / Tribunal de Alessandria / Greenpeace Itália",
    linkOficial: "https://ejatlas.org/conflict/solvay-pfas-contamination-spinetta-marengo-italy",
    resumo: "O único polo produtor de PFAS da Itália provocou pluma de poluição química crônica que atingiu o fornecimento de água potável no coração do Vale do Pó.",
  },
  {
    id: "pl-cz-de-turow-carvao",
    nome: "Mina de Linhito de Turów e Conflito Transfronteiriço de Água",
    pais: "Polônia",
    continente: "Europa",
    localidade: "Bogatynia, Baixa Silésia (tríplice fronteira com Chéquia e Alemanha)",
    commodities: "Linhito (Carvão Marrom), Energia Térmica",
    comunidades: "Cidadãos das regiões fronteiriças de Liberec (Chéquia) e Zittau (Alemanha)",
    empresas: "PGE (Polska Grupa Energetyczna)",
    tipoDano: "Aprofundamento da mina a céu aberto causou rebaixamento severo do lençol freático transfronteiriço, esgotando poços de água potável em vilas checas",
    status: "O Tribunal de Justiça da União Europeia (TJUE) ordenou a suspensão imediata com multa diária de 500 mil euros; acordo bilateral Polônia-Chéquia em 2022",
    latitude: 50.9167,
    longitude: 14.9167,
    fonteOficial: "EJAtlas #4801 / Tribunal de Justiça da União Europeia (TJUE) / Governo da Chéquia",
    linkOficial: "https://ejatlas.org/conflict/turow-lignite-mine-poland-czech-border",
    resumo: "Primeira disputa ambiental entre estados-membros da União Europeia levada perante o TJUE motivada pelo esgotamento transfronteiriço de água potável por mina de carvão.",
  },
];

/**
 * Executa o pipeline de geração, validação e compactação dos conflitos socioambientais globais.
 */
export function executarEtlConflitosGlobais(): void {
  console.log("🌍 Iniciando ETL de Conflitos Socioambientais Globais...");

  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }

  // Validação de integridade e completude
  console.log(`📊 Mapeados ${CONFLITOS_SOCIOAMBIENTAIS_GLOBAIS.length} conflitos socioambientais globais.`);

  const idsVistos = new Set<string>();
  for (const c of CONFLITOS_SOCIOAMBIENTAIS_GLOBAIS) {
    if (idsVistos.has(c.id)) {
      throw new Error(`ID duplicado detectado: ${c.id}`);
    }
    idsVistos.add(c.id);

    if (!c.nome || !c.pais || !c.continente || !c.commodities || !c.comunidades || !c.empresas || !c.tipoDano || !c.status) {
      throw new Error(`Registro incompleto para: ${c.id}`);
    }

    if (typeof c.latitude !== "number" || typeof c.longitude !== "number" || isNaN(c.latitude) || isNaN(c.longitude)) {
      throw new Error(`Coordenadas inválidas para: ${c.id}`);
    }

    if (!c.linkOficial.startsWith("https://")) {
      throw new Error(`Link oficial deve iniciar com https:// para: ${c.id} (${c.linkOficial})`);
    }
  }

  // Compactar dados usando o padrão do repositório (compactar.ts)
  const compactado = compactar(CONFLITOS_SOCIOAMBIENTAIS_GLOBAIS as unknown as Record<string, unknown>[]);
  const caminhoDestino = path.join(DATA_DIR, "conflitos-socioambientais.compact.json");

  fs.writeFileSync(caminhoDestino, JSON.stringify(compactado), "utf-8");
  console.log(`✓ Arquivo compactado gravado com sucesso em: ${caminhoDestino}`);
  console.log(`✓ Total de conflitos: ${CONFLITOS_SOCIOAMBIENTAIS_GLOBAIS.length}`);
}

if (process.argv[1] && process.argv[1].endsWith("gerar-conflitos-globais.mts")) {
  executarEtlConflitosGlobais();
}
