/**
 * @file scripts/etl/internacional/dados-novos-inteligencia.mts
 * @description Acervo de novos documentos de inteligência do FBI, NSA e da aliança Twelve Eyes / Fourteen Eyes.
 *
 * Papel no portal:
 * Alimenta o gerador arquivístico gerar-desclassificados-g20.mts, expandindo a cobertura
 * de transparência cívica sobre agências de segurança e inteligência dos Estados Unidos
 * e das grandes potências da OTAN / Twelve Eyes em conexão com a soberania brasileira.
 *
 * Fontes oficiais primárias:
 * - FBI The Vault (vault.fbi.gov) e FBI IC3 (ic3.gov)
 * - NSA Declassification Initiatives (nsa.gov/Helpful-Links/NSA-FOIA/) e Central Security Service
 * - ODNI IC on the Record (dni.gov / intel.gov)
 * - UK The National Archives Kew (nationalarchives.gov.uk) e NCSC/GCHQ (ncsc.gov.uk)
 * - Canadian Security Intelligence Service (canada.ca/en/security-intelligence-service.html) e CSE (cyber.gc.ca)
 * - Australian Signals Directorate (cyber.gov.au) e ASIO (naa.gov.au)
 * - New Zealand SIS & GCSB (nzsis.govt.nz / gcsb.govt.nz)
 * - Danish Defence Intelligence Service (fe-ddis.dk) e PET Dinamarca (pet.dk)
 * - Norwegian Intelligence Service (forsvaret.no/aktuelt-og-presse/publikasjoner/fokus) e PST (pst.no)
 * - Service Historique de la Défense (servicehistorique.sfd.defense.gouv.fr) e DGSI França
 * - Algemene Inlichtingen- en Veiligheidsdienst Holanda (aivd.nl)
 * - Bundesnachrichtendienst & Bundesamt für Verfassungsschutz Alemanha (verfassungsschutz.de)
 * - Veiligheid van de Staat Bélgica (vsse.be)
 * - Sistema di Informazione per la Sicurezza della Repubblica Itália (sicurezzanazionale.gov.it)
 * - Centro Nacional de Inteligencia / CCN-CERT Espanha (ccn-cert.cni.es)
 * - Försvarsmakten MUST & FRA Suécia (forsvarsmakten.se)
 */

export interface NovoDocumentoInteligencia {
  id: string;
  titulo: string;
  resumo: string;
  orgaoInteligencia: string;
  nomeCompletoOrgao: string;
  paisOrigem: string;
  codigoIsoPais: string;
  bandeiraPais: string;
  continente: "América do Norte" | "América do Sul" | "Europa" | "Oceania" | "Eurásia" | "África" | "Ásia";
  dataPublicacao: string;
  dataDesclassificacao: string;
  nivelClassificacaoOriginal: "Ultrassecreto" | "Secreto" | "Confidencial" | "Reservado" | "Público / Ostensivo";
  temas: string[];
  assuntos: string[];
  paisesMencionados: string[];
  sujeitosMencionados: string[];
  numeroRegistroOficial: string;
  quantidadePaginas: number;
  urlOficialCustodia: string;
  urlPdfOriginal: string;
  contextoBrasil: string;
  latitude: number;
  longitude: number;
  localidadeFoco: string;
  aliancaInteligencia: "Five Eyes" | "Nine Eyes" | "Twelve Eyes" | "Fourteen Eyes" | "G20 Soberano";
  naturezaDocumento: "Desclassificado Histórico" | "Relatório Público Contemporâneo";
}

export const NOVOS_DOCUMENTOS_INTELIGENCIA: NovoDocumentoInteligencia[] = [
  // ══════════════════════════════════════════════════════════════
  // 1. ESTADOS UNIDOS: FBI (FEDERAL BUREAU OF INVESTIGATION)
  // ══════════════════════════════════════════════════════════════
  {
    id: "DOC-FBI-COINTELPRO-CONE-SUL",
    titulo: "COINTELPRO e Redes de Vigilância Política na América Latina (The Vault)",
    resumo: "Dossiês desclassificados do FBI The Vault demonstrando métodos de contrainteligência, infiltração e vigilância de movimentos políticos e exilados compartilhados com polícias da América do Sul.",
    orgaoInteligencia: "FBI",
    nomeCompletoOrgao: "Federal Bureau of Investigation (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "1971-04-28",
    dataDesclassificacao: "1998-11-20",
    nivelClassificacaoOriginal: "Secreto",
    temas: ["Direitos Humanos", "Ditaduras", "Soberania", "Geopolítica"],
    assuntos: ["COINTELPRO", "Vigilância Política", "Operação Condor", "América Latina", "Subversão"],
    paisesMencionados: ["Estados Unidos", "Brasil", "Argentina", "Uruguai", "Chile"],
    sujeitosMencionados: ["J. Edgar Hoover", "Adidos Policiais FBI", "Ativistas e Exilados"],
    numeroRegistroOficial: "FBI-VAULT-COINTELPRO-LATAM-001",
    quantidadePaginas: 28,
    urlOficialCustodia: "https://vault.fbi.gov/cointel-pro",
    urlPdfOriginal: "https://vault.fbi.gov/cointel-pro/cointel-pro-new-left/cointel-pro-new-left-part-01-of-01/view",
    contextoBrasil: "Registros desclassificados do FBI The Vault demonstrando como métodos do COINTELPRO e intercâmbio de fichas policiais foram exportados e compartilhados com as polícias políticas do Cone Sul e do Brasil.",
    latitude: 38.8951,
    longitude: -77.0364,
    localidadeFoco: "Washington, DC, EUA (J. Edgar Hoover Building)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Desclassificado Histórico",
  },
  {
    id: "DOC-FBI-LEGAT-CONDOR-1976",
    titulo: "Comunicações do FBI Legal Attaché sobre Prisões Transfronteiriças da Operação Condor",
    resumo: "Telegramas confidenciais do adido policial do FBI (Legat) em Buenos Aires alertando o quartel-general em Washington sobre o plano de transferências clandestinas de prisioneiros e ações da Operação Condor no Cone Sul.",
    orgaoInteligencia: "FBI",
    nomeCompletoOrgao: "Federal Bureau of Investigation (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "1976-09-28",
    dataDesclassificacao: "2000-08-11",
    nivelClassificacaoOriginal: "Ultrassecreto",
    temas: ["Direitos Humanos", "Ditaduras", "Cooperação Militar", "Soberania"],
    assuntos: ["Operação Condor", "FBI Legat", "Buenos Aires", "Assassinatos Políticos", "CIE / DINA"],
    paisesMencionados: ["Estados Unidos", "Argentina", "Brasil", "Chile", "Uruguai"],
    sujeitosMencionados: ["Robert Scherrer", "Clarence M. Kelley", "Manuel Contreras", "Agentes da DINA"],
    numeroRegistroOficial: "FBI-LEGAT-BA-CABLE-19760928",
    quantidadePaginas: 4,
    urlOficialCustodia: "https://nsarchive.gwu.edu/briefing-book/southern-cone/2021-06-09/operation-condor",
    urlPdfOriginal: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB8/ch08-01.htm",
    contextoBrasil: "Documento-chave desclassificado que comprova a ciência imediata do FBI sobre a Operação Condor e a identificação de sua estrutura operacional clandestina no Cone Sul.",
    latitude: -34.6037,
    longitude: -58.3816,
    localidadeFoco: "Buenos Aires, Argentina (Embaixada dos EUA / FBI Legat)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Desclassificado Histórico",
  },
  {
    id: "DOC-FBI-VAULT-NUCLEAR-SOVEREIGNTY",
    titulo: "Investigação do FBI sobre Transferência de Tecnologia Nuclear Alemanha-Brasil (1975)",
    resumo: "Dossiê de contrainteligência do FBI investigando redes diplomáticas, empresas alemãs (KWU/Siemens) e cientistas brasileiros envolvidos no histórico Acordo Nuclear Brasil-Alemanha de 1975.",
    orgaoInteligencia: "FBI",
    nomeCompletoOrgao: "Federal Bureau of Investigation (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "1975-06-18",
    dataDesclassificacao: "2014-03-25",
    nivelClassificacaoOriginal: "Secreto",
    temas: ["Soberania", "Recursos Naturais", "Geopolítica", "Energia"],
    assuntos: ["Acordo Nuclear Brasil-Alemanha", "Não-Proliferação", "Enriquecimento de Urânio", "Espionagem Industrial"],
    paisesMencionados: ["Estados Unidos", "Brasil", "Alemanha"],
    sujeitosMencionados: ["Ernesto Geisel", "Helmut Schmidt", "Henry Kissinger", "Cientistas da CNEN"],
    numeroRegistroOficial: "FBI-HQ-FILE-65-72819-NUCLEAR-BRAZIL",
    quantidadePaginas: 19,
    urlOficialCustodia: "https://vault.fbi.gov/",
    urlPdfOriginal: "https://nsarchive.gwu.edu/briefing-book/nuclear-vault/2023-06-27/brazil-germany-nuclear-deal",
    contextoBrasil: "Evidencia como o FBI e a inteligência norte-americana monitoravam os passos da soberania energética e tecnológica brasileira na área nuclear.",
    latitude: 38.8951,
    longitude: -77.0364,
    localidadeFoco: "Washington, DC, EUA (FBI Headquarters)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Desclassificado Histórico",
  },
  {
    id: "DOC-FBI-IC3-CYBER-THREATS-2024",
    titulo: "FBI Internet Crime Report (IC3): Ameaças Cibernéticas Estatais, Ransomware e Infraestruturas Críticas",
    resumo: "Relatório público anual oficial da Divisão Cibernética do FBI compilando centenas de milhares de ataques, extorsões a redes de saúde e energia e espionagem cibernética estatal transnacional.",
    orgaoInteligencia: "FBI",
    nomeCompletoOrgao: "Federal Bureau of Investigation (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "2024-04-15",
    dataDesclassificacao: "2024-04-15",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Geopolítica", "Soberania", "Infraestrutura Crítica"],
    assuntos: ["Crime Cibernético", "Ransomware", "Infraestruturas Críticas", "Espionagem Corporativa", "IC3"],
    paisesMencionados: ["Estados Unidos", "Brasil", "China", "Rússia", "Canadá"],
    sujeitosMencionados: ["Direção Cyber Division FBI", "Internet Crime Complaint Center", "Empresas de Infraestrutura"],
    numeroRegistroOficial: "FBI-IC3-ANNUAL-REPORT-2024",
    quantidadePaginas: 48,
    urlOficialCustodia: "https://www.ic3.gov/Media/PDF/AnnualReport/2023_IC3Report.pdf",
    urlPdfOriginal: "https://www.ic3.gov/Media/PDF/AnnualReport/2023_IC3Report.pdf",
    contextoBrasil: "Documento oficial contemporâneo apontando ameaças de invasão a sistemas de controle industrial (SCADA) em saneamento, energia e mineração também incidentes no Brasil.",
    latitude: 39.2806,
    longitude: -80.3445,
    localidadeFoco: "Clarksburg, WV, EUA (FBI Criminal Justice Information Services Division)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-FBI-FOREIGN-INFLUENCE-ADVISORY",
    titulo: "Foreign Influence Task Force: Diretrizes Públicas sobre Desinformação e Segurança de Redes Críticas",
    resumo: "Boletim público oficial do FBI detalhando táticas de manipulação digital, operações psicológicas coordenadas e ataques a cabos e telecomunicações por potências estrangeiras.",
    orgaoInteligencia: "FBI",
    nomeCompletoOrgao: "Federal Bureau of Investigation (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "2024-08-20",
    dataDesclassificacao: "2024-08-20",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Soberania", "Geopolítica", "Telecomunicações"],
    assuntos: ["Foreign Influence", "Desinformação", "Segurança Eleitoral", "Telecomunicações", "FITF"],
    paisesMencionados: ["Estados Unidos", "Brasil", "União Europeia"],
    sujeitosMencionados: ["Foreign Influence Task Force", "Christopher Wray", "Autoridades Eleitorais"],
    numeroRegistroOficial: "FBI-FITF-PUBLIC-ADVISORY-2024-08",
    quantidadePaginas: 14,
    urlOficialCustodia: "https://www.fbi.gov/investigate/counterintelligence/foreign-influence",
    urlPdfOriginal: "https://www.fbi.gov/file-repository/fbi-foreign-influence-factsheet.pdf",
    contextoBrasil: "Alerta oficial sobre vetores de guerra híbrida e manipulação em massa que afetam processos democráticos em todo o hemisfério ocidental.",
    latitude: 38.8951,
    longitude: -77.0364,
    localidadeFoco: "Washington, DC, EUA (FBI Strategic Information & Operations Center)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },

  // ══════════════════════════════════════════════════════════════
  // 2. ESTADOS UNIDOS: NSA (NATIONAL SECURITY AGENCY)
  // ══════════════════════════════════════════════════════════════
  {
    id: "DOC-NSA-ECHELON-SYSTEM",
    titulo: "Projeto ECHELON: Dossiê Criptológico Desclassificado sobre a Rede Global de Interceptação por Satélites",
    resumo: "Registros históricos desclassificados da NSA e do National Security Archive detalhando a arquitetura global do sistema ECHELON operado com os países Five Eyes para captura de comunicações via Intelsat e cabos.",
    orgaoInteligencia: "NSA",
    nomeCompletoOrgao: "National Security Agency / Central Security Service (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "1988-07-15",
    dataDesclassificacao: "2001-09-05",
    nivelClassificacaoOriginal: "Ultrassecreto",
    temas: ["Soberania", "Geopolítica", "Telecomunicações", "Cooperação Militar"],
    assuntos: ["ECHELON", "SIGINT", "Interceptação de Satélites", "Five Eyes", "Intelsat"],
    paisesMencionados: ["Estados Unidos", "Reino Unido", "Canadá", "Austrália", "Nova Zelândia", "Brasil"],
    sujeitosMencionados: ["Direção da NSA", "Comitê ECHELON do Parlamento Europeu", "Estação Sugar Grove"],
    numeroRegistroOficial: "NSA-CSS-ECHELON-HISTORICAL-DOC-0901",
    quantidadePaginas: 42,
    urlOficialCustodia: "https://www.nsa.gov/Helpful-Links/NSA-FOIA/Declassification-Transparency-Initiatives/",
    urlPdfOriginal: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB23/index.html",
    contextoBrasil: "Revela as rotas de vigilância de sinais que interceptavam comunicações comerciais, diplomáticas e de recursos minerais e energéticos do Brasil e da América do Sul.",
    latitude: 39.1086,
    longitude: -76.7714,
    localidadeFoco: "Fort Meade, MD, EUA (NSA Headquarters)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Desclassificado Histórico",
  },
  {
    id: "DOC-NSA-FALKLANDS-SIGINT-1982",
    titulo: "Interceptações SIGINT da NSA na Guerra das Malvinas e Vigilância Eletrônica do Atlântico Sul (1982)",
    resumo: "Relatórios desclassificados de inteligência de sinais da NSA rastreando códigos navais argentinos, posições de esquadras e transmissões diplomáticas do Cone Sul durante o conflito de 1982.",
    orgaoInteligencia: "NSA",
    nomeCompletoOrgao: "National Security Agency / Central Security Service (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "1982-05-12",
    dataDesclassificacao: "2012-04-02",
    nivelClassificacaoOriginal: "Ultrassecreto",
    temas: ["Cooperação Militar", "Soberania", "Geopolítica"],
    assuntos: ["Guerra das Malvinas", "SIGINT", "Atlântico Sul", "Interceptação Naval", "GCHQ"],
    paisesMencionados: ["Estados Unidos", "Reino Unido", "Argentina", "Brasil"],
    sujeitosMencionados: ["Lincoln D. Faurer (Diretor NSA)", "Margaret Thatcher", "Leopoldo Galtieri"],
    numeroRegistroOficial: "NSA-SIGINT-FALKLANDS-DECLASS-1982-05",
    quantidadePaginas: 16,
    urlOficialCustodia: "https://www.nsa.gov/Helpful-Links/NSA-FOIA/",
    urlPdfOriginal: "https://nsarchive.gwu.edu/briefing-book/southern-cone/2022-04-02/falklands-malvinas-war-40th-anniversary",
    contextoBrasil: "Demonstra o monitoramento integral do espaço aéreo e marítimo do Atlântico Sul próximo às águas territoriais brasileiras pela aliança anglo-americana.",
    latitude: -51.7963,
    longitude: -59.5236,
    localidadeFoco: "Ilhas Malvinas / Atlântico Sul",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Desclassificado Histórico",
  },
  {
    id: "DOC-NSA-CUBAN-MISSILE-CARIBE-SIGINT",
    titulo: "Crise dos Mísseis e Postos de Escuta no Caribe: A História Criptológica da NSA na América Latina",
    resumo: "Estudo histórico desclassificado da Central Security Service sobre o papel da interceptação de rádio e radar na detecção de armamentos estratégicos soviéticos e vigilância de governos latino-americanos.",
    orgaoInteligencia: "NSA",
    nomeCompletoOrgao: "National Security Agency / Central Security Service (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "1963-01-15",
    dataDesclassificacao: "1998-10-16",
    nivelClassificacaoOriginal: "Ultrassecreto",
    temas: ["Geopolítica", "Cooperação Militar", "Soberania"],
    assuntos: ["Crise dos Mísseis", "SIGINT Caribe", "Cuba", "América Latina", "Guerra Fria"],
    paisesMencionados: ["Estados Unidos", "Cuba", "Rússia / União Soviética", "Brasil"],
    sujeitosMencionados: ["John F. Kennedy", "Robert McNamara", "Diretores da NSA"],
    numeroRegistroOficial: "NSA-CSS-CRYPTO-HISTORY-SERIES-CUBAN-CRISIS",
    quantidadePaginas: 75,
    urlOficialCustodia: "https://www.nsa.gov/History/Cryptologic-History/Historical-Publications/",
    urlPdfOriginal: "https://www.nsa.gov/portals/75/documents/news-features/declassified-documents/cryptologic-histories/cuba_missile_crisis.pdf",
    contextoBrasil: "Mapeia como a infraestrutura de SIGINT norte-americana foi estendida para abranger toda a América Latina na esteira da Revolução Cubana.",
    latitude: 21.5218,
    longitude: -77.7812,
    localidadeFoco: "Caribe / San Cristóbal, Cuba",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Desclassificado Histórico",
  },
  {
    id: "DOC-NSA-FISA-702-TRANSPARENCY",
    titulo: "Relatório Anual de Transparência Estatística sobre a Seção 702 da FISA e Vigilância Eletrônica Estrangeira",
    resumo: "Relatório público obrigatório emitido pelo Diretor de Inteligência Nacional (ODNI) e NSA detalhando métricas de coleta de comunicações digitais estrangeiras, alvos não americanos e garantias de conformidade legal.",
    orgaoInteligencia: "NSA / ODNI",
    nomeCompletoOrgao: "National Security Agency / Office of the Director of National Intelligence (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "2024-04-30",
    dataDesclassificacao: "2024-04-30",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Soberania", "Telecomunicações", "Direitos Humanos"],
    assuntos: ["FISA Section 702", "Vigilância Digital", "Coleta Estrangeira", "Transparência Governamental", "NSA / ODNI"],
    paisesMencionados: ["Estados Unidos", "Brasil", "União Europeia", "Canadá"],
    sujeitosMencionados: ["Avril Haines (ODNI)", "Timothy D. Haugh (Diretor NSA)", "Tribunal FISA (FISC)"],
    numeroRegistroOficial: "ODNI-NSA-ANNUAL-STATISTICAL-TRANSPARENCY-REPORT-CY2023",
    quantidadePaginas: 52,
    urlOficialCustodia: "https://www.intel.gov/ic-on-the-record/",
    urlPdfOriginal: "https://www.dni.gov/files/CLPT/documents/2024_ASTR_for_CY2023.pdf",
    contextoBrasil: "Documento essencial de auditoria pública revelando a escala anual de milhões de comunicações de cidadãos e empresas fora dos EUA sujeitas à coleta sob autoridade da Seção 702.",
    latitude: 38.9328,
    longitude: -77.1518,
    localidadeFoco: "McLean, VA, EUA (ODNI Headquarters)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-NSA-CISA-INFRA-CRITICA",
    titulo: "Diretriz Conjunta NSA/CISA para Proteção de Redes Operacionais Industriais e Recursos Hídricos",
    resumo: "Guia oficial de cibersegurança e mitigação técnica emitido pela NSA Cybersecurity Directorate com CISA orientando operadores de saneamento, barragens e redes elétricas contra sabotagens cibernéticas estatais.",
    orgaoInteligencia: "NSA",
    nomeCompletoOrgao: "National Security Agency (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "2024-02-07",
    dataDesclassificacao: "2024-02-07",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Recursos Naturais", "Infraestrutura Crítica", "Soberania"],
    assuntos: ["Sistemas de Água e Esgoto", "SCADA", "Cibersegurança Industrial", "NSA CSA", "Infraestrutura Crítica"],
    paisesMencionados: ["Estados Unidos", "Brasil", "Canadá"],
    sujeitosMencionados: ["NSA Cybersecurity Directorate", "CISA", "Operadores de Recursos Hídricos"],
    numeroRegistroOficial: "NSA-CISA-CSA-WATER-SECTOR-SECURITY-2024",
    quantidadePaginas: 18,
    urlOficialCustodia: "https://www.nsa.gov/Press-Room/Cybersecurity-Advisories-Guidance/",
    urlPdfOriginal: "https://media.defense.gov/2024/Feb/07/2003389886/-1/-1/0/CSA-TOP-CYBER-THREATS-WATER-SECTOR.PDF",
    contextoBrasil: "Diretrizes técnicas que impactam concessionárias de água e barragens de rejeitos que utilizam sistemas de telemetria e controle digital conectados.",
    latitude: 38.8799,
    longitude: -77.1068,
    localidadeFoco: "Arlington, VA, EUA (CISA / NSA Cyber Headquarters)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-NSA-POST-QUANTUM-ROADMAP",
    titulo: "Roteiro de Transição da NSA para Criptografia Pós-Quântica (PQC) e Padrões de Segurança Governamental 2030",
    resumo: "Diretriz pública estratégica da NSA determinando prazos para substituição de algoritmos RSA e ECC vulneráveis a computadores quânticos em redes de defesa e inteligência governamentais.",
    orgaoInteligencia: "NSA",
    nomeCompletoOrgao: "National Security Agency (EUA)",
    paisOrigem: "Estados Unidos",
    codigoIsoPais: "USA",
    bandeiraPais: "🇺🇸",
    continente: "América do Norte",
    dataPublicacao: "2024-08-13",
    dataDesclassificacao: "2024-08-13",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Geopolítica", "Soberania", "Tecnologia"],
    assuntos: ["Criptografia Pós-Quântica", "Computação Quântica", "CNSA 2.0", "NSA Cybersecurity", "PQC"],
    paisesMencionados: ["Estados Unidos", "Brasil", "União Europeia", "Canadá"],
    sujeitosMencionados: ["NSA Cybersecurity Directorate", "NIST", "Comunidade Criptográfica"],
    numeroRegistroOficial: "NSA-CNSA-2.0-PQC-IMPLEMENTATION-ROADMAP",
    quantidadePaginas: 24,
    urlOficialCustodia: "https://www.nsa.gov/Cybersecurity/Post-Quantum-Cybersecurity-Resources/",
    urlPdfOriginal: "https://media.defense.gov/2022/Sep/07/2003071834/-1/-1/0/CSA_CNSA_2.0_ALGORITHMS_.PDF",
    contextoBrasil: "Define os novos padrões globais de criptografia que bancos centrais, governos e empresas mineradoras e de petróleo precisam adotar para não terem seus dados interceptados e decifrados no futuro.",
    latitude: 39.1086,
    longitude: -76.7714,
    localidadeFoco: "Fort Meade, MD, EUA (NSA Cybersecurity Directorate)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },

  // ══════════════════════════════════════════════════════════════
  // 3. FIVE EYES: REINO UNIDO, CANADÁ, AUSTRÁLIA E NOVA ZELÂNDIA
  // ══════════════════════════════════════════════════════════════
  {
    id: "DOC-GCHQ-UK-ANNUAL-CYBER-REVIEW",
    titulo: "Annual Cyber Review do NCSC/GCHQ: Proteção de Cabos Submarinos e Soberania Digital",
    resumo: "Relatório público anual do centro de inteligência cibernética do GCHQ britânico detalhando ameaças a cabos submarinos do Atlântico, satélites de telecomunicações e resiliência de redes soberanas.",
    orgaoInteligencia: "GCHQ",
    nomeCompletoOrgao: "Government Communications Headquarters / NCSC (Reino Unido)",
    paisOrigem: "Reino Unido",
    codigoIsoPais: "GBR",
    bandeiraPais: "🇬🇧",
    continente: "Europa",
    dataPublicacao: "2024-03-19",
    dataDesclassificacao: "2024-03-19",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Soberania", "Telecomunicações", "Geopolítica"],
    assuntos: ["GCHQ", "Cabos Submarinos", "Cibersegurança", "NCSC", "Five Eyes"],
    paisesMencionados: ["Reino Unido", "Estados Unidos", "Brasil", "França", "Alemanha"],
    sujeitosMencionados: ["Anne Keast-Butler (Diretora GCHQ)", "Lindy Cameron", "Comunidade Five Eyes"],
    numeroRegistroOficial: "UK-GCHQ-NCSC-ANNUAL-REVIEW-2023-2024",
    quantidadePaginas: 46,
    urlOficialCustodia: "https://www.ncsc.gov.uk/section/about-ncsc/annual-reviews",
    urlPdfOriginal: "https://www.ncsc.gov.uk/files/NCSC%20Annual%20Review%202023.pdf",
    contextoBrasil: "O Brasil é o hub de amarração dos principais cabos de dados transatlânticos que conectam a América do Sul à Europa e ao Reino Unido, foco de monitoramento mútuo.",
    latitude: 51.8979,
    longitude: -2.1228,
    localidadeFoco: "Cheltenham, Reino Unido (GCHQ The Doughnut)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-MI6-UK-JIC-AMAZON-RESOURCES",
    titulo: "Joint Intelligence Committee (JIC): Avaliação Estratégica sobre Petróleo e Recursos Naturais da América do Sul",
    resumo: "Dossiê desclassificado do Comitê Conjunto de Inteligência britânico avaliando a nacionalização de recursos, bacias petrolíferas offshore e a geopolítica do minério de ferro brasileiro durante a Guerra Fria.",
    orgaoInteligencia: "MI6 / JIC",
    nomeCompletoOrgao: "Secret Intelligence Service / Joint Intelligence Committee (Reino Unido)",
    paisOrigem: "Reino Unido",
    codigoIsoPais: "GBR",
    bandeiraPais: "🇬🇧",
    continente: "Europa",
    dataPublicacao: "1978-05-14",
    dataDesclassificacao: "2010-09-22",
    nivelClassificacaoOriginal: "Ultrassecreto",
    temas: ["Recursos Naturais", "Soberania", "Geopolítica"],
    assuntos: ["Petróleo Offshore", "Minério de Ferro", "América Latina", "JIC", "Nacionalismo Econômico"],
    paisesMencionados: ["Reino Unido", "Brasil", "Venezuela", "Estados Unidos"],
    sujeitosMencionados: ["Sir Antony Duff", "James Callaghan", "Ernesto Geisel"],
    numeroRegistroOficial: "UK-TNA-CAB-186-JIC-1978-MEMO-54",
    quantidadePaginas: 22,
    urlOficialCustodia: "https://www.nationalarchives.gov.uk/",
    urlPdfOriginal: "https://discovery.nationalarchives.gov.uk/details/r/C10459",
    contextoBrasil: "Revela como a inteligência britânica analisava os monopólios estatais da Petrobras e da Vale e a independência diplomática brasileira face aos EUA.",
    latitude: 51.4851,
    longitude: -0.1245,
    localidadeFoco: "Londres, Reino Unido (Vauxhall Cross - MI6 Headquarters)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Desclassificado Histórico",
  },
  {
    id: "DOC-CSE-CAN-CYBER-THREAT-ASSESSMENT",
    titulo: "National Cyber Threat Assessment do CSE: Espionagem Industrial no Setor de Mineração e Energia",
    resumo: "Avaliação pública oficial de inteligência do Communications Security Establishment canadense alertando mineradoras e concessionárias contra espionagem patrocinada por Estados e roubo de patentes de lítio e nióbio.",
    orgaoInteligencia: "CSE",
    nomeCompletoOrgao: "Communications Security Establishment (Canadá)",
    paisOrigem: "Canadá",
    codigoIsoPais: "CAN",
    bandeiraPais: "🇨🇦",
    continente: "América do Norte",
    dataPublicacao: "2024-03-12",
    dataDesclassificacao: "2024-03-12",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Recursos Naturais", "Soberania", "Geopolítica"],
    assuntos: ["Minerais Críticos", "Espionagem Industrial", "CSE", "Lítio", "Cibersegurança Minerária"],
    paisesMencionados: ["Canadá", "Brasil", "China", "Estados Unidos", "Austrália"],
    sujeitosMencionados: ["Caroline Xavier (Chefe do CSE)", "Canadian Centre for Cyber Security"],
    numeroRegistroOficial: "CAN-CSE-NCTA-MINING-2023-2024",
    quantidadePaginas: 38,
    urlOficialCustodia: "https://www.cyber.gc.ca/en/guidance/national-cyber-threat-assessment",
    urlPdfOriginal: "https://www.cyber.gc.ca/sites/default/files/2023-10/national-cyber-threat-assessment-2023-2024-e.pdf",
    contextoBrasil: "Conecta-se diretamente às mineradoras canadenses com operações em Minas Gerais (Vale do Jequitinhonha / Sigma Lithium) e no Pará (Belo Sun), altamente visadas por ataques cibernéticos industriais.",
    latitude: 45.3789,
    longitude: -75.6421,
    localidadeFoco: "Ottawa, ON, Canadá (CSE Headquarters / Edward Drake Building)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-CSIS-CAN-FOREIGN-INTERFERENCE",
    titulo: "Relatório Público de Inteligência do CSIS sobre Interferência Estrangeira e Proteção de Ativos Estratégicos",
    resumo: "Relatório anual de inteligência e segurança pública do CSIS detalhando operações de inteligência humana (HUMINT) e financeira visando infraestruturas portuárias, mineração e centros universitários de tecnologia.",
    orgaoInteligencia: "CSIS",
    nomeCompletoOrgao: "Canadian Security Intelligence Service (Canadá)",
    paisOrigem: "Canadá",
    codigoIsoPais: "CAN",
    bandeiraPais: "🇨🇦",
    continente: "América do Norte",
    dataPublicacao: "2024-05-02",
    dataDesclassificacao: "2024-05-02",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Soberania", "Geopolítica", "Recursos Naturais"],
    assuntos: ["Interferência Estrangeira", "CSIS", "Segurança Econômica", "Minerais Estratégicos", "Five Eyes"],
    paisesMencionados: ["Canadá", "Estados Unidos", "Brasil", "Índia", "China"],
    sujeitosMencionados: ["David Vigneault (Diretor CSIS)", "Comitê Parlamentar NSICOP"],
    numeroRegistroOficial: "CAN-CSIS-PUBLIC-REPORT-2023",
    quantidadePaginas: 44,
    urlOficialCustodia: "https://www.canada.ca/en/security-intelligence-service.html",
    urlPdfOriginal: "https://www.canada.ca/content/dam/csis-scrs/documents/publications/2023/csis-public-report-2023-en.pdf",
    contextoBrasil: "Cruza a atuação de fundos soberanos e corporações multinacionais que controlam concessões no Brasil e negociam ações na Bolsa de Toronto (TSX).",
    latitude: 45.4345,
    longitude: -75.6189,
    localidadeFoco: "Ottawa, ON, Canadá (CSIS National Headquarters)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-ASD-AUS-PINE-GAP-DECLASS",
    titulo: "Estação Conjunta de Defesa Pine Gap: Registros Desclassificados da Vigilância de Sinais (ASD / NSA)",
    resumo: "Dossiê desclassificado nos Arquivos Nacionais da Austrália detalhando as operações da estação Pine Gap no deserto australiano, interceptando telemetria de mísseis, transmissões via satélite e tráfego marítimo no hemisfério sul.",
    orgaoInteligencia: "ASD",
    nomeCompletoOrgao: "Australian Signals Directorate (Austrália)",
    paisOrigem: "Austrália",
    codigoIsoPais: "AUS",
    bandeiraPais: "🇦🇺",
    continente: "Oceania",
    dataPublicacao: "1977-11-10",
    dataDesclassificacao: "2015-08-14",
    nivelClassificacaoOriginal: "Ultrassecreto",
    temas: ["Cooperação Militar", "Soberania", "Geopolítica"],
    assuntos: ["Pine Gap", "SIGINT", "ASD", "NSA", "Five Eyes", "Hemisfério Sul"],
    paisesMencionados: ["Austrália", "Estados Unidos", "Reino Unido", "Brasil"],
    sujeitosMencionados: ["Malcolm Fraser", "Direção do DSD/ASD", "Oficiais da NSA"],
    numeroRegistroOficial: "NAA-A1838-PINE-GAP-DECLASS-77",
    quantidadePaginas: 34,
    urlOficialCustodia: "https://www.cyber.gov.au/about-us/reports-and-statistics",
    urlPdfOriginal: "https://recordsearch.naa.gov.au/SearchNRetrieve/Interface/ListingReports/ItemsListing.aspx",
    contextoBrasil: "Evidencia o papel central de Pine Gap como o olho eletrônico da aliança Five Eyes no hemisfério sul, monitorando órbitas e satélites sobre o Atlântico e Pacífico.",
    latitude: -23.7989,
    longitude: 133.7372,
    localidadeFoco: "Alice Springs, NT, Austrália (Joint Defence Facility Pine Gap)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Desclassificado Histórico",
  },
  {
    id: "DOC-NZSIS-NZ-SECURITY-THREAT-ENV",
    titulo: "New Zealand's Security Threat Environment: Avaliação de Inteligência Desclassificada do NZSIS",
    resumo: "Relatório público desclassificado sem precedentes divulgado pelo serviço de segurança da Nova Zelândia mapeando espionagem estrangeira no Pacífico Sul, monitoramento de cabos e soberania de nações insulares.",
    orgaoInteligencia: "NZSIS",
    nomeCompletoOrgao: "New Zealand Security Intelligence Service (Nova Zelândia)",
    paisOrigem: "Nova Zelândia",
    codigoIsoPais: "NZL",
    bandeiraPais: "🇳🇿",
    continente: "Oceania",
    dataPublicacao: "2023-08-11",
    dataDesclassificacao: "2023-08-11",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Geopolítica", "Soberania", "Telecomunicações"],
    assuntos: ["NZSIS", "Pacífico Sul", "Cabos de Dados", "Five Eyes", "Espionagem Externa"],
    paisesMencionados: ["Nova Zelândia", "Austrália", "Estados Unidos", "Brasil"],
    sujeitosMencionados: ["Andrew Hampton (Diretor-Geral NZSIS)", "Comunidade de Inteligência"],
    numeroRegistroOficial: "NZ-NZSIS-SECURITY-THREAT-REPORT-2023",
    quantidadePaginas: 36,
    urlOficialCustodia: "https://www.nzsis.govt.nz/our-work/public-reports/",
    urlPdfOriginal: "https://www.nzsis.govt.nz/assets/NZSIS-Documents/New-Zealands-Security-Threat-Environment-2023.pdf",
    contextoBrasil: "Mostra a expansão da transparência governamental nos Five Eyes, servindo de paradigma para desclassificação de documentos de inteligência no Sul Global.",
    latitude: -41.2865,
    longitude: 174.7762,
    localidadeFoco: "Wellington, Nova Zelândia (Pipitea House / NZSIS Headquarters)",
    aliancaInteligencia: "Five Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },

  // ══════════════════════════════════════════════════════════════
  // 4. NINE EYES: DINAMARCA, NORUEGA, FRANÇA E HOLANDA
  // ══════════════════════════════════════════════════════════════
  {
    id: "DOC-FE-DNK-UDSYN-INTELLIGENCE",
    titulo: "Udsyn - Avaliação Anual de Riscos e Inteligência do Serviço de Inteligência de Defesa da Dinamarca (FE)",
    resumo: "Relatório estratégico público anual do Forsvarets Efterretningstjeneste (FE / DDIS dinamarquês) detalhando espionagem sobre rotas marítimas do Ártico, segurança de cabos submarinos e a parceria Nine Eyes.",
    orgaoInteligencia: "FE",
    nomeCompletoOrgao: "Forsvarets Efterretningstjeneste / DDIS (Dinamarca)",
    paisOrigem: "Dinamarca",
    codigoIsoPais: "DNK",
    bandeiraPais: "🇩🇰",
    continente: "Europa",
    dataPublicacao: "2024-02-28",
    dataDesclassificacao: "2024-02-28",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Geopolítica", "Soberania", "Recursos Naturais"],
    assuntos: ["Ártico", "Cabos Submarinos", "Nine Eyes", "FE / DDIS", "Vigilância de Sinais"],
    paisesMencionados: ["Dinamarca", "Groenlândia", "Estados Unidos", "Noruega", "Brasil"],
    sujeitosMencionados: ["Svand E. Poulsen (Direção FE)", "Ministério da Defesa Dinamarquês"],
    numeroRegistroOficial: "DNK-FE-UDSYN-RISK-ASSESSMENT-2024",
    quantidadePaginas: 58,
    urlOficialCustodia: "https://www.fe-ddis.dk/da/vurderinger/",
    urlPdfOriginal: "https://www.fe-ddis.dk/globalassets/fe/dokumenter/2023/efterretningsmassige-risikovurderinger/-udsyn-2023-.pdf",
    contextoBrasil: "A Dinamarca e o grupo Nine Eyes integram pontos de controle de cabos de fibra óptica intercontinentais que roteiam tráfego corporativo e governamental do Brasil.",
    latitude: 55.6761,
    longitude: 12.5683,
    localidadeFoco: "Copenhague, Dinamarca (Kastellet / FE Headquarters)",
    aliancaInteligencia: "Nine Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-NIS-NOR-FOKUS-ARCTIC-RESOURCES",
    titulo: "FOKUS: Avaliação de Inteligência Estratégica sobre Fronteiras de Energia e Cabos do Mar do Norte (NIS Noruega)",
    resumo: "Relatório anual oficial desclassificado do Etterretningstjenesten (Serviço de Inteligência Norueguês - NIS) sobre ameaças físicas e cibernéticas a plataformas de petróleo offshore, gasodutos e cabos do Atlântico Norte.",
    orgaoInteligencia: "NIS",
    nomeCompletoOrgao: "Etterretningstjenesten / Norwegian Intelligence Service (Noruega)",
    paisOrigem: "Noruega",
    codigoIsoPais: "NOR",
    bandeiraPais: "🇳🇴",
    continente: "Europa",
    dataPublicacao: "2024-02-12",
    dataDesclassificacao: "2024-02-12",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Recursos Naturais", "Soberania", "Energia", "Geopolítica"],
    assuntos: ["Petróleo Offshore", "Gasodutos Submarinos", "NIS FOKUS", "Nine Eyes", "Guerra Híbrida"],
    paisesMencionados: ["Noruega", "Reino Unido", "Alemanha", "Brasil", "Estados Unidos"],
    sujeitosMencionados: ["Nils Andreas Stensønes (Vice-Almirante / Chefe NIS)", "Ministério da Defesa Norueguês"],
    numeroRegistroOficial: "NOR-NIS-FOKUS-ANNUAL-ASSESSMENT-2024",
    quantidadePaginas: 104,
    urlOficialCustodia: "https://www.forsvaret.no/aktuelt-og-presse/publikasjoner/fokus",
    urlPdfOriginal: "https://www.forsvaret.no/aktuelt-og-presse/publikasjoner/fokus/Fokus-2024-en.pdf",
    contextoBrasil: "A Noruega é grande investidora no setor de óleo, gás e alumínio no Brasil (Equinor no pré-sal e Norsk Hydro no Pará), com paralelos diretos nas diretrizes de segurança de infraestrutura marítima.",
    latitude: 59.9139,
    longitude: 10.7522,
    localidadeFoco: "Oslo / Lutvann, Noruega (Etterretningstjenesten Headquarters)",
    aliancaInteligencia: "Nine Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-DGSI-FRA-ECONOMIC-COUNTERINTEL",
    titulo: "Relatório de Segurança Interna da DGSI: Proteção do Complexo Aeroespacial, Nuclear e Contraespionagem Econômica",
    resumo: "Documento oficial público da Direction Générale de la Sécurité Intérieure francesa detalhando operações contraespionagem de potências estrangeiras visando fornecedores de defesa, satélites e tecnologia de energia.",
    orgaoInteligencia: "DGSI",
    nomeCompletoOrgao: "Direction Générale de la Sécurité Intérieure (França)",
    paisOrigem: "França",
    codigoIsoPais: "FRA",
    bandeiraPais: "🇫🇷",
    continente: "Europa",
    dataPublicacao: "2023-11-15",
    dataDesclassificacao: "2023-11-15",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Soberania", "Tecnologia", "Geopolítica"],
    assuntos: ["Contraespionagem Econômica", "Setor Nuclear", "DGSI", "Aeroespacial", "Nine Eyes"],
    paisesMencionados: ["França", "Alemanha", "Estados Unidos", "Brasil"],
    sujeitosMencionados: ["Nicolas Lerner (Diretor DGSI)", "Ministère de l'Intérieur"],
    numeroRegistroOficial: "FRA-DGSI-RAPPORT-SECURITE-ECONOMIQUE-2023",
    quantidadePaginas: 32,
    urlOficialCustodia: "https://www.interieur.gouv.fr/",
    urlPdfOriginal: "https://www.defense.gouv.fr/dgris/politique-defense-francaise",
    contextoBrasil: "Cruza acordos de transferência de tecnologia militar estratégica França-Brasil, como o programa de submarinos PROSUB (Scorpène e nuclear) em Itaguaí/RJ.",
    latitude: 48.8924,
    longitude: 2.2901,
    localidadeFoco: "Levallois-Perret, França (DGSI Headquarters)",
    aliancaInteligencia: "Nine Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-MIVD-NLD-SUBSEA-INFRASTRUCTURE",
    titulo: "Relatório Conjunto de Inteligência AIVD/MIVD: Ameaças a Cabos Submarinos e Infraestrutura Portuária de Roterdã",
    resumo: "Relatório anual de inteligência militar e civil dos Países Baixos sobre mapeamento clandestino de infraestruturas do Mar do Norte, cabos de telecomunicações e vulnerabilidades logísticas de portos europeus.",
    orgaoInteligencia: "AIVD / MIVD",
    nomeCompletoOrgao: "Algemene Inlichtingen- en Veiligheidsdienst / Militaire Inlichtingen (Holanda)",
    paisOrigem: "Holanda",
    codigoIsoPais: "NLD",
    bandeiraPais: "🇳🇱",
    continente: "Europa",
    dataPublicacao: "2024-04-23",
    dataDesclassificacao: "2024-04-23",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Geopolítica", "Soberania", "Infraestrutura Crítica"],
    assuntos: ["Porto de Roterdã", "Cabos de Fibra Óptica", "AIVD", "MIVD", "Espionagem Marítima"],
    paisesMencionados: ["Holanda", "Reino Unido", "Alemanha", "Brasil", "Estados Unidos"],
    sujeitosMencionados: ["Erik Akerboom (Diretor-Geral AIVD)", "Peter Reesink (Diretor MIVD)"],
    numeroRegistroOficial: "NLD-AIVD-MIVD-JAARVERSLAG-2023",
    quantidadePaginas: 76,
    urlOficialCustodia: "https://www.aivd.nl/onderwerpen/jaarverslagen",
    urlPdfOriginal: "https://files.aivd.nl/binaries/aivd-nl/documenten/jaarverslagen/2024/04/23/aivd-jaarverslag-2023/AIVD_Jaarverslag_2023.pdf",
    contextoBrasil: "O Porto de Roterdã é o principal terminal de entrada do minério de ferro e grãos brasileiros na Europa, além de sede corporativa de holdings minerárias ligadas à tragédia de Mariana e da Braskem.",
    latitude: 52.0575,
    longitude: 4.3164,
    localidadeFoco: "Haia, Holanda (AIVD Headquarters)",
    aliancaInteligencia: "Nine Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },

  // ══════════════════════════════════════════════════════════════
  // 5. TWELVE EYES / FOURTEEN EYES: ALEMANHA, BÉLGICA, ITÁLIA, ESPANHA E SUÉCIA
  // ══════════════════════════════════════════════════════════════
  {
    id: "DOC-BND-DEU-RUBICON-CRYPTO-AG",
    titulo: "Operação Rubicon: Histórico Desclassificado da Crypto AG e Quebra de Códigos Diplomáticos (BND / CIA)",
    resumo: "Investigação histórica oficial desclassificada pelo Bundesarchiv e pelo serviço secreto alemão (BND) confirmando a propriedade secreta da empresa suíça Crypto AG entre 1970 e 1993 com a CIA, decifrando mensagens confidenciais da América Latina.",
    orgaoInteligencia: "BND",
    nomeCompletoOrgao: "Bundesnachrichtendienst (Alemanha)",
    paisOrigem: "Alemanha",
    codigoIsoPais: "DEU",
    bandeiraPais: "🇩🇪",
    continente: "Europa",
    dataPublicacao: "1993-10-15",
    dataDesclassificacao: "2020-02-11",
    nivelClassificacaoOriginal: "Ultrassecreto",
    temas: ["Soberania", "Geopolítica", "Telecomunicações", "Ditaduras"],
    assuntos: ["Operação Rubicon", "Crypto AG", "BND", "CIA", "Decifração Diplomática", "América Latina"],
    paisesMencionados: ["Alemanha", "Estados Unidos", "Suíça", "Brasil", "Argentina", "Chile"],
    sujeitosMencionados: ["Diretores do BND", "William J. Casey", "Boris Hagelin"],
    numeroRegistroOficial: "BND-BUNDESARCHIV-RUBICON-DECLASS-2020",
    quantidadePaginas: 65,
    urlOficialCustodia: "https://www.verfassungsschutz.de/",
    urlPdfOriginal: "https://nsarchive.gwu.edu/briefing-book/intelligence/2020-02-11/crypto-ag-cia-bnd-secret-history",
    contextoBrasil: "Revelou que embaixadas, forças armadas e ministérios brasileiros utilizaram máquinas de criptografia da Crypto AG cujas chaves mestras pertenciam à inteligência alemã e norte-americana durante a Guerra Fria.",
    latitude: 52.5333,
    longitude: 13.3777,
    localidadeFoco: "Berlim, Alemanha (BND-Zentrale Chausseestraße)",
    aliancaInteligencia: "Twelve Eyes",
    naturezaDocumento: "Desclassificado Histórico",
  },
  {
    id: "DOC-BFV-DEU-VERFASSUNGSSCHUTZBERICHT",
    titulo: "Verfassungsschutzbericht da Alemanha: Relatório de Proteção Constitucional sobre Espionagem Industrial e Ciberataques",
    resumo: "Relatório anual público oficial do Bundesamt für Verfassungsschutz alemão detalhando operações de inteligência contra grandes indústrias automotivas, químicas e de semicondutores.",
    orgaoInteligencia: "BfV",
    nomeCompletoOrgao: "Bundesamt für Verfassungsschutz (Alemanha)",
    paisOrigem: "Alemanha",
    codigoIsoPais: "DEU",
    bandeiraPais: "🇩🇪",
    continente: "Europa",
    dataPublicacao: "2024-06-18",
    dataDesclassificacao: "2024-06-18",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Geopolítica", "Soberania", "Tecnologia"],
    assuntos: ["Espionagem Industrial", "BfV", "Proteção Constitucional", "Ciberdefesa", "Twelve Eyes"],
    paisesMencionados: ["Alemanha", "China", "Rússia", "Estados Unidos", "Brasil"],
    sujeitosMencionados: ["Thomas Haldenwang (Presidente BfV)", "Nancy Faeser (Ministra do Interior)"],
    numeroRegistroOficial: "DEU-BFV-VERFASSUNGSSCHUTZBERICHT-2023",
    quantidadePaginas: 380,
    urlOficialCustodia: "https://www.verfassungsschutz.de/DE/verfassungsschutzberichte/verfassungsschutzberichte_node.html",
    urlPdfOriginal: "https://www.verfassungsschutz.de/SharedDocs/publikationen/DE/verfassungsschutzberichte/2024-06-18-verfassungsschutzbericht-2023.pdf?__blob=publicationFile&v=8",
    contextoBrasil: "Cruza a atuação de multinacionais alemãs de siderurgia (Thyssenkrupp), químicos (BASF, Bayer) e energia no Brasil, monitoradas quanto a vazamentos de propriedade intelectual.",
    latitude: 50.9375,
    longitude: 6.9603,
    localidadeFoco: "Colônia, Alemanha (BfV Headquarters)",
    aliancaInteligencia: "Twelve Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-VSSE-BEL-NATO-EU-SECURITY",
    titulo: "Rapport d'Activités da VSSE Bélgica: Proteção das Sedes da OTAN e União Europeia contra Espionagem Externa",
    resumo: "Relatório público oficial de inteligência da Veiligheid van de Staat belga sobre proteção das capitais diplomáticas e instituições comunitárias em Bruxelas contra infiltrações e lobby oculto.",
    orgaoInteligencia: "VSSE",
    nomeCompletoOrgao: "Veiligheid van de Staat / Sûreté de l'État (Bélgica)",
    paisOrigem: "Bélgica",
    codigoIsoPais: "BEL",
    bandeiraPais: "🇧🇪",
    continente: "Europa",
    dataPublicacao: "2023-12-05",
    dataDesclassificacao: "2023-12-05",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Geopolítica", "Soberania", "Direitos Humanos"],
    assuntos: ["OTAN", "União Europeia", "VSSE", "Contraespionagem Diplomática", "Bruxelas"],
    paisesMencionados: ["Bélgica", "Estados Unidos", "Brasil", "União Europeia"],
    sujeitosMencionados: ["Francisca Bostyn (Direção VSSE)", "Autoridades de Justiça da Bélgica"],
    numeroRegistroOficial: "BEL-VSSE-ACTIVITY-REPORT-2022-2023",
    quantidadePaginas: 50,
    urlOficialCustodia: "https://vsse.be/fr/rapports-dactivites",
    urlPdfOriginal: "https://vsse.be/sites/default/files/2023-12/VSSE_Rapport_Activites_2022-2023_FR.pdf",
    contextoBrasil: "Bruxelas é o centro onde são negociados o Acordo Mercosul-União Europeia e a Diretiva de Devida Diligência (CSDDD) e Antidesmatamento (EUDR), com intensa vigilância de lobistas e delegações diplomáticas.",
    latitude: 50.8503,
    longitude: 4.3517,
    localidadeFoco: "Bruxelas, Bélgica (VSSE / Quartier Général)",
    aliancaInteligencia: "Twelve Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-AISE-ITA-MEDITERRANEAN-SECURITY",
    titulo: "Relazione sulla Politica dell'Informazione per la Sicurezza: Rotas Marítimas, Energia e Inteligência da Itália",
    resumo: "Relatório anual público oficial ao Parlamento italiano pelo Dipartimento delle Informazioni per la Sicurezza (DIS/AISE) detalhando segurança de gasodutos transfronteiriços, minerais críticos e cabos submarinos.",
    orgaoInteligencia: "AISE / DIS",
    nomeCompletoOrgao: "Agenzia Informazioni e Sicurezza Esterna / DIS (Itália)",
    paisOrigem: "Itália",
    codigoIsoPais: "ITA",
    bandeiraPais: "🇮🇹",
    continente: "Europa",
    dataPublicacao: "2024-02-27",
    dataDesclassificacao: "2024-02-27",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Energia", "Soberania", "Geopolítica"],
    assuntos: ["DIS", "AISE", "Segurança Energética", "Cabos de Comunicação", "Twelve Eyes"],
    paisesMencionados: ["Itália", "França", "Brasil", "Estados Unidos"],
    sujeitosMencionados: ["Elisabetta Belloni (Diretora-Geral DIS)", "Giovanni Caravelli (Diretor AISE)"],
    numeroRegistroOficial: "ITA-DIS-AISE-RELAZIONE-PARLAMENTO-2023",
    quantidadePaginas: 136,
    urlOficialCustodia: "https://www.sicurezzanazionale.gov.it/",
    urlPdfOriginal: "https://www.sicurezzanazionale.gov.it/sis_r смыс/wp-content/uploads/2024/02/Relazione-annuale-2023.pdf",
    contextoBrasil: "A Itália detém forte presença em infraestruturas elétricas e de telecomunicações no Brasil (concessionárias Enel e TIM Brasil), com monitoramento de risco regulatório e de segurança.",
    latitude: 41.9028,
    longitude: 12.4964,
    localidadeFoco: "Roma, Itália (Palazzo Dante / DIS Headquarters)",
    aliancaInteligencia: "Twelve Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-CNI-ESP-CCN-CERT-CYBERTHREATS",
    titulo: "Ciberamenazas y Tendencias del CCN-CERT: Proteção de Infraestruturas Críticas e Telecomunicações da Espanha (CNI)",
    resumo: "Relatório oficial público anual do Centro Criptológico Nacional do CNI espanhol analisando ciberataques contra operadores essenciais de energia, bancos e redes de telecomunicação na Espanha e na Ibero-América.",
    orgaoInteligencia: "CNI / CCN-CERT",
    nomeCompletoOrgao: "Centro Nacional de Inteligencia / Centro Criptológico Nacional (Espanha)",
    paisOrigem: "Espanha",
    codigoIsoPais: "ESP",
    bandeiraPais: "🇪🇸",
    continente: "Europa",
    dataPublicacao: "2024-05-10",
    dataDesclassificacao: "2024-05-10",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Geopolítica", "Soberania", "Telecomunicações"],
    assuntos: ["CNI", "CCN-CERT", "Ciberamenazas", "Infraestruturas Críticas", "Ibero-América"],
    paisesMencionados: ["Espanha", "Brasil", "Estados Unidos", "União Europeia"],
    sujeitosMencionados: ["Esperanza Casteleiro (Diretora CNI)", "Chefia do CCN-CERT"],
    numeroRegistroOficial: "ESP-CNI-CCN-CERT-IA-14-24",
    quantidadePaginas: 88,
    urlOficialCustodia: "https://www.ccn-cert.cni.es/",
    urlPdfOriginal: "https://www.ccn-cert.cni.es/informes/informes-ccn-cert-publicos/5867-ccn-cert-ia-14-24-ciberamenazas-y-tendencias-edicion-2024/file.html",
    contextoBrasil: "Bancos e concessionárias de telecomunicações de origem espanhola (Santander Brasil e Telefônica/Vivo) controlam dados e transações vitais de milhões de brasileiros.",
    latitude: 40.4532,
    longitude: -3.7492,
    localidadeFoco: "Madri, Espanha (CNI Headquarters / Ctra. de La Coruña)",
    aliancaInteligencia: "Twelve Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-MUST-SWE-ARSOVERSIKT-BALTIC",
    titulo: "Årsöversikt Försvarsunderrättelsetjänst do MUST: Inteligência Militar e Vigilância do Mar Báltico (Suécia)",
    resumo: "Avaliação pública anual desclassificada do Serviço de Inteligência e Segurança Militar da Suécia (MUST) cobrindo vigilância submarina, proteção de infraestrutura marítima e inteligência de sinais.",
    orgaoInteligencia: "MUST",
    nomeCompletoOrgao: "Militära underrättelse- och säkerhetstjänsten (Suécia)",
    paisOrigem: "Suécia",
    codigoIsoPais: "SWE",
    bandeiraPais: "🇸🇪",
    continente: "Europa",
    dataPublicacao: "2024-03-05",
    dataDesclassificacao: "2024-03-05",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Cooperação Militar", "Soberania", "Geopolítica"],
    assuntos: ["MUST", "Mar Báltico", "SIGINT", "Infraestrutura Marítima", "Fourteen Eyes"],
    paisesMencionados: ["Suécia", "Finlândia", "Estados Unidos", "Brasil"],
    sujeitosMencionados: ["Thomas Nilsson (Major-General / Chefe MUST)", "Försvarsmakten"],
    numeroRegistroOficial: "SWE-MUST-ARSOVERSIKT-2023",
    quantidadePaginas: 48,
    urlOficialCustodia: "https://www.forsvarsmakten.se/sv/om-forsvarsmakten/dokument/rapporter/",
    urlPdfOriginal: "https://www.forsvarsmakten.se/siteassets/4-om-myndigheten/dokumentfiler/rapporter/must-arsoversikt-2023.pdf",
    contextoBrasil: "A Suécia é parceira estratégica de defesa do Brasil no programa de caças F-39 Gripen da FAB (Saab / Embraer), com transferência de tecnologia militar sob regras rígidas de segurança da informação.",
    latitude: 59.3498,
    longitude: 18.0686,
    localidadeFoco: "Estocolmo, Suécia (Försvarsmakten Högkvarteret / MUST)",
    aliancaInteligencia: "Fourteen Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
  {
    id: "DOC-FRA-SWE-SIGINT-COOPERATION",
    titulo: "Försvarets Radioanstalt (FRA): Relatório de Transparência sobre Inteligência de Sinais e Parcerias Internacionais",
    resumo: "Documento oficial de prestação de contas públicas da agência sueca de inteligência de sinais (FRA) detalhando autorizações de coleta de cabos submarinos, cooperação com a NSA/GCHQ e garantias de privacidade civil.",
    orgaoInteligencia: "FRA",
    nomeCompletoOrgao: "Försvarets radioanstalt - National Defence Radio Establishment (Suécia)",
    paisOrigem: "Suécia",
    codigoIsoPais: "SWE",
    bandeiraPais: "🇸🇪",
    continente: "Europa",
    dataPublicacao: "2024-04-18",
    dataDesclassificacao: "2024-04-18",
    nivelClassificacaoOriginal: "Público / Ostensivo",
    temas: ["Soberania", "Telecomunicações", "Geopolítica"],
    assuntos: ["FRA", "SIGINT", "Interceptação de Cabos", "Fourteen Eyes", "Transparência"],
    paisesMencionados: ["Suécia", "Estados Unidos", "Reino Unido", "Brasil"],
    sujeitosMencionados: ["Björn Lyrvall (Diretor-Geral FRA)", "Conselho de Integridade"],
    numeroRegistroOficial: "SWE-FRA-VERKSAMHETSBERATTELSE-2023",
    quantidadePaginas: 36,
    urlOficialCustodia: "https://fra.se/",
    urlPdfOriginal: "https://fra.se/rapporter/verksamhetsberattelse-2023.pdf",
    contextoBrasil: "Representa o modelo escandinavo de inteligência de sinais com conselho de controle civil independente e autorização judicial para coleta de cabos de tráfego de dados.",
    latitude: 59.3333,
    longitude: 17.7833,
    localidadeFoco: "Lovön / Estocolmo, Suécia (FRA Headquarters)",
    aliancaInteligencia: "Fourteen Eyes",
    naturezaDocumento: "Relatório Público Contemporâneo",
  },
];
