#!/usr/bin/env node
/**
 * @file scripts/etl/internacional/gerar-operacoes-militares.mts
 * @description Gerador arquivístico e ETL de dados de Operações Militares, Contratos de Defesa, PMCs e Conflitos Globais.
 *
 * Papel no portal:
 * Gera o acervo compactado em apps/web/data/internacional/operacoes-militares.compact.json
 * atendendo rigorosamente à Regra das 6 Qualidades do Controle Popular (AGENTS.md §8):
 * 1. Hiperlinks oficiais diretos para relatórios do Congresso dos EUA (CRS R42738),
 *    Conselho de Segurança da ONU, National Security Archive, DoD, UCDP e SIPRI.
 * 2. Facetas detalhadas: tipo de operação, países patrocinadores, continente e país do teatro,
 *    PMCs/mercenários envolvidos, grandes empreiteiras bélicas e décadas.
 * 3. Ordenação por ano de início, duração, baixas estimadas e relevância geopolítica.
 * 4. Microresumo com contextualização cívica do impacto na soberania e direitos humanos.
 * 5. Sanitização algorítmica rigorosa contra dados pessoais e vazamentos indevidos.
 * 6. Exportação em formato CSV com BOM UTF-8 e compatibilidade com mapa vetorial SVG.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compactar } from "../../../apps/web/lib/estatico/compactar.js";
import { sanitizarDadoPessoalInternacional } from "../../../apps/web/lib/internacional/privacidade-internacional.js";

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const DIR_OUT = path.join(RAIZ, "apps", "web", "data", "internacional");

export interface OperacaoMilitarBruta {
  id: string;
  codinome: string;
  titulo: string;
  resumo: string;
  tipoOperacao:
    | "intervencao_militar_direta"
    | "deposicao_regime_golpe"
    | "pmc_milicia_privada"
    | "guerra_proxy_apoio_rebelde"
    | "contrato_defesa_armamento"
    | "operacao_paz_mandato_onu";
  anoInicio: number;
  anoFim?: number;
  duracaoEstimada: string;
  paisesPatrocinadores: string[];
  orgaosForcasEnvolvidas: string[];
  pmcsEnvolvidas?: string[];
  principaisContratadasDefesa?: string[];
  paisTeatro: string;
  continenteTeatro:
    | "América do Sul"
    | "América Central e Caribe"
    | "América do Norte"
    | "Europa"
    | "Oriente Médio"
    | "África"
    | "Ásia e Oceania";
  localidadeFoco: string;
  latitude: number;
  longitude: number;
  baixasEstimadas?: string;
  custoFinanceiroEstimado?: string;
  desfechoSoberania: string;
  conexaoBrasilOuAmericaLatina?: string;
  fonteOficialNome: string;
  urlFonteOficial: string;
  urlDocumentoOriginalPdf?: string;
  identificadorOficialDoc?: string;
  assuntos: string[];
}

const OPERACOES_MILITARES: OperacaoMilitarBruta[] = [
  // --- BLOCO 1: INTERVENÇÕES MILITARES DIRETAS E GUERRAS FORMAIS ---
  {
    id: "OP-1950-KOR-COREIA",
    codinome: "Guerra da Coreia / Desembarque de Incheon",
    titulo: "Intervenção Militar da Coalizão da ONU liderada pelos EUA na Península Coreana",
    resumo: "Conflito bélico internacional iniciado após o avanço norte-coreano, seguido de contra-ofensiva anfíbia anfíbia em Incheon sob comando do general MacArthur e intervenção chinesa.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1950,
    anoFim: 1953,
    duracaoEstimada: "1950 - 1953 (3 anos)",
    paisesPatrocinadores: ["Estados Unidos", "Reino Unido", "Canadá", "Austrália", "França"],
    orgaosForcasEnvolvidas: ["US Armed Forces", "Comando das Nações Unidas (UNC)", "British Commonwealth Forces"],
    principaisContratadasDefesa: ["Boeing", "General Dynamics", "Douglas Aircraft"],
    paisTeatro: "Coreia do Sul",
    continenteTeatro: "Ásia e Oceania",
    localidadeFoco: "Incheon / Panmunjom",
    latitude: 37.4563,
    longitude: 126.7052,
    baixasEstimadas: "~2,5 a 3 milhões de mortos (militares e civis)",
    custoFinanceiroEstimado: "US$ 30 bilhões (equivalente a US$ 390 bi corrigidos)",
    desfechoSoberania: "Assinatura do Armistício de Panmunjom e estabelecimento da Zona Desmilitarizada (DMZ) na latitude do Paralelo 38.",
    conexaoBrasilOuAmericaLatina: "O Brasil foi pressionado pela administração Truman a enviar tropas terrestres, mas limitou sua atuação a apoio diplomático e fornecimento de matérias-primas minerais.",
    fonteOficialNome: "Congressional Research Service (CRS Report R42738) / US National Archives",
    urlFonteOficial: "https://www.archives.gov/research/military/korean-war",
    urlDocumentoOriginalPdf: "https://crsreports.congress.gov/product/pdf/R/R42738",
    identificadorOficialDoc: "CRS Report R42738 / US National Archives RG 338",
    assuntos: ["Guerra da Coreia", "Guerra Fria", "Desembarque Incheon", "ONU", "Paralelo 38"],
  },
  {
    id: "OP-1956-EGY-SUEZ",
    codinome: "Operação Mosqueteiro / Crise de Suez",
    titulo: "Ataque Militar Franco-Britânico e Israelense contra o Egito após Nacionalização do Canal",
    resumo: "Ação militar coordenada entre Reino Unido, França e Israel para retomar o controle do Canal de Suez e tentar derrubar o presidente Gamal Abdel Nasser após a nacionalização do canal.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1956,
    anoFim: 1956,
    duracaoEstimada: "1956 (1 semana)",
    paisesPatrocinadores: ["Reino Unido", "França", "Israel"],
    orgaosForcasEnvolvidas: ["British Armed Forces", "Forças Armadas da França", "Forças de Defesa de Israel (IDF)"],
    paisTeatro: "Egito",
    continenteTeatro: "África",
    localidadeFoco: "Port Said / Canal de Suez",
    latitude: 31.2653,
    longitude: 32.3019,
    baixasEstimadas: "~1.600 a 3.000 egípcios mortos",
    custoFinanceiroEstimado: "£ 500 milhões (provocou grave crise na libra esterlina)",
    desfechoSoberania: "Retirada humilhante das forças europeias sob forte pressão econômica dos EUA e ameaça da URSS, consolidando a soberania egípcia sobre o canal.",
    conexaoBrasilOuAmericaLatina: "O Brasil integrou a Primeira Força de Emergência das Nações Unidas (UNEF I) através do Batalhão Suez (1957-1967), mantendo presença militar de paz na região.",
    fonteOficialNome: "The National Archives (Kew, UK) / UN Peacemaker",
    urlFonteOficial: "https://discovery.nationalarchives.gov.uk/details/r/C1045",
    urlDocumentoOriginalPdf: "https://peacemaker.un.org/sites/peacemaker.un.org/files/EG_561107_Resolution%201001.pdf",
    identificadorOficialDoc: "UN General Assembly Resolution 1001 (ES-I) / TNA CAB 128/30",
    assuntos: ["Canal de Suez", "Descolonização", "Nasser", "Batalhão Suez", "Pressão Financeira"],
  },
  {
    id: "OP-1958-LBN-BLUEBAT",
    codinome: "Operação Blue Bat",
    titulo: "Desembarque Militar dos Fuzileiros Navais dos EUA em Beirute (Doutrina Eisenhower)",
    resumo: "Primeira aplicação formal da Doutrina Eisenhower no Oriente Médio, com desembarque de 14.000 marines americanos no Líbano para conter tensões da crise política pró-pan-arabismo.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1958,
    anoFim: 1958,
    duracaoEstimada: "1958 (3 meses)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["US Marine Corps", "US Navy Sixth Fleet", "US Army 24th Airborne"],
    paisTeatro: "Líbano",
    continenteTeatro: "Oriente Médio",
    localidadeFoco: "Beirute / Aeroporto Internacional",
    latitude: 33.8938,
    longitude: 35.5018,
    baixasEstimadas: "4 soldados dos EUA mortos; ~3.000 baixas libanesas em confrontos civis prévios",
    custoFinanceiroEstimado: "US$ 150 milhões",
    desfechoSoberania: "Estabilização temporária do governo pró-ocidental do presidente Camille Chamoun e transição negociada para Fouad Chehab.",
    conexaoBrasilOuAmericaLatina: "O Brasil abrigava a maior comunidade de imigrantes libaneses do mundo, gerando forte comoção comunitária em São Paulo e debates no parlamento brasileiro.",
    fonteOficialNome: "Naval History and Heritage Command / CRS Report R42738",
    urlFonteOficial: "https://www.history.navy.mil/research/library/online-reading-room/title-list-alphabetically/o/operation-bluebat.html",
    urlDocumentoOriginalPdf: "https://crsreports.congress.gov/product/pdf/R/R42738",
    identificadorOficialDoc: "CRS Report R42738 / DoD Action Report 1958",
    assuntos: ["Doutrina Eisenhower", "Líbano", "Fuzileiros Navais", "Oriente Médio"],
  },
  {
    id: "OP-1964-VNM-ROLLING-THUNDER",
    codinome: "Operação Rolling Thunder / Guerra do Vietnã",
    titulo: "Campanha Contínua de Bombardeio Aéreo Estratégico dos EUA sobre o Vietnã do Norte",
    resumo: "Campanha massiva de bombardeios da Força Aérea e Marinha dos EUA visando destruir a infraestrutura industrial e as rotas de suprimento da Trilha Ho Chi Minh.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1964,
    anoFim: 1973,
    duracaoEstimada: "1964 - 1973 (9 anos)",
    paisesPatrocinadores: ["Estados Unidos", "Austrália", "Nova Zelândia", "Coreia do Sul"],
    orgaosForcasEnvolvidas: ["US Air Force", "US Navy Task Force 77", "MACV"],
    principaisContratadasDefesa: ["Boeing (B-52)", "McDonnell Douglas (F-4)", "Bell Helicopter (UH-1)", "Dow Chemical (Agente Laranja)"],
    paisTeatro: "Vietnã",
    continenteTeatro: "Ásia e Oceania",
    localidadeFoco: "Hanói / Haiphong / Golfo de Tonquim",
    latitude: 21.0285,
    longitude: 105.8542,
    baixasEstimadas: "+2 a 3 milhões de mortos vietnamitas; 58.220 militares dos EUA mortos",
    custoFinanceiroEstimado: "US$ 168 bilhões (equivalente a US$ 1 trilhão hoje)",
    desfechoSoberania: "Acordos de Paz de Paris (1973), retirada completa das tropas dos EUA e unificação do Vietnã sob o governo de Hanói em 1975.",
    conexaoBrasilOuAmericaLatina: "A ditadura militar brasileira expressou solidariedade aos EUA na Guerra Fria, mas resistiu ao envio de tropas combatentes ('Batalhão Brasileiro') apesar dos apelos do presidente Johnson.",
    fonteOficialNome: "National Archives Vietnam War Records (RG 472) / Pentagon Papers",
    urlFonteOficial: "https://www.archives.gov/research/military/vietnam-war",
    urlDocumentoOriginalPdf: "https://www.archives.gov/files/research/pentagon-papers/pentagon-papers-part-iv-c-2.pdf",
    identificadorOficialDoc: "Pentagon Papers Part IV.C.2 / US National Archives RG 472",
    assuntos: ["Guerra do Vietnã", "Rolling Thunder", "Pentagon Papers", "Agente Laranja", "B-52"],
  },
  {
    id: "OP-1969-KHM-MENU",
    codinome: "Operação Menu / Operação Freedom Deal",
    titulo: "Campanha Clandestina de Bombardeio Aéreo em Larga Escala no Camboja por Nixon e Kissinger",
    resumo: "Mais de 100.000 missões de bombardeio clandestino autorizadas pela Casa Branca sem conhecimento do Congresso dos EUA, lançando 540.000 toneladas de bombas em áreas civis e florestais do Camboja.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1969,
    anoFim: 1973,
    duracaoEstimada: "1969 - 1973 (4 anos)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["US Strategic Air Command (SAC)", "Joint Chiefs of Staff"],
    principaisContratadasDefesa: ["Boeing"],
    paisTeatro: "Camboja",
    continenteTeatro: "Ásia e Oceania",
    localidadeFoco: "Fronteira Oriental / Phnom Penh",
    latitude: 11.5564,
    longitude: 104.9282,
    baixasEstimadas: "~150.000 a 300.000 civis cambojanos mortos",
    custoFinanceiroEstimado: "US$ 7 bilhões",
    desfechoSoberania: "Desestabilização social catastrófica do Camboja, que colapsou a monarquia de Sihanouk e criou vácuo de poder explorado pelo Khmer Vermelho de Pol Pot.",
    conexaoBrasilOuAmericaLatina: "Precedente internacional histórico de desrespeito à soberania de países neutros via ações executivas encobertas, amplamente estudado na diplomacia do Itamaraty.",
    fonteOficialNome: "US House Judiciary Committee Impeachment Hearings (Article IV) / National Security Archive",
    urlFonteOficial: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB193/index.htm",
    urlDocumentoOriginalPdf: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB193/kissinger-cambodia.pdf",
    identificadorOficialDoc: "National Security Archive EBB 193 / House Impeachment Inquiry 1974",
    assuntos: ["Bombardeio do Camboja", "Operação Menu", "Kissinger", "Nixon", "Bombas de Fragmentação"],
  },
  {
    id: "OP-1970-LAO-BARREL-ROLL",
    codinome: "Operação Barrel Roll / A Guerra Secreta no Laos",
    titulo: "Maior Bombardeio Per Capita da História Humana: A Guerra Aérea dos EUA no Laos",
    resumo: "Operação da CIA e Força Aérea dos EUA lançando 2 milhões de toneladas de explosivos sobre o Laos (um bombardeio a cada 8 minutos por 9 anos), tornando o Laos o país mais bombardeado do planeta.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1964,
    anoFim: 1973,
    duracaoEstimada: "1964 - 1973 (9 anos)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["CIA (Air America)", "US Air Force", "Exército Secreto Hmong"],
    principaisContratadasDefesa: ["Air America (CIA Proprietary Company)"],
    paisTeatro: "Laos",
    continenteTeatro: "Ásia e Oceania",
    localidadeFoco: "Planície dos Jarros / Xiangkhoang",
    latitude: 19.4539,
    longitude: 103.1866,
    baixasEstimadas: "+50.000 civis laocianos mortos; 80 milhões de bombas não detonadas (UXO) até hoje",
    custoFinanceiroEstimado: "US$ 15 bilhões",
    desfechoSoberania: "Vitória do Pathet Lao e contaminação permanente do território agrícola com munições de fragmentação não explodidas.",
    conexaoBrasilOuAmericaLatina: "Exemplo primordial da utilização de empresas aéreas de fachada (Air America) como precursoras das modernas PMCs de mercenários.",
    fonteOficialNome: "CIA FOIA Electronic Reading Room / Legacies of War Archives",
    urlFonteOficial: "https://www.cia.gov/readingroom/collection/air-america",
    urlDocumentoOriginalPdf: "https://www.cia.gov/readingroom/docs/DOC_0000014765.pdf",
    identificadorOficialDoc: "CIA-RDP90-00845R000100140001-3",
    assuntos: ["Laos", "Guerra Secreta", "Air America", "Munições Não Detonadas", "Bombardeio"],
  },
  {
    id: "OP-1982-FLK-MALVINAS",
    codinome: "Guerra das Malvinas / Operação Corporate",
    titulo: "Conflito Bélico Aeronaval entre Reino Unido e Argentina pela Soberania das Ilhas Malvinas",
    resumo: "Confronto armado após o desembarque argentino nas ilhas (Operação Rosário) e contra-ataque naval da Força-Tarefa britânica enviada por Margaret Thatcher com apoio de inteligência dos EUA.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1982,
    anoFim: 1982,
    duracaoEstimada: "1982 (74 dias)",
    paisesPatrocinadores: ["Reino Unido"],
    orgaosForcasEnvolvidas: ["Royal Navy Task Group 317.8", "British Army", "Royal Air Force"],
    principaisContratadasDefesa: ["Vickers Shipbuilding", "BAE (Hawker Siddeley Harrier)", "Aérospatiale (Mísseis Exocet argentinos)"],
    paisTeatro: "Argentina",
    continenteTeatro: "América do Sul",
    localidadeFoco: "Port Stanley / Ilhas Malvinas",
    latitude: -51.6977,
    longitude: -57.8517,
    baixasEstimadas: "649 militares argentinos mortos; 255 britânicos mortos; 3 civis",
    custoFinanceiroEstimado: "£ 2,8 bilhões",
    desfechoSoberania: "Restauração do controle colonial britânico nas ilhas e desmoronamento imediato da ditadura militar argentina do general Galtieri.",
    conexaoBrasilOuAmericaLatina: "O Brasil declarou neutralidade oficial, mas apoiou diplomaticamente a reivindicação argentina de soberania territorial e interceptou bombardeiros britânicos Vulcan que violaram o espaço aéreo no Rio de Janeiro.",
    fonteOficialNome: "The National Archives (Kew, UK) / Relatório Oficial Rattenbach (Argentina)",
    urlFonteOficial: "https://www.nationalarchives.gov.uk/falklands/",
    urlDocumentoOriginalPdf: "https://discovery.nationalarchives.gov.uk/download/CAB128-73",
    identificadorOficialDoc: "TNA CAB 128/73 / Relatório Rattenbach Ministério da Defesa ARG",
    assuntos: ["Malvinas", "Falklands", "Soberania Sul-Americana", "Thatcher", "Interceptor Vulcan"],
  },
  {
    id: "OP-1983-GRD-URGENT-FURY",
    codinome: "Operação Urgent Fury",
    titulo: "Invasão Militar dos Estados Unidos na Ilha Caribenha de Granada",
    resumo: "Invasão anfíbia e helitransportada ordenada pelo presidente Ronald Reagan após o assassinato do primeiro-ministro Maurice Bishop e tomada do poder por junta militar esquerdista.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1983,
    anoFim: 1983,
    duracaoEstimada: "1983 (1 semana)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["US Army 82nd Airborne", "US Navy SEALs", "US Marine Corps", "Army Rangers"],
    paisTeatro: "Granada",
    continenteTeatro: "América Central e Caribe",
    localidadeFoco: "Saint George's / Aeroporto de Point Salines",
    latitude: 12.0561,
    longitude: -61.7488,
    baixasEstimadas: "45 militares granadinos mortos; 24 civis mortos; 19 militares dos EUA mortos",
    custoFinanceiroEstimado: "US$ 134 milhões",
    desfechoSoberania: "Derrubada da junta de Hudson Austin, desmantelamento da influência cubana na ilha e instauração de governo provisório pró-EUA.",
    conexaoBrasilOuAmericaLatina: "Condenação da invasão na Assembleia Geral da ONU por 108 votos a 9, com voto contrário do Brasil ao unilateralismo militar nas Américas.",
    fonteOficialNome: "Congressional Research Service (CRS R42738) / UN General Assembly Resolution 38/7",
    urlFonteOficial: "https://digitallibrary.un.org/record/56578",
    urlDocumentoOriginalPdf: "https://crsreports.congress.gov/product/pdf/R/R42738",
    identificadorOficialDoc: "UN General Assembly Resolution 38/7 / CRS Report R42738",
    assuntos: ["Granada", "Urgent Fury", "Reagan", "Caribe", "Maurice Bishop"],
  },
  {
    id: "OP-1986-LBY-EL-DORADO",
    codinome: "Operação El Dorado Canyon",
    titulo: "Ataques Aéreos Noturnos dos EUA contra Alvos Governamentais e Militares na Líbia",
    resumo: "Ataque aéreo retaliatório ordenado por Ronald Reagan após atentado em discoteca de Berlim Ocidental, bombardeando quartéis em Trípoli e Benghazi.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1986,
    anoFim: 1986,
    duracaoEstimada: "1986 (1 noite)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["US Air Force 48th Tactical Fighter Wing", "US Navy Carrier Group"],
    principaisContratadasDefesa: ["General Dynamics (F-111 Aardvark)"],
    paisTeatro: "Líbia",
    continenteTeatro: "África",
    localidadeFoco: "Trípoli / Benghazi / Quartel Bab al-Azizia",
    latitude: 32.8872,
    longitude: 13.1913,
    baixasEstimadas: "~60 líbios mortos (incluindo a filha adotiva de Muammar Gaddafi); 2 pilotos dos EUA",
    custoFinanceiroEstimado: "US$ 250 milhões",
    desfechoSoberania: "Intensificação da crise diplomática e acirramento do confronto com a Líbia, culminando anos depois no atentado de Lockerbie.",
    conexaoBrasilOuAmericaLatina: "França e Espanha negaram autorização de sobrevoo para os aviões dos EUA, forçando rota de 4.000 km pelo Oceano Atlântico contornando a costa europeia.",
    fonteOficialNome: "Air Force Historical Research Agency / CRS Report R42738",
    urlFonteOficial: "https://www.afhra.af.mil/",
    urlDocumentoOriginalPdf: "https://crsreports.congress.gov/product/pdf/R/R42738",
    identificadorOficialDoc: "USAF Historical Study / CRS Report R42738",
    assuntos: ["Líbia", "El Dorado Canyon", "Gaddafi", "Reagan", "F-111"],
  },
  {
    id: "OP-1989-PAN-JUST-CAUSE",
    codinome: "Operação Just Cause",
    titulo: "Invasão Militar dos Estados Unidos ao Panamá e Captura do General Manuel Noriega",
    resumo: "Mobilização de 27.000 militares americanos para capturar o homem forte do Panamá, Manuel Noriega (ex-colaborador da CIA), sob acusações de narcotráfico.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1989,
    anoFim: 1990,
    duracaoEstimada: "1989 - 1990 (1 mês)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["US Army XVIII Airborne Corps", "US Navy SEALs", "Joint Special Operations Command"],
    principaisContratadasDefesa: ["Lockheed (F-117 Nighthawk - estreia em combate)"],
    paisTeatro: "Panamá",
    continenteTeatro: "América Central e Caribe",
    localidadeFoco: "Cidade do Panamá / Bairro El Chorrillo",
    latitude: 8.9824,
    longitude: -79.5199,
    baixasEstimadas: "~500 a 1.000 civis panamenhos mortos; 23 militares dos EUA",
    custoFinanceiroEstimado: "US$ 163 milhões",
    desfechoSoberania: "Rendição de Noriega na Nunciatura Apostólica, extinção das Forças de Defesa do Panamá e posse do presidente Guillermo Endara em base militar dos EUA.",
    conexaoBrasilOuAmericaLatina: "A OEA e a Assembleia Geral da ONU aprovaram resolução de profunda censura à intervenção dos EUA por violação da Carta da ONU e da soberania latino-americana.",
    fonteOficialNome: "US Southern Command / UN General Assembly Resolution 44/240",
    urlFonteOficial: "https://digitallibrary.un.org/record/82998",
    urlDocumentoOriginalPdf: "https://crsreports.congress.gov/product/pdf/R/R42738",
    identificadorOficialDoc: "UN General Assembly Resolution 44/240 / CRS Report R42738",
    assuntos: ["Panamá", "Just Cause", "Noriega", "Canal do Panamá", "El Chorrillo"],
  },
  {
    id: "OP-1991-IRQ-DESERT-STORM",
    codinome: "Operação Tempestade no Deserto / Guerra do Golfo",
    titulo: "Campanha Militar Internacional da Coalizão de 35 Nações para Libertar o Kuwait",
    resumo: "Campanha aérea de 42 dias seguida de ofensiva terrestre de 100 horas liderada pelo general Norman Schwarzkopf após a invasão e anexação do Kuwait pelo Iraque de Saddam Hussein.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1991,
    anoFim: 1991,
    duracaoEstimada: "1991 (1 mês e meio)",
    paisesPatrocinadores: ["Estados Unidos", "Reino Unido", "França", "Arábia Saudita", "Kuwait"],
    orgaosForcasEnvolvidas: ["Coalizão Internacional / US Central Command (CENTCOM)"],
    principaisContratadasDefesa: ["Lockheed Martin", "Raytheon (Mísseis Tomahawk e Patriot)", "General Dynamics", "McDonnell Douglas"],
    paisTeatro: "Kuwait",
    continenteTeatro: "Oriente Médio",
    localidadeFoco: "Cidade do Kuwait / Sul do Iraque / Basra",
    latitude: 29.3759,
    longitude: 47.9774,
    baixasEstimadas: "~25.000 a 50.000 soldados iraquianos mortos; ~3.600 civis; 292 militares da coalizão",
    custoFinanceiroEstimado: "US$ 61 bilhões (US$ 36 bi pagos por Arábia Saudita e Kuwait)",
    desfechoSoberania: "Restauração da soberania do Kuwait, imposição de severo regime de sanções da ONU sobre o Iraque e criação das Zonas de Exclusão Aérea.",
    conexaoBrasilOuAmericaLatina: "O Brasil perdeu grandes contratos comerciais no Iraque e teve de evacuar centenas de engenheiros da construtora Mendes Júnior que atuavam em Bagdá.",
    fonteOficialNome: "Department of Defense Final Report to Congress on the Conduct of the Persian Gulf War",
    urlFonteOficial: "https://www.esd.whs.mil/FOIA/Reading-Room/Reading-Room-List_Categories/Gulf-War/",
    urlDocumentoOriginalPdf: "https://crsreports.congress.gov/product/pdf/R/R42738",
    identificadorOficialDoc: "DoD Conduct of the Persian Gulf War Final Report / CRS R42738",
    assuntos: ["Guerra do Golfo", "Tempestade no Deserto", "Kuwait", "Saddam Hussein", "Mendes Júnior"],
  },
  {
    id: "OP-1992-SOM-RESTORE-HOPE",
    codinome: "Operação Restore Hope / Batalha de Mogadíscio",
    titulo: "Intervenção Humanitária-Militar das Forças Armadas dos EUA e ONU na Guerra Civil da Somália",
    resumo: "Força-Tarefa Unificada (UNITAF) para garantir ajuda humanitária durante grave fome, que escalou para combates urbanos contra a milícia do senhor da guerra Mohamed Farrah Aidid.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1992,
    anoFim: 1994,
    duracaoEstimada: "1992 - 1994 (2 anos)",
    paisesPatrocinadores: ["Estados Unidos", "Itália", "Paquistão", "Malásia"],
    orgaosForcasEnvolvidas: ["US Army Rangers", "Delta Force", "UNOSOM II"],
    paisTeatro: "Somália",
    continenteTeatro: "África",
    localidadeFoco: "Mogadíscio / Mercado Bakara",
    latitude: 2.0469,
    longitude: 45.3182,
    baixasEstimadas: "~1.000 a 2.000 somalis mortos; 18 soldados dos EUA (Batalha de Mogadíscio)",
    custoFinanceiroEstimado: "US$ 2,2 bilhões",
    desfechoSoberania: "Retirada unilateral das forças dos EUA pelo presidente Bill Clinton e colapso da missão da ONU, inaugurando a chamada 'Síndrome da Somália'.",
    conexaoBrasilOuAmericaLatina: "A 'Síndrome da Somália' gerou recuo dos EUA em intervenções multilaterais, levando à omissão da comunidade internacional diante do Genocídio de Ruanda em 1994.",
    fonteOficialNome: "US Army Center of Military History / UN Security Council Resolution 794",
    urlFonteOficial: "https://history.army.mil/brochures/Somalia/Somalia.htm",
    urlDocumentoOriginalPdf: "https://digitallibrary.un.org/record/156094/files/S_RES_794%281992%29-EN.pdf",
    identificadorOficialDoc: "UN Security Council Resolution 794 (1992) / US Army CMH Pub 70-81-1",
    assuntos: ["Somália", "Restore Hope", "Black Hawk Down", "Fome", "Mogadíscio"],
  },
  {
    id: "OP-1995-BIH-DELIBERATE-FORCE",
    codinome: "Operação Deliberate Force",
    titulo: "Campanha Aérea da OTAN contra Forças Sérvias da Bósnia após o Massacre de Srebrenica",
    resumo: "Bombardeios aéreos coordenados da OTAN contra artilharia, depósitos de munição e centros de comando das Forças Sérvias da Bósnia para forçar o cessar-fogo na Guerra da Bósnia.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1995,
    anoFim: 1995,
    duracaoEstimada: "1995 (3 semanas)",
    paisesPatrocinadores: ["Estados Unidos", "Reino Unido", "França", "Holanda", "OTAN"],
    orgaosForcasEnvolvidas: ["NATO Allied Forces Southern Europe", "UNPROFOR"],
    paisTeatro: "Bósnia e Herzegovina",
    continenteTeatro: "Europa",
    localidadeFoco: "Sarajevo / Pale / Tuzla",
    latitude: 43.8563,
    longitude: 18.4131,
    baixasEstimadas: "~30 militares sérvios bósnios mortos; ~1.000 alvos destruídos",
    custoFinanceiroEstimado: "US$ 1,1 bilhão",
    desfechoSoberania: "Fim do cerco de Sarajevo e assinatura dos Acordos de Dayton em Ohio, dividindo a Bósnia em duas entidades autônomas.",
    conexaoBrasilOuAmericaLatina: "O Brasil atuou no Tribunal Penal Internacional para a ex-Iugoslávia (TPIJ) em Haia, apoiando o julgamento por crimes de guerra e genocídio.",
    fonteOficialNome: "NATO Historical Archives / Dayton Peace Accords",
    urlFonteOficial: "https://www.nato.int/cps/en/natohq/topics_52144.htm",
    urlDocumentoOriginalPdf: "https://peacemaker.un.org/sites/peacemaker.un.org/files/BA_951121_DaytonAgreement.pdf",
    identificadorOficialDoc: "NATO Operational Directive / Dayton Peace Agreement UN Doc S/1995/999",
    assuntos: ["Bósnia", "OTAN", "Dayton", "Srebrenica", "Deliberate Force"],
  },
  {
    id: "OP-1999-YUG-ALLIED-FORCE",
    codinome: "Operação Allied Force / Bombardeio da Iugoslávia",
    titulo: "Campanha Aérea de 78 Dias da OTAN contra a Iugoslávia sem Autorização do Conselho de Segurança da ONU",
    resumo: "Bombardeio massivo contra infraestrutura militar, pontes, usinas elétricas e a emissora de TV estatal em Belgrado para forçar Slobodan Milosevic a retirar tropas de Kosovo.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 1999,
    anoFim: 1999,
    duracaoEstimada: "1999 (78 dias)",
    paisesPatrocinadores: ["Estados Unidos", "Reino Unido", "Alemanha", "França", "Itália", "OTAN"],
    orgaosForcasEnvolvidas: ["NATO Air Forces (38.000 surtidas)"],
    principaisContratadasDefesa: ["Lockheed Martin", "Raytheon", "Boeing", "Northrop Grumman (B-2 Spirit)"],
    paisTeatro: "Sérvia",
    continenteTeatro: "Europa",
    localidadeFoco: "Belgrado / Pristina / Novi Sad",
    latitude: 44.7866,
    longitude: 20.4489,
    baixasEstimadas: "~500 a 1.500 civis iugoslavos mortos; embaixada da China em Belgrado atingida",
    custoFinanceiroEstimado: "US$ 4,5 bilhões",
    desfechoSoberania: "Retirada das forças sérvias, ocupação pela KFOR sob Resolução 1244 e posterior declaração unilateral de independência de Kosovo em 2008.",
    conexaoBrasilOuAmericaLatina: "O Brasil, integrando o Conselho de Segurança da ONU, defendeu a primazia do direito internacional e criticou o ataque sem mandato formal da ONU.",
    fonteOficialNome: "UN Security Council Resolution 1244 / Human Rights Watch Report on NATO Civilian Casualties",
    urlFonteOficial: "https://www.hrw.org/reports/2000/nato/",
    urlDocumentoOriginalPdf: "https://digitallibrary.un.org/record/274480/files/S_RES_1244%281999%29-EN.pdf",
    identificadorOficialDoc: "UN Security Council Resolution 1244 (1999) / HRW Report E1201",
    assuntos: ["Iugoslávia", "Kosovo", "OTAN", "Belgrado", "Resolução 1244"],
  },
  {
    id: "OP-2001-AFG-ENDURING-FREEDOM",
    codinome: "Operação Enduring Freedom / Guerra do Afeganistão",
    titulo: "Invasão Militar dos EUA e Coalizão Internacional no Afeganistão após os Atentados de 11 de Setembro",
    resumo: "Campanha militar que derrubou o primeiro regime talibã e desencadeou a mais longa guerra da história dos EUA (20 anos), caracterizada por insurgência, drones e contraterrorismo.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 2001,
    anoFim: 2021,
    duracaoEstimada: "2001 - 2021 (20 anos)",
    paisesPatrocinadores: ["Estados Unidos", "Reino Unido", "Canadá", "Alemanha", "OTAN"],
    orgaosForcasEnvolvidas: ["US Central Command", "ISAF (NATO)", "CIA Special Activities Center"],
    pmcsEnvolvidas: ["DynCorp International", "Academi / Constellis", "Triple Canopy"],
    principaisContratadasDefesa: ["Lockheed Martin", "General Dynamics", "Raytheon", "KBR / Halliburton"],
    paisTeatro: "Afeganistão",
    continenteTeatro: "Ásia e Oceania",
    localidadeFoco: "Cabul / Kandahar / Tora Bora",
    latitude: 34.5553,
    longitude: 69.2075,
    baixasEstimadas: "+176.000 mortos (incluindo 46.000 civis afegãos); 2.461 militares dos EUA",
    custoFinanceiroEstimado: "US$ 2,31 trilhões (Brown University Costs of War Project)",
    desfechoSoberania: "Retirada caótica dos EUA em agosto de 2021, colapso do governo pró-ocidental e retorno imediato do Talibã ao poder em Cabul.",
    conexaoBrasilOuAmericaLatina: "Demonstração do custo astronômico e da dependência crítica de empresas militares privadas (PMCs terceirizadas superavam o número de soldados no terreno).",
    fonteOficialNome: "Special Inspector General for Afghanistan Reconstruction (SIGAR) / Costs of War Project",
    urlFonteOficial: "https://www.sigar.mil/",
    urlDocumentoOriginalPdf: "https://www.sigar.mil/pdf/lessonslearned/SIGAR-21-46-LL.pdf",
    identificadorOficialDoc: "SIGAR Lessons Learned Report 2021 / CRS Report R44116",
    assuntos: ["Afeganistão", "Enduring Freedom", "SIGAR", "Talibã", "PMCs Terceirizadas"],
  },
  {
    id: "OP-2003-IRQ-IRAQI-FREEDOM",
    codinome: "Operação Iraqi Freedom / Invasão do Iraque",
    titulo: "Invasão Militar do Iraque por Coalizão dos EUA sob Alegação Falsa de Armas de Destruição em Massa",
    resumo: "Guerra preventiva deflagrada pela administração George W. Bush e Tony Blair que derrubou Saddam Hussein, destruiu as instituições estatais iraquianas e gerou desestabilização regional com surgimento do ISIS.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 2003,
    anoFim: 2011,
    duracaoEstimada: "2003 - 2011 (8 anos)",
    paisesPatrocinadores: ["Estados Unidos", "Reino Unido", "Austrália", "Polônia"],
    orgaosForcasEnvolvidas: ["Coalition Provisional Authority (CPA)", "US Armed Forces", "British Armed Forces"],
    pmcsEnvolvidas: ["Blackwater / Xe", "CACI International", "Titan Corp", "Erinys International", "DynCorp"],
    principaisContratadasDefesa: ["Halliburton / KBR", "Bechtel", "Lockheed Martin", "Boeing"],
    paisTeatro: "Iraque",
    continenteTeatro: "Oriente Médio",
    localidadeFoco: "Bagdá / Fallujah / Tikrit",
    latitude: 33.3152,
    longitude: 44.3661,
    baixasEstimadas: "+500.000 mortos diretos e indiretos; 4.492 militares dos EUA mortos",
    custoFinanceiroEstimado: "US$ 1,9 trilhão (estudo Watson Institute / Harvard)",
    desfechoSoberania: "Execução de Saddam Hussein, dissolução do exército iraquiano (Desbaathificação), guerra sectária civil e ocupação prolongada.",
    conexaoBrasilOuAmericaLatina: "O diplomata brasileiro Sérgio Vieira de Mello, enviado especial da ONU em Bagdá, foi assassinado em 19 de agosto de 2003 em atentado a bomba no Hotel Canal.",
    fonteOficialNome: "The Chilcot Report (UK Iraq Inquiry) / US Senate Select Committee on Intelligence",
    urlFonteOficial: "https://webarchive.nationalarchives.gov.uk/ukgwa/20171123122743/http://www.iraqinquiry.org.uk/",
    urlDocumentoOriginalPdf: "https://webarchive.nationalarchives.gov.uk/ukgwa/20171123122743/http://www.iraqinquiry.org.uk/media/247921/the-report-of-the-iraq-inquiry_executive-summary.pdf",
    identificadorOficialDoc: "UK Chilcot Inquiry Report (HC 264) / Senate Intelligence Report on Pre-War Intelligence",
    assuntos: ["Iraque", "Sérgio Vieira de Mello", "Chilcot Report", "Blackwater", "Armas de Destruição em Massa"],
  },
  {
    id: "OP-2011-LBY-UNIFIED-PROTECTOR",
    codinome: "Operação Unified Protector",
    titulo: "Intervenção Militar e Bombardeio da OTAN na Líbia e Queda de Muammar Gaddafi",
    resumo: "Campanha aero-naval da OTAN autorizada sob pretexto de proteção de civis (Resolução 1973 da ONU), que rapidamente converteu-se em apoio militar direto aos rebeldes para derrubar o regime de Gaddafi.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 2011,
    anoFim: 2011,
    duracaoEstimada: "2011 (7 meses)",
    paisesPatrocinadores: ["França", "Reino Unido", "Estados Unidos", "Catar", "OTAN"],
    orgaosForcasEnvolvidas: ["NATO Air Command", "DGSE", "British Special Forces (SAS)"],
    paisTeatro: "Líbia",
    continenteTeatro: "África",
    localidadeFoco: "Trípoli / Benghazi / Sirte",
    latitude: 32.8872,
    longitude: 13.1913,
    baixasEstimadas: "+10.000 a 25.000 mortos durante o conflito",
    custoFinanceiroEstimado: "US$ 1,5 bilhão (apenas custo das Forças Armadas dos EUA)",
    desfechoSoberania: "Linchamento de Gaddafi, fragmentação territorial da Líbia entre milícias rivais e transformação do país em rota de tráfico humano e armas.",
    conexaoBrasilOuAmericaLatina: "O Brasil absteve-se na votação da Resolução 1973 do Conselho de Segurança e formulou o conceito de 'Responsabilidade ao Proteger' (RwP) alertando contra mudanças forçadas de regime.",
    fonteOficialNome: "UN Security Council Resolution 1973 / UK House of Commons Foreign Affairs Committee Report",
    urlFonteOficial: "https://publications.parliament.uk/pa/cm201617/cmselect/cmfaff/119/119.pdf",
    urlDocumentoOriginalPdf: "https://digitallibrary.un.org/record/699757/files/S_RES_1973%282011%29-EN.pdf",
    identificadorOficialDoc: "UN Security Council Resolution 1973 (2011) / UK Foreign Affairs Committee HC 119",
    assuntos: ["Líbia", "Gaddafi", "OTAN", "Responsabilidade ao Proteger", "Sarkozy"],
  },
  {
    id: "OP-2013-MLI-SERVAL-BARKHANE",
    codinome: "Operações Serval e Barkhane no Sahel",
    titulo: "Intervenção Militar Francesa no Mali, Níger e Burquina Fasso contra Insurgências Jihadistas",
    resumo: "Mobilização de 5.000 militares franceses para conter o avanço de grupos armados no norte do Mali, estendendo-se por quase uma década de ocupação de bases militares em 5 países do Sahel.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 2013,
    anoFim: 2022,
    duracaoEstimada: "2013 - 2022 (9 anos)",
    paisesPatrocinadores: ["França", "Alemanha", "União Europeia"],
    orgaosForcasEnvolvidas: ["Forças Armadas da França (Armée de Terre)", "Força Aérea Francesa", "G5 Sahel"],
    principaisContratadasDefesa: ["Dassault Aviation (Rafale)", "Thales", "Arquus (Veículos Blindados)"],
    paisTeatro: "Mali",
    continenteTeatro: "África",
    localidadeFoco: "Gao / Kidal / Bamako",
    latitude: 16.2717,
    longitude: -0.0447,
    baixasEstimadas: "53 soldados franceses mortos; milhares de civis e insurgentes mortos",
    custoFinanceiroEstimado: "€ 4,5 bilhões (cerca de € 1 bilhão por ano)",
    desfechoSoberania: "Ruptura diplomática das juntas militares do Mali, Níger e Burquina Fasso com Paris, expulsão das tropas francesas e aliança com o Wagner Group da Rússia.",
    conexaoBrasilOuAmericaLatina: "Crise geopolítica do neocolonialismo e decadência do modelo 'Françafrique', acompanhada de perto pela diplomacia de cooperação Sul-Sul do Brasil com a África Ocidental.",
    fonteOficialNome: "Ministère des Armées (França) / Assemblée Nationale Française Rapport d'Information",
    urlFonteOficial: "https://www.defense.gouv.fr/operations/operations/afrique-ouest-centrale/barkhane",
    urlDocumentoOriginalPdf: "https://www.assemblee-nationale.fr/dyn/15/rapports/cion_def/l15b4121_rapport-information.pdf",
    identificadorOficialDoc: "Assemblée Nationale Française Rapport n° 4121 (2021)",
    assuntos: ["Françafrique", "Mali", "Barkhane", "Sahel", "Ucrânia-Rússia"],
  },
  {
    id: "OP-2022-UKR-RUS-INVASION",
    codinome: "Invasão da Ucrânia / Suporte Militar Maciço da OTAN",
    titulo: "Maior Guerra Convencional em Solo Europeu desde 1945: Invasão Russa e Fornecimento de Armas Ocidentais",
    resumo: "Invasão militar em grande escala da Ucrânia pela Federação Russa, gerando resposta militar e econômica dos EUA e países da OTAN com fornecimento sem precedentes de armas, blindados e inteligência.",
    tipoOperacao: "intervencao_militar_direta",
    anoInicio: 2022,
    anoFim: undefined,
    duracaoEstimada: "2022 - presente (em curso)",
    paisesPatrocinadores: ["Rússia", "Estados Unidos", "Reino Unido", "Alemanha", "Polônia"],
    orgaosForcasEnvolvidas: ["Forças Armadas da Ucrânia", "Forças Armadas da Rússia", "NATO Intelligence Sharing"],
    pmcsEnvolvidas: ["Wagner Group (Rússia)", "Redut (Rússia)", "Academi / Voluntários Ocidentais"],
    principaisContratadasDefesa: ["Lockheed Martin (HIMARS, Javelin)", "Rheinmetall (Leopard, Munição 155mm)", "BAE Systems", "General Dynamics"],
    paisTeatro: "Ucrânia",
    continenteTeatro: "Europa",
    localidadeFoco: "Kiev / Kharkiv / Donbas / Mariupol",
    latitude: 50.4501,
    longitude: 30.5234,
    baixasEstimadas: "+500.000 baixas militares combinadas; dezenas de milhares de civis mortos",
    custoFinanceiroEstimado: "+US$ 300 bilhões em ajuda militar e financeira internacional",
    desfechoSoberania: "Conflito em andamento com ocupação russa de 18% do território ucraniano e corrida armamentista global no G20.",
    conexaoBrasilOuAmericaLatina: "O Brasil condenou a invasão territorial na ONU, mas defendeu a diplomacia de paz, neutralidade de sanções e a não entrega de munições brasileiras à Ucrânia.",
    fonteOficialNome: "UN General Assembly Emergency Special Session Resolution ES-11/1 / CRS Report R47054",
    urlFonteOficial: "https://crsreports.congress.gov/product/pdf/R/R47054",
    urlDocumentoOriginalPdf: "https://digitallibrary.un.org/record/3959039/files/A_RES_ES-11_1-EN.pdf",
    identificadorOficialDoc: "UN Resolution ES-11/1 / CRS Report R47054",
    assuntos: ["Ucrânia", "Rússia", "OTAN", "Rheinmetall", "HIMARS", "Wagner"],
  },

  // --- BLOCO 2: DEPOSIÇÕES DE REGIME, GOLPES E OPERAÇÕES ENCOBERTAS ---
  {
    id: "OP-1953-IRN-AJAX",
    codinome: "Operação Ajax (TPAJAX)",
    titulo: "Golpe de Estado Orquestrado pela CIA e MI6 no Irã para Derrubar o Primeiro-Ministro Mossadegh",
    resumo: "Operação secreta financiada pela inteligência dos EUA e Reino Unido após a nacionalização da Anglo-Iranian Oil Company (atual BP), subornando militares e políticos para instalar ditadura do Xá.",
    tipoOperacao: "deposicao_regime_golpe",
    anoInicio: 1953,
    anoFim: 1953,
    duracaoEstimada: "1953 (1 semana)",
    paisesPatrocinadores: ["Estados Unidos", "Reino Unido"],
    orgaosForcasEnvolvidas: ["CIA (Kermit Roosevelt Jr.)", "MI6", "Exército Imperial do Irã"],
    paisTeatro: "Irã",
    continenteTeatro: "Oriente Médio",
    localidadeFoco: "Teerã / Palácio Saadabad",
    latitude: 35.6892,
    longitude: 51.3890,
    baixasEstimadas: "~300 mortos em confrontos de rua pagos por agentes da CIA",
    custoFinanceiroEstimado: "US$ 1 milhão (verba secreta da CIA em dinheiro vivo)",
    desfechoSoberania: "Deposição do líder democrático Mohammad Mossadegh, restauração do poder absoluto do Xá Reza Pahlavi e concessão de 40% do petróleo iraniano a empresas americanas.",
    conexaoBrasilOuAmericaLatina: "Caso clássico de quebra de soberania estatal em represália à nacionalização de recursos energéticos nacionais (precedente estudado na criação da Petrobras em 1953).",
    fonteOficialNome: "National Security Archive (George Washington University) / CIA Declassified History",
    urlFonteOficial: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB435/",
    urlDocumentoOriginalPdf: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB435/docs/Doc%202%20-%20CIA%20memo%20on%20Overthrow%20of%20Mosaddeq.pdf",
    identificadorOficialDoc: "National Security Archive EBB 435 / CIA Historical Staff CS-HP-208",
    assuntos: ["Operação Ajax", "Irã", "Mossadegh", "Petróleo", "CIA", "MI6"],
  },
  {
    id: "OP-1954-GTM-PBSUCCESS",
    codinome: "Operação PBSUCCESS",
    titulo: "Golpe de Estado e Invasão Paramilitar Organizada pela CIA na Guatemala contra Jacobo Árbenz",
    resumo: "Operação psicológica, bombardeios clandestinos e formação de milícia mercenária sob o coronel Castillo Armas para derrubar o presidente Jacobo Árbenz após reforma agrária contra a United Fruit Company.",
    tipoOperacao: "deposicao_regime_golpe",
    anoInicio: 1954,
    anoFim: 1954,
    duracaoEstimada: "1954 (2 semanas)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["CIA (Diretor Allen Dulles)", "Exército de Libertação Paramilitar"],
    paisTeatro: "Guatemala",
    continenteTeatro: "América Central e Caribe",
    localidadeFoco: "Cidade da Guatemala / Puerto Barrios",
    latitude: 14.6349,
    longitude: -90.5069,
    baixasEstimadas: "Centenas de camponeses mortos; inaugurou 36 anos de guerra civil (+200.000 mortos)",
    custoFinanceiroEstimado: "US$ 3 milhões",
    desfechoSoberania: "Renúncia forçada de Árbenz, devolução das terras desapropriadas à United Fruit Company e instalação de juntas militares sanguinárias.",
    conexaoBrasilOuAmericaLatina: "Gerou protestos massivos no Brasil em 1954 contra o imperialismo americano semanas antes do suicídio do presidente Getúlio Vargas.",
    fonteOficialNome: "CIA FOIA Electronic Reading Room / State Department Foreign Relations of the United States (FRUS)",
    urlFonteOficial: "https://history.state.gov/historicaldocuments/frus1952-54Guat",
    urlDocumentoOriginalPdf: "https://www.cia.gov/readingroom/docs/DOC_0000135890.pdf",
    identificadorOficialDoc: "FRUS Guatemala 1952-1954 Document 268 / CIA Job 79-01025A",
    assuntos: ["Guatemala", "PBSUCCESS", "United Fruit", "Jacobo Árbenz", "Allen Dulles"],
  },
  {
    id: "OP-1961-CUB-ZAPATA",
    codinome: "Invasão da Baía dos Porcos / Operação Zapata",
    titulo: "Tentativa Fracassada de Invasão de Cuba por Brigada Paramilitar Mercenária Treinada pela CIA",
    resumo: "Invasão de 1.400 exilados cubanos armados e financiados pela CIA (Brigada 2506), derrotados em 72 horas pelas Forças Armadas Revolucionárias de Cuba na praia de Playa Girón.",
    tipoOperacao: "deposicao_regime_golpe",
    anoInicio: 1961,
    anoFim: 1961,
    duracaoEstimada: "1961 (3 dias)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["CIA Special Activities Division", "Brigada Paramilitar 2506"],
    paisTeatro: "Cuba",
    continenteTeatro: "América Central e Caribe",
    localidadeFoco: "Playa Girón / Baía dos Porcos",
    latitude: 22.0722,
    longitude: -81.0872,
    baixasEstimadas: "176 cubanos defensores mortos; 118 invasores mortos; 1.202 mercenários capturados",
    custoFinanceiroEstimado: "US$ 46 milhões",
    desfechoSoberania: "Vitória militar decisiva de Cuba, consolidação do regime socialista e aproximação estratégica de Fidel Castro com a União Soviética.",
    conexaoBrasilOuAmericaLatina: "O presidente brasileiro Jânio Quadros condecorou Che Guevara com a Ordem do Cruzeiro do Sul em 1961, reafirmando a Política Externa Independente contra o isolamento de Cuba.",
    fonteOficialNome: "John F. Kennedy Presidential Library / Taylor Commission Report",
    urlFonteOficial: "https://www.jfklibrary.org/asset-viewer/archives/jfknsa-330-001",
    urlDocumentoOriginalPdf: "https://www.jfklibrary.org/sites/default/files/archives/JFKPOF/115/JFKPOF-115-001.pdf",
    identificadorOficialDoc: "Taylor Committee Report to President Kennedy 1961 / JFK POF Box 115",
    assuntos: ["Baía dos Porcos", "Cuba", "Playa Girón", "CIA", "Kennedy", "Brigada 2506"],
  },
  {
    id: "OP-1961-COD-LUMUMBA",
    codinome: "Deposição e Assassinato de Patrice Lumumba",
    titulo: "Operação Encoberta da Bélgica e CIA para Assassinato do Primeiro-Ministro Patrice Lumumba",
    resumo: "Eliminação física do líder anticolonialista do Congo recém-independente após a secessão de Katanga rica em urânio e cobalto, articulada pela inteligência belga e telegramas de Allen Dulles.",
    tipoOperacao: "deposicao_regime_golpe",
    anoInicio: 1960,
    anoFim: 1961,
    duracaoEstimada: "1960 - 1961 (6 meses)",
    paisesPatrocinadores: ["Bélgica", "Estados Unidos"],
    orgaosForcasEnvolvidas: ["Inteligência Militar Belga", "CIA Station Leopoldville", "Mercenários Brancos de Katanga"],
    paisTeatro: "República Democrática do Congo",
    continenteTeatro: "África",
    localidadeFoco: "Katanga / Lubumbashi",
    latitude: -11.6609,
    longitude: 27.4794,
    baixasEstimadas: "Assassinato de Lumumba e 2 ministros; milhares de mortos na Crise do Congo",
    desfechoSoberania: "Ascensão da ditadura militar de Mobutu Sese Seko, que governou o Zaire de forma cleptocrática por mais de 30 anos com apoio ocidental.",
    conexaoBrasilOuAmericaLatina: "O parlamento belga realizou comissão parlamentar de inquérito em 2001 reconhecendo a responsabilidade moral e oficial da Bélgica no assassinato de Lumumba.",
    fonteOficialNome: "Comissão Parlamentar Belga sobre o Assassinato de Patrice Lumumba (2001) / US Church Committee",
    urlFonteOficial: "https://www.lachambre.be/kvvcr/showpage.cfm?section=/comm/lumumba&language=fr",
    urlDocumentoOriginalPdf: "https://www.senate.gov/about/resources/pdf/church-committee-interim-report.pdf",
    identificadorOficialDoc: "Chambre des Représentants de Belgique Doc 50-0312/006 / Church Committee Alleged Assassination Plots",
    assuntos: ["Lumumba", "Congo", "Bélgica", "CIA", "Descolonização", "Katanga"],
  },
  {
    id: "OP-1964-BRA-BROTHER-SAM",
    codinome: "Operação Brother Sam",
    titulo: "Mobilização Naval e Logística Militar dos EUA em Apoio ao Golpe de 1964 no Brasil",
    resumo: "Envio de força-tarefa aeronaval da Marinha dos EUA (incluindo porta-aviões USS Forrestal, destróieres e navios de combustível) ao litoral brasileiro para intervir em caso de resistência ao golpe contra João Goulart.",
    tipoOperacao: "deposicao_regime_golpe",
    anoInicio: 1964,
    anoFim: 1964,
    duracaoEstimada: "1964 (1 semana)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["US Navy Task Group", "Embaixada dos EUA (Embaixador Lincoln Gordon)", "Adido Militar Vernon Walters"],
    paisTeatro: "Brasil",
    continenteTeatro: "América do Sul",
    localidadeFoco: "Rio de Janeiro / Brasília / Baía de Guanabara",
    latitude: -22.9068,
    longitude: -43.1729,
    baixasEstimadas: "Instauração de ditadura militar de 21 anos com 434 mortos/desaparecidos oficiais",
    desfechoSoberania: "Deposição inconstitucional do presidente João Goulart e ruptura democrática no Brasil por 21 anos.",
    conexaoBrasilOuAmericaLatina: "Episódio central da história política contemporânea do Brasil, documentado em telegramas desclassificados do embaixador Lincoln Gordon e gravações de Lyndon Johnson.",
    fonteOficialNome: "National Security Archive (GWU) / LBJ Presidential Library Tape Recordings",
    urlFonteOficial: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB118/index.htm",
    urlDocumentoOriginalPdf: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB118/doc11.pdf",
    identificadorOficialDoc: "National Security Archive EBB 118 / State Department Telegram 1964",
    assuntos: ["Brother Sam", "Golpe de 1964", "João Goulart", "Lincoln Gordon", "Ditadura Militar"],
  },
  {
    id: "OP-1965-DOM-POWERPACK",
    codinome: "Operação Power Pack",
    titulo: "Invasão Militar dos Fuzileiros dos EUA na República Dominicana para Conter Movimento Constitucionalista",
    resumo: "Desembarque de 42.000 militares americanos para sufocar a revolta de militares patriotas liderados por Francisco Caamaño que exigiam o retorno do presidente constitucional Juan Bosch.",
    tipoOperacao: "deposicao_regime_golpe",
    anoInicio: 1965,
    anoFim: 1966,
    duracaoEstimada: "1965 - 1966 (1 ano)",
    paisesPatrocinadores: ["Estados Unidos", "Brasil (sob ditadura militar)"],
    orgaosForcasEnvolvidas: ["US Army 82nd Airborne", "US Marine Corps", "Força Interamericana de Paz (FIP)"],
    paisTeatro: "República Dominicana",
    continenteTeatro: "América Central e Caribe",
    localidadeFoco: "Santo Domingo",
    latitude: 18.4861,
    longitude: -69.9312,
    baixasEstimadas: "~3.000 a 4.000 dominicanos mortos; 44 soldados dos EUA mortos",
    custoFinanceiroEstimado: "US$ 180 milhões",
    desfechoSoberania: "Destruição do movimento constitucionalista, realização de eleições controladas e vitória de Joaquín Balaguer.",
    conexaoBrasilOuAmericaLatina: "A ditadura militar brasileira de Castelo Branco enviou 1.250 soldados (FAIBRAS) para chefiar militarmente a Força Interamericana de Paz (FIP), sob o general Hugo Panasco Alvim.",
    fonteOficialNome: "US Army Center of Military History / OEA Documentos Oficiais da FIP",
    urlFonteOficial: "https://history.army.mil/html/books/075/75-10/index.html",
    urlDocumentoOriginalPdf: "https://history.army.mil/html/books/075/75-10/CMH_Pub_75-10.pdf",
    identificadorOficialDoc: "US Army CMH Pub 75-10 / OEA Resolução Décima Reunião de Consulta",
    assuntos: ["Power Pack", "República Dominicana", "Juan Bosch", "FIP", "Ditadura Brasileira"],
  },
  {
    id: "OP-1973-CHL-FUBELT",
    codinome: "Operação FUBELT / Golpe Militar no Chile",
    titulo: "Ação Encoberta da CIA e Apoio de Nixon e Kissinger ao Golpe Militar contra Salvador Allende",
    resumo: "Guerra econômica ('make the economy scream'), financiamento de greves, sabotagens e articulação com as Forças Armadas chilenas comandadas por Augusto Pinochet, bombardeando o Palácio de La Moneda.",
    tipoOperacao: "deposicao_regime_golpe",
    anoInicio: 1970,
    anoFim: 1973,
    duracaoEstimada: "1970 - 1973 (3 anos)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["CIA Directorate of Operations", "Forças Armadas do Chile", "DINA"],
    principaisContratadasDefesa: ["ITT Corporation (International Telephone and Telegraph)"],
    paisTeatro: "Chile",
    continenteTeatro: "América do Sul",
    localidadeFoco: "Santiago / Palácio de La Moneda",
    latitude: -33.4489,
    longitude: -70.6693,
    baixasEstimadas: "+3.000 mortos e desaparecidos; dezenas de milhares de torturados no Estádio Nacional",
    custoFinanceiroEstimado: "US$ 10 milhões em fundos secretos da CIA",
    desfechoSoberania: "Morte do presidente Salvador Allende no palácio presidencial e instauração de 17 anos de terrorismo de Estado sob a ditadura de Pinochet.",
    conexaoBrasilOuAmericaLatina: "A ditadura brasileira atuou ativamente como base logística e financeira de suporte aos golpistas chilenos antes e após o 11 de setembro de 1973.",
    fonteOficialNome: "US Senate Church Committee Report on Covert Action in Chile (1975) / National Security Archive",
    urlFonteOficial: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB8/",
    urlDocumentoOriginalPdf: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB8/docs/doc01.pdf",
    identificadorOficialDoc: "Church Committee Interim Report 1975 / CIA Project FUBELT Files",
    assuntos: ["Chile", "Salvador Allende", "Pinochet", "Operação FUBELT", "Kissinger", "La Moneda"],
  },
  {
    id: "OP-1975-URY-ARG-CONDOR",
    codinome: "Operação Condor",
    titulo: "Consórcio Transnacional de Terrorismo de Estado e Eliminação de Opositores Políticos no Cone Sul",
    resumo: "Pacto de cooperação clandestina entre as ditaduras de Chile, Argentina, Uruguai, Paraguai, Bolívia e Brasil para caçar, sequestrar, torturar e assassinar opositores além de suas fronteiras nacionais.",
    tipoOperacao: "deposicao_regime_golpe",
    anoInicio: 1975,
    anoFim: 1983,
    duracaoEstimada: "1975 - 1983 (8 anos)",
    paisesPatrocinadores: ["Chile", "Argentina", "Uruguai", "Paraguai", "Brasil", "Estados Unidos"],
    orgaosForcasEnvolvidas: ["DINA (Chile)", "SIDE (Argentina)", "CIE / SNI (Brasil)", "DNII (Uruguai)", "CIA"],
    paisTeatro: "Argentina",
    continenteTeatro: "América do Sul",
    localidadeFoco: "Buenos Aires / Assunção / Santiago / Roma / Washington",
    latitude: -34.6037,
    longitude: -58.3816,
    baixasEstimadas: "+50.000 mortos no Cone Sul; centenas de bebês sequestrados",
    desfechoSoberania: "Assassinatos célebres no exterior como o de Orlando Letelier em Washington DC e Carlos Prats em Buenos Aires com carros-bomba.",
    conexaoBrasilOuAmericaLatina: "O Brasil participou através do CIE e DOPS no sequestro dos uruguaios Lilian Celiberti e Universindo Díaz em Porto Alegre em 1978.",
    fonteOficialNome: "Arquivos do Terror (Paraguai) / Comissão Nacional da Verdade do Brasil (Relatório Final)",
    urlFonteOficial: "https://www.gov.br/memoriasreveladas/pt-br/assuntos/comissao-nacional-da-verdade",
    urlDocumentoOriginalPdf: "https://nsarchive2.gwu.edu/NSAEBB/NSAEBB416/docs/condor_cable.pdf",
    identificadorOficialDoc: "Comissão Nacional da Verdade Vol. I e II / Arquivo do Terror Assunção",
    assuntos: ["Operação Condor", "Ditaduras Militares", "Arquivos do Terror", "Terrorismo de Estado", "Orlando Letelier"],
  },
  {
    id: "OP-1979-AFG-CYCLONE",
    codinome: "Operação Cyclone",
    titulo: "Programa Secreto da CIA para Armamento e Financiamento dos Guerrilheiros Mujahideen no Afeganistão",
    resumo: "A mais longa e dispendiosa operação secreta da história da CIA, canalizando bilhões de dólares e mísseis Stinger via o serviço de inteligência do Paquistão (ISI) para combater o Exército Vermelho soviético.",
    tipoOperacao: "guerra_proxy_apoio_rebelde",
    anoInicio: 1979,
    anoFim: 1989,
    duracaoEstimada: "1979 - 1989 (10 anos)",
    paisesPatrocinadores: ["Estados Unidos", "Arábia Saudita", "Reino Unido", "Paquistão"],
    orgaosForcasEnvolvidas: ["CIA Special Activities Division", "Inter-Services Intelligence (ISI Paquistão)", "MI6"],
    principaisContratadasDefesa: ["General Dynamics (Mísseis Stinger)"],
    paisTeatro: "Afeganistão",
    continenteTeatro: "Ásia e Oceania",
    localidadeFoco: "Peshawar / Cabul",
    latitude: 34.0151,
    longitude: 71.5249,
    baixasEstimadas: "+1 milhão de afegãos mortos; 14.453 militares soviéticos mortos",
    custoFinanceiroEstimado: "+US$ 20 bilhões em fundos conjuntos EUA e sauditas",
    desfechoSoberania: "Retirada soviética em 1989, guerra civil devastadora e formação inadvertida da Al-Qaeda e do Talibã com veteranos da guerrilha.",
    conexaoBrasilOuAmericaLatina: "Precedente global do fenômeno de 'blowback' (efeito bumerangue) das intervenções secretas ocidentais.",
    fonteOficialNome: "CIA FOIA Reading Room / 9/11 Commission Report",
    urlFonteOficial: "https://www.9-11commission.gov/report/",
    urlDocumentoOriginalPdf: "https://www.9-11commission.gov/report/911Report.pdf",
    identificadorOficialDoc: "9/11 Commission Report Chapter 2 / CIA Studies in Intelligence",
    assuntos: ["Operação Cyclone", "Mujahideen", "Mísseis Stinger", "Blowback", "Afeganistão"],
  },
  {
    id: "OP-1981-NIC-CONTRAS",
    codinome: "Guerra dos Contras / Caso Irã-Contras",
    titulo: "Financiamento Clandestino de Milícias Contrarrevolucionárias na Nicarágua pela Administração Reagan",
    resumo: "Operação ilegal coordenada pelo coronel Oliver North no Conselho de Segurança Nacional para financiar e armar as milícias dos Contras através da venda secreta de armas ao Irã, violando a Emenda Boland.",
    tipoOperacao: "guerra_proxy_apoio_rebelde",
    anoInicio: 1981,
    anoFim: 1990,
    duracaoEstimada: "1981 - 1990 (9 anos)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["National Security Council (NSC)", "CIA", "Milícias Contras (FDN)"],
    paisTeatro: "Nicarágua",
    continenteTeatro: "América Central e Caribe",
    localidadeFoco: "Manágua / Fronteira com Honduras",
    latitude: 12.1150,
    longitude: -86.2362,
    baixasEstimadas: "~30.000 nicaraguenses mortos; destruição massiva de escolas e clínicas",
    custoFinanceiroEstimado: "US$ 300 milhões em ajuda clandestina",
    desfechoSoberania: "Condenação histórica dos Estados Unidos pela Corte Internacional de Justiça (CIJ) em 1986 por violação do direito internacional e soberania da Nicarágua.",
    conexaoBrasilOuAmericaLatina: "A Corte de Haia determinou que os EUA pagassem reparações bilionárias à Nicarágua pelo bloqueio e minagem dos portos, decisão vetada pelos EUA no Conselho de Segurança.",
    fonteOficialNome: "International Court of Justice (ICJ Case Nicaragua v. USA) / Walsh Iran-Contra Final Report",
    urlFonteOficial: "https://www.icj-cij.org/case/70",
    urlDocumentoOriginalPdf: "https://www.icj-cij.org/public/files/case-related/70/070-19860627-JUD-01-00-EN.pdf",
    identificadorOficialDoc: "ICJ Judgment 27 June 1986 / Lawrence Walsh Iran-Contra Final Report",
    assuntos: ["Irã-Contras", "Nicarágua", "Corte Internacional de Justiça", "Oliver North", "Sandinistas"],
  },

  // --- BLOCO 3: MILÍCIAS PRIVADAS (PMCs) E MERCENÁRIOS ---
  {
    id: "PMC-1995-SLE-EXECUTIVE-OUTCOMES",
    codinome: "Executive Outcomes na Guerra Civil de Serra Leoa",
    titulo: "Contratação de Mercenários Sul-Africanos da Executive Outcomes pelo Governo de Serra Leoa",
    resumo: "O governo de Serra Leoa contratou a empresa militar privada sul-africana Executive Outcomes para combater os rebeldes da RUF (Frente Revolucionária Unida), recebendo concessões de minas de diamantes como pagamento.",
    tipoOperacao: "pmc_milicia_privada",
    anoInicio: 1995,
    anoFim: 1996,
    duracaoEstimada: "1995 - 1996 (1 ano)",
    paisesPatrocinadores: ["África do Sul", "Reino Unido"],
    orgaosForcasEnvolvidas: ["Executive Outcomes (Eeben Barlow)", "Exército de Serra Leoa (RSLMF)"],
    pmcsEnvolvidas: ["Executive Outcomes", "Sandline International"],
    paisTeatro: "Serra Leoa",
    continenteTeatro: "África",
    localidadeFoco: "Freetown / Minas de Koidu",
    latitude: 8.4840,
    longitude: -13.2299,
    baixasEstimadas: "Centenas de insurgentes mortos; expulsão da RUF da capital em semanas",
    custoFinanceiroEstimado: "US$ 35 milhões pagos em dinheiro e concessões minerárias da Branch Energy",
    desfechoSoberania: "Condução das primeiras eleições democráticas em quase 30 anos, mas consagrou a troca de segurança estatal por recursos minerais estratégicos.",
    conexaoBrasilOuAmericaLatina: "Marco fundamental do surgimento da moderna indústria corporativa de mercenários (PMCs) ligada diretamente à extração de commodities e mineração.",
    fonteOficialNome: "United Nations Institute for Disarmament Research (UNIDIR) / DCAF Geneva Centre",
    urlFonteOficial: "https://www.dcaf.ch/",
    urlDocumentoOriginalPdf: "https://www.unidir.org/files/publications/pdfs/privatising-security-en-347.pdf",
    identificadorOficialDoc: "UNIDIR Privatising Security Study 1998 / DCAF Monograph",
    assuntos: ["Executive Outcomes", "Mercenários", "Diamantes de Sangue", "Serra Leoa", "PMCs"],
  },
  {
    id: "PMC-2000-COL-DYNCORP",
    codinome: "DynCorp no Plano Colômbia",
    titulo: "Terceirização de Operações Militares e Pulverização Aérea com Glifosato pela DynCorp na Colômbia",
    resumo: "O Departamento de Estado dos EUA contratou a DynCorp International para pilotar aviões e helicópteros armados em missões de erradicação de coca com glifosato, busca e salvamento e treinamento de tropas colombianas.",
    tipoOperacao: "pmc_milicia_privada",
    anoInicio: 2000,
    anoFim: 2015,
    duracaoEstimada: "2000 - 2015 (15 anos)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["US State Dept INL", "Força Aérea Colombiana"],
    pmcsEnvolvidas: ["DynCorp International"],
    paisTeatro: "Colômbia",
    continenteTeatro: "América do Sul",
    localidadeFoco: "Putumayo / Caquetá / Fronteira com Equador",
    latitude: 0.5050,
    longitude: -76.9930,
    baixasEstimadas: "Milhares de camponeses intoxicados; ação judicial internacional por deriva química",
    custoFinanceiroEstimado: "US$ 1,2 bilhão em contratos da DynCorp",
    desfechoSoberania: "Processo de povos indígenas equatorianos na corte federal de Washington contra a DynCorp por danos à saúde e meio ambiente causados pela deriva transfronteiriça de veneno.",
    conexaoBrasilOuAmericaLatina: "Impacto direto na bacia amazônica compartilhada com o Brasil; o governo do Equador processou a Colômbia na Corte Internacional de Justiça em Haia pela pulverização.",
    fonteOficialNome: "US Government Accountability Office (GAO Report GAO-03-783) / US District Court DC",
    urlFonteOficial: "https://www.gao.gov/products/gao-03-783",
    urlDocumentoOriginalPdf: "https://www.gao.gov/assets/gao-03-783.pdf",
    identificadorOficialDoc: "GAO-03-783 Plan Colombia / US District Court Case Arias v. DynCorp",
    assuntos: ["DynCorp", "Plano Colômbia", "Glifosato", "Amazônia", "Contratistas Militares"],
  },
  {
    id: "PMC-2003-IRQ-CACI-TITAN",
    codinome: "Escândalo de Abu Ghraib / CACI e Titan Corp",
    titulo: "Torturas e Abusos de Prisioneiros por Contratados Militares Privados na Prisão de Abu Ghraib",
    resumo: "Interrogadores civis e tradutores contratados pelas empresas CACI International e Titan Corporation atuaram ao lado de policiais militares do exército americano na condução de torturas, humilhações e abusos sistemáticos.",
    tipoOperacao: "pmc_milicia_privada",
    anoInicio: 2003,
    anoFim: 2004,
    duracaoEstimada: "2003 - 2004 (1 ano)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["US Army 205th Military Intelligence Brigade"],
    pmcsEnvolvidas: ["CACI Premier Technology", "Titan Corporation (L-3)"],
    paisTeatro: "Iraque",
    continenteTeatro: "Oriente Médio",
    localidadeFoco: "Prisão Central de Abu Ghraib / Bagdá",
    latitude: 33.2922,
    longitude: 44.0622,
    baixasEstimadas: "Múltiplas mortes sob custódia e centenas de vítimas de tortura física e psicológica",
    custoFinanceiroEstimado: "Contratos de US$ 150 milhões para interrogadores civis",
    desfechoSoberania: "Vácuo legal onde contratados civis não podiam ser julgados pela corte marcial militar americana e gozavam de imunidade sob a Ordem 17 da CPA no Iraque.",
    conexaoBrasilOuAmericaLatina: "Em 2024, após 16 anos de litígio, um júri federal dos EUA condenou a CACI International a pagar US$ 42 milhões a três sobreviventes iraquianos de Abu Ghraib.",
    fonteOficialNome: "Major General Antonio Taguba Report on Abu Ghraib / US Senate Armed Services Committee",
    urlFonteOficial: "https://www.esd.whs.mil/FOIA/Reading-Room/Reading-Room-List_Categories/Detainee-Abuse/",
    urlDocumentoOriginalPdf: "https://www.esd.whs.mil/Portals/54/Documents/FOIA/Reading%20Room/Detainee_Abuse/taguba_report.pdf",
    identificadorOficialDoc: "Taguba Inquiry Report (AR 15-6) / Senate Armed Services Committee Inquiry 2008",
    assuntos: ["Abu Ghraib", "CACI", "Tortura", "Contratistas", "Direitos Humanos"],
  },
  {
    id: "PMC-2004-IRQ-AEGIS-DEFENCE",
    codinome: "Aegis Defence Services no Iraque",
    titulo: "Contratos de Segurança Militar Britânicos da Aegis Defence Services e Vídeos de Tiroteio",
    resumo: "A empresa britânica Aegis Defence Services, liderada pelo ex-oficial do exército Tim Spicer, venceu contrato de US$ 293 milhões do Pentágono para coordenar todos os contratados de segurança privada no Iraque.",
    tipoOperacao: "pmc_milicia_privada",
    anoInicio: 2004,
    anoFim: 2011,
    duracaoEstimada: "2004 - 2011 (7 anos)",
    paisesPatrocinadores: ["Reino Unido", "Estados Unidos"],
    orgaosForcasEnvolvidas: ["US Project and Contracting Office (PCO)"],
    pmcsEnvolvidas: ["Aegis Defence Services (atual GardaWorld)"],
    paisTeatro: "Iraque",
    continenteTeatro: "Oriente Médio",
    localidadeFoco: "Bagdá / Basra",
    latitude: 30.5081,
    longitude: 47.7835,
    custoFinanceiroEstimado: "US$ 450 milhões em contratos combinados",
    desfechoSoberania: "Em 2005, vídeos intitulados 'Trophy Videos' mostraram contratados da Aegis atirando indiscriminadamente contra carros civis iraquianos ao som de música pop.",
    conexaoBrasilOuAmericaLatina: "Expansão de empresas de segurança privada britânicas no controle de infraestruturas críticas e proteção patrimonial de multinacionais petroleiras.",
    fonteOficialNome: "Special Inspector General for Iraq Reconstruction (SIGIR Report 05-005) / UK Parliament",
    urlFonteOficial: "https://www.cybercemetery.unt.edu/archive/sigir/20131001092404/http://www.sigir.mil/",
    urlDocumentoOriginalPdf: "https://www.cybercemetery.unt.edu/archive/sigir/20131001092404/http://www.sigir.mil/files/audits/05-005.pdf",
    identificadorOficialDoc: "SIGIR Audit 05-005 / UK Foreign and Commonwealth Office Papers",
    assuntos: ["Aegis Defence", "Tim Spicer", "Iraque", "PMCs Britânicas", "Trophy Videos"],
  },
  {
    id: "PMC-2005-IRQ-DEFION",
    codinome: "Defion Internacional / Recrutamento Latino para o Iraque",
    titulo: "Recrutamento de Ex-Militares Peruanos e Chilenos como Guardas Baratos no Iraque",
    resumo: "A empresa peruana Defion Internacional foi subcontratada pela americana Triple Canopy para recrutar milhares de ex-militares e policiais da América Latina com salários de US$ 1.000/mês para segurança em Bagdá.",
    tipoOperacao: "pmc_milicia_privada",
    anoInicio: 2005,
    anoFim: 2008,
    duracaoEstimada: "2005 - 2008 (3 anos)",
    paisesPatrocinadores: ["Estados Unidos", "Peru"],
    pmcsEnvolvidas: ["Defion Internacional", "Triple Canopy"],
    paisTeatro: "Peru",
    continenteTeatro: "América do Sul",
    localidadeFoco: "Lima / Base de Treinamento em Huachipa",
    latitude: -12.0464,
    longitude: -77.0428,
    baixasEstimadas: "Diversos mortos e feridos sem cobertura adequada de plano de saúde",
    desfechoSoberania: "Comissão de Relações Exteriores do Congresso do Peru abriu investigações sobre a exportação de mão de obra militar precária para teatros de guerra estrangeiros.",
    conexaoBrasilOuAmericaLatina: "Evidência da exploração de militares da América do Sul por PMCs norte-americanas, recebendo uma fração dos salários pagos a contratistas americanos ou europeus.",
    fonteOficialNome: "Grupo de Trabalho da ONU sobre o Uso de Mercenários (Relatório sobre o Peru A/HRC/7/7/Add.2)",
    urlFonteOficial: "https://www.ohchr.org/en/special-procedures/wg-mercenaries",
    urlDocumentoOriginalPdf: "https://digitallibrary.un.org/record/622616/files/A_HRC_7_7_Add-2-EN.pdf",
    identificadorOficialDoc: "UN Human Rights Council Report A/HRC/7/7/Add.2 (2008)",
    assuntos: ["Defion", "Triple Canopy", "Peru", "Mercenários Baratos", "ONU Mercenários"],
  },
  {
    id: "PMC-2007-IRQ-NISOUR-BLACKWATER",
    codinome: "Massacre da Praça Nisour / Blackwater",
    titulo: "Fuzilamento de 17 Civis Desarmados em Bagdá por Contratados da Blackwater",
    resumo: "Comboio blindado da Blackwater Security Consulting (atual Constellis) abriu fogo desproporcional com metralhadoras e lança-granadas contra uma praça lotada de civis desarmados em Bagdá, matando 17 pessoas.",
    tipoOperacao: "pmc_milicia_privada",
    anoInicio: 2007,
    anoFim: 2007,
    duracaoEstimada: "2007 (1 dia)",
    paisesPatrocinadores: ["Estados Unidos"],
    orgaosForcasEnvolvidas: ["US State Department Diplomatic Security Service (DSS)"],
    pmcsEnvolvidas: ["Blackwater USA / Xe / Academi / Constellis (Erik Prince)"],
    paisTeatro: "Iraque",
    continenteTeatro: "Oriente Médio",
    localidadeFoco: "Praça Nisour / Bagdá",
    latitude: 33.3039,
    longitude: 44.3828,
    baixasEstimadas: "17 civis iraquianos mortos (incluindo crianças de 9 anos); 20 feridos graves",
    custoFinanceiroEstimado: "Contratos de mais de US$ 1 bilhão concedidos à Blackwater pelo State Dept",
    desfechoSoberania: "Quatro atiradores foram condenados em corte federal nos EUA em 2014, mas foram integralmente perdoados pelo presidente Donald Trump em dezembro de 2020.",
    conexaoBrasilOuAmericaLatina: "O perdão presidencial de 2020 foi formalmente repudiado pelo Escritório de Direitos Humanos da ONU como violação flagrante da obrigação de punir crimes de guerra.",
    fonteOficialNome: "US Department of Justice / United Nations Human Rights Office (OHCHR)",
    urlFonteOficial: "https://www.justice.gov/opa/pr/four-former-blackwater-contractors-sentenced-prison",
    urlDocumentoOriginalPdf: "https://www.justice.gov/sites/default/files/opa/legacy/2014/10/22/blackwater-indictment.pdf",
    identificadorOficialDoc: "US District Court DC Criminal No. 08-0360 / OHCHR Press Briefing 2020",
    assuntos: ["Blackwater", "Praça Nisour", "Erik Prince", "Crimes de Guerra", "Perdão Trump"],
  },
  {
    id: "PMC-2018-SYR-WAGNER-KHASHAM",
    codinome: "Batalha de Khasham / Wagner Group na Síria",
    titulo: "Confronto Direto entre Forças Especiais dos EUA e Mercenários Russos do Wagner Group",
    resumo: "Força de 500 combatentes pró-governo sírio e mercenários do Wagner Group avançaram contra instalação de gás em Deir ez-Zor guarnecida por forças curdas e operadores especiais dos EUA, resultando em bombardeio devastador.",
    tipoOperacao: "pmc_milicia_privada",
    anoInicio: 2018,
    anoFim: 2018,
    duracaoEstimada: "2018 (4 horas)",
    paisesPatrocinadores: ["Rússia", "Síria", "Estados Unidos"],
    orgaosForcasEnvolvidas: ["US Air Force (AC-130, F-15E, B-52)", "JSOC", "Wagner Group"],
    pmcsEnvolvidas: ["Wagner Group (Yevgeny Prigozhin)"],
    paisTeatro: "Síria",
    continenteTeatro: "Oriente Médio",
    localidadeFoco: "Khasham / Usina de Gás Conoco, Deir ez-Zor",
    latitude: 35.3022,
    longitude: 40.2978,
    baixasEstimadas: "~100 a 200 mercenários russos e sírios mortos; zero baixas americanas",
    desfechoSoberania: "Primeiro confronto armado direto com vítimas russas e tropas americanas desde a Guerra Fria, com Moscou negando vínculos com os contratados privados.",
    conexaoBrasilOuAmericaLatina: "Demonstração tática da negação plausível ('plausible deniability') utilizada por grandes potências ao terceirizar o combate bélico a corporações mercenárias.",
    fonteOficialNome: "US Central Command (CENTCOM) / Defense Intelligence Agency (DIA)",
    urlFonteOficial: "https://www.centcom.mil/",
    urlDocumentoOriginalPdf: "https://crsreports.congress.gov/product/pdf/R/R42738",
    identificadorOficialDoc: "CENTCOM Declassified Operational Summary / CRS Report R42738",
    assuntos: ["Wagner Group", "Batalha de Khasham", "Síria", "Prigozhin", "Confronto EUA-Rússia"],
  },
  {
    id: "PMC-2019-VEN-SILVERCORP",
    codinome: "Operação Gideão / Silvercorp na Venezuela",
    titulo: "Tentativa Fracassada de Incursão Marítima Mercenária contra a Venezuela",
    resumo: "Uma empresa de segurança privada com sede na Flórida (Silvercorp USA), comandada pelo ex-boina verde Jordan Goudreau, tentou uma invasão marítima para capturar Nicolás Maduro após assinar contrato com opositores.",
    tipoOperacao: "pmc_milicia_privada",
    anoInicio: 2020,
    anoFim: 2020,
    duracaoEstimada: "2020 (2 dias)",
    paisesPatrocinadores: ["Estados Unidos (sede da PMC)"],
    pmcsEnvolvidas: ["Silvercorp USA (Jordan Goudreau)"],
    paisTeatro: "Venezuela",
    continenteTeatro: "América do Sul",
    localidadeFoco: "Macuto / La Guaira",
    latitude: 10.6018,
    longitude: -66.9536,
    baixasEstimadas: "8 mercenários mortos; 2 ex-militares dos EUA capturados (Luke Denman e Airan Berry)",
    desfechoSoberania: "Fiasco operacional interceptado pela inteligência e pescadores locais, resultando na condenação dos norte-americanos a 20 anos de prisão na Venezuela.",
    conexaoBrasilOuAmericaLatina: "Tentativa recente de golpe via contratação de empresa mercenária privada na fronteira norte do Brasil, debatida na OEA e Conselho de Segurança da ONU.",
    fonteOficialNome: "UN Security Council Meeting Records (S/PV.8730) / Indictment US District Court Southern District of Florida",
    urlFonteOficial: "https://digitallibrary.un.org/record/3864455",
    urlDocumentoOriginalPdf: "https://digitallibrary.un.org/record/3864455/files/S_PV-8730-EN.pdf",
    identificadorOficialDoc: "UN Security Council Doc S/PV.8730 (2020) / US District Court Case 24-cr-20358",
    assuntos: ["Silvercorp", "Operação Gideão", "Venezuela", "Jordan Goudreau", "Mercenários"],
  },
  {
    id: "PMC-2022-MLI-MOURA-WAGNER",
    codinome: "Massacre de Moura / Wagner Group no Mali",
    titulo: "Execução em Massa de mais de 500 Civis em Moura por Forças Malinesas e Mercenários do Wagner",
    resumo: "Operação militar de 5 dias na cidade de Moura, no centro do Mali, onde soldados do exército malinês e contratados de língua russa do Wagner Group cercaram o mercado e executaram sumariamente civis desarmados.",
    tipoOperacao: "pmc_milicia_privada",
    anoInicio: 2022,
    anoFim: 2022,
    duracaoEstimada: "2022 (5 dias)",
    paisesPatrocinadores: ["Mali", "Rússia"],
    orgaosForcasEnvolvidas: ["Forças Armadas do Mali (FAMa)"],
    pmcsEnvolvidas: ["Wagner Group / Africa Corps"],
    paisTeatro: "Mali",
    continenteTeatro: "África",
    localidadeFoco: "Moura / Região de Mopti",
    latitude: 14.2833,
    longitude: -4.5667,
    baixasEstimadas: "+500 pessoas executadas sumariamente (relatório oficial da ONU)",
    desfechoSoberania: "Investigação da ONU concluiu que houve crimes de guerra e violações contra a humanidade, levando a sanções dos EUA e União Europeia contra chefes do Wagner no Mali.",
    conexaoBrasilOuAmericaLatina: "Expansão paramilitar de corporações privadas em Estados fragilizados da África Subsaariana com substituição de missões da ONU por tropas mercenárias.",
    fonteOficialNome: "Office of the United Nations High Commissioner for Human Rights (OHCHR Moura Fact-Finding Report)",
    urlFonteOficial: "https://www.ohchr.org/en/press-releases/2023/05/un-human-rights-report-recommends-accountability-over-moura-killings-mali",
    urlDocumentoOriginalPdf: "https://www.ohchr.org/sites/default/files/documents/countries/mali/20230512-Mali-Moura-Report.pdf",
    identificadorOficialDoc: "OHCHR Moura Fact-Finding Report May 2023",
    assuntos: ["Moura", "Mali", "Wagner Group", "Massacre", "Crimes de Guerra ONU"],
  },

  // --- BLOCO 4: CONTRATOS MILITARES E COMPLEXO INDUSTRIAL DE DEFESA ---
  {
    id: "CTR-2001-USA-LOCKHEED-F35",
    codinome: "Programa F-35 Joint Strike Fighter",
    titulo: "Maior Contrato de Armas da História Humana: O Caça F-35 Lightning II da Lockheed Martin",
    resumo: "Programa multinacional de caça de 5ª geração liderado pelos EUA com participação de Reino Unido, Itália, Holanda e Canadá, totalizando mais de US$ 1,7 trilhão no ciclo de vida.",
    tipoOperacao: "contrato_defesa_armamento",
    anoInicio: 2001,
    duracaoEstimada: "2001 - presente (em produção)",
    paisesPatrocinadores: ["Estados Unidos", "Reino Unido", "Itália", "Holanda", "Canadá"],
    principaisContratadasDefesa: ["Lockheed Martin", "Pratt & Whitney", "BAE Systems", "Northrop Grumman"],
    paisTeatro: "Estados Unidos",
    continenteTeatro: "América do Norte",
    localidadeFoco: "Fort Worth, Texas / Marham, Reino Unido",
    latitude: 32.7719,
    longitude: -97.4422,
    custoFinanceiroEstimado: "US$ 1,7 trilhão (ciclo de vida total estimado pelo GAO dos EUA)",
    desfechoSoberania: "Consolidação da hegemonia da Lockheed Martin na aviação de caça da OTAN, gerando dependência tecnológica total de softwares e peças controladas pelo Pentágono.",
    conexaoBrasilOuAmericaLatina: "Na concorrência F-X2 do Brasil, a Força Aérea Brasileira (FAB) rejeitou o F/A-18 da Boeing dos EUA justamente pela recusa em transferir 100% dos códigos-fonte e tecnologia.",
    fonteOficialNome: "US Government Accountability Office (GAO Report GAO-23-106047) / Defense.gov Contracts",
    urlFonteOficial: "https://www.gao.gov/products/gao-23-106047",
    urlDocumentoOriginalPdf: "https://www.gao.gov/assets/gao-23-106047.pdf",
    identificadorOficialDoc: "GAO-23-106047 F-35 Joint Strike Fighter / DoD Contract N00019-02-C-3002",
    assuntos: ["Lockheed Martin", "F-35", "Complexo Militar-Industrial", "OTAN", "Caças"],
  },
  {
    id: "CTR-2003-USA-RAYTHEON-PATRIOT",
    codinome: "Sistema de Mísseis Patriot / RTX Raytheon",
    titulo: "Mega-Contratos Globais de Defesa Antiaérea e Mísseis MIM-104 Patriot da Raytheon",
    resumo: "Fornecimento de baterias de mísseis interceptadores Patriot para os EUA, Alemanha, Polônia, Taiwan, Ucrânia e Arábia Saudita, movimentando dezenas de bilhões de dólares por ano.",
    tipoOperacao: "contrato_defesa_armamento",
    anoInicio: 2003,
    duracaoEstimada: "Contratos contínuos",
    paisesPatrocinadores: ["Estados Unidos", "Alemanha", "Arábia Saudita", "Ucrânia"],
    principaisContratadasDefesa: ["RTX (Raytheon Technologies)", "Lockheed Martin (mísseis PAC-3)"],
    paisTeatro: "Estados Unidos",
    continenteTeatro: "América do Norte",
    localidadeFoco: "Tewksbury e Andover, Massachusetts",
    latitude: 42.6053,
    longitude: -71.2173,
    custoFinanceiroEstimado: "+US$ 50 bilhões em vendas consolidadas de baterias e interceptadores",
    desfechoSoberania: "Papel central na defesa antimíssil em cenários de guerra ativa no Oriente Médio e na Ucrânia.",
    conexaoBrasilOuAmericaLatina: "Rastreamento do complexo industrial de mísseis e seus lobbies junto ao Congresso dos EUA (Foreign Military Sales - FMS).",
    fonteOficialNome: "Defense Security Cooperation Agency (DSCA) Major Arms Sales Notifications",
    urlFonteOficial: "https://www.dsca.mil/major-arms-sales",
    urlDocumentoOriginalPdf: "https://www.dsca.mil/press-media/major-arms-sales",
    identificadorOficialDoc: "DSCA Arms Sales Notifications / DoD Contract W31P4Q-20-C-0023",
    assuntos: ["Raytheon", "Patriot", "Mísseis", "DSCA", "Defesa Aérea"],
  },
  {
    id: "CTR-2005-USA-GD-ABRAMS",
    codinome: "General Dynamics / Tanques M1 Abrams e Submarinos Nucleares",
    titulo: "Contratos de Carros de Combate M1A2 Abrams e Submarinos Nucleares Classe Columbia",
    resumo: "A General Dynamics detém o monopólio da produção de carros de combate pesados e constrói a espinha dorsal da dissuasão nuclear naval com os submarinos estratégicos dos EUA.",
    tipoOperacao: "contrato_defesa_armamento",
    anoInicio: 2005,
    duracaoEstimada: "Contratos contínuos",
    paisesPatrocinadores: ["Estados Unidos", "Polônia", "Austrália"],
    principaisContratadasDefesa: ["General Dynamics Land Systems", "General Dynamics Electric Boat"],
    paisTeatro: "Estados Unidos",
    continenteTeatro: "América do Norte",
    localidadeFoco: "Sterling Heights, Michigan / Groton, Connecticut",
    latitude: 42.5803,
    longitude: -83.0302,
    custoFinanceiroEstimado: "US$ 132 bilhões para o programa de submarinos Columbia",
    desfechoSoberania: "Manutenção da frota de tanques e garantia da tríade nuclear com mísseis balísticos Trident II.",
    conexaoBrasilOuAmericaLatina: "Comparativo direto com o Programa de Desenvolvimento de Submarinos do Brasil (PROSUB), que constrói o primeiro submarino de propulsão nuclear da América Latina (Álvaro Alberto).",
    fonteOficialNome: "US Navy Fact Files / Congressional Research Service Report R41129",
    urlFonteOficial: "https://crsreports.congress.gov/product/pdf/R/R41129",
    urlDocumentoOriginalPdf: "https://crsreports.congress.gov/product/pdf/R/R41129",
    identificadorOficialDoc: "CRS Report R41129 Navy Columbia Class / DoD Contract N00024-21-C-2103",
    assuntos: ["General Dynamics", "M1 Abrams", "Submarinos Nucleares", "PROSUB", "Tríade Nuclear"],
  },
  {
    id: "CTR-2008-GBR-BAE-M777",
    codinome: "BAE Systems / Sistemas de Artilharia M777",
    titulo: "Produção e Exportação Global do Obuseiro Leve de Artilharia M777 pela Britânica BAE Systems",
    resumo: "O M777 de 155mm fabricado pela BAE Systems tornou-se a peça padrão de artilharia rebocada de titânio adotada pelos exércitos de EUA, Reino Unido, Canadá, Austrália e fornecida à Ucrânia.",
    tipoOperacao: "contrato_defesa_armamento",
    anoInicio: 2008,
    duracaoEstimada: "Contratos contínuos",
    paisesPatrocinadores: ["Reino Unido", "Estados Unidos"],
    principaisContratadasDefesa: ["BAE Systems Land & Armaments"],
    paisTeatro: "Reino Unido",
    continenteTeatro: "Europa",
    localidadeFoco: "Farnborough / Barrow-in-Furness, Reino Unido",
    latitude: 51.2787,
    longitude: -0.7571,
    custoFinanceiroEstimado: "+US$ 5 bilhões em contratos de artilharia e modernização",
    desfechoSoberania: "A BAE Systems é a maior empresa de defesa da Europa e um dos 10 maiores contratistas militares do Pentágono nos EUA.",
    conexaoBrasilOuAmericaLatina: "A BAE Systems fornece sistemas de canhões navais de 40mm e blindados M113 modernizados para o Exército Brasileiro e a Marinha do Brasil.",
    fonteOficialNome: "UK Ministry of Defence Annual Report / US Defense Security Cooperation Agency",
    urlFonteOficial: "https://www.gov.uk/government/organisations/ministry-of-defence",
    urlDocumentoOriginalPdf: "https://assets.publishing.service.gov.uk/media/64ddf7e252878b0014a45371/MOD_Annual_Report_and_Accounts_2022-23.pdf",
    identificadorOficialDoc: "UK MoD Annual Accounts / US Army Contract W56HZV-18-C-0133",
    assuntos: ["BAE Systems", "M777", "Reino Unido", "Artilharia 155mm", "Exército Brasileiro"],
  },
  {
    id: "CTR-2010-FRA-THALES-RADAR",
    codinome: "Thales Group / Sistemas de Radar e Guerra Eletrônica",
    titulo: "Contratos de Sensores Navais, Radares de Defesa Aérea e Satélites Militares do Thales Group",
    resumo: "A multinacional francesa Thales (parcialmente estatal) é uma das líderes mundiais em eletrônica de defesa, radares Ground Master e sistemas de combate para caças Rafale e navios de guerra.",
    tipoOperacao: "contrato_defesa_armamento",
    anoInicio: 2010,
    duracaoEstimada: "Contratos contínuos",
    paisesPatrocinadores: ["França", "União Europeia"],
    principaisContratadasDefesa: ["Thales Group", "Dassault Aviation"],
    paisTeatro: "França",
    continenteTeatro: "Europa",
    localidadeFoco: "La Défense, Paris / Élancourt, França",
    latitude: 48.8924,
    longitude: 2.2369,
    custoFinanceiroEstimado: "€ 18 bilhões de faturamento anual em defesa",
    desfechoSoberania: "Pilar de autonomia estratégica da França e principal exportador de tecnologia militar para o Oriente Médio, Ásia e América Latina.",
    conexaoBrasilOuAmericaLatina: "A Thales possui forte presença no Brasil através da Omnisys (em São Bernardo do Campo/SP), fabricando radares de controle de tráfego aéreo e componentes de defesa.",
    fonteOficialNome: "Ministère des Armées (França) / Thales Universal Registration Document",
    urlFonteOficial: "https://www.thalesgroup.com/en/investors",
    urlDocumentoOriginalPdf: "https://www.thalesgroup.com/sites/default/files/database/d7/asset/document/thales_urd_2023_en.pdf",
    identificadorOficialDoc: "Thales Universal Registration Document 2023 / DGA França",
    assuntos: ["Thales", "França", "Radares", "Omnisys Brasil", "Guerra Eletrônica"],
  },
  {
    id: "CTR-2012-DEU-RHEINMETALL-155MM",
    codinome: "Rheinmetall / Rearmamento Europeu e Artilharia",
    titulo: "Mega-Contratos de Munição de 155mm e Tanques Leopard da Alemã Rheinmetall",
    resumo: "A fabricante alemã Rheinmetall tornou-se o maior produtor ocidental de munições pesadas de artilharia e canhões de tanques, beneficiada pelo fundo especial de 100 bilhões de euros da Alemanha (Zeitenwende).",
    tipoOperacao: "contrato_defesa_armamento",
    anoInicio: 2012,
    duracaoEstimada: "Contratos contínuos",
    paisesPatrocinadores: ["Alemanha", "Ucrânia", "União Europeia"],
    principaisContratadasDefesa: ["Rheinmetall AG", "Krauss-Maffei Wegmann (KNDS)"],
    paisTeatro: "Alemanha",
    continenteTeatro: "Europa",
    localidadeFoco: "Düsseldorf / Fábrica de Unterlüss, Alemanha",
    latitude: 51.2497,
    longitude: 6.7828,
    custoFinanceiroEstimado: "Carteira de pedidos recorde de € 40 bilhões (2024)",
    desfechoSoberania: "Rearmamento maciço da Alemanha e quebra histórica da política de restrição de exportação de armas para zonas de guerra ativa.",
    conexaoBrasilOuAmericaLatina: "O chanceler alemão Olaf Scholz pediu pessoalmente ao Brasil munições de tanques Leopard 1 em 2023, pedido recusado pelo presidente Lula para preservar a posição pacifista do país.",
    fonteOficialNome: "Bundesministerium der Verteidigung (BMVg) / Rheinmetall Annual Financial Report",
    urlFonteOficial: "https://www.bmvg.de/de",
    urlDocumentoOriginalPdf: "https://ir.rheinmetall.com/download/companies/rheinmetall/Annual%20Reports/Rheinmetall_Annual_Report_2023.pdf",
    identificadorOficialDoc: "Rheinmetall AG Annual Report 2023 / BMVg Zeitenwende Status",
    assuntos: ["Rheinmetall", "Alemanha", "Leopard", "Artilharia 155mm", "Zeitenwende"],
  },
  {
    id: "CTR-2015-USA-SAUDI-WEAPONS",
    codinome: "Venda Massiva de Armas para a Guerra do Iêmen",
    titulo: "Pacotes de Bilhões de Dólares em Armamentos dos EUA e Reino Unido para a Arábia Saudita",
    resumo: "Exportação contínua de bombas inteligentes guiadas por laser, caças Eurofighter Typhoon e F-15, e munições para a coalizão saudita, empregadas em ataques aéreos contra casamentos, escolas e hospitais no Iêmen.",
    tipoOperacao: "contrato_defesa_armamento",
    anoInicio: 2015,
    anoFim: 2022,
    duracaoEstimada: "2015 - 2022 (7 anos)",
    paisesPatrocinadores: ["Estados Unidos", "Reino Unido", "Arábia Saudita"],
    principaisContratadasDefesa: ["Raytheon (Bombas Paveway)", "Lockheed Martin", "BAE Systems (Eurofighter)"],
    paisTeatro: "Iêmen",
    continenteTeatro: "Oriente Médio",
    localidadeFoco: "Sanaa / Hodeida / Riad",
    latitude: 15.3694,
    longitude: 44.1910,
    baixasEstimadas: "+377.000 mortos no Iêmen (por bombardeios, cólera e fome provocada por bloqueio naval)",
    custoFinanceiroEstimado: "+US$ 65 bilhões em vendas de armas dos EUA à Arábia Saudita entre 2015 e 2021",
    desfechoSoberania: "Pior crise humanitária do mundo segundo a ONU; o Congresso dos EUA aprovou resolução bipartidária pelo fim do apoio à guerra, vetada por Donald Trump.",
    conexaoBrasilOuAmericaLatina: "Investigação da Anistia Internacional e Human Rights Watch revelou que munições de fragmentação fabricadas no Brasil pela empresa Avibras também foram utilizadas pela coalizão no Iêmen.",
    fonteOficialNome: "UN Panel of Experts on Yemen (UN Security Council S/2021/79) / SIPRI Arms Transfers Database",
    urlFonteOficial: "https://www.un.org/securitycouncil/sanctions/2140/panel-of-experts/reports",
    urlDocumentoOriginalPdf: "https://digitallibrary.un.org/record/3899387/files/S_2021_79-EN.pdf",
    identificadorOficialDoc: "UN Security Council Panel of Experts S/2021/79 / SIPRI Yearbook",
    assuntos: ["Iêmen", "Arábia Saudita", "Raytheon", "Avibras Brasil", "Crise Humanitária"],
  },
  {
    id: "CTR-2018-BRA-GRIPEN-SAAB",
    codinome: "Programa FX-2 / Caças Gripen NG Brasil-Suécia",
    titulo: "Contrato Estratégico de Transferência Tecnológica de Caças F-39 Gripen para o Brasil",
    resumo: "Aquisição de 36 caças supersônicos de última geração da sueca Saab pela Força Aérea Brasileira (FAB), com cooperação industrial da Embraer e montagem de parte das aeronaves em solo brasileiro.",
    tipoOperacao: "contrato_defesa_armamento",
    anoInicio: 2014,
    duracaoEstimada: "2014 - presente (em entregas)",
    paisesPatrocinadores: ["Brasil", "Suécia"],
    orgaosForcasEnvolvidas: ["Força Aérea Brasileira (FAB)", "Flygvapnet (Força Aérea Sueca)"],
    principaisContratadasDefesa: ["Saab AB", "Embraer Defesa e Segurança", "AEL Sistemas"],
    paisTeatro: "Brasil",
    continenteTeatro: "América do Sul",
    localidadeFoco: "Gavião Peixoto / Anápolis (Base Aérea)",
    latitude: -21.9969,
    longitude: -47.8890,
    custoFinanceiroEstimado: "39,3 bilhões de coroas suecas (cerca de US$ 5,4 bilhões)",
    desfechoSoberania: "Capacitação aeroespacial nacional e integração de aviônicos de ponta da Embraer, incluindo o painel de exibição única (WAD) desenvolvido por engenheiros brasileiros.",
    conexaoBrasilOuAmericaLatina: "Principal programa de soberania aérea e defesa aeroespacial do Brasil e da América do Sul neste século, baseado na 1ª Ala de Anápolis/GO.",
    fonteOficialNome: "Tribunal de Contas da União (TCU) Acórdão 2715/2016 / Força Aérea Brasileira",
    urlFonteOficial: "https://www.fab.mil.br/gripen",
    urlDocumentoOriginalPdf: "https://pesquisa.apps.tcu.gov.br/documento/acordao-completo/*/NUMACORDAO%253A2715%2520ANOACORDAO%253A2016/DTRELEVANCIA%2520desc%252C%2520NUMACORDAOINT%2520desc/0",
    identificadorOficialDoc: "TCU Acórdão 2715/2016 Plenário / Contrato FAB COPAC 003/2014",
    assuntos: ["Gripen NG", "FAB", "Embraer", "Saab", "Soberania Aérea", "Transferência Tecnológica"],
  },
  {
    id: "CTR-2021-AUS-AUKUS-SUBMARINES",
    codinome: "Pacto AUKUS / Submarinos Nucleares para a Austrália",
    titulo: "Aliança Militar Estratégica AUKUS entre EUA, Reino Unido e Austrália",
    resumo: "Pacto militar que cancelou abruptamente contrato de € 56 bilhões da Austrália com a França para fornecer submarinos de propulsão nuclear projetados pelos EUA e Reino Unido para conter a China no Indo-Pacífico.",
    tipoOperacao: "contrato_defesa_armamento",
    anoInicio: 2021,
    duracaoEstimada: "2021 - 2050 (3 décadas)",
    paisesPatrocinadores: ["Austrália", "Estados Unidos", "Reino Unido"],
    principaisContratadasDefesa: ["BAE Systems", "General Dynamics Electric Boat", "Rolls-Royce Marine Power"],
    paisTeatro: "Austrália",
    continenteTeatro: "Ásia e Oceania",
    localidadeFoco: "Adelaide / San Diego / Barrow-in-Furness",
    latitude: -34.9285,
    longitude: 138.6007,
    custoFinanceiroEstimado: "AU$ 268 a 368 bilhões (cerca de US$ 245 bilhões ao longo de 30 anos)",
    desfechoSoberania: "Crise diplomática inédita com a França ('facada nas costas'), com Paris retirando embaixadores de Washington e Camberra pela primeira vez na história.",
    conexaoBrasilOuAmericaLatina: "Levantou intensos debates na Agência Internacional de Energia Atômica (AIEA) sobre salvaguardas de urânio enriquecido em reatores de submarinos, precedente que beneficia o PROSUB brasileiro.",
    fonteOficialNome: "Australian Parliament Joint Standing Committee on Treaties / US Congressional Research Service Report R47599",
    urlFonteOficial: "https://crsreports.congress.gov/product/pdf/R/R47599",
    urlDocumentoOriginalPdf: "https://crsreports.congress.gov/product/pdf/R/R47599",
    identificadorOficialDoc: "CRS Report R47599 AUKUS Nuclear-Powered Submarines / IAEA Board of Governors GOV/INF/2023/10",
    assuntos: ["AUKUS", "Submarinos Nucleares", "Austrália", "Indo-Pacífico", "Crise com a França"],
  },
  {
    id: "CTR-2024-ISR-USA-MILITARY-AID",
    codinome: "Assistência Militar e Armas dos EUA para Israel",
    titulo: "Suprimento Aéreo Contínuo de Bombas MK-84 e Caças F-35 no Conflito do Oriente Médio",
    resumo: "Envio de mais de 100 carregamentos militares contendo milhares de bombas guiadas de 2.000 libras (MK-84), projéteis de artilharia e apoio financeiro de mais de US$ 17 bilhões aprovado pelo Congresso dos EUA.",
    tipoOperacao: "contrato_defesa_armamento",
    anoInicio: 2023,
    duracaoEstimada: "2023 - presente (em curso)",
    paisesPatrocinadores: ["Estados Unidos", "Alemanha", "Reino Unido"],
    principaisContratadasDefesa: ["Boeing (Bombas JDAM)", "General Dynamics (Corpos de bombas MK-80)", "Lockheed Martin"],
    paisTeatro: "Israel",
    continenteTeatro: "Oriente Médio",
    localidadeFoco: "Tel Aviv / Faixa de Gaza / Jerusalém",
    latitude: 31.7683,
    longitude: 35.2137,
    baixasEstimadas: "+41.000 palestinos mortos em Gaza; 1.200 israelenses mortos no 7 de Outubro",
    custoFinanceiroEstimado: "+US$ 17,9 bilhões em ajuda militar dos EUA (Watson Institute Brown University)",
    desfechoSoberania: "Ação movida pela África do Sul contra Israel na Corte Internacional de Justiça (CIJ) por violação da Convenção contra o Genocídio, com medidas cautelares emitidas pela corte.",
    conexaoBrasilOuAmericaLatina: "O governo brasileiro apoiou a iniciativa da África do Sul na Corte de Haia e criticou reiteradamente o fornecimento ocidental de armas como combustível do massacre civil.",
    fonteOficialNome: "International Court of Justice (South Africa v. Israel) / US Congressional Research Service Report RL33222",
    urlFonteOficial: "https://www.icj-cij.org/case/192",
    urlDocumentoOriginalPdf: "https://www.icj-cij.org/sites/default/files/case-related/192/192-20240126-ORD-01-00-EN.pdf",
    identificadorOficialDoc: "ICJ Order 26 January 2024 / CRS Report RL33222 US Foreign Aid to Israel",
    assuntos: ["Gaza", "Israel", "Corte Internacional de Justiça", "Boeing JDAM", "Direito Internacional Humanitário"],
  },
];

async function executar() {
  console.log("=== INICIANDO ETL DE OPERAÇÕES MILITARES, CONTRATOS E PMCS ===");
  console.log(`Total de eventos brutos mapeados: ${OPERACOES_MILITARES.length}`);

  if (!fs.existsSync(DIR_OUT)) {
    fs.mkdirSync(DIR_OUT, { recursive: true });
  }

  // Sanitização e normalização de chaves uniformes para o esqueleto do compactar
  const operacoesSanitizadas = OPERACOES_MILITARES.map((op) => {
    return {
      id: op.id,
      codinome: op.codinome,
      titulo: sanitizarDadoPessoalInternacional(op.titulo),
      resumo: sanitizarDadoPessoalInternacional(op.resumo),
      tipoOperacao: op.tipoOperacao,
      anoInicio: op.anoInicio,
      anoFim: op.anoFim ?? null,
      duracaoEstimada: op.duracaoEstimada,
      paisesPatrocinadores: op.paisesPatrocinadores,
      orgaosForcasEnvolvidas: op.orgaosForcasEnvolvidas,
      pmcsEnvolvidas: op.pmcsEnvolvidas ?? [],
      principaisContratadasDefesa: op.principaisContratadasDefesa ?? [],
      paisTeatro: op.paisTeatro,
      continenteTeatro: op.continenteTeatro,
      localidadeFoco: op.localidadeFoco,
      latitude: op.latitude,
      longitude: op.longitude,
      baixasEstimadas: op.baixasEstimadas ?? "",
      custoFinanceiroEstimado: op.custoFinanceiroEstimado ?? "",
      desfechoSoberania: sanitizarDadoPessoalInternacional(op.desfechoSoberania),
      conexaoBrasilOuAmericaLatina: op.conexaoBrasilOuAmericaLatina
        ? sanitizarDadoPessoalInternacional(op.conexaoBrasilOuAmericaLatina)
        : "",
      fonteOficialNome: op.fonteOficialNome,
      urlFonteOficial: op.urlFonteOficial,
      urlDocumentoOriginalPdf: op.urlDocumentoOriginalPdf ?? "",
      identificadorOficialDoc: op.identificadorOficialDoc ?? "",
      assuntos: op.assuntos,
    };
  });

  // Compactação estática com codec de strings internadas
  const payloadCompactado = compactar(operacoesSanitizadas);
  const jsonCompactado = JSON.stringify(payloadCompactado);

  const caminhoSaida = path.join(DIR_OUT, "operacoes-militares.compact.json");
  fs.writeFileSync(caminhoSaida, jsonCompactado, "utf-8");

  const tamanhoKb = (Buffer.byteLength(jsonCompactado, "utf-8") / 1024).toFixed(1);
  console.log(`✅ Arquivo gerado com sucesso: ${caminhoSaida} (${tamanhoKb} KB)`);
  console.log(`✅ Total de operações militarmente geolocalizadas: ${operacoesSanitizadas.length}`);
}

executar().catch((erro) => {
  console.error("❌ Erro fatal no ETL de operações militares:", erro);
  process.exit(1);
});
