/**
 * Tags de assunto para convênios ambientais de MG.
 *
 * Extraídas dos campos `nome` e `objetivo` — o mesmo padrão de
 * `tags-licenciamento.ts` e `tags-barragens.ts`. Regras mais específicas
 * vêm antes de regras genéricas para que a ordem das tags faça sentido na tela.
 *
 * As tags são rótulos em português literal/plano, sem jargão técnico.
 */
import type { RegraTag } from "@/lib/tags";

export const REGRAS_TAGS_CONVENIOS: RegraTag[] = [
  {
    tag: "matas e florestas",
    termos: [
      "mata atlantica",
      "mata atlântica",
      "floresta",
      "reflorestamento",
      "replantio",
      "restauracao florestal",
      "restauração florestal",
      "reserva florestal",
      "fragmento florestal",
      "manejo florestal",
      "plantio de arvores",
      "plantio de árvores",
      "regeneracao natural",
      "regeneração natural",
      "cobertura florestal",
    ],
  },
  {
    tag: "ripar",
    termos: [
      "ripar",
      "ripar ribeirao",
      "ripar ribeirão",
      "recuperação de áreas de preservação permanente",
      "recuperacao de areas de preservacao permanente",
      "area de preservacao permanente",
      "área de preservação permanente",
      "app",
    ],
  },
  {
    tag: "nascentes e olhos d'água",
    termos: [
      "nascente",
      "olho d agua",
      "olho d'água",
      "olhos d agua",
      "manancial",
      "proteção de nascentes",
      "protecao de nascentes",
    ],
  },
  {
    tag: "recursos hídricos",
    termos: [
      "recursos hidricos",
      "recursos hídricos",
      "bacia hidrografica",
      "bacia hidrográfica",
      "comite de bacia",
      "comitê de bacia",
      "outorga",
      "captação de agua",
      "captação de água",
      "tratamento de agua",
      "tratamento de água",
      "saneamento",
      "esgoto",
      "tratamento de esgoto",
    ],
  },
  {
    tag: "solos e erosão",
    termos: [
      "controle de erosao",
      "controle de erosão",
      "recuperação de solos",
      "recuperacao de solos",
      "barragem de contencao",
      "barragem de contenção",
      "terra roxa",
      "degradação do solo",
      "degradacao do solo",
    ],
  },
  {
    tag: "biodiversidade e fauna",
    termos: [
      "biodiversidade",
      "fauna",
      "flora",
      "animais silvestres",
      "animais silvestres",
      "conservação da biodiversidade",
      "conservacao da biodiversidade",
      "corredor ecológico",
      "corredor ecologico",
      "área de conservação",
      "area de conservacao",
      "unidade de conservacao",
      "unidade de conservação",
      "parque",
      "reserva biologica",
      "reserva biológica",
      "refugio de vida silvestre",
      "refúgio de vida silvestre",
    ],
  },
  {
    tag: "avifauna",
    termos: [
      "avifauna",
      "aves",
      "aves migratórias",
      "aves migratorias",
      "passaros",
      "pássaros",
      "anilhamento de aves",
    ],
  },
  {
    tag: "ichthyofauna",
    termos: [
      "ictiofauna",
      "peixes",
      "peixe",
      "conservação de peixes",
      "conservacao de peixes",
      "migracao de peixes",
      "migração de peixes",
    ],
  },
  {
    tag: "educação ambiental",
    termos: [
      "educação ambiental",
      "educacao ambiental",
      "conscientização ambiental",
      "conscientizacao ambiental",
      "capacitação ambiental",
      "capacitacao ambiental",
      "campanha ambiental",
      "agenda 21",
      "conselho municipal de meio ambiente",
    ],
  },
  {
    tag: "monitoramento e controle",
    termos: [
      "monitoramento",
      "controle ambiental",
      " fiscalização ambiental",
      " fiscalizacao ambiental",
      "cadastro ambiental",
      "geoprocessamento",
      "sensoriamento remoto",
      "mapeamento ambiental",
      "qualidade ambiental",
      "indicadores ambientais",
    ],
  },
  {
    tag: "infraestrutura ambiental",
    termos: [
      "infrastructure ambiental",
      "infraestrutura ambiental",
      "estacao de tratamento",
      "estação de tratamento",
      "ATERRO SANITÁRIO",
      "aterro sanitario",
      "usina de compostagem",
      "estacao de monitoramento",
      "estação de monitoramento",
      "laboratório ambiental",
      "laboratorio ambiental",
    ],
  },
  {
    tag: "quietude e proteção urbana",
    termos: [
      "parque municipal",
      "parque urbano",
      "área verde urbana",
      "area verde urbana",
      "jardim botânico",
      "jardim botanico",
      "praça",
      "qualidade do ar",
      "qualidade do ar urbano",
      "poluição sonora",
      "poluição do ar",
    ],
  },
  {
    tag: "áreas degradadas",
    termos: [
      "área degradada",
      "area degradada",
      "passivo ambiental",
      "despoluição",
      "despoluicao",
      "recuperação de área degradada",
      "recuperacao de area degradada",
      "remediação ambiental",
      "remediacao ambiental",
    ],
  },
  {
    tag: "mineração e rejeitos",
    termos: [
      "mineração",
      "mineracao",
      "mina",
      "rejeitos",
      "rejeito",
      "barragem de rejeitos",
      "barragem de rejeito",
      "lavra",
      "extração mineral",
      "extracao mineral",
    ],
  },
  {
    tag: "queimadas e prevenção",
    termos: [
      "queimada",
      "queimadas",
      "incêndio florestal",
      "incendio florestal",
      "prevenção de incêndio",
      "prevencao de incendio",
      "combate ao fogo",
      "fogo",
    ],
  },
  {
    tag: "clima e mudanças climáticas",
    termos: [
      "mudança climática",
      "mudanca climatica",
      "clima",
      "emissão de gases",
      "emissao de gases",
      "créditos de carbono",
      "creditos de carbono",
      "seqüestro de carbono",
      "sequestro de carbono",
      "offset de carbono",
      "aquecimento global",
    ],
  },
  {
    tag: "resíduos sólidos",
    termos: [
      "resíduos sólidos",
      "residuos solidos",
      "resíduos",
      "residuos",
      "coleta seletiva",
      "reciclagem",
      "descarte inadequado",
      "lixo",
      "logística reversa",
      "logistica reversa",
    ],
  },
  {
    tag: "turismo ecológico",
    termos: [
      "turismo ecológico",
      "turismo ecologico",
      "ecoturismo",
      "trilha",
      "caminhada ecológica",
      "caminhada ecologica",
      "observação de fauna",
      "observacao de fauna",
      "loge de natureza",
      "loge",
    ],
  },
  {
    tag: "gestão ambiental",
    termos: [
      "gestão ambiental",
      "gestao ambiental",
      "plano de gestão ambiental",
      "plano de gestao ambiental",
      "licenciamento ambiental",
      "avaliação de impacto ambiental",
      "avaliacao de impacto ambiental",
      "relatório de impacto ambiental",
      "relatorio de impacto ambiental",
      "eia",
      "rima",
      "controle ambiental integrado",
    ],
  },
];

/** Inclui o campo `nome` E `objetivo` na extração. */
export const CAMPOS_TAGS_CONVENIOS: (keyof {
  nome: string;
  objetivo: string;
})[] = ["nome", "objetivo"];
