/**
 * Tags de assunto para projetos de TAC ambiental de MG.
 *
 * Extraídas dos campos `projeto` e `relato` — o mesmo padrão de
 * `tags-convenios.ts`. Regras mais específicas vêm antes de regras genéricas.
 *
 * As tags são rótulos em português literal/plano, sem jargão técnico.
 */
import type { RegraTag } from "@/lib/tags";

export const REGRAS_TAGS_TAC: RegraTag[] = [
  {
    tag: "água limpa pra gente",
    termos: [
      "tratamento de água",
      "tratamento de água",
      "abastecimento de água",
      "abastecimento de agua",
      "captação de água",
      "captação de agua",
      "estação de tratamento",
      "estacao de tratamento",
      "saneamento",
      "esgoto",
      "tratamento de esgoto",
      "ETE",
      "ETA",
      "reservatório de água",
      "reservatorio de agua",
      "adutora",
      "adução",
    ],
  },
  {
    tag: "nascentes vivas",
    termos: [
      "nascente",
      "olho d'água",
      "olho d agua",
      "olhos d'água",
      "manancial",
      "proteção de nascentes",
      "protecao de nascentes",
      "recuperação de nascentes",
      "recuperacao de nascentes",
      "barrinha",
    ],
  },
  {
    tag: "matas e florestas",
    termos: [
      "mata atlântica",
      "mata atlantica",
      "floresta",
      "reflorestamento",
      "replantio",
      "restauração florestal",
      "restauracao florestal",
      "reserva florestal",
      "fragmento florestal",
      "manejo florestal",
      "plantio de árvores",
      "plantio de arvores",
      "regeneração natural",
      "regeneracao natural",
      "cobertura florestal",
      "área de preservação permanente",
      "area de preservacao permanente",
      "APP",
      "RiPPAR",
      "ripar",
    ],
  },
  {
    tag: "biodiversidade e fauna",
    termos: [
      "biodiversidade",
      "fauna",
      "flora",
      "animais silvestres",
      "animais silvestres",
      "conservação da biodiversidade",
      "conservacao da biodiversidade",
      "corredor ecológico",
      "corredor ecologico",
      "área de conservação",
      "area de conservacao",
      "unidade de conservação",
      "unidade de conservacao",
      "parque",
      "reserva biológica",
      "reserva biologica",
      "refúgio de vida silvestre",
      "refugio de vida silvestre",
    ],
  },
  {
    tag: "peixes e rios",
    termos: [
      "ictiofauna",
      "peixes",
      "peixe",
      "conservação de peixes",
      "conservacao de peixes",
      "migração de peixes",
      "migracao de peixes",
      "fauna aquática",
      "fauna aquatica",
      "ribeirão",
      "ribeirao",
      "rio",
      "córrego",
      "corrego",
      "curso d'água",
      "curso d agua",
    ],
  },
  {
    tag: "aves e monitoring",
    termos: [
      "avifauna",
      "aves",
      "aves migratórias",
      "aves migratorias",
      "passaros",
      "pássaros",
      "anilhamento de aves",
      "monitoramento ambiental",
      "monitoramento",
    ],
  },
  {
    tag: "educação ambiental",
    termos: [
      "educação ambiental",
      "educacao ambiental",
      "conscientização ambiental",
      "conscientizacao ambiental",
      "capacitação ambiental",
      "capacitacao ambiental",
      "campanha ambiental",
      "agenda 21",
      "conselho municipal de meio ambiente",
    ],
  },
  {
    tag: "solos e erosão",
    termos: [
      "controle de erosão",
      "controle de erosao",
      "recuperação de solos",
      "recuperacao de solos",
      "barragem de contenção",
      "barragem de contencao",
      "degradação do solo",
      "degradacao do solo",
      "barragem",
    ],
  },
  {
    tag: "áreas degradadas",
    termos: [
      "área degradada",
      "area degradada",
      "passivo ambiental",
      "despoluição",
      "despoluicao",
      "recuperação de área degradada",
      "recuperacao de area degradada",
      "remediação ambiental",
      "remediacao ambiental",
    ],
  },
  {
    tag: "mineração e rejeitos",
    termos: [
      "mineração",
      "mineracao",
      "mina",
      "rejeitos",
      "rejeito",
      "barragem de rejeitos",
      "barragem de rejeito",
      "lavra",
      "extração mineral",
      "extracao mineral",
    ],
  },
  {
    tag: "resíduos sólidos",
    termos: [
      "resíduos sólidos",
      "residuos solidos",
      "resíduos",
      "residuos",
      "coleta seletiva",
      "reciclagem",
      "descarte inadequado",
      "lixo",
      "logística reversa",
      "logistica reversa",
    ],
  },
  {
    tag: "clima e ar",
    termos: [
      "mudança climática",
      "mudanca climatica",
      "clima",
      "emissão de gases",
      "emissao de gases",
      "qualidade do ar",
      "poluição do ar",
      "queimada",
      "queimadas",
      "incêndio florestal",
      "incendio florestal",
    ],
  },
  {
    tag: "licenciamento",
    termos: [
      "licenciamento ambiental",
      "licença",
      "licenca",
      "EIA",
      "RIMA",
      "avaliação de impacto",
      "avaliacao de impacto",
    ],
  },
];
