/**
 * Cobertura da Defensoria Pública de Minas Gerais, comarca a comarca.
 * ARQUIVO GERADO por `scripts/gerar-transparencia-justica.mts`.
 *
 * ═══ O DENOMINADOR É O PRODUTO ═══
 *
 * A DPMG publica onde ELA está. Nunca publica onde ela **não** está. "128
 * unidades" parece cobertura boa; contra as 298 comarcas do estado, vira
 * déficit. Esta camada existe para juntar as duas pontas.
 *
 * ⚠️ **AS FONTES DIVERGEM, E AS DUAS FICAM.** A DPMG lista 129 unidades hoje
 * (128 comarcas mineiras + a sede em Brasília); a Pesquisa Nacional da
 * Defensoria 2025 marca 120 comarcas como atendidas. São recortes
 * diferentes — unidade física instalada contra comarca declarada atendida —,
 * e escolher um e calar esconderia a diferença.
 *
 * ⚠️ Duas armadilhas medidas na coleta: a planilha nacional só baixa com
 * headers de navegador (curl cru = HTTP 406), e o CSV do IPEA 2013 é **CP850**,
 * não ISO-8859-1 — decodificar errado produz texto ilegível em silêncio.
 */

export interface ComarcaDefensoria {
  nome: string;
  populacao: number | null;
  populacaoAte3SM: number | null;
  municipios: number | null;
  /** SIM | NÃO | PARCIALMENTE — Pesquisa Nacional da Defensoria 2025 */
  atendida2025: string | null;
  /** A DPMG lista unidade física nesta comarca hoje? */
  temUnidadeHoje: boolean;
  link: string | null;
  atendida2013: string | null;
  defensores2013: number | null;
}

export const COBERTURA_DEFENSORIA = {
  extraidoEm: "2026-08-22",
  comarcas: 298,
  atendidas2025: 120,
  naoAtendidas2025: 176,
  parcialmente2025: 2,
  comUnidadeFisicaHoje: 128,
  comarcas2013: 295,
  atendidas2013: 105,
  populacaoEmComarcaNaoAtendida: 6090773,
} as const;

export const COMARCAS_MG: ComarcaDefensoria[] = [
 {
  "nome": "ABAETÉ",
  "populacao": 28525,
  "populacaoAte3SM": 26555,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ABRE CAMPO",
  "populacao": 74492,
  "populacaoAte3SM": 71989,
  "municipios": 6,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/abre-campo/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "AÇUCENA",
  "populacao": 39940,
  "populacaoAte3SM": 37806,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ÁGUAS FORMOSAS",
  "populacao": 48468,
  "populacaoAte3SM": 46990,
  "municipios": 7,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "AIMORÉS",
  "populacao": 26165,
  "populacaoAte3SM": 24321,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "AIURUOCA",
  "populacao": 27372,
  "populacaoAte3SM": 26004,
  "municipios": 7,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ALÉM PARAÍBA",
  "populacao": 39687,
  "populacaoAte3SM": 35937,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/alem-paraiba/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "ALFENAS",
  "populacao": 89752,
  "populacaoAte3SM": 79835,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/alfenas/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 4
 },
 {
  "nome": "ALMENARA",
  "populacao": 88385,
  "populacaoAte3SM": 85327,
  "municipios": 7,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "ALPINÓPOLIS",
  "populacao": 26756,
  "populacaoAte3SM": 24409,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ALTO RIO DOCE",
  "populacao": 16593,
  "populacaoAte3SM": 16175,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ALVINÓPOLIS",
  "populacao": 23151,
  "populacaoAte3SM": 22219,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ANDRADAS",
  "populacao": 45721,
  "populacaoAte3SM": 41030,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ANDRELÂNDIA",
  "populacao": 34404,
  "populacaoAte3SM": 32213,
  "municipios": 5,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ARAÇUAÍ",
  "populacao": 97996,
  "populacaoAte3SM": 95186,
  "municipios": 6,
  "atendida2025": "NÃO",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/aracuai/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ARAGUARI",
  "populacao": 129183,
  "populacaoAte3SM": 112864,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/araguari/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 4
 },
 {
  "nome": "ARAXÁ",
  "populacao": 121889,
  "populacaoAte3SM": 103877,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/araxa/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "ARCOS",
  "populacao": 51689,
  "populacaoAte3SM": 46522,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/arcos/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "AREADO",
  "populacao": 28465,
  "populacaoAte3SM": 26639,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/areado/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "ARINOS",
  "populacao": 52059,
  "populacaoAte3SM": 50516,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BAEPENDI",
  "populacao": 18768,
  "populacaoAte3SM": 17755,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/baependi/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "BAMBUÍ",
  "populacao": 29891,
  "populacaoAte3SM": 27072,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/bambui/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "BARÃO DE COCAIS",
  "populacao": 37870,
  "populacaoAte3SM": 34753,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BARBACENA",
  "populacao": 189699,
  "populacaoAte3SM": 171509,
  "municipios": 12,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/barbacena/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 6
 },
 {
  "nome": "BARROSO",
  "populacao": 20566,
  "populacaoAte3SM": 18992,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/barroso/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BELO HORIZONTE",
  "populacao": 2416339,
  "populacaoAte3SM": 1859635,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/belo-horizonte/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 221
 },
 {
  "nome": "BELO VALE",
  "populacao": 14237,
  "populacaoAte3SM": 13415,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BETIM",
  "populacao": 429236,
  "populacaoAte3SM": 386843,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/betim/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 9
 },
 {
  "nome": "BICAS",
  "populacao": 24443,
  "populacaoAte3SM": 22539,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BOA ESPERANÇA",
  "populacao": 63700,
  "populacaoAte3SM": 59630,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/boa-esperanca/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "BOCAIÚVA",
  "populacao": 71366,
  "populacaoAte3SM": 68109,
  "municipios": 5,
  "atendida2025": "NÃO",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/bocaiuva/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BOM DESPACHO",
  "populacao": 61773,
  "populacaoAte3SM": 54370,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/bom-despacho/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "BOM SUCESSO",
  "populacao": 37901,
  "populacaoAte3SM": 36140,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BONFIM",
  "populacao": 24207,
  "populacaoAte3SM": 23062,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/bonfim/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "BONFINÓPOLIS DE MINAS",
  "populacao": 19898,
  "populacaoAte3SM": 19101,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BORDA DA MATA",
  "populacao": 21710,
  "populacaoAte3SM": 20090,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/borda-da-mata/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "BOTELHOS",
  "populacao": 15137,
  "populacaoAte3SM": 14056,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BRASÍLIA DE MINAS",
  "populacao": 67460,
  "populacaoAte3SM": 65671,
  "municipios": 6,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/brasilia-de-minas/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BRAZÓPOLIS",
  "populacao": 23957,
  "populacaoAte3SM": 22383,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": null,
  "defensores2013": null
 },
 {
  "nome": "BRUMADINHO",
  "populacao": 40777,
  "populacaoAte3SM": 35873,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/brumadinho/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BUENO BRANDÃO",
  "populacao": 19018,
  "populacaoAte3SM": 18129,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BUENÓPOLIS",
  "populacao": 17713,
  "populacaoAte3SM": 16922,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "BURITIS",
  "populacao": 32796,
  "populacaoAte3SM": 30869,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CABO VERDE",
  "populacao": 17389,
  "populacaoAte3SM": 16405,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CACHOEIRA DE MINAS",
  "populacao": 23431,
  "populacaoAte3SM": 22101,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CAETÉ",
  "populacao": 50301,
  "populacaoAte3SM": 46227,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CALDAS",
  "populacao": 14588,
  "populacaoAte3SM": 13482,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CAMANDUCAIA",
  "populacao": 40883,
  "populacaoAte3SM": 37900,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/camanducaia/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "CAMBUÍ",
  "populacao": 54940,
  "populacaoAte3SM": 51053,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/cambui/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "CAMBUQUIRA",
  "populacao": 12560,
  "populacaoAte3SM": 11493,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/cambuquira/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CAMPANHA",
  "populacao": 16334,
  "populacaoAte3SM": 14721,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/campanha/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "CAMPESTRE",
  "populacao": 27289,
  "populacaoAte3SM": 25542,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CAMPINA VERDE",
  "populacao": 18250,
  "populacaoAte3SM": 16628,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/campina-verde/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "CAMPO BELO",
  "populacao": 75274,
  "populacaoAte3SM": 69445,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/campo-belo/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "CAMPOS ALTOS",
  "populacao": 16612,
  "populacaoAte3SM": 15517,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CAMPOS GERAIS",
  "populacao": 38433,
  "populacaoAte3SM": 36561,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CANÁPOLIS",
  "populacao": 21195,
  "populacaoAte3SM": 19735,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CANDEIAS",
  "populacao": 14236,
  "populacaoAte3SM": 13317,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CAPELINHA",
  "populacao": 61941,
  "populacaoAte3SM": 59245,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CAPINÓPOLIS",
  "populacao": 21068,
  "populacaoAte3SM": 19351,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CARANDAÍ",
  "populacao": 31744,
  "populacaoAte3SM": 29883,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "CARANGOLA",
  "populacao": 50963,
  "populacaoAte3SM": 47296,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CARATINGA",
  "populacao": 169530,
  "populacaoAte3SM": 160057,
  "municipios": 11,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/caratinga/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 4
 },
 {
  "nome": "CARLOS CHAGAS",
  "populacao": 18852,
  "populacaoAte3SM": 17952,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CARMO DA MATA",
  "populacao": 11279,
  "populacaoAte3SM": 10651,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CARMO DE MINAS",
  "populacao": 17290,
  "populacaoAte3SM": 16287,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CARMO DO CAJURU",
  "populacao": 24376,
  "populacaoAte3SM": 22570,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/carmo-do-cajuru/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "CARMO DO PARANAÍBA",
  "populacao": 29899,
  "populacaoAte3SM": 27525,
  "municipios": 1,
  "atendida2025": "PARCIALMENTE",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CARMO DO RIO CLARO",
  "populacao": 32132,
  "populacaoAte3SM": 29677,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CARMÓPOLIS DE MINAS",
  "populacao": 18498,
  "populacaoAte3SM": 17369,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CÁSSIA",
  "populacao": 32907,
  "populacaoAte3SM": 30193,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/cassia/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "CATAGUASES",
  "populacao": 95961,
  "populacaoAte3SM": 88196,
  "municipios": 5,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/cataguases/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "CAXAMBU",
  "populacao": 21436,
  "populacaoAte3SM": 19302,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/caxambu/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "CLÁUDIO",
  "populacao": 31665,
  "populacaoAte3SM": 29471,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CONCEIÇÃO DAS ALAGOAS",
  "populacao": 35711,
  "populacaoAte3SM": 31331,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "CONCEIÇÃO DO MATO DENTRO",
  "populacao": 40507,
  "populacaoAte3SM": 38992,
  "municipios": 6,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/conceicao-do-mato-dentro/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CONCEIÇÃO DO RIO VERDE",
  "populacao": 12780,
  "populacaoAte3SM": 12085,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CONGONHAS",
  "populacao": 54986,
  "populacaoAte3SM": 48140,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CONQUISTA",
  "populacao": 6864,
  "populacaoAte3SM": 6171,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CONSELHEIRO LAFAIETE",
  "populacao": 167880,
  "populacaoAte3SM": 149042,
  "municipios": 9,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/conselheiro-lafaiete/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 6
 },
 {
  "nome": "CONSELHEIRO PENA",
  "populacao": 33949,
  "populacaoAte3SM": 32145,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CONTAGEM",
  "populacao": 649975,
  "populacaoAte3SM": 559782,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/contagem/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 16
 },
 {
  "nome": "CORAÇÃO DE JESUS",
  "populacao": 44692,
  "populacaoAte3SM": 43791,
  "municipios": 5,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CORINTO",
  "populacao": 26716,
  "populacaoAte3SM": 25125,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "COROMANDEL",
  "populacao": 36378,
  "populacaoAte3SM": 33231,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/coromandel/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "CORONEL FABRICIANO",
  "populacao": 117939,
  "populacaoAte3SM": 104983,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CRISTINA",
  "populacao": 25184,
  "populacaoAte3SM": 24053,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CRUZÍLIA",
  "populacao": 19594,
  "populacaoAte3SM": 18560,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/cruzilia/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "CURVELO",
  "populacao": 111659,
  "populacaoAte3SM": 104754,
  "municipios": 5,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/curvelo/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "DIAMANTINA",
  "populacao": 88597,
  "populacaoAte3SM": 83107,
  "municipios": 9,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/diamantina/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "DIVINO",
  "populacao": 30088,
  "populacaoAte3SM": 28878,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "DIVINÓPOLIS",
  "populacao": 242328,
  "populacaoAte3SM": 209513,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/divinopolis/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 9
 },
 {
  "nome": "DORES DO INDAIÁ",
  "populacao": 19627,
  "populacaoAte3SM": 18207,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ELÓI MENDES",
  "populacao": 27343,
  "populacaoAte3SM": 25307,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ENTRE RIOS DE MINAS",
  "populacao": 33581,
  "populacaoAte3SM": 32057,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ERVÁLIA",
  "populacao": 29169,
  "populacaoAte3SM": 27916,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/ervalia/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "ESMERALDAS",
  "populacao": 91573,
  "populacaoAte3SM": 86977,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ESPERA FELIZ",
  "populacao": 35368,
  "populacaoAte3SM": 33580,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ESPINOSA",
  "populacao": 37481,
  "populacaoAte3SM": 36814,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ESTRELA DO SUL",
  "populacao": 11109,
  "populacaoAte3SM": 10237,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "EUGENÓPOLIS",
  "populacao": 18368,
  "populacaoAte3SM": 17332,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "EXTREMA",
  "populacao": 65454,
  "populacaoAte3SM": 57844,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/extrema/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "FERROS",
  "populacao": 12348,
  "populacaoAte3SM": 11905,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "FORMIGA",
  "populacao": 85772,
  "populacaoAte3SM": 78408,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/formiga/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "FRANCISCO SÁ",
  "populacao": 38220,
  "populacaoAte3SM": 37164,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/francisco-sa/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "FRUTAL",
  "populacao": 90148,
  "populacaoAte3SM": 80386,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/frutal/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "GALILÉIA",
  "populacao": 13642,
  "populacaoAte3SM": 13057,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "GOVERNADOR VALADARES",
  "populacao": 299306,
  "populacaoAte3SM": 271467,
  "municipios": 7,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/governador-valadares/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 12
 },
 {
  "nome": "GRÃO MOGOL",
  "populacao": 28704,
  "populacaoAte3SM": 28231,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "GUANHÃES",
  "populacao": 41643,
  "populacaoAte3SM": 39032,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/guanhaes/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "GUAPÉ",
  "populacao": 14073,
  "populacaoAte3SM": 13357,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "GUARANÉSIA",
  "populacao": 19611,
  "populacaoAte3SM": 18257,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/guaranesia/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "GUARANI",
  "populacao": 19738,
  "populacaoAte3SM": 18561,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "GUAXUPÉ",
  "populacao": 57600,
  "populacaoAte3SM": 51834,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/guaxupe/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "IBIÁ",
  "populacao": 26269,
  "populacaoAte3SM": 24089,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "IBIRACI",
  "populacao": 15834,
  "populacaoAte3SM": 14503,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/ibiraci/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "IBIRITÉ",
  "populacao": 234586,
  "populacaoAte3SM": 219423,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/ibirite/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "IGARAPÉ",
  "populacao": 84971,
  "populacaoAte3SM": 79222,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/igarape/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 5
 },
 {
  "nome": "IGUATAMA",
  "populacao": 6845,
  "populacaoAte3SM": 6334,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/iguatama/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "INHAPIM",
  "populacao": 63919,
  "populacaoAte3SM": 61261,
  "municipios": 7,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "IPANEMA",
  "populacao": 39392,
  "populacaoAte3SM": 37559,
  "municipios": 5,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "IPATINGA",
  "populacao": 301285,
  "populacaoAte3SM": 261124,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/ipatinga/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 9
 },
 {
  "nome": "ITABIRA",
  "populacao": 132255,
  "populacaoAte3SM": 117065,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/itabira/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ITABIRITO",
  "populacao": 55877,
  "populacaoAte3SM": 49089,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ITAGUARA",
  "populacao": 14325,
  "populacaoAte3SM": 13133,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ITAJUBÁ",
  "populacao": 116719,
  "populacaoAte3SM": 101042,
  "municipios": 5,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/itajuba/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 5
 },
 {
  "nome": "ITAMARANDIBA",
  "populacao": 47590,
  "populacaoAte3SM": 45888,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ITAMBACURI",
  "populacao": 45079,
  "populacaoAte3SM": 43536,
  "municipios": 7,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ITAMOGI",
  "populacao": 11062,
  "populacaoAte3SM": 10495,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/itamogi/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "ITAMONTE",
  "populacao": 18009,
  "populacaoAte3SM": 16621,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/itamonte/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "ITANHANDU",
  "populacao": 24826,
  "populacaoAte3SM": 22979,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "ITANHOMI",
  "populacao": 15948,
  "populacaoAte3SM": 15309,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ITAPAGIPE",
  "populacao": 19861,
  "populacaoAte3SM": 17935,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ITAPECERICA",
  "populacao": 33684,
  "populacaoAte3SM": 31658,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ITAÚNA",
  "populacao": 116103,
  "populacaoAte3SM": 103025,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/itauna/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 4
 },
 {
  "nome": "ITUIUTABA",
  "populacao": 111600,
  "populacaoAte3SM": 98779,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/ituiutaba/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 4
 },
 {
  "nome": "ITUMIRIM",
  "populacao": 17978,
  "populacaoAte3SM": 16730,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "ITURAMA",
  "populacao": 62576,
  "populacaoAte3SM": 55898,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/iturama/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "JABOTICATUBAS",
  "populacao": 26793,
  "populacaoAte3SM": 25307,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/jaboticatubas/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "JACINTO",
  "populacao": 43069,
  "populacaoAte3SM": 41839,
  "municipios": 5,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "JACUÍ",
  "populacao": 11148,
  "populacaoAte3SM": 10330,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "JACUTINGA",
  "populacao": 29728,
  "populacaoAte3SM": 27170,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "JAÍBA",
  "populacao": 48354,
  "populacaoAte3SM": 46543,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": null,
  "defensores2013": null
 },
 {
  "nome": "JANAÚBA",
  "populacao": 87831,
  "populacaoAte3SM": 83695,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/janauba/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "JANUÁRIA",
  "populacao": 113138,
  "populacaoAte3SM": 108989,
  "municipios": 5,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/januaria/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "JEQUERI",
  "populacao": 27583,
  "populacaoAte3SM": 26688,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "JEQUITINHONHA",
  "populacao": 49634,
  "populacaoAte3SM": 47880,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "JOÃO MONLEVADE",
  "populacao": 83360,
  "populacaoAte3SM": 73038,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/joao-monlevade/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "JOÃO PINHEIRO",
  "populacao": 63964,
  "populacaoAte3SM": 59563,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "JUATUBA",
  "populacao": 32726,
  "populacaoAte3SM": 30310,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": null,
  "defensores2013": null
 },
 {
  "nome": "JUIZ DE FORA",
  "populacao": 571740,
  "populacaoAte3SM": 475732,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/juiz-de-fora/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 28
 },
 {
  "nome": "LAGOA DA PRATA",
  "populacao": 58255,
  "populacaoAte3SM": 52531,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/lagoa-da-prata/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "LAGOA SANTA",
  "populacao": 79981,
  "populacaoAte3SM": 66729,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/lagoa-santa/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "LAJINHA",
  "populacao": 27683,
  "populacaoAte3SM": 26214,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "LAMBARI",
  "populacao": 28862,
  "populacaoAte3SM": 26712,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "LAVRAS",
  "populacao": 127107,
  "populacaoAte3SM": 109954,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/lavras/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "LEOPOLDINA",
  "populacao": 66758,
  "populacaoAte3SM": 61312,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/leopoldina/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "LIMA DUARTE",
  "populacao": 21552,
  "populacaoAte3SM": 20482,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "LUZ",
  "populacao": 21282,
  "populacaoAte3SM": 19416,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/luz/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "MACHADO",
  "populacao": 42248,
  "populacaoAte3SM": 38275,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MALACACHETA",
  "populacao": 32845,
  "populacaoAte3SM": 31918,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MANGA",
  "populacao": 36666,
  "populacaoAte3SM": 36015,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MANHUAÇU",
  "populacao": 153099,
  "populacaoAte3SM": 143334,
  "municipios": 6,
  "atendida2025": "NÃO",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/manhuacu/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MANHUMIRIM",
  "populacao": 52311,
  "populacaoAte3SM": 49504,
  "municipios": 5,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/manhumirim/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "MANTENA",
  "populacao": 61688,
  "populacaoAte3SM": 59052,
  "municipios": 7,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MAR DE ESPANHA",
  "populacao": 18303,
  "populacaoAte3SM": 17100,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MARIANA",
  "populacao": 67654,
  "populacaoAte3SM": 60784,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/mariana/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MARTINHO CAMPOS",
  "populacao": 14461,
  "populacaoAte3SM": 13385,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MATEUS LEME",
  "populacao": 40239,
  "populacaoAte3SM": 37172,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MATIAS BARBOSA",
  "populacao": 24679,
  "populacaoAte3SM": 22902,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/matias-barbosa/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "MATOZINHOS",
  "populacao": 62336,
  "populacaoAte3SM": 57836,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MEDINA",
  "populacao": 46473,
  "populacaoAte3SM": 44751,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MERCÊS",
  "populacao": 10609,
  "populacaoAte3SM": 10116,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MESQUITA",
  "populacao": 13817,
  "populacaoAte3SM": 13329,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MINAS NOVAS",
  "populacao": 57316,
  "populacaoAte3SM": 55977,
  "municipios": 5,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MIRADOURO",
  "populacao": 12806,
  "populacaoAte3SM": 12285,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MIRAÍ",
  "populacao": 17141,
  "populacaoAte3SM": 16152,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MONTALVÂNIA",
  "populacao": 20089,
  "populacaoAte3SM": 19565,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MONTE ALEGRE DE MINAS",
  "populacao": 20666,
  "populacaoAte3SM": 19138,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/monte-alegre-de-minas/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "MONTE AZUL",
  "populacao": 37678,
  "populacaoAte3SM": 36516,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MONTE BELO",
  "populacao": 13340,
  "populacaoAte3SM": 12542,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MONTE CARMELO",
  "populacao": 62086,
  "populacaoAte3SM": 57070,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MONTE SANTO DE MINAS",
  "populacao": 30649,
  "populacaoAte3SM": 28553,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/monte-santo-de-minas/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "MONTE SIÃO",
  "populacao": 24933,
  "populacaoAte3SM": 22158,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/monte-siao/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "MONTES CLAROS",
  "populacao": 471543,
  "populacaoAte3SM": 427148,
  "municipios": 7,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/montes-claros/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 13
 },
 {
  "nome": "MORADA NOVA DE MINAS",
  "populacao": 11773,
  "populacaoAte3SM": 10952,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MURIAÉ",
  "populacao": 119099,
  "populacaoAte3SM": 107659,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/muriae/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 5
 },
 {
  "nome": "MUTUM",
  "populacao": 28670,
  "populacaoAte3SM": 27430,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "MUZAMBINHO",
  "populacao": 34070,
  "populacaoAte3SM": 30597,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "NANUQUE",
  "populacao": 42490,
  "populacaoAte3SM": 39982,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/nanuque/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "NATÉRCIA",
  "populacao": 13911,
  "populacaoAte3SM": 13342,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "NEPOMUCENO",
  "populacao": 25774,
  "populacaoAte3SM": 24459,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "NOVA ERA",
  "populacao": 28219,
  "populacaoAte3SM": 26177,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "NOVA LIMA",
  "populacao": 146503,
  "populacaoAte3SM": 122584,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/nova-lima/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "NOVA PONTE",
  "populacao": 31681,
  "populacaoAte3SM": 28237,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "NOVA RESENDE",
  "populacao": 21496,
  "populacaoAte3SM": 20012,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "NOVA SERRANA",
  "populacao": 135391,
  "populacaoAte3SM": 125378,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/nova-serrana/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "NOVO CRUZEIRO",
  "populacao": 64882,
  "populacaoAte3SM": 63540,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/novo-cruzeiro/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "OLIVEIRA",
  "populacao": 46845,
  "populacaoAte3SM": 43542,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "OURO BRANCO",
  "populacao": 40411,
  "populacaoAte3SM": 34202,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/ouro-branco/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "OURO FINO",
  "populacao": 40737,
  "populacaoAte3SM": 37417,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/ouro-fino/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "OURO PRETO",
  "populacao": 77601,
  "populacaoAte3SM": 68752,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PALMA",
  "populacao": 10733,
  "populacaoAte3SM": 10240,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/palma/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "PARÁ DE MINAS",
  "populacao": 145825,
  "populacaoAte3SM": 132693,
  "municipios": 7,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/para-de-minas/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "PARACATU",
  "populacao": 98397,
  "populacaoAte3SM": 89137,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/paracatu/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PARAGUAÇU",
  "populacao": 25019,
  "populacaoAte3SM": 23169,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PARAISÓPOLIS",
  "populacao": 33936,
  "populacaoAte3SM": 31618,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PARAOPEBA",
  "populacao": 46448,
  "populacaoAte3SM": 43605,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PASSA QUATRO",
  "populacao": 15842,
  "populacaoAte3SM": 14695,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/passa-quatro/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "PASSA TEMPO",
  "populacao": 15580,
  "populacaoAte3SM": 14796,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PASSOS",
  "populacao": 124442,
  "populacaoAte3SM": 109319,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/passos/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 6
 },
 {
  "nome": "PATOS DE MINAS",
  "populacao": 202141,
  "populacaoAte3SM": 179468,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/patos-de-minas/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 5
 },
 {
  "nome": "PATROCÍNIO",
  "populacao": 118480,
  "populacaoAte3SM": 107502,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/patrocinio/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "PEÇANHA",
  "populacao": 54988,
  "populacaoAte3SM": 53205,
  "municipios": 8,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PEDRA AZUL",
  "populacao": 55331,
  "populacaoAte3SM": 53618,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PEDRALVA",
  "populacao": 15166,
  "populacaoAte3SM": 14268,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PEDRO LEOPOLDO",
  "populacao": 72586,
  "populacaoAte3SM": 64344,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/pedro-leopoldo/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "PERDIZES",
  "populacao": 21234,
  "populacaoAte3SM": 19079,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PERDÕES",
  "populacao": 27347,
  "populacaoAte3SM": 25537,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PIRANGA",
  "populacao": 38652,
  "populacaoAte3SM": 37831,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PIRAPETINGA",
  "populacao": 13612,
  "populacaoAte3SM": 12774,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/pirapetinga/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PIRAPORA",
  "populacao": 88071,
  "populacaoAte3SM": 82061,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/pirapora/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "PITANGUI",
  "populacao": 58296,
  "populacaoAte3SM": 54147,
  "municipios": 5,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/pitangui/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "PIUMHI",
  "populacao": 50101,
  "populacaoAte3SM": 45208,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "POÇO FUNDO",
  "populacao": 16791,
  "populacaoAte3SM": 15378,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "POÇOS DE CALDAS",
  "populacao": 171533,
  "populacaoAte3SM": 144926,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/pocos-de-caldas/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 7
 },
 {
  "nome": "POMPÉU",
  "populacao": 32305,
  "populacaoAte3SM": 30307,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PONTE NOVA",
  "populacao": 96183,
  "populacaoAte3SM": 89140,
  "municipios": 8,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/ponte-nova/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "PORTEIRINHA",
  "populacao": 62489,
  "populacaoAte3SM": 61124,
  "municipios": 5,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "POUSO ALEGRE",
  "populacao": 186127,
  "populacaoAte3SM": 161136,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/pouso-alegre/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 9
 },
 {
  "nome": "PRADOS",
  "populacao": 19640,
  "populacaoAte3SM": 18771,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PRATA",
  "populacao": 29578,
  "populacaoAte3SM": 26728,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PRATÁPOLIS",
  "populacao": 23206,
  "populacaoAte3SM": 20875,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "PRESIDENTE OLEGÁRIO",
  "populacao": 35059,
  "populacaoAte3SM": 32968,
  "municipios": 3,
  "atendida2025": "PARCIALMENTE",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "RAUL SOARES",
  "populacao": 28916,
  "populacaoAte3SM": 27588,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "RESENDE COSTA",
  "populacao": 15106,
  "populacaoAte3SM": 14199,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/resende-costa/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "RESPLENDOR",
  "populacao": 29803,
  "populacaoAte3SM": 28325,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "RIBEIRÃO DAS NEVES",
  "populacao": 344828,
  "populacaoAte3SM": 327160,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/ribeirao-das-neves/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 13
 },
 {
  "nome": "RIO CASCA",
  "populacao": 24457,
  "populacaoAte3SM": 23425,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "RIO NOVO",
  "populacao": 15733,
  "populacaoAte3SM": 14777,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "RIO PARANAÍBA",
  "populacao": 17817,
  "populacaoAte3SM": 16167,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "RIO PARDO DE MINAS",
  "populacao": 47572,
  "populacaoAte3SM": 46363,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "RIO PIRACICABA",
  "populacao": 15001,
  "populacaoAte3SM": 13872,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "RIO POMBA",
  "populacao": 24345,
  "populacaoAte3SM": 22628,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "RIO PRETO",
  "populacao": 13275,
  "populacaoAte3SM": 12548,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/rio-preto/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "RIO VERMELHO",
  "populacao": 12815,
  "populacaoAte3SM": 12556,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SABARÁ",
  "populacao": 134286,
  "populacaoAte3SM": 121575,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/sabara/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "SABINÓPOLIS",
  "populacao": 22793,
  "populacaoAte3SM": 21947,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SACRAMENTO",
  "populacao": 27891,
  "populacaoAte3SM": 25243,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/sacramento/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SALINAS",
  "populacao": 65479,
  "populacaoAte3SM": 62955,
  "municipios": 6,
  "atendida2025": "NÃO",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/salinas/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SANTA BÁRBARA",
  "populacao": 49777,
  "populacaoAte3SM": 46463,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SANTA LUZIA",
  "populacao": 229483,
  "populacaoAte3SM": 212926,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/santa-luzia/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SANTA MARIA DO SUAÇUÍ",
  "populacao": 31355,
  "populacaoAte3SM": 30439,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SANTA RITA DE CALDAS",
  "populacao": 17887,
  "populacaoAte3SM": 16610,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SANTA RITA DO SAPUCAÍ",
  "populacao": 49014,
  "populacaoAte3SM": 44142,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/santa-rita-do-sapucai/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "SANTA VITÓRIA",
  "populacao": 21745,
  "populacaoAte3SM": 19886,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SANTO ANTÔNIO DO MONTE",
  "populacao": 32590,
  "populacaoAte3SM": 29857,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/santo-antonio-do-monte/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SANTOS DUMONT",
  "populacao": 53024,
  "populacaoAte3SM": 48799,
  "municipios": 5,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/santos-dumont/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "SÃO DOMINGOS DO PRATA",
  "populacao": 30052,
  "populacaoAte3SM": 28453,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SÃO FRANCISCO",
  "populacao": 72382,
  "populacaoAte3SM": 70398,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/sao-francisco/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SÃO GONÇALO DO SAPUCAÍ",
  "populacao": 34756,
  "populacaoAte3SM": 32387,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SÃO GOTARDO",
  "populacao": 47216,
  "populacaoAte3SM": 42489,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SÃO JOÃO DA PONTE",
  "populacao": 57590,
  "populacaoAte3SM": 56407,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/sao-joao-da-ponte/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SÃO JOÃO DEL REI",
  "populacao": 152125,
  "populacaoAte3SM": 138342,
  "municipios": 8,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/sao-joao-del-rei/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 4
 },
 {
  "nome": "SÃO JOÃO DO PARAÍSO",
  "populacao": 35519,
  "populacaoAte3SM": 34915,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": null,
  "defensores2013": null
 },
 {
  "nome": "SÃO JOÃO EVANGELISTA",
  "populacao": 23868,
  "populacaoAte3SM": 23022,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SÃO JOÃO NEPOMUCENO",
  "populacao": 33899,
  "populacaoAte3SM": 31677,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/sao-joao-nepomuceno/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 },
 {
  "nome": "SÃO LOURENÇO",
  "populacao": 61514,
  "populacaoAte3SM": 54221,
  "municipios": 4,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/sao-lourenco/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "SÃO ROMÃO",
  "populacao": 14104,
  "populacaoAte3SM": 13790,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SÃO ROQUE DE MINAS",
  "populacao": 9547,
  "populacaoAte3SM": 8812,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SÃO SEBASTIÃO DO PARAÍSO",
  "populacao": 81595,
  "populacaoAte3SM": 72780,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/sao-sebastiao-do-paraiso/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "SENADOR FIRMINO",
  "populacao": 17418,
  "populacaoAte3SM": 16866,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SERRO",
  "populacao": 34680,
  "populacaoAte3SM": 33477,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "SETE LAGOAS",
  "populacao": 277031,
  "populacaoAte3SM": 246764,
  "municipios": 8,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/sete-lagoas/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 6
 },
 {
  "nome": "SILVIANÓPOLIS",
  "populacao": 21421,
  "populacaoAte3SM": 20051,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "TAIOBEIRAS",
  "populacao": 52678,
  "populacaoAte3SM": 50527,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "TARUMIRIM",
  "populacao": 41392,
  "populacaoAte3SM": 39966,
  "municipios": 5,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "TEIXEIRAS",
  "populacao": 16005,
  "populacaoAte3SM": 15180,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "TEÓFILO OTONI",
  "populacao": 209215,
  "populacaoAte3SM": 195879,
  "municipios": 7,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/teofilo-otoni/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 8
 },
 {
  "nome": "TIMÓTEO",
  "populacao": 92021,
  "populacaoAte3SM": 79150,
  "municipios": 3,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "TIROS",
  "populacao": 8172,
  "populacaoAte3SM": 7631,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "TOMBOS",
  "populacao": 11582,
  "populacaoAte3SM": 10772,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "TRÊS CORAÇÕES",
  "populacao": 90003,
  "populacaoAte3SM": 81183,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/tres-coracoes/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "TRÊS MARIAS",
  "populacao": 29927,
  "populacaoAte3SM": 27268,
  "municipios": 1,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "TRÊS PONTAS",
  "populacao": 63867,
  "populacaoAte3SM": 58546,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/tres-pontas/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 2
 },
 {
  "nome": "TUPACIGUARA",
  "populacao": 35417,
  "populacaoAte3SM": 32131,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "TURMALINA",
  "populacao": 34287,
  "populacaoAte3SM": 32986,
  "municipios": 4,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "UBÁ",
  "populacao": 144570,
  "populacaoAte3SM": 132118,
  "municipios": 5,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/uba/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "UBERABA",
  "populacao": 379628,
  "populacaoAte3SM": 320419,
  "municipios": 5,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/uberaba/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 16
 },
 {
  "nome": "UBERLÂNDIA",
  "populacao": 754954,
  "populacaoAte3SM": 624921,
  "municipios": 1,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/uberlandia/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 21
 },
 {
  "nome": "UNAÍ",
  "populacao": 97521,
  "populacaoAte3SM": 87617,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/unai/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "VARGINHA",
  "populacao": 163128,
  "populacaoAte3SM": 141174,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/varginha/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 7
 },
 {
  "nome": "VÁRZEA DA PALMA",
  "populacao": 41997,
  "populacaoAte3SM": 40360,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "VAZANTE",
  "populacao": 27117,
  "populacaoAte3SM": 24649,
  "municipios": 2,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "VESPASIANO",
  "populacao": 164536,
  "populacaoAte3SM": 152816,
  "municipios": 2,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/vespasiano/",
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "VIÇOSA",
  "populacao": 110740,
  "populacaoAte3SM": 97385,
  "municipios": 6,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/vicosa/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 3
 },
 {
  "nome": "VIRGINÓPOLIS",
  "populacao": 31628,
  "populacaoAte3SM": 30595,
  "municipios": 5,
  "atendida2025": "NÃO",
  "temUnidadeHoje": false,
  "link": null,
  "atendida2013": "Comarca sem Defensoria Pública",
  "defensores2013": 0
 },
 {
  "nome": "VISCONDE DO RIO BRANCO",
  "populacao": 58975,
  "populacaoAte3SM": 54909,
  "municipios": 3,
  "atendida2025": "SIM",
  "temUnidadeHoje": true,
  "link": "https://defensoria.mg.def.br/unidade/visconde-do-rio-branco/",
  "atendida2013": "Comarca com Defensoria Pública",
  "defensores2013": 1
 }
];
