/**
 * apps/web/lib/eixos/catalogo.ts
 *
 * Catálogo canônico dos 3 Eixos Temáticos e suas 18 subfrentes.
 * Inclui mapeamento de rotas legadas para compatibilidade guarda-chuva.
 */

import type { Eixo, EixoId, Subfrente, SubfrenteId } from './types';

export const CATALOGO_EIXOS: Record<EixoId, Eixo> = {
  direitos: {
    id: 'direitos',
    titulo: 'Direitos em Movimento',
    subtitulo: 'Garantias fundamentais, serviços essenciais e justiça social',
    descricao:
      'Monitoramento de saúde pública, educação, renda, segurança alimentar, moradia e canais populares de denúncia e acesso à justiça.',
    corVar: '--cp-eixo-direitos',
    corInkVar: '--cp-eixo-direitos-ink',
    subfrentes: [
      {
        id: 'trabalho-e-renda',
        eixoId: 'direitos',
        titulo: 'Trabalho e Renda',
        descricao: 'Emprego formal, admissões CAGED, estoques RAIS e impacto de contratos públicos na economia local.',
        slug: 'trabalho-e-renda',
        icone: 'Briefcase',
        tagsRelacionadas: ['trabalho', 'renda', 'caged', 'rais', 'salario', 'emprego'],
      },
      {
        id: 'saude-publica',
        eixoId: 'direitos',
        titulo: 'Saúde Pública',
        descricao: 'Capacidade instalada do SUS, estabelecimentos CNES, razão habitante/leito e internações SIH.',
        slug: 'saude-publica',
        icone: 'HeartPulse',
        tagsRelacionadas: ['saude', 'sus', 'cnes', 'leitos', 'hospitais', 'atendimento'],
      },
      {
        id: 'educacao',
        eixoId: 'direitos',
        titulo: 'Educação',
        descricao: 'Infraestrutura escolar, matrículas do Censo Escolar e indicadores de qualidade IDEB por município.',
        slug: 'educacao',
        icone: 'GraduationCap',
        tagsRelacionadas: ['educacao', 'escolas', 'ideb', 'inep', 'ensino', 'matriculas'],
      },
      {
        id: 'seguranca-alimentar',
        eixoId: 'direitos',
        titulo: 'Segurança Alimentar',
        descricao: 'Programas de transferência, vulnerabilidade nutricional e agricultura familiar.',
        slug: 'seguranca-alimentar',
        icone: 'Apple',
        tagsRelacionadas: ['alimentacao', 'bolsa-familia', 'vulnerabilidade', 'nutricao'],
        rotaLegada: '/direitos-em-movimento',
      },
      {
        id: 'moradia',
        eixoId: 'direitos',
        titulo: 'Moradia e Habitação',
        descricao: 'Déficit habitacional, regularização fundiária urbana e prevenção a remoções forçadas.',
        slug: 'moradia',
        icone: 'Home',
        tagsRelacionadas: ['moradia', 'habitacao', 'remocoes', 'regularizacao'],
        rotaLegada: '/direitos-em-movimento/ajuda',
      },
      {
        id: 'acesso-a-justica',
        eixoId: 'direitos',
        titulo: 'Acesso à Justiça e Denúncias',
        descricao: 'Defensoria Pública, canais de denúncia popular e assistência jurídica comunitária.',
        slug: 'acesso-a-justica',
        icone: 'Scale',
        tagsRelacionadas: ['justica', 'defensoria', 'denuncia', 'direitos-humanos'],
        rotaLegada: '/direitos-em-movimento',
      },
    ],
  },
  terra: {
    id: 'terra',
    titulo: 'Terra e Territórios',
    subtitulo: 'Soberania socioambiental, cidades e defesa dos biomas',
    descricao:
      'Fiscalização de 199 cidades estratégicas, bacias hidrográficas, licenciamento ambiental, terras indígenas e unidades de conservação.',
    corVar: '--cp-eixo-terra',
    corInkVar: '--cp-eixo-terra-ink',
    subfrentes: [
      {
        id: 'cidades',
        eixoId: 'terra',
        titulo: '199 Cidades Estratégicas',
        descricao: 'Rede de fiscalização municipal em 27 capitais e 172 polos regionais do interior do Brasil.',
        slug: 'cidades',
        icone: 'Building2',
        tagsRelacionadas: ['cidades', 'municipios', 'interior', 'capitais', 'ibge'],
        rotaLegada: '/cidades',
      },
      {
        id: 'meio-ambiente',
        eixoId: 'terra',
        titulo: 'Meio Ambiente (ONSA)',
        descricao: 'Observatório Nacional Socioambiental: licenciamento, pauta do COPAM, TACs e barragens SIGBM.',
        slug: 'meio-ambiente',
        icone: 'Trees',
        tagsRelacionadas: ['meio-ambiente', 'onsa', 'copam', 'licenciamento', 'ibama', 'barragens'],
        rotaLegada: '/ambiental',
      },
      {
        id: 'terras-indigenas-quilombolas',
        eixoId: 'terra',
        titulo: 'Terras Indígenas e Quilombolas',
        descricao: 'Monitoramento de demarcações, sobreposições de mineração e defesa de povos originários.',
        slug: 'terras-indigenas-quilombolas',
        icone: 'Shield',
        tagsRelacionadas: ['indigenas', 'quilombolas', 'demarcacao', 'funai', 'incra'],
        rotaLegada: '/funcaosocialterra',
      },
      {
        id: 'nossas-serras',
        eixoId: 'terra',
        titulo: 'Nossas Serras',
        descricao: 'Preservação de topos de morro, patrimônio geológico e contenção da expansão minerária predatória.',
        slug: 'nossas-serras',
        icone: 'Mountain',
        tagsRelacionadas: ['serras', 'mineracao', 'relevo', 'geologia'],
      },
      {
        id: 'nossos-rios',
        eixoId: 'terra',
        titulo: 'Nossos Rios e Bacias',
        descricao: 'Qualidade das águas, monitoramento de desastres (Rio Doce, Paraopeba) e saneamento básico.',
        slug: 'nossos-rios',
        icone: 'Waves',
        tagsRelacionadas: ['rios', 'bacias', 'paraopeba', 'mariana', 'saneamento', 'agua'],
        rotaLegada: '/paraopeba',
      },
      {
        id: 'vales',
        eixoId: 'terra',
        titulo: 'Vales do Jequitinhonha e do Mucuri',
        descricao: '82 municípios: lítio do Médio Jequitinhonha, comunidades tradicionais e o povo Maxakali.',
        slug: 'vales',
        icone: 'MapPin',
        tagsRelacionadas: ['jequitinhonha', 'mucuri', 'litio', 'comunidades-tradicionais', 'maxakali'],
      },
      {
        id: 'biomas',
        eixoId: 'terra',
        titulo: 'Biomas e Biodiversidade',
        descricao: 'Cerrado, Mata Atlântica, Caatinga e Amazônia: índices de risco climático e áreas de preservação.',
        slug: 'biomas',
        icone: 'Compass',
        tagsRelacionadas: ['biomas', 'cerrado', 'mata-atlantica', 'clima', 'adaptabrasil'],
        rotaLegada: '/ambiental/clima-risco',
      },
    ],
  },
  estado: {
    id: 'estado',
    titulo: 'Estado e Economia',
    subtitulo: 'Transparência institucional, orçamento público e poder econômico',
    descricao:
      'Vigilância de contratos municipais e federais, compras públicas, composição do Judiciário e votações no Congresso.',
    corVar: '--cp-eixo-estado',
    corInkVar: '--cp-eixo-estado-ink',
    subfrentes: [
      {
        id: 'judiciario',
        eixoId: 'estado',
        titulo: 'Judiciário e Justiça',
        descricao: 'Composição de tribunais, vagas, remunerações, inspeções do CNJ e processos ambientais SIRENEJud.',
        slug: 'judiciario',
        icone: 'Gavel',
        tagsRelacionadas: ['judiciario', 'tribunais', 'cnj', 'sirenejud', 'magistrados'],
        rotaLegada: '/judiciario',
      },
      {
        id: 'congresso',
        eixoId: 'estado',
        titulo: 'Congresso e Legislação',
        descricao: 'Proposições legislativas, votações nominais, comissões temáticas e bancadas estaduais.',
        slug: 'congresso',
        icone: 'Landmark',
        tagsRelacionadas: ['congresso', 'assembleias', 'camara', 'senado', 'deputados', 'leis', 'votacoes'],
        rotaLegada: '/congresso',
      },
      {
        id: 'executivo',
        eixoId: 'estado',
        titulo: 'Executivo e Políticas',
        descricao: 'Atos oficiais, diários municipais, nomeações e execução direta de programas de governo.',
        slug: 'executivo',
        icone: 'ScrollText',
        tagsRelacionadas: ['executivo', 'prefeitura', 'diario-oficial', 'decretos'],
        rotaLegada: '/governo',
      },
      {
        id: 'empresas',
        eixoId: 'estado',
        titulo: 'Empresas e Mercado',
        descricao: 'Relação de sócios, grandes conglomerados, concentração de fornecedores e observatório de mineradoras.',
        slug: 'empresas',
        icone: 'Building',
        tagsRelacionadas: ['empresas', 'fornecedores', 'contratos', 'socios', 'vale'],
        rotaLegada: '/empresas',
      },
      {
        id: 'orcamento',
        eixoId: 'estado',
        titulo: 'Orçamento Público',
        descricao: 'Dotação vs. execução financeira, transferências constitucionais e indicadores macroeconômicos BCB.',
        slug: 'orcamento',
        icone: 'Coins',
        tagsRelacionadas: ['orcamento', 'financas', 'gastos', 'receitas', 'bcb', 'ipca'],
      },
      {
        id: 'transparencia',
        eixoId: 'estado',
        titulo: 'Transparência e Controle Social',
        descricao: 'Pedidos de Lei de Acesso à Informação (LAI), alertas de auditoria do TCU e fiscalização cidadã.',
        slug: 'transparencia',
        icone: 'Eye',
        tagsRelacionadas: ['transparencia', 'lai', 'tcu', 'controle-social', 'auditoria'],
        rotaLegada: '/dados/comunicabr',
      },
    ],
  },
  central: {
    id: 'central',
    titulo: 'Central e Ferramentas',
    subtitulo: 'Inteligência cívica, acervo transversal e método ONSA',
    descricao:
      'Hub central de ferramentas públicas: busca universal no acervo, comparador de dados, radar de editais, biblioteca digital, relatórios e tecnologia livre.',
    corVar: '--cp-primary',
    corInkVar: '--cp-primary-ink',
    subfrentes: [
      {
        id: 'busca',
        eixoId: 'central',
        titulo: 'Busca Global',
        descricao: 'Motor de busca em tempo real com tolerância a acentos em todo o acervo do portal.',
        slug: 'busca',
        icone: 'Search',
        tagsRelacionadas: ['busca', 'pesquisa', 'indice', 'acervo'],
        rotaLegada: '/busca',
      },
      {
        id: 'laboratorio',
        eixoId: 'central',
        titulo: 'Laboratório de Dados',
        descricao: 'Cruzamento lado a lado de bases públicas com gráficos interativos e inteligência do Seu Nonô.',
        slug: 'laboratorio',
        icone: 'BarChart3',
        tagsRelacionadas: ['laboratorio', 'graficos', 'comparador', 'cruzamento'],
        rotaLegada: '/laboratorio',
      },
      {
        id: 'editais',
        eixoId: 'central',
        titulo: 'Radar de Editais DO-MG',
        descricao: 'Monitoramento diário de chamamentos públicos, licitações de impacto social e termos de fomento.',
        slug: 'editais',
        icone: 'FileSpreadsheet',
        tagsRelacionadas: ['editais', 'diario-oficial', 'licitacoes', 'fomento'],
        rotaLegada: '/editais',
      },
      {
        id: 'biblioteca',
        eixoId: 'central',
        titulo: 'Biblioteca Digital',
        descricao: 'Mais de 24 mil documentos públicos, relatórios de ATIs, perícias e decisões judiciais catalogadas.',
        slug: 'biblioteca',
        icone: 'BookOpen',
        tagsRelacionadas: ['biblioteca', 'documentos', 'relatorios', 'decisoes'],
        rotaLegada: '/biblioteca',
      },
      {
        id: 'noticias',
        eixoId: 'central',
        titulo: 'Blog e Notícias Analíticas',
        descricao: 'Estudos técnicos, investigações cívicas e artigos aprofundados com link direto à fonte oficial.',
        slug: 'noticias',
        icone: 'Newspaper',
        tagsRelacionadas: ['blog', 'noticias', 'estudos', 'artigos'],
        rotaLegada: '/noticias',
      },
      {
        id: 'tecnologia',
        eixoId: 'central',
        titulo: 'Tecnologia & IA Livre',
        descricao: 'Ferramentas de código aberto, modelos locais soberanos e metodologias para auditoria cidadã.',
        slug: 'tecnologia',
        icone: 'Cpu',
        tagsRelacionadas: ['tecnologia', 'ia', 'inteligencia-artificial', 'codigo-aberto'],
        rotaLegada: '/tecnologia',
      },
      {
        id: 'documentacao',
        eixoId: 'central',
        titulo: 'Documentação do Sistema',
        descricao: 'Arquitetura técnica, schemas do banco de dados, governança e manuais de integração de dados.',
        slug: 'documentacao',
        icone: 'FileText',
        tagsRelacionadas: ['documentacao', 'arquitetura', 'api', 'schemas'],
        rotaLegada: '/documentacao',
      },
      {
        id: 'alertas',
        eixoId: 'central',
        titulo: 'Alertas e Notificações',
        descricao: 'Canal de avisos em tempo real sobre barragens, desastres climáticos e decisões emergenciais.',
        slug: 'alertas',
        icone: 'Bell',
        tagsRelacionadas: ['alertas', 'emergencias', 'notificacoes', 'clima'],
        rotaLegada: '/alertas',
      },
      {
        id: 'estudos-rurais',
        eixoId: 'central',
        titulo: 'Estudos Rurais e Territoriais',
        descricao: 'Cartografia social, reforma agrária, soberania alimentar e produção camponesa.',
        slug: 'estudos-rurais',
        icone: 'Map',
        tagsRelacionadas: ['campo', 'reforma-agraria', 'camponeses', 'territorio'],
        rotaLegada: '/estudos-rurais',
      },
      {
        id: 'imprensa',
        eixoId: 'central',
        titulo: 'Sala de Imprensa & Dados',
        descricao: 'Releases, resumos para comunicadores populares, dados abertos e contato de porta-vozes.',
        slug: 'imprensa',
        icone: 'Building2',
        tagsRelacionadas: ['imprensa', 'jornalismo', 'releases', 'comunicacao'],
        rotaLegada: '/imprensa',
      },
      {
        id: 'sobre',
        eixoId: 'central',
        titulo: 'Sobre o ONSA e Método',
        descricao: 'Princípios da auditoria cívica popular, regra das seis qualidades e compromisso social.',
        slug: 'sobre',
        icone: 'Info',
        tagsRelacionadas: ['sobre', 'metodo', 'auditoria', 'principios'],
        rotaLegada: '/sobre',
      },
      {
        id: 'termos',
        eixoId: 'central',
        titulo: 'Termos de Uso e LGPD',
        descricao: 'Políticas de privacidade, anonimização de dados pessoais e conformidade jurídica.',
        slug: 'termos',
        icone: 'ShieldCheck',
        tagsRelacionadas: ['termos', 'privacidade', 'lgpd', 'licenca'],
        rotaLegada: '/termos',
      },
    ],
  },
};

export function obterEixo(id: EixoId): Eixo {
  return CATALOGO_EIXOS[id];
}

export function listarTodosEixos(): Eixo[] {
  return Object.values(CATALOGO_EIXOS);
}

export function buscarSubfrente(id: SubfrenteId): Subfrente | undefined {
  for (const eixo of Object.values(CATALOGO_EIXOS)) {
    const encontrada = eixo.subfrentes.find((s) => s.id === id);
    if (encontrada) return encontrada;
  }
  return undefined;
}
