/**
 * @file scripts/etl/america-latina/gerar-acervo-america-latina.mts
 * @description ETL gerador do acervo de mineradoras e geolocalização de sedes/instalações na América Latina.
 *
 * Papel no portal:
 * 1. Mapeia corporações de mineração, sedes corporativas, minas de grande porte, refinarias e portos
 *    na América Latina (Brasil, Chile, Peru, Argentina, México, Colômbia, Bolívia, Equador e Panamá).
 * 2. Gera o arquivo GeoJSON para o Globo 3D:
 *    `apps/web/public/terras/globo/dados/camadas/sedes-instalacoes-mineradoras-latam.geojson`.
 * 3. Compacta os dados com `compactar.ts` para consumo leve em Server Components em:
 *    `apps/web/data/america-latina/mineradoras-latam.compact.json`.
 *
 * Fontes oficiais consultadas:
 * - Brasil: ANM (SIGBM), CPRM, IBRAM.
 * - Chile: SERNAGEOMIN, Cochilco, CMF.
 * - Peru: INGEMMET, MINEM, OEFA.
 * - Argentina: Secretaría de Minería de la Nación, SEGEMAR.
 * - México: Secretaría de Economía (DGM), SEMARNAT.
 * - Colômbia: ANM Colombia, ANLA.
 * - Bolívia: SERGEOMIN, YLB, COMIBOL.
 * - Equador: Ministerio de Energía y Minas, ARCOM.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compactar } from "../../../apps/web/lib/estatico/compactar.js";

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const GEOJSON_DESTINO = path.join(
  RAIZ,
  "apps",
  "web",
  "public",
  "terras",
  "globo",
  "dados",
  "camadas",
  "sedes-instalacoes-mineradoras-latam.geojson"
);
const DATA_DIR = path.join(RAIZ, "apps", "web", "data", "america-latina");

export interface InstalacaoLatam {
  id: string;
  nome: string;
  empresa: string;
  pais: string;
  tipo: "sede_corporativa" | "mina_operacao" | "complexo_beneficiamento" | "porto_minerario" | "projeto_litio";
  mineralPrincipal: string;
  status: string;
  latitude: number;
  longitude: number;
  baciaOuRegiao: string;
  fonteOficial: string;
  descricao: string;
}

export const INSTALACOES_LATAM: InstalacaoLatam[] = [
  // --- BRASIL ---
  {
    id: "br-vale-sede",
    nome: "Sede Corporativa Global - Vale S.A.",
    empresa: "Vale S.A.",
    pais: "Brasil",
    tipo: "sede_corporativa",
    mineralPrincipal: "Ferro / Cobre / Níquel",
    status: "Sede Corporativa",
    latitude: -22.9068,
    longitude: -43.1729,
    baciaOuRegiao: "Baía de Guanabara / Rio de Janeiro",
    fonteOficial: "CVM / Relatório Anual 20-F",
    descricao: "Sede administrativa da maior produtora de minério de ferro das Américas.",
  },
  {
    id: "br-vale-carajas",
    nome: "Complexo Minerário de Carajás (S11D / Serra Norte)",
    empresa: "Vale S.A.",
    pais: "Brasil",
    tipo: "mina_operacao",
    mineralPrincipal: "Minério de Ferro",
    status: "Operação ativa",
    latitude: -6.0614,
    longitude: -50.1833,
    baciaOuRegiao: "Bacia do Rio Itacaiúnas / Rio Tocantins",
    fonteOficial: "ANM / Cadastro Nacional de Barragens",
    descricao: "Maior mina de minério de ferro a céu aberto do planeta, com teor médio acima de 65% Fe.",
  },
  {
    id: "br-vale-brucutu",
    nome: "Mina de Brucutu",
    empresa: "Vale S.A.",
    pais: "Brasil",
    tipo: "mina_operacao",
    mineralPrincipal: "Minério de Ferro",
    status: "Operação ativa",
    latitude: -19.8656,
    longitude: -43.4111,
    baciaOuRegiao: "Bacia do Rio Doce / São Gonçalo do Rio Abaixo",
    fonteOficial: "ANM / FEAM MG",
    descricao: "Uma das maiores minas do Quadrilátero Ferrífero de Minas Gerais, pioneira em caminhões autônomos.",
  },
  {
    id: "br-anglo-minasrio",
    nome: "Complexo Minas-Rio",
    empresa: "Anglo American",
    pais: "Brasil",
    tipo: "mina_operacao",
    mineralPrincipal: "Minério de Ferro",
    status: "Operação ativa",
    latitude: -19.0347,
    longitude: -43.4258,
    baciaOuRegiao: "Bacia do Rio Santo Antônio / Rio Doce",
    fonteOficial: "SEMAD MG / ANM",
    descricao: "Mina a céu aberto interligada ao maior mineroduto do mundo (529 km até o Porto do Açu/RJ).",
  },
  {
    id: "br-sigma-grota-cirilo",
    nome: "Projeto Grota do Cirilo - Lítio Verde",
    empresa: "Sigma Lithium",
    pais: "Brasil",
    tipo: "projeto_litio",
    mineralPrincipal: "Lítio (Espodumênio)",
    status: "Operação ativa",
    latitude: -16.6022,
    longitude: -41.8319,
    baciaOuRegiao: "Bacia do Rio Jequitinhonha / Itinga e Araçuaí",
    fonteOficial: "ANM / SEMAD MG (LOC)",
    descricao: "Principal complexo de extração de lítio em rocha pegmatítica do Vale do Jequitinhonha.",
  },
  {
    id: "br-kinross-paracatu",
    nome: "Mina Morro do Ouro",
    empresa: "Kinross Gold Corporation",
    pais: "Brasil",
    tipo: "mina_operacao",
    mineralPrincipal: "Ouro",
    status: "Operação ativa",
    latitude: -17.2217,
    longitude: -46.8856,
    baciaOuRegiao: "Bacia do Rio Paracatu / Rio São Francisco",
    fonteOficial: "ANM / CVRM",
    descricao: "Maior mina de ouro a céu aberto do Brasil, com duas grandes barragens de rejeitos (Eustáquio e Santo Antônio).",
  },
  {
    id: "br-cbmm-araxa",
    nome: "Complexo Industrial e Minerário de Araxá",
    empresa: "CBMM",
    pais: "Brasil",
    tipo: "complexo_beneficiamento",
    mineralPrincipal: "Nióbio (Ferronióbio)",
    status: "Operação ativa",
    latitude: -19.6419,
    longitude: -46.9458,
    baciaOuRegiao: "Bacia do Rio Grande / Triângulo Mineiro",
    fonteOficial: "ANM / CPRM",
    descricao: "Responsável por mais de 75% da produção global de nióbio e ligas de alta tecnologia.",
  },
  {
    id: "br-vale-salobo",
    nome: "Mina de Cobre Salobo",
    empresa: "Vale Base Metals",
    pais: "Brasil",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Ouro",
    status: "Operação ativa",
    latitude: -5.7944,
    longitude: -50.5372,
    baciaOuRegiao: "Floresta Nacional de Tapirapé-Aquiri / Pará",
    fonteOficial: "ANM / ICMBio",
    descricao: "Maior reserva de cobre comprovada do Brasil, operada com usina de concentração associada.",
  },
  {
    id: "br-samarco-germano",
    nome: "Complexo de Germano",
    empresa: "Samarco (Vale / BHP)",
    pais: "Brasil",
    tipo: "mina_operacao",
    mineralPrincipal: "Minério de Ferro",
    status: "Operação retomada com filtragem",
    latitude: -20.2319,
    longitude: -43.4658,
    baciaOuRegiao: "Bacia do Rio Doce / Mariana",
    fonteOficial: "ANM / FEAM",
    descricao: "Local do rompimento da barragem de Fundão em 2015; operação retomada sem uso de barragem a montante.",
  },
  {
    id: "br-csn-casadepedra",
    nome: "Mina Casa de Pedra",
    empresa: "CSN Mineração",
    pais: "Brasil",
    tipo: "mina_operacao",
    mineralPrincipal: "Minério de Ferro",
    status: "Operação ativa",
    latitude: -20.5056,
    longitude: -43.8617,
    baciaOuRegiao: "Bacia do Rio Paraopeba / Congonhas",
    fonteOficial: "ANM / CVM",
    descricao: "Uma das mais antigas e produtivas minas de ferro do país, adjacente à malha urbana de Congonhas.",
  },
  {
    id: "br-porto-tubarao",
    nome: "Porto de Tubarão",
    empresa: "Vale S.A.",
    pais: "Brasil",
    tipo: "porto_minerario",
    mineralPrincipal: "Terminal Graneleiro de Ferro",
    status: "Operação ativa",
    latitude: -20.2917,
    longitude: -40.2444,
    baciaOuRegiao: "Oceano Atlântico / Vitória (ES)",
    fonteOficial: "Antaq / Vale",
    descricao: "Maior porto exportador de minério de ferro e pelotas do Atlântico Sul.",
  },
  {
    id: "br-porto-ponta-madeira",
    nome: "Terminal Marítimo de Ponta da Madeira",
    empresa: "Vale S.A.",
    pais: "Brasil",
    tipo: "porto_minerario",
    mineralPrincipal: "Terminal Graneleiro de Ferro",
    status: "Operação ativa",
    latitude: -2.5714,
    longitude: -44.3708,
    baciaOuRegiao: "Baía de São Marcos / São Luís (MA)",
    fonteOficial: "Antaq / Marinha do Brasil",
    descricao: "Capaz de atracar os maiores navios mineraleiros do mundo (Valemax com 400.000 DWT).",
  },

  // --- CHILE ---
  {
    id: "cl-codelco-sede",
    nome: "Sede Corporativa Central - Codelco",
    empresa: "Codelco (Corporación Nacional del Cobre)",
    pais: "Chile",
    tipo: "sede_corporativa",
    mineralPrincipal: "Cobre",
    status: "Sede Estatal",
    latitude: -33.4429,
    longitude: -70.6539,
    baciaOuRegiao: "Región Metropolitana de Santiago",
    fonteOficial: "Cochilco / CMF Chile",
    descricao: "Maior empresa estatal produtora de cobre do mundo, controladora das principais divisões chilenas.",
  },
  {
    id: "cl-bhp-escondida",
    nome: "Mina Escondida",
    empresa: "Minera Escondida (BHP 57.5% / Rio Tinto 30% / JECO)",
    pais: "Chile",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Ouro / Prata",
    status: "Operação ativa",
    latitude: -24.2711,
    longitude: -69.0719,
    baciaOuRegiao: "Deserto de Atacama / Región de Antofagasta",
    fonteOficial: "SERNAGEOMIN Chile",
    descricao: "Maior produtora individual de cobre do planeta, responsável por cerca de 5% de todo o cobre mundial.",
  },
  {
    id: "cl-codelco-chuquicamata",
    nome: "División Chuquicamata",
    empresa: "Codelco",
    pais: "Chile",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Molibdênio",
    status: "Operação subterrânea",
    latitude: -22.3167,
    longitude: -68.9000,
    baciaOuRegiao: "Cuenca del Río Loa / Calama",
    fonteOficial: "SERNAGEOMIN / Codelco",
    descricao: "Histórica e monumental mina a céu aberto, convertida para operação subterrânea de alta tecnologia.",
  },
  {
    id: "cl-codelco-el-teniente",
    nome: "División El Teniente",
    empresa: "Codelco",
    pais: "Chile",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Molibdênio",
    status: "Operação ativa",
    latitude: -34.0956,
    longitude: -70.3589,
    baciaOuRegiao: "Cordillera de los Andes / Región de O'Higgins",
    fonteOficial: "SERNAGEOMIN Chile",
    descricao: "A maior mina subterrânea de cobre do mundo, com mais de 3.000 km de galerias subterrâneas.",
  },
  {
    id: "cl-collahuasi",
    nome: "Compañía Minera Doña Inés de Collahuasi",
    empresa: "Anglo American (44%) / Glencore (44%) / JCR (12%)",
    pais: "Chile",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Molibdênio",
    status: "Operação ativa",
    latitude: -20.9753,
    longitude: -68.6836,
    baciaOuRegiao: "Altiplano Andino / Región de Tarapacá",
    fonteOficial: "SERNAGEOMIN / SMA Chile",
    descricao: "Mina a 4.400 metros de altitude, entre as três maiores operações de cobre do Chile.",
  },
  {
    id: "cl-sqm-salardeatacama",
    nome: "Complexo Salar de Atacama - SQM",
    empresa: "SQM (Sociedad Química y Minera de Chile)",
    pais: "Chile",
    tipo: "projeto_litio",
    mineralPrincipal: "Lítio (Carbonato e Hidróxido) / Potássio",
    status: "Operação ativa",
    latitude: -23.5000,
    longitude: -68.2500,
    baciaOuRegiao: "Salar de Atacama / Antofagasta",
    fonteOficial: "CORFO / SMA Chile",
    descricao: "Maior reserva de salmoura de lítio em produção do mundo, no coração do 'Triângulo do Lítio'.",
  },
  {
    id: "cl-albemarle-salardeatacama",
    nome: "Planta Salar de Atacama - Albemarle",
    empresa: "Albemarle Corporation",
    pais: "Chile",
    tipo: "projeto_litio",
    mineralPrincipal: "Lítio",
    status: "Operação ativa",
    latitude: -23.6028,
    longitude: -68.3278,
    baciaOuRegiao: "Salar de Atacama / Antofagasta",
    fonteOficial: "SERNAGEOMIN / CORFO",
    descricao: "Segunda grande operadora de extração por evaporação solar de salmoura de lítio no Atacama.",
  },
  {
    id: "cl-pelambres-antofagasta",
    nome: "Minera Los Pelambres",
    empresa: "Antofagasta Minerals (Grupo Luksic)",
    pais: "Chile",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Ouro / Molibdênio",
    status: "Operação ativa",
    latitude: -31.7219,
    longitude: -70.5019,
    baciaOuRegiao: "Valle del Choapa / Región de Coquimbo",
    fonteOficial: "SERNAGEOMIN / Antofagasta plc",
    descricao: "Principal operação da Antofagasta plc, com usina dessalinizadora própria na costa.",
  },
  {
    id: "cl-porto-mejillones",
    nome: "Terminal Portuario de Mejillones",
    empresa: "Puerto Mejillones",
    pais: "Chile",
    tipo: "porto_minerario",
    mineralPrincipal: "Cobre / Ácido Sulfúrico",
    status: "Operação ativa",
    latitude: -23.1042,
    longitude: -70.4503,
    baciaOuRegiao: "Bahía de Mejillones / Antofagasta",
    fonteOficial: "Directemar / Ministerio de Transportes Chile",
    descricao: "Porto especializado no embarque de concentrado de cobre e recepção de insumos para mineração.",
  },

  // --- PERU ---
  {
    id: "pe-southern-sede",
    nome: "Sede Operacional Peru - Southern Copper",
    empresa: "Southern Copper Corporation (Grupo México)",
    pais: "Peru",
    tipo: "sede_corporativa",
    mineralPrincipal: "Cobre / Prata",
    status: "Sede Regional",
    latitude: -12.0569,
    longitude: -77.0375,
    baciaOuRegiao: "Lima Metropolitana",
    fonteOficial: "SMV Peru / SEC Form 10-K",
    descricao: "Escritório central de coordenação das minas de Toquepala e Cuajone e fundição de Ilo.",
  },
  {
    id: "pe-antamina",
    nome: "Compañía Minera Antamina",
    empresa: "BHP (33.75%) / Glencore (33.75%) / Teck (22.5%) / Mitsubishi (10%)",
    pais: "Peru",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Zinco / Prata / Molibdênio",
    status: "Operação ativa",
    latitude: -9.5356,
    longitude: -77.0519,
    baciaOuRegiao: "Cordillera Blanca / Región Áncash",
    fonteOficial: "INGEMMET / MINEM Peru",
    descricao: "Um dos maiores complexos polimetálicos do planeta a 4.300m de altitude, com mineroduto até Huarmey.",
  },
  {
    id: "pe-cerro-verde",
    nome: "Sociedad Minera Cerro Verde",
    empresa: "Freeport-McMoRan (53.56%) / SMM Cerro Verde (21%) / Buenaventura (19.58%)",
    pais: "Peru",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Molibdênio",
    status: "Operação ativa",
    latitude: -16.5369,
    longitude: -71.5931,
    baciaOuRegiao: "Cuenca del Río Chili / Arequipa",
    fonteOficial: "INGEMMET / OEFA Peru",
    descricao: "Complexo produtor de cobre a céu aberto nos arredores de Arequipa, com usinas concentradoras gigantes.",
  },
  {
    id: "pe-las-bambas",
    nome: "Minera Las Bambas",
    empresa: "MMG Limited (62.5%) / Guoxin (22.5%) / CITIC (15%)",
    pais: "Peru",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Molibdênio / Ouro",
    status: "Operação ativa",
    latitude: -14.1028,
    longitude: -72.3278,
    baciaOuRegiao: "Cuenca del Río Vilcabamba / Apurímac",
    fonteOficial: "MINEM / OEFA Peru",
    descricao: "Uma das maiores minas de cobre do mundo, com histórico de conflitos no corredor logístico viário.",
  },
  {
    id: "pe-quellaveco",
    nome: "Proyecto Quellaveco",
    empresa: "Anglo American (60%) / Mitsubishi (40%)",
    pais: "Peru",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre",
    status: "Operação ativa",
    latitude: -17.1128,
    longitude: -70.6139,
    baciaOuRegiao: "Cuenca del Río Asana / Moquegua",
    fonteOficial: "INGEMMET / MINEM",
    descricao: "Primeira mina 100% digital do Peru, operada com caminhões e perfuratrizes totalmente autônomas.",
  },
  {
    id: "pe-toquepala",
    nome: "Mina Toquepala",
    empresa: "Southern Copper Corporation",
    pais: "Peru",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Prata / Molibdênio",
    status: "Operação ativa",
    latitude: -17.2519,
    longitude: -70.6358,
    baciaOuRegiao: "Región Tacna",
    fonteOficial: "INGEMMET Peru",
    descricao: "Mina a céu aberto em operação contínua desde a década de 1960 no sul peruano.",
  },
  {
    id: "pe-yanacocha",
    nome: "Minera Yanacocha",
    empresa: "Newmont Corporation",
    pais: "Peru",
    tipo: "mina_operacao",
    mineralPrincipal: "Ouro / Cobre",
    status: "Operação ativa",
    latitude: -6.9856,
    longitude: -78.5028,
    baciaOuRegiao: "Cabecera de Cuenca / Cajamarca",
    fonteOficial: "INGEMMET / MINEM",
    descricao: "A maior mina de ouro da América do Sul, operada por lixiviação em pilhas.",
  },
  {
    id: "pe-porto-matarani",
    nome: "Terminal Portuario de Matarani",
    empresa: "Tisur (Grupo Romero)",
    pais: "Peru",
    tipo: "porto_minerario",
    mineralPrincipal: "Concentrado de Cobre",
    status: "Operação ativa",
    latitude: -17.0019,
    longitude: -72.1039,
    baciaOuRegiao: "Océano Pacífico / Arequipa",
    fonteOficial: "Autoridad Portuaria Nacional (APN Peru)",
    descricao: "Porto estratégico que embarca o minério de Cerro Verde, Las Bambas, Antapaccay e Southern.",
  },

  // --- ARGENTINA ---
  {
    id: "ar-sede-buenosaires",
    nome: "Pólo Institucional de Mineração da Argentina",
    empresa: "Secretaría de Minería de la Nación",
    pais: "Argentina",
    tipo: "sede_corporativa",
    mineralPrincipal: "Multimineral",
    status: "Sede Governamental",
    latitude: -34.6037,
    longitude: -58.3816,
    baciaOuRegiao: "Ciudad Autónoma de Buenos Aires",
    fonteOficial: "Secretaría de Minería Argentina",
    descricao: "Órgão regulador nacional responsável pelo cadastro e fomento geológico-mineiro (SEGEMAR).",
  },
  {
    id: "ar-arcadium-fenix",
    nome: "Proyecto Fénix (Salar del Hombre Muerto)",
    empresa: "Arcadium Lithium (fusão Livent + Allkem)",
    pais: "Argentina",
    tipo: "projeto_litio",
    mineralPrincipal: "Lítio (Cloreto e Carbonato)",
    status: "Operação ativa",
    latitude: -25.4389,
    longitude: -67.0358,
    baciaOuRegiao: "Salar del Hombre Muerto / Catamarca",
    fonteOficial: "Ministerio de Minería de Catamarca",
    descricao: "Pioneiro e mais antigo projeto de extração comercial de lítio em salmoura da Argentina.",
  },
  {
    id: "ar-allkem-olaroz",
    nome: "Proyecto Salar de Olaroz",
    empresa: "Arcadium Lithium (Allkem 66.5% / Toyota Tsusho 25% / JEMSE 8.5%)",
    pais: "Argentina",
    tipo: "projeto_litio",
    mineralPrincipal: "Lítio (Carbonato)",
    status: "Operação ativa",
    latitude: -23.6542,
    longitude: -66.8047,
    baciaOuRegiao: "Puna Jujeña / Susques, Jujuy",
    fonteOficial: "Secretaría de Minería de Jujuy",
    descricao: "Grande planta de carbonato de lítio em salmoura a quase 4.000m de altitude.",
  },
  {
    id: "ar-ganfeng-cauchari",
    nome: "Proyecto Cauchari-Olaroz",
    empresa: "Minera Exar (Ganfeng Lithium 46.7% / Lithium Americas 44.8% / JEMSE 8.5%)",
    pais: "Argentina",
    tipo: "projeto_litio",
    mineralPrincipal: "Lítio",
    status: "Operação ativa",
    latitude: -23.9519,
    longitude: -66.7847,
    baciaOuRegiao: "Salar de Cauchari / Jujuy",
    fonteOficial: "JEMSE / Gobierno de Jujuy",
    descricao: "Mais nova megaoperação de lítio na Argentina financiada com capital sino-canadense.",
  },
  {
    id: "ar-barrick-veladero",
    nome: "Mina Veladero",
    empresa: "Minera Argentina Gold (Barrick 50% / Shandong Gold 50%)",
    pais: "Argentina",
    tipo: "mina_operacao",
    mineralPrincipal: "Ouro / Prata",
    status: "Operação ativa",
    latitude: -29.3708,
    longitude: -69.9542,
    baciaOuRegiao: "Cordillera Frontal / San Juan",
    fonteOficial: "Ministerio de Minería de San Juan",
    descricao: "Mina de ouro a céu aberto na Cordilheira dos Andes com histórico de vazamentos de solução cianetada.",
  },
  {
    id: "ar-glencore-alumbrera",
    nome: "Bajo de la Alumbrera",
    empresa: "Glencore",
    pais: "Argentina",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Ouro / Molibdênio",
    status: "Cuidado e manutenção / Reuso",
    latitude: -27.3333,
    longitude: -66.6000,
    baciaOuRegiao: "Belén / Catamarca",
    fonteOficial: "Secretaría de Minería de Catamarca",
    descricao: "Primeira grande megamina da história da Argentina, em transição para o projeto integrado MARA.",
  },
  {
    id: "ar-lundin-josemaria",
    nome: "Proyecto Josemaría",
    empresa: "Lundin Mining",
    pais: "Argentina",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Ouro / Prata",
    status: "Desenvolvimento / Construção",
    latitude: -28.4528,
    longitude: -69.7547,
    baciaOuRegiao: "Iglesia / San Juan",
    fonteOficial: "Gobierno de San Juan",
    descricao: "Megaprojeto de cobre que marca o retorno dos investimentos de pórfiro cuprífero na Argentina.",
  },

  // --- MÉXICO ---
  {
    id: "mx-grupomexico-sede",
    nome: "Sede Corporativa Grupo México",
    empresa: "Grupo México",
    pais: "México",
    tipo: "sede_corporativa",
    mineralPrincipal: "Cobre / Prata / Zinco",
    status: "Sede Corporativa",
    latitude: 19.4326,
    longitude: -99.1889,
    baciaOuRegiao: "Ciudad de México",
    fonteOficial: "Bolsa Mexicana de Valores (BMV) / SEC",
    descricao: "Conglomerado controlador da Southern Copper e maior mineradora de cobre do México.",
  },
  {
    id: "mx-buenavista-cobre",
    nome: "Mina Buenavista del Cobre (Cananea)",
    empresa: "Southern Copper / Grupo México",
    pais: "México",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Molibdênio",
    status: "Operação ativa",
    latitude: 30.9856,
    longitude: -110.3019,
    baciaOuRegiao: "Cuenca del Río Sonora / Cananea, Sonora",
    fonteOficial: "SEMARNAT / PROFEPA",
    descricao: "Uma das maiores reservas de cobre do mundo; local do desastre ambiental do Rio Sonora em 2014.",
  },
  {
    id: "mx-penoles-fresnillo",
    nome: "Mina Fresnillo",
    empresa: "Fresnillo plc / Industrias Peñoles",
    pais: "México",
    tipo: "mina_operacao",
    mineralPrincipal: "Prata / Chumbo / Zinco",
    status: "Operação ativa",
    latitude: 23.1819,
    longitude: -102.8842,
    baciaOuRegiao: "Mesa Central / Zacatecas",
    fonteOficial: "Secretaría de Economía México (DGM)",
    descricao: "A mina de prata primária mais rica e produtiva em operação contínua no mundo.",
  },
  {
    id: "mx-newmont-penasquito",
    nome: "Mina Peñasquito",
    empresa: "Newmont Corporation",
    pais: "México",
    tipo: "mina_operacao",
    mineralPrincipal: "Ouro / Prata / Chumbo / Zinco",
    status: "Operação ativa",
    latitude: 24.7333,
    longitude: -101.6833,
    baciaOuRegiao: "Mazapil / Zacatecas",
    fonteOficial: "SEMARNAT / Newmont",
    descricao: "Maior mina polimetálica a céu aberto do México e uma das maiores produtoras de ouro e prata do continente.",
  },
  {
    id: "mx-penoles-torreon",
    nome: "Complejo Metalúrgico Met-Mex Peñoles",
    empresa: "Industrias Peñoles",
    pais: "México",
    tipo: "complexo_beneficiamento",
    mineralPrincipal: "Prata / Chumbo / Ouro / Zinco",
    status: "Operação ativa",
    latitude: 25.5342,
    longitude: -103.4542,
    baciaOuRegiao: "Comarca Lagunera / Torreón, Coahuila",
    fonteOficial: "Secretaría de Economía México",
    descricao: "Maior complexo metalúrgico não ferroso da América Latina e o maior produtor de prata refinada do mundo.",
  },

  // --- COLÔMBIA ---
  {
    id: "co-glencore-cerrejon",
    nome: "Mina Cerrejón",
    empresa: "Glencore (100%)",
    pais: "Colômbia",
    tipo: "mina_operacao",
    mineralPrincipal: "Carvão Térmico",
    status: "Operação ativa",
    latitude: 11.1019,
    longitude: -72.6719,
    baciaOuRegiao: "Cuenca del Río Ranchería / La Guajira",
    fonteOficial: "Agencia Nacional de Minería (ANM Colombia)",
    descricao: "A maior mina de carvão térmico a céu aberto da América Latina, com ferrovia privativa de 150 km.",
  },
  {
    id: "co-drummond-pribbenow",
    nome: "Mina Pribbenow (La Loma)",
    empresa: "Drummond Company",
    pais: "Colômbia",
    tipo: "mina_operacao",
    mineralPrincipal: "Carvão Térmico",
    status: "Operação ativa",
    latitude: 9.7042,
    longitude: -73.4756,
    baciaOuRegiao: "Cuenca del Cesar / El Paso",
    fonteOficial: "ANM Colombia / ANLA",
    descricao: "Principal operação de carvão da multinacional americana Drummond em território colombiano.",
  },
  {
    id: "co-south32-cerromatoso",
    nome: "Mina Cerro Matoso",
    empresa: "South32",
    pais: "Colômbia",
    tipo: "complexo_beneficiamento",
    mineralPrincipal: "Níquel (Ferroníquel)",
    status: "Operação ativa",
    latitude: 7.9542,
    longitude: -75.4358,
    baciaOuRegiao: "Montelíbano / Córdoba",
    fonteOficial: "ANM Colombia",
    descricao: "Um dos maiores depósitos de níquel laterítico a céu aberto do mundo com fundição própria.",
  },
  {
    id: "co-porto-bolivar",
    nome: "Puerto Bolívar",
    empresa: "Cerrejón / Glencore",
    pais: "Colômbia",
    tipo: "porto_minerario",
    mineralPrincipal: "Terminal Graneleiro de Carvão",
    status: "Operação ativa",
    latitude: 12.2542,
    longitude: -71.9719,
    baciaOuRegiao: "Mar do Caribe / Bahía Portete, La Guajira",
    fonteOficial: "DIMAR / Supertransporte Colombia",
    descricao: "Porto carbonífero marítimo com capacidade para atracar navios Capesize com calado natural profundo.",
  },

  // --- BOLÍVIA ---
  {
    id: "bo-ylb-uyuni",
    nome: "Complexo Industrial de Lítio Uyuni",
    empresa: "Yacimientos de Litio Bolivianos (YLB)",
    pais: "Bolívia",
    tipo: "projeto_litio",
    mineralPrincipal: "Lítio (Carbonato) / Potássio",
    status: "Operação estatal",
    latitude: -20.4856,
    longitude: -67.5519,
    baciaOuRegiao: "Salar de Uyuni / Potosí",
    fonteOficial: "Ministerio de Minería y Metalurgia Bolivia / YLB",
    descricao: "Centro nevrálgico da estratégia estatal boliviana sobre a maior reserva geológica de lítio da Terra.",
  },
  {
    id: "bo-san-cristobal",
    nome: "Mina San Cristóbal",
    empresa: "San Cristóbal Mining Inc. (ex-Sumitomo)",
    pais: "Bolívia",
    tipo: "mina_operacao",
    mineralPrincipal: "Zinco / Chumbo / Prata",
    status: "Operação ativa",
    latitude: -21.1542,
    longitude: -67.2219,
    baciaOuRegiao: "Provincia Nor Lípez / Potosí",
    fonteOficial: "SERGEOMIN Bolivia",
    descricao: "Maior empreendimento mineiro privado da Bolívia, localizado no altiplano andino a 4.000m de altitude.",
  },
  {
    id: "bo-comibol-huanuni",
    nome: "Empresa Minera Huanuni",
    empresa: "COMIBOL (Corporación Minera de Bolivia)",
    pais: "Bolívia",
    tipo: "mina_operacao",
    mineralPrincipal: "Estanho (Cassiterita)",
    status: "Operação estatal",
    latitude: -18.2856,
    longitude: -66.8342,
    baciaOuRegiao: "Cerro Posokoni / Oruro",
    fonteOficial: "COMIBOL / Ministerio de Minería",
    descricao: "Mundialmente famosa pela extração subterrânea de estanho de alto teor em rocha andina.",
  },

  // --- EQUADOR ---
  {
    id: "ec-mirador-cobre",
    nome: "Mina Mirador",
    empresa: "EcuaCorriente (CRCC-Tongling Nonferrous)",
    pais: "Equador",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Ouro / Prata",
    status: "Operação ativa",
    latitude: -3.5719,
    longitude: -78.4358,
    baciaOuRegiao: "Cordillera del Cóndor / Zamora Chinchipe",
    fonteOficial: "Ministerio de Energía y Minas Ecuador",
    descricao: "Primeira mina de cobre em grande escala a céu aberto na Amazônia equatoriana.",
  },
  {
    id: "ec-fruta-del-norte",
    nome: "Mina Fruta del Norte",
    empresa: "Lundin Gold (Canadá)",
    pais: "Equador",
    tipo: "mina_operacao",
    mineralPrincipal: "Ouro / Prata",
    status: "Operação ativa",
    latitude: -3.7656,
    longitude: -78.6189,
    baciaOuRegiao: "Cuenca Amazónica / Yantzaza, Zamora Chinchipe",
    fonteOficial: "Ministerio de Energía y Minas Ecuador / Lundin Gold",
    descricao: "Depósito de ouro subterrâneo de alto teor operado com normas internacionais de sustentabilidade.",
  },

  // --- PANAMÁ ---
  {
    id: "pa-cobre-panama",
    nome: "Mina Cobre Panamá",
    empresa: "First Quantum Minerals",
    pais: "Panamá",
    tipo: "mina_operacao",
    mineralPrincipal: "Cobre / Ouro / Molibdênio",
    status: "Paralisada por decisão da Suprema Corte",
    latitude: 9.0042,
    longitude: -80.6519,
    baciaOuRegiao: "Corredor Biológico Mesoamericano / Donoso, Colón",
    fonteOficial: "Ministerio de Comercio e Industrias (MICI) / Corte Suprema de Panamá",
    descricao: "Maior investimento privado da história do Panamá, objeto de litígio constitucional e ambiental histórico.",
  },
];

/**
 * Converte as instalações para GeoJSON FeatureCollection.
 */
export function gerarGeoJsonInstalacoesLatam(): object {
  return {
    type: "FeatureCollection",
    metadata: {
      fonte: "Controle Popular — Observatório Transnacional de Mineração na América Latina",
      dataAtualizacao: "2026-09-30",
      totalInstalacoes: INSTALACOES_LATAM.length,
      paisesCobertos: ["Brasil", "Chile", "Peru", "Argentina", "México", "Colômbia", "Bolívia", "Equador", "Panamá"],
      aviso: "Coordenadas precisas em datum WGS84 compiladas a partir de relatórios regulatórios oficiais e imagens de satélite.",
    },
    features: INSTALACOES_LATAM.map((inst) => ({
      type: "Feature",
      id: inst.id,
      geometry: {
        type: "Point",
        coordinates: [inst.longitude, inst.latitude],
      },
      properties: {
        id: inst.id,
        nome: inst.nome,
        empresa: inst.empresa,
        pais: inst.pais,
        tipo: inst.tipo,
        mineral: inst.mineralPrincipal,
        status: inst.status,
        bacia: inst.baciaOuRegiao,
        fonte: inst.fonteOficial,
        descricao: inst.descricao,
      },
    })),
  };
}

/**
 * Executa a compilação e gravação dos arquivos.
 */
export function executarEtlAmericaLatina(): void {
  console.log("🌎 Iniciando ETL de Mineração e Instalações da América Latina...");

  // 1. Gera GeoJSON para o Globo 3D
  fs.mkdirSync(path.dirname(GEOJSON_DESTINO), { recursive: true });
  const geojson = gerarGeoJsonInstalacoesLatam();
  fs.writeFileSync(GEOJSON_DESTINO, JSON.stringify(geojson, null, 2), "utf-8");
  console.log(`✓ GeoJSON salvo em: ${GEOJSON_DESTINO} (${INSTALACOES_LATAM.length} feições)`);

  // 2. Compacta dados para o frontend Next.js
  fs.mkdirSync(DATA_DIR, { recursive: true });
  const compactadoInstalacoes = compactar(INSTALACOES_LATAM as unknown as Record<string, unknown>[]);
  const caminhoJsonCompacto = path.join(DATA_DIR, "instalacoes-latam.compact.json");
  fs.writeFileSync(caminhoJsonCompacto, JSON.stringify(compactadoInstalacoes), "utf-8");
  console.log(`✓ JSON compactado salvo em: ${caminhoJsonCompacto}`);

  // 3. Agrupamento por empresas corporativas da América Latina
  const empresasAgrupadas = Array.from(new Set(INSTALACOES_LATAM.map((i) => i.empresa))).map((empresa) => {
    const insts = INSTALACOES_LATAM.filter((i) => i.empresa === empresa);
    const paises = Array.from(new Set(insts.map((i) => i.pais)));
    const minerais = Array.from(new Set(insts.map((i) => i.mineralPrincipal)));
    return {
      empresa,
      totalInstalacoes: insts.length,
      paises,
      minerais,
      instalacoes: insts.map((i) => ({ id: i.id, nome: i.nome, tipo: i.tipo })),
    };
  });

  const compactadoEmpresas = compactar(empresasAgrupadas as unknown as Record<string, unknown>[]);
  const caminhoEmpresas = path.join(DATA_DIR, "mineradoras-latam.compact.json");
  fs.writeFileSync(caminhoEmpresas, JSON.stringify(compactadoEmpresas), "utf-8");
  console.log(`✓ Acervo de mineradoras compactado salvo em: ${caminhoEmpresas} (${empresasAgrupadas.length} empresas)`);
}

if (process.argv[1] && process.argv[1].endsWith("gerar-acervo-america-latina.mts")) {
  executarEtlAmericaLatina();
}
