// Gerado automaticamente de top-100-paginas.json
// Mapa href → resumo para TTS (OuvirNavbar)
export const RESUMOS_TOP100: Record<string, string> = {
  "/": "Painel consolidado com R$ 251 bi em recursos públicos monitorados, acesso aos 3 Eixos Temáticos, notícias urgentes e busca rápida.",
  "/busca": "Motor de busca textual em memória cobre atos oficiais, proposições, tribunais, notícias e páginas estruturais do portal.",
  "/indice": "Sumário completo em formato wiki organizado por frentes cívicas, temas transversais e situações práticas do cidadão.",
  "/sobre": "Apresentação institucional do ONSA, fontes oficiais, separação entre código determinístico e IA, e garantia editorial.",
  "/imprensa": "Números-chave para redações e pesquisadores: R$ 251 bi auditados, 199 cidades estratégicas e acordos socioambientais.",
  "/termos": "Direitos dos titulares de dados, política de transparência passiva, canal de retificação e princípios de proteção à privacidade.",
  "/dados/populares": "Ponto de partida para os datasets brutos do portal, dicionários de variáveis e arquivos compactados.",
  "/dados/comunicabr": "Painel dos R$ 139 bi transferidos pela União aos 853 municípios mineiros (Bolsa Família, SUS, Fundeb e BPC).",
  "/alertas": "Inscrição cidadã para receber atualizações sobre editais, desastres, novos contratos e riscos climáticos.",
  "/tecnologia": "Documentação da stack aberta, modelos Seu Nonô e Sabiá 7B, guias AppLivre e soberania tecnológica.",
  "/editais": "Painel interativo de 50 certames com gráfico SVG inline por órgão, 4 cartões de status, filtros e exportação CSV.",
  "/estudos-rurais": "Hub de pesquisas do campo, agroecologia, agricultura familiar e produção científica do PPGER/UFVJM.",
  "/biblioteca": "Acervo unificado de documentos públicos, relatórios de auditoria, estudos de impacto e perícias.",
  "/ambiental/legislacao": "Repositório de decretos, leis municipais e normas de acesso à informação e controle fiscal.",
  "/direitos-em-movimento": "Compras públicas de alimentos da agricultura familiar e programas de combate à vulnerabilidade alimentar.",
  "/direitos-em-movimento/saude-publica": "Monitoramento de unidades básicas de saúde, leitos hospitalares, repasses da União e atendimento.",
  "/direitos-em-movimento/educacao": "Infraestrutura escolar, merenda, metas educacionais e acompanhamento do orçamento do Fundeb.",
  "/direitos-em-movimento/trabalho-e-renda": "Saldo de empregos formais, setores econômicos em crescimento e evolução salarial municipal.",
  "/direitos-em-movimento/ajuda": "Guia de órgãos de assistência jurídica gratuita: Defensoria Pública, OAB Cidadã, CRAS, CREAS e Conselhos Tutelares.",
  "/direitos-em-movimento/denuncia": "Ferramenta no navegador para estruturar denúncias formais a ouvidorias e ministérios públicos sem salvar dados pessoais.",
  "/direitos-em-movimento/informacao": "Modelos de ofício e orientações da Lei 12.527/2011 para requerer documentos a órgãos públicos.",
  "/direitos-em-movimento/conselhos": "Diretório e canais de participação popular nas decisões sobre políticas públicas locais.",
  "/cidades": "Panorama completo dos municípios mineiros monitorados com indicadores fiscais, econômicos e ambientais.",
  "/betim": "Município polo industrial com mais de R$ 1,65 bi em compras catalogadas e orçamento detalhado.",
  "/betim/camara": "Perfil dos vereadores, tramitação de projetos de lei, diários da câmara e despesas do Legislativo.",
  "/betim/prefeitura/diario": "Acervo histórico de 16.601 atos oficiais classificados por matéria de interesse social.",
  "/betim/saude": "Hospitais, UPAs, contratos de insumos e medicamentos, e acompanhamento do SUS municipal.",
  "/betim/educacao": "Rede municipal de ensino, infraestrutura de creches e desempenho nas metas do IDEB.",
  "/betim/economia": "Maiores fornecedores municipais, contratações pelo PNCP e arrecadação tributária.",
  "/betim/clima": "Áreas suscetíveis a alagamento, monitoramento meteorológico e alertas da Defesa Civil.",
  "/betim/meio-ambiente": "Licenciamentos industriais, preservação da bacia hidrográfica e gestão de resíduos.",
  "/betim/rede-de-protecao": "Mapeamento de CRAS, CREAS, abrigos públicos e entidades civis de assistência.",
  "/bh": "Orçamento anual de mais de R$ 19 bi, grandes obras, contratações e atos oficiais da capital mineira.",
  "/bh/camara": "Fiscalização do Executivo, projetos em debate e atuação dos 41 vereadores de BH.",
  "/bh/saude": "Rede hospitalar do SUS na capital, fila de consultas e leitos de UTI.",
  "/bh/educacao": "Avaliação do IDEB municipal, distribuição de escolas e orçamento da educação básica.",
  "/bh/economia": "Grandes licitações de transporte público, limpeza urbana e infraestrutura de Belo Horizonte.",
  "/diamantina": "Mais de 16 mil atos oficiais catalogados, proteção ao patrimônio histórico e compras públicas.",
  "/aracuai": "Contratos municipais, repasses sociais e acompanhamento dos impactos da mineração de lítio.",
  "/itinga": "Arrecadação de royalties minerais (CFEM), contratos e serviços públicos no polo do lítio.",
  "/brumadinho": "Repasses do Acordo de Reparação, projetos comunitários, saúde mental e infraestrutura urbana.",
  "/mariana": "Obras de reparação do rompimento da barragem de Fundão, reassentamentos e acompanhamento orçamentário.",
  "/serro": "Atos municipais, preservação cultural do queijo artesanal e monitoramento de outorgas hídricas.",
  "/governador-valadares": "Qualidade da água tratada, indenizações do desastre de Mariana e compras públicas municipais.",
  "/ipatinga": "Polo siderúrgico mineiro, licenciamento ambiental de indústrias, finanças e diário oficial.",
  "/juiz-de-fora": "Contratos, dados de transparência tributária e indicadores hospitalares da Zona da Mata.",
  "/uberlandia": "Segunda maior economia de Minas: receitas tributárias, compras públicas e prestação de contas.",
  "/ambiental": "Painel integrado do Observatório Nacional Socioambiental: bacias, alertas ecológicos e crimes socioambientais.",
  "/ambiental/mariana": "Execução da repactuação judicial de R$ 171 bilhões, repasses estaduais e obras na bacia do Rio Doce.",
  "/ambiental/barragens": "Gestão de barragens da ANM/SIGBM e FEAM com classificação de dano potencial, categoria de risco e localização geográfica.",
  "/ambiental/barragens/descaracterizacao": "Cronograma de eliminação de barragens com método a montante (Lei Mar de Lama) e alertas de Nível 3.",
  "/ambiental/barragens/sigbm": "Consulta técnica detalhada de relatórios de estabilidade, vistorias e coordenadas da ANM.",
  "/paraopeba": "Acompanhamento dos repasses mensais executados pela FGV em suporte financeiro às famílias atingidas.",
  "/paraopeba/execucao": "Auditoria dos R$ 5,48 bi transferidos com taxa de pagamento e status físico dos projetos.",
  "/paraopeba/biblioteca": "Acervo digital de laudos periciais da UFMG, pareceres das ATIs e relatórios socioeconômicos.",
  "/ambiental/licenciamento": "Processos minerários e industriais no SIAM/Semad, classes de impacto e tramitação.",
  "/ambiental/copam": "Pautas de julgamento, atas e deliberações das Câmaras Técnicas de mineração e indústria.",
  "/ambiental/tac": "Obrigações e compensações socioambientais firmadas por empresas com o Ministério Público e o Estado.",
  "/ambiental/conselhos": "Estrutura dos Comitês de Bacias Hidrográficas (CBH) e conselhos municipais de meio ambiente.",
  "/ambiental/clima-risco": "Mapa de riscos climáticos em MG: áreas de secas extremas, deslizamentos e enchentes recorrentes.",
  "/ambiental/car": "Análise de 1,16 milhão de imóveis rurais em 14 URFBios de Minas Gerais, tempo médio de espera, setores e portes.",
  "/ambiental/capacidade-institucional": "Série histórica decenal (2016-2026) de servidores, orçamento real deflacionado pelo IPCA e sobrecarga em 14 órgãos reguladores.",
  "/ambiental/ecossistema": "Mapeamento dos órgãos ambientais dos 27 estados (OEMAs), ministérios federais, autarquias e concessionárias de água e luz.",
  "/judiciario": "Transparência dos órgãos de justiça em Minas: orçamentos bilionários, auxílios e produtividade.",
  "/judiciario/instituicoes": "Quadro comparativo de despesas, remunerações, lideranças e contatos de todas as cortes.",
  "/judiciario/instituicoes/tjmg": "Orçamento anual de R$ 14,96 bi: folha de pagamentos, auxílio-alimentação e diárias de magistrados.",
  "/judiciario/instituicoes/mpmg": "Orçamento de R$ 4,09 bi, verbas indenizatórias de promotores e atuação das promotorias de tutela coletiva.",
  "/judiciario/instituicoes/dpmg": "Orçamento de R$ 1,10 bi, disparidade em relação a TJ/MP e mapa do déficit de defensores públicos.",
  "/judiciario/instituicoes/trt3": "Orçamento de R$ 3,18 bi, varas trabalhistas de Minas, correições e atendimento ao trabalhador.",
  "/judiciario/instituicoes/trf6": "Justiça federal em MG: despesas de instalação, custeio e julgamentos de litígios federais.",
  "/judiciario/instituicoes/tcemg": "Orçamento de R$ 1,15 bi, auditorias externas, pareceres sobre contas municipais e rejeições.",
  "/judiciario/instituicoes/dpu": "Assistência jurídica federal gratuita para o cidadão perante o INSS, Caixa e órgãos federais.",
  "/judiciario/sirenejud": "Painel de processos judiciais ambientais por município, vara e classe processual em Minas Gerais.",
  "/congresso": "Atuação dos 53 deputados e 3 senadores de Minas Gerais: votações, presença e propostas.",
  "/congresso/gastos": "Despesas indenizatórias de gabinete: passagens aéreas, combustível, consultorias e alimentação.",
  "/congresso/proposicoes": "Acompanhamento das proposições em tramitação com foco em direitos sociais e sustentabilidade.",
  "/congresso/votacoes": "Registro de como cada parlamentar mineiro votou nas principais reformas e medidas legislativas.",
  "/congresso/emendas": "Rastreamento do destino de recursos federais alocados por deputados e senadores nas cidades do estado.",
  "/governo": "Checagem das propostas do plano de governo estadual, concessões e privatizações.",
  "/governo/mg": "Organograma do governo estadual, orçamentos setoriais e despesas de custeio por pasta.",
  "/estado-e-economia": "Painel integrado das receitas estaduais, endividamento com a União e investimentos públicos.",
  "/estado-e-economia/orcamento": "Distribuição do ICMS, repasses automáticos aos municípios e execução orçamentária da LOA.",
  "/instituicoes": "Diretório unificado de secretarias, autarquias e empresas estatais com telefones e ouvidorias.",
  "/empresas": "Monitoramento de governança corporativa, licenças, infrações ambientais e contratos com o Estado.",
  "/empresas/vale": "Produção mineral, balanço financeiro, compromissos judiciais dos rompimentos e autos de infração.",
  "/empresas/sigma-lithium": "Operações no Vale do Jequitinhonha, licenças ambientais, outorgas de água e incentivos fiscais.",
  "/empresas/documentos": "Autos de embargo do Ibama, relatórios da CVM e termos de ajuste de conduta das corporações.",
  "/funcaosocialterra": "Demarcação, proteção territorial e situação jurídica das terras dos povos originários em MG.",
  "/funcaosocialterra/mapa": "Visualização tridimensional em satélite de requerimentos minerários, CAR, UCs e territórios tradicionais.",
  "/funcaosocialterra/alertas": "Identificação automática de processos de mineração sobrepostos a terras protegidas e quilombos.",
  "/noticias": "Artigos investigativos de profundidade com rigor científico, citações ABNT e metadados BibTeX."
};
