// Gerado automaticamente de top-100-paginas.json
// Mapa href → resumo para TTS (OuvirNavbar)
export const RESUMOS_TOP100: Record<string, string> = {
  "/terra-e-territorios": "Visão geral da soberania socioambiental, cidades estratégicas, bacias hidrográficas, licenciamento e Globo 3D.",
  "/funcaosocialterra/mapa": "Visualizador 3D interativo com camadas de terras indígenas, quilombolas, CAR, bacias, cavas e mineração.",
  "/funcaosocialterra": "Diagnóstico fundiário de áreas sem cadastro no CAR, sobreposições registrais e cumprimento da função social.",
  "/funcaosocialterra/alertas": "Monitoramento de alertas de desmatamento, invasões de áreas protegidas e conflitos fundiários em tempo real.",
  "/cidades": "Rede de fiscalização municipal em 27 capitais e 176 polos regionais com dados fiscais, contratuais e do SUS.",
  "/cidades/mg": "Painel estadual completo com indicadores orçamentários, repasses constitucionais e contratos dos 853 municípios de MG.",
  "/betim": "Polo industrial da RMBH com mais de R$ 1,65 bi em compras auditadas, saúde, educação e obras públicas.",
  "/bh": "Fiscalização de contratos da PBH, Câmara Municipal, leitos SUS, trânsito e arrecadação da capital mineira.",
  "/sp": "Monitoramento de contratos bilionários da Prefeitura de SP, Câmara de Vereadores e execução orçamentária paulistana.",
  "/brumadinho": "Acompanhamento minucioso das obras de reparação, repasses do Acordo Judicial e perícias do desastre de 2019.",
  "/mariana": "Execução da repactuação histórica de Mariana, reassentamentos de Bento Rodrigues e Paracatu e indenizações.",
  "/aracuai": "Capital histórica do Vale do Jequitinhonha: projetos de lítio, transição energética e impacto em comunidades.",
  "/diamantina": "Patrimônio cultural da humanidade, nascentes de bacias, turismo sustentável e dados públicos municipais.",
  "/itinga": "Epicentro da mineração de lítio em Minas Gerais: receitas da CFEM, contratos públicos e impactos hídricos locais.",
  "/governador-valadares": "Principal centro urbano do Vale do Rio Doce atingido pela lama da Samarco: captação de água e repasses do acordo.",
  "/uberlandia": "Maior cidade do interior de Minas: logística do agronegócio, orçamento municipal e contratos públicos.",
  "/juiz-de-fora": "Indicadores fiscais, saúde pública regional, Câmara Municipal e serviços essenciais da Zona da Mata.",
  "/terra-e-territorios/vales": "82 municípios analisados: corrida do lítio, comunidades quilombolas, povo Maxakali e IDH regional.",
  "/terra-e-territorios/nossos-rios": "Monitoramento hidrológico de 8 bacias: qualidade da água, outorgas, desastres industriais e saneamento básico.",
  "/terra-e-territorios/nossas-serras": "Defesa de formações geológicas, recarga de aquíferos e contenção da expansão minerária na Serra do Curral e Espinhaço.",
  "/paraopeba": "Biblioteca de crimes socioambientais: monitoramento dos R$ 37,7 bi do acordo de Brumadinho e direitos atingidos.",
  "/paraopeba/execucao": "Detalhamento de cada desembolso da Vale S.A., cronograma físico-financeiro de projetos e obras nos 26 municípios.",
  "/paraopeba/biblioteca": "Mais de 400 documentos técnicos: relatórios de auditorias independentes, perícias judiciais da UFMG e TACs.",
  "/paraopeba/linha-do-tempo": "Cronologia desde o rompimento da barragem B1 em 2019 até as audiências judiciais e cumprimento de prazos do acordo.",
  "/ambiental": "Hub integrador de dados ambientais de Minas Gerais: licenciamento, barragens, denúncias e decisões colegiadas.",
  "/ambiental/mariana": "Fiscalização da repactuação de R$ 171 bi do desastre de Mariana: reparação do Rio Doce, saúde e indenizações individuais.",
  "/ambiental/barragens": "Catálogo completo de 942 barragens de mineração com dados de altura, volume, categoria de dano potencial e vistorias.",
  "/ambiental/barragens/descaracterizacao": "Acompanhamento do cronograma de descaracterização de estruturas a montante obrigadas pela Lei Mar de Lama Nunca Mais.",
  "/ambiental/licenciamento": "Mais de 8.600 processos minerários e industriais com status, audiências públicas e pareceres da FEAM, IBAMA e órgãos estaduais.",
  "/ambiental/copam": "Atas, votações nominais de conselheiros e pautas de reuniões das Câmaras Especializadas do Conselho de Política Ambiental.",
  "/ambiental/tac": "Acordos extrajudiciais firmados por poluidoras com o Ministério Público e IBAMA para compensação de danos socioambientais.",
  "/ambiental/clima-risco": "Vulnerabilidade climática de todos os municípios brasileiros em recursos hídricos, seca, desastres naturais e saúde.",
  "/ambiental/car": "Base de imóveis rurais declarados, áreas de preservação permanente (APP), reserva legal e sobreposições em terras públicas.",
  "/mineracao/cavas": "Série temporal de imagens de satélite Sentinel e modelo de visão computacional calibrado mapeando a expansão de cavas em MG.",
  "/canada": "Vigilância de mineradoras listadas na TSX que operam em território brasileiro: histórico de emissões e processos ambientais.",
  "/america-latina": "Monitoramento de impactos da megamineração e litígios ambientais nos Andes e Cone Sul conectando bacias transfronteiriças.",
  "/direitos-em-movimento": "Garantias fundamentais, serviços essenciais, saúde, educação, moradia e canais populares de acesso à justiça.",
  "/memoria": "Registro cronológico vivo das mobilizações sociais, greves, conquistas de direitos e marcos históricos da classe trabalhadora.",
  "/ambiental/legislacao": "Mais de 15 mil normas e decretos federais, estaduais e municipais organizados por direito social atingido e marco legal.",
  "/direitos-em-movimento/ajuda": "Guia de assistência jurídica gratuita (Defensoria/OAB), clínicas populares e proteção contra corte de água e energia.",
  "/direitos-em-movimento/saude-publica": "Capacidade instalada do SUS, estabelecimentos CNES, razão habitante/leito e internações hospitalares por município.",
  "/direitos-em-movimento/educacao": "Indicadores educacionais do IDEB, matrículas do Censo Escolar, merenda e aplicação das verbas constitucionais do Fundeb.",
  "/direitos-em-movimento/trabalho-e-renda": "Estatísticas de admissões e demissões do CAGED, evolução do salário médio e estoque de empregos formais por cidade.",
  "/direitos-em-movimento/conselhos": "710 conselhos municipais e estaduais mapeados: saúde, educação, assistência social, CODEMA e conselhos tutelares.",
  "/direitos-em-movimento/informacao": "Modelos prontos de ofício sob a Lei 12.527/2011 e diretório direto de 445 portais oficiais de transparência passiva.",
  "/direitos-em-movimento/denuncia": "Roteiro guiado para formatar denúncias a ouvidorias e MPs: gera documento DOCX localmente no navegador sem salvar dados.",
  "/ambiental/decisoes-lai": "Decisões colegiadas que derrubaram negativas indevidas de órgãos públicos para fundamentar recursos de cidadãos.",
  "/ambiental/direitos-humanos": "Relatórios e recomendações do CNDH sobre violações contra populações atingidas por barragens e comunidades tradicionais.",
  "/ambiental/direito-critico": "Artigos, teses garantistas e pareceres da assessoria jurídica popular para defesa de direitos coletivos e difusos.",
  "/ambiental/conselhos": "Funcionamento de conselhos municipais de meio ambiente em Minas Gerais e canais para representação comunitária.",
  "/ambiental/capacidade-institucional": "Auditoria de quadro de pessoal, fiscais de campo e capacidade operacional da FEAM, IEF, IGAM e IBAMA.",
  "/ambiental/ecossistema": "Rede de cooperação entre movimentos sociais, sindicatos, universidades e organizações não governamentais.",
  "/ambiental/patrimonio-cultural": "Base de bens culturais tombados pelo IEPHA e IPHAN, fazendas históricas, sítios arqueológicos e comunidades quilombolas.",
  "/recursos/estados": "Comparativo federativo de programas estaduais de proteção social, combate à pobreza e assistência judiciária.",
  "/estado-e-economia": "Vigilância de contratos públicos, compras governamentais, 27 Assembleias, Congresso, Judiciário e ESG.",
  "/estado-e-economia/orcamento": "Dotação inicial, arrecadação tributária em tempo real e despesas liquidadas do Governo de Minas Gerais.",
  "/judiciario/instituicoes": "Estrutura dos órgãos de controle disciplinar: Conselho Nacional de Justiça, CNMP e corregedorias dos tribunais.",
  "/judiciario/contatos": "Catálogo com telefones DDD, e-mails, endereços com CEP, juízes titulares e link do Balcão Virtual em 298 comarcas.",
  "/assembleias": "Painel comparativo com projetos de lei, despesas de gabinete e composição parlamentar de todas as 27 Assembleias.",
  "/ambiental/contratos": "Monitoramento de contratos administrativos, alertas de dispensa indevida de licitação e concentração de fornecedores.",
  "/judiciario": "Visão geral de tribunais de justiça, cortes superiores e tribunais de contas com dados de composição e remuneração.",
  "/judiciario/tribunais": "Lista nominal de desembargadores e ministros, idade, tempo de toga, histórico de nomeações e quinto constitucional.",
  "/judiciario/sirenejud": "Base de dados geográfica do CNJ de ações civis públicas ambientais, embargos judiciais e crimes contra a flora.",
  "/judiciario/recomendacoes": "Relatórios de correições e inspeções do CNJ em comarcas mineiras sobre morosidade processual e conduta.",
  "/congresso": "Atuação legislativa federal: proposições classificadas por direito violado, bancadas temáticas e comissões.",
  "/congresso/proposicoes": "Projetos de lei de impacto social, tramitação em tempo real, autores, relatores e alertas de risco aos direitos.",
  "/congresso/votacoes": "Placar nominal de votações em plenário com análise de coerência entre discursos e votos sobre pautas populares.",
  "/congresso/mg": "Atuação detalhada dos 53 deputados federais e 3 senadores de MG: emendas parlamentares destinadas e votações.",
  "/governo": "Checagem independente de promessas de campanha registradas no TSE versus entregas reais e decretos governamentais.",
  "/dados/comunicabr": "R$ 139 bi transferidos pela União aos 853 municípios de MG: Bolsa Família, Farmácia Popular, Fundeb e SUS.",
  "/ambiental/convenios": "Acordos e emendas parlamentares federais do Transferegov destinados a obras e custeio nos municípios.",
  "/ambiental/ppp": "Contratos de concessão rodoviária, saneamento, metrô e energia com tarifas cobradas e obrigações de investimento.",
  "/empresas": "Observatório de grandes conglomerados, rede societária, infrações ambientais e contratos com o poder público.",
  "/empresas/fortunas": "Patrimônio de bilionários, fundos transnacionais e cruzamentos com a posse de terras e minas no Brasil.",
  "/empresas/conglomerados": "Mapeamento das teias acionárias e holdings que controlam setores estratégicos da mineração, energia e finanças.",
  "/empresas/executivos": "Movimentação de altos executivos entre agências reguladoras públicas e diretorias de empresas privadas fiscalizadas.",
  "/eua": "Dados públicos da SEC americana sobre empresas operando no Brasil, grandes fundos (BlackRock) e compras governamentais.",
  "/europa": "Processos históricos de desastres brasileiros julgados no exterior: BHP em Londres, Braskem em Roterdã e diretivas de devida diligência.",
  "/desclassificados": "Acervo de arquivos diplomáticos e militares desclassificados sobre soberania nacional, acordos bilaterais e inteligência.",
  "/": "Painel mestre com R$ 251 bi monitorados, acesso aos 4 Eixos Temáticos, notícias urgentes e busca universal.",
  "/central": "Centro de inteligência cívica: editais diários, biblioteca digital, laboratório de gráficos, rádios e assistente Seu Nonô.",
  "/editais": "Varredura automatizada diária do Diário Oficial de MG para chamamentos de fomento popular, licitações e certames públicos.",
  "/biblioteca": "Mais de 24 mil relatórios de ATIs, auditorias independentes, perícias da UFMG e decisões judiciais na íntegra.",
  "/laboratorio/arvore": "Grafo interativo estilo Obsidian mapeando teias de relações entre empresas, poderes públicos, bacias e cidades.",
  "/assistente": "Inteligência artificial cívica com escada determinística, citação de fontes oficiais e leitura em áudio para o cidadão.",
  "/busca": "Motor de busca de alta velocidade com tolerância a acentos sobre atos oficiais, leis, empresas e acervos do portal.",
  "/indice": "Sumário geral em formato wiki organizado pelos 4 Eixos Temáticos, catálogo das 100 páginas e situações práticas.",
  "/laboratorio": "Cruzamento lado a lado de bases públicas com gráficos interativos dither e testes de hipóteses socioeconômicas.",
  "/radio": "44 emissoras públicas, universitárias e comunitárias do Brasil e do mundo com transmissão direta e sem rastreadores.",
  "/noticias": "Investigações cívicas aprofundadas, estudos técnicos e matérias analíticas com hiperlink para cada dado citado.",
  "/alertas": "Alertas sobre emergências em barragens, riscos climáticos do Inmet e novos contratos públicos de alto impacto.",
  "/tecnologia": "Arquitetura aberta do portal, ferramentas sem dependência de big techs e documentação de modelos de IA locais.",
  "/documentacao": "Manuais de arquitetura, governança dos 4 Eixos Temáticos, diagramas de dados e rotinas operacionais.",
  "/api": "Endpoints públicos em JSON aberto sem necessidade de chave de autenticação para pesquisadores e auditores.",
  "/estudos-rurais": "Estudos acadêmicos e populares sobre cartografia social, agroecologia e agricultura camponesa (UFVJM/PPGER).",
  "/sobre": "Histórico do Observatório Nacional Socioambiental, Regra das Seis Qualidades e garantia de dupla checagem.",
  "/imprensa": "Informações estruturadas para jornalistas e comunicadores populares com números auditados e contatos.",
  "/termos": "Blindagem contra dados pessoais (CPF), conformidade rigorosa com a LGPD e termos de licença de dados públicos.",
  "/dados/populares": "Acesso a planilhas CSV com BOM UTF-8 e arquivos compactados gerados pelos coletores do portal.",
  "/internacional": "Transparência global: resoluções da ONU, dados de saúde da OMS, patrimônio UNESCO e metas do clima.",
};
