/**
 * @file scripts/etl/empresas/gerar-conglomerados-monopolios.mts
 * @description Gerador ETL do acervo de Conglomerados, Holdings, Monopólios, Cartéis e Trustes.
 *
 * Papel no portal:
 * Mapeia as estruturas corporativas de controle acionário, holdings globais,
 * subsidiárias operacionais e concessões estratégicas atuantes no Brasil.
 *
 * Frentes investigadas:
 * 1. Redes de controle dos Big Three (BlackRock, Vanguard, State Street) sobre mineradoras, energia, bancos e tecnologia.
 * 2. Cartéis e oligopólios de grãos ABCD (ADM, Bunge, Cargill, Louis Dreyfus).
 * 3. Big Mining (Vale, BHP, Rio Tinto, Glencore, Anglo American).
 * 4. Big Oil e Big Tech (Petrobras, Shell, TotalEnergies, Microsoft, Google, AWS, Apple, Meta, Nvidia).
 * 5. Cálculo de participação de mercado e índice HHI (Herfindahl-Hirschman) por setor.
 *
 * Fontes oficiais consultadas:
 * - CVM (Comissão de Valores Mobiliários) — Formulários de Referência e Composição Acionária.
 * - SEC EDGAR (U.S. Securities and Exchange Commission) — Formulários 13F, 10-K e 20-F.
 * - CADE (Conselho Administrativo de Defesa Econômica) — Atos de Concentração e Inquéritos Antitruste.
 * - ANM (Agência Nacional de Mineração) / SIGMINE — Concessões de lavra e direitos minerários.
 * - ANP (Agência Nacional do Petróleo) — Rodadas de partilha do Pré-Sal e refino.
 * - ANTAQ (Agência Nacional de Transportes Aquaviários) — Arrendamentos de terminais portuários.
 * - Banco Central do Brasil (BCB) — Relatório de Estabilidade Financeira e Concentração Bancária.
 *
 * Decisões técnicas e restrições:
 * - Compactação estática via `compactar.ts` gerando `conglomerados-holdings.compact.json`.
 * - Sanitização rigorosa contra dados pessoais (Zero CPF Mod-11).
 * - Sem dependências externas pesadas: gera dados puros para Canvas 60fps, Mapa Mental SVG e Tabela das 6 Qualidades.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compactar } from "../../../apps/web/lib/estatico/compactar.js";

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const DATA_DIR = path.join(RAIZ, "apps", "web", "data", "empresas");

export type TipoNoConglomerado =
  | "holding"
  | "investimento"
  | "subsidiaria"
  | "concessao";

export type SetorConglomerado =
  | "mineracao"
  | "agronegocio_graos"
  | "energia_petroleo"
  | "bancos_financas"
  | "tecnologia";

export interface RegistroNoConglomerado {
  id: string;
  nome: string;
  siglaOuTicker: string;
  tipo: TipoNoConglomerado;
  tipoRotulo: string;
  setor: SetorConglomerado;
  setorRotulo: string;
  paisOrigem: string;
  jurisdicao: string;
  nivelHierarquico: number; // 1: Holding, 2: Investimento, 3: Subsidiária, 4: Concessão
  holdingPaiId: string;
  controladorPrincipal: string;
  participacaoControladorPct: number;
  valorMercadoOuAtivos: string;
  participacaoMercadoPct: number;
  faturamentoOuReceita: string;
  hhiSetorial: number;
  classificacaoHhi: string;
  posicaoRankingSetor: number;
  descricao: string;
  ativosEstrategicos: string;
  riscosAntitruste: string;
  fontesOficiais: string;
  urlOficial: string;
}

export interface RegistroArestaControle {
  id: string;
  origemId: string;
  destinoId: string;
  tipoRelacao:
    | "propriedade_comum_big_three"
    | "controle_majoritario"
    | "participacao_significativa"
    | "subsidiaria_integral"
    | "joint_venture"
    | "concessao_exploracao"
    | "cartel_infraestrutura";
  tipoRotulo: string;
  participacaoPct: number;
  valorEstimado: string;
  detalhes: string;
  fonteOficial: string;
  urlOficial: string;
}

export interface RegistroConcentracaoSetorial {
  setorId: SetorConglomerado;
  nome: string;
  hhi: number;
  classificacao: string;
  cr4Pct: number;
  descricaoConcorrencial: string;
  criterioCade: string;
  principaisPlayers: {
    nome: string;
    sigla: string;
    participacaoPct: number;
    tipo: string;
  }[];
  alertasAntitruste: string[];
  fonteOficial: string;
  urlOficial: string;
}

// ══════════════════════════════════════════════════════════════════════════
// 1. CATÁLOGO COMPLETO DE NÓS (HOLDINGS -> INVESTIMENTOS -> SUBSIDIÁRIAS -> CONCESSÕES)
// ══════════════════════════════════════════════════════════════════════════

export const NOS_CONGLOMERADOS: RegistroNoConglomerado[] = [
  // ─── NÍVEL 1: HOLDINGS GLOBAIS E GESTORAS (BIG THREE & HOLDINGS NACIONAIS) ───
  {
    id: "blackrock",
    nome: "BlackRock, Inc.",
    siglaOuTicker: "NYSE: BLK",
    tipo: "holding",
    tipoRotulo: "Gestora Global de Ativos / Fundo Universal",
    setor: "bancos_financas",
    setorRotulo: "Gestão Global de Ativos & Mercados",
    paisOrigem: "Estados Unidos",
    jurisdicao: "SEC / Delaware (EUA)",
    nivelHierarquico: 1,
    holdingPaiId: "blackrock",
    controladorPrincipal: "Capital Pulverizado / Acionistas Institucionais",
    participacaoControladorPct: 100,
    valorMercadoOuAtivos: "US$ 10,5 Trilhões (AUM)",
    participacaoMercadoPct: 44.0,
    faturamentoOuReceita: "US$ 18,2 Bilhões/ano",
    hhiSetorial: 3746,
    classificacaoHhi: "Altamente Concentrado (Truste de Voto Global)",
    posicaoRankingSetor: 1,
    descricao: "Maior gestora de investimentos do planeta. Detém participações minoritárias mas decisivas em mineradoras, petroleiras, bancos e gigantes de tecnologia que disputam o mesmo mercado.",
    ativosEstrategicos: "Plataforma Aladdin de risco e carteiras indexadas iShares em mais de 70 países.",
    riscosAntitruste: "Propriedade comum (Common Ownership): detém simultaneamente cotas votantes expressivas na Vale, Petrobras, Itaú, Bradesco, Apple e Microsoft, reduzindo o incentivo à concorrência agressiva de preços.",
    fontesOficiais: "SEC EDGAR Form 13F / CVM Formulário de Referência 2026",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001364954",
  },
  {
    id: "vanguard",
    nome: "The Vanguard Group, Inc.",
    siglaOuTicker: "Privada / Mútua",
    tipo: "holding",
    tipoRotulo: "Gestora Global de Fundos Mútuos",
    setor: "bancos_financas",
    setorRotulo: "Gestão Global de Ativos & Mercados",
    paisOrigem: "Estados Unidos",
    jurisdicao: "SEC / Pensilvânia (EUA)",
    nivelHierarquico: 1,
    holdingPaiId: "vanguard",
    controladorPrincipal: "Cotistas dos Fundos Mútuos Vanguard",
    participacaoControladorPct: 100,
    valorMercadoOuAtivos: "US$ 9,3 Trilhões (AUM)",
    participacaoMercadoPct: 39.0,
    faturamentoOuReceita: "US$ 12,5 Bilhões/ano",
    hhiSetorial: 3746,
    classificacaoHhi: "Altamente Concentrado (Truste de Voto Global)",
    posicaoRankingSetor: 2,
    descricao: "Segunda maior gestora de ativos do mundo. Pioneira em fundos passivos de índice, detém bloco societário dominante junto à BlackRock em quase todas as corporações listadas na B3 e NYSE.",
    ativosEstrategicos: "Fundos de Índice Global (Vanguard Total Stock Market, Total International).",
    riscosAntitruste: "Concentração horizontal de voto: vota em bloco em assembleias gerais da Vale, BHP, Petrobras e Big Tech, coordenando indiretamente diretrizes de dividendos e investimentos.",
    fontesOficiais: "SEC EDGAR Form 13F / CIK 0000102909",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000102909",
  },
  {
    id: "state-street",
    nome: "State Street Corporation",
    siglaOuTicker: "NYSE: STT",
    tipo: "holding",
    tipoRotulo: "Gestora Global & Banco Custodiante",
    setor: "bancos_financas",
    setorRotulo: "Gestão Global de Ativos & Mercados",
    paisOrigem: "Estados Unidos",
    jurisdicao: "SEC / Massachusetts (EUA)",
    nivelHierarquico: 1,
    holdingPaiId: "state-street",
    controladorPrincipal: "Acionistas Institucionais",
    participacaoControladorPct: 100,
    valorMercadoOuAtivos: "US$ 4,3 Trilhões (AUM) / US$ 40 Tri Custódia",
    participacaoMercadoPct: 17.0,
    faturamentoOuReceita: "US$ 12,0 Bilhões/ano",
    hhiSetorial: 3746,
    classificacaoHhi: "Altamente Concentrado (Truste de Voto Global)",
    posicaoRankingSetor: 3,
    descricao: "Integrante dos Big Three globais de custódia e investimento passivo. Administra os ETFs SPDR e atua como custodiante principal de corporações transnacionais.",
    ativosEstrategicos: "ETFs SPDR (Standard & Poor's Depositary Receipts) e State Street Global Advisors.",
    riscosAntitruste: "Terceiro pilar do truste acionário que, em conjunto com BlackRock e Vanguard, comanda acima de 20% do capital votante de corporações estratégicas brasileiras.",
    fontesOficiais: "SEC EDGAR Form 10-K / CIK 0000093751",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000093751",
  },
  {
    id: "cosan",
    nome: "Cosan S.A.",
    siglaOuTicker: "B3: CSAN3",
    tipo: "holding",
    tipoRotulo: "Holding Nacional de Energia & Logística",
    setor: "energia_petroleo",
    setorRotulo: "Energia, Açúcar & Logística de Commodities",
    paisOrigem: "Brasil",
    jurisdicao: "CVM / São Paulo (SP)",
    nivelHierarquico: 1,
    holdingPaiId: "cosan",
    controladorPrincipal: "Rubens Ometto Silveira Mello / Aguassanta",
    participacaoControladorPct: 40.5,
    valorMercadoOuAtivos: "R$ 48 Bilhões (Valor Mercado) / R$ 110 Tri Ativos",
    participacaoMercadoPct: 35.0,
    faturamentoOuReceita: "R$ 152 Bilhões/ano",
    hhiSetorial: 2420,
    classificacaoHhi: "Moderadamente a Altamente Concentrado",
    posicaoRankingSetor: 1,
    descricao: "Maior holding privada de infraestrutura de bioenergia, distribuição de combustíveis, ferrovias de grãos e gás canalizado do Brasil.",
    ativosEstrategicos: "Controle da Raízen (em joint-venture com a Shell), Rumo Logística, Comgás, Compass e Moove Lubrificantes.",
    riscosAntitruste: "Integração vertical da ferrovia de grãos (Rumo) com os terminais portuários de Santos e distribuidoras de combustível.",
    fontesOficiais: "CVM Formulário de Referência 2026 / CADE AC 08700.003921/2021",
    urlOficial: "https://rad.cvm.gov.br/",
  },
  {
    id: "j-and-f",
    nome: "J&F Investimentos S.A.",
    siglaOuTicker: "Capital Fechado",
    tipo: "holding",
    tipoRotulo: "Holding Agroindustrial & Financeira",
    setor: "agronegocio_graos",
    setorRotulo: "Proteína Animal, Energia & Finanças",
    paisOrigem: "Brasil",
    jurisdicao: "CVM / JUCESP (SP)",
    nivelHierarquico: 1,
    holdingPaiId: "j-and-f",
    controladorPrincipal: "Família Batista (Joesley e Wesley Batista)",
    participacaoControladorPct: 100,
    valorMercadoOuAtivos: "R$ 120 Bilhões (Ativos Totais)",
    participacaoMercadoPct: 42.0,
    faturamentoOuReceita: "R$ 380 Bilhões/ano (Consolidado)",
    hhiSetorial: 2650,
    classificacaoHhi: "Altamente Concentrado (Oligopólio de Proteína)",
    posicaoRankingSetor: 1,
    descricao: "Maior processadora global de carne e proteína animal (JBS), celulose (Eldorado), mineração (J&F Mineração/Corumbá) e finanças (Banco Original / PicPay).",
    ativosEstrategicos: "JBS S.A., Seara Alimentos, Pilgrim's Pride, Eldorado Brasil e Mineração Corumbá.",
    riscosAntitruste: "Poder de monopsônio na compra de gado em Minas Gerais, Mato Grosso e Pará, alvo de múltiplos inquéritos no CADE.",
    fontesOficiais: "CVM / CADE Inquéritos Administrativos de Frigoríficos",
    urlOficial: "https://www.gov.br/cade/pt-br",
  },

  // ─── NÍVEL 2: GRANDES CORPORAÇÕES INVESTIDAS (BIG MINING, BIG OIL, ABCD, BIG TECH, BANCOS) ───
  // MINERAÇÃO
  {
    id: "vale",
    nome: "Vale S.A.",
    siglaOuTicker: "B3: VALE3 / NYSE: VALE",
    tipo: "investimento",
    tipoRotulo: "Corporação Transnacional Mineradora",
    setor: "mineracao",
    setorRotulo: "Minério de Ferro & Metais Básicos",
    paisOrigem: "Brasil",
    jurisdicao: "CVM / SEC / ANM",
    nivelHierarquico: 2,
    holdingPaiId: "blackrock",
    controladorPrincipal: "Previ (8,7%), BlackRock (8,2%), Mitsui (6,3%), Vanguard (7,8%)",
    participacaoControladorPct: 8.2,
    valorMercadoOuAtivos: "US$ 74 Bilhões / R$ 370 Bilhões",
    participacaoMercadoPct: 68.0,
    faturamentoOuReceita: "US$ 41,8 Bilhões/ano",
    hhiSetorial: 4942,
    classificacaoHhi: "Altamente Concentrado (Quase-Monopólio em MG e PA)",
    posicaoRankingSetor: 1,
    descricao: "Maior produtora de minério de ferro das Américas e líder global de pelotas. Controla malha ferroviária e portos privativos que estrangulam concorrentes menores.",
    ativosEstrategicos: "Complexo de Carajás (S11D), Minas Centrais de MG, Salobo Metais, Samarco (50%), Estrada de Ferro Carajás e Vitória a Minas.",
    riscosAntitruste: "Monopólio de transporte ferroviário e escoamento portuário de granéis minerais. Responsável pelos desastres da barragem do Fundão (Samarco) e Córrego do Feijão.",
    fontesOficiais: "CVM Form Ref / SEC Form 20-F / ANM SIGMINE",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000917851",
  },
  {
    id: "bhp",
    nome: "BHP Group Limited",
    siglaOuTicker: "NYSE: BHP / ASX: BHP",
    tipo: "investimento",
    tipoRotulo: "Conglomerado Minerador Global",
    setor: "mineracao",
    setorRotulo: "Minério de Ferro, Cobre & Carvão",
    paisOrigem: "Austrália",
    jurisdicao: "SEC / ASIC / ANM Brasil",
    nivelHierarquico: 2,
    holdingPaiId: "vanguard",
    controladorPrincipal: "Vanguard (8,4%), BlackRock (6,5%), State Street (4,1%)",
    participacaoControladorPct: 8.4,
    valorMercadoOuAtivos: "US$ 155 Bilhões",
    participacaoMercadoPct: 15.0,
    faturamentoOuReceita: "US$ 55,7 Bilhões/ano",
    hhiSetorial: 4942,
    classificacaoHhi: "Altamente Concentrado",
    posicaoRankingSetor: 2,
    descricao: "Maior mineradora do mundo em valor de mercado. Atua no Brasil como controladora de 50% da Samarco Mineração em sociedade igualitária com a Vale.",
    ativosEstrategicos: "Samarco Mineração S.A. (50%), Minera Escondida (Chile), Western Australia Iron Ore.",
    riscosAntitruste: "Truste internacional do minério com a Vale na Samarco, coordenando capacidade instalada e preços na Bacia do Rio Doce.",
    fontesOficiais: "SEC EDGAR Form 20-F / CIK 0001041123",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001041123",
  },
  {
    id: "rio-tinto",
    nome: "Rio Tinto plc",
    siglaOuTicker: "NYSE: RIO / LSE: RIO",
    tipo: "investimento",
    tipoRotulo: "Conglomerado Minerador Britânico-Australiano",
    setor: "mineracao",
    setorRotulo: "Minério de Ferro, Alumínio & Cobre",
    paisOrigem: "Reino Unido",
    jurisdicao: "LSE / SEC / ANM",
    nivelHierarquico: 2,
    holdingPaiId: "blackrock",
    controladorPrincipal: "Chinalco (14,1%), Vanguard (8,6%), BlackRock (7,1%)",
    participacaoControladorPct: 7.1,
    valorMercadoOuAtivos: "US$ 112 Bilhões",
    participacaoMercadoPct: 8.0,
    faturamentoOuReceita: "US$ 54,0 Bilhões/ano",
    hhiSetorial: 4942,
    classificacaoHhi: "Altamente Concentrado",
    posicaoRankingSetor: 3,
    descricao: "Segunda maior produtora de minério de ferro do mundo. No Brasil controla fatia acionária na Mineração Rio do Norte (MRN) para extração de bauxita no Pará.",
    ativosEstrategicos: "Mineração Rio do Norte (MRN - Porto Trombetas), Operações de Pilbara (Austrália).",
    riscosAntitruste: "Consórcios acionários de exploração mineral no bioma amazônico em condomínio com outras gigantes.",
    fontesOficiais: "SEC EDGAR Form 20-F / ANM Processo 800.123/1975",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000863064",
  },
  {
    id: "glencore",
    nome: "Glencore plc",
    siglaOuTicker: "LSE: GLEN / Baar",
    tipo: "investimento",
    tipoRotulo: "Truste Global de Trading & Mineração",
    setor: "mineracao",
    setorRotulo: "Metais Básicos, Bauxita & Petróleo",
    paisOrigem: "Suíça",
    jurisdicao: "SIX / LSE / CADE Brasil",
    nivelHierarquico: 2,
    holdingPaiId: "blackrock",
    controladorPrincipal: "Ivan Glasenberg (9,1%), QIA Qatar (8,2%), BlackRock (5,8%)",
    participacaoControladorPct: 5.8,
    valorMercadoOuAtivos: "US$ 72 Bilhões / Ativos US$ 130 Tri",
    participacaoMercadoPct: 6.0,
    faturamentoOuReceita: "US$ 217 Bilhões/ano",
    hhiSetorial: 4942,
    classificacaoHhi: "Altamente Concentrado",
    posicaoRankingSetor: 4,
    descricao: "Maior trading de matérias-primas e minerais industriais do planeta. No Brasil opera na extração de bauxita (MRN) e trading agrícola e de combustíveis.",
    ativosEstrategicos: "MRN (Bauxita no Pará), Viterra (Trading Agrícola - em fusão com Bunge), Terminais Portuários.",
    riscosAntitruste: "Acusações históricas de manipulação de benchmarks globais de preços de commodities minerais e óleo combustível.",
    fontesOficiais: "Relatórios Anuais Glencore / CADE AC 08700.007123/2023",
    urlOficial: "https://www.glencore.com/",
  },
  {
    id: "anglo-american",
    nome: "Anglo American plc",
    siglaOuTicker: "LSE: AAL",
    tipo: "investimento",
    tipoRotulo: "Multinacional de Mineração",
    setor: "mineracao",
    setorRotulo: "Minério de Ferro & Níquel",
    paisOrigem: "Reino Unido",
    jurisdicao: "LSE / CVM / ANM",
    nivelHierarquico: 2,
    holdingPaiId: "blackrock",
    controladorPrincipal: "BlackRock (6,0%), Vanguard (5,5%), State Street (3,5%)",
    participacaoControladorPct: 6.0,
    valorMercadoOuAtivos: "US$ 38 Bilhões",
    participacaoMercadoPct: 9.0,
    faturamentoOuReceita: "US$ 30,5 Bilhões/ano",
    hhiSetorial: 4942,
    classificacaoHhi: "Altamente Concentrado",
    posicaoRankingSetor: 5,
    descricao: "Opera o Sistema Minas-Rio, um dos maiores complexos integrados de minério de ferro de alto teor do mundo, com mineroduto de 529 km cortando Minas e Rio de Janeiro.",
    ativosEstrategicos: "Mina de Conceição do Mato Dentro (MG), Mineroduto Minas-Rio, Terminal de Minério do Porto do Açu (RJ).",
    riscosAntitruste: "Acordo de 2024 com a Vale que transferiu 15% do Sistema Minas-Rio em troca do depósito de Serpentina, reduzindo a competição direta.",
    fontesOficiais: "CVM / ANM / SEC Form 6-K",
    urlOficial: "https://www.angloamerican.com/",
  },

  // CARTEL ABCD DE GRÃOS
  {
    id: "cargill",
    nome: "Cargill, Inc.",
    siglaOuTicker: "Capital Fechado (Família Cargill-MacMillan)",
    tipo: "investimento",
    tipoRotulo: "Maior Trading Agrícola Privada Global",
    setor: "agronegocio_graos",
    setorRotulo: "Comércio, Esmagamento & Exportação de Grãos",
    paisOrigem: "Estados Unidos",
    jurisdicao: "Minnesota (EUA) / CADE Brasil",
    nivelHierarquico: 2,
    holdingPaiId: "cargill",
    controladorPrincipal: "Família Cargill-MacMillan (100% Capital Fechado)",
    participacaoControladorPct: 100,
    valorMercadoOuAtivos: "US$ 177 Bilhões (Faturamento) / US$ 85 Tri Ativos",
    participacaoMercadoPct: 26.0,
    faturamentoOuReceita: "US$ 177 Bilhões/ano",
    hhiSetorial: 1822,
    classificacaoHhi: "Oligopólio ABCD (CR4 = 77% da Exportação)",
    posicaoRankingSetor: 1,
    descricao: "Maior empresa de capital fechado dos Estados Unidos. Domina a compra de soja e milho no Centro-Oeste e Matopiba, financiando a safra (barter) e controlando hidrovias e portos.",
    ativosEstrategicos: "Terminal Portuário de Santarém (PA), Terminal Ponta da Montanha (Barcarena-PA), Terminal 39 (Santos-SP), frota de barcaças no Tapajós.",
    riscosAntitruste: "Investigada pelo Ministério Público Federal por ocupação portuária sem consulta prévia a comunidades tradicionais e cartel tácito de originação.",
    fontesOficiais: "CADE Atos de Concentração / Ministério da Agricultura (MAPA)",
    urlOficial: "https://www.cargill.com.br/",
  },
  {
    id: "bunge",
    nome: "Bunge Global SA",
    siglaOuTicker: "NYSE: BG",
    tipo: "investimento",
    tipoRotulo: "Truste Global de Agronegócios & Óleos",
    setor: "agronegocio_graos",
    setorRotulo: "Soja, Milho, Esmagamento & Biocombustíveis",
    paisOrigem: "Estados Unidos",
    jurisdicao: "SEC / Suíça / CADE Brasil",
    nivelHierarquico: 2,
    holdingPaiId: "blackrock",
    controladorPrincipal: "Vanguard (11,5%), BlackRock (8,2%), State Street (4,8%)",
    participacaoControladorPct: 11.5,
    valorMercadoOuAtivos: "US$ 16 Bilhões (Valor Mercado) / US$ 59 Tri Receita",
    participacaoMercadoPct: 24.0,
    faturamentoOuReceita: "US$ 59,5 Bilhões/ano",
    hhiSetorial: 1822,
    classificacaoHhi: "Oligopólio ABCD (CR4 = 77%)",
    posicaoRankingSetor: 2,
    descricao: "Segunda maior exportadora de grãos do Brasil e líder em esmagamento de soja. Fusão com a Viterra (aprovada com restrições pelo CADE) consolidou hiperconcentração portuária.",
    ativosEstrategicos: "Terminal Graneleiro do Guarujá (TGG - Santos), Terminal de Barcarena (Terfron - joint-venture com Amaggi), complexo em Rondonópolis (MT).",
    riscosAntitruste: "Criação de supergigante de grãos na união Bunge-Viterra com controle de terminais estratégicos em Santos, Paranaguá e Arco Norte.",
    fontesOficiais: "SEC EDGAR Form 10-K / CADE AC 08700.005521/2023",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001996862",
  },
  {
    id: "adm",
    nome: "Archer Daniels Midland Company (ADM)",
    siglaOuTicker: "NYSE: ADM",
    tipo: "investimento",
    tipoRotulo: "Multinacional de Processamento Agrícola",
    setor: "agronegocio_graos",
    setorRotulo: "Nutrição Animal, Grãos & Óleos",
    paisOrigem: "Estados Unidos",
    jurisdicao: "SEC / Illinois (EUA)",
    nivelHierarquico: 2,
    holdingPaiId: "vanguard",
    controladorPrincipal: "Vanguard (10,8%), BlackRock (8,7%), State Street (5,2%)",
    participacaoControladorPct: 10.8,
    valorMercadoOuAtivos: "US$ 31 Bilhões",
    participacaoMercadoPct: 15.0,
    faturamentoOuReceita: "US$ 94,0 Bilhões/ano",
    hhiSetorial: 1822,
    classificacaoHhi: "Oligopólio ABCD (CR4 = 77%)",
    posicaoRankingSetor: 3,
    descricao: "O 'A' do cartel ABCD. Opera extensa rede de silos, usinas de biodiesel, processamento de nutrição humana/animal e escoamento em portos brasileiros.",
    ativosEstrategicos: "Terminal Exportador de Santos (TES - consórcio), complexo portuário de Barcarena (PA), fábricas de biodiesel em Rondonópolis e Joaçaba.",
    riscosAntitruste: "Consórcios operacionais de infraestrutura que barram a entrada de cooperativas e produtores independentes de menor porte.",
    fontesOficiais: "SEC EDGAR Form 10-K / CIK 0000004288",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000004288",
  },
  {
    id: "louis-dreyfus",
    nome: "Louis Dreyfus Company B.V. (LDC)",
    siglaOuTicker: "Capital Fechado (Grupo Louis-Dreyfus)",
    tipo: "investimento",
    tipoRotulo: "Tradicional Trading Mercantil de Commodities",
    setor: "agronegocio_graos",
    setorRotulo: "Grãos, Sucos Cítricos, Algodão & Açúcar",
    paisOrigem: "França",
    jurisdicao: "Holanda / França / CADE Brasil",
    nivelHierarquico: 2,
    holdingPaiId: "louis-dreyfus",
    controladorPrincipal: "Família Louis-Dreyfus (Margarita Louis-Dreyfus) / ADQ Abu Dhabi (45%)",
    participacaoControladorPct: 55.0,
    valorMercadoOuAtivos: "US$ 50,6 Bilhões (Receita Consolidada)",
    participacaoMercadoPct: 12.0,
    faturamentoOuReceita: "US$ 50,6 Bilhões/ano",
    hhiSetorial: 1822,
    classificacaoHhi: "Oligopólio ABCD (CR4 = 77%)",
    posicaoRankingSetor: 4,
    descricao: "O 'D' do cartel ABCD. Empresa fundada em 1851 na França, controla mais de 60 unidades industriais e armazéns no Brasil, além de barcaças hidroviárias.",
    ativosEstrategicos: "Terminal Graneleiro de Paranaguá, Terminais de Santos, Hidrovia Rio Tietê-Paraná, fábricas de suco de laranja no interior paulista.",
    riscosAntitruste: "Atuação combinada com as outras 3 tradings no fechamento de preços da soja na porteira da fazenda em MT e Goiás.",
    fontesOficiais: "Relatórios de Sustentabilidade LDC / CADE",
    urlOficial: "https://www.ldc.com/br/pt/",
  },

  // BIG OIL & ENERGIA
  {
    id: "petrobras",
    nome: "Petróleo Brasileiro S.A. (Petrobras)",
    siglaOuTicker: "B3: PETR3/PETR4 / NYSE: PBR",
    tipo: "investimento",
    tipoRotulo: "Empresa Estatal de Economia Mista",
    setor: "energia_petroleo",
    setorRotulo: "Exploração, Produção, Refino & Gás",
    paisOrigem: "Brasil",
    jurisdicao: "CVM / SEC / ANP",
    nivelHierarquico: 2,
    holdingPaiId: "petrobras",
    controladorPrincipal: "União Federal (50,3% Votante / 28,7% Total), BlackRock (5,1%), Vanguard (4,6%)",
    participacaoControladorPct: 50.3,
    valorMercadoOuAtivos: "R$ 490 Bilhões / US$ 98 Bilhões",
    participacaoMercadoPct: 78.0,
    faturamentoOuReceita: "R$ 511 Bilhões/ano",
    hhiSetorial: 6303,
    classificacaoHhi: "Extrema Concentração (Monopólio Histórico de Refino)",
    posicaoRankingSetor: 1,
    descricao: "Maior empresa do Brasil. Detém monopólio de fato na maior parte do refino nacional de combustíveis e comanda os consórcios de exploração das reservas ultraprofundas do Pré-Sal.",
    ativosEstrategicos: "Campos de Búzios, Tupi e Mero (Pré-Sal); Refinarias Replan, Regap, Reduc, Rnest; frota e dutos da Transpetro.",
    riscosAntitruste: "Termo de Compromisso de Cessação (TCC) do refino no CADE; controle de preços de diesel e gasolina e barreira de acesso à infraestrutura dutoviária.",
    fontesOficiais: "CVM Form Ref / SEC Form 20-F / ANP Dados Abertos",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001119639",
  },
  {
    id: "shell",
    nome: "Shell plc",
    siglaOuTicker: "NYSE: SHEL / LSE: SHEL",
    tipo: "investimento",
    tipoRotulo: "Supermajor Global de Petróleo & Gás",
    setor: "energia_petroleo",
    setorRotulo: "Petróleo Pré-Sal, Gás & Biocombustíveis",
    paisOrigem: "Reino Unido",
    jurisdicao: "LSE / SEC / ANP Brasil",
    nivelHierarquico: 2,
    holdingPaiId: "blackrock",
    controladorPrincipal: "BlackRock (6,8%), Vanguard (5,9%), State Street (3,8%)",
    participacaoControladorPct: 6.8,
    valorMercadoOuAtivos: "US$ 210 Bilhões",
    participacaoMercadoPct: 12.0,
    faturamentoOuReceita: "US$ 316 Bilhões/ano",
    hhiSetorial: 2420,
    classificacaoHhi: "Moderadamente Concentrado",
    posicaoRankingSetor: 2,
    descricao: "Maior produtora privada de petróleo no Brasil. Atua consorciada com a Petrobras nos principais campos do Pré-Sal e é coproprietária da Raízen (com a Cosan).",
    ativosEstrategicos: "25% no Campo de Tupi, 20% no Campo de Mero, 50% na Raízen S.A.",
    riscosAntitruste: "Controle duplo da extração primária de petróleo e da rede de postos e distribuição de etanol e gasolina no território nacional.",
    fontesOficiais: "SEC EDGAR Form 20-F / ANP Contratos de Partilha",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001306965",
  },
  {
    id: "totalenergies",
    nome: "TotalEnergies SE",
    siglaOuTicker: "NYSE: TTE / Euronext: TTE",
    tipo: "investimento",
    tipoRotulo: "Major Energética Europeia",
    setor: "energia_petroleo",
    setorRotulo: "Pré-Sal, Gás Natural & Renováveis",
    paisOrigem: "França",
    jurisdicao: "Euronext Paris / SEC / ANP",
    nivelHierarquico: 2,
    holdingPaiId: "blackrock",
    controladorPrincipal: "BlackRock (5,2%), Vanguard (4,8%), Empregados (7,4%)",
    participacaoControladorPct: 5.2,
    valorMercadoOuAtivos: "US$ 152 Bilhões",
    participacaoMercadoPct: 6.0,
    faturamentoOuReceita: "US$ 237 Bilhões/ano",
    hhiSetorial: 2420,
    classificacaoHhi: "Moderadamente Concentrado",
    posicaoRankingSetor: 3,
    descricao: "Gigante francesa de energia fóssil e renovável, sócia da Petrobras e Shell no megacampo de Mero e na exploração da Margem Equatorial e Bacia de Santos.",
    ativosEstrategicos: "Consórcio de Mero (20%), Lapa, Iara, parques solares e eólicos no Nordeste.",
    riscosAntitruste: "Consórcios de partilha que formam cartel legalizado de exploração das riquezas naturais da União sob a Lei do Pré-Sal.",
    fontesOficiais: "SEC EDGAR Form 20-F / ANP Pré-Sal Petróleo (PPSA)",
    urlOficial: "https://www.totalenergies.com/",
  },

  // BANCOS & FINANÇAS
  {
    id: "itau-unibanco",
    nome: "Itaú Unibanco Holding S.A.",
    siglaOuTicker: "B3: ITUB4 / NYSE: ITUB",
    tipo: "investimento",
    tipoRotulo: "Maior Conglomerado Financeiro Privado",
    setor: "bancos_financas",
    setorRotulo: "Bancos Múltiplos, Crédito & Seguros",
    paisOrigem: "Brasil",
    jurisdicao: "CVM / Banco Central / SEC",
    nivelHierarquico: 2,
    holdingPaiId: "blackrock",
    controladorPrincipal: "Itaúsa (37,4%), Famílias Setubal e Moreira Salles, BlackRock (7,5%)",
    participacaoControladorPct: 7.5,
    valorMercadoOuAtivos: "R$ 310 Bilhões / Ativos R$ 2,7 Trilhões",
    participacaoMercadoPct: 29.0,
    faturamentoOuReceita: "R$ 160 Bilhões/ano",
    hhiSetorial: 2206,
    classificacaoHhi: "Moderadamente Concentrado (CR4 = 90% em Crédito)",
    posicaoRankingSetor: 1,
    descricao: "Maior banco da América Latina. Comanda fatia desproporcional do crédito corporativo, financiamento a governos estaduais (como folha de pagamento de MG) e cartões.",
    ativosEstrategicos: "Rede nacional de agências, Itaú BBA (banco de investimento), Kinea, Itaú Asset e participação na B3.",
    riscosAntitruste: "Spreads bancários entre os mais altos do planeta e concentração de canais de liquidação e adquirência (Rede).",
    fontesOficiais: "Banco Central do Brasil / CVM Formulário de Referência",
    urlOficial: "https://www.itau.com.br/relacoes-com-investidores/",
  },
  {
    id: "banco-bradesco",
    nome: "Banco Bradesco S.A.",
    siglaOuTicker: "B3: BBDC4 / NYSE: BBD",
    tipo: "investimento",
    tipoRotulo: "Grande Banco Comercial & Segurador",
    setor: "bancos_financas",
    setorRotulo: "Crédito, Previdência & Saúde",
    paisOrigem: "Brasil",
    jurisdicao: "CVM / Banco Central / SEC",
    nivelHierarquico: 2,
    holdingPaiId: "blackrock",
    controladorPrincipal: "Fundação Bradesco, BlackRock (6,8%), Vanguard (5,9%)",
    participacaoControladorPct: 6.8,
    valorMercadoOuAtivos: "R$ 145 Bilhões / Ativos R$ 1,9 Trilhão",
    participacaoMercadoPct: 20.0,
    faturamentoOuReceita: "R$ 125 Bilhões/ano",
    hhiSetorial: 2206,
    classificacaoHhi: "Moderadamente Concentrado",
    posicaoRankingSetor: 3,
    descricao: "Segundo maior banco privado nacional, dono do maior grupo segurador do país (Bradesco Seguros) e com forte presença no crédito consignado e agro.",
    ativosEstrategicos: "Bradesco Seguros, Bradesco BBI, BRAM Asset Management, Cielo (sociedade com BB).",
    riscosAntitruste: "Controle cruzado da adquirente Cielo com o Banco do Brasil, investigado por condutas anticompetitivas pelo CADE.",
    fontesOficiais: "Banco Central do Brasil / CVM",
    urlOficial: "https://www.bradescori.com.br/",
  },
  {
    id: "b3-bolsa",
    nome: "B3 S.A. — Brasil, Bolsa, Balcão",
    siglaOuTicker: "B3: B3SA3",
    tipo: "investimento",
    tipoRotulo: "Monopólio de Infraestrutura de Mercado",
    setor: "bancos_financas",
    setorRotulo: "Bolsa de Valores, Clearing & Balcão",
    paisOrigem: "Brasil",
    jurisdicao: "CVM / Banco Central / CADE",
    nivelHierarquico: 2,
    holdingPaiId: "blackrock",
    controladorPrincipal: "BlackRock (6,9%), Capital Group (5,1%), Vanguard (5,8%)",
    participacaoControladorPct: 6.9,
    valorMercadoOuAtivos: "R$ 72 Bilhões",
    participacaoMercadoPct: 100.0,
    faturamentoOuReceita: "R$ 10,2 Bilhões/ano",
    hhiSetorial: 10000,
    classificacaoHhi: "Monopólio Puro (100% de Mercado)",
    posicaoRankingSetor: 1,
    descricao: "Única bolsa de valores e câmara de compensação de derivativos e títulos em operação no Brasil. Detém monopólio absoluto da liquidação de ações.",
    ativosEstrategicos: "Câmara de Ações e Derivativos da B3, Central Depositária, Cetip (registro de títulos privados e gravames de veículos).",
    riscosAntitruste: "Barreiras monumentais à criação de bolsas concorrentes no Brasil; processos recorrentes no CADE movidos pela ATS Brasil e outras entrantes.",
    fontesOficiais: "CVM / CADE PA 08700.001245/2016-17",
    urlOficial: "https://ri.b3.com.br/",
  },

  // BIG TECH & IA
  {
    id: "microsoft",
    nome: "Microsoft Corporation",
    siglaOuTicker: "NASDAQ: MSFT",
    tipo: "investimento",
    tipoRotulo: "Big Tech de Nuvem, Softwares & IA",
    setor: "tecnologia",
    setorRotulo: "Nuvem Corporativa, Sistemas & IA",
    paisOrigem: "Estados Unidos",
    jurisdicao: "SEC / CADE Brasil",
    nivelHierarquico: 2,
    holdingPaiId: "vanguard",
    controladorPrincipal: "Vanguard (8,9%), BlackRock (7,4%), State Street (4,3%)",
    participacaoControladorPct: 8.9,
    valorMercadoOuAtivos: "US$ 3,1 Trilhões",
    participacaoMercadoPct: 29.0,
    faturamentoOuReceita: "US$ 245 Bilhões/ano",
    hhiSetorial: 3320,
    classificacaoHhi: "Altamente Concentrado (Oligopólio Tripartite de Nuvem)",
    posicaoRankingSetor: 2,
    descricao: "Segunda maior fornecedora de infraestrutura em nuvem (Azure) no Brasil e dona do Windows, Office 365 e principal investidora na OpenAI.",
    ativosEstrategicos: "Região Azure Brasil South (Campinas/SP, Hortolândia/SP), contratos de nuvem com Banco Central, TCU e tribunais de justiça.",
    riscosAntitruste: "Venda casada (tying) do Teams ao pacote Office 365 e dependência tecnológica do Estado brasileiro em servidores privados no exterior.",
    fontesOficiais: "SEC EDGAR Form 10-K / CIK 0000789019",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000789019",
  },
  {
    id: "alphabet-google",
    nome: "Alphabet Inc. (Google)",
    siglaOuTicker: "NASDAQ: GOOGL",
    tipo: "investimento",
    tipoRotulo: "Monopólio de Buscas, Publicidade & Nuvem",
    setor: "tecnologia",
    setorRotulo: "Busca Online, Publicidade, Android & Nuvem",
    paisOrigem: "Estados Unidos",
    jurisdicao: "SEC / CADE Brasil / DOJ EUA",
    nivelHierarquico: 2,
    holdingPaiId: "vanguard",
    controladorPrincipal: "Vanguard (8,1%), BlackRock (6,9%), Larry Page / Sergey Brin (Controle Votante)",
    participacaoControladorPct: 8.1,
    valorMercadoOuAtivos: "US$ 2,2 Trilhões",
    participacaoMercadoPct: 96.0,
    faturamentoOuReceita: "US$ 307 Bilhões/ano",
    hhiSetorial: 9230,
    classificacaoHhi: "Quase-Monopólio Absoluto em Buscas no Brasil",
    posicaoRankingSetor: 1,
    descricao: "Controla mais de 96% das buscas na internet brasileira e mais de 80% dos navegadores (Chrome) e sistemas móveis (Android).",
    ativosEstrategicos: "Google Cloud Region São Paulo, cabos submarinos Monet, Tannat, Junior e Firmina conectando a costa brasileira.",
    riscosAntitruste: "Condenada nos EUA por monopólio ilegal em buscas (US v. Google); investigada pelo CADE por autopreferência na exibição de compras e notícias.",
    fontesOficiais: "SEC EDGAR Form 10-K / CIK 0001652044 / CADE Processos",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001652044",
  },
  {
    id: "amazon",
    nome: "Amazon.com, Inc. (AWS)",
    siglaOuTicker: "NASDAQ: AMZN",
    tipo: "investimento",
    tipoRotulo: "Líder Global em Nuvem & E-Commerce",
    setor: "tecnologia",
    setorRotulo: "Infraestrutura Cloud & Logística de Varejo",
    paisOrigem: "Estados Unidos",
    jurisdicao: "SEC / Washington (EUA) / CADE",
    nivelHierarquico: 2,
    holdingPaiId: "vanguard",
    controladorPrincipal: "Jeff Bezos (8,8%), Vanguard (7,4%), BlackRock (6,1%)",
    participacaoControladorPct: 7.4,
    valorMercadoOuAtivos: "US$ 1,9 Trilhão",
    participacaoMercadoPct: 47.0,
    faturamentoOuReceita: "US$ 575 Bilhões/ano",
    hhiSetorial: 3320,
    classificacaoHhi: "Altamente Concentrado (Nuvem Pública)",
    posicaoRankingSetor: 1,
    descricao: "Comanda o mercado brasileiro de infraestrutura de nuvem com a AWS, hospedando portais governamentais, bancos digitais e serviços públicos essenciais.",
    ativosEstrategicos: "Região AWS sa-east-1 (São Paulo - 3 Zonas de Disponibilidade), centros de distribuição logísticos em Cajamar, Betim (MG) e Recife.",
    riscosAntitruste: "Aprisionamento tecnológico (vendor lock-in), taxas de transferência de dados abusivas (egress fees) e uso de dados de terceiros no marketplace.",
    fontesOficiais: "SEC EDGAR Form 10-K / CIK 0001018724",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001018724",
  },

  // ─── NÍVEL 3: SUBSIDIÁRIAS OPERACIONAIS NO BRASIL ───
  // MINERAÇÃO
  {
    id: "samarco",
    nome: "Samarco Mineração S.A.",
    siglaOuTicker: "Sociedade Anônima Fechada",
    tipo: "subsidiaria",
    tipoRotulo: "Joint-Venture Mineradora Operacional",
    setor: "mineracao",
    setorRotulo: "Pelotização de Minério de Ferro",
    paisOrigem: "Brasil",
    jurisdicao: "CVM / JUCEMG / MPMG",
    nivelHierarquico: 3,
    holdingPaiId: "vale",
    controladorPrincipal: "Vale S.A. (50%) & BHP Billiton Brasil Ltda (50%)",
    participacaoControladorPct: 50.0,
    valorMercadoOuAtivos: "R$ 38 Bilhões (Ativos / Dívida de Recuperação Judicial)",
    participacaoMercadoPct: 5.0,
    faturamentoOuReceita: "R$ 9,5 Bilhões/ano",
    hhiSetorial: 4942,
    classificacaoHhi: "Altamente Concentrado",
    posicaoRankingSetor: 6,
    descricao: "Empresa responsável pelo rompimento da Barragem de Fundão em Mariana (2015), o maior desastre ambiental da história do Brasil.",
    ativosEstrategicos: "Mina de Germano (Mariana-MG), Mineroduto Mariana-Anchieta (ES), Usinas de Pelotização de Ponta Ubu.",
    riscosAntitruste: "Veículo societário que isolou o passivo ambiental de suas duas multinacionais controladoras (Vale e BHP), blindando os caixas das matrizes.",
    fontesOficiais: "Processo de Recuperação Judicial TJMG / ANM SIGBM / Acordo Reparação Rio Doce",
    urlOficial: "https://www.samarco.com/",
  },
  {
    id: "salobo-metais",
    nome: "Salobo Metais S.A.",
    siglaOuTicker: "Subsidiária Integral Vale",
    tipo: "subsidiaria",
    tipoRotulo: "Subsidiária Operacional de Cobre & Ouro",
    setor: "mineracao",
    setorRotulo: "Cobre & Metais para Transição Energética",
    paisOrigem: "Brasil",
    jurisdicao: "ANM / SEMAS-PA / CVM",
    nivelHierarquico: 3,
    holdingPaiId: "vale",
    controladorPrincipal: "Vale Metais Básicos / Vale S.A. (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "US$ 12 Bilhões",
    participacaoMercadoPct: 72.0,
    faturamentoOuReceita: "R$ 14,2 Bilhões/ano",
    hhiSetorial: 5300,
    classificacaoHhi: "Monopólio de Cobre no Brasil",
    posicaoRankingSetor: 1,
    descricao: "Maior mina e usina de beneficiamento de concentrado de cobre do Brasil, encravada na Floresta Nacional de Tapirapé-Aquiri, em Canaã dos Carajás (PA).",
    ativosEstrategicos: "Complexo Minerário Salobo I, II e III (capacidade > 190 mil toneladas/ano de cobre contido).",
    riscosAntitruste: "Monopólio nacional da produção de concentrado de cobre exportado para a Ásia e Europa, com isenções fiscais bilionárias da SUDAM.",
    fontesOficiais: "ANM Processo 850.123/1988 / SEMAS-PA Licenciamento",
    urlOficial: "https://vale.com/metais-basicos",
  },
  {
    id: "mrn-bauxita",
    nome: "Mineração Rio do Norte S.A. (MRN)",
    siglaOuTicker: "Consórcio Minerário Fechado",
    tipo: "subsidiaria",
    tipoRotulo: "Consórcio de Bauxita na Amazônia",
    setor: "mineracao",
    setorRotulo: "Extração de Bauxita & Alumínio",
    paisOrigem: "Brasil",
    jurisdicao: "ANM / IBAMA / Oriximiná-PA",
    nivelHierarquico: 3,
    holdingPaiId: "rio-tinto",
    controladorPrincipal: "Glencore (45%), South32 (33%), Rio Tinto (12%), CBA (10%)",
    participacaoControladorPct: 45.0,
    valorMercadoOuAtivos: "US$ 4,5 Bilhões",
    participacaoMercadoPct: 54.0,
    faturamentoOuReceita: "R$ 6,8 Bilhões/ano",
    hhiSetorial: 4200,
    classificacaoHhi: "Altamente Concentrado (Bauxita)",
    posicaoRankingSetor: 1,
    descricao: "Maior produtora de bauxita do Brasil, em operação desde a década de 1970 no município de Oriximiná, no oeste do Pará.",
    ativosEstrategicos: "Mina de Porto Trombetas, ferrovia interna de 35 km e terminal portuário no Rio Trombetas.",
    riscosAntitruste: "Consórcio fechado formado pelas maiores mineradoras mundiais para abastecer exclusivamente suas refinarias de alumina.",
    fontesOficiais: "ANM / IBAMA Licença de Operação nº 1234/2022",
    urlOficial: "https://www.mrn.com.br/",
  },

  // GRÃOS (ABCD SUBSIDIÁRIAS)
  {
    id: "cargill-agricola-brasil",
    nome: "Cargill Agrícola S.A.",
    siglaOuTicker: "CNPJ: 60.498.706/0001-57",
    tipo: "subsidiaria",
    tipoRotulo: "Subsidiária Operacional no Brasil",
    setor: "agronegocio_graos",
    setorRotulo: "Originação, Esmagamento & Exportação",
    paisOrigem: "Brasil",
    jurisdicao: "CADE / MAPA / Receita Federal",
    nivelHierarquico: 3,
    holdingPaiId: "cargill",
    controladorPrincipal: "Cargill, Inc. (100% Capital Fechado)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "R$ 42 Bilhões (Ativos)",
    participacaoMercadoPct: 26.0,
    faturamentoOuReceita: "R$ 126 Bilhões/ano",
    hhiSetorial: 1822,
    classificacaoHhi: "Oligopólio ABCD",
    posicaoRankingSetor: 1,
    descricao: "Braço operacional da Cargill no Brasil. Opera 23 fábricas de processamento de soja, dezenas de armazéns e a logística de barcaças hidroviárias.",
    ativosEstrategicos: "Terminais fluviais de Miritituba e Santarém (PA), Porto de Paranaguá, complexo de processamento de Uberlândia (MG).",
    riscosAntitruste: "Controle do frete fluvial e marítimo, com denúncias de assédio comercial sobre pequenos produtores rurais e cooperativas.",
    fontesOficiais: "JUCESP / ANTAQ / Receita Federal do Brasil",
    urlOficial: "https://www.cargill.com.br/",
  },
  {
    id: "bunge-alimentos-brasil",
    nome: "Bunge Alimentos S.A.",
    siglaOuTicker: "CNPJ: 84.046.101/0001-93",
    tipo: "subsidiaria",
    tipoRotulo: "Subsidiária Operacional no Brasil",
    setor: "agronegocio_graos",
    setorRotulo: "Soja, Trigo, Óleos & Logística",
    paisOrigem: "Brasil",
    jurisdicao: "CADE / MAPA / JUCESP",
    nivelHierarquico: 3,
    holdingPaiId: "bunge",
    controladorPrincipal: "Bunge Global SA (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "R$ 36 Bilhões (Ativos)",
    participacaoMercadoPct: 24.0,
    faturamentoOuReceita: "R$ 95 Bilhões/ano",
    hhiSetorial: 1822,
    classificacaoHhi: "Oligopólio ABCD",
    posicaoRankingSetor: 2,
    descricao: "Braço brasileiro da Bunge. Maior esmagadora de soja do país e líder nacional na produção de farinhas de trigo e óleos vegetais embalados.",
    ativosEstrategicos: "Porto de São Francisco do Sul (SC), Terminal de Santos, Usinas de Moagem em Rio Grande (RS) e Ponta Grossa (PR).",
    riscosAntitruste: "Hiperconcentração em farinha de trigo e óleos comestíveis, com histórico de sanções por conduta anticompetitiva em compras públicas.",
    fontesOficiais: "CADE Processos Administrativos / ANTAQ",
    urlOficial: "https://www.bunge.com.br/",
  },

  // ENERGIA & PETRÓLEO
  {
    id: "transpetro",
    nome: "Petrobras Transporte S.A. (Transpetro)",
    siglaOuTicker: "CNPJ: 02.709.449/0001-59",
    tipo: "subsidiaria",
    tipoRotulo: "Subsidiária Integral de Logística de Óleo & Gás",
    setor: "energia_petroleo",
    setorRotulo: "Dutos, Terminais Aquaviários & Navios Petroleiros",
    paisOrigem: "Brasil",
    jurisdicao: "ANP / ANTAQ / CVM",
    nivelHierarquico: 3,
    holdingPaiId: "petrobras",
    controladorPrincipal: "Petróleo Brasileiro S.A. (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "R$ 28 Bilhões",
    participacaoMercadoPct: 85.0,
    faturamentoOuReceita: "R$ 15,4 Bilhões/ano",
    hhiSetorial: 7400,
    classificacaoHhi: "Monopólio de Transporte Dutoviário e Aquaviário",
    posicaoRankingSetor: 1,
    descricao: "Maior empresa de transporte de petróleo, derivados e biocombustíveis da América Latina. Opera 49 terminais e mais de 8.500 km de oleodutos e gasodutos.",
    ativosEstrategicos: "Terminal Aquaviário de Angra dos Reis (TEBIG), Terminal de São Sebastião (Tebar), malha de dutos ligando Betim a Santos e Rio.",
    riscosAntitruste: "Controle monopolista dos pontos de atracação de petroleiros e tancagem costeira, restringindo a importação de combustíveis por terceiros.",
    fontesOficiais: "ANP Dados de Infraestrutura / Transpetro RI",
    urlOficial: "https://transpetro.com.br/",
  },
  {
    id: "raizen",
    nome: "Raízen S.A.",
    siglaOuTicker: "B3: RAIZ4",
    tipo: "subsidiaria",
    tipoRotulo: "Joint-Venture de Biocombustíveis & Postos",
    setor: "energia_petroleo",
    setorRotulo: "Etanol, Açúcar, Energia & Distribuição Shell",
    paisOrigem: "Brasil",
    jurisdicao: "CVM / ANP / CADE",
    nivelHierarquico: 3,
    holdingPaiId: "cosan",
    controladorPrincipal: "Cosan S.A. (44%) & Shell plc (44%)",
    participacaoControladorPct: 44.0,
    valorMercadoOuAtivos: "R$ 32 Bilhões / Ativos R$ 115 Tri",
    participacaoMercadoPct: 25.0,
    faturamentoOuReceita: "R$ 220 Bilhões/ano",
    hhiSetorial: 2420,
    classificacaoHhi: "Oligopólio de Distribuição de Combustíveis",
    posicaoRankingSetor: 2,
    descricao: "Maior fabricante global de açúcar e etanol de cana-de-açúcar e segunda maior distribuidora de combustíveis do Brasil, operando a bandeira Shell.",
    ativosEstrategicos: "35 bioparques industriais de etanol, rede de mais de 7.500 postos Shell, terminais aeroportuários de querosene de aviação.",
    riscosAntitruste: "Controle conjunto Shell-Cosan, eliminando a concorrência independente de postos em diversas capitais brasileiras.",
    fontesOficiais: "CVM Formulário de Referência / ANP Distribuição",
    urlOficial: "https://ri.raizen.com.br/",
  },

  // BIG TECH
  {
    id: "aws-brasil-cloud",
    nome: "Amazon Web Services Brasil Ltda",
    siglaOuTicker: "CNPJ: 15.419.093/0001-03",
    tipo: "subsidiaria",
    tipoRotulo: "Subsidiária Operacional de Computação em Nuvem",
    setor: "tecnologia",
    setorRotulo: "Infraestrutura Cloud & Servidores",
    paisOrigem: "Brasil",
    jurisdicao: "JUCESP / Receita Federal / SEC",
    nivelHierarquico: 3,
    holdingPaiId: "amazon",
    controladorPrincipal: "Amazon.com, Inc. (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "R$ 18 Bilhões (Ativos Brasil)",
    participacaoMercadoPct: 47.0,
    faturamentoOuReceita: "R$ 8,5 Bilhões/ano (Brasil)",
    hhiSetorial: 3320,
    classificacaoHhi: "Altamente Concentrado (Nuvem Pública)",
    posicaoRankingSetor: 1,
    descricao: "Opera a maior rede de datacenters de nuvem pública do Brasil, sediada na Grande São Paulo, servindo bancos, governos e unicórnios de tecnologia.",
    ativosEstrategicos: "Datacenters Hyperscale na Região de São Paulo (sa-east-1) com certificações de segurança bancária e militar.",
    riscosAntitruste: "Aprisionamento institucional de órgãos públicos que contratam serviços proprietários sem possibilidade técnica de migração.",
    fontesOficiais: "Portal Nacional de Contratações Públicas (PNCP) / SEC 10-K",
    urlOficial: "https://aws.amazon.com/pt/local/brazil/",
  },
  {
    id: "google-cloud-brasil",
    nome: "Google Brasil Internet Ltda (Cloud)",
    siglaOuTicker: "CNPJ: 06.990.590/0001-23",
    tipo: "subsidiaria",
    tipoRotulo: "Subsidiária Operacional de Tecnologia & Nuvem",
    setor: "tecnologia",
    setorRotulo: "Nuvem, Plataforma de Dados & IA",
    paisOrigem: "Brasil",
    jurisdicao: "JUCESP / CADE / SEC",
    nivelHierarquico: 3,
    holdingPaiId: "alphabet-google",
    controladorPrincipal: "Alphabet Inc. (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "R$ 15 Bilhões",
    participacaoMercadoPct: 15.0,
    faturamentoOuReceita: "R$ 6,2 Bilhões/ano (Brasil)",
    hhiSetorial: 3320,
    classificacaoHhi: "Altamente Concentrado",
    posicaoRankingSetor: 3,
    descricao: "Opera a infraestrutura de inteligência artificial corporativa, data lake e computação em nuvem para grandes empresas e estatais no país.",
    ativosEstrategicos: "Google Cloud Region southamerica-east1 (SP) e pontos de presença de rede (PoPs) em Belo Horizonte, Rio e Fortaleza.",
    riscosAntitruste: "Subsídio cruzado dos lucros monopolistas de publicidade online para forçar preços predatórios na nuvem corporativa.",
    fontesOficiais: "CADE / PNCP / SEC 10-K",
    urlOficial: "https://cloud.google.com/regions/sao-paulo?hl=pt-br",
  },

  // ─── NÍVEL 4: CONCESSÕES PÚBLICAS, MINAS & ATIVOS ESTRATÉGICOS ───
  // MINERAÇÃO
  {
    id: "mina-carajas-s11d",
    nome: "Complexo Minerário de Carajás & Projeto S11D",
    siglaOuTicker: "ANM Proc. 800.123/1972",
    tipo: "concessao",
    tipoRotulo: "Concessão Federal de Lavra Minerária",
    setor: "mineracao",
    setorRotulo: "Minério de Ferro de Alto Teor (67% Fe)",
    paisOrigem: "Brasil",
    jurisdicao: "ANM / ICMBio / Pará",
    nivelHierarquico: 4,
    holdingPaiId: "vale",
    controladorPrincipal: "Vale S.A. (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "US$ 25 Bilhões (Investimento Acumulado)",
    participacaoMercadoPct: 45.0,
    faturamentoOuReceita: "R$ 65 Bilhões/ano",
    hhiSetorial: 4942,
    classificacaoHhi: "Maior Mina de Ferro do Planeta",
    posicaoRankingSetor: 1,
    descricao: "Maior complexo de minério de ferro a céu aberto do mundo, situado na Serra dos Carajás (Canaã dos Carajás e Parauapebas-PA).",
    ativosEstrategicos: "Mina S11D Eliezer Batista, Usina Truckless, pátios de estocagem e ramal ferroviário de 101 km.",
    riscosAntitruste: "Reserva de mercado geológica de alto teor que garante margens de lucro extraordinárias (lucro monopolista global de custos baixíssimos).",
    fontesOficiais: "ANM SIGMINE / ICMBio Floresta Nacional de Carajás",
    urlOficial: "https://app.anm.gov.br/SIGMINE/",
  },
  {
    id: "porto-ponta-madeira",
    nome: "Terminal Marítimo de Ponta da Madeira",
    siglaOuTicker: "ANTAQ Term. Privativo Vale",
    tipo: "concessao",
    tipoRotulo: "Concessão de Terminal Portuário Privativo",
    setor: "mineracao",
    setorRotulo: "Logística Portuária de Granéis Minerais",
    paisOrigem: "Brasil",
    jurisdicao: "ANTAQ / Marinha do Brasil / Maranhão",
    nivelHierarquico: 4,
    holdingPaiId: "vale",
    controladorPrincipal: "Vale S.A. (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "R$ 15 Bilhões",
    participacaoMercadoPct: 60.0,
    faturamentoOuReceita: "R$ 8,2 Bilhões/ano (Logística)",
    hhiSetorial: 5800,
    classificacaoHhi: "Monopólio de Escoamento Portuário do Norte",
    posicaoRankingSetor: 1,
    descricao: "Porto campeão nacional em movimentação de carga por tonelagem. Localizado em São Luís (MA), escoa a produção de Carajás para navios Valemax de 400 mil toneladas.",
    ativosEstrategicos: "Píer IV com calado natural de mais de 23 metros, permitindo atracação dos maiores navios mineraleiros do mundo.",
    riscosAntitruste: "Ponto de estrangulamento essencial (essential facility): nenhuma outra mineradora consegue exportar pelo Norte sem aprovação da Vale.",
    fontesOficiais: "ANTAQ Estatístico Aquaviário Oficial / Capitania dos Portos",
    urlOficial: "https://web.antaq.gov.br/anuario/",
  },
  {
    id: "barragem-fundao-germano",
    nome: "Complexo Minerário de Germano & Barragem de Fundão",
    siglaOuTicker: "ANM Proc. 800.456/1976",
    tipo: "concessao",
    tipoRotulo: "Concessão de Lavra & Disposição de Rejeitos",
    setor: "mineracao",
    setorRotulo: "Minério de Ferro & Rejeitos em Mariana (MG)",
    paisOrigem: "Brasil",
    jurisdicao: "ANM / FEAM-MG / Justiça Federal",
    nivelHierarquico: 4,
    holdingPaiId: "samarco",
    controladorPrincipal: "Samarco Mineração S.A. (Vale 50% / BHP 50%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "R$ 130 Bilhões (Passivo do Acordo de Reparação Definitivo)",
    participacaoMercadoPct: 5.0,
    faturamentoOuReceita: "R$ 4,5 Bilhões/ano",
    hhiSetorial: 4942,
    classificacaoHhi: "Maior Litígio Socioambiental da Mineração",
    posicaoRankingSetor: 2,
    descricao: "Mina e bacia de rejeitos em Mariana (MG) onde ocorreu o colapso da barragem de Fundão em 5 de novembro de 2015, matando 19 pessoas e destruindo o Rio Doce.",
    ativosEstrategicos: "Cava de Alegria Sul, Cava de Germano e sistema de filtragem de rejeitos a seco.",
    riscosAntitruste: "Tentativas sucessivas de postergação de pagamento das indenizações às comunidades atingidas via disputas judiciais em cortes internacionais (Londres e Brasil).",
    fontesOficiais: "ANM SIGBM / Ministério Público Federal / Acordo Judicial Rio Doce 2024",
    urlOficial: "https://www.snisb.gov.br/",
  },

  // GRÃOS (CONCESSÕES PORTUÁRIAS DO CARTEL ABCD)
  {
    id: "terminal-ponta-montanha",
    nome: "Terminal Portuário Ponta da Montanha (Barcarena)",
    siglaOuTicker: "ANTAQ TUP Cargill",
    tipo: "concessao",
    tipoRotulo: "Terminal de Uso Privado (TUP)",
    setor: "agronegocio_graos",
    setorRotulo: "Escoamento de Soja e Milho pelo Arco Norte",
    paisOrigem: "Brasil",
    jurisdicao: "ANTAQ / SEMAS-PA / Capitania dos Portos",
    nivelHierarquico: 4,
    holdingPaiId: "cargill-agricola-brasil",
    controladorPrincipal: "Cargill Agrícola S.A. (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "R$ 3,2 Bilhões",
    participacaoMercadoPct: 32.0,
    faturamentoOuReceita: "R$ 1,8 Bilhão/ano",
    hhiSetorial: 3150,
    classificacaoHhi: "Oligopólio Portuário do Arco Norte",
    posicaoRankingSetor: 1,
    descricao: "Terminal graneleiro em Barcarena (PA) que recebe comboios de barcaças do Rio Tapajós e transfere grãos para navios transoceânicos rumo à Europa e China.",
    ativosEstrategicos: "Píer flutuante com capacidade de carregamento de mais de 7 milhões de toneladas de grãos/ano.",
    riscosAntitruste: "Inquérito civil no MPF por conflitos territoriais com quilombolas e ribeirinhos de Barcarena e Abaetetuba.",
    fontesOficiais: "ANTAQ / SEMAS Pará / MPF",
    urlOficial: "https://web.antaq.gov.br/",
  },
  {
    id: "terminal-tgg-santos",
    nome: "Terminal Graneleiro do Guarujá (TGG - Santos)",
    siglaOuTicker: "ANTAQ Arrendamento Portuário",
    tipo: "concessao",
    tipoRotulo: "Concessão Portuária de Grãos e Açúcar",
    setor: "agronegocio_graos",
    setorRotulo: "Exportação Portuária no Porto de Santos",
    paisOrigem: "Brasil",
    jurisdicao: "ANTAQ / Autoridade Portuária de Santos (APS)",
    nivelHierarquico: 4,
    holdingPaiId: "bunge-alimentos-brasil",
    controladorPrincipal: "Bunge Alimentos S.A. & Amaggi (50% / 50%)",
    participacaoControladorPct: 50.0,
    valorMercadoOuAtivos: "R$ 2,5 Bilhões",
    participacaoMercadoPct: 22.0,
    faturamentoOuReceita: "R$ 1,4 Bilhão/ano",
    hhiSetorial: 2850,
    classificacaoHhi: "Concentração Portuária em Santos",
    posicaoRankingSetor: 2,
    descricao: "Um dos maiores terminais de granéis agrícolas sólidos do Porto de Santos, com capacidade de movimentar mais de 9 milhões de toneladas de soja, farelo e milho.",
    ativosEstrategicos: "2 berços de atracação para navios Panamax/Capesize e integração direta com a malha da Rumo Logística.",
    riscosAntitruste: "Controle conjunto Bunge-Amaggi que prioriza o escoamento de grãos próprios em detrimento de cargas de cooperativas independentes.",
    fontesOficiais: "Autoridade Portuária de Santos / ANTAQ",
    urlOficial: "https://www.portodesantos.com.br/",
  },

  // ENERGIA & PRÉ-SAL
  {
    id: "campo-pre-sal-mero",
    nome: "Campo de Mero (Consórcio de Libra - Bacia de Santos)",
    siglaOuTicker: "ANP Contrato Partilha 001/2013",
    tipo: "concessao",
    tipoRotulo: "Contrato de Partilha de Produção do Pré-Sal",
    setor: "energia_petroleo",
    setorRotulo: "Megareservatório de Petróleo Leve em Águas Ultraprofundas",
    paisOrigem: "Brasil",
    jurisdicao: "ANP / PPSA / Marinha do Brasil",
    nivelHierarquico: 4,
    holdingPaiId: "petrobras",
    controladorPrincipal: "Petrobras (38,6%), Shell (19,3%), TotalEnergies (19,3%), CNPC (9,65%), CNOOC (9,65%)",
    participacaoControladorPct: 38.6,
    valorMercadoOuAtivos: "US$ 35 Bilhões (Investimento do Consórcio)",
    participacaoMercadoPct: 18.0,
    faturamentoOuReceita: "US$ 8,5 Bilhões/ano",
    hhiSetorial: 3100,
    classificacaoHhi: "Cartel Legalizado de Partilha de Petróleo",
    posicaoRankingSetor: 1,
    descricao: "Terceiro maior campo produtor de petróleo e gás do Brasil, situado a 180 km do litoral do Rio de Janeiro sob 2.100 metros de lâmina d'água.",
    ativosEstrategicos: "FPSOs Guanabara, Sepetiba, Marechal Duque de Caxias e Alexandre de Gusmão (capacidade de 720 mil barris/dia).",
    riscosAntitruste: "Consórcio de partilha que reúne as maiores concorrentes mundiais de petróleo na mesma mesa decisória de investimentos.",
    fontesOficiais: "ANP Boletim da Produção / PPSA Pré-Sal Petróleo",
    urlOficial: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
  },
  {
    id: "refinaria-regap-betim",
    nome: "Refinaria Gabriel Passos (Regap - Betim/MG)",
    siglaOuTicker: "ANP Instalação 003/Petrobras",
    tipo: "concessao",
    tipoRotulo: "Ativo Industrial de Refino de Petróleo",
    setor: "energia_petroleo",
    setorRotulo: "Combustíveis Automotivos, Asfalto & GLP em MG",
    paisOrigem: "Brasil",
    jurisdicao: "ANP / FEAM-MG / Betim",
    nivelHierarquico: 4,
    holdingPaiId: "petrobras",
    controladorPrincipal: "Petróleo Brasileiro S.A. (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "R$ 18 Bilhões",
    participacaoMercadoPct: 82.0,
    faturamentoOuReceita: "R$ 32 Bilhões/ano",
    hhiSetorial: 8800,
    classificacaoHhi: "Monopólio Geográfico de Refino em Minas Gerais",
    posicaoRankingSetor: 1,
    descricao: "Refinaria responsável pelo abastecimento de mais de 80% da gasolina, diesel, querosene de aviação e gás de cozinha consumidos no estado de Minas Gerais.",
    ativosEstrategicos: "Capacidade de processar 166 mil barris/dia (26,4 milhões de litros/dia) conectada a oleodutos com a Baixada Fluminense.",
    riscosAntitruste: "Monopólio natural regional em Minas Gerais: não existe nenhum refino concorrente em um raio de mais de 500 km.",
    fontesOficiais: "ANP / Petrobras Relatório Operacional Regap",
    urlOficial: "https://petrobras.com.br/pt/nossas-atividades/principais-operacoes/refinarias/regap.htm",
  },

  // BIG TECH INFRAESTRUTURA
  {
    id: "cabo-submarino-firmina",
    nome: "Cabo Submarino de Fibra Óptica Firmina (Google)",
    siglaOuTicker: "ANATEL Concessão Telecom",
    tipo: "concessao",
    tipoRotulo: "Infraestrutura Crítica de Telecomunicação",
    setor: "tecnologia",
    setorRotulo: "Cabos Submarinos Intercontinentais de Alta Capacidade",
    paisOrigem: "Brasil",
    jurisdicao: "ANATEL / Marinha do Brasil / EUA",
    nivelHierarquico: 4,
    holdingPaiId: "google-cloud-brasil",
    controladorPrincipal: "Google LLC / Alphabet Inc. (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "US$ 1,2 Bilhão",
    participacaoMercadoPct: 40.0,
    faturamentoOuReceita: "US$ 350 Milhões/ano (Capacidade)",
    hhiSetorial: 4800,
    classificacaoHhi: "Altamente Concentrado (Infraestrutura de Dados)",
    posicaoRankingSetor: 1,
    descricao: "Maior cabo submarino aberto do mundo com alimentação de energia ponta a ponta por fonte única, ligando a Carolina do Sul (EUA) a Praia Grande (Brasil), Punta del Este e Buenos Aires.",
    ativosEstrategicos: "12 pares de fibra óptica com transmissão ultra-rápida de pacotes de dados e tráfego de inteligência artificial.",
    riscosAntitruste: "Propriedade privada de rotas fundamentais da internet por uma única empresa que também controla o motor de busca e a publicidade.",
    fontesOficiais: "ANATEL Sistema Mosaico / Submarine Cable Map",
    urlOficial: "https://www.submarinecablemap.com/submarine-cable/firmina",
  },
  {
    id: "datacenter-azure-campinas",
    nome: "Região de Nuvem Azure Brasil South (Campinas/SP)",
    siglaOuTicker: "Instalação Hyperscale Microsoft",
    tipo: "concessao",
    tipoRotulo: "Infraestrutura Crítica de Servidores",
    setor: "tecnologia",
    setorRotulo: "Datacenters Hyperscale & Soberania Digital",
    paisOrigem: "Brasil",
    jurisdicao: "Receita Federal / JUCESP",
    nivelHierarquico: 4,
    holdingPaiId: "microsoft",
    controladorPrincipal: "Microsoft Corporation (100%)",
    participacaoControladorPct: 100.0,
    valorMercadoOuAtivos: "US$ 2,5 Bilhões",
    participacaoMercadoPct: 29.0,
    faturamentoOuReceita: "US$ 1,2 Bilhão/ano",
    hhiSetorial: 3320,
    classificacaoHhi: "Altamente Concentrado (Nuvem Soberana)",
    posicaoRankingSetor: 2,
    descricao: "Campus de datacenters no interior paulista que processa dados financeiros da B3, de ministérios federais e das maiores instituições bancárias do país.",
    ativosEstrategicos: "Rede privada interconectada com múltiplos anéis de fibra e garantia de retenção de dados em solo nacional.",
    riscosAntitruste: "Submissão de dados de soberania nacional à jurisdição da lei extraterritorial dos EUA (CLOUD Act), sem auditoria popular direta.",
    fontesOficiais: "Microsoft Azure Infrastructure / PNCP",
    urlOficial: "https://azure.microsoft.com/pt-br/explore/global-infrastructure/geographies/#brazil",
  },
];

// ══════════════════════════════════════════════════════════════════════════
// 2. ARESTAS DE CONTROLE ACIONÁRIO, SUBSIDIÁRIAS E JOINT-VENTURES
// ══════════════════════════════════════════════════════════════════════════

export const ARESTAS_CONTROLE: RegistroArestaControle[] = [
  // ─── PROPRIEDADE COMUM DOS BIG THREE (BLACKROCK, VANGUARD, STATE STREET) ───
  // MINERAÇÃO
  {
    id: "blk-vale",
    origemId: "blackrock",
    destinoId: "vale",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Propriedade Comum (8,2% Votante)",
    participacaoPct: 8.2,
    valorEstimado: "US$ 6,0 Bilhões",
    detalhes: "BlackRock detém 8,2% das ações ordinárias da Vale S.A. via ADRs e B3, integrando o comitê consultivo societário.",
    fonteOficial: "SEC EDGAR Form 13F / CVM Form Ref 2026",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001364954",
  },
  {
    id: "vng-vale",
    origemId: "vanguard",
    destinoId: "vale",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Propriedade Comum (7,8% Votante)",
    participacaoPct: 7.8,
    valorEstimado: "US$ 5,7 Bilhões",
    detalhes: "The Vanguard Group possui 7,8% da Vale em fundos indexados mundiais.",
    fonteOficial: "SEC EDGAR Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000102909",
  },
  {
    id: "stt-vale",
    origemId: "state-street",
    destinoId: "vale",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Propriedade Comum (4,5% Votante)",
    participacaoPct: 4.5,
    valorEstimado: "US$ 3,3 Bilhões",
    detalhes: "State Street Corporation detém 4,5% de participação e atua como custodiante internacional.",
    fonteOficial: "SEC EDGAR Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000093751",
  },
  {
    id: "blk-bhp",
    origemId: "blackrock",
    destinoId: "bhp",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Propriedade Comum (6,5% Votante)",
    participacaoPct: 6.5,
    valorEstimado: "US$ 10,0 Bilhões",
    detalhes: "BlackRock controla 6,5% da BHP, principal concorrente mundial da Vale.",
    fonteOficial: "SEC EDGAR Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001364954",
  },
  {
    id: "vng-bhp",
    origemId: "vanguard",
    destinoId: "bhp",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Propriedade Comum (8,4% Votante)",
    participacaoPct: 8.4,
    valorEstimado: "US$ 13,0 Bilhões",
    detalhes: "Vanguard detém 8,4% da BHP, sendo o maior acionista institucional da empresa.",
    fonteOficial: "SEC EDGAR Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000102909",
  },
  {
    id: "blk-rio-tinto",
    origemId: "blackrock",
    destinoId: "rio-tinto",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Propriedade Comum (7,1% Votante)",
    participacaoPct: 7.1,
    valorEstimado: "US$ 7,9 Bilhões",
    detalhes: "BlackRock comanda 7,1% da Rio Tinto, unificando o controle das 3 maiores mineradoras do planeta.",
    fonteOficial: "LSE / SEC Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001364954",
  },
  {
    id: "blk-anglo",
    origemId: "blackrock",
    destinoId: "anglo-american",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Propriedade Comum (6,0% Votante)",
    participacaoPct: 6.0,
    valorEstimado: "US$ 2,2 Bilhões",
    detalhes: "BlackRock possui 6% da Anglo American, operadora do Sistema Minas-Rio.",
    fonteOficial: "LSE Companies House / SEC",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001364954",
  },

  // ENERGIA & PETRÓLEO
  {
    id: "blk-petrobras",
    origemId: "blackrock",
    destinoId: "petrobras",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Participação em Ações Votantes e ADRs (5,1%)",
    participacaoPct: 5.1,
    valorEstimado: "US$ 4,9 Bilhões",
    detalhes: "BlackRock é o maior investidor estrangeiro privado na Petrobras, com 5,1% de capital.",
    fonteOficial: "CVM Formulário de Referência 2026",
    urlOficial: "https://rad.cvm.gov.br/",
  },
  {
    id: "vng-petrobras",
    origemId: "vanguard",
    destinoId: "petrobras",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Participação em Carteiras Globais (4,6%)",
    participacaoPct: 4.6,
    valorEstimado: "US$ 4,5 Bilhões",
    detalhes: "Vanguard possui 4,6% da Petrobras em fundos de mercados emergentes.",
    fonteOficial: "SEC Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000102909",
  },
  {
    id: "blk-shell",
    origemId: "blackrock",
    destinoId: "shell",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Propriedade Comum (6,8% Votante)",
    participacaoPct: 6.8,
    valorEstimado: "US$ 14,2 Bilhões",
    detalhes: "BlackRock é acionista de relevo na Shell, que por sua vez concorre e é sócia da Petrobras no Pré-Sal.",
    fonteOficial: "SEC Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001364954",
  },

  // BANCOS
  {
    id: "blk-itau",
    origemId: "blackrock",
    destinoId: "itau-unibanco",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Propriedade Comum (7,5% Capital)",
    participacaoPct: 7.5,
    valorEstimado: "US$ 4,6 Bilhões",
    detalhes: "BlackRock é a maior acionista institucional externa do Itaú Unibanco.",
    fonteOficial: "CVM / Banco Central",
    urlOficial: "https://rad.cvm.gov.br/",
  },
  {
    id: "blk-bradesco",
    origemId: "blackrock",
    destinoId: "banco-bradesco",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Propriedade Comum (6,8% Capital)",
    participacaoPct: 6.8,
    valorEstimado: "US$ 2,0 Bilhões",
    detalhes: "BlackRock detém simultaneamente 6,8% do Bradesco, maior rival do Itaú.",
    fonteOficial: "CVM / SEC 13F",
    urlOficial: "https://rad.cvm.gov.br/",
  },
  {
    id: "blk-b3",
    origemId: "blackrock",
    destinoId: "b3-bolsa",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Maior Acionista Institucional da Bolsa (6,9%)",
    participacaoPct: 6.9,
    valorEstimado: "US$ 1,0 Bilhão",
    detalhes: "BlackRock é a maior detentora individual de ações da B3 S.A., controlando a infraestrutura onde suas próprias investidas são negociadas.",
    fonteOficial: "CVM Formulário de Referência B3",
    urlOficial: "https://ri.b3.com.br/",
  },

  // BIG TECH
  {
    id: "vng-microsoft",
    origemId: "vanguard",
    destinoId: "microsoft",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Maior Acionista Institucional (8,9%)",
    participacaoPct: 8.9,
    valorEstimado: "US$ 275 Bilhões",
    detalhes: "Vanguard comanda a maior fatia acionária da Microsoft no mundo.",
    fonteOficial: "SEC Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000102909",
  },
  {
    id: "blk-microsoft",
    origemId: "blackrock",
    destinoId: "microsoft",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Segundo Maior Acionista (7,4%)",
    participacaoPct: 7.4,
    valorEstimado: "US$ 229 Bilhões",
    detalhes: "BlackRock comanda a segunda maior fatia acionária da Microsoft.",
    fonteOficial: "SEC Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001364954",
  },
  {
    id: "vng-google",
    origemId: "vanguard",
    destinoId: "alphabet-google",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Maior Acionista Institucional (8,1%)",
    participacaoPct: 8.1,
    valorEstimado: "US$ 178 Bilhões",
    detalhes: "Vanguard é a maior acionista institucional da controladora do Google.",
    fonteOficial: "SEC Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000102909",
  },
  {
    id: "vng-amazon",
    origemId: "vanguard",
    destinoId: "amazon",
    tipoRelacao: "propriedade_comum_big_three",
    tipoRotulo: "Maior Acionista Institucional (7,4%)",
    participacaoPct: 7.4,
    valorEstimado: "US$ 140 Bilhões",
    detalhes: "Vanguard supera todos os fundos globais em ações da Amazon.",
    fonteOficial: "SEC Form 13F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0000102909",
  },

  // ─── SUBSIDIÁRIAS OPERACIONAIS E JOINT-VENTURES (NÍVEL 2 -> NÍVEL 3) ───
  {
    id: "vale-samarco",
    origemId: "vale",
    destinoId: "samarco",
    tipoRelacao: "joint_venture",
    tipoRotulo: "Joint-Venture 50% / 50%",
    participacaoPct: 50.0,
    valorEstimado: "R$ 19 Bilhões",
    detalhes: "Vale divide meio a meio com a BHP o controle da Samarco Mineração.",
    fonteOficial: "CVM / JUCEMG",
    urlOficial: "https://rad.cvm.gov.br/",
  },
  {
    id: "bhp-samarco",
    origemId: "bhp",
    destinoId: "samarco",
    tipoRelacao: "joint_venture",
    tipoRotulo: "Joint-Venture 50% / 50%",
    participacaoPct: 50.0,
    valorEstimado: "R$ 19 Bilhões",
    detalhes: "BHP divide meio a meio com a Vale o controle da Samarco Mineração.",
    fonteOficial: "ASIC / SEC Form 20-F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001041123",
  },
  {
    id: "vale-salobo",
    origemId: "vale",
    destinoId: "salobo-metais",
    tipoRelacao: "subsidiaria_integral",
    tipoRotulo: "Subsidiária Integral (100%)",
    participacaoPct: 100.0,
    valorEstimado: "US$ 12 Bilhões",
    detalhes: "Vale Metais Básicos detém 100% da Salobo Metais S.A.",
    fonteOficial: "CVM Form Ref 2026",
    urlOficial: "https://rad.cvm.gov.br/",
  },
  {
    id: "rio-mrn",
    origemId: "rio-tinto",
    destinoId: "mrn-bauxita",
    tipoRelacao: "joint_venture",
    tipoRotulo: "Participação Acionária (12%)",
    participacaoPct: 12.0,
    valorEstimado: "US$ 540 Milhões",
    detalhes: "Rio Tinto possui fatia na maior mina de bauxita do Brasil.",
    fonteOficial: "ANM / MRN Relatórios",
    urlOficial: "https://www.mrn.com.br/",
  },
  {
    id: "glen-mrn",
    origemId: "glencore",
    destinoId: "mrn-bauxita",
    tipoRelacao: "controle_majoritario",
    tipoRotulo: "Controle Acionário (45%)",
    participacaoPct: 45.0,
    valorEstimado: "US$ 2,0 Bilhões",
    detalhes: "Glencore adquiriu participação de controle na Mineração Rio do Norte.",
    fonteOficial: "CADE AC 08700.007123/2023",
    urlOficial: "https://www.glencore.com/",
  },
  {
    id: "cargill-cargillbr",
    origemId: "cargill",
    destinoId: "cargill-agricola-brasil",
    tipoRelacao: "subsidiaria_integral",
    tipoRotulo: "Controle Integral (100%)",
    participacaoPct: 100.0,
    valorEstimado: "R$ 42 Bilhões",
    detalhes: "Cargill, Inc. opera no Brasil exclusivamente por meio de sua subsidiária integral.",
    fonteOficial: "JUCESP / Receita Federal",
    urlOficial: "https://www.cargill.com.br/",
  },
  {
    id: "bunge-bungebr",
    origemId: "bunge",
    destinoId: "bunge-alimentos-brasil",
    tipoRelacao: "subsidiaria_integral",
    tipoRotulo: "Controle Integral (100%)",
    participacaoPct: 100.0,
    valorEstimado: "R$ 36 Bilhões",
    detalhes: "Bunge Global SA consolida suas fábricas brasileiras na Bunge Alimentos S.A.",
    fonteOficial: "SEC Form 10-K",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001996862",
  },
  {
    id: "petro-transpetro",
    origemId: "petrobras",
    destinoId: "transpetro",
    tipoRelacao: "subsidiaria_integral",
    tipoRotulo: "Subsidiária Integral (100%)",
    participacaoPct: 100.0,
    valorEstimado: "R$ 28 Bilhões",
    detalhes: "Petrobras detém 100% das ações com direito a voto da Transpetro.",
    fonteOficial: "CVM Formulário de Referência",
    urlOficial: "https://rad.cvm.gov.br/",
  },
  {
    id: "cosan-raizen",
    origemId: "cosan",
    destinoId: "raizen",
    tipoRelacao: "joint_venture",
    tipoRotulo: "Coproprietária (44% do Capital)",
    participacaoPct: 44.0,
    valorEstimado: "R$ 14 Bilhões",
    detalhes: "Cosan divide o comando da Raízen com a Shell.",
    fonteOficial: "CVM Formulário de Referência",
    urlOficial: "https://rad.cvm.gov.br/",
  },
  {
    id: "shell-raizen",
    origemId: "shell",
    destinoId: "raizen",
    tipoRelacao: "joint_venture",
    tipoRotulo: "Coproprietária (44% do Capital)",
    participacaoPct: 44.0,
    valorEstimado: "R$ 14 Bilhões",
    detalhes: "Shell divide o comando da Raízen com a Cosan.",
    fonteOficial: "SEC Form 20-F",
    urlOficial: "https://www.sec.gov/edgar/browse/?CIK=0001306965",
  },
  {
    id: "amzn-awsbr",
    origemId: "amazon",
    destinoId: "aws-brasil-cloud",
    tipoRelacao: "subsidiaria_integral",
    tipoRotulo: "Controle Integral (100%)",
    participacaoPct: 100.0,
    valorEstimado: "R$ 18 Bilhões",
    detalhes: "Amazon.com comanda diretamente sua filial brasileira de servidores.",
    fonteOficial: "Receita Federal / SEC",
    urlOficial: "https://aws.amazon.com/pt/",
  },
  {
    id: "goog-googcloudbr",
    origemId: "alphabet-google",
    destinoId: "google-cloud-brasil",
    tipoRelacao: "subsidiaria_integral",
    tipoRotulo: "Controle Integral (100%)",
    participacaoPct: 100.0,
    valorEstimado: "R$ 15 Bilhões",
    detalhes: "Alphabet opera serviços de nuvem e IA via Google Brasil Internet Ltda.",
    fonteOficial: "CADE / SEC",
    urlOficial: "https://cloud.google.com/",
  },

  // ─── CONCESSÕES PÚBLICAS, MINAS & ATIVOS (NÍVEL 3 -> NÍVEL 4) ───
  {
    id: "vale-carajas",
    origemId: "vale",
    destinoId: "mina-carajas-s11d",
    tipoRelacao: "concessao_exploracao",
    tipoRotulo: "Concessão Federal de Lavra (ANM)",
    participacaoPct: 100.0,
    valorEstimado: "US$ 25 Bilhões",
    detalhes: "Vale detém a concessão de lavra do megaprojeto S11D em Carajás.",
    fonteOficial: "ANM SIGMINE",
    urlOficial: "https://app.anm.gov.br/SIGMINE/",
  },
  {
    id: "vale-ponta-madeira",
    origemId: "vale",
    destinoId: "porto-ponta-madeira",
    tipoRelacao: "concessao_exploracao",
    tipoRotulo: "Terminal Privativo Portuário (ANTAQ)",
    participacaoPct: 100.0,
    valorEstimado: "R$ 15 Bilhões",
    detalhes: "Terminal marítimo privativo que conecta Carajás aos mercados mundiais.",
    fonteOficial: "ANTAQ",
    urlOficial: "https://web.antaq.gov.br/",
  },
  {
    id: "samarco-fundao",
    origemId: "samarco",
    destinoId: "barragem-fundao-germano",
    tipoRelacao: "concessao_exploracao",
    tipoRotulo: "Operadora da Barragem e Mina (100%)",
    participacaoPct: 100.0,
    valorEstimado: "R$ 130 Bilhões (Passivo)",
    detalhes: "Samarco é a titular da concessão do complexo de Germano e da barragem rompida de Fundão.",
    fonteOficial: "ANM SIGBM",
    urlOficial: "https://www.snisb.gov.br/",
  },
  {
    id: "cargillbr-ponta-montanha",
    origemId: "cargill-agricola-brasil",
    destinoId: "terminal-ponta-montanha",
    tipoRelacao: "concessao_exploracao",
    tipoRotulo: "Terminal Privado Graneleiro (ANTAQ)",
    participacaoPct: 100.0,
    valorEstimado: "R$ 3,2 Bilhões",
    detalhes: "Terminal fluvial e marítimo da Cargill em Barcarena.",
    fonteOficial: "ANTAQ TUP",
    urlOficial: "https://web.antaq.gov.br/",
  },
  {
    id: "bungebr-tgg",
    origemId: "bunge-alimentos-brasil",
    destinoId: "terminal-tgg-santos",
    tipoRelacao: "cartel_infraestrutura",
    tipoRotulo: "Arrendamento Portuário Santos (50%)",
    participacaoPct: 50.0,
    valorEstimado: "R$ 2,5 Bilhões",
    detalhes: "Bunge compartilha o controle do TGG no Porto de Santos com a Amaggi.",
    fonteOficial: "Autoridade Portuária de Santos",
    urlOficial: "https://www.portodesantos.com.br/",
  },
  {
    id: "petro-mero",
    origemId: "petrobras",
    destinoId: "campo-pre-sal-mero",
    tipoRelacao: "concessao_exploracao",
    tipoRotulo: "Operadora do Consórcio de Partilha (38,6%)",
    participacaoPct: 38.6,
    valorEstimado: "US$ 13,5 Bilhões",
    detalhes: "Petrobras opera os navios-plataforma FPSO do Campo de Mero.",
    fonteOficial: "ANP / PPSA",
    urlOficial: "https://www.gov.br/anp/",
  },
  {
    id: "shell-mero",
    origemId: "shell",
    destinoId: "campo-pre-sal-mero",
    tipoRelacao: "joint_venture",
    tipoRotulo: "Consórcio de Partilha Pré-Sal (19,3%)",
    participacaoPct: 19.3,
    valorEstimado: "US$ 6,7 Bilhões",
    detalhes: "Shell é a principal sócia privada internacional no megacampo de Mero.",
    fonteOficial: "ANP Contratos",
    urlOficial: "https://www.gov.br/anp/",
  },
  {
    id: "total-mero",
    origemId: "totalenergies",
    destinoId: "campo-pre-sal-mero",
    tipoRelacao: "joint_venture",
    tipoRotulo: "Consórcio de Partilha Pré-Sal (19,3%)",
    participacaoPct: 19.3,
    valorEstimado: "US$ 6,7 Bilhões",
    detalhes: "TotalEnergies detém fatia idêntica à da Shell na extração de Mero.",
    fonteOficial: "ANP Contratos",
    urlOficial: "https://www.gov.br/anp/",
  },
  {
    id: "petro-regap",
    origemId: "petrobras",
    destinoId: "refinaria-regap-betim",
    tipoRelacao: "concessao_exploracao",
    tipoRotulo: "Controle Integral do Refino em MG (100%)",
    participacaoPct: 100.0,
    valorEstimado: "R$ 18 Bilhões",
    detalhes: "Petrobras é proprietária única da Regap em Betim.",
    fonteOficial: "ANP",
    urlOficial: "https://petrobras.com.br/",
  },
  {
    id: "googcloud-firmina",
    origemId: "google-cloud-brasil",
    destinoId: "cabo-submarino-firmina",
    tipoRelacao: "concessao_exploracao",
    tipoRotulo: "Concessão Privada de Fibra Óptica (100%)",
    participacaoPct: 100.0,
    valorEstimado: "US$ 1,2 Bilhão",
    detalhes: "Google detém a concessão e a operação do cabo transatlântico Firmina.",
    fonteOficial: "ANATEL",
    urlOficial: "https://www.submarinecablemap.com/",
  },
  {
    id: "msft-campinas",
    origemId: "microsoft",
    destinoId: "datacenter-azure-campinas",
    tipoRelacao: "concessao_exploracao",
    tipoRotulo: "Proprietária do Campus Hyperscale (100%)",
    participacaoPct: 100.0,
    valorEstimado: "US$ 2,5 Bilhões",
    detalhes: "Microsoft opera diretamente os datacenters de sua infraestrutura em Campinas.",
    fonteOficial: "Microsoft Azure Infra",
    urlOficial: "https://azure.microsoft.com/",
  },
];

// ══════════════════════════════════════════════════════════════════════════
// 3. ANÁLISE DE CONCENTRAÇÃO SETORIAL & ÍNDICE HHI (HERFINDAHL-HIRSCHMAN)
// ══════════════════════════════════════════════════════════════════════════

export const CONCENTRACAO_SETORIAL: RegistroConcentracaoSetorial[] = [
  {
    setorId: "mineracao",
    nome: "Minério de Ferro & Metais Básicos (Big Mining)",
    hhi: 4942,
    classificacao: "Altamente Concentrado (Quase-Monopólio)",
    cr4Pct: 96.0,
    descricaoConcorrencial: "A Vale domina 68% da exportação nacional de minério de ferro. Somada à CSN Mineração (14%), Anglo American (9%) e Samarco (5%), os 4 maiores players comandam 96% do mercado brasileiro.",
    criterioCade: "Índice HHI de 4.942 supera quase o dobro do teto de 2.500 pontos do Guia de Concentração Horizontal do CADE, sinalizando altíssimo poder de mercado e barreiras geológicas e logísticas insuperáveis.",
    principaisPlayers: [
      { nome: "Vale S.A.", sigla: "VALE3", participacaoPct: 68.0, tipo: "Líder Quase-Monopolista" },
      { nome: "CSN Mineração", sigla: "CMIN3", participacaoPct: 14.0, tipo: "Vice-Líder Nacional" },
      { nome: "Anglo American (Minas-Rio)", sigla: "AAL", participacaoPct: 9.0, tipo: "Multinacional Britânica" },
      { nome: "Samarco Mineração", sigla: "SAMARCO", participacaoPct: 5.0, tipo: "Joint-Venture Vale/BHP" },
      { nome: "Outras Mineradoras", sigla: "DIVERSAS", participacaoPct: 4.0, tipo: "Franja Competitiva" },
    ],
    alertasAntitruste: [
      "Monopólio da malha ferroviária federal (EFVM e EFC) concedida à Vale.",
      "Acordo societário da Samarco entre duas líderes mundiais (Vale e BHP).",
      "Venda cruzada de participações (Vale adquiriu 15% da Anglo American no Minas-Rio).",
      "Truste de voto dos Big Three (BlackRock, Vanguard e State Street detêm mais de 20% do capital da Vale e da BHP).",
    ],
    fonteOficial: "ANM / IBRAM / CADE Atos de Concentração do Setor Mineral",
    urlOficial: "https://www.gov.br/anm/pt-br/assuntos/dados-abertos",
  },
  {
    setorId: "agronegocio_graos",
    nome: "Comércio, Esmagamento & Exportação de Grãos (Cartel ABCD)",
    hhi: 1822,
    classificacao: "Oligopólio Coordenado (CR4 = 77% / HHI Portuário = 3.150)",
    cr4Pct: 77.0,
    descricaoConcorrencial: "O quarteto transnacional ABCD (ADM, Bunge, Cargill e Louis Dreyfus) controla 77% da exportação de soja e milho do Brasil. Embora o HHI bruto de originação indique concentração moderada (1.822), o HHI de escoamento nos portos do Arco Norte e Santos supera 3.150 pontos.",
    criterioCade: "Oligopólio com poder de compra (monopsônio tácito) sobre produtores rurais que dependem das tradings para insumos, crédito e transporte.",
    principaisPlayers: [
      { nome: "Cargill, Inc.", sigla: "CARGILL", participacaoPct: 26.0, tipo: "Líder Global" },
      { nome: "Bunge Global SA", sigla: "BUNGE", participacaoPct: 24.0, tipo: "Líder em Esmagamento" },
      { nome: "Archer Daniels Midland", sigla: "ADM", participacaoPct: 15.0, tipo: "Processamento e Biocombustíveis" },
      { nome: "Louis Dreyfus Company", sigla: "LDC", participacaoPct: 12.0, tipo: "Tradicional Trading Mercantil" },
      { nome: "Amaggi Group", sigla: "AMAGGI", participacaoPct: 11.0, tipo: "Conglomerado Familiar Nacional" },
      { nome: "COFCO International", sigla: "COFCO", participacaoPct: 8.0, tipo: "Estatal Chinesa" },
      { nome: "Outras Tradings", sigla: "OUTRAS", participacaoPct: 4.0, tipo: "Franja de Cooperativas" },
    ],
    alertasAntitruste: [
      "Fusão Bunge-Viterra concentrou terminais portuários em Santos e Paranaguá.",
      "Consórcios conjuntos de terminais de grãos entre concorrentes diretas.",
      "Fixação coordenada de margens de esmagamento e preços na porteira.",
      "Apropriação privada de acessos hidroviários públicos na Amazônia.",
    ],
    fonteOficial: "CADE AC Bunge-Viterra / USDA Foreign Agricultural Service / MAPA",
    urlOficial: "https://www.gov.br/cade/pt-br",
  },
  {
    setorId: "energia_petroleo",
    nome: "Petróleo, Refino & Combustíveis (Big Oil)",
    hhi: 6303,
    classificacao: "Extrema Concentração em Refino (Monopólio Natural)",
    cr4Pct: 98.0,
    descricaoConcorrencial: "A Petrobras mantém 78% do refino nacional de combustíveis, gerando um HHI setorial recorde de 6.303 pontos. No Pré-Sal, os consórcios de partilha reúnem Petrobras, Shell e TotalEnergies, eliminando a disputa de preços na extração primária.",
    criterioCade: "Termo de Compromisso de Cessação (TCC) de refino do CADE foi parcialmente revisto em 2024, mantendo a dependência estrutural do mercado na Petrobras.",
    principaisPlayers: [
      { nome: "Petrobras", sigla: "PETR4", participacaoPct: 78.0, tipo: "Estatal de Economia Mista" },
      { nome: "Acelen (Refinaria Mataripe)", sigla: "ACELEN", participacaoPct: 13.0, tipo: "Fundo Soberano Mubadala" },
      { nome: "Shell Brasil", sigla: "SHEL", participacaoPct: 5.0, tipo: "Maior Produtora Privada" },
      { nome: "TotalEnergies", sigla: "TTE", participacaoPct: 2.0, tipo: "Sócia no Pré-Sal" },
      { nome: "Outras Refinarias", sigla: "OUTRAS", participacaoPct: 2.0, tipo: "Refinarias Independentes" },
    ],
    alertasAntitruste: [
      "Monopólio regional das refinarias (Regap em MG, Replan em SP, Reduc no RJ).",
      "Consórcios unificados de exploração em Mero, Tupi e Búzios.",
      "Duopólio na distribuição de combustíveis entre Vibra e Raízen (Shell/Cosan).",
      "Acionistas comuns (BlackRock e Vanguard possuem participações simultâneas na Petrobras, Shell e Total).",
    ],
    fonteOficial: "ANP Boletim de Petróleo e Refino / CADE / Petrobras RI",
    urlOficial: "https://www.gov.br/anp/pt-br",
  },
  {
    setorId: "bancos_financas",
    nome: "Sistema Financeiro & Bancos (Top Bancos & Big Three)",
    hhi: 2206,
    classificacao: "Moderadamente Concentrado (CR4 = 90% em Ativos e Crédito)",
    cr4Pct: 90.0,
    descricaoConcorrencial: "Quatro instituições financeiras (Itaú Unibanco, Banco do Brasil, Bradesco e Caixa Econômica) detêm 90% dos ativos e da concessão de crédito no Brasil. A B3 detém 100% de monopólio na liquidação de ações.",
    criterioCade: "Mercado caracterizado por elevadas barreiras regulatórias, fidelização forçada de clientes e controle acionário cruzado dos Big Three.",
    principaisPlayers: [
      { nome: "Itaú Unibanco", sigla: "ITUB4", participacaoPct: 29.0, tipo: "Maior Banco Privado" },
      { nome: "Banco do Brasil", sigla: "BBAS3", participacaoPct: 24.0, tipo: "Estatal do Agronegócio" },
      { nome: "Banco Bradesco", sigla: "BBDC4", participacaoPct: 20.0, tipo: "Banco Múltiplo e Segurador" },
      { nome: "Caixa Econômica Federal", sigla: "CEF", participacaoPct: 17.0, tipo: "Monopólio Imobiliário/Social" },
      { nome: "Santander Brasil", sigla: "SANB11", participacaoPct: 10.0, tipo: "Subsidiária Espanhola" },
    ],
    alertasAntitruste: [
      "Monopólio de 100% da B3 S.A. na custódia e negociação de ações no país.",
      "Spreads bancários e tarifas de serviços desproporcionais.",
      "BlackRock e Vanguard como donos simultâneos de blocos relevantes no Itaú e Bradesco.",
      "Controle cruzado das adquirentes Cielo e Rede pelos bancos líderes.",
    ],
    fonteOficial: "Banco Central do Brasil — Relatório de Estabilidade Financeira / CVM",
    urlOficial: "https://www.bcb.gov.br/",
  },
  {
    setorId: "tecnologia",
    nome: "Infraestrutura Cloud & Big Tech",
    hhi: 3320,
    classificacao: "Altamente Concentrado (Oligopólio Tripartite)",
    cr4Pct: 95.0,
    descricaoConcorrencial: "A AWS da Amazon domina 47% dos servidores de nuvem no país, seguida pela Microsoft Azure (29%) e Google Cloud (15%). Juntas, as 3 Big Techs norte-americanas controlam 91% da computação corporativa e estatal brasileira.",
    criterioCade: "Aprisionamento tecnológico de dados públicos e barreiras sistêmicas à soberania digital nacional.",
    principaisPlayers: [
      { nome: "Amazon AWS", sigla: "AMZN", participacaoPct: 47.0, tipo: "Líder Absoluta de Infraestrutura" },
      { nome: "Microsoft Azure", sigla: "MSFT", participacaoPct: 29.0, tipo: "Líder no Setor Público" },
      { nome: "Google Cloud", sigla: "GOOGL", participacaoPct: 15.0, tipo: "Líder em IA e Data Lake" },
      { nome: "Oracle Cloud", sigla: "ORCL", participacaoPct: 5.0, tipo: "Bancos de Dados Corporativos" },
      { nome: "Outras Nuvens", sigla: "OUTRAS", participacaoPct: 4.0, tipo: "Provedores Locais e Nacionais" },
    ],
    alertasAntitruste: [
      "Taxas abusivas de saída de dados (egress fees) que impedem concorrência.",
      "Venda casada de licenças de software corporativo com serviços de nuvem.",
      "Controle dos cabos submarinos intercontinentais pelo Google e Meta.",
      "Truste acionário comum de Vanguard e BlackRock em todas as 5 maiores Big Techs.",
    ],
    fonteOficial: "IDC Brasil / Gartner Cloud Infrastructure / CADE",
    urlOficial: "https://www.gartner.com/",
  },
];

// ══════════════════════════════════════════════════════════════════════════
// 4. EXECUÇÃO DO ETL E COMPACTAÇÃO VIA compactar.ts
// ══════════════════════════════════════════════════════════════════════════

export function executarEtlConglomerados(): void {
  console.log("🏢 Iniciando ETL de Conglomerados, Holdings, Monopólios e Cartéis...");

  fs.mkdirSync(DATA_DIR, { recursive: true });

  // 1. Compacta os nós corporativos e holdings
  const compactadoNos = compactar(NOS_CONGLOMERADOS as unknown as Record<string, unknown>[]);
  const caminhoNos = path.join(DATA_DIR, "conglomerados-holdings.compact.json");
  fs.writeFileSync(caminhoNos, JSON.stringify(compactadoNos), "utf-8");
  console.log(`✓ Holdings e Nós compactados salvos em: ${caminhoNos} (${NOS_CONGLOMERADOS.length} entidades)`);

  // 2. Compacta as arestas de controle societário
  const compactadoArestas = compactar(ARESTAS_CONTROLE as unknown as Record<string, unknown>[]);
  const caminhoArestas = path.join(DATA_DIR, "conglomerados-arestas.compact.json");
  fs.writeFileSync(caminhoArestas, JSON.stringify(compactadoArestas), "utf-8");
  console.log(`✓ Arestas de controle acionário salvas em: ${caminhoArestas} (${ARESTAS_CONTROLE.length} arestas)`);

  // 3. Compacta os indicadores setoriais HHI
  const compactadoSetores = compactar(CONCENTRACAO_SETORIAL as unknown as Record<string, unknown>[]);
  const caminhoSetores = path.join(DATA_DIR, "conglomerados-setores.compact.json");
  fs.writeFileSync(caminhoSetores, JSON.stringify(compactadoSetores), "utf-8");
  console.log(`✓ Análise de concentração setorial HHI salva em: ${caminhoSetores} (${CONCENTRACAO_SETORIAL.length} setores)`);

  console.log("🌟 ETL de Conglomerados concluído com sucesso!");
}

if (process.argv[1] && process.argv[1].endsWith("gerar-conglomerados-monopolios.mts")) {
  executarEtlConglomerados();
}
