// GERADO por `scripts/extrair-clipping-ati.mts` a partir de
// `painel-paraopeba (V1).html` (`const ATI_DATA`, a página `page-clipati`).
// Não editar à mão: rode o script de novo quando o painel-fonte mudar.
//
// Acervo histórico do painel-fonte — o portal NÃO recalcula, NÃO consulta
// API e NÃO atualiza sozinho. Como em `clipping.ts`, `PERIODO_CLIPPING_ATI`
// existe para toda tela rotular o acervo pelo período real que ele cobre.
//
// ═══ O QUE ESTE ARQUIVO TEM QUE `clipping.ts` NÃO TEM ═══
//
// `clipping.ts` guarda o clipping geral, classificado por tipo de veículo
// (imprensa, institucional, movimento, assessoria). Este guarda a curadoria
// separada que o painel mantinha na página das ATIs, com duas chaves que o
// outro acervo não tem: **qual ATI produziu** (`ati`) e **sob qual tema da
// reparação** (`tema`). São curadorias distintas, medido: dos 46 itens
// daqui, 2 apontam para uma URL que também aparece nos 149 de
// `clipping.ts`, e nenhum título se repete. Por isso os dois arrays convivem
// sem deduplicação — juntá-los apagaria a classificação temática.
//
// As três ATIs foram eleitas pelas comunidades atingidas e dividem as cinco
// regiões do processo: AEDAS (Regiões 1 e 2), NACAB (Região 3) e Instituto
// Guaicuy (Regiões 4 e 5).

/** Sigla da Assessoria Técnica Independente que produziu o material. */
export type SiglaAti = "aedas" | "nacab" | "guaicuy";

export const ATI_LABEL: Record<SiglaAti, string> = {
  aedas: "AEDAS",
  nacab: "NACAB",
  guaicuy: "Guaicuy",
};

/** Região do processo em que cada ATI atua — do cabeçalho do painel-fonte. */
export const ATI_REGIOES: Record<SiglaAti, string> = {
  aedas: "Regiões 1 e 2",
  nacab: "Região 3",
  guaicuy: "Regiões 4 e 5",
};

/** Eixo temático da reparação, como o painel-fonte classificou. */
export type TemaAti = "pericias" | "ershre" | "ambiental" | "indenizacao" | "participacao" | "ati";

export const TEMA_ATI_LABEL: Record<TemaAti, string> = {
  pericias: "Perícias Judiciais",
  ershre: "Risco à Saúde (ERSHRE)",
  ambiental: "Reparação Ambiental",
  indenizacao: "Indenização Individual",
  participacao: "Participação Popular",
  ati: "Direito à ATI",
};

/** Ordem de exibição por tema — a mesma que o painel-fonte usava. */
export const TEMA_ATI_ORDEM: TemaAti[] = ["pericias", "ershre", "ambiental", "indenizacao", "participacao", "ati"];

export interface NoticiaAti {
  id: string;
  /** Qual das três ATIs produziu o material. */
  ati: SiglaAti;
  /** Eixo temático da reparação sob o qual o painel-fonte classificou. */
  tema: TemaAti;
  titulo: string;
  /** Resumo escrito por quem montou o painel-fonte, não pelo Controle Popular. */
  resumo: string;
  data: string;
  /** Veículo/organização que publicou — nem sempre igual ao rótulo da ATI. */
  fonte: string;
  url: string;
  tags: string[];
}

/** Cobertura real do acervo — usar para rotular a tela, nunca "notícias de hoje". */
export const PERIODO_CLIPPING_ATI = {
  de: "2021-02-05",
  ate: "2026-02-13",
} as const;

export const CLIPPING_ATI: NoticiaAti[] = [
  {
    id: "pj01",
    ati: "guaicuy",
    tema: "pericias",
    titulo: "Juiz Murilo decreta inversão do ônus da prova e nomeia UFMG como perita judicial",
    resumo: "O juiz Murilo Silvio de Abreu define que a UFMG (CTC/UFMG) conduzirá as perícias que determinarão quais são os danos e seus valores. Determina também a inversão do ônus da prova: caberá à Vale provar que os danos não ocorreram. Para o Guaicuy, é uma conquista histórica que reforça décadas de mapeamento de danos pelas ATIs.",
    data: "2023-03-14",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/indenizacoes-entenda-porque-novas-decisoes-do-caso-brumadinho-sao-conquistas-para-as-pessoas-atingidas-pela-vale/",
    tags: ["perícia", "UFMG", "inversão ônus prova", "juiz Murilo", "danos individuais"],
  },
  {
    id: "pj02",
    ati: "guaicuy",
    tema: "pericias",
    titulo: "Juiz decreta início da liquidação coletiva dos danos individuais — nova etapa rumo às indenizações",
    resumo: "O juiz Murilo decreta a liquidação coletiva dos danos individuais homogêneos, determinando a construção de uma matriz de danos com participação das partes e perícia judicial da UFMG. O Guaicuy destaca que a Vale tentou bloquear a decisão, mas foi derrotada. A mineradora tem 15 dias úteis para se manifestar.",
    data: "2023-12-18",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/nova-decisao-juiz-indenizacao-avanca/",
    tags: ["liquidação coletiva", "juiz Murilo", "UFMG", "indenização", "Vale"],
  },
  {
    id: "pj03",
    ati: "guaicuy",
    tema: "pericias",
    titulo: "UFMG apresenta plano de trabalho com 26 categorias de danos para a liquidação coletiva",
    resumo: "Em audiência, a UFMG apresenta 26 categorias de danos às partes. A Vale reafirma sua posição contrária à liquidação coletiva. O TJMG havia rejeitado em outubro de 2024 todos os recursos da Vale contra a decisão de início da liquidação. A UFMG aceita elaborar perícias também para a Região 5 (entorno da Represa de Três Marias) e para Caetanópolis.",
    data: "2024-05-02",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/linha-tempo-resolucao-coletiva-indenizacoes-individuais/",
    tags: ["UFMG", "26 categorias", "danos", "plano de trabalho", "liquidação coletiva"],
  },
  {
    id: "pj04",
    ati: "guaicuy",
    tema: "pericias",
    titulo: "TJMG rejeita recursos da Vale e mantém liquidação coletiva; UFMG aceita pedidos sobre Região 5",
    resumo: "O TJMG rejeita unanimemente os recursos da Vale contra a liquidação coletiva. A UFMG informa que pode estender as perícias à Região 5 e Caetanópolis, possibilitando indenizações a comunidades antes excluídas do processo.",
    data: "2024-10-18",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/linha-tempo-resolucao-coletiva-indenizacoes-individuais/",
    tags: ["TJMG", "liquidação coletiva", "Região 5", "UFMG", "Vale"],
  },
  {
    id: "pj05",
    ati: "guaicuy",
    tema: "pericias",
    titulo: "Vale contesta metodologia da UFMG no processo das indenizações individuais",
    resumo: "A Vale volta à Justiça contestando metodologia das perícias da UFMG, defendendo que seus próprios acordos extrajudiciais encerrariam os danos coletivos. A empresa também exclui a Região 5 de sua visão dos atingidos. O Guaicuy aponta que o dossiê mostra que apenas 12 das 318 ações individuais das Regiões 4 e 5 tiveram resultado favorável em 2024.",
    data: "2025-02-14",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/vale-contesta-pericias-do-ctc-ufmg/",
    tags: ["Vale", "UFMG", "metodologia", "contestação", "indenização individual"],
  },
  {
    id: "pj06",
    ati: "guaicuy",
    tema: "pericias",
    titulo: "Juiz suspende ações individuais e determina que liquidação coletiva avance",
    resumo: "O juiz suspende todas as ações individuais de reparação nas comarcas mineiras para evitar conflito com a liquidação coletiva. A UFMG é intimada a verificar identidade entre metais dos rejeitos e impactos na Região 5, especialmente quanto à qualidade da água, solo e peixes.",
    data: "2025-03-05",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/juiz-suspende-acoes-individuais-por-indenizacoes/",
    tags: ["juiz Murilo", "ações individuais", "liquidação coletiva", "UFMG", "Região 5"],
  },
  {
    id: "pj07",
    ati: "nacab",
    tema: "pericias",
    titulo: "MPMG mantém posição de defesa da liquidação coletiva frente a questionamentos da Vale",
    resumo: "O MPMG sustenta que o TC firmado com a DPMG não esgota os danos e que a perícia do CTC/UFMG é necessária para apurar a totalidade. A mineradora não pode escolher a quem pagar. Para o NACAB, a liquidação coletiva é a via mais justa para garantir indenizações equitativas a todas as pessoas atingidas.",
    data: "2025-02-05",
    fonte: "NACAB",
    url: "https://nacab.org.br/ministeriopublicomantemposicionamento/",
    tags: ["MPMG", "liquidação coletiva", "Vale", "Termo de Compromisso", "PNAB"],
  },
  {
    id: "pj08",
    ati: "nacab",
    tema: "pericias",
    titulo: "Justiça suspende ações individuais para garantir avanço da liquidação coletiva",
    resumo: "O juiz Murilo decreta a suspensão de todas as ações individuais de reparação em andamento nas comarcas mineiras. Um estudo do NACAB com amostra representativa revelou que 80% das ações individuais tiveram resultados desfavoráveis ou indenizações muito baixas. A liquidação coletiva é considerada a via mais adequada pelas IJs.",
    data: "2025-03-19",
    fonte: "NACAB",
    url: "https://nacab.org.br/justica-suspende-acoes-individuais-de-reparacao/",
    tags: ["liquidação coletiva", "ações individuais", "NACAB", "suspensão", "juiz Murilo"],
  },
  {
    id: "pj09",
    ati: "nacab",
    tema: "pericias",
    titulo: "Vale recorre ao STJ tentando reverter a liquidação coletiva das indenizações",
    resumo: "A Vale apresenta REsp no STJ buscando reverter a decisão do TJMG que manteve a liquidação coletiva. O NACAB alerta: enquanto o STJ decide, a liquidação continua válida. Para as IJs, a via coletiva é a mais adequada para garantir reparação justa a todas as pessoas atingidas.",
    data: "2025-04-11",
    fonte: "NACAB",
    url: "https://nacab.org.br/vale-insiste-em-impedir-liquidacao-coletiva-das-indenizacoes-individuais/",
    tags: ["Vale", "STJ", "liquidação coletiva", "recurso", "indenização individual"],
  },
  {
    id: "pj10",
    ati: "nacab",
    tema: "pericias",
    titulo: "TJMG publica decisões favoráveis sobre prescrição, usando prazo de 5 anos do CDC",
    resumo: "O TJMG define que as ações individuais dos atingidos têm prazo prescricional de 5 anos (art. 27 do CDC), não 3 anos do Código Civil. O prazo começa no trânsito em julgado do Acordo (fev/2021). As ações coletivas também suspendem o prazo das individuais. As ATIs haviam antecipado esse debate em cartilha de 2021.",
    data: "2023-08-02",
    fonte: "NACAB",
    url: "https://nacab.org.br/tribunal-de-justica-publica-decisoes-favoraveis-as-pessoas-atingidas-sobre-a-prescricao/",
    tags: ["prescrição", "TJMG", "5 anos", "CDC", "ações individuais"],
  },
  {
    id: "pj11",
    ati: "guaicuy",
    tema: "pericias",
    titulo: "UFMG apresenta resultados das perícias na Audiência de Contextualização do TJMG",
    resumo: "Na Audiência de Contextualização do TJMG, o CTC/UFMG apresenta os estudos periciando os danos do rompimento. É a primeira vez que os atingidos acompanham presencialmente as evidências periciais. A Vale critica a metodologia. AEDAS, NACAB e Guaicuy estão presentes como ouvintes.",
    data: "2025-11-28",
    fonte: "AEDAS",
    url: "https://aedasmg.org/ufmg-ctc-audiencia-projeto-brumadinho/",
    tags: ["UFMG", "CTC", "audiência", "TJMG", "danos", "Vale"],
  },
  {
    id: "er01",
    ati: "aedas",
    tema: "ershre",
    titulo: "Entenda o Plano de Reparação Socioambiental e os Estudos de Risco à Saúde Humana",
    resumo: "A AEDAS explica que o Acordo prevê Estudos de Avaliação de Risco à Saúde Humana e Risco Ecológico (ERSHRE), conduzidos pelo Grupo EPA (depois substituído pela ERM). O objetivo é identificar riscos potenciais à saúde pela presença de rejeitos no solo e na água e definir estratégias de intervenção.",
    data: "2022-09-02",
    fonte: "AEDAS",
    url: "https://aedasmg.org/entenda-o-plano-de-reparacao-socioambiental/",
    tags: ["ERSHRE", "EPA", "ERM", "risco saúde", "Paraopeba"],
  },
  {
    id: "er02",
    ati: "guaicuy",
    tema: "ershre",
    titulo: "Guaicuy divulga análises de água no Paraopeba: alumínio e ferro acima dos limites em 10 de 12 pontos",
    resumo: "O Guaicuy realiza análises independentes em 12 pontos do Baixo Paraopeba e da Represa de Três Marias. Em 10 deles, os níveis de alumínio e ferro estão acima do limite permitido. O estudo serve de base para futuras pesquisas sobre qualidade da água nas comunidades atingidas.",
    data: "2022-06-01",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/analises-aguas-rio-paraopeba-e-represa-de-tres-marias/",
    tags: ["água", "metais", "alumínio", "ferro", "Três Marias", "Guaicuy"],
  },
  {
    id: "er03",
    ati: "guaicuy",
    tema: "ershre",
    titulo: "Conheça os contaminantes encontrados nas análises do Paraopeba e os riscos para a saúde",
    resumo: "O Guaicuy detalha os contaminantes encontrados nas análises: alumínio (retardo neurológico em crianças e fetos), ferro, zinco, arsênio, cádmio, cromo, manganês e mercúrio. Conclui que o rompimento da Vale é a hipótese mais forte para a contaminação, mas que a origem precisa de mais estudos.",
    data: "2022-03-17",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/artigo-conheca-as-substancias-encontradas-nas-analises-e-a-relacao-com-sua-saude/",
    tags: ["metais pesados", "arsênio", "alumínio", "ferro", "saúde", "crianças"],
  },
  {
    id: "er04",
    ati: "guaicuy",
    tema: "ershre",
    titulo: "UFMG divulga resultados: 63,5% das amostras de água subterrânea violam limites legais no Paraopeba",
    resumo: "O CTC/UFMG revela que 63,5% das 52 amostras de água subterrânea violam limites legais (Resolução CONAMA 396/2008). Foram identificadas 145 substâncias nocivas não previstas em lei, incluindo agrotóxicos da família dos endosulfans, benzeno e seus derivados, e etilbenzeno. O estudo recomenda continuidade das análises na Região 5.",
    data: "2023-08-21",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/resumo-dos-resultados-de-pesquisas-realizadas-pelo-ctc-ufmg/",
    tags: ["UFMG", "água subterrânea", "contaminação", "agrotóxicos", "metais", "63%"],
  },
  {
    id: "er05",
    ati: "guaicuy",
    tema: "ershre",
    titulo: "Evento Guaicuy: dados ambientais e de saúde de 10 municípios, de Curvelo a Três Marias",
    resumo: "No 5º aniversário do rompimento, o Guaicuy divulga dados ambientais e de saúde coletados nas Regiões 4 e 5. Foram constatadas alterações em peixes livres, metais em sedimentos e análises de saúde das comunidades com perspectivas sociais, biológicas e ambientais. Os dados são disponibilizados no site do Instituto.",
    data: "2024-01-24",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/guaicuy-realiza-evento-para-divulgar-dados/",
    tags: ["saúde", "metais", "peixes", "sedimentos", "Baixo Paraopeba", "Três Marias"],
  },
  {
    id: "er06",
    ati: "guaicuy",
    tema: "ershre",
    titulo: "Audiência na ALMG debate política pública de saúde para comunidades atingidas pela mineração",
    resumo: "A Comissão de Direitos Humanos da ALMG debate política de saúde para comunidades atingidas. A promotora Vanessa Campolina cita o estudo da Fiocruz de 2022, que mostrou adultos e crianças com metais pesados acima do valor de referência. O SUS não está preparado para monitorar exposição a metais com protocolos específicos para atingidos.",
    data: "2024-09-25",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/audiencia-discute-politica-publica-direcionada-a-saude-de-pessoas-atingidas-pela-mineracao/",
    tags: ["ALMG", "saúde", "metais pesados", "Fiocruz", "SUS", "mineração"],
  },
  {
    id: "er07",
    ati: "aedas",
    tema: "ershre",
    titulo: "Informe AECOM (mai/2024): ERSHRE não é discutido; dragagem no trecho 0–550m ainda não finalizada",
    resumo: "A AEDAS informa que a reunião mensal da AECOM de maio de 2024 não abordou o ERSHRE. A dragagem do trecho 0–550m do Paraopeba ainda não foi finalizada, com atraso em relação ao planejado. O promotor Lucas Trindade aguarda notas técnicas sobre riscos de contaminação das águas subterrâneas — solicitadas desde julho de 2023.",
    data: "2024-05-01",
    fonte: "AEDAS",
    url: "https://aedasmg.org/informes-aecom-0524/",
    tags: ["AECOM", "ERSHRE", "auditoria", "dragagem", "cronograma"],
  },
  {
    id: "er08",
    ati: "nacab",
    tema: "ershre",
    titulo: "Estudo do NACAB: rejeitos da Vale foram remobilizados pelas cheias de 2022, revitimizando ~2 mil pessoas",
    resumo: "Estudo científico do NACAB publicado na revista Remote Sensing Applications Society and Environment comprova, por imagens de satélite, que os rejeitos depositados no fundo do Paraopeba foram transportados pelas cheias de 2020 e 2022 para novas áreas. Uma região de ~24 milhões de m² apresentou aumento de material ferroso. Cerca de 2 mil pessoas são 'revitimizadas' com contaminação não prevista inicialmente.",
    data: "2026-01-26",
    fonte: "NACAB",
    url: "https://nacab.org.br/rejeitos-vale-avancam-novas-areas-chuvas/",
    tags: ["rejeitos", "cheias 2022", "remobilização", "satélite", "Remote Sensing", "NACAB"],
  },
  {
    id: "ra01",
    ati: "aedas",
    tema: "ambiental",
    titulo: "Auditoria AECOM aponta atrasos expressivos na reparação socioambiental em carta ao MPMG",
    resumo: "A AECOM encaminha ao MPMG carta técnica revelando atrasos expressivos nos principais projetos do Plano de Reparação Socioambiental: remoção de rejeitos, recuperação do ribeirão Ferro-Carvão, dragagem dos primeiros 2km do Paraopeba e construção da nova captação de água. Os cronogramas foram repetidamente revisados para datas mais distantes.",
    data: "2024-04-01",
    fonte: "AEDAS",
    url: "https://aedasmg.org/auditoria-socioambiental-paraopeba-1205/",
    tags: ["AECOM", "auditoria", "atrasos", "dragagem", "Ferro-Carvão", "remoção de rejeitos"],
  },
  {
    id: "ra02",
    ati: "aedas",
    tema: "ambiental",
    titulo: "Informe AECOM (mai/2024): dragagem prevista para 2024 adiada para agosto de 2025; cronograma de 46km adiado para 2027",
    resumo: "A AEDAS informa que a Vale, que previa finalizar os 6km iniciais de dragagem em 2024, avançou pouco — o trecho 0–550m ainda não foi concluído. O novo cronograma prevê a finalização dos primeiros 2km para agosto de 2025 e o total de 46km somente em dezembro de 2027.",
    data: "2024-05-21",
    fonte: "AEDAS",
    url: "https://aedasmg.org/informes-aecom-0524/",
    tags: ["AECOM", "dragagem", "Paraopeba", "cronograma", "2027", "atraso"],
  },
  {
    id: "ra03",
    ati: "guaicuy",
    tema: "ambiental",
    titulo: "Plano de Manejo de Rejeitos: contaminação de manganês identificada em águas subterrâneas",
    resumo: "O Guaicuy explica o Plano de Manejo de Rejeitos: o ribeirão Ferro-Carvão segue com sua estação de tratamento comprometida. A contaminação de manganês foi identificada nas águas subterrâneas pelos estudos do PRSABP. Enquanto o sistema de disposição final dos rejeitos não for concluído, os contaminantes continuarão carregados para outras áreas nos períodos chuvosos.",
    data: "2023-06-15",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/confira-os-principais-pontos-sobre-o-plano-de-manejo-de-rejeitos-parte-do-plano-de-reparacao-socioambiental-da-bacia-do-paraopeba/",
    tags: ["rejeitos", "água subterrânea", "manganês", "Ferro-Carvão", "cava", "contaminação"],
  },
  {
    id: "ra04",
    ati: "aedas",
    tema: "ambiental",
    titulo: "Informe AECOM (abr/2025): dragagem adiada para 2027–2028; disposição final de rejeitos para 2030",
    resumo: "A AEDAS divulga que o cronograma de dragagem foi novamente revisado: conclusão adiada para entre 2027 e 2028. A previsão de finalização do lançamento de rejeitos em cava foi postergada para 2030. Permanecem sem resposta os pedidos de notas técnicas sobre o risco de contaminação das águas subterrâneas por rejeitos na cava, solicitados desde 2023.",
    data: "2025-04-01",
    fonte: "AEDAS",
    url: "https://aedasmg.org/informes-aecom-0425/",
    tags: ["AECOM", "dragagem", "2027", "2028", "rejeitos", "cava", "cronograma"],
  },
  {
    id: "ra05",
    ati: "aedas",
    tema: "ambiental",
    titulo: "Informe AECOM (dez/2025): obras de dragagem previstas entre 2028 e 2029; margens e vegetação ciliar só a partir de 2027",
    resumo: "A AEDAS informa o novo horizonte: conclusão das obras de dragagem entre 2028 e 2029. Algumas ações de recuperação de margens e vegetação ciliar (trecho do ribeirão Ferro-Carvão até 6km do Paraopeba) só poderão começar a partir de fevereiro de 2027. A qualidade do ar também deve ser monitorada durante as obras de dragagem, transporte e secagem de rejeitos.",
    data: "2025-12-01",
    fonte: "AEDAS",
    url: "https://aedasmg.org/documento/informes-aecom-1225/",
    tags: ["AECOM", "dragagem", "2028", "2029", "vegetação ciliar", "cronograma"],
  },
  {
    id: "ra06",
    ati: "nacab",
    tema: "ambiental",
    titulo: "Rejeitos do Paraopeba: cheias de 2022 remobilizaram os depósitos e ampliaram área contaminada",
    resumo: "As cheias de janeiro de 2022 remobilizaram os rejeitos depositados no fundo do Paraopeba, ampliando a área contaminada. Moradores de Cachoeira do Choro relatam que a água do poço ficou escura novamente. O estudo posterior do NACAB comprovou, por imagens de satélite, a redistribuição de material ferroso em ~24 milhões de m².",
    data: "2022-01-26",
    fonte: "NACAB",
    url: "https://nacab.org.br/rejeitos-vale-avancam-novas-areas-chuvas/",
    tags: ["rejeitos", "cheias", "2022", "remobilização", "Paraopeba", "contaminação"],
  },
  {
    id: "ra07",
    ati: "aedas",
    tema: "ambiental",
    titulo: "Quem é quem na reparação de Brumadinho: AECOM, EPA, ERSHRE e as ATIs",
    resumo: "A AEDAS explica os papéis dos atores na reparação: a AECOM conduz mensalmente a auditoria dos estudos socioambientais; o Grupo EPA (depois ERM) é responsável pelo ERSHRE. As ATIs participam das reuniões mensais da AECOM apenas como ouvintes, sem direito a fala.",
    data: "2022-09-02",
    fonte: "AEDAS",
    url: "https://aedasmg.org/quem-e-quem-na-reparacao-dos-danos-causados-pelo-rompimento-da-barragem-em-brumadinho/",
    tags: ["AECOM", "EPA", "ERM", "ERSHRE", "ATI", "auditoria socioambiental"],
  },
  {
    id: "in01",
    ati: "nacab",
    tema: "indenizacao",
    titulo: "Pesquisa do NACAB: 80% das ações individuais contra a Vale têm resultado desfavorável ou indenizações baixas",
    resumo: "Pesquisa jurisprudencial do NACAB com amostra representativa das ações individuais no TJMG revela que 80% dos processos tiveram resultado desfavorável ou indenizações muito baixas. O estudo fundamentou a posição das ATIs em favor da liquidação coletiva como via mais adequada e justa para os atingidos.",
    data: "2023-01-01",
    fonte: "NACAB",
    url: "https://nacab.org.br/justica-suspende-acoes-individuais-de-reparacao/",
    tags: ["ações individuais", "NACAB", "pesquisa", "80%", "TJMG", "Vale"],
  },
  {
    id: "in02",
    ati: "nacab",
    tema: "indenizacao",
    titulo: "Acordo de Reparação: perguntas e respostas — PTR não é descontado das indenizações individuais",
    resumo: "O NACAB esclarece que o PTR não se confunde com as indenizações individuais: não são descontadas e não excludentes. Define também que 'atingido' tem critério mais amplo que o do PTR. As ATIs continuam atuando como assistentes técnicos das IJs após o Acordo.",
    data: "2021-02-05",
    fonte: "NACAB",
    url: "https://nacab.org.br/perguntas-frequentes-sobre-o-acordo-assinado-entre-governo-de-minas-ijs-e-vale/",
    tags: ["Acordo", "PTR", "indenização individual", "NACAB", "critérios"],
  },
  {
    id: "in03",
    ati: "aedas",
    tema: "indenizacao",
    titulo: "Sistema AgroPesca: ATI orienta pescadores e agricultores sobre prazo para indenizações",
    resumo: "A AEDAS informa sobre o Sistema AgroPesca para solicitação de indenizações individuais específicas para pescadores profissionais e agricultores familiares. O prazo para adesão é de 60 dias a partir de 5 de abril de 2025. A ATI orienta os atingidos a buscar o mobilizador de referência de seu território.",
    data: "2025-04-05",
    fonte: "AEDAS",
    url: "https://aedasmg.org/2025/04/11/sistema-agro-pesca-mineradora-samarco-disponibiliza-plataforma-de-solicitacao-das-indenizacoes-individuais-especificas-para-pescadoresas-e-agricultoresas-familiares/",
    tags: ["AgroPesca", "pescadores", "agricultores", "indenização", "prazo", "60 dias"],
  },
  {
    id: "in04",
    ati: "guaicuy",
    tema: "indenizacao",
    titulo: "CTC/UFMG apoia extensão de perícias à Região 5 e inclui 8 novas categorias de danos",
    resumo: "O CTC/UFMG se manifesta positivamente sobre a extensão das perícias à Região 5 e Caetanópolis e apoia a inclusão de 8 novas categorias de danos, como danos às relações de produção e trabalho, direito à moradia, e danos por ações e omissões das empresas responsáveis.",
    data: "2024-11-07",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/ctc-ufmg-se-manifesta-sobre-pedidos-relativos-a-resolucao-coletiva-das-indenizacoes/",
    tags: ["UFMG", "Região 5", "categorias", "danos", "moradia", "produção", "indenização"],
  },
  {
    id: "in05",
    ati: "aedas",
    tema: "indenizacao",
    titulo: "AEDAS lança Matriz de Danos para orientar as comunidades atingidas no processo de indenização",
    resumo: "A AEDAS apresenta a Matriz de Danos, documento construído com as comunidades das Regiões 1 e 2, mapeando os prejuízos individuais e coletivos causados pelo rompimento. O documento serve de base para as perícias judiciais e para garantir que os atingidos conheçam seus direitos antes de qualquer negociação individual com a Vale.",
    data: "2022-01-25",
    fonte: "AEDAS",
    url: "https://aedasmg.org/brumadinho/",
    tags: ["Matriz de Danos", "AEDAS", "indenização", "comunidades", "mapeamento"],
  },
  {
    id: "in06",
    ati: "nacab",
    tema: "indenizacao",
    titulo: "MPMG: Termo de Compromisso da DPMG com a Vale tem cláusula que garante diferença nas conquistas coletivas futuras",
    resumo: "O MPMG aponta que a cláusula 15 do TC com a DPMG garante que, caso os atingidos que já fecharam acordo individual obtenham benefícios adicionais pela via coletiva, a Vale deverá pagar a diferença. O TC deve ser visto como valor mínimo, não como encerramento dos danos.",
    data: "2025-02-05",
    fonte: "NACAB",
    url: "https://nacab.org.br/ministeriopublicomantemposicionamento/",
    tags: ["Termo de Compromisso", "DPMG", "MPMG", "conquistas coletivas", "mínimo indenizatório"],
  },
  {
    id: "in07",
    ati: "guaicuy",
    tema: "indenizacao",
    titulo: "Vale critica perícias da UFMG e afirma que dados de 2021–2022 não refletem situação atual",
    resumo: "Após a Audiência de Contextualização do TJMG, a Vale contesta os resultados da UFMG alegando que os dados de 2021–2022 não representam a situação atual e que os danos coletivos foram resolvidos pelo Acordo. O Guaicuy rebate: 80% das ações individuais das Regiões 4 e 5 foram desfavoráveis aos atingidos, demonstrando que a reparação não foi integral.",
    data: "2026-02-13",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/vale-critica-pericias-da-ufmg/",
    tags: ["Vale", "UFMG", "perícia", "contestação", "danos coletivos", "Acordo"],
  },
  {
    id: "pp01",
    ati: "guaicuy",
    tema: "participacao",
    titulo: "Entenda o Acordo: Anexo 1.1 destina R$ 3 bilhões a projetos definidos pelas próprias comunidades",
    resumo: "O Guaicuy explica que o Anexo 1.1 é o único do Acordo que exige participação das pessoas atingidas em todas as etapas. Prevê R$ 3 bilhões para projetos de demandas das comunidades nos 26 municípios da Bacia do Paraopeba, com governança popular e microcrédito.",
    data: "2021-02-05",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/ati/ati-paraopeba/reparacao/acordo/anexo-1-1/",
    tags: ["Anexo 1.1", "R$ 3 bilhões", "participação popular", "comunidades", "Acordo"],
  },
  {
    id: "pp02",
    ati: "nacab",
    tema: "participacao",
    titulo: "NACAB realiza 32 reuniões com comissões da Região 3 para construir governança do Anexo 1.1",
    resumo: "O NACAB realizou 32 reuniões com comissões de atingidos da Região 3 entre ago/2021 e jun/2022. Cerca de mil pessoas, em 10 municípios, participaram do debate sobre formas de organização e governança dos R$ 3 bilhões. As ATIs publicam caderno conjunto sobre a proposta de Sistema de Participação.",
    data: "2022-04-13",
    fonte: "NACAB",
    url: "https://nacab.org.br/projetos-das-comunidades-atingidas-quem-decide/",
    tags: ["Anexo 1.1", "NACAB", "Região 3", "governança", "participação popular", "1000 pessoas"],
  },
  {
    id: "pp03",
    ati: "aedas",
    tema: "participacao",
    titulo: "AEDAS: entenda o Anexo 1.1 e a governança popular dos R$ 3 bilhões",
    resumo: "A AEDAS explica a estrutura do Anexo 1.1: as comunidades definem coletivamente os projetos e as políticas de microcrédito, com assessoria das ATIs. A governança deve garantir economicidade, soberania popular, transparência e reparação integral. A AEDAS realizou rodas de conversa, cartografia social e coletas de água e solo como base para as propostas.",
    data: "2022-06-09",
    fonte: "AEDAS",
    url: "https://aedasmg.org/participacao_comunidades_anexo/",
    tags: ["Anexo 1.1", "governança popular", "comunidades", "Região 2", "AEDAS", "microcrédito"],
  },
  {
    id: "pp04",
    ati: "guaicuy",
    tema: "participacao",
    titulo: "Cáritas MG é selecionada como Entidade Gestora do Anexo 1.1 pelos compromitentes",
    resumo: "As IJs selecionam o consórcio liderado pela Cáritas Brasileira Regional MG (com ANAB e Instituto E-Dinheiro Brasil) para gerir o Anexo 1.1. Em março de 2024, IJs e Entidade Gestora assinam Termo de Colaboração para os 90 dias de construção do Plano de Ação.",
    data: "2023-03-01",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/juiz-determina-inicio-execucao-anexo-1-1/",
    tags: ["Cáritas MG", "Entidade Gestora", "Anexo 1.1", "ANAB", "IJs", "seleção"],
  },
  {
    id: "pp05",
    ati: "guaicuy",
    tema: "participacao",
    titulo: "Juiz determina início imediato da execução do Anexo 1.1 com participação das ATIs",
    resumo: "O juiz determina o início imediato da execução do Anexo 1.1, com assessoramento preferencialmente pelas ATIs já presentes. Guaicuy, AEDAS e NACAB têm 30 dias para assinar Termo Aditivo de Compromisso. O Guaicuy aponta avanço, mas questiona que a verba das ATIs saísse dos juros do próprio Anexo 1.1, destinado diretamente aos atingidos.",
    data: "2025-04-30",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/juiz-determina-inicio-execucao-anexo-1-1/",
    tags: ["Anexo 1.1", "juiz", "execução", "ATI", "Cáritas MG", "Termo Aditivo"],
  },
  {
    id: "pp06",
    ati: "nacab",
    tema: "participacao",
    titulo: "Perguntas e respostas: Projetos para a Bacia do Paraopeba (Anexo 1.3)",
    resumo: "O NACAB esclarece dúvidas das comunidades sobre o Anexo 1.3 (R$ 2,5 bilhões para projetos de fortalecimento de serviços públicos nos 25 municípios). As perguntas foram respondidas pelos compromitentes em reunião de agosto de 2022. O Nacab garante o registro e a disseminação das respostas para todas as regiões.",
    data: "2022-06-07",
    fonte: "NACAB",
    url: "https://nacab.org.br/perguntas-e-respostas-projetos-para-a-bacia-do-paraopeba-anexo-1-3/",
    tags: ["Anexo 1.3", "Paraopeba", "projetos", "R$ 2,5 bilhões", "NACAB", "IJs"],
  },
  {
    id: "pp07",
    ati: "guaicuy",
    tema: "participacao",
    titulo: "Compromitentes respondem dúvidas das comunidades sobre a execução do Acordo de Reparação",
    resumo: "O Comitê de Compromitentes realiza live com representantes das cinco regiões e as ATIs para responder dúvidas sobre a execução dos Anexos 1.1 a 1.4. As perguntas e respostas são publicadas no site do Comitê Pró-Brumadinho. O Guaicuy destaca o direito à participação informada como base do processo.",
    data: "2021-04-25",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/execucao-do-acordo-de-reparacao/",
    tags: ["Acordo", "compromitentes", "dúvidas", "comunidades", "ATI", "Anexos 1.1–1.4"],
  },
  {
    id: "pp08",
    ati: "aedas",
    tema: "participacao",
    titulo: "AEDAS lança caderno com balanço de vulnerabilidades nas Regiões 1 e 2 (2022–2024)",
    resumo: "A AEDAS publica caderno com balanço das demandas de acompanhamento das vulnerabilidades nas Regiões 1 e 2 entre janeiro e outubro de 2024. Os dados foram coletados via Aplicativo de Registro de Demandas. O material orienta ações de reparação integral para as comunidades atingidas.",
    data: "2024-12-23",
    fonte: "AEDAS",
    url: "https://aedasmg.org/2025/04/22/caderno-balanco-demanda-vulnerabilidade-regiao1e2/",
    tags: ["AEDAS", "vulnerabilidade", "caderno", "Regiões 1 e 2", "2024", "mapeamento"],
  },
  {
    id: "at01",
    ati: "guaicuy",
    tema: "ati",
    titulo: "Audiência na ALMG debate o direito à ATI para comunidades atingidas por barragens",
    resumo: "A Comissão de Direitos Humanos da ALMG realiza audiência sobre a importância das ATIs para as comunidades atingidas. Deputadas Bella Gonçalves, Leninha e Beatriz Cerqueira solicitam a audiência. Representantes dos atingidos afirmam: 'Sem as ATIs os Anexos do Acordo não seriam executados de forma adequada e participativa.'",
    data: "2022-05-25",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/movimentacoes-em-defesa-da-ati/",
    tags: ["ATI", "ALMG", "direito", "audiência", "comunidades", "atingidos"],
  },
  {
    id: "at02",
    ati: "guaicuy",
    tema: "ati",
    titulo: "IJs cortam 48% do orçamento das ATIs sem consulta prévia — comunidades reagem",
    resumo: "No início de março de 2023, as IJs comunicam às ATIs um corte de 48% do orçamento sem consulta prévia, desconsiderando gastos já realizados em janeiro e fevereiro. O deputado federal Patrus Ananias denuncia que o corte contraria o plano de desmobilização gradual aprovado. Deputadas e deputados solicitam reunião urgente com o MPMG.",
    data: "2023-03-01",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/movimentacoes-em-defesa-da-ati/",
    tags: ["ATI", "corte orçamentário", "48%", "IJs", "MPMG", "MPF", "DPMG"],
  },
  {
    id: "at03",
    ati: "aedas",
    tema: "ati",
    titulo: "Ato em BH: atingidos protestam contra precarização das ATIs e cobram auxílio emergencial",
    resumo: "Centenas de lideranças marcham em Belo Horizonte exigindo o auxílio emergencial e contra o corte de 61% no orçamento das ATIs. O ato denuncia que a precarização das assessorias técnicas compromete diretamente o exercício do direito à participação informada das comunidades.",
    data: "2025-07-14",
    fonte: "AEDAS",
    url: "https://aedasmg.org/ato-11-de-julho-2025-atingidos-atingidas-paraopeba/",
    tags: ["ATI", "protesto", "BH", "corte", "61%", "auxílio emergencial"],
  },
  {
    id: "at04",
    ati: "nacab",
    tema: "ati",
    titulo: "IJs lançam edital para seleção de nova ATI — NACAB, AEDAS e Guaicuy denunciam exclusão",
    resumo: "As IJs lançam edital para nova ATI sem garantir a continuidade das três já atuantes. NACAB, AEDAS e Guaicuy denunciam que o processo desconsidera os vínculos construídos com as comunidades e compromete a reparação integral, especialmente no momento em que o processo das indenizações individuais avança.",
    data: "2025-10-31",
    fonte: "NACAB",
    url: "https://nacab.org.br/julgamento-auxilio-vale-limita-atis/",
    tags: ["ATI", "edital", "seleção", "IJs", "NACAB", "AEDAS", "Guaicuy"],
  },
  {
    id: "at05",
    ati: "guaicuy",
    tema: "ati",
    titulo: "O papel das ATIs no Acordo de Reparação: assistentes técnicas das IJs com recursos garantidos",
    resumo: "O Guaicuy explica que o Acordo prevê recursos expressamente para as ATIs e as define como assistentes técnicas das IJs na coleta de provas até fevereiro de 2022. As ATIs fomentam a participação informada das comunidades em todas as etapas, incluindo a construção dos planos de trabalho das perícias.",
    data: "2021-02-05",
    fonte: "Instituto Guaicuy",
    url: "https://guaicuy.org.br/6-pontos-que-voce-precisa-saber-sobre-os-projetos-de-demandas-das-comunidades-atingidas-anexo-1-1/",
    tags: ["ATI", "Acordo", "IJs", "assistente técnico", "recursos", "participação informada"],
  },
];
