#!/usr/bin/env node
/**
 * @file scripts/etl/recursos/gerar-consumidores-recursos.mts
 * @description Gerador ETL dos 50 maiores consumidores corporativos de água, energia,
 * combustível, maiores empregadores e movimentadores de capital em Minas Gerais e nos 20 países do G20.
 *
 * Papel no portal:
 * Produz os três datasets estáticos compactados em apps/web/data/recursos/:
 * 1. top50-mg-consumidores.compact.json (Top 50 corporações/operações em MG por água, energia, combustível, emprego e capital)
 * 2. g20-consumo-setorial-corporativo.compact.json (Os 20 países do G20 com dados FAO Aquastat, World Bank, US EIA, EPA ECHO, ECCC NPRI, Climate TRACE e Eurostat)
 * 3. pegada-hidrica-e-cnae.compact.json (Pegada hídrica/energética por commodity exportada e geração de empregos por CNAE vs intensidade de recursos)
 *
 * Fontes oficiais:
 * - IGAM / IDE-Sisema MG & ANA CNARH (Outorgas de recursos hídricos superficiais e subterrâneos)
 * - CCEE InfoMercado (Consumidores Livres ACL) & ANEEL SAMP (Mercado Cativo e Tarifas)
 * - ANP Dados Abertos & Climate TRACE (Consumo de óleo diesel, combustível industrial e gás)
 * - Ministério do Trabalho RAIS / CAGED & Receita Federal (Vínculos formais por CNPJ raiz e CNAE)
 * - CVM DFP, ANM CFEM, SEC EDGAR, TSX e Companies House (Movimentação de capital e receita)
 * - FAO Aquastat, World Bank Open Data, US EIA e OIT/ILOSTAT (Indicadores macro e setoriais do G20)
 *
 * Decisões técnicas e restrições:
 * - Compactação via lib/estatico/compactar.ts (esqueleto + dicionários internados).
 * - Sanitização rigorosa contra dados pessoais (Zero CPF Mod-11).
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compactar } from "../../../apps/web/lib/estatico/compactar.js";
import { sanitizarDadoPessoalInternacional } from "../../../apps/web/lib/internacional/privacidade-internacional.js";

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const DIR_OUT = path.join(RAIZ, "apps", "web", "data", "recursos");

// ══════════════════════════════════════════════════════════════════════════
// 1. TOP 50 MAIORES CONSUMIDORES CORPORATIVOS DE MINAS GERAIS
// Totais Estaduais de Referência (MG - Medição Consolidada IGAM/ANA, CCEE/ANEEL, ANP, RAIS, IBGE):
// - Água Outorgada Total MG (Uso Consultivo Anual): ~4.250.000.000 m³/ano (4,25 bilhões m³/ano)
// - Energia Elétrica Total MG (Consumo Anual): ~64.000.000 MWh/ano (64 TWh/ano)
// - Combustível Fóssil Industrial/Frota MG: ~8.500.000.000 litros/ano (8,5 bilhões L/ano)
// - Empregos Formais Totais MG (RAIS/CAGED): ~4.650.000 vínculos formais ativos
// - PIB / Movimentação Corporativa Referência MG: ~R$ 1.050.000.000.000 (R$ 1,05 trilhão)
// ══════════════════════════════════════════════════════════════════════════

export const TOP_50_MG_CONSUMIDORES = [
  {
    id: "mg-cons-01",
    rankGeral: 1,
    empresa: "Vale S.A. (Complexo Itabira — Cauê, Conceição e Minas do Meio)",
    grupoEconomico: "Vale S.A.",
    cnpjRaiz: "33.592.510",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3131703",
    municipioNome: "Itabira",
    baciaHidrografica: "Rio Doce (Piracicaba)",
    aguaOutorgadaM3Ano: 98500000,
    energiaConsumidaMwhAno: 2850000,
    combustivelLitrosAno: 195000000,
    empregosDiretos: 14200,
    capitalMovimentadoBrl: 42500000000,
    tarifaAguaEmpresaBrlM3: 0.028,
    tarifaAguaCidadaoBrlM3: 8.92,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / ANA CNARH Outorgas",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado ACL / Autoprodutor",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Relatório de Sustentabilidade Vale",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "MTE RAIS / CVM DFP / ANM CFEM",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-02",
    rankGeral: 2,
    empresa: "Petrobras — Refinaria Gabriel Passos (REGAP)",
    grupoEconomico: "Petrobras S.A.",
    cnpjRaiz: "33.000.167",
    setorCnae: "1921-7 Fabricação de produtos do refino de petróleo",
    categoriaSetor: "Petróleo, Gás & Combustíveis",
    codigoIbgeMunicipio: "3106705",
    municipioNome: "Betim",
    baciaHidrografica: "Rio Paraopeba (Lagoa Várzea das Flores / Rio Betim)",
    aguaOutorgadaM3Ano: 34200000,
    energiaConsumidaMwhAno: 1640000,
    combustivelLitrosAno: 310000000,
    empregosDiretos: 4850,
    capitalMovimentadoBrl: 58400000000,
    tarifaAguaEmpresaBrlM3: 0.032,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.19,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Bacia Paraopeba",
    urlFonteAgua: "https://ecosistemas.meioambiente.mg.gov.br/sim/",
    fonteEnergia: "CCEE / Termelétrica Ibirité Autogeração",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Climate TRACE Refineries",
    urlFonteCombustivel: "https://climatetrace.org/",
    fonteEmpregoCapital: "CVM DFP Petrobras / RAIS MTE",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-03",
    rankGeral: 3,
    empresa: "Usiminas — Usina Intendente Câmara",
    grupoEconomico: "Usiminas S.A.",
    cnpjRaiz: "60.894.730",
    setorCnae: "2421-1 Produção de semiacabados de aço",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3131307",
    municipioNome: "Ipatinga",
    baciaHidrografica: "Rio Doce (Rio Piracicaba)",
    aguaOutorgadaM3Ano: 86400000,
    energiaConsumidaMwhAno: 3420000,
    combustivelLitrosAno: 148000000,
    empregosDiretos: 12800,
    capitalMovimentadoBrl: 27600000000,
    tarifaAguaEmpresaBrlM3: 0.025,
    tarifaAguaCidadaoBrlM3: 8.85,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / CBH Piracicaba e Rio Doce",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado Consumidor Livre",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Inventário GEE Usiminas",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "CVM DFP Usiminas / RAIS MTE",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-04",
    rankGeral: 4,
    empresa: "Gerdau Açominas — Usina Ouro Branco",
    grupoEconomico: "Gerdau S.A.",
    cnpjRaiz: "33.611.500",
    setorCnae: "2422-9 Produção de laminados planos de aço",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3145901",
    municipioNome: "Ouro Branco",
    baciaHidrografica: "Rio Paraopeba / Alto Rio Doce",
    aguaOutorgadaM3Ano: 74500000,
    energiaConsumidaMwhAno: 2980000,
    combustivelLitrosAno: 132000000,
    empregosDiretos: 9600,
    capitalMovimentadoBrl: 24800000000,
    tarifaAguaEmpresaBrlM3: 0.027,
    tarifaAguaCidadaoBrlM3: 8.95,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM IDE-Sisema Outorgas",
    urlFonteAgua: "https://idemg.meioambiente.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Climate TRACE Steel",
    urlFonteCombustivel: "https://climatetrace.org/",
    fonteEmpregoCapital: "CVM DFP Gerdau / RAIS MTE",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-05",
    rankGeral: 5,
    empresa: "Kinross Brasil Mineração — Mina Morro do Ouro",
    grupoEconomico: "Kinross Gold Corp (Canadá)",
    cnpjRaiz: "20.346.524",
    setorCnae: "0724-3 Extração de minério de metais preciosos",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3147006",
    municipioNome: "Paracatu",
    baciaHidrografica: "Rio Paracatu (Bacia do São Francisco)",
    aguaOutorgadaM3Ano: 69200000,
    energiaConsumidaMwhAno: 1580000,
    combustivelLitrosAno: 89000000,
    empregosDiretos: 5400,
    capitalMovimentadoBrl: 11200000000,
    tarifaAguaEmpresaBrlM3: 0.024,
    tarifaAguaCidadaoBrlM3: 9.10,
    tarifaEnergiaEmpresaBrlKwh: 0.20,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH / IGAM Bacia São Francisco",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE / Usinas Hidrelétricas Próprias",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / TSX Kinross Sustainability Report",
    urlFonteCombustivel: "https://www.tsx.com/",
    fonteEmpregoCapital: "ANM CFEM / TSX SEDAR+",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-06",
    rankGeral: 6,
    empresa: "Anglo American — Sistema Minas-Rio (Mina do Sapo e Mineroduto)",
    grupoEconomico: "Anglo American plc (Reino Unido)",
    cnpjRaiz: "02.359.572",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3117504",
    municipioNome: "Conceição do Mato Dentro",
    baciaHidrografica: "Rio Santo Antônio (Bacia do Rio Doce)",
    aguaOutorgadaM3Ano: 64800000,
    energiaConsumidaMwhAno: 1890000,
    combustivelLitrosAno: 94000000,
    empregosDiretos: 6800,
    capitalMovimentadoBrl: 19400000000,
    tarifaAguaEmpresaBrlM3: 0.026,
    tarifaAguaCidadaoBrlM3: 8.90,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Mineroduto Minas-Rio",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Companies House UK Sustainability",
    urlFonteCombustivel: "https://find-and-update.company-information.service.gov.uk/",
    fonteEmpregoCapital: "ANM CFEM / RAIS MTE",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-07",
    rankGeral: 7,
    empresa: "CSN Mineração — Mina Casa de Pedra",
    grupoEconomico: "Companhia Siderúrgica Nacional (CSN)",
    cnpjRaiz: "08.902.291",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3118007",
    municipioNome: "Congonhas",
    baciaHidrografica: "Rio Paraopeba (Rio Maranhão)",
    aguaOutorgadaM3Ano: 58300000,
    energiaConsumidaMwhAno: 1720000,
    combustivelLitrosAno: 118000000,
    empregosDiretos: 9200,
    capitalMovimentadoBrl: 18600000000,
    tarifaAguaEmpresaBrlM3: 0.029,
    tarifaAguaCidadaoBrlM3: 8.95,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Alto Paraopeba",
    urlFonteAgua: "https://idemg.meioambiente.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Relatório Integrado CSN",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "CVM DFP CSN Mineração / ANM CFEM",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-08",
    rankGeral: 8,
    empresa: "Stellantis Automóveis Brasil (Polo Automotivo Fiat Betim)",
    grupoEconomico: "Stellantis N.V. (Holanda/Itália/França)",
    cnpjRaiz: "16.701.716",
    setorCnae: "2910-7 Fabricação de automóveis, camionetas e utilitários",
    categoriaSetor: "Indústria Automotiva & Manufatura",
    codigoIbgeMunicipio: "3106705",
    municipioNome: "Betim",
    baciaHidrografica: "Rio Paraopeba (Ribeirão Betim)",
    aguaOutorgadaM3Ano: 14600000,
    energiaConsumidaMwhAno: 940000,
    combustivelLitrosAno: 52000000,
    empregosDiretos: 16500,
    capitalMovimentadoBrl: 38900000000,
    tarifaAguaEmpresaBrlM3: 0.035,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.23,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / COPASA Industrial Betim",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Gasmig Gás Natural Industrial",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS/CAGED MTE / Balanço Stellantis",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-09",
    rankGeral: 9,
    empresa: "Cenibra — Celulose Nipo-Brasileira S.A.",
    grupoEconomico: "Japan Brazil Paper and Pulp Resources (Japão)",
    cnpjRaiz: "42.278.796",
    setorCnae: "1710-9 Fabricação de celulose e outras pastas",
    categoriaSetor: "Celulose, Papel & Agroindústria",
    codigoIbgeMunicipio: "3106309",
    municipioNome: "Belo Oriente",
    baciaHidrografica: "Rio Doce",
    aguaOutorgadaM3Ano: 78900000,
    energiaConsumidaMwhAno: 1450000,
    combustivelLitrosAno: 74000000,
    empregosDiretos: 8100,
    capitalMovimentadoBrl: 6400000000,
    tarifaAguaEmpresaBrlM3: 0.022,
    tarifaAguaCidadaoBrlM3: 8.80,
    tarifaEnergiaEmpresaBrlKwh: 0.18,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH Calha do Rio Doce",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE Cogeração Biomassa Licor Negro",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Relatório de Sustentabilidade Cenibra",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Demonstrações Financeiras",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-10",
    rankGeral: 10,
    empresa: "ArcelorMittal Brasil — Usina Monlevade e Mina do Andrade",
    grupoEconomico: "ArcelorMittal S.A. (Luxemburgo)",
    cnpjRaiz: "17.469.701",
    setorCnae: "2423-7 Produção de laminados longos de aço",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3136207",
    municipioNome: "João Monlevade",
    baciaHidrografica: "Rio Piracicaba (Rio Doce)",
    aguaOutorgadaM3Ano: 54200000,
    energiaConsumidaMwhAno: 2150000,
    combustivelLitrosAno: 92000000,
    empregosDiretos: 7400,
    capitalMovimentadoBrl: 15800000000,
    tarifaAguaEmpresaBrlM3: 0.026,
    tarifaAguaCidadaoBrlM3: 8.90,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Rio Piracicaba",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Climate TRACE Steel",
    urlFonteCombustivel: "https://climatetrace.org/",
    fonteEmpregoCapital: "RAIS MTE / Relatório ArcelorMittal",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-11",
    rankGeral: 11,
    empresa: "Samarco Mineração S.A. — Complexo Germano e Alegria",
    grupoEconomico: "Vale S.A. (50%) / BHP Billiton (50%)",
    cnpjRaiz: "16.628.281",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3140001",
    municipioNome: "Mariana",
    baciaHidrografica: "Rio Gualaxo do Norte (Rio Doce)",
    aguaOutorgadaM3Ano: 49800000,
    energiaConsumidaMwhAno: 1340000,
    combustivelLitrosAno: 68000000,
    empregosDiretos: 5900,
    capitalMovimentadoBrl: 9800000000,
    tarifaAguaEmpresaBrlM3: 0.027,
    tarifaAguaCidadaoBrlM3: 8.85,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / ANA Outorga Mineroduto e Beneficiamento",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / Processo Judicial Mariana",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-12",
    rankGeral: 12,
    empresa: "Vale S.A. — Complexo Paraopeba (Córrego do Feijão, Jangada e Mar Azul)",
    grupoEconomico: "Vale S.A.",
    cnpjRaiz: "33.592.510",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3109006",
    municipioNome: "Brumadinho",
    baciaHidrografica: "Rio Paraopeba",
    aguaOutorgadaM3Ano: 42100000,
    energiaConsumidaMwhAno: 1120000,
    combustivelLitrosAno: 76000000,
    empregosDiretos: 6300,
    capitalMovimentadoBrl: 14500000000,
    tarifaAguaEmpresaBrlM3: 0.028,
    tarifaAguaCidadaoBrlM3: 9.05,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorgas Bacia do Paraopeba",
    urlFonteAgua: "https://idemg.meioambiente.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / Acordo Judicial Brumadinho",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-13",
    rankGeral: 13,
    empresa: "Aperam South America — Usina Siderúrgica de Timóteo",
    grupoEconomico: "Aperam S.A. (Luxemburgo / França)",
    cnpjRaiz: "33.390.170",
    setorCnae: "2422-9 Produção de aços inoxidáveis e elétricos",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3168705",
    municipioNome: "Timóteo",
    baciaHidrografica: "Rio Piracicaba (Rio Doce)",
    aguaOutorgadaM3Ano: 46500000,
    energiaConsumidaMwhAno: 1920000,
    combustivelLitrosAno: 84000000,
    empregosDiretos: 5800,
    capitalMovimentadoBrl: 8900000000,
    tarifaAguaEmpresaBrlM3: 0.025,
    tarifaAguaCidadaoBrlM3: 8.85,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Rio Piracicaba",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / BioEnergia Carvão Vegetal Aperam",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Relatório Sustentabilidade Aperam",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-14",
    rankGeral: 14,
    empresa: "CBMM — Companhia Brasileira de Metalurgia e Mineração (Nióbio)",
    grupoEconomico: "Grupo Moreira Salles / Consórcio Japonês-Coreano-Chinês",
    cnpjRaiz: "33.131.541",
    setorCnae: "0729-4 Extração de minerais metálicos não ferrosos (Nióbio)",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3104007",
    municipioNome: "Araxá",
    baciaHidrografica: "Rio Araguari (Bacia do Paranaíba)",
    aguaOutorgadaM3Ano: 38400000,
    energiaConsumidaMwhAno: 1480000,
    combustivelLitrosAno: 61000000,
    empregosDiretos: 4900,
    capitalMovimentadoBrl: 12400000000,
    tarifaAguaEmpresaBrlM3: 0.026,
    tarifaAguaCidadaoBrlM3: 8.95,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Bacia do Rio Araguari",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / Demonstrações Financeiras CBMM",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-15",
    rankGeral: 15,
    empresa: "Mosaic Fertilizantes — Complexo Mineroquímico de Uberaba e Tapira",
    grupoEconomico: "The Mosaic Company (Estados Unidos)",
    cnpjRaiz: "61.156.501",
    setorCnae: "2013-4 Fabricação de adubos e fertilizantes fosfatados",
    categoriaSetor: "Química, Fertilizantes & Cimento",
    codigoIbgeMunicipio: "3170107",
    municipioNome: "Uberaba",
    baciaHidrografica: "Rio Grande / Rio Araguari",
    aguaOutorgadaM3Ano: 51200000,
    energiaConsumidaMwhAno: 1390000,
    combustivelLitrosAno: 72000000,
    empregosDiretos: 5600,
    capitalMovimentadoBrl: 16200000000,
    tarifaAguaEmpresaBrlM3: 0.027,
    tarifaAguaCidadaoBrlM3: 8.75,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH Rio Grande / IGAM",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / SEC EDGAR 10-K Mosaic",
    urlFonteCombustivel: "https://www.sec.gov/edgar/searchedgar/companysearch",
    fonteEmpregoCapital: "ANM CFEM / SEC EDGAR CIK 0001285785",
    urlFonteEmpregoCapital: "https://www.sec.gov/edgar/searchedgar/companysearch",
  },
  {
    id: "mg-cons-16",
    rankGeral: 16,
    empresa: "Alcoa Alumínio S.A. — Refinaria e Minas de Poços de Caldas",
    grupoEconomico: "Alcoa Corporation (Estados Unidos)",
    cnpjRaiz: "23.637.697",
    setorCnae: "2441-5 Metalurgia do alumínio e suas ligas",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3151800",
    municipioNome: "Poços de Caldas",
    baciaHidrografica: "Rio Pardo / Rio Grande",
    aguaOutorgadaM3Ano: 32800000,
    energiaConsumidaMwhAno: 2450000,
    combustivelLitrosAno: 58000000,
    empregosDiretos: 3900,
    capitalMovimentadoBrl: 7800000000,
    tarifaAguaEmpresaBrlM3: 0.029,
    tarifaAguaCidadaoBrlM3: 8.60,
    tarifaEnergiaEmpresaBrlKwh: 0.19,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH / IGAM Sul de Minas",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado / Consórcio Machadinho",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / SEC EDGAR 10-K Alcoa",
    urlFonteCombustivel: "https://www.sec.gov/edgar/searchedgar/companysearch",
    fonteEmpregoCapital: "ANM CFEM / SEC EDGAR CIK 0001675149",
    urlFonteEmpregoCapital: "https://www.sec.gov/edgar/searchedgar/companysearch",
  },
  {
    id: "mg-cons-17",
    rankGeral: 17,
    empresa: "Nexa Resources — Refinaria de Zinco de Três Marias",
    grupoEconomico: "Grupo Votorantim / Nexa (Luxemburgo/Canadá)",
    cnpjRaiz: "42.416.651",
    setorCnae: "2449-1 Metalurgia dos metais não ferrosos (Zinco)",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3169356",
    municipioNome: "Três Marias",
    baciaHidrografica: "Rio São Francisco",
    aguaOutorgadaM3Ano: 36500000,
    energiaConsumidaMwhAno: 1840000,
    combustivelLitrosAno: 44000000,
    empregosDiretos: 3400,
    capitalMovimentadoBrl: 6900000000,
    tarifaAguaEmpresaBrlM3: 0.024,
    tarifaAguaCidadaoBrlM3: 8.95,
    tarifaEnergiaEmpresaBrlKwh: 0.20,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH Calha do Rio São Francisco",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / SEC EDGAR Nexa",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-18",
    rankGeral: 18,
    empresa: "Sigma Lithium — Grota do Cirilo (Cavas Xuxa e Barreiro)",
    grupoEconomico: "Sigma Lithium Corp (Canadá TSX-V / NASDAQ)",
    cnpjRaiz: "16.584.115",
    setorCnae: "0729-4 Extração de minerais metálicos (Lítio)",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3103405",
    municipioNome: "Araçuaí",
    baciaHidrografica: "Rio Jequitinhonha (Ribeirão Piauí)",
    aguaOutorgadaM3Ano: 18900000,
    energiaConsumidaMwhAno: 420000,
    combustivelLitrosAno: 38000000,
    empregosDiretos: 2450,
    capitalMovimentadoBrl: 3800000000,
    tarifaAguaEmpresaBrlM3: 0.021,
    tarifaAguaCidadaoBrlM3: 9.20,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH Rio Jequitinhonha / IGAM",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / SEDAR+ TSX Technical Report",
    urlFonteCombustivel: "https://www.sedarplus.ca/",
    fonteEmpregoCapital: "ANM CFEM / SEC EDGAR CIK 0001848309",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-19",
    rankGeral: 19,
    empresa: "Vale S.A. — Complexo Mariana (Fábrica Nova, Timbopeba e Alegria)",
    grupoEconomico: "Vale S.A.",
    cnpjRaiz: "33.592.510",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3146107",
    municipioNome: "Ouro Preto",
    baciaHidrografica: "Rio Piracicaba / Rio das Velhas",
    aguaOutorgadaM3Ano: 61500000,
    energiaConsumidaMwhAno: 1680000,
    combustivelLitrosAno: 112000000,
    empregosDiretos: 8700,
    capitalMovimentadoBrl: 21500000000,
    tarifaAguaEmpresaBrlM3: 0.027,
    tarifaAguaCidadaoBrlM3: 8.85,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Bacia Piracicaba",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / CVM DFP Vale",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-20",
    rankGeral: 20,
    empresa: "Vale S.A. — Mina de Brucutu (Maior mina de ferro de MG)",
    grupoEconomico: "Vale S.A.",
    cnpjRaiz: "33.592.510",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3161908",
    municipioNome: "São Gonçalo do Rio Abaixo",
    baciaHidrografica: "Rio Santa Bárbara (Rio Doce)",
    aguaOutorgadaM3Ano: 59400000,
    energiaConsumidaMwhAno: 1520000,
    combustivelLitrosAno: 104000000,
    empregosDiretos: 6900,
    capitalMovimentadoBrl: 23100000000,
    tarifaAguaEmpresaBrlM3: 0.026,
    tarifaAguaCidadaoBrlM3: 8.90,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Rio Santa Bárbara",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / CVM DFP Vale",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-21",
    rankGeral: 21,
    empresa: "Vale S.A. — Complexo Vargem Grande e Capitão do Mato",
    grupoEconomico: "Vale S.A.",
    cnpjRaiz: "33.592.510",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3144805",
    municipioNome: "Nova Lima",
    baciaHidrografica: "Alto Rio das Velhas (Rio São Francisco)",
    aguaOutorgadaM3Ano: 47200000,
    energiaConsumidaMwhAno: 1290000,
    combustivelLitrosAno: 88000000,
    empregosDiretos: 7800,
    capitalMovimentadoBrl: 18900000000,
    tarifaAguaEmpresaBrlM3: 0.031,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorgas Alto Rio das Velhas",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / CVM DFP Vale",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-22",
    rankGeral: 22,
    empresa: "Vallourec Soluções Tubulares do Brasil — Usina Barreiro",
    grupoEconomico: "Vallourec S.A. (França)",
    cnpjRaiz: "17.170.150",
    setorCnae: "2423-7 Produção de tubos de aço sem costura",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3106200",
    municipioNome: "Belo Horizonte",
    baciaHidrografica: "Ribeirão Arrudas (Rio das Velhas)",
    aguaOutorgadaM3Ano: 22400000,
    energiaConsumidaMwhAno: 1180000,
    combustivelLitrosAno: 64000000,
    empregosDiretos: 6200,
    capitalMovimentadoBrl: 9400000000,
    tarifaAguaEmpresaBrlM3: 0.034,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / COPASA Industrial BH",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Gasmig Gás Industrial",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Relatório Vallourec",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-23",
    rankGeral: 23,
    empresa: "Vallourec & Sumitomo Tubos do Brasil (VSB Jeceaba)",
    grupoEconomico: "Vallourec (França) / Nippon Steel (Japão)",
    cnpjRaiz: "09.123.654",
    setorCnae: "2423-7 Siderurgia e tubos industriais",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3135407",
    municipioNome: "Jeceaba",
    baciaHidrografica: "Rio Paraopeba (Rio Camapuã)",
    aguaOutorgadaM3Ano: 28900000,
    energiaConsumidaMwhAno: 1260000,
    combustivelLitrosAno: 53000000,
    empregosDiretos: 3800,
    capitalMovimentadoBrl: 6700000000,
    tarifaAguaEmpresaBrlM3: 0.028,
    tarifaAguaCidadaoBrlM3: 8.95,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Bacia do Paraopeba",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Demonstrações Vallourec",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-24",
    rankGeral: 24,
    empresa: "ArcelorMittal Juiz de Fora — Siderurgia e Trefilaria",
    grupoEconomico: "ArcelorMittal S.A. (Luxemburgo)",
    cnpjRaiz: "17.469.701",
    setorCnae: "2423-7 Produção de aços longos e arames",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3136702",
    municipioNome: "Juiz de Fora",
    baciaHidrografica: "Rio Paraibuna (Paraíba do Sul)",
    aguaOutorgadaM3Ano: 31500000,
    energiaConsumidaMwhAno: 1490000,
    combustivelLitrosAno: 59000000,
    empregosDiretos: 4300,
    capitalMovimentadoBrl: 8200000000,
    tarifaAguaEmpresaBrlM3: 0.029,
    tarifaAguaCidadaoBrlM3: 8.70,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH Bacia Paraíba do Sul / IGAM",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Relatório ArcelorMittal",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-25",
    rankGeral: 25,
    empresa: "Nexa Resources — Unidade Metalúrgica de Juiz de Fora",
    grupoEconomico: "Grupo Votorantim / Nexa",
    cnpjRaiz: "42.416.651",
    setorCnae: "2449-1 Metalurgia de zinco e ligas",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3136702",
    municipioNome: "Juiz de Fora",
    baciaHidrografica: "Rio Paraibuna (Paraíba do Sul)",
    aguaOutorgadaM3Ano: 21800000,
    energiaConsumidaMwhAno: 1120000,
    combustivelLitrosAno: 37000000,
    empregosDiretos: 2600,
    capitalMovimentadoBrl: 4500000000,
    tarifaAguaEmpresaBrlM3: 0.029,
    tarifaAguaCidadaoBrlM3: 8.70,
    tarifaEnergiaEmpresaBrlKwh: 0.20,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH / IGAM",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / SEC EDGAR Nexa",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-26",
    rankGeral: 26,
    empresa: "AngloGold Ashanti — Mina Cuiabá e Complexo Queiroz",
    grupoEconomico: "AngloGold Ashanti plc (Reino Unido / África do Sul)",
    cnpjRaiz: "18.565.382",
    setorCnae: "0724-3 Extração de minério de ouro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3156700",
    municipioNome: "Sabará",
    baciaHidrografica: "Rio Sabará / Rio das Velhas",
    aguaOutorgadaM3Ano: 29400000,
    energiaConsumidaMwhAno: 980000,
    combustivelLitrosAno: 46000000,
    empregosDiretos: 4900,
    capitalMovimentadoBrl: 6100000000,
    tarifaAguaEmpresaBrlM3: 0.030,
    tarifaAguaCidadaoBrlM3: 9.10,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Rio das Velhas",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / SEC EDGAR AngloGold",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-27",
    rankGeral: 27,
    empresa: "Mineração Usiminas (MUSA) — Serra Azul",
    grupoEconomico: "Usiminas (70%) / Sumitomo Corp (30%)",
    cnpjRaiz: "12.056.613",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3132206",
    municipioNome: "Itatiaiuçu",
    baciaHidrografica: "Rio Paraopeba (Serra Azul)",
    aguaOutorgadaM3Ano: 31200000,
    energiaConsumidaMwhAno: 890000,
    combustivelLitrosAno: 62000000,
    empregosDiretos: 3700,
    capitalMovimentadoBrl: 6800000000,
    tarifaAguaEmpresaBrlM3: 0.028,
    tarifaAguaCidadaoBrlM3: 9.00,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Bacia do Paraopeba",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / CVM DFP Usiminas",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-28",
    rankGeral: 28,
    empresa: "Vale S.A. — Complexo Pico e Fábrica",
    grupoEconomico: "Vale S.A.",
    cnpjRaiz: "33.592.510",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3131901",
    municipioNome: "Itabirito",
    baciaHidrografica: "Alto Rio das Velhas",
    aguaOutorgadaM3Ano: 44600000,
    energiaConsumidaMwhAno: 1190000,
    combustivelLitrosAno: 79000000,
    empregosDiretos: 5600,
    capitalMovimentadoBrl: 15400000000,
    tarifaAguaEmpresaBrlM3: 0.029,
    tarifaAguaCidadaoBrlM3: 8.95,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Rio das Velhas",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / CVM DFP Vale",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-29",
    rankGeral: 29,
    empresa: "CSN Cimentos — Fábrica de Arcos e Calcário",
    grupoEconomico: "Companhia Siderúrgica Nacional (CSN)",
    cnpjRaiz: "33.042.730",
    setorCnae: "2320-6 Fabricação de cimento",
    categoriaSetor: "Química, Fertilizantes & Cimento",
    codigoIbgeMunicipio: "3104205",
    municipioNome: "Arcos",
    baciaHidrografica: "Alto Rio São Francisco",
    aguaOutorgadaM3Ano: 19200000,
    energiaConsumidaMwhAno: 1080000,
    combustivelLitrosAno: 86000000,
    empregosDiretos: 2900,
    capitalMovimentadoBrl: 4800000000,
    tarifaAguaEmpresaBrlM3: 0.025,
    tarifaAguaCidadaoBrlM3: 8.85,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Alto São Francisco",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Climate TRACE Cement",
    urlFonteCombustivel: "https://climatetrace.org/",
    fonteEmpregoCapital: "CVM DFP CSN / RAIS MTE",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-30",
    rankGeral: 30,
    empresa: "InterCement / Cimentos Cauê — Pedro Leopoldo e Matozinhos",
    grupoEconomico: "Grupo Mover / InterCement",
    cnpjRaiz: "62.258.884",
    setorCnae: "2320-6 Fabricação de cimento",
    categoriaSetor: "Química, Fertilizantes & Cimento",
    codigoIbgeMunicipio: "3149309",
    municipioNome: "Pedro Leopoldo",
    baciaHidrografica: "Rio das Velhas (Carste de Lagoa Santa)",
    aguaOutorgadaM3Ano: 16400000,
    energiaConsumidaMwhAno: 920000,
    combustivelLitrosAno: 74000000,
    empregosDiretos: 2100,
    capitalMovimentadoBrl: 3600000000,
    tarifaAguaEmpresaBrlM3: 0.029,
    tarifaAguaCidadaoBrlM3: 9.10,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Aquífero Cárstico",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Climate TRACE Cement",
    urlFonteCombustivel: "https://climatetrace.org/",
    fonteEmpregoCapital: "RAIS MTE / CVM InterCement",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-31",
    rankGeral: 31,
    empresa: "Ambev S.A. — Cervejaria Juatuba e Sete Lagoas",
    grupoEconomico: "AB InBev (Bélgica / Brasil)",
    cnpjRaiz: "07.526.557",
    setorCnae: "1113-5 Fabricação de malte, cervejas e chopes",
    categoriaSetor: "Celulose, Papel & Agroindústria",
    codigoIbgeMunicipio: "3167202",
    municipioNome: "Sete Lagoas",
    baciaHidrografica: "Rio das Velhas / Rio Paraopeba",
    aguaOutorgadaM3Ano: 24800000,
    energiaConsumidaMwhAno: 640000,
    combustivelLitrosAno: 42000000,
    empregosDiretos: 4100,
    capitalMovimentadoBrl: 9200000000,
    tarifaAguaEmpresaBrlM3: 0.031,
    tarifaAguaCidadaoBrlM3: 8.95,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Subterrânea e Superficial",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "CVM DFP Ambev / RAIS MTE",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-32",
    rankGeral: 32,
    empresa: "Iveco Group / CNH Industrial — Complexo Sete Lagoas",
    grupoEconomico: "Exor N.V. / Iveco Group (Itália/Holanda)",
    cnpjRaiz: "01.844.555",
    setorCnae: "2920-4 Fabricação de caminhões e ônibus",
    categoriaSetor: "Indústria Automotiva & Manufatura",
    codigoIbgeMunicipio: "3167202",
    municipioNome: "Sete Lagoas",
    baciaHidrografica: "Rio das Velhas",
    aguaOutorgadaM3Ano: 9400000,
    energiaConsumidaMwhAno: 480000,
    combustivelLitrosAno: 31000000,
    empregosDiretos: 4600,
    capitalMovimentadoBrl: 7900000000,
    tarifaAguaEmpresaBrlM3: 0.033,
    tarifaAguaCidadaoBrlM3: 8.95,
    tarifaEnergiaEmpresaBrlKwh: 0.23,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / SAAE Sete Lagoas",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Balanço Iveco",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-33",
    rankGeral: 33,
    empresa: "Cargill Agrícola S.A. — Complexo Agroindustrial de Uberlândia",
    grupoEconomico: "Cargill Inc. (Estados Unidos)",
    cnpjRaiz: "60.498.706",
    setorCnae: "1041-4 Fabricação de óleos vegetais e processamento de grãos",
    categoriaSetor: "Celulose, Papel & Agroindústria",
    codigoIbgeMunicipio: "3170206",
    municipioNome: "Uberlândia",
    baciaHidrografica: "Rio Araguari / Rio Uberabinha",
    aguaOutorgadaM3Ano: 33600000,
    energiaConsumidaMwhAno: 910000,
    combustivelLitrosAno: 69000000,
    empregosDiretos: 5200,
    capitalMovimentadoBrl: 14800000000,
    tarifaAguaEmpresaBrlM3: 0.026,
    tarifaAguaCidadaoBrlM3: 8.40,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / DMAE Uberlândia",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Balanço Cargill Brasil",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-34",
    rankGeral: 34,
    empresa: "BRF S.A. (Sadia/Perdigão) — Complexo Frigorífico Uberlândia",
    grupoEconomico: "BRF S.A. / Marfrig",
    cnpjRaiz: "01.838.723",
    setorCnae: "1012-1 Abate de aves e suínos e industrialização",
    categoriaSetor: "Celulose, Papel & Agroindústria",
    codigoIbgeMunicipio: "3170206",
    municipioNome: "Uberlândia",
    baciaHidrografica: "Rio Uberabinha (Bacia do Paranaíba)",
    aguaOutorgadaM3Ano: 29800000,
    energiaConsumidaMwhAno: 780000,
    combustivelLitrosAno: 54000000,
    empregosDiretos: 7400,
    capitalMovimentadoBrl: 9600000000,
    tarifaAguaEmpresaBrlM3: 0.027,
    tarifaAguaCidadaoBrlM3: 8.40,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Rio Uberabinha",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "CVM DFP BRF / RAIS MTE",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-35",
    rankGeral: 35,
    empresa: "JBS S.A. (Friboi / Seara) — Unidades Ituiutaba, Uberaba e Contagem",
    grupoEconomico: "JBS S.A.",
    cnpjRaiz: "02.916.265",
    setorCnae: "1011-2 Abate de bovinos e processamento de carnes",
    categoriaSetor: "Celulose, Papel & Agroindústria",
    codigoIbgeMunicipio: "3118601",
    municipioNome: "Contagem",
    baciaHidrografica: "Rio Paraopeba / Rio Paranaíba",
    aguaOutorgadaM3Ano: 27400000,
    energiaConsumidaMwhAno: 720000,
    combustivelLitrosAno: 61000000,
    empregosDiretos: 6800,
    capitalMovimentadoBrl: 11400000000,
    tarifaAguaEmpresaBrlM3: 0.029,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / ANA CNARH",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "CVM DFP JBS / RAIS MTE",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-36",
    rankGeral: 36,
    empresa: "Magnesita Refratários (RHI Magnesita) — Contagem e Brumado",
    grupoEconomico: "RHI Magnesita N.V. (Áustria / Reino Unido)",
    cnpjRaiz: "19.791.215",
    setorCnae: "2341-9 Fabricação de produtos cerâmicos refratários",
    categoriaSetor: "Química, Fertilizantes & Cimento",
    codigoIbgeMunicipio: "3118601",
    municipioNome: "Contagem",
    baciaHidrografica: "Ribeirão Arrudas (Rio das Velhas)",
    aguaOutorgadaM3Ano: 14200000,
    energiaConsumidaMwhAno: 860000,
    combustivelLitrosAno: 57000000,
    empregosDiretos: 3900,
    capitalMovimentadoBrl: 5400000000,
    tarifaAguaEmpresaBrlM3: 0.033,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / COPASA Industrial Contagem",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / Gasmig Gás Natural",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Companies House UK",
    urlFonteEmpregoCapital: "https://find-and-update.company-information.service.gov.uk/",
  },
  {
    id: "mg-cons-37",
    rankGeral: 37,
    empresa: "ArcelorMittal Contagem e Sabará — Trefilaria e Aços Longos",
    grupoEconomico: "ArcelorMittal S.A. (Luxemburgo)",
    cnpjRaiz: "17.469.701",
    setorCnae: "2423-7 Siderurgia e trefilados",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3118601",
    municipioNome: "Contagem",
    baciaHidrografica: "Ribeirão Arrudas / Rio das Velhas",
    aguaOutorgadaM3Ano: 15800000,
    energiaConsumidaMwhAno: 940000,
    combustivelLitrosAno: 45000000,
    empregosDiretos: 3600,
    capitalMovimentadoBrl: 6200000000,
    tarifaAguaEmpresaBrlM3: 0.032,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Rio das Velhas",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Relatório ArcelorMittal",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-38",
    rankGeral: 38,
    empresa: "Novo Nordisk Produção Farmacêutica — Planta Montes Claros",
    grupoEconomico: "Novo Nordisk A/S (Dinamarca)",
    cnpjRaiz: "35.802.828",
    setorCnae: "2121-1 Fabricação de medicamentos alopáticos (Insulina)",
    categoriaSetor: "Indústria Automotiva & Manufatura",
    codigoIbgeMunicipio: "3143302",
    municipioNome: "Montes Claros",
    baciaHidrografica: "Rio Verde Grande (Bacia do São Francisco)",
    aguaOutorgadaM3Ano: 16800000,
    energiaConsumidaMwhAno: 590000,
    combustivelLitrosAno: 28000000,
    empregosDiretos: 3400,
    capitalMovimentadoBrl: 8900000000,
    tarifaAguaEmpresaBrlM3: 0.029,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / ANA Bacia do Verde Grande",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Relatório Novo Nordisk",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-39",
    rankGeral: 39,
    empresa: "Usina Coruripe — Polos Iturama, Campo Florido e Carneirinho",
    grupoEconomico: "Grupo Tércio Wanderley",
    cnpjRaiz: "12.229.415",
    setorCnae: "1071-6 Fabricação de açúcar em bruto e etanol",
    categoriaSetor: "Celulose, Papel & Agroindústria",
    codigoIbgeMunicipio: "3134400",
    municipioNome: "Iturama",
    baciaHidrografica: "Rio Grande / Rio Paranaíba",
    aguaOutorgadaM3Ano: 68400000,
    energiaConsumidaMwhAno: 890000,
    combustivelLitrosAno: 94000000,
    empregosDiretos: 7200,
    capitalMovimentadoBrl: 5900000000,
    tarifaAguaEmpresaBrlM3: 0.019,
    tarifaAguaCidadaoBrlM3: 8.85,
    tarifaEnergiaEmpresaBrlKwh: 0.17,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH Irrigação e Indústria Rio Grande",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE Cogeração Bagaço de Cana",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / ANP Produção de Etanol",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-40",
    rankGeral: 40,
    empresa: "BP Bunge Bioenergia (Raízen/BP) — Frutal e Ituiutaba",
    grupoEconomico: "BP plc (Reino Unido)",
    cnpjRaiz: "08.439.659",
    setorCnae: "1931-4 Fabricação de álcool (etanol) e açúcar",
    categoriaSetor: "Celulose, Papel & Agroindústria",
    codigoIbgeMunicipio: "3127107",
    municipioNome: "Frutal",
    baciaHidrografica: "Rio Grande",
    aguaOutorgadaM3Ano: 54600000,
    energiaConsumidaMwhAno: 760000,
    combustivelLitrosAno: 81000000,
    empregosDiretos: 5800,
    capitalMovimentadoBrl: 5200000000,
    tarifaAguaEmpresaBrlM3: 0.019,
    tarifaAguaCidadaoBrlM3: 8.85,
    tarifaEnergiaEmpresaBrlKwh: 0.18,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH Bacia do Rio Grande",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE Biomassa Canavieira",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS MTE / Companies House BP",
    urlFonteEmpregoCapital: "https://find-and-update.company-information.service.gov.uk/",
  },
  {
    id: "mg-cons-41",
    rankGeral: 41,
    empresa: "Gerdau S.A. — Usina Divinópolis",
    grupoEconomico: "Gerdau S.A.",
    cnpjRaiz: "33.611.500",
    setorCnae: "2423-7 Produção de laminados longos de aço",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3122306",
    municipioNome: "Divinópolis",
    baciaHidrografica: "Rio Pará (Bacia do São Francisco)",
    aguaOutorgadaM3Ano: 21500000,
    energiaConsumidaMwhAno: 1120000,
    combustivelLitrosAno: 48000000,
    empregosDiretos: 2900,
    capitalMovimentadoBrl: 4900000000,
    tarifaAguaEmpresaBrlM3: 0.027,
    tarifaAguaCidadaoBrlM3: 8.95,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Rio Pará",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "CVM DFP Gerdau / RAIS MTE",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-42",
    rankGeral: 42,
    empresa: "Vale S.A. — Mina de Gongo Soco e Complexo Barão de Cocais",
    grupoEconomico: "Vale S.A.",
    cnpjRaiz: "33.592.510",
    setorCnae: "0710-3 Extração de minério de ferro",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3105400",
    municipioNome: "Barão de Cocais",
    baciaHidrografica: "Rio Santa Bárbara (Rio Doce)",
    aguaOutorgadaM3Ano: 26800000,
    energiaConsumidaMwhAno: 740000,
    combustivelLitrosAno: 51000000,
    empregosDiretos: 3400,
    capitalMovimentadoBrl: 7200000000,
    tarifaAguaEmpresaBrlM3: 0.027,
    tarifaAguaCidadaoBrlM3: 8.90,
    tarifaEnergiaEmpresaBrlKwh: 0.21,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Rio Santa Bárbara",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / CVM DFP Vale",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-43",
    rankGeral: 43,
    empresa: "Nexa Resources — Mina Subterrânea de Vazante (Rebaixamento Cárstico)",
    grupoEconomico: "Grupo Votorantim / Nexa",
    cnpjRaiz: "42.416.651",
    setorCnae: "0729-4 Extração de minério de zinco e chumbo",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3170800",
    municipioNome: "Vazante",
    baciaHidrografica: "Rio Paracatu (Bacia do São Francisco)",
    aguaOutorgadaM3Ano: 76200000,
    energiaConsumidaMwhAno: 940000,
    combustivelLitrosAno: 41000000,
    empregosDiretos: 2800,
    capitalMovimentadoBrl: 4300000000,
    tarifaAguaEmpresaBrlM3: 0.022,
    tarifaAguaCidadaoBrlM3: 8.95,
    tarifaEnergiaEmpresaBrlKwh: 0.20,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorga Rebaixamento de Lençol Freático",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / SEC EDGAR Nexa",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-44",
    rankGeral: 44,
    empresa: "Companhia Brasileira de Lítio (CBL) — Mina da Cachoeira e Divisa Alegre",
    grupoEconomico: "Grupo Codemge / CBL",
    cnpjRaiz: "22.694.814",
    setorCnae: "0729-4 Extração e beneficiamento de lítio",
    categoriaSetor: "Mineração & Siderurgia",
    codigoIbgeMunicipio: "3134004",
    municipioNome: "Itinga",
    baciaHidrografica: "Rio Jequitinhonha",
    aguaOutorgadaM3Ano: 11200000,
    energiaConsumidaMwhAno: 310000,
    combustivelLitrosAno: 22000000,
    empregosDiretos: 1450,
    capitalMovimentadoBrl: 1850000000,
    tarifaAguaEmpresaBrlM3: 0.023,
    tarifaAguaCidadaoBrlM3: 9.20,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM / ANA Bacia do Jequitinhonha",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANM CFEM / RAIS MTE",
    urlFonteEmpregoCapital: "https://sistemas.anm.gov.br/arrecadacao/extra/Relatorios/distribuicao_cfem.aspx",
  },
  {
    id: "mg-cons-45",
    rankGeral: 45,
    empresa: "COPASA MG — Companhia de Saneamento de Minas Gerais (Sede e ETA Rio das Velhas)",
    grupoEconomico: "Estado de Minas Gerais / Mercado B3",
    cnpjRaiz: "17.281.106",
    setorCnae: "3600-6 Captação, tratamento e distribuição de água",
    categoriaSetor: "Infraestrutura, Saneamento & Energia",
    codigoIbgeMunicipio: "3106200",
    municipioNome: "Belo Horizonte",
    baciaHidrografica: "Rio das Velhas e Rio Paraopeba (RMBH)",
    aguaOutorgadaM3Ano: 495000000,
    energiaConsumidaMwhAno: 1760000,
    combustivelLitrosAno: 38000000,
    empregosDiretos: 11400,
    capitalMovimentadoBrl: 7100000000,
    tarifaAguaEmpresaBrlM3: 0.025,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.22,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorgas Abastecimento Público RMBH",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE / ANEEL SAMP",
    urlFonteEnergia: "https://dadosabertos.aneel.gov.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "CVM DFP COPASA / SNIS",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-46",
    rankGeral: 46,
    empresa: "CEMIG Geração e Transmissão / Distribuição S.A.",
    grupoEconomico: "Grupo CEMIG",
    cnpjRaiz: "06.981.180",
    setorCnae: "3511-5 Geração, transmissão e distribuição de energia elétrica",
    categoriaSetor: "Infraestrutura, Saneamento & Energia",
    codigoIbgeMunicipio: "3106200",
    municipioNome: "Belo Horizonte",
    baciaHidrografica: "Bacias do Grande, Paranaíba, São Francisco e Doce",
    aguaOutorgadaM3Ano: 42000000,
    energiaConsumidaMwhAno: 1320000,
    combustivelLitrosAno: 49000000,
    empregosDiretos: 9800,
    capitalMovimentadoBrl: 36800000000,
    tarifaAguaEmpresaBrlM3: 0.025,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.18,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH Reservatórios e Usinas",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "ANEEL Dados Abertos / CCEE",
    urlFonteEnergia: "https://dadosabertos.aneel.gov.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "CVM DFP CEMIG / SEC EDGAR",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-47",
    rankGeral: 47,
    empresa: "VLI Multimodal S.A. — Ferrovia Centro-Atlântica e Estrada de Ferro Vitória a Minas",
    grupoEconomico: "Vale / Brookfield / Mitsui / BNDESPar",
    cnpjRaiz: "00.924.429",
    setorCnae: "4911-6 Transporte ferroviário de carga",
    categoriaSetor: "Infraestrutura, Saneamento & Energia",
    codigoIbgeMunicipio: "3106200",
    municipioNome: "Belo Horizonte",
    baciaHidrografica: "Estadual (Corredores Ferroviários MG)",
    aguaOutorgadaM3Ano: 8900000,
    energiaConsumidaMwhAno: 490000,
    combustivelLitrosAno: 285000000,
    empregosDiretos: 8600,
    capitalMovimentadoBrl: 9400000000,
    tarifaAguaEmpresaBrlM3: 0.032,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.23,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "IGAM Outorgas Oficinas Ferroviárias",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado ACL",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP / ANTT Consumo de Diesel Ferroviário",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "ANTT / CVM DFP VLI",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-48",
    rankGeral: 48,
    empresa: "MRV Engenharia e Participações S.A.",
    grupoEconomico: "Grupo MRV&Co",
    cnpjRaiz: "08.343.492",
    setorCnae: "4120-4 Construção de edifícios e incorporação",
    categoriaSetor: "Indústria Automotiva & Manufatura",
    codigoIbgeMunicipio: "3106200",
    municipioNome: "Belo Horizonte",
    baciaHidrografica: "Ribeirão Arrudas e Onça (RMBH)",
    aguaOutorgadaM3Ano: 7800000,
    energiaConsumidaMwhAno: 340000,
    combustivelLitrosAno: 36000000,
    empregosDiretos: 14800,
    capitalMovimentadoBrl: 8200000000,
    tarifaAguaEmpresaBrlM3: 0.038,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.24,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "COPASA / IGAM Canteiros de Obra",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "ANEEL / CCEE",
    urlFonteEnergia: "https://dadosabertos.aneel.gov.br/",
    fonteCombustivel: "ANP Dados Abertos",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "CVM DFP MRV / CAGED MTE",
    urlFonteEmpregoCapital: "https://dados.cvm.gov.br/",
  },
  {
    id: "mg-cons-49",
    rankGeral: 49,
    empresa: "Supermercados BH Comércio de Alimentos S.A.",
    grupoEconomico: "Grupo Supermercados BH",
    cnpjRaiz: "04.641.376",
    setorCnae: "4711-3 Comércio varejista de mercadorias em geral (hipermercados)",
    categoriaSetor: "Comércio, Logística & Atacado",
    codigoIbgeMunicipio: "3118601",
    municipioNome: "Contagem",
    baciaHidrografica: "Ribeirão Arrudas / Pampulha",
    aguaOutorgadaM3Ano: 6400000,
    energiaConsumidaMwhAno: 680000,
    combustivelLitrosAno: 47000000,
    empregosDiretos: 34500,
    capitalMovimentadoBrl: 17400000000,
    tarifaAguaEmpresaBrlM3: 0.042,
    tarifaAguaCidadaoBrlM3: 9.15,
    tarifaEnergiaEmpresaBrlKwh: 0.24,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "COPASA Comercial / IGAM",
    urlFonteAgua: "https://www.igam.mg.gov.br/",
    fonteEnergia: "CCEE InfoMercado Consumidor Livre Varejo",
    urlFonteEnergia: "https://dadosabertos.ccee.org.br/",
    fonteCombustivel: "ANP Frota Logística CD Contagem",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "RAIS/CAGED MTE / Ranking ABRAS",
    urlFonteEmpregoCapital: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "mg-cons-50",
    rankGeral: 50,
    empresa: "Tereos / Cocal & Irrigação Megapivôs de Unaí e Paracatu",
    grupoEconomico: "Clusters de Irrigação Noroeste de MG",
    cnpjRaiz: "18.945.612",
    setorCnae: "0115-6 Cultivo de soja, milho e cana irrigados por pivô central",
    categoriaSetor: "Celulose, Papel & Agroindústria",
    codigoIbgeMunicipio: "3170404",
    municipioNome: "Unaí",
    baciaHidrografica: "Rio Preto e Rio Paracatu (Bacia do São Francisco)",
    aguaOutorgadaM3Ano: 145000000,
    energiaConsumidaMwhAno: 960000,
    combustivelLitrosAno: 78000000,
    empregosDiretos: 4200,
    capitalMovimentadoBrl: 8500000000,
    tarifaAguaEmpresaBrlM3: 0.015,
    tarifaAguaCidadaoBrlM3: 9.10,
    tarifaEnergiaEmpresaBrlKwh: 0.17,
    tarifaEnergiaCidadaoBrlKwh: 0.96,
    fonteAgua: "ANA CNARH / IGAM Outorgas de Pivôs Centrais",
    urlFonteAgua: "https://www.snirh.gov.br/cnarh/",
    fonteEnergia: "ANEEL Tarifa Irrigante Noturna / CCEE",
    urlFonteEnergia: "https://dadosabertos.aneel.gov.br/",
    fonteCombustivel: "ANP Óleo Diesel Agrícola",
    urlFonteCombustivel: "https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos",
    fonteEmpregoCapital: "IBGE PAM / RAIS MTE",
    urlFonteEmpregoCapital: "https://sidra.ibge.gov.br/",
  },
];

// ══════════════════════════════════════════════════════════════════════════
// 2. OS 20 PAÍSES DO G20 — CONSUMO DE RECURSOS, SETORES E CORPORAÇÕES
// Fontes: World Bank API, FAO Aquastat, US EIA, ILOSTAT, EPA ECHO, ECCC NPRI,
// Climate TRACE, Eurostat, SEC EDGAR, TSX, Companies House.
// ══════════════════════════════════════════════════════════════════════════

export const G20_CONSUMO_CORPORATIVO = [
  {
    pais: "Brasil",
    codigoIso3: "BRA",
    bandeira: "🇧🇷",
    continente: "América do Sul",
    retiradaAguaTotalBilhoesM3Ano: 67.2,
    pctAguaAgricola: 60.5,
    pctAguaIndustrial: 17.0,
    pctAguaDomestica: 22.5,
    energiaEletricaTotalTwhAno: 698.0,
    energiaEletricaKwhPerCapita: 3240,
    combustivelPetroleoMilBarrisDia: 3120,
    forcaTrabalhoMilhoes: 108.4,
    pibBilhoesUsd: 2173.0,
    tarifaEnergiaIndustrialUsdKwh: 0.095,
    tarifaEnergiaResidencialUsdKwh: 0.185,
    tarifaAguaBrutaIndustrialUsdM3: 0.006,
    tarifaAguaResidencialUsdM3: 1.72,
    topCorporacoesConsumidoras: "Vale S.A., Petrobras, JBS, Suzano Celulose, CSN, Gerdau, Alcoa/Alumar, ArcelorMittal, Braskem, Raízen",
    setorMaisIntensivoAgua: "Irrigação de Commodities (Soja/Cana) e Mineração de Ferro",
    setorMaisIntensivoEnergia: "Metalurgia do Alumínio, Siderurgia e Ferro-ligas",
    fontePrimariaPais: "ANA CNARH / CCEE / ANEEL / ANP / IBGE / FAO Aquastat",
    urlFonteOficial: "https://www.snirh.gov.br/cnarh/",
    urlWorldBank: "https://data.worldbank.org/country/brazil",
  },
  {
    pais: "Estados Unidos",
    codigoIso3: "USA",
    bandeira: "🇺🇸",
    continente: "América do Norte",
    retiradaAguaTotalBilhoesM3Ano: 444.3,
    pctAguaAgricola: 39.7,
    pctAguaIndustrial: 47.1,
    pctAguaDomestica: 13.2,
    energiaEletricaTotalTwhAno: 4286.0,
    energiaEletricaKwhPerCapita: 12705,
    combustivelPetroleoMilBarrisDia: 20250,
    forcaTrabalhoMilhoes: 168.1,
    pibBilhoesUsd: 27360.0,
    tarifaEnergiaIndustrialUsdKwh: 0.081,
    tarifaEnergiaResidencialUsdKwh: 0.162,
    tarifaAguaBrutaIndustrialUsdM3: 0.015,
    tarifaAguaResidencialUsdM3: 2.15,
    topCorporacoesConsumidoras: "ExxonMobil, Chevron, Dow Chemical, Nucor Steel, Alcoa, Cargill, Tyson Foods, Freeport-McMoRan, Microsoft/AWS Data Centers",
    setorMaisIntensivoAgua: "Refrigeração Termelétrica/Nuclear e Irrigação Agroindustrial",
    setorMaisIntensivoEnergia: "Refino Petroquímico, Siderurgia e Hiper-Data Centers",
    fontePrimariaPais: "USGS Water Use / EPA ECHO / US EIA / SEC EDGAR",
    urlFonteOficial: "https://echo.epa.gov/",
    urlWorldBank: "https://data.worldbank.org/country/united-states",
  },
  {
    pais: "Canadá",
    codigoIso3: "CAN",
    bandeira: "🇨🇦",
    continente: "América do Norte",
    retiradaAguaTotalBilhoesM3Ano: 35.9,
    pctAguaAgricola: 10.2,
    pctAguaIndustrial: 76.5,
    pctAguaDomestica: 13.3,
    energiaEletricaTotalTwhAno: 642.0,
    energiaEletricaKwhPerCapita: 16020,
    combustivelPetroleoMilBarrisDia: 2410,
    forcaTrabalhoMilhoes: 21.6,
    pibBilhoesUsd: 2140.0,
    tarifaEnergiaIndustrialUsdKwh: 0.068,
    tarifaEnergiaResidencialUsdKwh: 0.125,
    tarifaAguaBrutaIndustrialUsdM3: 0.004,
    tarifaAguaResidencialUsdM3: 1.85,
    topCorporacoesConsumidoras: "Suncor Energy, Canadian Natural Resources (CNRL), Rio Tinto Alcan, Vale Base Metals (Sudbury), Teck Resources, Imperial Oil, Barrick Gold",
    setorMaisIntensivoAgua: "Extração de Areias Betuminosas (Oil Sands Alberta) e Mineração",
    setorMaisIntensivoEnergia: "Fundição de Alumínio (Quebec/BC) e Extração de Petróleo Pesado",
    fontePrimariaPais: "Environment Canada ECCC NPRI / StatCan / TSX SEDAR+",
    urlFonteOficial: "https://www.canada.ca/en/services/environment/pollution-waste-management/national-pollutant-release-inventory.html",
    urlWorldBank: "https://data.worldbank.org/country/canada",
  },
  {
    pais: "China",
    codigoIso3: "CHN",
    bandeira: "🇨🇳",
    continente: "Ásia",
    retiradaAguaTotalBilhoesM3Ano: 591.0,
    pctAguaAgricola: 62.1,
    pctAguaIndustrial: 21.0,
    pctAguaDomestica: 16.9,
    energiaEletricaTotalTwhAno: 9220.0,
    energiaEletricaKwhPerCapita: 6530,
    combustivelPetroleoMilBarrisDia: 16400,
    forcaTrabalhoMilhoes: 778.0,
    pibBilhoesUsd: 17795.0,
    tarifaEnergiaIndustrialUsdKwh: 0.088,
    tarifaEnergiaResidencialUsdKwh: 0.079,
    tarifaAguaBrutaIndustrialUsdM3: 0.055,
    tarifaAguaResidencialUsdM3: 0.62,
    topCorporacoesConsumidoras: "China Baowu Steel, Sinopec, PetroChina, Chalco (Aluminum Corp), State Grid, China Shenhua Energy, Zijin Mining, CMOC",
    setorMaisIntensivoAgua: "Agricultura Irrigada, Siderurgia Pesada e Carboquímica",
    setorMaisIntensivoEnergia: "Siderurgia (50% do aço mundial), Alumínio e Refino Químico",
    fontePrimariaPais: "National Bureau of Statistics China / Climate TRACE / FAO Aquastat",
    urlFonteOficial: "https://climatetrace.org/",
    urlWorldBank: "https://data.worldbank.org/country/china",
  },
  {
    pais: "Alemanha",
    codigoIso3: "DEU",
    bandeira: "🇩🇪",
    continente: "Europa",
    retiradaAguaTotalBilhoesM3Ano: 24.4,
    pctAguaAgricola: 2.5,
    pctAguaIndustrial: 77.8,
    pctAguaDomestica: 19.7,
    energiaEletricaTotalTwhAno: 512.0,
    energiaEletricaKwhPerCapita: 6060,
    combustivelPetroleoMilBarrisDia: 2110,
    forcaTrabalhoMilhoes: 44.5,
    pibBilhoesUsd: 4456.0,
    tarifaEnergiaIndustrialUsdKwh: 0.195,
    tarifaEnergiaResidencialUsdKwh: 0.415,
    tarifaAguaBrutaIndustrialUsdM3: 0.090,
    tarifaAguaResidencialUsdM3: 3.85,
    topCorporacoesConsumidoras: "BASF SE (Ludwigshafen), Thyssenkrupp Steel, RWE AG, Volkswagen Group, Bayer AG, Salzgitter AG, Heidelberg Materials",
    setorMaisIntensivoAgua: "Indústria Química Pesada (Bacia do Reno) e Termelétricas",
    setorMaisIntensivoEnergia: "Química Integrada (BASF consome 6 TWh/ano sozinha) e Aço",
    fontePrimariaPais: "Destatis / Umweltbundesamt (UBA) / BAFA LkSG / Eurostat",
    urlFonteOficial: "https://www.destatis.de/EN/Home/_node.html",
    urlWorldBank: "https://data.worldbank.org/country/germany",
  },
  {
    pais: "Reino Unido",
    codigoIso3: "GBR",
    bandeira: "🇬🇧",
    continente: "Europa",
    retiradaAguaTotalBilhoesM3Ano: 8.4,
    pctAguaAgricola: 13.8,
    pctAguaIndustrial: 14.2,
    pctAguaDomestica: 72.0,
    energiaEletricaTotalTwhAno: 292.0,
    energiaEletricaKwhPerCapita: 4310,
    combustivelPetroleoMilBarrisDia: 1390,
    forcaTrabalhoMilhoes: 34.6,
    pibBilhoesUsd: 3340.0,
    tarifaEnergiaIndustrialUsdKwh: 0.245,
    tarifaEnergiaResidencialUsdKwh: 0.370,
    tarifaAguaBrutaIndustrialUsdM3: 0.045,
    tarifaAguaResidencialUsdM3: 2.95,
    topCorporacoesConsumidoras: "INEOS, Tata Steel UK (Port Talbot), British Steel, Shell UK, BP plc, Thames Water, Rio Tinto / Anglo American (Sedes Globais)",
    setorMaisIntensivoAgua: "Concessionárias Privatizadas de Saneamento e Petroquímica",
    setorMaisIntensivoEnergia: "Siderurgia, Refino no Mar do Norte e Setor Financeiro/Dados",
    fontePrimariaPais: "UK Environment Agency / Companies House / DEFRA",
    urlFonteOficial: "https://environment.data.gov.uk/",
    urlWorldBank: "https://data.worldbank.org/country/united-kingdom",
  },
  {
    pais: "França",
    codigoIso3: "FRA",
    bandeira: "🇫🇷",
    continente: "Europa",
    retiradaAguaTotalBilhoesM3Ano: 26.8,
    pctAguaAgricola: 11.8,
    pctAguaIndustrial: 67.5,
    pctAguaDomestica: 20.7,
    energiaEletricaTotalTwhAno: 448.0,
    energiaEletricaKwhPerCapita: 6580,
    combustivelPetroleoMilBarrisDia: 1510,
    forcaTrabalhoMilhoes: 31.4,
    pibBilhoesUsd: 3030.0,
    tarifaEnergiaIndustrialUsdKwh: 0.165,
    tarifaEnergiaResidencialUsdKwh: 0.275,
    tarifaAguaBrutaIndustrialUsdM3: 0.052,
    tarifaAguaResidencialUsdM3: 3.40,
    topCorporacoesConsumidoras: "EDF (Frota Nuclear), TotalEnergies, ArcelorMittal Dunkerque/Fos, Air Liquide, Saint-Gobain, Veolia, Suez, Vallourec",
    setorMaisIntensivoAgua: "Refrigeração de Usinas Nucleares (Rios Ródano e Loire) e Agro",
    setorMaisIntensivoEnergia: "Metalurgia, Gases Industriais e Indústria Aeroespacial",
    fontePrimariaPais: "Eaufrance / INSEE / data.gouv.fr / Eurostat",
    urlFonteOficial: "https://www.eaufrance.fr/",
    urlWorldBank: "https://data.worldbank.org/country/france",
  },
  {
    pais: "Itália",
    codigoIso3: "ITA",
    bandeira: "🇮🇹",
    continente: "Europa",
    retiradaAguaTotalBilhoesM3Ano: 33.9,
    pctAguaAgricola: 49.5,
    pctAguaIndustrial: 22.8,
    pctAguaDomestica: 27.7,
    energiaEletricaTotalTwhAno: 308.0,
    energiaEletricaKwhPerCapita: 5230,
    combustivelPetroleoMilBarrisDia: 1240,
    forcaTrabalhoMilhoes: 25.4,
    pibBilhoesUsd: 2254.0,
    tarifaEnergiaIndustrialUsdKwh: 0.215,
    tarifaEnergiaResidencialUsdKwh: 0.345,
    tarifaAguaBrutaIndustrialUsdM3: 0.048,
    tarifaAguaResidencialUsdM3: 2.30,
    topCorporacoesConsumidoras: "Eni S.p.A., Enel S.p.A., Acciaierie d'Italia (Ex-Ilva Taranto), Arvedi Steel, Edison, Stellantis Itália, Prysmian",
    setorMaisIntensivoAgua: "Irrigação no Vale do Pó e Polo Siderúrgico de Taranto",
    setorMaisIntensivoEnergia: "Siderurgia em Forno Elétrico, Cerâmica e Manufatura",
    fontePrimariaPais: "ISPRA Ambiente / ISTAT / ARERA / Eurostat",
    urlFonteOficial: "https://www.isprambiente.gov.it/",
    urlWorldBank: "https://data.worldbank.org/country/italy",
  },
  {
    pais: "Índia",
    codigoIso3: "IND",
    bandeira: "🇮🇳",
    continente: "Ásia",
    retiradaAguaTotalBilhoesM3Ano: 647.5,
    pctAguaAgricola: 90.4,
    pctAguaIndustrial: 2.2,
    pctAguaDomestica: 7.4,
    energiaEletricaTotalTwhAno: 1840.0,
    energiaEletricaKwhPerCapita: 1295,
    combustivelPetroleoMilBarrisDia: 5420,
    forcaTrabalhoMilhoes: 594.0,
    pibBilhoesUsd: 3549.0,
    tarifaEnergiaIndustrialUsdKwh: 0.105,
    tarifaEnergiaResidencialUsdKwh: 0.075,
    tarifaAguaBrutaIndustrialUsdM3: 0.035,
    tarifaAguaResidencialUsdM3: 0.28,
    topCorporacoesConsumidoras: "NTPC Limited, Coal India, Tata Steel, JSW Steel, Reliance Industries (Jamnagar), Vedanta Resources, Hindalco, Adani Power",
    setorMaisIntensivoAgua: "Extração Subterrânea Agrícola (Monções) e Termelétricas a Carvão",
    setorMaisIntensivoEnergia: "Refino de Petróleo (Jamnagar), Siderurgia e Alumínio",
    fontePrimariaPais: "Central Water Commission India / CEA / FAO Aquastat",
    urlFonteOficial: "https://data.apps.fao.org/aquastat/",
    urlWorldBank: "https://data.worldbank.org/country/india",
  },
  {
    pais: "Japão",
    codigoIso3: "JPN",
    bandeira: "🇯🇵",
    continente: "Ásia",
    retiradaAguaTotalBilhoesM3Ano: 78.4,
    pctAguaAgricola: 67.6,
    pctAguaIndustrial: 13.5,
    pctAguaDomestica: 18.9,
    energiaEletricaTotalTwhAno: 942.0,
    energiaEletricaKwhPerCapita: 7560,
    combustivelPetroleoMilBarrisDia: 3280,
    forcaTrabalhoMilhoes: 69.1,
    pibBilhoesUsd: 4212.0,
    tarifaEnergiaIndustrialUsdKwh: 0.175,
    tarifaEnergiaResidencialUsdKwh: 0.235,
    tarifaAguaBrutaIndustrialUsdM3: 0.085,
    tarifaAguaResidencialUsdM3: 1.95,
    topCorporacoesConsumidoras: "Nippon Steel, JFE Steel, TEPCO, ENEOS Holdings, Toyota Motor, Mitsubishi Chemical, Sumitomo Metal Mining, Mitsui & Co.",
    setorMaisIntensivoAgua: "Rizicultura Irrigada, Siderurgia Costeira e Semicondutores",
    setorMaisIntensivoEnergia: "Altos-fornos Siderúrgicos, Química e Indústria Automotiva",
    fontePrimariaPais: "METI Japan / MLIT Water Resources / US EIA",
    urlFonteOficial: "https://www.meti.go.jp/english/statistics/",
    urlWorldBank: "https://data.worldbank.org/country/japan",
  },
  {
    pais: "Austrália",
    codigoIso3: "AUS",
    bandeira: "🇦🇺",
    continente: "Oceania",
    retiradaAguaTotalBilhoesM3Ano: 13.7,
    pctAguaAgricola: 67.2,
    pctAguaIndustrial: 11.4,
    pctAguaDomestica: 21.4,
    energiaEletricaTotalTwhAno: 268.0,
    energiaEletricaKwhPerCapita: 10050,
    combustivelPetroleoMilBarrisDia: 1080,
    forcaTrabalhoMilhoes: 14.5,
    pibBilhoesUsd: 1723.0,
    tarifaEnergiaIndustrialUsdKwh: 0.135,
    tarifaEnergiaResidencialUsdKwh: 0.265,
    tarifaAguaBrutaIndustrialUsdM3: 0.042,
    tarifaAguaResidencialUsdM3: 2.80,
    topCorporacoesConsumidoras: "BHP Group (Pilbara / Olympic Dam), Rio Tinto, Fortescue Metals, Glencore Australia, Alcoa Australia, Woodside Energy, South32",
    setorMaisIntensivoAgua: "Mineração no Deserto de Pilbara (Rebaixamento) e Bacia Murray-Darling",
    setorMaisIntensivoEnergia: "Fundição de Alumínio, Liquefação de GNL e Mineração de Ferro/Carvão",
    fontePrimariaPais: "Australian Bureau of Statistics (ABS) / NPI / Bureau of Meteorology",
    urlFonteOficial: "https://www.npi.gov.au/",
    urlWorldBank: "https://data.worldbank.org/country/australia",
  },
  {
    pais: "Coreia do Sul",
    codigoIso3: "KOR",
    bandeira: "🇰🇷",
    continente: "Ásia",
    retiradaAguaTotalBilhoesM3Ano: 29.2,
    pctAguaAgricola: 52.8,
    pctAguaIndustrial: 19.4,
    pctAguaDomestica: 27.8,
    energiaEletricaTotalTwhAno: 588.0,
    energiaEletricaKwhPerCapita: 11360,
    combustivelPetroleoMilBarrisDia: 2510,
    forcaTrabalhoMilhoes: 29.3,
    pibBilhoesUsd: 1712.0,
    tarifaEnergiaIndustrialUsdKwh: 0.115,
    tarifaEnergiaResidencialUsdKwh: 0.128,
    tarifaAguaBrutaIndustrialUsdM3: 0.065,
    tarifaAguaResidencialUsdM3: 0.95,
    topCorporacoesConsumidoras: "POSCO (Pohang e Gwangyang), Samsung Electronics (Fabs de Chips), SK Hynix, Hyundai Steel, LG Chem, S-Oil, KEPCO",
    setorMaisIntensivoAgua: "Fábricas de Semicondutores (Água Ultrapura) e Siderurgia",
    setorMaisIntensivoEnergia: "Siderurgia Integrada (POSCO), Semicondutores e Petroquímica",
    fontePrimariaPais: "Korea Environment Corporation / KESIS / World Bank",
    urlFonteOficial: "https://www.kesis.net/",
    urlWorldBank: "https://data.worldbank.org/country/korea-rep",
  },
  {
    pais: "Arábia Saudita",
    codigoIso3: "SAU",
    bandeira: "🇸🇦",
    continente: "Ásia",
    retiradaAguaTotalBilhoesM3Ano: 23.8,
    pctAguaAgricola: 81.5,
    pctAguaIndustrial: 4.5,
    pctAguaDomestica: 14.0,
    energiaEletricaTotalTwhAno: 396.0,
    energiaEletricaKwhPerCapita: 10720,
    combustivelPetroleoMilBarrisDia: 3680,
    forcaTrabalhoMilhoes: 16.4,
    pibBilhoesUsd: 1067.0,
    tarifaEnergiaIndustrialUsdKwh: 0.048,
    tarifaEnergiaResidencialUsdKwh: 0.053,
    tarifaAguaBrutaIndustrialUsdM3: 0.012,
    tarifaAguaResidencialUsdM3: 1.40,
    topCorporacoesConsumidoras: "Saudi Aramco, SABIC (Petroquímica), Ma'aden (Saudi Arabian Mining / Manara), Saline Water Conversion Corp (SWCC), SEC",
    setorMaisIntensivoAgua: "Extração de Aquíferos Fósseis Não-Renováveis e Dessalinização",
    setorMaisIntensivoEnergia: "Dessalinização Térmica/Osmose, Refino e Alumínio (Ma'aden)",
    fontePrimariaPais: "GASTAT Saudi Arabia / FAO Aquastat / US EIA",
    urlFonteOficial: "https://www.stats.gov.sa/en",
    urlWorldBank: "https://data.worldbank.org/country/saudi-arabia",
  },
  {
    pais: "África do Sul",
    codigoIso3: "ZAF",
    bandeira: "🇿🇦",
    continente: "África",
    retiradaAguaTotalBilhoesM3Ano: 19.3,
    pctAguaAgricola: 61.8,
    pctAguaIndustrial: 11.2,
    pctAguaDomestica: 27.0,
    energiaEletricaTotalTwhAno: 224.0,
    energiaEletricaKwhPerCapita: 3710,
    combustivelPetroleoMilBarrisDia: 610,
    forcaTrabalhoMilhoes: 24.8,
    pibBilhoesUsd: 377.0,
    tarifaEnergiaIndustrialUsdKwh: 0.078,
    tarifaEnergiaResidencialUsdKwh: 0.165,
    tarifaAguaBrutaIndustrialUsdM3: 0.032,
    tarifaAguaResidencialUsdM3: 1.60,
    topCorporacoesConsumidoras: "Eskom (Termelétricas a Carvão), Sasol (Carvão-para-Líquido Secunda), Anglo American Platinum, Sibanye-Stillwater, ArcelorMittal SA",
    setorMaisIntensivoAgua: "Geração a Carvão em Bacias Secas (Mpumalanga) e Mineração Profunda",
    setorMaisIntensivoEnergia: "Complexo Sintético Sasol, Fundições de Cromo/Platina e Minas",
    fontePrimariaPais: "Department of Water and Sanitation SA / Stats SA / Climate TRACE",
    urlFonteOficial: "https://www.dws.gov.za/",
    urlWorldBank: "https://data.worldbank.org/country/south-africa",
  },
  {
    pais: "México",
    codigoIso3: "MEX",
    bandeira: "🇲🇽",
    continente: "América do Norte",
    retiradaAguaTotalBilhoesM3Ano: 89.6,
    pctAguaAgricola: 76.0,
    pctAguaIndustrial: 9.2,
    pctAguaDomestica: 14.8,
    energiaEletricaTotalTwhAno: 342.0,
    energiaEletricaKwhPerCapita: 2660,
    combustivelPetroleoMilBarrisDia: 1920,
    forcaTrabalhoMilhoes: 60.8,
    pibBilhoesUsd: 1788.0,
    tarifaEnergiaIndustrialUsdKwh: 0.112,
    tarifaEnergiaResidencialUsdKwh: 0.098,
    tarifaAguaBrutaIndustrialUsdM3: 0.018,
    tarifaAguaResidencialUsdM3: 1.15,
    topCorporacoesConsumidoras: "PEMEX, CFE, Grupo México (Buenavista del Cobre), Ternium México, Cemex, FEMSA / Coca-Cola, Constellation Brands, Peñoles",
    setorMaisIntensivoAgua: "Concessões CONAGUA para Mineração no Norte Árido e Cervejarias",
    setorMaisIntensivoEnergia: "Refino PEMEX, Cimento (Cemex) e Siderurgia (Ternium)",
    fontePrimariaPais: "CONAGUA REPDA (Registro Público de Derechos de Agua) / INEGI",
    urlFonteOficial: "https://app.conagua.gob.mx/consultarepda.aspx",
    urlWorldBank: "https://data.worldbank.org/country/mexico",
  },
  {
    pais: "Argentina",
    codigoIso3: "ARG",
    bandeira: "🇦🇷",
    continente: "América do Sul",
    retiradaAguaTotalBilhoesM3Ano: 37.8,
    pctAguaAgricola: 73.9,
    pctAguaIndustrial: 10.6,
    pctAguaDomestica: 15.5,
    energiaEletricaTotalTwhAno: 146.0,
    energiaEletricaKwhPerCapita: 3180,
    combustivelPetroleoMilBarrisDia: 690,
    forcaTrabalhoMilhoes: 21.4,
    pibBilhoesUsd: 640.0,
    tarifaEnergiaIndustrialUsdKwh: 0.072,
    tarifaEnergiaResidencialUsdKwh: 0.089,
    tarifaAguaBrutaIndustrialUsdM3: 0.008,
    tarifaAguaResidencialUsdM3: 0.95,
    topCorporacoesConsumidoras: "YPF S.A. (Vaca Muerta Fracking), Ternium Argentina (Techint), Aluar Aluminio, Arcadium Lithium (Salar del Hombre Muerto), Barrick Veladero",
    setorMaisIntensivoAgua: "Salmouras de Lítio na Puna (Jujuy/Catamarca/Salta) e Fracking",
    setorMaisIntensivoEnergia: "Alumínio Primário (Aluar Puerto Madryn) e Siderurgia",
    fontePrimariaPais: "Secretaría de Energía Argentina / CAMMESA / INDEC",
    urlFonteOficial: "https://cammesaweb.cammesa.com/",
    urlWorldBank: "https://data.worldbank.org/country/argentina",
  },
  {
    pais: "Rússia",
    codigoIso3: "RUS",
    bandeira: "🇷🇺",
    continente: "Eurásia",
    retiradaAguaTotalBilhoesM3Ano: 64.4,
    pctAguaAgricola: 28.5,
    pctAguaIndustrial: 51.2,
    pctAguaDomestica: 20.3,
    energiaEletricaTotalTwhAno: 1125.0,
    energiaEletricaKwhPerCapita: 7820,
    combustivelPetroleoMilBarrisDia: 3740,
    forcaTrabalhoMilhoes: 73.6,
    pibBilhoesUsd: 2021.0,
    tarifaEnergiaIndustrialUsdKwh: 0.052,
    tarifaEnergiaResidencialUsdKwh: 0.058,
    tarifaAguaBrutaIndustrialUsdM3: 0.009,
    tarifaAguaResidencialUsdM3: 0.65,
    topCorporacoesConsumidoras: "Gazprom, Rosneft, Rusal (Alumínio Siberiano), Nornickel (Norilsk), Severstal, NLMK, Evraz, Lukoil",
    setorMaisIntensivoAgua: "Complexos Metalúrgicos Árticos e Refrigeração Termonuclear",
    setorMaisIntensivoEnergia: "Fundição de Alumínio (Rusal) e Mineração de Níquel/Paládio",
    fontePrimariaPais: "FAO Aquastat / US EIA International / Climate TRACE",
    urlFonteOficial: "https://climatetrace.org/",
    urlWorldBank: "https://data.worldbank.org/country/russian-federation",
  },
  {
    pais: "Indonésia",
    codigoIso3: "IDN",
    bandeira: "🇮🇩",
    continente: "Ásia",
    retiradaAguaTotalBilhoesM3Ano: 222.6,
    pctAguaAgricola: 85.2,
    pctAguaIndustrial: 5.1,
    pctAguaDomestica: 9.7,
    energiaEletricaTotalTwhAno: 356.0,
    energiaEletricaKwhPerCapita: 1280,
    combustivelPetroleoMilBarrisDia: 1690,
    forcaTrabalhoMilhoes: 142.5,
    pibBilhoesUsd: 1371.0,
    tarifaEnergiaIndustrialUsdKwh: 0.074,
    tarifaEnergiaResidencialUsdKwh: 0.092,
    tarifaAguaBrutaIndustrialUsdM3: 0.011,
    tarifaAguaResidencialUsdM3: 0.55,
    topCorporacoesConsumidoras: "Freeport Indonesia (Mina Grasberg), Pertamina, PLN, Tsingshan Morowali Industrial Park (Níquel), Vale Indonesia (PT Inco), Adaro Energy",
    setorMaisIntensivoAgua: "Processamento Hidrometalúrgico de Níquel (HPAL) e Óleo de Palma",
    setorMaisIntensivoEnergia: "Fundições de Níquel movidas a Carvão Cativo em Sulawesi",
    fontePrimariaPais: "BPS Statistics Indonesia / Climate TRACE / FAO Aquastat",
    urlFonteOficial: "https://www.bps.go.id/en",
    urlWorldBank: "https://data.worldbank.org/country/indonesia",
  },
  {
    pais: "Turquia",
    codigoIso3: "TUR",
    bandeira: "🇹🇷",
    continente: "Eurásia",
    retiradaAguaTotalBilhoesM3Ano: 61.5,
    pctAguaAgricola: 80.7,
    pctAguaIndustrial: 8.1,
    pctAguaDomestica: 11.2,
    energiaEletricaTotalTwhAno: 331.0,
    energiaEletricaKwhPerCapita: 3870,
    combustivelPetroleoMilBarrisDia: 1050,
    forcaTrabalhoMilhoes: 35.2,
    pibBilhoesUsd: 1108.0,
    tarifaEnergiaIndustrialUsdKwh: 0.118,
    tarifaEnergiaResidencialUsdKwh: 0.086,
    tarifaAguaBrutaIndustrialUsdM3: 0.028,
    tarifaAguaResidencialUsdM3: 1.10,
    topCorporacoesConsumidoras: "Erdemir (Ereğli Demir ve Çelik), Kardemir, Tüpraş (Refino), İçdaş Steel, Eti Maden (Boro), Şişecam, Çalık Enerji",
    setorMaisIntensivoAgua: "Irrigação na Anatólia (GAP), Têxtil e Siderurgia",
    setorMaisIntensivoEnergia: "Fornos Elétricos a Arco (Maior produtor de aço da Europa/Oriente Médio)",
    fontePrimariaPais: "TurkStat (TÜİK) / DSI State Hydraulic Works / Eurostat",
    urlFonteOficial: "https://www.tuik.gov.tr/Home/Index",
    urlWorldBank: "https://data.worldbank.org/country/turkiye",
  },
  {
    pais: "União Europeia",
    codigoIso3: "EUU",
    bandeira: "🇪🇺",
    continente: "Europa",
    retiradaAguaTotalBilhoesM3Ano: 198.5,
    pctAguaAgricola: 29.4,
    pctAguaIndustrial: 48.2,
    pctAguaDomestica: 22.4,
    energiaEletricaTotalTwhAno: 2695.0,
    energiaEletricaKwhPerCapita: 6010,
    combustivelPetroleoMilBarrisDia: 10950,
    forcaTrabalhoMilhoes: 217.0,
    pibBilhoesUsd: 18349.0,
    tarifaEnergiaIndustrialUsdKwh: 0.188,
    tarifaEnergiaResidencialUsdKwh: 0.312,
    tarifaAguaBrutaIndustrialUsdM3: 0.062,
    tarifaAguaResidencialUsdM3: 3.10,
    topCorporacoesConsumidoras: "ArcelorMittal Europe, BASF, TotalEnergies, Shell (Roterdã), Enel, Iberdrola, RWE, Thyssenkrupp, Repsol, EDP",
    setorMaisIntensivoAgua: "Refrigeração Industrial/Energética e Agricultura Mediterrânea",
    setorMaisIntensivoEnergia: "Química, Siderurgia, Refino (Porto de Roterdã/Antuérpia) e Papel",
    fontePrimariaPais: "Eurostat / European Environment Agency (E-PRTR Industrial Portal)",
    urlFonteOficial: "https://industry.eea.europa.eu/",
    urlWorldBank: "https://data.worldbank.org/region/european-union",
  },
];

// ══════════════════════════════════════════════════════════════════════════
// 3. PEGADA HÍDRICA & ENERGÉTICA DE COMMODITIES E GERAÇÃO DE EMPREGO POR CNAE
// Fontes: Water Footprint Network, FAO Aquastat, EPE Balanço Energético, RAIS/MTE
// ══════════════════════════════════════════════════════════════════════════

export const PEGADA_E_INTENSIDADE_SETORIAL = [
  {
    id: "pegada-01",
    produtoOuSetor: "Minério de Ferro (Pelotização e Mineroduto)",
    cnaeAssociado: "0710-3 Extração de minério de ferro",
    aguaLitrosPorTonelada: 680,
    energiaKwhPorTonelada: 52,
    empregosPorBilhaoLitrosAgua: 145,
    empregosPorGwhEnergia: 5.1,
    destinoExportacaoPrincipal: "China (68%), União Europeia (12%), Japão (8%)",
    observacaoCivica: "Baixíssima geração de emprego direto por bilhão de litros de água captados; deixa passivo permanente de barragens.",
    urlFonte: "https://www.snirh.gov.br/cnarh/",
  },
  {
    id: "pegada-02",
    produtoOuSetor: "Carbonato/Concentrado de Lítio (Vale do Jequitinhonha)",
    cnaeAssociado: "0729-4 Extração de minerais metálicos não ferrosos",
    aguaLitrosPorTonelada: 14500,
    energiaKwhPorTonelada: 480,
    empregosPorBilhaoLitrosAgua: 130,
    empregosPorGwhEnergia: 5.8,
    destinoExportacaoPrincipal: "China (55%), Estados Unidos (25%), Coreia do Sul (15%)",
    observacaoCivica: "Concentrada no semiárido mineiro (Araçuaí/Itinga), onde comunidades rurais enfrentam racionamento hídrico.",
    urlFonte: "https://www.igam.mg.gov.br/",
  },
  {
    id: "pegada-03",
    produtoOuSetor: "Aço Bruto e Laminados Siderúrgicos",
    cnaeAssociado: "2421-1 / 2422-9 Siderurgia integrada",
    aguaLitrosPorTonelada: 28500,
    energiaKwhPorTonelada: 690,
    empregosPorBilhaoLitrosAgua: 185,
    empregosPorGwhEnergia: 4.2,
    destinoExportacaoPrincipal: "Estados Unidos (45%), América do Sul (25%), Europa (15%)",
    observacaoCivica: "Altíssimo consumo de carvão mineral/vegetal e energia elétrica subsidiada no Mercado Livre.",
    urlFonte: "https://dadosabertos.ccee.org.br/",
  },
  {
    id: "pegada-04",
    produtoOuSetor: "Alumínio Primário e Alumina",
    cnaeAssociado: "2441-5 Metalurgia do alumínio",
    aguaLitrosPorTonelada: 34000,
    energiaKwhPorTonelada: 14800,
    empregosPorBilhaoLitrosAgua: 118,
    empregosPorGwhEnergia: 1.6,
    destinoExportacaoPrincipal: "Estados Unidos, União Europeia e Japão",
    observacaoCivica: "Setor mais eletrointensivo da economia: 1 tonelada de alumínio consome o mesmo que 8 residências em um ano inteiro.",
    urlFonte: "https://dadosabertos.ccee.org.br/",
  },
  {
    id: "pegada-05",
    produtoOuSetor: "Celulose Branqueada de Eucalipto",
    cnaeAssociado: "1710-9 Fabricação de celulose",
    aguaLitrosPorTonelada: 32000,
    energiaKwhPorTonelada: 980,
    empregosPorBilhaoLitrosAgua: 105,
    empregosPorGwhEnergia: 5.6,
    destinoExportacaoPrincipal: "China (48%), União Europeia (28%), Estados Unidos (14%)",
    observacaoCivica: "Além da captação industrial no Rio Doce, extensos monocultivos de eucalipto reduzem a recarga de nascentes.",
    urlFonte: "https://www.snirh.gov.br/cnarh/",
  },
  {
    id: "pegada-06",
    produtoOuSetor: "Soja e Milho Irrigados (Pivô Central)",
    cnaeAssociado: "0115-6 Cultivo de cereais e oleaginosas",
    aguaLitrosPorTonelada: 2145000,
    energiaKwhPorTonelada: 210,
    empregosPorBilhaoLitrosAgua: 29,
    empregosPorGwhEnergia: 4.4,
    destinoExportacaoPrincipal: "China (72%), União Europeia (14%), Ásia (10%)",
    observacaoCivica: "Exportação massiva de 'água virtual': cada tonelada de soja embarcada leva mais de 2 milhões de litros de água.",
    urlFonte: "https://data.apps.fao.org/aquastat/",
  },
  {
    id: "pegada-07",
    produtoOuSetor: "Carne Bovina e Proteína Animal",
    cnaeAssociado: "1011-2 Frigoríficos e abate de reses",
    aguaLitrosPorTonelada: 15400000,
    energiaKwhPorTonelada: 840,
    empregosPorBilhaoLitrosAgua: 248,
    empregosPorGwhEnergia: 9.4,
    destinoExportacaoPrincipal: "China, Estados Unidos, Oriente Médio e União Europeia",
    observacaoCivica: "Maior pegada hídrica total (incluindo pastagem, dessedentação e lavagem industrial de carcaças).",
    urlFonte: "https://data.apps.fao.org/aquastat/",
  },
  {
    id: "pegada-08",
    produtoOuSetor: "Indústria Automotiva, Autopeças e Manufatura",
    cnaeAssociado: "2910-7 Fabricação de veículos automotores",
    aguaLitrosPorTonelada: 4200,
    energiaKwhPorTonelada: 1150,
    empregosPorBilhaoLitrosAgua: 1130,
    empregosPorGwhEnergia: 17.5,
    destinoExportacaoPrincipal: "Mercado Interno Brasileiro, Argentina, México e Chile",
    observacaoCivica: "Gera 8 vezes mais empregos diretos por bilhão de litros de água consumidos do que a mineração primária.",
    urlFonte: "https://bi.mte.gov.br/bgcaged/",
  },
  {
    id: "pegada-09",
    produtoOuSetor: "Comércio, Serviços, Tecnologia e Varejo Alimentar",
    cnaeAssociado: "4711-3 Comércio varejista e serviços urbanos",
    aguaLitrosPorTonelada: 450,
    energiaKwhPorTonelada: 180,
    empregosPorBilhaoLitrosAgua: 5390,
    empregosPorGwhEnergia: 50.7,
    destinoExportacaoPrincipal: "Abastecimento Popular Municipal e Regional",
    observacaoCivica: "Campeão em geração de postos de trabalho por unidade de água e energia consumida nas cidades.",
    urlFonte: "https://bi.mte.gov.br/bgcaged/",
  },
];

function sanitizarLista<T extends Record<string, unknown>>(lista: T[]): T[] {
  return lista.map((item) => {
    const limpo: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(item)) {
      if (typeof v === "string") {
        limpo[k] = sanitizarDadoPessoalInternacional(v);
      } else {
        limpo[k] = v;
      }
    }
    return limpo as T;
  });
}

function main() {
  console.log("🚀 Iniciando geração dos datasets de Maiores Consumidores (MG + G20)...");

  if (!fs.existsSync(DIR_OUT)) {
    fs.mkdirSync(DIR_OUT, { recursive: true });
  }

  // 1. Top 50 MG Consumidores
  const mgLimpos = sanitizarLista(TOP_50_MG_CONSUMIDORES);
  const mgCompacto = compactar(mgLimpos);
  const arqMg = path.join(DIR_OUT, "top50-mg-consumidores.compact.json");
  fs.writeFileSync(arqMg, JSON.stringify(mgCompacto, null, 2), "utf-8");
  console.log(
    `✅ top50-mg-consumidores.compact.json gerado (${mgLimpos.length} registros, ${(fs.statSync(arqMg).size / 1024).toFixed(1)} KB).`
  );

  // 2. G20 Consumo Setorial e Corporativo
  const g20Limpos = sanitizarLista(G20_CONSUMO_CORPORATIVO);
  const g20Compacto = compactar(g20Limpos);
  const arqG20 = path.join(DIR_OUT, "g20-consumo-setorial-corporativo.compact.json");
  fs.writeFileSync(arqG20, JSON.stringify(g20Compacto, null, 2), "utf-8");
  console.log(
    `✅ g20-consumo-setorial-corporativo.compact.json gerado (${g20Limpos.length} países, ${(fs.statSync(arqG20).size / 1024).toFixed(1)} KB).`
  );

  // 3. Pegada Hídrica e Intensidade Setorial CNAE
  const pegadaLimpos = sanitizarLista(PEGADA_E_INTENSIDADE_SETORIAL);
  const pegadaCompacto = compactar(pegadaLimpos);
  const arqPegada = path.join(DIR_OUT, "pegada-hidrica-e-cnae.compact.json");
  fs.writeFileSync(arqPegada, JSON.stringify(pegadaCompacto, null, 2), "utf-8");
  console.log(
    `✅ pegada-hidrica-e-cnae.compact.json gerado (${pegadaLimpos.length} setores, ${(fs.statSync(arqPegada).size / 1024).toFixed(1)} KB).`
  );
}

main();
