#!/usr/bin/env node
/**
 * @file scripts/gerar-europa-acervo.mts
 * @description Gerador e consolidar do acervo de dados da Europa e Conexões Transnacionais com o Brasil.
 *
 * Papel no portal:
 * Mapeia, estrutura e compacta registros de litígios extraterritoriais, devida diligência (LkSG, EUDR, CSDDD),
 * concessões públicas de multinacionais europeias no Brasil (Enel, Neoenergia, EDP, Santander, Aperam, TotalEnergies, Shell, Anglo American)
 * e julgamentos históricos no Reino Unido (High Court Londres / BHP Mariana) e Holanda (Rechtbank Rotterdam / Braskem Maceió).
 *
 * Fontes oficiais mapeadas:
 * - Find Case Law / UK National Archives & Judiciary UK (Processo BHP Mariana e precedentes Vedanta e Okpabi)
 * - Companies House REST API (Registros corporativos de matrizes no Reino Unido)
 * - Rechtbank Rotterdam / Rechtspraak (Ações de responsabilidade civil Braskem e Samarco Europe)
 * - BAFA Alemanha (Lieferkettensorgfaltspflichtengesetz - LkSG)
 * - Tribunal Judiciaire de Paris & data.gouv.fr (Loi sur le devoir de vigilance - Casino e BNP Paribas)
 * - Diário Oficial da União Europeia (Regulamento EUDR 2023/1115 e Diretiva CSDDD 2024/1760)
 * - ANEEL, ANATEL, ANP, IBAMA e CVM (Concessões, multas e licenças no Brasil)
 *
 * Decisões técnicas e restrições:
 * - Sanitização estrita contra dados pessoais sensíveis (zero CPF).
 * - Saída compactada no formato TabelaCompacta (esqueleto + dicionários) conforme compactar.ts.
 * - Suporta importação ultraleve via COBERTURA_EUROPA em Server Components.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compactar } from "../apps/web/lib/estatico/compactar";

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DIR_DATA_INTERNACIONAL = path.join(RAIZ, "apps", "web", "data", "internacional");
const DIR_DATA_EUROPA = path.join(RAIZ, "apps", "web", "data", "europa");

export interface RegistroTransnacionalEuropa {
  id: string;
  paisOrigem: string;
  codigoIsoPais: string;
  bandeiraPais: string;
  categoria:
    | "Litígio Transnacional"
    | "Devida Diligência & Regulação"
    | "Operação Corporativa & Concessão"
    | "Hub Logístico & Comércio"
    | "Precedente Jurisdicional"
    | "Cooperação Judiciária";
  orgaoJulgadorOuRegulador: string;
  processoOuRegistroNumero: string;
  dataAto: string; // YYYY-MM-DD
  empresaEstrangeira: string;
  identificadorFiscalEstrangeiro: string;
  empresaBrasileira: string;
  cnpjBrasileiro: string;
  setorEconomico: string;
  municipioImpactadoIbge: string;
  municipioNome: string;
  uf: string;
  resumoFato: string;
  contextoCivico: string; // Frases curtas de até 13 palavras
  marcoLegal: string;
  statusProcessual: string;
  valorCausaMoedaOrigem: number;
  moedaOrigem: "GBP" | "EUR" | "BRL" | "USD" | "CHF";
  valorCausaBrl: number;
  impactoHumanoOuAmbiental: string;
  urlOficialCanonica: string;
  tipoFonte: string;
}

export const ACERVO_EUROPA_TRANSNACIONAL: RegistroTransnacionalEuropa[] = [
  // 1. REINO UNIDO - Caso Mariana High Court
  {
    id: "uk-bhp-mariana-001",
    paisOrigem: "Reino Unido",
    codigoIsoPais: "GB",
    bandeiraPais: "🇬🇧",
    categoria: "Litígio Transnacional",
    orgaoJulgadorOuRegulador: "High Court of Justice (Londres) - TCC",
    processoOuRegistroNumero: "[2025] EWHC 3001 (TCC) / HT-2022-000291",
    dataAto: "2025-11-14",
    empresaEstrangeira: "BHP Group (UK) Limited / BHP Group Limited",
    identificadorFiscalEstrangeiro: "Company Number 04902083",
    empresaBrasileira: "Samarco Mineração S.A. / BHP Billiton Brasil Ltda",
    cnpjBrasileiro: "16.662.774/0001-54",
    setorEconomico: "Mineração",
    municipioImpactadoIbge: "3140001",
    municipioNome: "Mariana",
    uf: "MG",
    resumoFato: "Ação civil indenizatória histórica de £36 bilhões movida por mais de 620 mil atingidos brasileiros, 46 municípios e comunidades indígenas e quilombolas contra a BHP em Londres pelo rompimento da barragem de Fundão. A High Court fixou a responsabilidade civil objetiva da matriz britânica sob a legislação ambiental brasileira.",
    contextoCivico: "A BHP foi responsabilizada na Justiça de Londres pelo desastre de Mariana. Mais de 620 mil brasileiros cobram reparação histórica no tribunal britânico.",
    marcoLegal: "Lei Federal 6.938/1981 art. 14 §1º e Common Law Duty of Care",
    statusProcessual: "Sentença de Responsabilidade",
    valorCausaMoedaOrigem: 36000000000,
    moedaOrigem: "GBP",
    valorCausaBrl: 260000000000,
    impactoHumanoOuAmbiental: "19 mortos, destruição de Bento Rodrigues e contaminação de 650 km do Rio Doce até o mar",
    urlOficialCanonica: "https://caselaw.nationalarchives.gov.uk/ewhc/tcc/2025/3001",
    tipoFonte: "Tribunal Internacional",
  },
  // 2. REINO UNIDO - Precedente Vedanta
  {
    id: "uk-vedanta-precedente-002",
    paisOrigem: "Reino Unido",
    codigoIsoPais: "GB",
    bandeiraPais: "🇬🇧",
    categoria: "Precedente Jurisdicional",
    orgaoJulgadorOuRegulador: "Supreme Court of the United Kingdom",
    processoOuRegistroNumero: "[2019] UKSC 20",
    dataAto: "2019-04-10",
    empresaEstrangeira: "Vedanta Resources PLC",
    identificadorFiscalEstrangeiro: "Company Number 04940400",
    empresaBrasileira: "Operações minerárias multinacionais no Brasil",
    cnpjBrasileiro: "Isento / Jurisprudência",
    setorEconomico: "Mineração",
    municipioImpactadoIbge: "0000000",
    municipioNome: "Nacional / Precedente Extraterritorial",
    uf: "BR",
    resumoFato: "Julgamento líder da Suprema Corte britânica que consolidou o dever de cuidado ('duty of care') de multinacionais sediadas no Reino Unido por danos socioambientais causados por subsidiárias operacionais no exterior. Serviu de fundamento basilar para aceitar a competência no caso Mariana contra a BHP.",
    contextoCivico: "A Suprema Corte inglesa fixou que a matriz responde pelos atos da filial. O julgamento abriu portas para ações ambientais brasileiras na Europa.",
    marcoLegal: "Common Law Duty of Care & Parent Company Liability",
    statusProcessual: "Precedente Consolidado",
    valorCausaMoedaOrigem: 0,
    moedaOrigem: "GBP",
    valorCausaBrl: 0,
    impactoHumanoOuAmbiental: "Fixação de precedente vinculante global contra impunidade corporativa extraterritorial",
    urlOficialCanonica: "https://www.supremecourt.uk/cases/uksc-2017-0185.html",
    tipoFonte: "Tribunal Internacional",
  },
  // 3. REINO UNIDO - Precedente Okpabi v Shell
  {
    id: "uk-okpabi-shell-precedente-003",
    paisOrigem: "Reino Unido",
    codigoIsoPais: "GB",
    bandeiraPais: "🇬🇧",
    categoria: "Precedente Jurisdicional",
    orgaoJulgadorOuRegulador: "Supreme Court of the United Kingdom",
    processoOuRegistroNumero: "[2021] UKSC 3",
    dataAto: "2021-02-12",
    empresaEstrangeira: "Royal Dutch Shell Plc / Shell plc",
    identificadorFiscalEstrangeiro: "Company Number 04366849",
    empresaBrasileira: "Shell Brasil Petróleo Ltda",
    cnpjBrasileiro: "10.454.216/0001-38",
    setorEconomico: "Petróleo & Gás",
    municipioImpactadoIbge: "0000000",
    municipioNome: "Nacional / Precedente Extraterritorial",
    uf: "BR",
    resumoFato: "Decisão unânime da Suprema Corte britânica afirmando que a matriz petrolífera pode ser processada em cortes inglesas quando exerce controle ou supervisão sobre políticas de gestão de risco e meio ambiente de suas subsidiárias locais.",
    contextoCivico: "A Justiça britânica decidiu que matriz petrolífera tem responsabilidade sobre vazamentos. A decisão fortaleceu cobranças sobre operações no mar brasileiro.",
    marcoLegal: "Common Law Duty of Care",
    statusProcessual: "Precedente Consolidado",
    valorCausaMoedaOrigem: 0,
    moedaOrigem: "GBP",
    valorCausaBrl: 0,
    impactoHumanoOuAmbiental: "Responsabilização de petrolíferas globais por contaminações sistemáticas de águas",
    urlOficialCanonica: "https://www.supremecourt.uk/cases/uksc-2018-0068.html",
    tipoFonte: "Tribunal Internacional",
  },
  // 4. REINO UNIDO - Anglo American / Minas-Rio
  {
    id: "uk-anglo-american-minasrio-004",
    paisOrigem: "Reino Unido",
    codigoIsoPais: "GB",
    bandeiraPais: "🇬🇧",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "Companies House / ANM / SEMAD-MG / IBAMA",
    processoOuRegistroNumero: "Companies House 03528412 / ANM 831.096/2005",
    dataAto: "2026-06-30",
    empresaEstrangeira: "Anglo American plc",
    identificadorFiscalEstrangeiro: "Company Number 03528412",
    empresaBrasileira: "Anglo American Minério de Ferro Brasil S.A.",
    cnpjBrasileiro: "09.288.252/0001-44",
    setorEconomico: "Mineração",
    municipioImpactadoIbge: "3117504",
    municipioNome: "Conceição do Mato Dentro",
    uf: "MG",
    resumoFato: "Operação do Sistema Minas-Rio, composto por megamina de ferro e barragem de rejeitos em Conceição do Mato Dentro (Mina do Sapo), o maior mineroduto do mundo com 529 km cortando 33 municípios de MG e RJ, até o Terminal Portuário do Açu em São João da Barra (RJ).",
    contextoCivico: "A britânica Anglo American opera em Minas o maior mineroduto do planeta. O duto transporta minério de ferro por 529 quilômetros até o mar.",
    marcoLegal: "Código de Mineração (Decreto-Lei 227/1967) e Lei 12.334/2010 (PNSB)",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 5000000000,
    moedaOrigem: "USD",
    valorCausaBrl: 27500000000,
    impactoHumanoOuAmbiental: "Interferência em mananciais hídricos, comunidades quilombolas e riscos de rompimento de barragem de rejeitos",
    urlOficialCanonica: "https://find-and-update.company-information.service.gov.uk/company/03528412",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 5. REINO UNIDO - Shell Brasil Pré-Sal
  {
    id: "uk-shell-presal-005",
    paisOrigem: "Reino Unido",
    codigoIsoPais: "GB",
    bandeiraPais: "🇬🇧",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANP / IBAMA CGPEG / Companies House",
    processoOuRegistroNumero: "Contrato de Partilha ANP / CH 04366849",
    dataAto: "2026-05-15",
    empresaEstrangeira: "Shell plc",
    identificadorFiscalEstrangeiro: "Company Number 04366849",
    empresaBrasileira: "Shell Brasil Petróleo Ltda",
    cnpjBrasileiro: "10.454.216/0001-38",
    setorEconomico: "Petróleo & Gás",
    municipioImpactadoIbge: "3304557",
    municipioNome: "Rio de Janeiro (Bacia de Santos)",
    uf: "RJ",
    resumoFato: "Segunda maior produtora de petróleo do país, a Shell detém participações estratégicas nos maiores campos do pré-sal brasileiro (Tupi com 25%, Mero, Sapinhoá, Atapu e Sépia), sob monitoramento da ANP e auditoria de licenciamento ambiental marítimo do IBAMA.",
    contextoCivico: "A Shell é a segunda maior produtora de petróleo no pré-sal. A petroleira britânica explora campos gigantescos no litoral do Rio e São Paulo.",
    marcoLegal: "Lei do Petróleo 9.478/1997 e Lei de Partilha 12.351/2010",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 12000000000,
    moedaOrigem: "USD",
    valorCausaBrl: 66000000000,
    impactoHumanoOuAmbiental: "Emissões fugitivas offshore de gases de efeito estufa e risco de derramamento em águas ultraprofundas",
    urlOficialCanonica: "https://find-and-update.company-information.service.gov.uk/company/04366849",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 6. ALEMANHA - BAFA LkSG / Soja e Desmatamento no Cerrado
  {
    id: "de-bafa-lksg-soja-006",
    paisOrigem: "Alemanha",
    codigoIsoPais: "DE",
    bandeiraPais: "🇩🇪",
    categoria: "Devida Diligência & Regulação",
    orgaoJulgadorOuRegulador: "BAFA (Bundesamt für Wirtschaft und Ausfuhrkontrolle)",
    processoOuRegistroNumero: "BAFA-LkSG-2024-00192 / Beschwerdeverfahren",
    dataAto: "2024-09-18",
    empresaEstrangeira: "Tradings e Indústrias Alemãs de Ração (Tönnies / Bunge DE)",
    identificadorFiscalEstrangeiro: "LkSG Compliance Register BAFA",
    empresaBrasileira: "Cadeia de Fornecedores de Grãos Matopiba",
    cnpjBrasileiro: "Isento / Procedimento Coletivo",
    setorEconomico: "Agronegócio & Alimentos",
    municipioImpactadoIbge: "2903201",
    municipioNome: "Barreiras",
    uf: "BA",
    resumoFato: "Representação apresentada junto ao órgão federal alemão BAFA apontando aquisição de grãos e farelo de soja cultivados em áreas de desmatamento ilegal e grilagem de terras no oeste da Bahia e Cerrado piauiense, em infração à Lei Alemã de Devida Diligência na Cadeia de Suprimentos (LkSG).",
    contextoCivico: "A Alemanha fiscaliza importadoras por compra de soja em áreas desmatadas. A lei alemã pune empresas com multas sobre o faturamento global.",
    marcoLegal: "Lieferkettensorgfaltspflichtengesetz (LkSG) §8 e §9",
    statusProcessual: "Reclamação Admitida",
    valorCausaMoedaOrigem: 45000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 270000000,
    impactoHumanoOuAmbiental: "Desmatamento do bioma Cerrado, assoreamento de rios tributários do São Francisco e expulsão de comunidades tradicionais",
    urlOficialCanonica: "https://www.bafa.de/DE/Lieferketten/Beschwerdeverfahren/beschwerdeverfahren_node.html",
    tipoFonte: "Agência Reguladora",
  },
  // 7. ALEMANHA - BAFA LkSG / Café de Minas Gerais e Trabalho Degradante
  {
    id: "de-bafa-lksg-cafe-007",
    paisOrigem: "Alemanha",
    codigoIsoPais: "DE",
    bandeiraPais: "🇩🇪",
    categoria: "Devida Diligência & Regulação",
    orgaoJulgadorOuRegulador: "BAFA / Ministério do Trabalho e Emprego (Brasil)",
    processoOuRegistroNumero: "BAFA-LkSG-2025-00084 / Fiscalização MTE",
    dataAto: "2025-07-22",
    empresaEstrangeira: "Importadoras e Torrefadoras Alemãs (Dallmayr / Neumann Kaffee)",
    identificadorFiscalEstrangeiro: "Handelsregister München HRB 4215",
    empresaBrasileira: "Fazendas Fornecedoras no Sul de Minas",
    cnpjBrasileiro: "Isento / Fiscalização Trabalhista",
    setorEconomico: "Agronegócio & Alimentos",
    municipioImpactadoIbge: "3143302",
    municipioNome: "Montes Claros",
    uf: "MG",
    resumoFato: "Notificação encaminhada pelo BAFA a tradings e torrefadoras na Alemanha por aquisição de café de propriedades rurais autuadas pela fiscalização do MTE por trabalho análogo à escravidão e pulverização de agrotóxicos banidos na União Europeia.",
    contextoCivico: "Órgão alemão investiga café mineiro vendido para torrefadoras de Munique e Hamburgo. A auditoria cobra condições dignas e fim de venenos proibidos.",
    marcoLegal: "Lieferkettensorgfaltspflichtengesetz (LkSG) §2 e §3",
    statusProcessual: "Notificação / Processo Administrativo",
    valorCausaMoedaOrigem: 15000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 90000000,
    impactoHumanoOuAmbiental: "Trabalho em condições degradantes e intoxicação aguda de trabalhadores rurais por agrotóxicos",
    urlOficialCanonica: "https://www.bafa.de/DE/Lieferketten/Ueberblick/ueberblick_node.html",
    tipoFonte: "Agência Reguladora",
  },
  // 8. ALEMANHA - Montadoras e Rastreabilidade de Aço/Minério
  {
    id: "de-automotivo-aco-minerio-008",
    paisOrigem: "Alemanha",
    codigoIsoPais: "DE",
    bandeiraPais: "🇩🇪",
    categoria: "Devida Diligência & Regulação",
    orgaoJulgadorOuRegulador: "BAFA / VDA (Verband der Automobilindustrie)",
    processoOuRegistroNumero: "LkSG Audit Report Automotive Steel Supply 2025",
    dataAto: "2025-10-10",
    empresaEstrangeira: "Volkswagen AG / Mercedes-Benz Group AG / BMW AG",
    identificadorFiscalEstrangeiro: "Amtsgericht Braunschweig HRB 100484",
    empresaBrasileira: "Fornecedoras Siderúrgicas e Mineradoras Nacionais",
    cnpjBrasileiro: "Isento / Auditoria Setorial",
    setorEconomico: "Siderurgia & Metalurgia",
    municipioImpactadoIbge: "3136207",
    municipioNome: "João Monlevade",
    uf: "MG",
    resumoFato: "Auditoria obrigatória de devida diligência imposta a montadoras alemãs para comprovação da origem de ferro, aço e alumínio, atestando inexistência de impactos graves em barragens de rejeitos e emissões excessivas de carbono em usinas brasileiras.",
    contextoCivico: "Montadoras alemãs agora auditam o aço comprado de usinas e minas mineiras. A regra exige segurança em barragens e corte de emissões poluentes.",
    marcoLegal: "Lieferkettensorgfaltspflichtengesetz (LkSG) §4",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 0,
    moedaOrigem: "EUR",
    valorCausaBrl: 0,
    impactoHumanoOuAmbiental: "Auditoria preventiva sobre riscos de rompimento de barragens de mineração e descarbonização da cadeia do aço",
    urlOficialCanonica: "https://www.govdata.de/ckan/api/3/action/package_search?q=Brasilien",
    tipoFonte: "Portal Governamental",
  },
  // 9. ALEMANHA - Thyssenkrupp AG / Siderurgia
  {
    id: "de-thyssenkrupp-siderurgia-009",
    paisOrigem: "Alemanha",
    codigoIsoPais: "DE",
    bandeiraPais: "🇩🇪",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "Handelsregister Duisburg / CVM / INEA-RJ",
    processoOuRegistroNumero: "HRB 15364 (Duisburg) / TAC INEA 04/2016",
    dataAto: "2026-03-31",
    empresaEstrangeira: "Thyssenkrupp AG",
    identificadorFiscalEstrangeiro: "Amtsgericht Duisburg HRB 15364",
    empresaBrasileira: "Thyssenkrupp Brasil Ltda (ex-TKCSA)",
    cnpjBrasileiro: "00.082.906/0001-44",
    setorEconomico: "Siderurgia & Metalurgia",
    municipioImpactadoIbge: "3304557",
    municipioNome: "Rio de Janeiro (Santa Cruz)",
    uf: "RJ",
    resumoFato: "Histórico passivo socioambiental decorrente da implantação da Companhia Siderúrgica do Atlântico (TKCSA) no bairro de Santa Cruz, com episódios repetidos de 'chuva de prata' (poluição particulada de grafite e ferro), ações civis públicas do MPF e indenizações a pescadores da Baía de Sepetiba.",
    contextoCivico: "A alemã Thyssenkrupp causou chuva de prata e poluição na zona oeste carioca. Famílias e pescadores de Santa Cruz foram indenizados após anos de luta.",
    marcoLegal: "Lei da Política Nacional do Meio Ambiente 6.938/1981",
    statusProcessual: "Homologado / Execução",
    valorCausaMoedaOrigem: 800000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 4800000000,
    impactoHumanoOuAmbiental: "Contaminação respiratória por particulados pesados e destruição do berçário pesqueiro da Baía de Sepetiba",
    urlOficialCanonica: "https://www.handelsregister.de/",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 10. ALEMANHA - BASF SE / Polo Químico Guaratinguetá e Camaçari
  {
    id: "de-basf-quimica-010",
    paisOrigem: "Alemanha",
    codigoIsoPais: "DE",
    bandeiraPais: "🇩🇪",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "Handelsregister Ludwigshafen / CETESB / INEMA",
    processoOuRegistroNumero: "HRB 3000 Ludwigshafen / Licenças CETESB 22005411",
    dataAto: "2026-04-18",
    empresaEstrangeira: "BASF SE",
    identificadorFiscalEstrangeiro: "Amtsgericht Ludwigshafen HRB 3000",
    empresaBrasileira: "BASF S.A.",
    cnpjBrasileiro: "48.539.407/0001-18",
    setorEconomico: "Química & Defensivos",
    municipioImpactadoIbge: "3518404",
    municipioNome: "Guaratinguetá",
    uf: "SP",
    resumoFato: "Maior complexo químico da América Latina em Guaratinguetá (SP) e polo de acrílicos e defensivos em Camaçari (BA), com histórico de TACs com o Ministério Público do Trabalho e CETESB em decorrência de contaminações crônicas do solo e lençol freático por compostos organoclorados na fábrica desativada de Paulínia.",
    contextoCivico: "A BASF alemã opera o maior polo químico do continente em Guaratinguetá. A empresa assinou acordos bilionários por contaminação histórica em Paulínia.",
    marcoLegal: "CLT art. 157, Lei 6.938/1981 e Acordo Histórico TST Paulínia",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 200000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 1200000000,
    impactoHumanoOuAmbiental: "Intoxicação ocupacional de centenas de trabalhadores e contaminação de aquíferos por resíduos químicos persistentes",
    urlOficialCanonica: "https://www.handelsregister.de/",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 11. ALEMANHA - Bayer AG / Monsanto e Glifosato
  {
    id: "de-bayer-monsanto-011",
    paisOrigem: "Alemanha",
    codigoIsoPais: "DE",
    bandeiraPais: "🇩🇪",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "Handelsregister Köln / ANVISA / MAPA",
    processoOuRegistroNumero: "HRB 48248 Köln / Registros Defensivos MAPA",
    dataAto: "2026-02-28",
    empresaEstrangeira: "Bayer AG",
    identificadorFiscalEstrangeiro: "Amtsgericht Köln HRB 48248",
    empresaBrasileira: "Bayer S.A. / Monsanto do Brasil Ltda",
    cnpjBrasileiro: "18.459.628/0001-15",
    setorEconomico: "Química & Defensivos",
    municipioImpactadoIbge: "3170206",
    municipioNome: "Uberlândia",
    uf: "MG",
    resumoFato: "Operações industriais de produção e distribuição de sementes geneticamente modificadas e formulações à base de glifosato nos polos de Uberlândia (MG) e Belford Roxo (RJ), sob litígios no Judiciário brasileiro e fiscalização sanitária da ANVISA sobre riscos cancerígenos e cobrança de royalties em sementes de soja Intacta.",
    contextoCivico: "A Bayer alemã controla a produção de sementes transgênicas e glifosato no Brasil. Produtores e órgãos de saúde contestam patentes e impactos à saúde.",
    marcoLegal: "Lei de Biossegurança 11.105/2005 e Lei dos Agrotóxicos 7.802/1989",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 3000000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 18000000000,
    impactoHumanoOuAmbiental: "Exposição massiva de populações rurais a defensivos e monopólio tecnológico sobre a cadeia de sementes",
    urlOficialCanonica: "https://www.handelsregister.de/",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 12. FRANÇA - Grupo Casino / Devoir de Vigilance e Carne do Desmatamento
  {
    id: "fr-casino-desmatamento-012",
    paisOrigem: "França",
    codigoIsoPais: "FR",
    bandeiraPais: "🇫🇷",
    categoria: "Litígio Transnacional",
    orgaoJulgadorOuRegulador: "Tribunal judiciaire de Paris",
    processoOuRegistroNumero: "RG 21/05829 (Tribunal de Paris)",
    dataAto: "2024-06-12",
    empresaEstrangeira: "Casino Guichard-Perrachon S.A. (Rallye SA)",
    identificadorFiscalEstrangeiro: "SIREN 552 037 807",
    empresaBrasileira: "Companhia Brasileira de Distribuição (GPA / Pão de Açúcar / Assaí)",
    cnpjBrasileiro: "47.508.411/0001-56",
    setorEconomico: "Agronegócio & Alimentos",
    municipioImpactadoIbge: "1100023",
    municipioNome: "Ariquemes",
    uf: "RO",
    resumoFato: "Ação judicial pioneira em Paris sob a Lei do Dever de Vigilância proposta por povos indígenas (COIAB) e entidades internacionais contra o grupo francês Casino pela comercialização, nos supermercados GPA e Assaí, de carne bovina proveniente de fazendas ligadas ao desmatamento e invasão da Terra Indígena Uru-Eu-Wau-Wau.",
    contextoCivico: "Tribunal de Paris julga o grupo Casino por carne ligada a desmatamento. Indígenas brasileiros denunciaram invasão de terras ancestrais na corte francesa.",
    marcoLegal: "Loi n° 2017-399 relative au devoir de vigilance des sociétés mères",
    statusProcessual: "Em Instrução / Julgamento",
    valorCausaMoedaOrigem: 3200000,
    moedaOrigem: "EUR",
    valorCausaBrl: 19200000,
    impactoHumanoOuAmbiental: "Invasão de territórios protegidos, grilagem de terras públicas na Amazônia e destruição florestal",
    urlOficialCanonica: "https://annuaire-entreprises.data.gouv.fr/entreprise/552037807",
    tipoFonte: "Tribunal Internacional",
  },
  // 13. FRANÇA - BNP Paribas / Financiamento ao Desmatamento e Lavagem
  {
    id: "fr-bnp-paribas-marfrig-013",
    paisOrigem: "França",
    codigoIsoPais: "FR",
    bandeiraPais: "🇫🇷",
    categoria: "Litígio Transnacional",
    orgaoJulgadorOuRegulador: "Tribunal judiciaire de Paris / Parquet National Financier (PNF)",
    processoOuRegistroNumero: "Plainte Devoir de Vigilance / PNF-2023-014",
    dataAto: "2023-02-27",
    empresaEstrangeira: "BNP Paribas S.A.",
    identificadorFiscalEstrangeiro: "SIREN 662 042 449",
    empresaBrasileira: "Cadeia de Financiamento Pecuário (Marfrig)",
    cnpjBrasileiro: "03.853.896/0001-40",
    setorEconomico: "Bancário & Finanças",
    municipioImpactadoIbge: "5107909",
    municipioNome: "Sinop",
    uf: "MT",
    resumoFato: "Litígio e denúncia criminal apresentada em Paris contra o BNP Paribas por falha no plano de vigilância e lavagem socioambiental decorrente da concessão de linhas de crédito bilionárias a grandes frigoríficos sem verificação de desmatamento ilegal e trabalho forçado na cadeia de fornecedores indiretos de gado.",
    contextoCivico: "O maior banco francês foi denunciado por financiar carne ligada a queimadas. A denúncia em Paris aponta lavagem de dinheiro socioambiental de frigoríficos.",
    marcoLegal: "Code de Commerce Art. L. 225-102-4 e Code Pénal Art. 324-1",
    statusProcessual: "Em Instrução / Julgamento",
    valorCausaMoedaOrigem: 50000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 300000000,
    impactoHumanoOuAmbiental: "Financiamento de cadeias pecuárias ligadas a milhares de hectares de desmatamento na Amazônia e Cerrado",
    urlOficialCanonica: "https://annuaire-entreprises.data.gouv.fr/entreprise/662042449",
    tipoFonte: "Tribunal Internacional",
  },
  // 14. FRANÇA - TotalEnergies / Pré-Sal e Margem Equatorial
  {
    id: "fr-totalenergies-presal-014",
    paisOrigem: "França",
    codigoIsoPais: "FR",
    bandeiraPais: "🇫🇷",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANP / IBAMA CGPEG / Registre du Commerce de Paris",
    processoOuRegistroNumero: "SIREN 542 051 180 / Contratos Partilha ANP",
    dataAto: "2026-05-30",
    empresaEstrangeira: "TotalEnergies SE",
    identificadorFiscalEstrangeiro: "SIREN 542 051 180",
    empresaBrasileira: "TotalEnergies EP Brasil Ltda",
    cnpjBrasileiro: "04.517.014/0001-92",
    setorEconomico: "Petróleo & Gás",
    municipioImpactadoIbge: "3304557",
    municipioNome: "Rio de Janeiro (Bacia de Santos)",
    uf: "RJ",
    resumoFato: "Operadora francesa de campos gigantes no pré-sal da Bacia de Santos (Mero com 19,4%, Lapa com 45%, Iara/Atapu) e que protagonizou a tentativa de perfuração exploratória na Foz do Amazonas / Margem Equatorial, indeferida pelo IBAMA por riscos iminentes ao bioma de corais e terras indígenas.",
    contextoCivico: "A francesa TotalEnergies explora o pré-sal e tentou perfurar a foz amazônica. O Ibama barrou perfurações sensíveis perto de recifes de corais.",
    marcoLegal: "Loi de Vigilance francesa e Lei Federal do Petróleo 9.478/1997",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 8000000000,
    moedaOrigem: "USD",
    valorCausaBrl: 44000000000,
    impactoHumanoOuAmbiental: "Pressão sobre ecossistemas marítimos vulneráveis e riscos a povos indígenas da costa norte",
    urlOficialCanonica: "https://annuaire-entreprises.data.gouv.fr/entreprise/542051180",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 15. FRANÇA/LUXEMBURGO - Aperam / Siderurgia Timóteo e Eucalipto no Jequitinhonha
  {
    id: "fr-aperam-jequitinhonha-015",
    paisOrigem: "França",
    codigoIsoPais: "FR",
    bandeiraPais: "🇫🇷",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "Registre de Commerce Luxembourg / IEF-MG / FEAM",
    processoOuRegistroNumero: "RCS Luxembourg B153920 / Outorgas IGAM Jequitinhonha",
    dataAto: "2026-06-15",
    empresaEstrangeira: "Aperam S.A.",
    identificadorFiscalEstrangeiro: "RCS Luxembourg B153920",
    empresaBrasileira: "Aperam South America / Aperam BioEnergia Ltda",
    cnpjBrasileiro: "19.876.424/0001-42",
    setorEconomico: "Siderurgia & Metalurgia",
    municipioImpactadoIbge: "3168705",
    municipioNome: "Timóteo",
    uf: "MG",
    resumoFato: "Usina siderúrgica de aços inoxidáveis em Timóteo (Vale do Aço) abastecida pelo carvão vegetal da Aperam BioEnergia, detentora de 126 mil hectares de monocultivo de eucalipto no Vale do Jequitinhonha (Itamarandiba, Capelinha, Minas Novas, Turmalina, Veredinha), gerando conflitos territoriais com comunidades geraizeiras e quilombolas pelo uso da água e cercamento de terras de uso comum.",
    contextoCivico: "A Aperam planta 126 mil hectares de eucalipto no Vale do Jequitinhonha. Geraizeiros e quilombolas denunciam escassez de água e cercamento de terras comunitárias.",
    marcoLegal: "Lei da Política Florestal de MG 20.922/2013 e Convenção 169 da OIT",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 2500000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 15000000000,
    impactoHumanoOuAmbiental: "Secamento de nascentes em veredas, perda de biodiversidade e restrição ao pastoreio tradicional geraizeiro",
    urlOficialCanonica: "https://www.aperam.com/investors/",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 16. HOLANDA - Rechtbank Rotterdam / Braskem Maceió
  {
    id: "nl-braskem-maceio-016",
    paisOrigem: "Holanda",
    codigoIsoPais: "NL",
    bandeiraPais: "🇳🇱",
    categoria: "Litígio Transnacional",
    orgaoJulgadorOuRegulador: "Rechtbank Rotterdam (Tribunal de Roterdã)",
    processoOuRegistroNumero: "C/10/606412 / HA ZA 20-1014 (ECLI:NL:RBROT:2024:6281)",
    dataAto: "2024-07-17",
    empresaEstrangeira: "Braskem Netherlands Finance B.V. / Braskem Holland B.V.",
    identificadorFiscalEstrangeiro: "KVK 63821094 / KVK 24424905",
    empresaBrasileira: "Braskem S.A.",
    cnpjBrasileiro: "42.150.391/0001-70",
    setorEconomico: "Química & Defensivos",
    municipioImpactadoIbge: "2704302",
    municipioNome: "Maceió",
    uf: "AL",
    resumoFato: "Sentença de responsabilidade civil proferida pelo Tribunal Distrital de Roterdã contra a Braskem e suas subsidiárias financeiras holandesas pelo afundamento geológico de cinco bairros em Maceió (Pinheiro, Mutange, Bebedouro, Bom Parto e Farol) provocado pela extração predatória de sal-gema, forçando a desocupação de 60 mil pessoas e danificando mais de 14 mil imóveis.",
    contextoCivico: "O Tribunal de Roterdã julgou a Braskem culpada pelo afundamento de Maceió. Sessenta mil moradores foram expulsos de cinco bairros após desastre do sal-gema.",
    marcoLegal: "Burgerlijk Wetboek (Código Civil Holandês) e Lei 6.938/1981",
    statusProcessual: "Sentença de Responsabilidade",
    valorCausaMoedaOrigem: 1500000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 9000000000,
    impactoHumanoOuAmbiental: "Desastre urbano sem precedentes: 60 mil desabrigados, apagamento de patrimônio histórico e danos estruturais gravíssimos",
    urlOficialCanonica: "https://uitspraken.rechtspraak.nl/#!/details?id=ECLI:NL:RBROT:2024:6281",
    tipoFonte: "Tribunal Internacional",
  },
  // 17. HOLANDA - Rechtbank Rotterdam / Stichting Rio Doce Claims (Vale / Samarco Europe)
  {
    id: "nl-riodoce-claims-017",
    paisOrigem: "Holanda",
    codigoIsoPais: "NL",
    bandeiraPais: "🇳🇱",
    categoria: "Litígio Transnacional",
    orgaoJulgadorOuRegulador: "Rechtbank Rotterdam",
    processoOuRegistroNumero: "C/10/654890 / HA ZA 23-412 (Rio Doce Claims)",
    dataAto: "2025-03-20",
    empresaEstrangeira: "Samarco Iron Ore Europe B.V.",
    identificadorFiscalEstrangeiro: "KVK 24301540",
    empresaBrasileira: "Vale S.A. / Samarco Mineração S.A.",
    cnpjBrasileiro: "33.592.510/0001-54",
    setorEconomico: "Mineração",
    municipioImpactadoIbge: "3127701",
    municipioNome: "Governador Valadares",
    uf: "MG",
    resumoFato: "Ação coletiva movida pela fundação Stichting Rio Doce Claims no Tribunal de Roterdã representando mais de 77 mil atingidos da bacia do Rio Doce (Minas Gerais e Espírito Santo) contra a subsidiária holandesa da Samarco e a Vale S.A., pleiteando arresto de ativos e indenizações integrais suplementares.",
    contextoCivico: "Fundação holandesa cobra indenização suplementar contra a Vale em tribunal de Roterdã. Ação defende 77 mil atingidos de Minas Gerais e do Espírito Santo.",
    marcoLegal: "Direito Processual Civil Holandês e Responsabilidade por Ato Ilícito",
    statusProcessual: "Em Instrução / Julgamento",
    valorCausaMoedaOrigem: 3000000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 18000000000,
    impactoHumanoOuAmbiental: "Contaminação da calha hídrica do Rio Doce, perda de meios de subsistência e danos à saúde pública",
    urlOficialCanonica: "https://uitspraken.rechtspraak.nl/",
    tipoFonte: "Tribunal Internacional",
  },
  // 18. HOLANDA - Porto de Roterdã / Terminal EMO Minério de Ferro
  {
    id: "nl-porto-roterdam-emo-018",
    paisOrigem: "Holanda",
    codigoIsoPais: "NL",
    bandeiraPais: "🇳🇱",
    categoria: "Hub Logístico & Comércio",
    orgaoJulgadorOuRegulador: "Port of Rotterdam Authority / EMO Terminal Maasvlakte",
    processoOuRegistroNumero: "Terminal Concession Maasvlakte EMO 2026",
    dataAto: "2026-06-30",
    empresaEstrangeira: "Europees Massagoed Overslagbedrijf (EMO) B.V.",
    identificadorFiscalEstrangeiro: "KVK 24108842",
    empresaBrasileira: "Vale S.A. (Carregamento Valemax)",
    cnpjBrasileiro: "33.592.510/0001-54",
    setorEconomico: "Logística Portuária",
    municipioImpactadoIbge: "3131703",
    municipioNome: "Itabira",
    uf: "MG",
    resumoFato: "O Terminal EMO na Maasvlakte (Porto de Roterdã) é o maior porto de transbordo de granéis sólidos da Europa, recebendo navios Valemax (400 mil toneladas) carregados de minério de ferro extraído em Itabira, Carajás e no Quadrilátero Ferrífero para abastecer os altos-fornos alemães do Vale do Ruhr por barcaças fluviais pelo Rio Reno.",
    contextoCivico: "O Porto de Roterdã recebe os maiores navios de minério do mundo. O minério de Minas e Carajás abastece a indústria pesada da Alemanha.",
    marcoLegal: "Port Regulations Rotterdam & Acordos de Logística Transnacional",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 0,
    moedaOrigem: "EUR",
    valorCausaBrl: 0,
    impactoHumanoOuAmbiental: "Transbordo anual de dezenas de milhões de toneladas de minério de ferro, ligando a extração bruta em MG à siderurgia europeia",
    urlOficialCanonica: "https://www.portofrotterdam.com/",
    tipoFonte: "Portal Governamental",
  },
  // 19. HOLANDA - Porto de Roterdã / Terminais de Soja e Regulação EUDR
  {
    id: "nl-porto-roterdam-soja-019",
    paisOrigem: "Holanda",
    codigoIsoPais: "NL",
    bandeiraPais: "🇳🇱",
    categoria: "Hub Logístico & Comércio",
    orgaoJulgadorOuRegulador: "NVWA (Autoridade Holandesa de Segurança Alimentar) / EUDR",
    processoOuRegistroNumero: "Regulamento (UE) 2023/1115 / TRACES-NT Audits",
    dataAto: "2026-01-01",
    empresaEstrangeira: "Viterra B.V. / Bunge Netherlands B.V.",
    identificadorFiscalEstrangeiro: "KVK 24226758",
    empresaBrasileira: "Terminais e Tradings de Exportação de Grãos",
    cnpjBrasileiro: "Isento / Auditoria Portuária",
    setorEconomico: "Agronegócio & Alimentos",
    municipioImpactadoIbge: "5107925",
    municipioNome: "Sorriso",
    uf: "MT",
    resumoFato: "Aplicação do Regulamento Europeu Antidesmatamento (EUDR) sobre os terminais graneleiros do Porto de Roterdã, exigindo georreferenciamento poligonal por GPS e verificação da legalidade fundiária de cada lote de farelo e grão de soja importado do Mato Grosso e Goiás.",
    contextoCivico: "Fiscais em Roterdã exigem mapa por satélite de cada fazenda de soja. Cargas sem prova de desmatamento zero são impedidas de entrar na Europa.",
    marcoLegal: "Regulamento (UE) 2023/1115 (EUDR) art. 3º e 9º",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 0,
    moedaOrigem: "EUR",
    valorCausaBrl: 0,
    impactoHumanoOuAmbiental: "Exigência de rastreabilidade integral para desestimular conversão florestal ilegal no Cerrado e Amazônia",
    urlOficialCanonica: "https://www.nvwa.nl/onderwerpen/eudr",
    tipoFonte: "Agência Reguladora",
  },
  // 20. ITÁLIA - Enel Distribuição São Paulo (Apagões e Multas ANEEL)
  {
    id: "it-enel-sp-concessao-020",
    paisOrigem: "Itália",
    codigoIsoPais: "IT",
    bandeiraPais: "🇮🇹",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANEEL / ALESP / Ministério da Economia e Finanças da Itália (MEF)",
    processoOuRegistroNumero: "Processo ANEEL 48500.005820/2023 / CPI Enel ALESP",
    dataAto: "2026-02-10",
    empresaEstrangeira: "Enel S.p.A. (Roma)",
    identificadorFiscalEstrangeiro: "Partita IVA 00934061003",
    empresaBrasileira: "Enel Distribuição São Paulo (ex-Eletropaulo)",
    cnpjBrasileiro: "61.695.227/0001-93",
    setorEconomico: "Energia Elétrica",
    municipioImpactadoIbge: "3550308",
    municipioNome: "São Paulo",
    uf: "SP",
    resumoFato: "Concessão pública federal de distribuição elétrica na Região Metropolitana de São Paulo (atendendo 7,8 milhões de unidades consumidoras e 18 milhões de habitantes). Alvo de multas da ANEEL superiores a R$ 165 milhões, inquéritos civis do MPSP e processo de caducidade contratual após sucessivos apagões que deixaram milhões de domicílios sem eletricidade por dias.",
    contextoCivico: "A italiana Enel controla a rede de luz de São Paulo. Apagões prolongados levaram a multas da Aneel e pedidos de cancelamento do contrato.",
    marcoLegal: "Lei Federal de Concessões 8.987/1995 e Contrato Concessão ANEEL 162/1998",
    statusProcessual: "Notificação / Processo Administrativo",
    valorCausaMoedaOrigem: 165000000,
    moedaOrigem: "BRL",
    valorCausaBrl: 165000000,
    impactoHumanoOuAmbiental: "Desabastecimento essencial de energia para hospitais, residências e perdas bilionárias no comércio",
    urlOficialCanonica: "https://www.aneel.gov.br/",
    tipoFonte: "Agência Reguladora",
  },
  // 21. ITÁLIA - Enel Distribuição Rio
  {
    id: "it-enel-rio-concessao-021",
    paisOrigem: "Itália",
    codigoIsoPais: "IT",
    bandeiraPais: "🇮🇹",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANEEL / Procon-RJ / MPRJ",
    processoOuRegistroNumero: "Contrato Concessão ANEEL 007/1996 / ACP MPRJ",
    dataAto: "2025-12-15",
    empresaEstrangeira: "Enel S.p.A.",
    identificadorFiscalEstrangeiro: "Partita IVA 00934061003",
    empresaBrasileira: "Enel Distribuição Rio (ex-Ampla)",
    cnpjBrasileiro: "33.050.071/0001-58",
    setorEconomico: "Energia Elétrica",
    municipioImpactadoIbge: "3303302",
    municipioNome: "Niterói",
    uf: "RJ",
    resumoFato: "Concessão de fornecimento de eletricidade em 66 municípios do Estado do Rio de Janeiro (cobrindo 73% do território fluminense com 3 milhões de clientes), com histórico de multas por interrupções reiteradas de serviço na Região dos Lagos, Niterói e São Gonçalo.",
    contextoCivico: "A Enel atende 66 cidades do estado do Rio de Janeiro. A concessionária enfrenta ações judiciais por constantes quedas de fornecimento de energia.",
    marcoLegal: "Lei 9.427/1996 e Código de Defesa do Consumidor (Lei 8.078/1990)",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 95000000,
    moedaOrigem: "BRL",
    valorCausaBrl: 95000000,
    impactoHumanoOuAmbiental: "Prejuízos a serviços públicos e queima massiva de aparelhos domésticos de consumidores fluminenses",
    urlOficialCanonica: "https://www.aneel.gov.br/",
    tipoFonte: "Agência Reguladora",
  },
  // 22. ITÁLIA - Enel Green Power Brasil / Megacomplexos Nordeste
  {
    id: "it-enel-greenpower-nordeste-022",
    paisOrigem: "Itália",
    codigoIsoPais: "IT",
    bandeiraPais: "🇮🇹",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANEEL / SEMARH-PI / INEMA-BA",
    processoOuRegistroNumero: "Outorgas de Geração Centralizada ANEEL 2026",
    dataAto: "2026-04-10",
    empresaEstrangeira: "Enel Green Power S.p.A.",
    identificadorFiscalEstrangeiro: "Partita IVA 10236451000",
    empresaBrasileira: "Enel Green Power Brasil Participações Ltda",
    cnpjBrasileiro: "07.653.640/0001-08",
    setorEconomico: "Energia Elétrica",
    municipioImpactadoIbge: "2210052",
    municipioNome: "São Gonçalo do Gurguéia",
    uf: "PI",
    resumoFato: "Operação do Complexo Solar São Gonçalo (864 MW, maior parque solar da América Latina) e do Complexo Eólico Lagoa dos Ventos (>1 GW em Dom Inocêncio/PI), além de complexos na Bahia, levantando debates sociofundiários sobre contratos de arrendamento de terras de agricultores familiares no semiárido.",
    contextoCivico: "A Enel opera o maior parque solar da América Latina no Piauí. Comunidades do semiárido debatem contratos de arrendamento de terra para energia eólica.",
    marcoLegal: "Resoluções Normativas ANEEL de Energia Renovável e Lei Agrária 4.504/1964",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 1500000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 9000000000,
    impactoHumanoOuAmbiental: "Ocupação extensiva do solo no semiárido e contratos de arrendamento contestados por sindicatos de trabalhadores rurais",
    urlOficialCanonica: "https://www.enelgreenpower.com/pt/paises/america-do-sul/brasil",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 23. ITÁLIA - TIM Brasil e Cabos Submarinos Sparkle
  {
    id: "it-tim-sparkle-telecom-023",
    paisOrigem: "Itália",
    codigoIsoPais: "IT",
    bandeiraPais: "🇮🇹",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANATEL / Golden Power Governo Italiano",
    processoOuRegistroNumero: "Outorga SMP ANATEL / B3 TIMS3",
    dataAto: "2026-05-20",
    empresaEstrangeira: "Telecom Italia S.p.A. / Sparkle S.p.A.",
    identificadorFiscalEstrangeiro: "Partita IVA 00488410010",
    empresaBrasileira: "TIM S.A. (TIM Brasil)",
    cnpjBrasileiro: "02.421.421/0001-11",
    setorEconomico: "Telecomunicações",
    municipioImpactadoIbge: "3304557",
    municipioNome: "Rio de Janeiro",
    uf: "RJ",
    resumoFato: "Segunda maior operadora móvel do país, controlada pelo grupo italiano Telecom Italia. A subsidiária Telecom Italia Sparkle opera infraestrutura estratégica de cabos submarinos (Monet e Seabras-1) com pontos de aterrissagem em Fortaleza, Salvador, RJ e Praia Grande, canalizando tráfego de dados de internet entre a América do Sul e o Hemisfério Norte.",
    contextoCivico: "A Telecom Italia controla a operadora TIM e cabos submarinos transatlânticos. A rede transporta os dados de internet do Brasil para o mundo.",
    marcoLegal: "Lei Geral de Telecomunicações 9.472/1997",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 4000000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 24000000000,
    impactoHumanoOuAmbiental: "Infraestrutura crítica de comunicações digitais e segurança de dados de dezenas de milhões de cidadãos",
    urlOficialCanonica: "https://www.anatel.gov.br/",
    tipoFonte: "Agência Reguladora",
  },
  // 24. ITÁLIA - Cooperação Judiciária Brasil-Itália
  {
    id: "it-cooperacao-judiciaria-024",
    paisOrigem: "Itália",
    codigoIsoPais: "IT",
    bandeiraPais: "🇮🇹",
    categoria: "Cooperação Judiciária",
    orgaoJulgadorOuRegulador: "Ministério da Justiça (Itália) / MPF / PF / STF",
    processoOuRegistroNumero: "Decreto Presidencial nº 862/1993 (Tratado Bilateral de Cooperação)",
    dataAto: "2026-01-15",
    empresaEstrangeira: "Ministero della Giustizia della Repubblica Italiana",
    identificadorFiscalEstrangeiro: "Governo della Repubblica Italiana",
    empresaBrasileira: "Departamento de Recuperação de Ativos (DRCI/MJSP)",
    cnpjBrasileiro: "00.394.494/0001-36",
    setorEconomico: "Bancário & Finanças",
    municipioImpactadoIbge: "5300108",
    municipioNome: "Brasília",
    uf: "DF",
    resumoFato: "Mecanismo bilateral de cooperação judiciária em matéria penal e extradição, permitindo o bloqueio e repatriação de valores obtidos por corrupção e lavagem de capitais mantidos em contas bancárias na Itália, além de pedidos de extradição ativa e passiva entre os dois países.",
    contextoCivico: "Brasil e Itália cooperam para bloquear dinheiro de corrupção e extraditar condenados. O tratado garante cooperação entre tribunais dos dois países.",
    marcoLegal: "Tratado de Cooperação Judiciária em Matéria Penal de 1989 (Decreto 862/1993)",
    statusProcessual: "Precedente Consolidado",
    valorCausaMoedaOrigem: 0,
    moedaOrigem: "EUR",
    valorCausaBrl: 0,
    impactoHumanoOuAmbiental: "Rastreamento transnacional de fluxos financeiros ilícitos e combate à lavagem internacional de capitais",
    urlOficialCanonica: "https://www.justica.gov.br/sua-protecao/lavagem-de-dinheiro/drci",
    tipoFonte: "Portal Governamental",
  },
  // 25. ESPANHA - Santander Brasil / Financiamento do Agronegócio e Crédito Rural
  {
    id: "es-santander-agro-credito-025",
    paisOrigem: "Espanha",
    codigoIsoPais: "ES",
    bandeiraPais: "🇪🇸",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "Banco Central do Brasil (Bacen) / CNMV Espanha",
    processoOuRegistroNumero: "Resolução CMN 4.945/2021 / Registro CNMV Santander",
    dataAto: "2026-04-30",
    empresaEstrangeira: "Banco Santander S.A. (Boadilla del Monte)",
    identificadorFiscalEstrangeiro: "NIF A-39000013",
    empresaBrasileira: "Banco Santander (Brasil) S.A.",
    cnpjBrasileiro: "90.400.888/0001-42",
    setorEconomico: "Bancário & Finanças",
    municipioImpactadoIbge: "3550308",
    municipioNome: "São Paulo",
    uf: "SP",
    resumoFato: "A subsidiária brasileira do Santander responde historicamente por até 30% do lucro global do grupo espanhol. É um dos maiores operadores privados de crédito rural e CPRs, sob escrutínio da Resolução CMN 4.945/2021 para barrar concessão de crédito agrícola a propriedades com embargos por desmatamento lavrados pelo IBAMA ou sobrepostas a terras indígenas.",
    contextoCivico: "O Santander fatura um terço do seu lucro global no Brasil. Regras do Banco Central cobram auditoria contra empréstimos para fazendas desmatadas.",
    marcoLegal: "Resolução CMN nº 4.945/2021 (PRSAC) e Lei da Reforma Bancária 4.595/1964",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 60000000000,
    moedaOrigem: "BRL",
    valorCausaBrl: 60000000000,
    impactoHumanoOuAmbiental: "Alocação massiva de recursos financeiros e risco de fomento indireto a desmatamentos ilegais no Cerrado e Amazônia",
    urlOficialCanonica: "https://www.cnmv.es/",
    tipoFonte: "Agência Reguladora",
  },
  // 26. ESPANHA - Telefónica / Vivo / Concessão e Bens Reversíveis
  {
    id: "es-telefonica-vivo-concessao-026",
    paisOrigem: "Espanha",
    codigoIsoPais: "ES",
    bandeiraPais: "🇪🇸",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANATEL / TCU / CNMV Espanha",
    processoOuRegistroNumero: "Acordo de Migração STFC ANATEL / TCU Processo 013.910/2023-0",
    dataAto: "2025-11-20",
    empresaEstrangeira: "Telefónica S.A. (Madri)",
    identificadorFiscalEstrangeiro: "NIF A-28015865",
    empresaBrasileira: "Telefônica Brasil S.A. (Vivo)",
    cnpjBrasileiro: "02.558.157/0001-62",
    setorEconomico: "Telecomunicações",
    municipioImpactadoIbge: "3550308",
    municipioNome: "São Paulo",
    uf: "SP",
    resumoFato: "Maior operadora de telecomunicações do Brasil em linhas ativas e fibra ótica, a Telefónica concluiu perante a ANATEL e o Tribunal de Contas da União a migração da concessão de telefonia fixa para autorização, comprometendo-se a converter obrigações bilionárias de bens reversíveis em infraestrutura de banda larga para escolas públicas e rodovias federais.",
    contextoCivico: "A espanhola Telefônica é a dona da marca Vivo no Brasil. O acordo com o TCU converte concessões antigas em internet para escolas.",
    marcoLegal: "Lei Geral de Telecomunicações 9.472/1997 e Lei 13.879/2019",
    statusProcessual: "Homologado / Execução",
    valorCausaMoedaOrigem: 4500000000,
    moedaOrigem: "BRL",
    valorCausaBrl: 4500000000,
    impactoHumanoOuAmbiental: "Destinação de patrimônio público de telecomunicações e inclusão digital de comunidades vulneráveis",
    urlOficialCanonica: "https://www.anatel.gov.br/",
    tipoFonte: "Agência Reguladora",
  },
  // 27. ESPANHA - Iberdrola / Neoenergia / Hidrelétrica Belo Monte
  {
    id: "es-neoenergia-belomonte-027",
    paisOrigem: "Espanha",
    codigoIsoPais: "ES",
    bandeiraPais: "🇪🇸",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANEEL / IBAMA / CNMV",
    processoOuRegistroNumero: "Contrato Concessão ANEEL 01/2010 (Norte Energia S.A.)",
    dataAto: "2026-05-10",
    empresaEstrangeira: "Iberdrola S.A. (Bilbau)",
    identificadorFiscalEstrangeiro: "NIF A-48010615",
    empresaBrasileira: "Neoenergia S.A. / Norte Energia S.A.",
    cnpjBrasileiro: "01.083.200/0001-18",
    setorEconomico: "Energia Elétrica",
    municipioImpactadoIbge: "1500602",
    municipioNome: "Altamira",
    uf: "PA",
    resumoFato: "A Iberdrola é controladora da Neoenergia, que detém 10% do consórcio Norte Energia S.A. na UHE Belo Monte (11.233 MW). A usina alterou drasticamente o pulso hidrológico na Volta Grande do Xingu, afetando a pesca, a sobrevivência dos povos indígenas Paquiçamba e Arara da Volta Grande e forçando o IBAMA a rever hidrogramas de consenso.",
    contextoCivico: "A espanhola Iberdrola é sócia na usina hidrelétrica de Belo Monte. A obra desviou o Rio Xingu e prejudicou a pesca indígena.",
    marcoLegal: "Decreto Legislativo 788/2005 e Licença de Operação IBAMA 1317/2015",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 40000000000,
    moedaOrigem: "BRL",
    valorCausaBrl: 40000000000,
    impactoHumanoOuAmbiental: "Desidratação de mais de 100 km do canal natural do Rio Xingu e insegurança alimentar das comunidades ribeirinhas e indígenas",
    urlOficialCanonica: "https://www.ibama.gov.br/",
    tipoFonte: "Agência Reguladora",
  },
  // 28. ESPANHA - Iberdrola / Neoenergia / Distribuidoras Coelba, Celpe, Cosern e Elektro
  {
    id: "es-neoenergia-distribuicao-028",
    paisOrigem: "Espanha",
    codigoIsoPais: "ES",
    bandeiraPais: "🇪🇸",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANEEL / Procons Nordeste",
    processoOuRegistroNumero: "Contratos de Concessão de Distribuição ANEEL",
    dataAto: "2026-03-25",
    empresaEstrangeira: "Iberdrola S.A.",
    identificadorFiscalEstrangeiro: "NIF A-48010615",
    empresaBrasileira: "Neoenergia Coelba / Pernambuco / Cosern / Elektro / Brasília",
    cnpjBrasileiro: "15.139.629/0001-94",
    setorEconomico: "Energia Elétrica",
    municipioImpactadoIbge: "2927408",
    municipioNome: "Salvador",
    uf: "BA",
    resumoFato: "A Neoenergia atende mais de 16 milhões de clientes em dezenas de milhões de domicílios através das distribuidoras Coelba (Bahia), Neoenergia Pernambuco, Cosern (RN), Elektro (SP/MS) e Brasília (DF), sob fiscalização constante da ANEEL por índices de DEC e FEC.",
    contextoCivico: "O grupo da espanhola Iberdrola distribui eletricidade para 16 milhões de brasileiros. As concessionárias atendem grandes capitais e cidades do interior do Nordeste.",
    marcoLegal: "Lei Federal 9.427/1996 e Contratos de Concessão de Distribuição",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 35000000000,
    moedaOrigem: "BRL",
    valorCausaBrl: 35000000000,
    impactoHumanoOuAmbiental: "Continuidade e tarifa do serviço público essencial de energia elétrica para dezenas de milhões de cidadãos",
    urlOficialCanonica: "https://www.neoenergia.com/",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 29. ESPANHA - Repsol Sinopec / Pré-Sal e Bloco BM-C-33
  {
    id: "es-repsol-sinopec-presal-029",
    paisOrigem: "Espanha",
    codigoIsoPais: "ES",
    bandeiraPais: "🇪🇸",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANP / IBAMA CGPEG / CNMV Espanha",
    processoOuRegistroNumero: "Contrato Concessão ANP BM-C-33 Pão de Açúcar",
    dataAto: "2026-06-01",
    empresaEstrangeira: "Repsol S.A. (Madri)",
    identificadorFiscalEstrangeiro: "NIF A-78658820",
    empresaBrasileira: "Repsol Sinopec Brasil S.A.",
    cnpjBrasileiro: "03.007.331/0001-41",
    setorEconomico: "Petróleo & Gás",
    municipioImpactadoIbge: "3302403",
    municipioNome: "Macaé",
    uf: "RJ",
    resumoFato: "Joint-venture da petrolífera espanhola Repsol com investimentos no campo de Sapinhoá (Bacia de Santos) e no megaprojeto BM-C-33 (Pão de Açúcar na Bacia de Campos), com investimento bilionário para produção e escoamento offshore de 16 milhões de m³ de gás natural por dia até o terminal de Cabiúnas em Macaé.",
    contextoCivico: "A espanhola Repsol investe bilhões em gás natural no litoral do Rio. A produção submarina abastece a indústria nacional e termelétricas.",
    marcoLegal: "Lei do Petróleo 9.478/1997 e Lei do Gás 14.134/2021",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 9000000000,
    moedaOrigem: "USD",
    valorCausaBrl: 49500000000,
    impactoHumanoOuAmbiental: "Emissões industriais offshore e infraestrutura de gasoduto de alta pressão no leito oceânico",
    urlOficialCanonica: "https://www.repsolsinopec.com.br/",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 30. ESPANHA - Bolsa de Madri BME Latibex
  {
    id: "es-bme-latibex-brasil-030",
    paisOrigem: "Espanha",
    codigoIsoPais: "ES",
    bandeiraPais: "🇪🇸",
    categoria: "Hub Logístico & Comércio",
    orgaoJulgadorOuRegulador: "BME Latibex / CNMV Espanha / B3",
    processoOuRegistroNumero: "Latibex Tickers: XPBRA, XPBR, XVALO, XBBDC",
    dataAto: "2026-07-15",
    empresaEstrangeira: "Bolsas y Mercados Españoles (BME)",
    identificadorFiscalEstrangeiro: "NIF A-83244243",
    empresaBrasileira: "Petrobras, Vale, Bradesco e Gerdau",
    cnpjBrasileiro: "Isento / Mercado Financeiro",
    setorEconomico: "Bancário & Finanças",
    municipioImpactadoIbge: "0000000",
    municipioNome: "Internacional / Mercado Europeu",
    uf: "BR",
    resumoFato: "O Latibex é o único mercado internacional de valores mobiliários dedicado a títulos latino-americanos cotados em Euros, permitindo que investidores da União Europeia comprem e negociem diretamente ações de gigantes brasileiras (Petrobras, Vale, Gerdau) sem conversão para Dólares americanos.",
    contextoCivico: "A Bolsa de Madri negocia ações da Petrobras e da Vale em Euros. O sistema permite investimentos europeus diretos nas maiores empresas brasileiras.",
    marcoLegal: "Ley del Mercado de Valores española e Diretiva MiFID II (UE)",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 0,
    moedaOrigem: "EUR",
    valorCausaBrl: 0,
    impactoHumanoOuAmbiental: "Fluxos de capital de investimento externo europeu sobre empresas com grandes passivos socioambientais no Brasil",
    urlOficialCanonica: "https://www.latibex.com/",
    tipoFonte: "Portal Governamental",
  },
  // 31. PORTUGAL - EDP Brasil / Distribuição em São Paulo e Espírito Santo
  {
    id: "pt-edp-concessoes-brasil-031",
    paisOrigem: "Portugal",
    codigoIsoPais: "PT",
    bandeiraPais: "🇵🇹",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANEEL / CMVM Portugal / B3",
    processoOuRegistroNumero: "Contratos de Concessão ANEEL 164/1998 e 002/1995",
    dataAto: "2026-03-10",
    empresaEstrangeira: "EDP - Energias de Portugal S.A. (Lisboa)",
    identificadorFiscalEstrangeiro: "NIPC 500697256",
    empresaBrasileira: "EDP São Paulo / EDP Espírito Santo (EDP Brasil)",
    cnpjBrasileiro: "03.853.808/0001-40",
    setorEconomico: "Energia Elétrica",
    municipioImpactadoIbge: "3518800",
    municipioNome: "Guarulhos",
    uf: "SP",
    resumoFato: "A matriz portuguesa EDP fechou o capital da EDP Brasil na B3 em 2023. Controla a concessão elétrica no Alto Tietê e Vale do Paraíba (EDP SP, atendendo 2 milhões de clientes em cidades como Guarulhos e São José dos Campos) e no Espírito Santo (EDP ES, atendendo 70 municípios e 1,7 milhão de clientes), além de hidrelétricas em TO, ES e AP.",
    contextoCivico: "A portuguesa EDP comanda a luz no Espírito Santo e Alto Tietê. A empresa atende quase quatro milhões de residências brasileiras.",
    marcoLegal: "Lei Federal de Concessões 8.987/1995 e Lei do Setor Elétrico 9.427/1996",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 15000000000,
    moedaOrigem: "BRL",
    valorCausaBrl: 15000000000,
    impactoHumanoOuAmbiental: "Fornecimento de energia essencial e remuneração regulatória de ativos de rede pública",
    urlOficialCanonica: "https://www.edp.com.br/",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 32. PORTUGAL - Galp Energia / Petrogal no Pré-Sal (Campo de Tupi e Bacalhau)
  {
    id: "pt-galp-petrogal-presal-032",
    paisOrigem: "Portugal",
    codigoIsoPais: "PT",
    bandeiraPais: "🇵🇹",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "ANP / IBAMA CGPEG / CMVM Portugal",
    processoOuRegistroNumero: "Contrato Concessão ANP Tupi / Bacalhau",
    dataAto: "2026-05-18",
    empresaEstrangeira: "Galp Energia SGPS S.A.",
    identificadorFiscalEstrangeiro: "NIPC 504499777",
    empresaBrasileira: "Petrogal Brasil S.A.",
    cnpjBrasileiro: "03.515.271/0001-60",
    setorEconomico: "Petróleo & Gás",
    municipioImpactadoIbge: "3304557",
    municipioNome: "Rio de Janeiro (Bacia de Santos)",
    uf: "RJ",
    resumoFato: "A Petrogal Brasil é a 4ª maior produtora de petróleo e gás do país. Detém 10% no gigantesco Campo de Tupi (maior produtor do país) e 20% no campo de Bacalhau (Carcará) na Bacia de Santos, operado em parceria com a Equinor e ExxonMobil.",
    contextoCivico: "A petrolífera portuguesa Galp é a quarta maior produtora de óleo no Brasil. A empresa extrai petróleo e gás nos principais campos do pré-sal.",
    marcoLegal: "Lei 9.478/1997 e Resoluções Técnicas ANP",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 5000000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 30000000000,
    impactoHumanoOuAmbiental: "Emissões de gases com efeito de estufa e exploração em ecossistemas marinhos profundos",
    urlOficialCanonica: "https://www.galp.com/corp/pt/",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 33. PORTUGAL - Cooperação Judiciária DCIAP/PJ & MPF/PF
  {
    id: "pt-cooperacao-dciap-mpf-033",
    paisOrigem: "Portugal",
    codigoIsoPais: "PT",
    bandeiraPais: "🇵🇹",
    categoria: "Cooperação Judiciária",
    orgaoJulgadorOuRegulador: "DCIAP / Polícia Judiciária (Portugal) / MPF / PF",
    processoOuRegistroNumero: "Decreto Presidencial nº 1.325/1994 / Convenção CPLP",
    dataAto: "2026-02-14",
    empresaEstrangeira: "Departamento Central de Investigação e Ação Penal (DCIAP)",
    identificadorFiscalEstrangeiro: "Ministério Público da República Portuguesa",
    empresaBrasileira: "Ministério Público Federal / Polícia Federal",
    cnpjBrasileiro: "00.394.494/0001-36",
    setorEconomico: "Bancário & Finanças",
    municipioImpactadoIbge: "5300108",
    municipioNome: "Brasília",
    uf: "DF",
    resumoFato: "Acordo bilateral e multilateral da CPLP que fundamenta o rastreamento, congelamento e confisco de patrimônio ilícito mantido em Lisboa, Cascais, Porto e Algarve, originário de corrupção, fraudes financeiras e crimes ambientais investigados no Brasil.",
    contextoCivico: "Promotores do Brasil e Portugal rastreiam imóveis de luxo e contas bancárias. A cooperação bloqueia bens comprados na Europa com dinheiro ilícito brasileiro.",
    marcoLegal: "Tratado de Extradição (Decreto 1.325/1994) e Convenção de Auxílio Judiciário CPLP",
    statusProcessual: "Precedente Consolidado",
    valorCausaMoedaOrigem: 250000000,
    moedaOrigem: "EUR",
    valorCausaBrl: 1500000000,
    impactoHumanoOuAmbiental: "Recuperação de ativos desviados dos cofres públicos brasileiros e combate à lavagem imobiliária em praça europeia",
    urlOficialCanonica: "https://dciap.ministeriopublico.pt/",
    tipoFonte: "Portal Governamental",
  },
  // 34. UNIÃO EUROPEIA - Regulamento Antidesmatamento (EUDR)
  {
    id: "eu-eudr-regulamento-034",
    paisOrigem: "União Europeia",
    codigoIsoPais: "EU",
    bandeiraPais: "🇪🇺",
    categoria: "Devida Diligência & Regulação",
    orgaoJulgadorOuRegulador: "Comissão Europeia / Parlamento Europeu / TRACES-NT",
    processoOuRegistroNumero: "Regulamento (UE) 2023/1115 (EUDR)",
    dataAto: "2023-06-09",
    empresaEstrangeira: "União Europeia (27 Estados-Membros)",
    identificadorFiscalEstrangeiro: "Jornal Oficial da UE L 150",
    empresaBrasileira: "Cadeias Exportadoras (Soja, Carne, Café, Madeira, Borracha, Cacau)",
    cnpjBrasileiro: "Isento / Marco Regulatório Comunitário",
    setorEconomico: "Regulação Ambiental",
    municipioImpactadoIbge: "0000000",
    municipioNome: "Nacional / Todos os Biomas",
    uf: "BR",
    resumoFato: "Marco regulatório da UE que proíbe a colocação e exportação no mercado europeu de commodities produzidas em áreas desmatadas após 31 de dezembro de 2020. Impõe auditoria prévia obrigatória com polígonos georreferenciados por satélite (geofencing) e emissão de Declaração de Devida Diligência no sistema TRACES-NT.",
    contextoCivico: "A lei europeia proíbe compra de produtos de áreas desmatadas após 2020. Exportadores de carne, soja e café devem enviar coordenadas por satélite.",
    marcoLegal: "Regulamento (UE) 2023/1115",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 0,
    moedaOrigem: "EUR",
    valorCausaBrl: 0,
    impactoHumanoOuAmbiental: "Desestímulo ao desmatamento legal e ilegal nos biomas Amazônia, Cerrado e Mata Atlântica",
    urlOficialCanonica: "https://eur-lex.europa.eu/legal-content/PT/TXT/?uri=CELEX:32023R1115",
    tipoFonte: "Diário Oficial da UE",
  },
  // 35. UNIÃO EUROPEIA - Diretiva CSDDD de Devida Diligência Corporativa
  {
    id: "eu-csddd-diretiva-035",
    paisOrigem: "União Europeia",
    codigoIsoPais: "EU",
    bandeiraPais: "🇪🇺",
    categoria: "Devida Diligência & Regulação",
    orgaoJulgadorOuRegulador: "Comissão Europeia / Conselho da União Europeia",
    processoOuRegistroNumero: "Diretiva (UE) 2024/1760 (CSDDD)",
    dataAto: "2024-06-13",
    empresaEstrangeira: "Multinacionais da União Europeia com mais de 1.000 funcionários",
    identificadorFiscalEstrangeiro: "Jornal Oficial da UE L 2024/1760",
    empresaBrasileira: "Subsidiárias e Fornecedores no Brasil",
    cnpjBrasileiro: "Isento / Diretiva Comunitária",
    setorEconomico: "Regulação Ambiental",
    municipioImpactadoIbge: "0000000",
    municipioNome: "Nacional / Relações Transnacionais",
    uf: "BR",
    resumoFato: "Diretiva de Devida Diligência sobre Sustentabilidade Corporativa que estabelece a responsabilidade civil objetiva de multinacionais europeias perante cortes dos Estados-Membros por violações de direitos humanos e danos socioambientais causados ao longo de toda a sua cadeia de valor global no Brasil.",
    contextoCivico: "Nova diretiva europeia responsabiliza matrizes por crimes de subsidiárias brasileiras. Vítimas podem acionar tribunais da Europa com pedidos de indenização.",
    marcoLegal: "Diretiva (UE) 2024/1760",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 0,
    moedaOrigem: "EUR",
    valorCausaBrl: 0,
    impactoHumanoOuAmbiental: "Abertura de acesso direto à justiça internacional para comunidades brasileiras atingidas por corporações europeias",
    urlOficialCanonica: "https://eur-lex.europa.eu/legal-content/PT/TXT/?uri=CELEX:32024L1760",
    tipoFonte: "Diário Oficial da UE",
  },
  // 36. SUÍÇA - Glencore International AG / Mineração e Leniência
  {
    id: "ch-glencore-commodities-036",
    paisOrigem: "Suíça",
    codigoIsoPais: "CH",
    bandeiraPais: "🇨🇭",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "Zefix Handelsregister Zug / MPF / CGU",
    processoOuRegistroNumero: "UID CHE-106.909.529 / Acordo Leniência Lava Jato",
    dataAto: "2024-05-15",
    empresaEstrangeira: "Glencore International AG (Baar)",
    identificadorFiscalEstrangeiro: "UID CHE-106.909.529",
    empresaBrasileira: "Glencore Brasil Ltda",
    cnpjBrasileiro: "02.502.937/0001-09",
    setorEconomico: "Mineração",
    municipioImpactadoIbge: "3550308",
    municipioNome: "São Paulo",
    uf: "SP",
    resumoFato: "Maior trading diversificada de minérios e commodities do planeta, sediada no cantão suíço de Zug. Firmou acordo de leniência global e com autoridades brasileiras reconhecendo pagamento de propinas no comércio de óleo bunker da Petrobras e comercializa grandes volumes de cobre e zinco extraídos no Brasil.",
    contextoCivico: "A suíça Glencore é a maior trading de minérios do mundo. A multinacional confessou propinas no abastecimento marítimo da Petrobras.",
    marcoLegal: "Artigos 964a a 964c do Código das Obrigações Suíço e Lei Anticorrupção 12.846/2013",
    statusProcessual: "Homologado / Execução",
    valorCausaMoedaOrigem: 1100000000,
    moedaOrigem: "USD",
    valorCausaBrl: 6050000000,
    impactoHumanoOuAmbiental: "Danos ao erário público e distorção concorrencial nos mercados de combustíveis e minerais",
    urlOficialCanonica: "https://www.zefix.ch/en/search/entity/list/firm/113101",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 37. SUÍÇA - Trafigura e Vitol / Tradings de Energia
  {
    id: "ch-trafigura-vitol-037",
    paisOrigem: "Suíça",
    codigoIsoPais: "CH",
    bandeiraPais: "🇨🇭",
    categoria: "Hub Logístico & Comércio",
    orgaoJulgadorOuRegulador: "Zefix Genebra / MPF / Justiça Federal",
    processoOuRegistroNumero: "UID CHE-480.993.428 / Ação Civil Pública MPF",
    dataAto: "2024-08-20",
    empresaEstrangeira: "Trafigura Group Pte / Vitol Holding B.V. (Genebra)",
    identificadorFiscalEstrangeiro: "UID CHE-480.993.428",
    empresaBrasileira: "Trafigura do Brasil Consultoria Ltda",
    cnpjBrasileiro: "04.425.864/0001-44",
    setorEconomico: "Petróleo & Gás",
    municipioImpactadoIbge: "3304557",
    municipioNome: "Rio de Janeiro",
    uf: "RJ",
    resumoFato: "Gigantes globais de comercialização de petróleo e derivados sediadas em Genebra, que celebraram acordos de leniência por operações ilícitas de compra e venda de derivados de petróleo com a diretoria de Abastecimento da Petrobras e atuam nos principais portos marítimos do país.",
    contextoCivico: "Tradings de Genebra negociam derivados de petróleo em portos brasileiros. Gigantes suíças assinaram acordos de leniência por desvios em combustíveis.",
    marcoLegal: "Lei Anticorrupção 12.846/2013 e Legislação de Transparência Suíça",
    statusProcessual: "Homologado / Execução",
    valorCausaMoedaOrigem: 150000000,
    moedaOrigem: "USD",
    valorCausaBrl: 825000000,
    impactoHumanoOuAmbiental: "Prejuízos financeiros vultosos à estatal brasileira e opacidade em cadeias globais de combustíveis",
    urlOficialCanonica: "https://www.zefix.ch/",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 38. LUXEMBURGO - ArcelorMittal / Siderurgia e Barragem Serra Azul em Itatiaiuçu
  {
    id: "lu-arcelormittal-itatiaiucu-038",
    paisOrigem: "Luxemburgo",
    codigoIsoPais: "LU",
    bandeiraPais: "🇱🇺",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "RCS Luxembourg B42180 / ANM SIGBM / MPMG",
    processoOuRegistroNumero: "RCS Luxembourg B42180 / ANM Barragem Serra Azul",
    dataAto: "2026-04-12",
    empresaEstrangeira: "ArcelorMittal S.A. (Luxemburgo)",
    identificadorFiscalEstrangeiro: "RCS Luxembourg B42180",
    empresaBrasileira: "ArcelorMittal Brasil S.A.",
    cnpjBrasileiro: "17.469.701/0001-77",
    setorEconomico: "Siderurgia & Metalurgia",
    municipioImpactadoIbge: "3133709",
    municipioNome: "Itatiaiuçu",
    uf: "MG",
    resumoFato: "Maior siderúrgica do mundo, a ArcelorMittal opera usinas em Tubarão/Serra (ES), João Monlevade (MG) e a Mina de Serra Azul em Itatiaiuçu (MG), cuja barragem de rejeitos entrou em Nível 3 de Emergência (risco iminente de colapso), forçando a evacuação forçada da comunidade de Pinheiros e a construção de muro de contenção a jusante.",
    contextoCivico: "A ArcelorMittal luxemburguesa opera minas e usinas de aço em Minas. Em Itatiaiuçu, barragem em risco de colapso evacuou moradores de Pinheiros.",
    marcoLegal: "Política Nacional de Segurança de Barragens (Lei 12.334/2010)",
    statusProcessual: "Em Vigor / Fiscalização",
    valorCausaMoedaOrigem: 450000000,
    moedaOrigem: "BRL",
    valorCausaBrl: 450000000,
    impactoHumanoOuAmbiental: "Deslocamento compulsório de famílias sob risco de rompimento e poluição hídrica na bacia do Rio Paraopeba",
    urlOficialCanonica: "https://www.lbr.lu/",
    tipoFonte: "Registro Comercial Oficial",
  },
  // 39. NORUEGA - Norsk Hydro / Refinaria Alunorte e Bauxita em Barcarena e Paragominas
  {
    id: "no-norsk-hydro-alunorte-039",
    paisOrigem: "Noruega",
    codigoIsoPais: "NO",
    bandeiraPais: "🇳🇴",
    categoria: "Operação Corporativa & Concessão",
    orgaoJulgadorOuRegulador: "Brønnøysundregistrene / MPF-PA / SEMAS-PA",
    processoOuRegistroNumero: "Org. nr. 914778271 / TAC Hydro Barcarena 2018",
    dataAto: "2026-05-25",
    empresaEstrangeira: "Norsk Hydro ASA (Oslo)",
    identificadorFiscalEstrangeiro: "Organisasjonsnummer 914778271",
    empresaBrasileira: "Alunorte - Alumina do Norte do Brasil S.A. / Mineração Paragominas S.A.",
    cnpjBrasileiro: "04.538.718/0001-09",
    setorEconomico: "Siderurgia & Metalurgia",
    municipioImpactadoIbge: "1501303",
    municipioNome: "Barcarena",
    uf: "PA",
    resumoFato: "Operação da maior refinaria de alumina do mundo (Alunorte em Barcarena) conectada por mineroduto de 244 km à mina de bauxita em Paragominas. Protagonizou o vazamento de efluentes de bauxita por duto clandestino em fevereiro de 2018, resultando em TAC firmado com MPF e MPPA para reforma de bacias e indenização a comunidades ribeirinhas.",
    contextoCivico: "A norueguesa Norsk Hydro comanda a maior refinaria de alumina do mundo. Vazamento tóxico em Barcarena gerou TAC histórico com o Ministério Público.",
    marcoLegal: "Termo de Ajustamento de Conduta (TAC Barcarena 2018) e Lei 6.938/1981",
    statusProcessual: "Homologado / Execução",
    valorCausaMoedaOrigem: 1100000000,
    moedaOrigem: "BRL",
    valorCausaBrl: 1100000000,
    impactoHumanoOuAmbiental: "Contaminação de igarapés por metais pesados e prejuízos crônicos a comunidades tradicionais da Amazônia paraense",
    urlOficialCanonica: "https://www.hydro.com/pt-BR/",
    tipoFonte: "Registro Comercial Oficial",
  },
];

export function gerarAcervoEuropa(): void {
  // Garantir diretórios
  if (!fs.existsSync(DIR_DATA_INTERNACIONAL)) {
    fs.mkdirSync(DIR_DATA_INTERNACIONAL, { recursive: true });
  }
  if (!fs.existsSync(DIR_DATA_EUROPA)) {
    fs.mkdirSync(DIR_DATA_EUROPA, { recursive: true });
  }

  // Compactar dados usando o algoritmo do repositório (compactar.ts)
  const compactado = compactar(
    ACERVO_EUROPA_TRANSNACIONAL as unknown as Record<string, unknown>[]
  );

  const conteudoJson = JSON.stringify(compactado, null, 2);

  const caminhoInternacional = path.join(
    DIR_DATA_INTERNACIONAL,
    "europa-transnacional.compact.json"
  );
  const caminhoEuropa = path.join(
    DIR_DATA_EUROPA,
    "europa-transnacional.compact.json"
  );

  fs.writeFileSync(caminhoInternacional, conteudoJson, "utf8");
  fs.writeFileSync(caminhoEuropa, conteudoJson, "utf8");

  console.log(`✅ Acervo Europa gerado com sucesso!`);
  console.log(`- Registros: ${ACERVO_EUROPA_TRANSNACIONAL.length}`);
  console.log(`- Arquivo 1: ${caminhoInternacional} (${Buffer.byteLength(conteudoJson, "utf8")} bytes)`);
  console.log(`- Arquivo 2: ${caminhoEuropa} (${Buffer.byteLength(conteudoJson, "utf8")} bytes)`);
}

// Executar se chamado diretamente
if (process.argv[1] && process.argv[1].endsWith("gerar-europa-acervo.mts")) {
  gerarAcervoEuropa();
}
