import json
import os
from datetime import datetime

# Carrega dados existentes
caminho = os.path.join(os.path.dirname(__file__), "..", "apps", "web", "public", "data", "biblioteca-desastres.json")
if os.path.exists(caminho):
    with open(caminho, encoding="utf-8") as f:
        dados_existentes = json.load(f)
    itens_existentes = dados_existentes.get("itens", [])
else:
    itens_existentes = []

# Novos itens: regiões MG, casos nacionais, ações coletivas
novos_itens = [
    # ─── QUADRILÁTERO FERRÍFERO ───
    {"id": "qf-001", "desastre": "nacional", "bacia": "velhas", "titulo": "Mina Apolo vs. Parque Serra do Gandarela — Conflito de Mineração", "data": "2025", "tipo": "Conflito socioambiental", "orgao": "SEMAD / FEAM / IEF", "esfera": "estadual", "uf": "MG", "tags": ["quadrilatero-ferrifero", "mineracao", "parque", "gandarela", "conflito"], "resumo": "Conflito entre a Mina Apolo (Vale) e o Parque Estadual da Serra do Gandarela. Operação Rejeito (PF, 2025) investigou impactos ambientais na região.", "url": "https://www.gov.br/mg/pt-br/secretarias/secretaria-de-estado-de-meio-ambiente-e-desenvolvimento-sustentavel", "fonteId": "quadrilatero-ferrifero", "regiao_mg": "Quadrilátero Ferrífero", "classificavel": True},
    {"id": "qf-002", "desastre": "nacional", "bacia": "velhas", "titulo": "Operação Rejeito — Polícia Federal (2025)", "data": "2025", "tipo": "Operação policial", "orgao": "Polícia Federal", "esfera": "federal", "uf": "MG", "tags": ["quadrilatero-ferrifero", "operacao-rejeito", "pf", "mineracao-ilegal"], "resumo": "Operação da PF para combater mineração ilegal no Quadrilátero Ferrífero, com foco em desmatamento e contaminação hídrica.", "url": "https://www.gov.br/pf/pt-br/assuntos/noticias", "fonteId": "quadrilatero-ferrifero", "regiao_mg": "Quadrilátero Ferrífero", "classificavel": True},
    {"id": "qf-003", "desastre": "nacional", "bacia": "velhas", "titulo": "Serra do Rola-Moça — Proteção Ambiental vs. Mineração", "data": "2024", "tipo": "Litígio ambiental", "orgao": "ICMBio / IBAMA", "esfera": "federal", "uf": "MG", "tags": ["quadrilatero-ferrifero", "serra-do-rola-moca", "icmbio", "protecao-ambiental"], "resumo": "Conflito entre atividade mineradora e a proteção da Serra do Rola-Moça no Vale do Aço. ICMBio e IBAMA investigam impactos.", "url": "https://www.gov.br/icmbio/pt-br/", "fonteId": "quadrilatero-ferrifero", "regiao_mg": "Quadrilátero Ferrífero", "classificavel": True},

    # ─── VALE DO AÇO ───
    {"id": "va-001", "desastre": "nacional", "bacia": "velhas", "titulo": "Impactos Acumulados da Mineração no Vale do Aço", "data": "2024", "tipo": "Relatório técnico", "orgao": "FEAM / SEMAD", "esfera": "estadual", "uf": "MG", "tags": ["vale-do-aco", "contaminacao", "metais-pesados", "microplasticos"], "resumo": "Relatório sobre contaminação por metais pesados e microplásticos no Vale do Aço, região com impactos acumulados do rompimento de Fundão.", "url": "https://www.gov.br/mg/pt-br/secretarias/secretaria-de-estado-de-meio-ambiente", "fonteId": "quadrilatero-ferrifero", "regiao_mg": "Vale do Aço", "classificavel": True},
    {"id": "va-002", "desastre": "nacional", "bacia": "velhas", "titulo": "Acompanhamento da Desindustrialização e Danos Ambientais", "data": "2025", "tipo": "Estudo de impacto", "orgao": "CPRM / CODEMIG", "esfera": "estadual", "uf": "MG", "tags": ["vale-do-aco", "desindustrializacao", "cprm", "codedmig"], "resumo": "Estudo da CPRM e CODEMIG sobre impactos ambientais acumulados da mineração na região do Vale do Aço.", "url": "https://www.gov.br/cprm/pt-br/", "fonteId": "quadrilatero-ferrifero", "regiao_mg": "Vale do Aço", "classificavel": True},

    # ─── SÃO FRANCISCO (QUILÔBLOCOS) ───
    {"id": "sf-001", "desastre": "nacional", "bacia": "sao_francisco", "titulo": "Conflitos Quilombola vs. Agronegócio no Alto São Francisco", "data": "2025", "tipo": "Conflito socioambiental", "orgao": "IBAMA / INCRA / IEF", "esfera": "federal", "uf": "MG", "tags": ["sao-francisco", "quilombolas", "conflito-agrario", "uc"], "resumo": "Conflitos entre comunidades quilombolas e vazanteiros com agronegócio e unidades de conservação no Alto São Francisco (Parque Mata Seca, Verde Grande).", "url": "https://www.gov.br/ibama/pt-br/assuntos/terra-socioambiental/quilombolas", "fonteId": "casos-nacionais-crimes", "regiao_mg": "São Francisco", "classificavel": True},

    # ─── RIO DAS VELHAS ───
    {"id": "rv-001", "desastre": "nacional", "bacia": "velhas", "titulo": "Poluição Crônica por Esgoto no Rio das Velhas", "data": "2025", "tipo": "Relatório técnico", "orgao": "IGAM / COPAM / Copasa", "esfera": "estadual", "uf": "MG", "tags": ["rio-das-velhas", "esgoto", "poluicao", "classe-4"], "resumo": "Poluição crônica por esgoto no Rio das Velhas com Classe 4 de qualidade. 30 km entre Sabará e Ribeirão da Mata afetados. Mineração vs. mananciais.", "url": "https://www.gov.br/mg/pt-br/secretarias/secretaria-de-estado-de-meio-ambiente", "fonteId": "casos-nacionais-crimes", "regiao_mg": "Rio das Velhas", "classificavel": True},
    {"id": "rv-002", "desastre": "nacional", "bacia": "velhas", "titulo": "Conflito Hídrico no Alto Pará", "data": "2024", "tipo": "Conflito hídrico", "orgao": "IGAM / CBH-SF2 / FEAM", "esfera": "estadual", "uf": "MG", "tags": ["alto-para", "conflito-hidrico", "outorga", "mineracao"], "resumo": "Conflito hídrico no Rio Pará com outorga superior a 30% em trechos. Mineração vs. abastecimento humano.", "url": "https://www.gov.br/mg/pt-br/secretarias/secretaria-de-estado-de-meio-ambiente", "fonteId": "casos-nacionais-crimes", "regiao_mg": "Alto Pará", "classificavel": True},

    # ─── VERDE GRANDE ───
    {"id": "vg-001", "desastre": "nacional", "bacia": "verde_grande", "titulo": "Conflito Hídrico no Rio Verde Grande — Garimpo Ilegal", "data": "2025", "tipo": "Conflito hídrico", "orgao": "IGAM / FEAM / IBAMA / PF", "esfera": "federal", "uf": "MG", "tags": ["verde-grande", "garimpo", "conflito-hidrico", "outorga"], "resumo": "Conflito hídrico no Rio Verde Grande com outorga superior a 126%. Garimpo ilegal na região. IGAM, FEAM, IBAMA e PF investigam.", "url": "https://www.gov.br/ibama/pt-br/assuntos/meio-ambiente/areas-protegidas", "fonteId": "casos-nacionais-crimes", "regiao_mg": "Verde Grande", "classificavel": True},

    # ─── NORTE DE MG (GARIMPO) ───
    {"id": "nm-001", "desastre": "nacional", "bacia": "sao_francisco", "titulo": "Operação Nascentes Livres (2026) — Garimpo em Vargem Grande", "data": "2026", "tipo": "Operação policial", "orgao": "ICMBio / PF / IBAMA / SEMAD", "esfera": "federal", "uf": "MG", "tags": ["norte-de-mg", "operacao-nascentes-livres", "garimpo", "quartzo", "vargem-grande"], "resumo": "Operação contra garimpo de quartzo em Vargem Grande do Rio Pardo, no Norte de MG. ICMBio e PF atuam com SEMAD.", "url": "https://www.gov.br/icmbio/pt-br/", "fonteId": "casos-nacionais-crimes", "regiao_mg": "Norte (garimpo ilegal)", "classificavel": True},

    # ─── SUL DE MG (GARIMPO) ───
    {"id": "sm-001", "desastre": "nacional", "bacia": "geral", "titulo": "Operação Protetor dos Biomas (2026) — Garimpo Ilegal", "data": "2026", "tipo": "Operação policial", "orgao": "PF / PMMG / IBAMA / ANM", "esfera": "federal", "uf": "MG", "tags": ["sul-de-mg", "operacao-protetor-biomas", "garimpo-clandestino", "9-municipios"], "resumo": "Operação contra garimpo clandestino em 9 municípios do Sul de MG, nas bacias do Mortes e Grande. PF, PMMG, IBAMA e ANM coordenam.", "url": "https://www.gov.br/pf/pt-br/assuntos/noticias", "fonteId": "casos-nacionais-crimes", "regiao_mg": "Sul (garimpo ilegal)", "classificavel": True},

    # ─── MUCURI ───
    {"id": "mu-001", "desastre": "nacional", "bacia": "mucuri", "titulo": "Conflito Quilombola PCH Mucuri — Comunidade Marques vs. Queiroz Galvão", "data": "2024", "tipo": "Litígio socioambiental", "orgao": "FEAM / IBAMA / INCRA / MPF", "esfera": "federal", "uf": "MG", "tags": ["mucuri", "quilombola", "pch", "conflito"], "resumo": "Conflito entre a Comunidade Quilombola Marques e a empresa Queiroz Galvão pela implantação de PCH no Rio Mucuri, na fronteira MG/BA.", "url": "https://www.gov.br/feam/pt-br/", "fonteId": "casos-nacionais-crimes", "regiao_mg": "Mucuri", "classificavel": True},

    # ─── PARACATU / URUCUIA ───
    {"id": "pa-001", "desastre": "nacional", "bacia": "paracatu", "titulo": "Conflito Hídrico no Noroeste — Paracatu/Urucuia", "data": "2025", "tipo": "Conflito hídrico", "orgao": "IGAM / CBH-SF7 / CBH-SF8 / CPRM", "esfera": "estadual", "uf": "MG", "tags": ["noroeste", "paracatu", "uruculia", "outorga", "agronegocio"], "resumo": "Maior volume de água outorgado no estado (~140 m³/s). Conflito entre agronegócio e segurança hídrica no Noroeste de MG.", "url": "https://www.gov.br/mg/pt-br/secretarias/secretaria-de-estado-de-meio-ambiente", "fonteId": "casos-nacionais-crimes", "regiao_mg": "Noroeste (Paracatu/Urucuia)", "classificavel": True},

    # ─── CONCEIÇÃO DO MATO DENTRO ───
    {"id": "cm-001", "desastre": "nacional", "bacia": "doce", "titulo": "Mineroduto Minas-Rio vs. Quilombolas — Anglo American", "data": "2025", "tipo": "Litígio socioambiental", "orgao": "IBAMA / FEAM / IEF / MPF", "esfera": "federal", "uf": "MG", "tags": ["conceicao-do-mato-dentro", "mineroduto", "anglo-american", "quilombolas", "fragmentacao"], "resumo": "Conflito entre o mineroduto Minas-Rio (Anglo American) e comunidades quilombolas em Conceição do Mato Dentro. Licenciamento fragmentado.", "url": "https://www.gov.br/ibama/pt-br/assuntos/meio-ambiente/licenciamento", "fonteId": "casos-nacionais-crimes", "regiao_mg": "Nordeste (Conceição do Mato Dentro)", "classificavel": True},

    # ─── AÇÕES COLETIVAS — JUSTIÇA ───
    {"id": "ac-001", "desastre": "nacional", "bacia": "doce", "titulo": "MPF/MG — ACP: Repasse de Multas Ambientais ao Funcap", "data": "2025", "tipo": "Ação Civil Pública", "orgao": "MPF/MG", "esfera": "federal", "uf": "MG", "tags": ["acao-coletiva", "mpf", "funcap", "multas-ambientais", "fundao"], "resumo": "MPF/MG ajuíza ACP para repasse de multas ambientais ao Fundo de Defesa do Meio Ambiente (Funcap) referente aos rompimentos de Fundão e Córrego do Feijão.", "url": "https://www.mpf.mp.br/", "fonteId": "acoes-coletivas-justica", "acao_coletiva": True, "instituicao_justica": "MPF/MG", "classificavel": True},
    {"id": "ac-002", "desastre": "nacional", "bacia": "paraopeba", "titulo": "MPMG — TAC: Usiminas — Redução de Pó-Preto em Ipatinga", "data": "2016-2022", "tipo": "Termo de Ajustamento de Conduta", "orgao": "MPMG", "esfera": "estadual", "uf": "MG", "tags": ["tac", "mpmg", "usiminas", "poe-preto", "ipatinga", "saudude"], "resumo": "TAC firmado entre MPMG e Usiminas para redução de emissão de pó-preto em Ipatinga. Vigente desde 2016, renovado até 2022.", "url": "https://www.mpmg.mp.br/", "fonteId": "acoes-coletivas-justica", "acao_coletiva": True, "instituicao_justica": "MPMG", "classificavel": True},
    {"id": "ac-003", "desastre": "nacional", "bacia": "geral", "titulo": "MPMG — TAC: Gerdau — R$ 27 mi para Reparação", "data": "2024", "tipo": "Termo de Ajustamento de Conduta", "orgao": "MPMG", "esfera": "estadual", "uf": "MG", "tags": ["tac", "mpmg", "gerdau", "reparacao", "5-municipios"], "resumo": "TAC firmado entre MPMG e Gerdau para R$ 27 milhões em reparação ambiental em 5 municípios de MG.", "url": "https://www.mpmg.mp.br/", "fonteId": "acoes-coletivas-justica", "acao_coletiva": True, "instituicao_justica": "MPMG", "classificavel": True},
    {"id": "ac-004", "desastre": "nacional", "bacia": "jequitinhonha", "titulo": "MPMG — ACP: Sigma Lithium — Impactos em Araçuaí/Itinga", "data": "2025", "tipo": "Ação Civil Pública", "orgao": "MPMG", "esfera": "estadual", "uf": "MG", "tags": ["acao-coletiva", "mpmg", "sigma-lithium", "lítio", "aracuaí", "itinga"], "resumo": "MPMG ajuíza ACP contra Sigma Lithium por impactos socioambientais em Araçuaí e Itinga, no Vale do Jequitinhonha.", "url": "https://www.mpmg.mp.br/", "fonteId": "acoes-coletivas-justica", "acao_coletiva": True, "instituicao_justica": "MPMG", "classificavel": True},
    {"id": "ac-005", "desastre": "nacional", "bacia": "doce", "titulo": "DPU — Comitê Temático Rio Doce/Brumadinho", "data": "2020-presente", "tipo": "Ação Coletiva", "orgao": "DPU", "esfera": "federal", "uf": "MG", "tags": ["acao-coletiva", "dpu", "comite-tematico", "atingidos", "saude", "habitacao"], "resumo": "Ação coletiva da Defensoria Pública da União para atenção a atingidos nos rompimentos de Fundão e Córrego do Feijão. Habitação, renda e saúde.", "url": "https://direitoshumanos.dpu.def.br/comite-tematico-especializado-rio-doce-brumadinho/", "fonteId": "acoes-coletivas-justica", "acao_coletiva": True, "instituicao_justica": "DPU", "classificavel": True},
    {"id": "ac-006", "desastre": "nacional", "bacia": "doce", "titulo": "MPF/ES + MPES — Medida Cautelar Samarco", "data": "2015", "tipo": "Medida Cautelar", "orgao": "MPF/ES + MPES", "esfera": "federal", "uf": "ES", "tags": ["medida-cautelar", "mpf", "samarco", "onda-de-lama", "rio-doce"], "resumo": "Medida cautelar do MPF/ES e MPES para monitoramento da onda de lama do rompimento de Fundão no Rio Doce. Decisão liminar em 2015.", "url": "https://www.mpf.mp.br/", "fonteId": "acoes-coletivas-justica", "acao_coletiva": True, "instituicao_justica": "MPF/ES + MPES", "classificavel": True},

    # ─── NOTAS TÉCNICAS MINISTERIAIS ───
    {"id": "mt-001", "desastre": "brumadinho", "bacia": "paraopeba", "titulo": "MPMG Coerdoce — ITJ: Relatório de Fiscalização Bacia do Paraopeba", "data": "2025", "tipo": "Informação Técnico-Jurídica (ITJ)", "orgao": "MPMG — Coerdoce", "esfera": "estadual", "uf": "MG", "tags": ["mpmg-coerdoce", "itj", "fiscalizacao", "paraopeba", "brumadinho"], "resumo": "Informação Técnico-Jurídica do MPMG sobre fiscalização na bacia do Paraopeba relacionada ao rompimento da barragem Córrego do Feijão.", "url": "https://mpmg.mp.br/portal/menu/comunicacao/noticias/", "fonteId": "mpmg-coerdoce", "regiao_mg": "Paraopeba", "classificavel": True},
    {"id": "mt-002", "desastre": "mariana", "bacia": "doce", "titulo": "MPF Grandes Casos — Laudo Instituto Lactec", "data": "2024", "tipo": "Laudo técnico", "orgao": "MPF — Grandes Casos", "esfera": "federal", "uf": "MG", "tags": ["mpf-grandes-casos", "lactec", "laudo", "fundao", "samarco"], "resumo": "Laudo técnico do Instituto Lactec apresentado pelo MPF Grandes Casos no caso Samarco/Fundão. Base para acordo e indenizações.", "url": "https://mpf.mp.br/atuacao/grandes-casos/caso-samarco/documentos", "fonteId": "mpf-grandes-casos", "regiao_mg": "Rio Doce", "classificavel": True},
    {"id": "mt-003", "desastre": "brumadinho", "bacia": "paraopeba", "titulo": "DPU Comitê Temático — Nota Técnica Habitação e Renda", "data": "2024", "tipo": "Nota técnica", "orgao": "DPU — Comitê Temático", "esfera": "federal", "uf": "MG", "tags": ["dpu-comite-tematico", "habitacao", "renda", "atingidos", "brumadinho"], "resumo": "Nota técnica do DPU sobre atenção às comunidades atingidas em habitação e renda no âmbito da reparação do rompimento de Córrego do Feijão.", "url": "https://direitoshumanos.dpu.def.br/comite-tematico-especializado-rio-doce-brumadinho/", "fonteId": "dpu-comite-tematico", "regiao_mg": "Paraopeba", "classificavel": True},
    {"id": "mt-004", "desastre": "brumadinho", "bacia": "paraopeba", "titulo": "DPMG — Atuação em Comitês do Acordo de Reparação", "data": "2025", "tipo": "Nota técnica", "orgao": "DPMG", "esfera": "estadual", "uf": "MG", "tags": ["dpmg", "acordo", "reparacao", "comites", "atingidos"], "resumo": "Nota técnica da Defensoria Pública de MG sobre atuação nos comitês do Acordo de Reparação e situação dos atingidos.", "url": "https://defensoria.mg.def.br/", "fonteId": "dpmg-notas", "regiao_mg": "Paraopeba", "classificavel": True},
    {"id": "mt-005", "desastre": "mariana", "bacia": "doce", "titulo": "MPMG Coordenadoria Paraopeba — Articulação com CBH Paraopeba", "data": "2024", "tipo": "Nota técnica", "orgao": "MPMG — Coordenadoria Paraopeba", "esfera": "estadual", "uf": "MG", "tags": ["mpmg-paraopeba", "cbh-paraopeba", "saneamento", "rejeitos"], "resumo": "Nota sobre articulação com CBH Paraopeba e questões de saneamento e rejeitos na bacia, coordenada pela MPMG.", "url": "https://mpmg.mp.br/", "fonteId": "mpmg-coerdoce", "regiao_mg": "Paraopeba", "classificavel": True},
    {"id": "mt-006", "desastre": "mariana", "bacia": "doce", "titulo": "MPMG Coordenadoria Jequitinhonha — Mineração na Bacia", "data": "2024", "tipo": "Nota técnica", "orgao": "MPMG — Coordenadoria Jequitinhonha", "esfera": "estadual", "uf": "MG", "tags": ["mpmg-jequitinhonha", "mineracao", "bacia", "inqueritos-civis"], "resumo": "Nota sobre inquéritos civis e problemas de mineração na bacia do Jequitinhonha, coordenada pela MPMG.", "url": "https://mpmg.mp.br/", "fonteId": "mpmg-coerdoce", "regiao_mg": "Jequitinhonha", "classificavel": True},
    {"id": "mt-007", "desastre": "mariana", "bacia": "doce", "titulo": "CIF/IBAMA — Notas Técnicas Ambientais GTA-PMQQS", "data": "2024", "tipo": "Nota técnica ambiental", "orgao": "CIF/IBAMA", "esfera": "federal", "uf": "MG", "tags": ["cif-ibama", "gta-pmqqs", "notas-tecnicas", "monitoramento", "rio-doce"], "resumo": "Notas técnicas ambientais do Grupo de Trabalho Ambiental do PMQQS (GTA-PMQQS) com dados quantitativos sobre o Rio Doce. 80+ NTs publicadas.", "url": "https://www.ibama.gov.br/cif/notas-tecnicas/", "fonteId": "mpf-grandes-casos", "regiao_mg": "Rio Doce", "classificavel": True},
]

# Atualiza o JSON
dados_expandidos = {
    "fonte": "biblioteca-desastres-expandido",
    "nome": "Biblioteca Unificada Expandido — Mariana, Brumadinho, Nacional e Ações Coletivas",
    "licenca": "lei-acesso-informacao",
    "geradoEm": datetime.utcnow().isoformat() + "Z",
    "ficouDeFora": "Novos itens adicionados: Quadrilátero Ferrífero, Vale do Aço, São Francisco, Rio das Velhas, Verde Grande, Norte/Sul MG, Mucuri, Paracatu, Conceição do Mato Dentro, casos nacionais e ações coletivas.",
    "itens": itens_existentes + novos_itens
}

# Salva o arquivo expandido
caminho_saida = os.path.join(os.path.dirname(__file__), "..", "apps", "web", "public", "data", "biblioteca-desastres.json")
with open(caminho_saida, "w", encoding="utf-8") as f:
    json.dump(dados_expandidos, f, ensure_ascii=False, indent=2)

print(f"Arquivo atualizado: {len(dados_expandidos['itens'])} itens totais")
print(f"Novos itens adicionados: {len(novos_itens)}")
