#!/usr/bin/env node
/**
 * @file scripts/etl/clima/gerar-crise-climatica.mts
 * @description Gerador ETL e consolidador do Acervo Global da Crise Climática.
 *
 * Papel no portal:
 * Alimenta o painel público /ambiental/crise-climatica no portal Controle Popular,
 * disponibilizando os quatro pilares do monitoramento climático global:
 * 1. Emissões de gases de efeito estufa dos países do G20 (Climate TRACE + IPCC AR6 WG3);
 * 2. As maiores instalações e operações industriais pontuais poluidoras do planeta (Climate TRACE + GEM);
 * 3. Anomalias históricas de temperatura média, secas e eventos extremos (Copernicus ECMWF ERA5 + WMO);
 * 4. Metas das NDCs (Acordo de Paris) e intensidade de carbono por setor econômico (UNFCCC + IEA).
 *
 * Fontes oficiais:
 * - Climate TRACE (Emissões antropogênicas territoriais e inventário de ativos industriais): https://climatetrace.org/
 * - IPCC AR6 WG3 (Painel Intergovernamental sobre Mudanças Climáticas - Mitigação): https://www.ipcc.ch/report/ar6/wg3/
 * - Copernicus Climate Change Service / ECMWF (Reanálise ERA5 e anomalias globais de temperatura e SST): https://climate.copernicus.eu/
 * - WMO / OMM (Organização Meteorológica Mundial - State of the Global Climate): https://wmo.int/
 * - UNFCCC NDC Registry (Contribuições Nacionalmente Determinadas): https://unfccc.int/NDCREG
 * - Global Energy Monitor / GEM (Global Coal Plant Tracker & Global Oil and Gas Plant Tracker): https://globalenergymonitor.org/
 * - SEEG / Observatório do Clima (Sistema de Estimativas de Emissões e Remoções de Gases de Efeito Estufa - Brasil): https://seeg.eco.br/
 *
 * Decisões técnicas e restrições:
 * - Compactação algorítmica rigorosa via lib/estatico/compactar.ts (esqueleto + dicionários internados).
 * - Sanitização algorítmica de dados pessoais para conformidade com AGENTS.md §5.2 e LGPD/GDPR.
 * - Todos os valores monetários em USD, emissões em Mt CO₂e ou Gt CO₂e, e temperaturas em graus Celsius (°C).
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compactar } from "../../../apps/web/lib/estatico/compactar.js";
import { sanitizarDadoPessoalInternacional } from "../../../apps/web/lib/internacional/privacidade-internacional.js";

const RAIZ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const DIR_OUT = path.join(RAIZ, "apps", "web", "data", "clima");

// ══════════════════════════════════════════════════════════════════════════
// 1. EMISSÕES DE GEE DOS PAÍSES DO G20 (CLIMATE TRACE + IPCC AR6)
// Referência Global: ~53.800 Mt CO₂e/ano em emissões antropogênicas totais.
// Os 20 membros do G20 respondem por aproximadamente 78% do total mundial.
// ══════════════════════════════════════════════════════════════════════════
export const PAISES_G20_EMISSOES = [
  {
    id: "g20-chn",
    pais: "China",
    codigoIso3: "CHN",
    bandeira: "🇨🇳",
    continente: "Ásia",
    emissoesTotaisMtCo2e: 14320,
    emissoesPerCapitaTCo2e: 10.1,
    participacaoGlobalPct: 26.6,
    setorLiderEmissao: "Geração Elétrica a Carvão & Manufatura Pesada",
    pctSetorLider: 48.2,
    variacaoDecenalPct: 24.5,
    metaNdc2030: "Atingir pico de emissões antes de 2030 e reduzir intensidade de carbono em 65% sobre 2005",
    anoNetZero: 2060,
    classificacaoCat: "Altamente Insuficiente",
    fonteOficial: "Climate TRACE / IPCC AR6 WG3 / MEE China",
    urlFonteOficial: "https://climatetrace.org/",
    observacaoCivica: "Maior emissor mundial absoluto; mais de 1.100 GW operacionais em termoelétricas a carvão mineral.",
  },
  {
    id: "g20-usa",
    pais: "Estados Unidos",
    codigoIso3: "USA",
    bandeira: "🇺🇸",
    continente: "América do Norte",
    emissoesTotaisMtCo2e: 5980,
    emissoesPerCapitaTCo2e: 17.6,
    participacaoGlobalPct: 11.1,
    setorLiderEmissao: "Transportes Rodoviários, Aviação & Gás Fóssil",
    pctSetorLider: 29.4,
    variacaoDecenalPct: -11.8,
    metaNdc2030: "Reduzir emissões líquidas em 50% a 52% abaixo dos níveis de 2005 até 2030",
    anoNetZero: 2050,
    classificacaoCat: "Insuficiente",
    fonteOficial: "EPA Inventory of U.S. GHG / Climate TRACE",
    urlFonteOficial: "https://www.epa.gov/ghgemissions/inventory-us-greenhouse-gas-emissions-and-sinks",
    observacaoCivica: "Maior emissor histórico acumulado do planeta desde a Revolução Industrial; altíssima emissão per capita.",
  },
  {
    id: "g20-ind",
    pais: "Índia",
    codigoIso3: "IND",
    bandeira: "🇮🇳",
    continente: "Ásia",
    emissoesTotaisMtCo2e: 3960,
    emissoesPerCapitaTCo2e: 2.8,
    participacaoGlobalPct: 7.4,
    setorLiderEmissao: "Geração Termelétrica & Agropecuária (Arroz/Gado)",
    pctSetorLider: 42.1,
    variacaoDecenalPct: 41.3,
    metaNdc2030: "Reduzir intensidade de emissões do PIB em 45% e atingir 50% de capacidade elétrica não fóssil",
    anoNetZero: 2070,
    classificacaoCat: "Insuficiente",
    fonteOficial: "Ministry of Environment, Forest and Climate Change / Climate TRACE",
    urlFonteOficial: "https://moef.gov.in/",
    observacaoCivica: "Emissões per capita ainda inferiores à média global, mas com rápida expansão da queima de carvão térmico.",
  },
  {
    id: "g20-eur",
    pais: "União Europeia (UE-27)",
    codigoIso3: "EUR",
    bandeira: "🇪🇺",
    continente: "Europa",
    emissoesTotaisMtCo2e: 3340,
    emissoesPerCapitaTCo2e: 7.4,
    participacaoGlobalPct: 6.2,
    setorLiderEmissao: "Transportes, Indústria Química & Aquecimento",
    pctSetorLider: 28.1,
    variacaoDecenalPct: -23.4,
    metaNdc2030: "Meta vinculante do Fit for 55: redução líquida de pelo menos 55% das emissões frente a 1990",
    anoNetZero: 2050,
    classificacaoCat: "Quase Suficiente",
    fonteOficial: "European Environment Agency (EEA) / Eurostat",
    urlFonteOficial: "https://www.eea.europa.eu/data-and-maps/data/data-viewers/greenhouse-gases-viewer",
    observacaoCivica: "Pioneira no mercado de carbono regulado (EU ETS) e Mecanismo de Ajuste de Fronteira de Carbono (CBAM).",
  },
  {
    id: "g20-rus",
    pais: "Rússia",
    codigoIso3: "RUS",
    bandeira: "🇷🇺",
    continente: "Eurásia",
    emissoesTotaisMtCo2e: 2470,
    emissoesPerCapitaTCo2e: 17.1,
    participacaoGlobalPct: 4.6,
    setorLiderEmissao: "Extração de Gás Natural (Vazamentos/Flaring) & Aquecimento",
    pctSetorLider: 38.6,
    variacaoDecenalPct: 4.8,
    metaNdc2030: "Limitar emissões a 70% do nível de 1990 considerando capacidade de absorção de florestas boreais",
    anoNetZero: 2060,
    classificacaoCat: "Criticamente Insuficiente",
    fonteOficial: "Roshydromet / Climate TRACE",
    urlFonteOficial: "https://climatetrace.org/",
    observacaoCivica: "Grandes vazamentos de metano (CH₄) em gasodutos e exploração ártica de combustíveis fósseis.",
  },
  {
    id: "g20-bra",
    pais: "Brasil",
    codigoIso3: "BRA",
    bandeira: "🇧🇷",
    continente: "América do Sul",
    emissoesTotaisMtCo2e: 2320,
    emissoesPerCapitaTCo2e: 10.9,
    participacaoGlobalPct: 4.3,
    setorLiderEmissao: "Mudança no Uso da Terra / Desmatamento Amazônia e Cerrado",
    pctSetorLider: 48.0,
    variacaoDecenalPct: 15.2,
    metaNdc2030: "Reduzir emissões líquidas em 53% em 2030 frente a 2005 (meta de desmatamento ilegal zero)",
    anoNetZero: 2050,
    classificacaoCat: "Insuficiente",
    fonteOficial: "SEEG / Observatório do Clima / MCTI SIRENE",
    urlFonteOficial: "https://seeg.eco.br/",
    observacaoCivica: "Perfil atípico no G20: quase metade das emissões vem do desmatamento e 27% da agropecuária (gado bovino).",
  },
  {
    id: "g20-idn",
    pais: "Indonésia",
    codigoIso3: "IDN",
    bandeira: "🇮🇩",
    continente: "Ásia",
    emissoesTotaisMtCo2e: 1390,
    emissoesPerCapitaTCo2e: 5.0,
    participacaoGlobalPct: 2.6,
    setorLiderEmissao: "Drenagem de Turfeiras, Queimadas & Expansão de Carvão",
    pctSetorLider: 44.5,
    variacaoDecenalPct: 29.8,
    metaNdc2030: "Redução incondicional de 31,89% e condicional de até 43,2% com cooperação internacional",
    anoNetZero: 2060,
    classificacaoCat: "Altamente Insuficiente",
    fonteOficial: "Ministry of Environment and Forestry Indonesia / Climate TRACE",
    urlFonteOficial: "https://climatetrace.org/",
    observacaoCivica: "Incêndios em turfeiras liberam reservas milenares de carbono; rápida construção de termelétricas cativas para níquel.",
  },
  {
    id: "g20-jpn",
    pais: "Japão",
    codigoIso3: "JPN",
    bandeira: "🇯🇵",
    continente: "Ásia",
    emissoesTotaisMtCo2e: 1115,
    emissoesPerCapitaTCo2e: 8.9,
    participacaoGlobalPct: 2.1,
    setorLiderEmissao: "Geração Termelétrica a Carvão/GNL & Indústria Pesada",
    pctSetorLider: 36.2,
    variacaoDecenalPct: -16.4,
    metaNdc2030: "Redução de 46% nas emissões de GEE até 2030 em comparação com os níveis de 2013",
    anoNetZero: 2050,
    classificacaoCat: "Insuficiente",
    fonteOficial: "Ministry of the Environment Japan / Greenhouse Gas Inventory Office",
    urlFonteOficial: "https://www.env.go.jp/en/",
    observacaoCivica: "Forte importador de GNL e carvão após o desligamento prolongado de usinas nucleares pós-Fukushima.",
  },
  {
    id: "g20-sau",
    pais: "Arábia Saudita",
    codigoIso3: "SAU",
    bandeira: "🇸🇦",
    continente: "Ásia",
    emissoesTotaisMtCo2e: 785,
    emissoesPerCapitaTCo2e: 21.6,
    participacaoGlobalPct: 1.5,
    setorLiderEmissao: "Extração, Refino de Petróleo & Dessalinização Fóssil",
    pctSetorLider: 51.4,
    variacaoDecenalPct: 18.2,
    metaNdc2030: "Reduzir, evitar e remover 278 milhões de toneladas de CO₂e ao ano até 2030",
    anoNetZero: 2060,
    classificacaoCat: "Criticamente Insuficiente",
    fonteOficial: "Ministry of Energy Saudi Arabia / Climate TRACE",
    urlFonteOficial: "https://climatetrace.org/",
    observacaoCivica: "Uma das maiores pegadas per capita do planeta; matriz quase 100% dependente de gás e óleo cru.",
  },
  {
    id: "g20-deu",
    pais: "Alemanha",
    codigoIso3: "DEU",
    bandeira: "🇩🇪",
    continente: "Europa",
    emissoesTotaisMtCo2e: 675,
    emissoesPerCapitaTCo2e: 8.0,
    participacaoGlobalPct: 1.3,
    setorLiderEmissao: "Indústria de Base, Siderurgia & Queima de Lignito",
    pctSetorLider: 31.0,
    variacaoDecenalPct: -27.6,
    metaNdc2030: "Meta nacional da Lei de Proteção do Clima (KSG): corte de 65% até 2030 e neutralidade em 2045",
    anoNetZero: 2045,
    classificacaoCat: "Quase Suficiente",
    fonteOficial: "Umweltbundesamt (UBA) / Climate Action Tracker",
    urlFonteOficial: "https://www.umweltbundesamt.de/en",
    observacaoCivica: "Maior economia da UE; plano de eliminação progressiva do carvão lignito acelerado para a década de 2030.",
  },
  {
    id: "g20-can",
    pais: "Canadá",
    codigoIso3: "CAN",
    bandeira: "🇨🇦",
    continente: "América do Norte",
    emissoesTotaisMtCo2e: 670,
    emissoesPerCapitaTCo2e: 16.8,
    participacaoGlobalPct: 1.2,
    setorLiderEmissao: "Areias Betuminosas de Alberta (Tar Sands) & Transportes",
    pctSetorLider: 32.5,
    variacaoDecenalPct: -7.5,
    metaNdc2030: "Reduzir emissões em 40% a 45% abaixo dos níveis de 2005 até 2030",
    anoNetZero: 2050,
    classificacaoCat: "Insuficiente",
    fonteOficial: "Environment and Climate Change Canada (ECCC)",
    urlFonteOficial: "https://www.canada.ca/en/environment-climate-change.html",
    observacaoCivica: "A extração em areias betuminosas é uma das formas de petróleo mais intensivas em carbono do mundo.",
  },
  {
    id: "g20-kor",
    pais: "Coreia do Sul",
    codigoIso3: "KOR",
    bandeira: "🇰🇷",
    continente: "Ásia",
    emissoesTotaisMtCo2e: 650,
    emissoesPerCapitaTCo2e: 12.6,
    participacaoGlobalPct: 1.2,
    setorLiderEmissao: "Usinas Termelétricas a Carvão, Siderurgia & Petroquímica",
    pctSetorLider: 37.8,
    variacaoDecenalPct: -5.2,
    metaNdc2030: "Corte de 40% nas emissões totais de GEE em relação ao ano de pico de 2018",
    anoNetZero: 2050,
    classificacaoCat: "Altamente Insuficiente",
    fonteOficial: "Greenhouse Gas Inventory and Research Center of Korea (GIR)",
    urlFonteOficial: "https://www.gir.go.kr/eng/",
    observacaoCivica: "Alta concentração em complexos industriais siderúrgicos (POSCO) e parques térmicos de carvão mineral.",
  },
  {
    id: "g20-mex",
    pais: "México",
    codigoIso3: "MEX",
    bandeira: "🇲🇽",
    continente: "América do Norte",
    emissoesTotaisMtCo2e: 625,
    emissoesPerCapitaTCo2e: 4.8,
    participacaoGlobalPct: 1.2,
    setorLiderEmissao: "Petróleo e Refino (PEMEX) & Geração a Óleo Combustível",
    pctSetorLider: 34.0,
    variacaoDecenalPct: 2.1,
    metaNdc2030: "Meta incondicional de corte de 35% nas emissões de GEE frente ao cenário tendencial (BAU)",
    anoNetZero: 2050,
    classificacaoCat: "Criticamente Insuficiente",
    fonteOficial: "INECC / SEMARNAT / Climate TRACE",
    urlFonteOficial: "https://www.gob.mx/inecc",
    observacaoCivica: "Emissões fugitivas elevadas de queima em tocha (flaring) na exploração offshore de hidrocarbonetos.",
  },
  {
    id: "g20-tur",
    pais: "Turquia",
    codigoIso3: "TUR",
    bandeira: "🇹🇷",
    continente: "Eurásia",
    emissoesTotaisMtCo2e: 565,
    emissoesPerCapitaTCo2e: 6.6,
    participacaoGlobalPct: 1.0,
    setorLiderEmissao: "Cimento, Siderurgia & Queima de Lignito Doméstico",
    pctSetorLider: 31.5,
    variacaoDecenalPct: 32.4,
    metaNdc2030: "Redução de até 41% das emissões em relação ao cenário tendencial (BAU) até 2030",
    anoNetZero: 2053,
    classificacaoCat: "Criticamente Insuficiente",
    fonteOficial: "TurkStat / Ministry of Environment, Urbanisation and Climate Change",
    urlFonteOficial: "https://data.tuik.gov.tr/",
    observacaoCivica: "Grande produtor e exportador de cimento e clínquer para a bacia mediterrânea com alta intensidade fóssil.",
  },
  {
    id: "g20-aus",
    pais: "Austrália",
    codigoIso3: "AUS",
    bandeira: "🇦🇺",
    continente: "Oceania",
    emissoesTotaisMtCo2e: 535,
    emissoesPerCapitaTCo2e: 20.3,
    participacaoGlobalPct: 1.0,
    setorLiderEmissao: "Mineração de Carvão e Minério de Ferro & Pecuária",
    pctSetorLider: 35.7,
    variacaoDecenalPct: -12.3,
    metaNdc2030: "Redução de 43% nas emissões líquidas de GEE abaixo dos níveis de 2005 até 2030",
    anoNetZero: 2050,
    classificacaoCat: "Insuficiente",
    fonteOficial: "Department of Climate Change, Energy, the Environment and Water (DCCEEW)",
    urlFonteOficial: "https://www.dcceew.gov.au/climate-change",
    observacaoCivica: "Maior exportador mundial de carvão metalúrgico e térmico (emissões de Escopo 3 massivas no exterior).",
  },
  {
    id: "g20-zaf",
    pais: "África do Sul",
    codigoIso3: "ZAF",
    bandeira: "🇿🇦",
    continente: "África",
    emissoesTotaisMtCo2e: 485,
    emissoesPerCapitaTCo2e: 8.0,
    participacaoGlobalPct: 0.9,
    setorLiderEmissao: "Gaseificação de Carvão (Sasol) & Termelétricas Eskom",
    pctSetorLider: 58.6,
    variacaoDecenalPct: 1.5,
    metaNdc2030: "Faixa de emissões entre 350 e 420 Mt CO₂e em 2030 (corte significativo frente ao pico histórico)",
    anoNetZero: 2050,
    classificacaoCat: "Insuficiente",
    fonteOficial: "Department of Forestry, Fisheries and the Environment (DFFE) / Climate TRACE",
    urlFonteOficial: "https://www.dffe.gov.za/",
    observacaoCivica: "Matriz elétrica quase 80% carvão e sede da planta industrial pontual mais poluidora do planeta (Secunda).",
  },
  {
    id: "g20-gbr",
    pais: "Reino Unido",
    codigoIso3: "GBR",
    bandeira: "🇬🇧",
    continente: "Europa",
    emissoesTotaisMtCo2e: 410,
    emissoesPerCapitaTCo2e: 6.0,
    participacaoGlobalPct: 0.8,
    setorLiderEmissao: "Transportes Terrestres, Aquecimento a Gás & Aviação",
    pctSetorLider: 33.2,
    variacaoDecenalPct: -31.2,
    metaNdc2030: "Compromisso de corte de 68% até 2030 em relação aos níveis de 1990",
    anoNetZero: 2050,
    classificacaoCat: "Quase Suficiente",
    fonteOficial: "Department for Energy Security and Net Zero (DESNZ) / Climate Change Committee",
    urlFonteOficial: "https://www.gov.uk/government/organisations/department-for-energy-security-and-net-zero",
    observacaoCivica: "Encerrou formalmente a queima de carvão para eletricidade em 2024, mas enfrenta gargalo no aquecimento doméstico.",
  },
  {
    id: "g20-ita",
    pais: "Itália",
    codigoIso3: "ITA",
    bandeira: "🇮🇹",
    continente: "Europa",
    emissoesTotaisMtCo2e: 395,
    emissoesPerCapitaTCo2e: 6.7,
    participacaoGlobalPct: 0.7,
    setorLiderEmissao: "Usinas Termelétricas a Gás Natural & Transporte Rodoviário",
    pctSetorLider: 30.5,
    variacaoDecenalPct: -18.7,
    metaNdc2030: "Integrada ao plano Fit for 55 da UE: meta nacional de redução de 43,7% no setor ESR",
    anoNetZero: 2050,
    classificacaoCat: "Quase Suficiente",
    fonteOficial: "ISPRA (Istituto Superiore per la Protezione e la Ricerca Ambientale)",
    urlFonteOficial: "https://www.isprambiente.gov.it/en",
    observacaoCivica: "Dependência acentuada de gás natural importado da Argélia e Azerbaijão para geração termoelétrica.",
  },
  {
    id: "g20-fra",
    pais: "França",
    codigoIso3: "FRA",
    bandeira: "🇫🇷",
    continente: "Europa",
    emissoesTotaisMtCo2e: 385,
    emissoesPerCapitaTCo2e: 5.6,
    participacaoGlobalPct: 0.7,
    setorLiderEmissao: "Transporte Rodoviário & Agropecuária (Matriz Elétrica Nuclear Descarbonizada)",
    pctSetorLider: 31.8,
    variacaoDecenalPct: -19.4,
    metaNdc2030: "Alinhada ao Fit for 55 da UE: meta de -47,5% no esforço compartilhado (ESR) frente a 2005",
    anoNetZero: 2050,
    classificacaoCat: "Quase Suficiente",
    fonteOficial: "CITEPA / Ministère de la Transition Écologique",
    urlFonteOficial: "https://www.citepa.org/fr/",
    observacaoCivica: "Setor elétrico tem baixa emissão devido a ~70% de geração nuclear, concentrando desafio nos transportes.",
  },
  {
    id: "g20-arg",
    pais: "Argentina",
    codigoIso3: "ARG",
    bandeira: "🇦🇷",
    continente: "América do Sul",
    emissoesTotaisMtCo2e: 375,
    emissoesPerCapitaTCo2e: 8.1,
    participacaoGlobalPct: 0.7,
    setorLiderEmissao: "Agropecuária Bovina, Mudança no Uso do Solo & Vaca Muerta (Gás de Xisto)",
    pctSetorLider: 39.0,
    variacaoDecenalPct: 1.8,
    metaNdc2030: "Não ultrapassar a emissão líquida de 349 Mt CO₂e em 2030 (meta incondicional)",
    anoNetZero: 2050,
    classificacaoCat: "Criticamente Insuficiente",
    fonteOficial: "Inventario Nacional de GEI / Secretaría de Ambiente y Desarrollo Sustentable",
    urlFonteOficial: "https://www.argentina.gob.ar/ambiente/cambio-climatico",
    observacaoCivica: "Expansão massiva da fratura hidráulica (fracking) em Vaca Muerta com emissões fugitivas de metano.",
  },
];

// ══════════════════════════════════════════════════════════════════════════
// 2. MAIORES INSTALAÇÕES E OPERAÇÕES POLUIDORAS GLOBAIS (CLIMATE TRACE + GEM)
// Instalações pontuais de ultra-emissão (usinas de carvão, refinarias, CTL e mineração)
// ══════════════════════════════════════════════════════════════════════════
export const MAIORES_INSTALACOES_POLUIDORAS = [
  {
    id: "inst-01",
    nomeInstalacao: "Complexo Secunda Synfuels (Carvão para Líquidos - CTL)",
    operadorControlador: "Sasol South Africa Ltd.",
    pais: "África do Sul",
    codigoIso3: "ZAF",
    cidadeEstado: "Secunda, Mpumalanga",
    tipoAtividade: "Gaseificação CTL / Química",
    emissoesAnuaisMtCo2e: 51.5,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Mineral Sub-betuminoso",
    capacidadeInstalada: "150.000 barris de combustíveis sintéticos/dia",
    equivalenciaCarrosPasseioMilhoes: 11.2,
    latitude: -26.5518,
    longitude: 29.1764,
    fonteOficial: "Climate TRACE Asset-Level / Relatório de Sustentabilidade Sasol",
    urlFonteOficial: "https://climatetrace.org/data",
    contextoImpacto: "A maior instalação industrial pontual emissora de gases de efeito estufa do planeta Terra.",
  },
  {
    id: "inst-02",
    nomeInstalacao: "Usina Termelétrica de Tuoketuo",
    operadorControlador: "Datang International Power Generation Co.",
    pais: "China",
    codigoIso3: "CHN",
    cidadeEstado: "Togtoh, Mongólia Interior",
    tipoAtividade: "Termelétrica a Carvão",
    emissoesAnuaisMtCo2e: 34.2,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Betuminoso de Jazida Aberta",
    capacidadeInstalada: "6.720 MW (8x600 MW + 2x660 MW + 2x300 MW)",
    equivalenciaCarrosPasseioMilhoes: 7.4,
    latitude: 40.1969,
    longitude: 111.3653,
    fonteOficial: "Global Energy Monitor (GEM) / Climate TRACE",
    urlFonteOficial: "https://globalenergymonitor.org/projects/global-coal-plant-tracker/",
    contextoImpacto: "A maior usina termelétrica a carvão do mundo, responsável por abastecer a rede de alta tensão de Pequim.",
  },
  {
    id: "inst-03",
    nomeInstalacao: "Usina Termelétrica de Vindhyachal",
    operadorControlador: "NTPC Limited",
    pais: "Índia",
    codigoIso3: "IND",
    cidadeEstado: "Singrauli, Madhya Pradesh",
    tipoAtividade: "Termelétrica a Carvão",
    emissoesAnuaisMtCo2e: 33.6,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Mineral Doméstico (alto teor de cinzas)",
    capacidadeInstalada: "4.760 MW (6x210 MW + 7x500 MW)",
    equivalenciaCarrosPasseioMilhoes: 7.3,
    latitude: 24.0988,
    longitude: 82.6719,
    fonteOficial: "Central Electricity Authority India (CEA) / Climate TRACE",
    urlFonteOficial: "https://cea.nic.in/",
    contextoImpacto: "Supercomplexo térmico situado no polo energético de Singrauli, com severo impacto em bacias e qualidade do ar.",
  },
  {
    id: "inst-04",
    nomeInstalacao: "Usina Termelétrica de Bełchatów",
    operadorControlador: "PGE Górnictwo i Energetyka Konwencjonalna S.A.",
    pais: "Polônia",
    codigoIso3: "POL",
    cidadeEstado: "Rogowiec, Voivodia de Łódź",
    tipoAtividade: "Termelétrica a Carvão",
    emissoesAnuaisMtCo2e: 32.1,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Lignito (Castanho)",
    capacidadeInstalada: "5.102 MW",
    equivalenciaCarrosPasseioMilhoes: 7.0,
    latitude: 51.2664,
    longitude: 19.3317,
    fonteOficial: "European Pollutant Release and Transfer Register (E-PRTR) / EEA",
    urlFonteOficial: "https://industry.eea.europa.eu/",
    contextoImpacto: "A maior emissora industrial da União Europeia, alimentada por mina a céu aberto contígua de lignito.",
  },
  {
    id: "inst-05",
    nomeInstalacao: "Usina Termelétrica de Taichung",
    operadorControlador: "Taiwan Power Company (Taipower)",
    pais: "Taiwan",
    codigoIso3: "TWN",
    cidadeEstado: "Longjing, Taichung",
    tipoAtividade: "Termelétrica a Carvão",
    emissoesAnuaisMtCo2e: 31.8,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Betuminoso Importado",
    capacidadeInstalada: "5.780 MW (10x550 MW a carvão + turbinas a gás)",
    equivalenciaCarrosPasseioMilhoes: 6.9,
    latitude: 24.2128,
    longitude: 120.4851,
    fonteOficial: "Global Energy Monitor / Climate TRACE",
    urlFonteOficial: "https://globalenergymonitor.org/",
    contextoImpacto: "Queima mais de 12 milhões de toneladas de carvão importado da Austrália e Indonésia anualmente.",
  },
  {
    id: "inst-06",
    nomeInstalacao: "Usina Termelétrica de Kendal",
    operadorControlador: "Eskom Holdings SOC Ltd.",
    pais: "África do Sul",
    codigoIso3: "ZAF",
    cidadeEstado: "Witbank / Emalahleni, Mpumalanga",
    tipoAtividade: "Termelétrica a Carvão",
    emissoesAnuaisMtCo2e: 29.5,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Betuminoso",
    capacidadeInstalada: "4.116 MW (6x686 MW com resfriamento a ar indireto)",
    equivalenciaCarrosPasseioMilhoes: 6.4,
    latitude: -26.0906,
    longitude: 28.9692,
    fonteOficial: "Eskom Integrated Report / Climate TRACE",
    urlFonteOficial: "https://www.eskom.co.za/",
    contextoImpacto: "Situada na bacia carbonífera de Highveld, uma das áreas com pior concentração de dióxido de enxofre do mundo.",
  },
  {
    id: "inst-07",
    nomeInstalacao: "Complexo de Refino de Jamnagar",
    operadorControlador: "Reliance Industries Limited",
    pais: "Índia",
    codigoIso3: "IND",
    cidadeEstado: "Jamnagar, Gujarat",
    tipoAtividade: "Refinaria de Petróleo",
    emissoesAnuaisMtCo2e: 28.4,
    anoReferencia: 2024,
    combustivelPrincipal: "Petróleo Pesado & Coque de Petróleo (Petcoke)",
    capacidadeInstalada: "1.240.000 barris de petróleo bruto/dia",
    equivalenciaCarrosPasseioMilhoes: 6.2,
    latitude: 22.3556,
    longitude: 69.8394,
    fonteOficial: "Climate TRACE Oil & Gas Asset Inventory / Reliance Annual Report",
    urlFonteOficial: "https://climatetrace.org/",
    contextoImpacto: "A maior refinaria de petróleo do planeta em capacidade de processamento contínuo.",
  },
  {
    id: "inst-08",
    nomeInstalacao: "Usina Termelétrica de Dangjin",
    operadorControlador: "Korea East-West Power Co. (KEPCO)",
    pais: "Coreia do Sul",
    codigoIso3: "KOR",
    cidadeEstado: "Dangjin, Chungcheong do Sul",
    tipoAtividade: "Termelétrica a Carvão",
    emissoesAnuaisMtCo2e: 26.2,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Betuminoso Supercrítico",
    capacidadeInstalada: "6.040 MW (8x500 MW + 2x1.020 MW)",
    equivalenciaCarrosPasseioMilhoes: 5.7,
    latitude: 37.0558,
    longitude: 126.5139,
    fonteOficial: "Korea Greenhouse Gas Inventory and Research Center / Climate TRACE",
    urlFonteOficial: "https://www.gir.go.kr/",
    contextoImpacto: "Fornece energia para os polos petroquímicos e siderúrgicos da costa oeste coreana.",
  },
  {
    id: "inst-09",
    nomeInstalacao: "Complexo Siderúrgico de Tangshan (HBIS Tangsteel)",
    operadorControlador: "HBIS Group Co., Ltd.",
    pais: "China",
    codigoIso3: "CHN",
    cidadeEstado: "Tangshan, Hebei",
    tipoAtividade: "Siderurgia & Metalurgia",
    emissoesAnuaisMtCo2e: 24.5,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Metalúrgico (Coque) & Minério de Ferro",
    capacidadeInstalada: "18 milhões de toneladas de aço bruto/ano",
    equivalenciaCarrosPasseioMilhoes: 5.3,
    latitude: 39.6309,
    longitude: 118.1802,
    fonteOficial: "Climate TRACE Steel Tracker / GEM Global Steel Plant Tracker",
    urlFonteOficial: "https://globalenergymonitor.org/projects/global-steel-plant-tracker/",
    contextoImpacto: "Epicentro da siderurgia pesada da China, com queima intensa de carvão metalúrgico para alto-fornos BOF.",
  },
  {
    id: "inst-10",
    nomeInstalacao: "Usina Termelétrica de Neurath",
    operadorControlador: "RWE Power AG",
    pais: "Alemanha",
    codigoIso3: "DEU",
    cidadeEstado: "Grevenbroich, Renânia do Norte-Vestfália",
    tipoAtividade: "Termelétrica a Carvão",
    emissoesAnuaisMtCo2e: 22.8,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Lignito (Castanho)",
    capacidadeInstalada: "4.211 MW (inclui blocos BoA de alta eficiência)",
    equivalenciaCarrosPasseioMilhoes: 5.0,
    latitude: 51.0375,
    longitude: 6.6231,
    fonteOficial: "Umweltbundesamt (UBA) / E-PRTR",
    urlFonteOficial: "https://www.umweltbundesamt.de/",
    contextoImpacto: "Alimentada pela mina a céu aberto de Garzweiler, centro de intensos protestos ecológicos na bacia do Reno.",
  },
  {
    id: "inst-11",
    nomeInstalacao: "Mina de Carvão e Complexo Térmico de Bogatyr (Ekibastuz GRES-1)",
    operadorControlador: "Samruk-Energy / Bogatyr Komir",
    pais: "Cazaquistão",
    codigoIso3: "KAZ",
    cidadeEstado: "Ekibastuz, Pavlodar",
    tipoAtividade: "Mineração & Extração",
    emissoesAnuaisMtCo2e: 21.4,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Sub-betuminoso (44% cinzas)",
    capacidadeInstalada: "4.000 MW térmicos + 42 Mt extração de carvão/ano",
    equivalenciaCarrosPasseioMilhoes: 4.7,
    latitude: 51.7236,
    longitude: 75.3211,
    fonteOficial: "Ministry of Energy Republic of Kazakhstan / Climate TRACE",
    urlFonteOficial: "https://climatetrace.org/",
    contextoImpacto: "A maior mina a céu aberto do mundo em operação contínua, com a chaminé de concreto mais alta da Terra (419,7 m).",
  },
  {
    id: "inst-12",
    nomeInstalacao: "Usina Termelétrica de Waigaoqiao",
    operadorControlador: "Shenergy Company Limited / China Energy",
    pais: "China",
    codigoIso3: "CHN",
    cidadeEstado: "Pudong, Xangai",
    tipoAtividade: "Termelétrica a Carvão",
    emissoesAnuaisMtCo2e: 21.0,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Betuminoso Ultra-supercrítico",
    capacidadeInstalada: "5.000 MW",
    equivalenciaCarrosPasseioMilhoes: 4.6,
    latitude: 31.3533,
    longitude: 121.5975,
    fonteOficial: "Global Energy Monitor / Climate TRACE",
    urlFonteOficial: "https://globalenergymonitor.org/",
    contextoImpacto: "Maior usina termoelétrica litorânea que atende a metrópole de Xangai.",
  },
  {
    id: "inst-13",
    nomeInstalacao: "Usina Termelétrica James H. Miller Jr.",
    operadorControlador: "Alabama Power (Southern Company)",
    pais: "Estados Unidos",
    codigoIso3: "USA",
    cidadeEstado: "Quinton, Alabama",
    tipoAtividade: "Termelétrica a Carvão",
    emissoesAnuaisMtCo2e: 18.7,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Sub-betuminoso da Bacia Powder River",
    capacidadeInstalada: "2.822 MW (4x700 MW)",
    equivalenciaCarrosPasseioMilhoes: 4.1,
    latitude: 33.6319,
    longitude: -87.0597,
    fonteOficial: "EPA FLIGHT (Facility Level Information on Greenhouse Gases Tool)",
    urlFonteOficial: "https://ghgdata.epa.gov/ghgp/main.do",
    contextoImpacto: "A instalação industrial com maior emissão absoluta de CO₂ dos Estados Unidos pelo 9º ano consecutivo.",
  },
  {
    id: "inst-14",
    nomeInstalacao: "Usina Termelétrica Surgut-2",
    operadorControlador: "Unipro (PJSC Unipro)",
    pais: "Rússia",
    codigoIso3: "RUS",
    cidadeEstado: "Surgut, Khanty-Mansi",
    tipoAtividade: "Termelétrica a Gás",
    emissoesAnuaisMtCo2e: 17.6,
    anoReferencia: 2024,
    combustivelPrincipal: "Gás Natural de Petróleo Associado (APG)",
    capacidadeInstalada: "5.687 MW (ciclo combinado gás)",
    equivalenciaCarrosPasseioMilhoes: 3.8,
    latitude: 61.2789,
    longitude: 73.4794,
    fonteOficial: "Ministry of Energy Russian Federation / Climate TRACE",
    urlFonteOficial: "https://climatetrace.org/",
    contextoImpacto: "A maior usina termelétrica a gás fóssil do hemisfério ocidental, que abastece os campos petrolíferos siberianos.",
  },
  {
    id: "inst-15",
    nomeInstalacao: "Complexo Petroquímico e Refino de Jurong Island",
    operadorControlador: "ExxonMobil Asia Pacific / Shell Singapore",
    pais: "Cingapura",
    codigoIso3: "SGP",
    cidadeEstado: "Jurong Island",
    tipoAtividade: "Petroquímica",
    emissoesAnuaisMtCo2e: 14.1,
    anoReferencia: 2024,
    combustivelPrincipal: "Nafta Petroquímica & Óleo Residual",
    capacidadeInstalada: "1.300.000 barris/dia (hub integrado de refino e craqueamento)",
    equivalenciaCarrosPasseioMilhoes: 3.1,
    latitude: 1.2711,
    longitude: 103.7039,
    fonteOficial: "National Environment Agency Singapore / Climate TRACE",
    urlFonteOficial: "https://www.nea.gov.sg/",
    contextoImpacto: "Principal centro de refino e abastecimento marítimo de bunker oil do Sudeste Asiático.",
  },
  {
    id: "inst-16",
    nomeInstalacao: "Refinaria de Baytown",
    operadorControlador: "ExxonMobil Corporation",
    pais: "Estados Unidos",
    codigoIso3: "USA",
    cidadeEstado: "Baytown, Texas",
    tipoAtividade: "Refinaria de Petróleo",
    emissoesAnuaisMtCo2e: 13.2,
    anoReferencia: 2024,
    combustivelPrincipal: "Petróleo Bruto & Gás Fóssil de Refino",
    capacidadeInstalada: "560.500 barris de petróleo bruto/dia",
    equivalenciaCarrosPasseioMilhoes: 2.9,
    latitude: 29.7525,
    longitude: -95.0119,
    fonteOficial: "EPA FLIGHT / Texas Commission on Environmental Quality (TCEQ)",
    urlFonteOficial: "https://ghgdata.epa.gov/",
    contextoImpacto: "Um dos maiores complexos integrados de refino de petróleo e olefinas das Américas na costa do Golfo.",
  },
  {
    id: "inst-17",
    nomeInstalacao: "Complexo Petroquímico Formosa Plastics Point Comfort",
    operadorControlador: "Formosa Plastics Group",
    pais: "Estados Unidos",
    codigoIso3: "USA",
    cidadeEstado: "Point Comfort, Texas",
    tipoAtividade: "Petroquímica",
    emissoesAnuaisMtCo2e: 9.8,
    anoReferencia: 2024,
    combustivelPrincipal: "Etano Fóssil Fraturado & Gás Natural",
    capacidadeInstalada: "2,5 milhões de toneladas de resinas plásticas e etileno/ano",
    equivalenciaCarrosPasseioMilhoes: 2.1,
    latitude: 28.6653,
    longitude: -96.5583,
    fonteOficial: "EPA FLIGHT / Environmental Integrity Project",
    urlFonteOficial: "https://environmentalintegrity.org/",
    contextoImpacto: "Mega-instalação de produção de pellets plásticos (nurdles) e cloreto de vinila com histórico de sanções ambientais.",
  },
  {
    id: "inst-18",
    nomeInstalacao: "Complexo Minerometalúrgico de Carajás (S11D e Mina Norte)",
    operadorControlador: "Vale S.A.",
    pais: "Brasil",
    codigoIso3: "BRA",
    cidadeEstado: "Parauapebas / Canaã dos Carajás, Pará",
    tipoAtividade: "Mineração & Extração",
    emissoesAnuaisMtCo2e: 4.9,
    anoReferencia: 2024,
    combustivelPrincipal: "Óleo Diesel S500/S10 em frotas pesadas & Eletricidade Industrial",
    capacidadeInstalada: "180 milhões de toneladas de minério de ferro/ano",
    equivalenciaCarrosPasseioMilhoes: 1.1,
    latitude: -6.0611,
    longitude: -50.1772,
    fonteOficial: "SEEG / Relatório Integrado de Sustentabilidade Vale S.A. / ANM",
    urlFonteOficial: "https://vale.com/pt/esg",
    contextoImpacto: "A maior mina de minério de ferro a céu aberto do planeta, situada em enclave florestal na Amazônia Oriental.",
  },
  {
    id: "inst-19",
    nomeInstalacao: "Refinaria de Paulínia (REPLAN)",
    operadorControlador: "Petróleo Brasileiro S.A. — Petrobras",
    pais: "Brasil",
    codigoIso3: "BRA",
    cidadeEstado: "Paulínia, São Paulo",
    tipoAtividade: "Refinaria de Petróleo",
    emissoesAnuaisMtCo2e: 4.6,
    anoReferencia: 2024,
    combustivelPrincipal: "Petróleo Bruto do Pré-Sal & Gás de Refinaria",
    capacidadeInstalada: "434.000 barris de petróleo bruto/dia (~20% do refino nacional)",
    equivalenciaCarrosPasseioMilhoes: 1.0,
    latitude: -22.7233,
    longitude: -47.1264,
    fonteOficial: "CETESB / Relatório de Sustentabilidade Petrobras / SEEG",
    urlFonteOficial: "https://petrobras.com.br/sustentabilidade",
    contextoImpacto: "A maior refinaria de petróleo do Brasil, responsável pelo abastecimento de combustíveis do Centro-Sul.",
  },
  {
    id: "inst-20",
    nomeInstalacao: "Complexo Termelétrico Jorge Lacerda",
    operadorControlador: "Diamante Geração de Energia S.A.",
    pais: "Brasil",
    codigoIso3: "BRA",
    cidadeEstado: "Capivari de Baixo, Santa Catarina",
    tipoAtividade: "Termelétrica a Carvão",
    emissoesAnuaisMtCo2e: 4.2,
    anoReferencia: 2024,
    combustivelPrincipal: "Carvão Mineral da Bacia de Santa Catarina",
    capacidadeInstalada: "857 MW (7 grupos geradores)",
    equivalenciaCarrosPasseioMilhoes: 0.9,
    latitude: -28.4489,
    longitude: -48.9719,
    fonteOficial: "ANEEL / CCEE / IMA-SC / SEEG",
    urlFonteOficial: "https://dadosabertos.ccee.org.br/",
    contextoImpacto: "O maior complexo termelétrico a carvão fóssil da América do Sul e o maior poluidor pontual de Santa Catarina.",
  },
];

// ══════════════════════════════════════════════════════════════════════════
// 3. ANOMALIAS DE TEMPERATURA MÉDIA E EVENTOS EXTREMOS (COPERNICUS + WMO)
// ══════════════════════════════════════════════════════════════════════════
export const ANOMALIAS_EVENTOS_EXTREMOS = [
  {
    id: "evt-01",
    tituloEvento: "Recorde Histórico da Temperatura Média Global (Ano Civil de 2024)",
    categoria: "Anomalia Térmica Global",
    regiaoAfetada: "Global (Atmosfera Terrestre)",
    paisesAbrangidos: "Global (Todos os continentes)",
    anoInicio: 2024,
    anoFim: 2024,
    anomaliaOuMagnitude: "+1,64°C acima da média pré-industrial (1850-1900)",
    populacaoOuAreaImpactada: "8,1 bilhões de habitantes do planeta",
    danosEconomicosUsdBilhoes: 310.0,
    orgaoMonitoramento: "Copernicus Climate Change Service (ECMWF) / WMO",
    urlBoletimOficial: "https://climate.copernicus.eu/global-climate-highlights-2024",
    sumarioCientifico: "Primeiro ano civil completo na história instrumental a superar a barreira simbólica de 1,5°C estabelecida no Acordo de Paris.",
  },
  {
    id: "evt-02",
    tituloEvento: "Anomalia Térmica Extrema Global e El Niño Superaquecido (Ano de 2023)",
    categoria: "Anomalia Térmica Global",
    regiaoAfetada: "Global",
    paisesAbrangidos: "Global",
    anoInicio: 2023,
    anoFim: 2023,
    anomaliaOuMagnitude: "+1,48°C acima da era pré-industrial",
    populacaoOuAreaImpactada: "Planeta Terra",
    danosEconomicosUsdBilhoes: 280.0,
    orgaoMonitoramento: "Copernicus ECMWF / NOAA / NASA GISS",
    urlBoletimOficial: "https://climate.copernicus.eu/global-climate-highlights-2023",
    sumarioCientifico: "Ano marcou quebra contínua de recordes mensais consecutivos de temperatura na terra e nos mares.",
  },
  {
    id: "evt-03",
    tituloEvento: "Temperatura Máxima da Superfície do Mar Global (SST Recorde dos Oceanos)",
    categoria: "Oceano & Criosfera",
    regiaoAfetada: "Bacias Oceânicas Globais (60°S a 60°N)",
    paisesAbrangidos: "Zonas Costeiras Globais",
    anoInicio: 2023,
    anoFim: 2025,
    anomaliaOuMagnitude: "21,15°C de temperatura média diária das águas marinhas",
    populacaoOuAreaImpactada: "Ecossistemas coralíneos e 3 bilhões dependentes do mar",
    danosEconomicosUsdBilhoes: 120.0,
    orgaoMonitoramento: "Copernicus Marine Service / NOAA Coral Reef Watch",
    urlBoletimOficial: "https://marine.copernicus.eu/ocean-climate-portal",
    sumarioCientifico: "4º evento global de branqueamento massivo de corais; oceanos absorveram mais de 90% do excesso de calor gerado por GEE.",
  },
  {
    id: "evt-04",
    tituloEvento: "Seca Histórica Extrema e Crise Hídrica na Bacia Amazônica",
    categoria: "Seca & Crise Hídrica",
    regiaoAfetada: "Amazônia Brasileira, Peruana e Colombiana",
    paisesAbrangidos: "Brasil, Peru, Colômbia, Bolívia",
    anoInicio: 2023,
    anoFim: 2024,
    anomaliaOuMagnitude: "Rio Negro em Manaus em cota mínima de 12,70 m (recorde em 122 anos)",
    populacaoOuAreaImpactada: "Mais de 650 mil ribeirinhos e indígenas isolados",
    danosEconomicosUsdBilhoes: 4.8,
    orgaoMonitoramento: "CEMADEN / ANA / INPA / CPRM SGB",
    urlBoletimOficial: "https://www.gov.br/cemaden/pt-br",
    sumarioCientifico: "Combinação de El Niño severo e Atlântico Norte superaquecido estrangulou a umidade amazônica, matando mais de 200 botos no lago Tefé.",
  },
  {
    id: "evt-05",
    tituloEvento: "Inundações Catastróficas no Rio Grande do Sul (Maio de 2024)",
    categoria: "Inundação & Enxurrada",
    regiaoAfetada: "Bacia Hidrográfica do Guaíba e Serra Gaúcha (RS, Brasil)",
    paisesAbrangidos: "Brasil (478 municípios atingidos)",
    anoInicio: 2024,
    anoFim: 2024,
    anomaliaOuMagnitude: "Precipitação superior a 700 mm em 72h; Guaíba atingiu 5,35 m",
    populacaoOuAreaImpactada: "2,3 milhões de pessoas afetadas, 600 mil desalojados",
    danosEconomicosUsdBilhoes: 18.5,
    orgaoMonitoramento: "INMET / CEMADEN / CPRM / IPH-UFRGS",
    urlBoletimOficial: "https://portal.inmet.gov.br/",
    sumarioCientifico: "Bloqueio atmosférico e transporte de umidade em 'rio voador' represado causaram o maior desastre climático da história do Sul do Brasil.",
  },
  {
    id: "evt-06",
    tituloEvento: "Superincêndios Florestais no Pantanal e Cerrado Brasileiro",
    categoria: "Incêndio Florestal",
    regiaoAfetada: "Biomas Pantanal e Cerrado (MT, MS, MG, GO, TO)",
    paisesAbrangidos: "Brasil, Bolívia, Paraguai",
    anoInicio: 2024,
    anoFim: 2024,
    anomaliaOuMagnitude: "3,8 milhões de hectares consumidos pelo fogo no Pantanal",
    populacaoOuAreaImpactada: "Fauna endêmica e comunidades tradicionais pantaneiras",
    danosEconomicosUsdBilhoes: 3.2,
    orgaoMonitoramento: "LASA-UFRJ / INPE Queimadas / IBAMA Prevfogo",
    urlBoletimOficial: "https://queimadas.dgi.inpe.br/queimadas/portal",
    sumarioCientifico: "A maior estiagem dos últimos 74 anos no Pantanal transformou planícies alagáveis em combustível seco inflamável.",
  },
  {
    id: "evt-07",
    tituloEvento: "Incêndios Florestais Históricos no Canadá e Fumaça Continental",
    categoria: "Incêndio Florestal",
    regiaoAfetada: "Florestas Boreais do Canadá (Quebec, Alberta, NWT)",
    paisesAbrangidos: "Canadá e Estados Unidos",
    anoInicio: 2023,
    anoFim: 2023,
    anomaliaOuMagnitude: "18,5 milhões de hectares queimados (6 vezes a média histórica decenal)",
    populacaoOuAreaImpactada: "120 milhões de pessoas sob alertas de ar perigoso (AQI > 400)",
    danosEconomicosUsdBilhoes: 37.0,
    orgaoMonitoramento: "Canadian Wildland Fire Information System (CWFIS) / NOAA",
    urlBoletimOficial: "https://cwfis.cfs.nrcan.gc.ca/",
    sumarioCientifico: "Temporada de incêndios boreais sem precedentes liberou mais de 2 bilhões de toneladas de CO₂e para a atmosfera.",
  },
  {
    id: "evt-08",
    tituloEvento: "Mínimo Histórico de Gelo Marinho na Antártica",
    categoria: "Oceano & Criosfera",
    regiaoAfetada: "Oceano Austral e Plataformas de Gelo da Antártica",
    paisesAbrangidos: "Antártica",
    anoInicio: 2023,
    anoFim: 2024,
    anomaliaOuMagnitude: "Extensão marinha recuou para 1,79 milhão km² (-2,6 milhões km² vs média)",
    populacaoOuAreaImpactada: "Regulação termohalina global e nível médio dos mares",
    danosEconomicosUsdBilhoes: 65.0,
    orgaoMonitoramento: "National Snow and Ice Data Center (NSIDC) / Copernicus",
    urlBoletimOficial: "https://nsidc.org/arcticseaicenews/",
    sumarioCientifico: "Desvio estatístico extremo de 5 desvios-padrão (evento de 1 em 7 milhões de anos sob clima estável).",
  },
  {
    id: "evt-09",
    tituloEvento: "Onda de Calor Letal no Sahel e África Ocidental",
    categoria: "Anomalia Térmica Global",
    regiaoAfetada: "Sahel Ocidental",
    paisesAbrangidos: "Mali, Burkina Faso, Senegal, Níger",
    anoInicio: 2024,
    anoFim: 2024,
    anomaliaOuMagnitude: "Temperaturas sustentadas de 48,5°C em áreas densamente povoadas",
    populacaoOuAreaImpactada: "115 milhões de habitantes com precariedade de refrigeração",
    danosEconomicosUsdBilhoes: 2.5,
    orgaoMonitoramento: "World Weather Attribution (WWA) / WMO",
    urlBoletimOficial: "https://www.worldweatherattribution.org/",
    sumarioCientifico: "Atribuição científica comprovou que o evento extremo foi 45 vezes mais provável e 1,4°C mais quente devido ao aquecimento antrópico.",
  },
  {
    id: "evt-10",
    tituloEvento: "Furacão Otis e Intensificação Explosiva no Pacífico Leste",
    categoria: "Ciclone & Furacão",
    regiaoAfetada: "Costa de Guerrero e Acapulco (México)",
    paisesAbrangidos: "México",
    anoInicio: 2023,
    anoFim: 2023,
    anomaliaOuMagnitude: "Ventos de 270 km/h; intensificação de tempestade tropical a cat. 5 em 12 horas",
    populacaoOuAreaImpactada: "1 milhão de pessoas na área urbana de Acapulco",
    danosEconomicosUsdBilhoes: 16.0,
    orgaoMonitoramento: "National Hurricane Center (NOAA / NHC)",
    urlBoletimOficial: "https://www.nhc.noaa.gov/",
    sumarioCientifico: "Águas oceânicas superficiais a 31°C alimentaram a mais rápida intensificação ciclônica já documentada no Pacífico Oriental.",
  },
  {
    id: "evt-11",
    tituloEvento: "Seca e Colapso Hídrico na Bacia do Rio Yangtzé",
    categoria: "Seca & Crise Hídrica",
    regiaoAfetada: "Bacia Central e Baixa do Yangtzé (China)",
    paisesAbrangidos: "China (Sichuan, Hubei, Jiangxi)",
    anoInicio: 2022,
    anoFim: 2023,
    anomaliaOuMagnitude: "Lago Poyang perdeu 75% da sua superfície; vazão do Yangtzé 50% abaixo da média",
    populacaoOuAreaImpactada: "370 milhões de pessoas e polo hidrelétrico nacional",
    danosEconomicosUsdBilhoes: 14.5,
    orgaoMonitoramento: "China Meteorological Administration (CMA) / Copernicus",
    urlBoletimOficial: "http://www.cma.gov.cn/en2014/",
    sumarioCientifico: "Pior onda de calor e seca da história da China continental, paralisando a navegação fluvial e fábricas de baterias por falta de hidroenergia.",
  },
  {
    id: "evt-12",
    tituloEvento: "Ciclone Daniel e Rompimento de Barragens em Derna (Líbia)",
    categoria: "Inundação & Enxurrada",
    regiaoAfetada: "Cirenaica e Mediterrâneo Oriental",
    paisesAbrangidos: "Líbia, Grécia, Turquia",
    anoInicio: 2023,
    anoFim: 2023,
    anomaliaOuMagnitude: "Precipitação de 414 mm em 24h sobre solo árido; colapso de 2 barragens",
    populacaoOuAreaImpactada: "Cidade de Derna: mais de 11.300 mortos e 40 mil desabrigados",
    danosEconomicosUsdBilhoes: 4.3,
    orgaoMonitoramento: "WMO / ECMWF Copernicus",
    urlBoletimOficial: "https://wmo.int/news/media-centre/",
    sumarioCientifico: "Ciclone com características tropicais (medicane) alimentado por águas do Mediterrâneo 3°C acima da média histórica.",
  },
];

// ══════════════════════════════════════════════════════════════════════════
// 4. METAS DAS NDCS E INTENSIDADE DE CARBONO POR SETOR (UNFCCC + IEA)
// ══════════════════════════════════════════════════════════════════════════
export const NDCS_E_SETORES = [
  {
    id: "setor-01",
    setorEconomico: "Geração de Energia Elétrica e Calor",
    subsetor: "Usinas Termelétricas a Carvão e Gás Fóssil",
    intensidadeCarbonoUnidade: "g CO₂e / kWh",
    valorIntensidadeFossil: 980.0,
    valorIntensidadeLimpa: 18.0,
    potencialReducaoPct: 98.2,
    emissaoGlobalAnualGtCo2e: 15.2,
    participacaoEmissoesGlobaisPct: 28.2,
    metaDescarbonizacao2030: "Triplicar capacidade renovável global (11.000 GW) e dobrar eficiência energética",
    metaNetZero2050: "Setor elétrico 100% descarbonizado nas economias avançadas até 2035 e globalmente até 2040",
    tecnologiaChaveTransicao: "Energia Solar Fotovoltaica, Eólica Onshore/Offshore e Baterias Estacionárias BESS",
    fonteOficial: "IEA World Energy Outlook / Net Zero Roadmap / IPCC AR6",
    urlFonteOficial: "https://www.iea.org/reports/net-zero-roadmap-a-global-pathway-to-keep-the-15-0c-goal-in-reach",
    desafioTransição: "Aposentadoria precoce de mais de 2.000 usinas de carvão e modernização massiva de redes de transmissão.",
  },
  {
    id: "setor-02",
    setorEconomico: "Indústria Pesada — Siderurgia e Aço",
    subsetor: "Alto-forno a Carvão Coque (BF-BOF) vs Forno Elétrico (EAF)",
    intensidadeCarbonoUnidade: "t CO₂e / tonelada de aço bruto",
    valorIntensidadeFossil: 1.89,
    valorIntensidadeLimpa: 0.38,
    potencialReducaoPct: 79.9,
    emissaoGlobalAnualGtCo2e: 3.6,
    participacaoEmissoesGlobaisPct: 6.7,
    metaDescarbonizacao2030: "Comissionamento de pelo menos 50 complexos siderúrgicos com redução direta a hidrogênio verde",
    metaNetZero2050: "Eliminação total do coque fóssil através de DRI-H₂ e eletrificação de alta temperatura",
    tecnologiaChaveTransicao: "Redução Direta de Ferro com Hidrogênio Verde (DRI-H₂) e Forno Elétrico a Arco (EAF)",
    fonteOficial: "Global Energy Monitor (GEM) / IEA Iron and Steel Technology Roadmap",
    urlFonteOficial: "https://www.iea.org/reports/iron-and-steel-technology-roadmap",
    desafioTransição: "Custo elevado do hidrogênio renovável e vida útil residual longa de altos-fornos recém-construídos na Ásia.",
  },
  {
    id: "setor-03",
    setorEconomico: "Indústria de Materiais — Cimento e Clínquer",
    subsetor: "Calcinação de Calcário e Queima de Petcoke",
    intensidadeCarbonoUnidade: "t CO₂e / tonelada de cimento",
    valorIntensidadeFossil: 0.62,
    valorIntensidadeLimpa: 0.18,
    potencialReducaoPct: 71.0,
    emissaoGlobalAnualGtCo2e: 2.8,
    participacaoEmissoesGlobaisPct: 5.2,
    metaDescarbonizacao2030: "Reduzir o fator clínquer médio global para 0,65 e disseminar cimentos de argila calcinada (LC3)",
    metaNetZero2050: "Captura e Armazenamento Geológico de Carbono (CCUS) industrial obrigatório para emissões de processo",
    tecnologiaChaveTransicao: "Cimentos LC3, biomassa/resíduos em coprocessamento e captura CCUS nas chaminés dos fornos",
    fonteOficial: "Global Cement and Concrete Association (GCCA) / IEA",
    urlFonteOficial: "https://gccassociation.org/net-zero-pathway/",
    desafioTransição: "Emissões químicas intrínsecas da descarbonatação do carbonato de cálcio (CaCO₃ → CaO + CO₂).",
  },
  {
    id: "setor-04",
    setorEconomico: "Agropecuária, Uso da Terra e Florestas (AFOLU)",
    subsetor: "Desmatamento Tropical & Fermentação Entérica Bovina",
    intensidadeCarbonoUnidade: "t CO₂e / hectare desmatado na Amazônia",
    valorIntensidadeFossil: 450.0,
    valorIntensidadeLimpa: 0.0,
    potencialReducaoPct: 100.0,
    emissaoGlobalAnualGtCo2e: 7.8,
    participacaoEmissoesGlobaisPct: 14.5,
    metaDescarbonizacao2030: "Desmatamento líquido zero global até 2030 e restauração de 350 milhões de hectares (Desafio de Bonn)",
    metaNetZero2050: "Setor agroflorestal atuando como sumidouro líquido de carbono (-5 Gt CO₂e/ano absorvidos)",
    tecnologiaChaveTransicao: "Rastreabilidade por satélite, sistemas agroflorestais (ILPF), aditivos antimetanogênicos e bioinsumos",
    fonteOficial: "IPCC Special Report on Climate Change and Land / FAO / SEEG",
    urlFonteOficial: "https://www.ipcc.ch/srccl/",
    desafioTransição: "Pressão de commodities agrícolas (soja, carne e óleo de palma) sobre fronteiras florestais nativas.",
  },
  {
    id: "setor-05",
    setorEconomico: "Transportes Terrestres de Passageiros e Cargas",
    subsetor: "Frotas Leves e Caminhões Pesados a Diesel/Gasolina",
    intensidadeCarbonoUnidade: "g CO₂e / passageiro-km ou t-km",
    valorIntensidadeFossil: 165.0,
    valorIntensidadeLimpa: 22.0,
    potencialReducaoPct: 86.7,
    emissaoGlobalAnualGtCo2e: 8.2,
    participacaoEmissoesGlobaisPct: 15.2,
    metaDescarbonizacao2030: "100% dos novos veículos leves vendidos sendo elétricos em mercados líderes e 60% globalmente",
    metaNetZero2050: "Eliminação total de motores a combustão interna fóssil em frotas urbanas e rodoviárias",
    tecnologiaChaveTransicao: "Veículos Elétricos a Bateria (BEV), trens eletrificados e células de combustível de hidrogênio verde",
    fonteOficial: "IEA Global EV Outlook / ICCT (International Council on Clean Transportation)",
    urlFonteOficial: "https://www.iea.org/reports/global-ev-outlook-2024",
    desafioTransição: "Infraestrutura de recarga ultrarrápida em rodovias e disponibilidade de minerais críticos (lítio, níquel, cobre).",
  },
  {
    id: "setor-06",
    setorEconomico: "Aviação Comercial e Executiva",
    subsetor: "Voos Domésticos e Internacionais de Longo Curso",
    intensidadeCarbonoUnidade: "g CO₂e / passageiro-quilômetro (com forçante radiativa)",
    valorIntensidadeFossil: 185.0,
    valorIntensidadeLimpa: 35.0,
    potencialReducaoPct: 81.1,
    emissaoGlobalAnualGtCo2e: 1.1,
    participacaoEmissoesGlobaisPct: 2.0,
    metaDescarbonizacao2030: "Alcançar pelo menos 10% de Combustível Sustentável de Aviação (SAF) no consumo global",
    metaNetZero2050: "Aviação Net-Zero sob o esquema CORSIA da ICAO com 65% de combustíveis sintéticos renováveis",
    tecnologiaChaveTransicao: "Combustível Sustentável de Aviação (SAF biológico e sintético e-kerosene) e motores eficientes",
    fonteOficial: "ICAO (International Civil Aviation Organization) / IATA Net Zero",
    urlFonteOficial: "https://www.icao.int/environmental-protection/CORSIA/",
    desafioTransição: "Escassez de matérias-primas para SAF e custo 3 a 4 vezes superior ao querosene fóssil Jet-A1.",
  },
  {
    id: "setor-07",
    setorEconomico: "Transporte Marítimo Internacional de Cabotagem e Cargas",
    subsetor: "Navios Porta-contêineres, Graneleiros e Petroleiros",
    intensidadeCarbonoUnidade: "g CO₂e / tonelada-milha náutica",
    valorIntensidadeFossil: 14.5,
    valorIntensidadeLimpa: 1.8,
    potencialReducaoPct: 87.6,
    emissaoGlobalAnualGtCo2e: 1.05,
    participacaoEmissoesGlobaisPct: 1.9,
    metaDescarbonizacao2030: "Adoção de combustíveis de emissão zero em pelo menos 5% a 10% da energia da frota mercante (IMO)",
    metaNetZero2050: "Emissões líquidas zero no transporte marítimo internacional até ou por volta de 2050 (Estratégia IMO 2023)",
    tecnologiaChaveTransicao: "Metanol Verde, Amônia Verde, propulsão auxiliar eólica (rotor sails) e eletrificação em cais",
    fonteOficial: "IMO (International Maritime Organization) Greenhouse Gas Strategy",
    urlFonteOficial: "https://www.imo.org/en/OurWork/Environment/Pages/GHG-Emissions.aspx",
    desafioTransição: "Segurança no manuseio de amônia como combustível e reconversão da infraestrutura portuária global.",
  },
  {
    id: "setor-08",
    setorEconomico: "Edificações Residenciais e Comerciais",
    subsetor: "Aquecimento de Ambientes, Água e Refrigeração (Ar-Condicionado)",
    intensidadeCarbonoUnidade: "kg CO₂e / m² de área construída / ano",
    valorIntensidadeFossil: 85.0,
    valorIntensidadeLimpa: 8.0,
    potencialReducaoPct: 90.6,
    emissaoGlobalAnualGtCo2e: 3.4,
    participacaoEmissoesGlobaisPct: 6.3,
    metaDescarbonizacao2030: "Dobrar a taxa de retrofit energético profundo de edifícios existentes para 2,5% ao ano",
    metaNetZero2050: "100% dos edifícios operando com emissão zero e aquecimento por bombas de calor eletrificadas",
    tecnologiaChaveTransicao: "Bombas de Calor de Alta Eficiência, isolamento térmico avançado e arquitetura bioclimática passiva",
    fonteOficial: "Global Alliance for Buildings and Construction (GlobalABC) / UNEP",
    urlFonteOficial: "https://globalabc.org/",
    desafioTransição: "Lentidão nas reformas de edifícios antigos nas cidades do hemisfério norte com caldeiras a gás e óleo.",
  },
  {
    id: "setor-09",
    setorEconomico: "Indústria Química e Petroquímica",
    subsetor: "Produção de Amônia, Etileno, Propileno e Metanol",
    intensidadeCarbonoUnidade: "t CO₂e / tonelada de produto químico primário",
    valorIntensidadeFossil: 2.45,
    valorIntensidadeLimpa: 0.45,
    potencialReducaoPct: 81.6,
    emissaoGlobalAnualGtCo2e: 2.1,
    participacaoEmissoesGlobaisPct: 3.9,
    metaDescarbonizacao2030: "Expandir o uso de matérias-primas químicas recicladas e eletrificação de fornos de craqueamento",
    metaNetZero2050: "Substituição completa de nafta e gás por matérias-primas de carbono circular biobaseado e CCUS",
    tecnologiaChaveTransicao: "Craqueamento elétrico (e-crackers), hidrogênio verde na síntese de amônia e reciclagem molecular",
    fonteOficial: "IEA The Future of Petrochemicals / CEFIC",
    urlFonteOficial: "https://www.iea.org/reports/the-future-of-petrochemicals",
    desafioTransição: "Demanda voraz por energia térmica de alta temperatura e carbono fóssil incorporado na estrutura molecular dos plásticos.",
  },
  {
    id: "setor-10",
    setorEconomico: "Sistemas de Resíduos e Efluentes Urbanos",
    subsetor: "Aterros Sanitários, Lixões e Tratamento de Esgoto Sem Coleta de Biogás",
    intensidadeCarbonoUnidade: "kg CO₂e / habitante atendido / ano",
    valorIntensidadeFossil: 240.0,
    valorIntensidadeLimpa: 25.0,
    potencialReducaoPct: 89.6,
    emissaoGlobalAnualGtCo2e: 1.7,
    participacaoEmissoesGlobaisPct: 3.2,
    metaDescarbonizacao2030: "Corte de 30% nas emissões de metano (Global Methane Pledge) eliminando o descarte de resíduos orgânicos",
    metaNetZero2050: "Universalização da compostagem, digestão anaeróbia com biometano injetado na rede e lixão zero",
    tecnologiaChaveTransicao: "Biodigestores Anaeróbios com Purificação de Biometano e Aterros com Drenagem Ativa de Queima",
    fonteOficial: "Global Methane Initiative / UNEP Global Methane Assessment",
    urlFonteOficial: "https://www.globalmethane.org/",
    desafioTransição: "Persistência de lixões a céu aberto no Sul Global gerando emissões descontroladas de metano por décadas.",
  },
];

function sanitizarLista<T extends Record<string, unknown>>(lista: T[]): T[] {
  return lista.map((item) => {
    const limpo: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(item)) {
      if (typeof v === "string") {
        limpo[k] = sanitizarDadoPessoalInternacional(v);
      } else {
        limpo[k] = v;
      }
    }
    return limpo as T;
  });
}

function main() {
  console.log("🌍 Iniciando geração do Acervo Global da Crise Climática...");

  if (!fs.existsSync(DIR_OUT)) {
    fs.mkdirSync(DIR_OUT, { recursive: true });
  }

  // 1. Sanitizar cada coleção
  const paisesLimpos = sanitizarLista(PAISES_G20_EMISSOES);
  const instalacoesLimpos = sanitizarLista(MAIORES_INSTALACOES_POLUIDORAS);
  const anomaliasLimpos = sanitizarLista(ANOMALIAS_EVENTOS_EXTREMOS);
  const ndcsLimpos = sanitizarLista(NDCS_E_SETORES);

  // 2. Compactar cada coleção via compactar.ts
  const paisesCompacto = compactar(paisesLimpos);
  const instalacoesCompacto = compactar(instalacoesLimpos);
  const anomaliasCompacto = compactar(anomaliasLimpos);
  const ndcsCompacto = compactar(ndcsLimpos);

  // 3. Montar acervo consolidado
  const acervoConsolidado = {
    metadados: {
      versao: "2026-10-01",
      titulo: "Acervo Global da Crise Climática — Controle Popular",
      descricao: "Inventário analítico de emissões do G20, mega-instalações poluidoras mundiais, anomalias extremas Copernicus/WMO e NDCs setoriais.",
      dataAtualizacao: "2026-10-01",
      fontesPrincipais: [
        "Climate TRACE (Asset-level GHG emissions & Country inventories)",
        "IPCC AR6 WG3 (Mitigation of Climate Change)",
        "Copernicus Climate Change Service / ECMWF (ERA5 Reanalysis)",
        "WMO / OMM (State of the Global Climate Report)",
        "UNFCCC (Nationally Determined Contributions Registry)",
        "Global Energy Monitor (GEM Coal & Steel Trackers)",
        "SEEG / Observatório do Clima (Emissões e Metas Nacionais - Brasil)"
      ],
      totalPaisesG20: paisesLimpos.length,
      totalInstalacoes: instalacoesLimpos.length,
      totalAnomaliasEventos: anomaliasLimpos.length,
      totalSetoresNdc: ndcsLimpos.length,
    },
    paisesG20: paisesCompacto,
    instalacoesPoluidoras: instalacoesCompacto,
    anomaliasExtremos: anomaliasCompacto,
    ndcsSetores: ndcsCompacto,
  };

  const caminhoSaida = path.join(DIR_OUT, "crise-climatica-global.compact.json");
  fs.writeFileSync(caminhoSaida, JSON.stringify(acervoConsolidado, null, 2), "utf-8");

  const tamanhoKb = (fs.statSync(caminhoSaida).size / 1024).toFixed(1);
  console.log(`✅ crise-climatica-global.compact.json gerado com sucesso em ${caminhoSaida} (${tamanhoKb} KB).`);
  console.log(`   - Países do G20: ${paisesLimpos.length}`);
  console.log(`   - Mega-instalações poluidoras: ${instalacoesLimpos.length}`);
  console.log(`   - Anomalias e eventos extremos: ${anomaliasLimpos.length}`);
  console.log(`   - NDCs e setores econômicos: ${ndcsLimpos.length}`);
}

main();
