/**
 * Correções de curadoria da memória (títulos curtos e resumos revisados).
 *
 * GERADO por `scripts/memoria/gerar-correcoes-mistica.mts` a partir do
 * relatório da revisão assistida. NÃO editar à mão: o dado vive no
 * relatório (`docs/relatorios-automacao/revisao-textos-memoria.json`) e é
 * reaplicado pelo gerador. A chave é `chaveCorrecao()` em `correcoes.ts`.
 *
 *   tituloCurto — nome de acontecimento (estilo "Revolta da Balaiada");
 *   resumo      — texto revisado, só quando o relatório propôs.
 */
export interface Correcao {
  tituloCurto?: string;
  resumo?: string;
}

export const CORRECOES: Record<string, Correcao> = {
  "01-01|1849|os praieiros, assim conhecidos por se reunirem e": {"tituloCurto":"Revolta Praieira: os praieiros apresentam seu programa no Recife"},
  "01-01|1959|em 1º de janeiro de 1959, fulgencio batista foge": {"tituloCurto":"Triunfo da Revolução Cubana: Fulgêncio Batista foge de Cuba"},
  "01-01|1994|revolucao zapatista em chiapas, mexico": {"tituloCurto":"Revolta Zapatista: EZLN toma Chiapas no México"},
  "01-02|1975|assassinato sumario de siraj sikder pelo aparelh": {"tituloCurto":"Assassinato de Siraj Sikder pelo aparelho de repressão bengali"},
  "01-03|1898|3 de janeiro: 1898: nascimento de luiz carlos pr": {"tituloCurto":"Nasce Luiz Carlos Prestes, o Cavaleiro da Esperança"},
  "01-03|1959|chega a frente de sua coluna em 3 de janeiro de ": {"tituloCurto":"Chegada a Havana da Revolução"},
  "01-03|1961|inicio da revolta camponesa da baixa de cassange": {"tituloCurto":"Revolta camponesa da Baixa de Cassange, em Angola"},
  "01-04|1988|morreu em 4 de janeiro de 1988, vitima da aids, ": {"tituloCurto":"Morre vítima da Aids contraída em transfusão de sangue"},
  "01-05|1968|alexander dubcek chega ao poder na tchecoslovaqu": {"tituloCurto":"Dubček chega ao poder e inicia a Primavera de Praga"},
  "01-06|1835|inicio da revolta dos cabanos": {"tituloCurto":"Início da Revolta dos Cabanos no Grão-Pará"},
  "01-07|1835|a data de 7 de janeiro de 1835 e considerada pel": {"tituloCurto":"Início da Cabanagem no Pará"},
  "01-07|1919|inicio da semana tragica, em buenos aires": {"tituloCurto":"Semana Trágica: operários da Vesena em greve são reprimidos em Buenos Aires"},
  "01-07|s/ano|queimam canaviais, fogem as centenas, atacam naz": {"tituloCurto":"Insurreição de escravizados no Recôncavo baiano"},
  "01-08|1959|fidel castro entra em la habana": {"tituloCurto":"Fidel Castro entra em La Habana após o triunfo da Revolução"},
  "01-09|1920|nascimento de joao cabral de melo neto": {"tituloCurto":"Nasce João Cabral de Melo Neto, poeta do galo e da manhã"},
  "01-12|1886|apos a morte de alexandre, a familia, tambem ja ": {"tituloCurto":"Após a morte de Alexandre, a família muda-se para Kazan"},
  "01-12|s/ano|em 12 de janeiro, um cessar-fogo foi declarado e": {"tituloCurto":"Cessar-fogo e início das negociações entre governo e EZLN"},
  "01-13|1898|emile zola publica “j’accuse…!” e abre publicame": {"tituloCurto":"Émile Zola publica J'Accuse e abre o caso Dreyfus"},
  "01-13|1999|faleceu em itu (sp) em 13 de janeiro de 1999.": {"tituloCurto":"Falece Nelson Werneck Sodré em Itu"},
  "01-14|s/ano|apos mas de 10 horas de batalha, com 300 mortos ": {"tituloCurto":"Praieiros sofrem sua maior derrota após mais de 10 horas de batalha"},
  "01-15|1919|durante o levante operario em berlim, e presa ju": {"tituloCurto":"Assassinato de Rosa Luxemburgo e Karl Liebknecht em Berlim"},
  "01-16|1976|operario metalurgico e militante de base do part": {"tituloCurto":"Assassinato de Manoel Fiel Filho, operário e militante do PCB, pela ditadura"},
  "01-16|1997|assassinato de jose alves dos santos e vanderlei": {"tituloCurto":"Assassinato de José Alves dos Santos e Vanderlei das Neves, mártires da reforma agrária"},
  "01-18|s/ano|em 1961, o governo de lumumba sofre um golpe mil": {"tituloCurto":"Golpe militar assassina Lumumba no Congo"},
  "01-19|1944|nascimento de helenira resende, a “preta”, marti": {"tituloCurto":"Nasce Helenira Resende, a 'Preta', mártir da Revolução Brasileira"},
  "01-20|1973|em 20 de janeiro de 1973, os projetos de cabral ": {"tituloCurto":"Assassinato de Cabral em Conacri interrompe projetos de libertação"},
  "01-21|1924|suas forcas foram se acabando aos poucos, e, no ": {"tituloCurto":"Morre Lenin, revolucionário russo"},
  "01-21|2000|no dia 21 de janeiro de 2000, a rebeliao popular": {"tituloCurto":"Rebelião popular depõe Jamil Mahuad no Equador"},
  "01-22|1891|nasce antonio gramsci": {"tituloCurto":"Nasce Antonio Gramsci, teórico revolucionário italiano"},
  "01-22|s/ano|em 22 de janeiro, o partido comunista salvadoren": {"tituloCurto":"Insurreição salvadorenha e prisão de Farabundo Martí"},
  "01-23|1937|17 militantes comunistas sao condenados no caso ": {"tituloCurto":"17 militantes comunistas condenados no 'Centro Trotskista Anti-Soviético'"},
  "01-24|1835|inicio da revolta dos males": {"tituloCurto":"Início da Revolta dos Malês em Salvador"},
  "01-24|1969|em 24 de janeiro de 1969, comanda uma das mais o": {"tituloCurto":"Deserção e ação ousada da guerrilha no quartel de Quitaúna"},
  "01-24|2006|faleceu em 24 de janeiro de 2006.": {"tituloCurto":"Morre Handal, líder salvadorenho"},
  "01-24|s/ano|encontro aconteceu entre 21 e 24 de janeiro e ma": {"tituloCurto":"Primeiro Encontro Nacional funda movimento unitário"},
  "01-25|2003|o jornal brasil de fato foi lancado no forum soc": {"tituloCurto":"Lançamento do jornal Brasil de Fato no Fórum Social Mundial"},
  "01-25|2019|praticas predatorias da vale s.a. ensejam no rom": {"tituloCurto":"Rompimento da barragem da Vale em Brumadinho"},
  "01-26|1944|nascimento de angela davis": {"tituloCurto":"Nasce Angela Davis, militante e teórica"},
  "01-27|s/ano|os trabalhadores da cana representaram um dos pi": {"tituloCurto":"Trabalhadores da cana, pilar das lutas populares no Uruguai"},
  "01-28|s/ano|mahuad era vice-presidente de abdala bucaram, de": {"tituloCurto":"Dolarização de Mahuad no Equador"},
  "01-30|1956|bombardeio da casa de martin luther king jr. por": {"tituloCurto":"Bombardeio da casa de Martin Luther King Jr. em Montgomery"},
  "01-31|1891|revolta inaugura as lutas pela instauracao da re": {"tituloCurto":"Revolta do Porto inaugura lutas pela República em Portugal"},
  "02-01|1932|execucao de farabundo marti, lider revolucionari": {"tituloCurto":"Execução de Farabundo Martí, líder revolucionário salvadorenho"},
  "02-03|1969|em 3 de fevereiro de 1969, foi assassinado por u": {"tituloCurto":"Assassinato de Mondlane por carta-bomba"},
  "02-05|1944|nasce henfil, cartunista da esperanca": {"tituloCurto":"Nasce Henfil, cartunista da esperança"},
  "02-06|1694|diante da resistencia, o bandeirante domingos jo": {"tituloCurto":"Destruição do Quilombo dos Palmares e morte de Zumbi"},
  "02-07|1756|em 7 de fevereiro de 1756, as margens da sanga d": {"tituloCurto":"Morte de Sepé Tiaraju e massacre de Caiboaté"},
  "02-09|1953|padre ezequiel ramin nasceu em padua, italia, em": {"tituloCurto":"Nasce Padre Ezequiel Ramin, missionário em Rondônia"},
  "02-11|1948|faleceu em 11 de fevereiro de 1948, em moscou.": {"tituloCurto":"Faleceu em 11 de fevereiro de 1948, em Moscou"},
  "02-12|s/ano|ultima expedicao repressiva contra os escravos, ": {"tituloCurto":"Última expedição repressiva contra escravos em revolta no engenho Santana"},
  "02-13|s/ano|mostrou para a classe trabalhadora que o teatro ": {"tituloCurto":"Teatro como arma revolucionária a serviço da emancipação humana"},
  "02-14|s/ano|1997: morte de salete strozake, educadora e diri": {"tituloCurto":"Morte de Salete Strozake, educadora e dirigente do MST"},
  "02-15|1966|no dia 15 de fevereiro de 1966, o revolucionario": {"tituloCurto":"Morte de Camilo Torres Restrepo em enfrentamento na Colômbia"},
  "02-16|s/ano|outras terras do mundo reclamam a colaboracao de": {"tituloCurto":"Chegada às selvas do Congo e partida para a Bolívia"},
  "02-17|1997|foi eleito senador pelo rio de janeiro, cargo qu": {"tituloCurto":"Eleito senador pelo Rio de Janeiro, cargo ocupado até a morte em Brasília"},
  "02-18|1922|entre 11 e 18 de fevereiro de 1922, diversos esc": {"tituloCurto":"Semana da Arte Moderna no Teatro Municipal de São Paulo"},
  "02-19|s/ano|vendo que a derrota era inevitavel, somoza fugiu": {"tituloCurto":"Fuga de Somoza para Miami e derrota da FSLN nas eleições de 1990"},
  "02-20|s/ano|em 1936, com a eclosao da guerra civil espanhola": {"tituloCurto":"Pablo Neruda é destituído do cargo de cônsul na Guerra Civil Espanhola"},
  "02-21|1934|logo apos um encontro, foi sequestrado com algun": {"tituloCurto":"Sequestro e fuzilamento em operação comandada por Anastasio Somoza García"},
  "02-21|1965|em 21 de fevereiro de 1965, aos 39 anos de idade": {"tituloCurto":"Assassinato de Malcolm X enquanto discursava"},
  "02-21|2008|trechos da palestra proferida por emilia viotti ": {"tituloCurto":"Palestra de Emília Viotti da Costa na Escola Nacional Florestan Fernandes"},
  "02-22|s/ano|1989: morte de olivio albani, lider sem-terra ol": {"tituloCurto":"Morte de Olívio Albani, líder sem-terra"},
  "02-23|1917|em 8 de marco de 1917 (dia 23 de fevereiro no ca": {"tituloCurto":"Greve das tecelãs de São Petersburgo inicia a Revolução Russa"},
  "02-24|1965|em 1965 participa da conferencia de argel, em 24": {"tituloCurto":"Participação na Conferência de Argel"},
  "02-25|s/ano|o assassinato de keno ganhou notoriedade interna": {"tituloCurto":"Assassinato de Keno e protestos internacionais"},
  "02-26|s/ano|1984: greve de peoes da construcao civil – belo ": {"tituloCurto":"Greve dos peões da construção civil em Belo Horizonte"},
  "02-27|1917|1917 (27 de fevereiro no calendario russo): grev": {"tituloCurto":"Greve das tecelãs de São Petersburgo dá início à Revolução Russa"},
  "02-28|s/ano|depois que tudo terminou, as autoridades difundi": {"tituloCurto":"Autocrítica do PCB sobre a guerrilha de Porecatu"},
  "02-29|s/ano|o que o proletariado combativo europeu e america": {"tituloCurto":"Homenagem a Marx e sua descoberta da lei da história"},
  "03-01|s/ano|um dos mais importantes dirigentes comunistas po": {"tituloCurto":"Álvaro Cunhal, dirigente comunista português"},
  "03-02|s/ano|o maior conflito armado da historia da america d": {"tituloCurto":"Guerra do Paraguai, o maior conflito armado da América do Sul"},
  "03-03|s/ano|em 1905, enquanto o pais estava em guerra com o ": {"tituloCurto":"Revoltas de 1905 e a criação do primeiro soviete"},
  "03-04|s/ano|deixou obras interessantes, como cachaca (contos": {"tituloCurto":"Obras de autor sobre a questão agrária"},
  "03-05|1909|nascimento de patativa do assare": {"tituloCurto":"Nasce Patativa do Assaré, poeta do sertão"},
  "03-06|1817|no dia 6 de marco, foram tomados fortes militare": {"tituloCurto":"Revolução Pernambucana de 1817"},
  "03-06|1996|perseu abramo morreu em 6 de marco de 1996, aos ": {"tituloCurto":"Morre Perseu Abramo, fundador do PT"},
  "03-07|1936|nascimento de georges perec": {"tituloCurto":"Nasce Georges Perec, escritor"},
  "03-07|1990|luiz carlos prestes nasceu em porto alegre, no r": {"tituloCurto":"Morre Luiz Carlos Prestes, líder da Coluna"},
  "03-08|1911|maria bonita nasceu no sitio malhada da caicara,": {"tituloCurto":"Nasce Maria Bonita, companheira de Lampião"},
  "03-08|1917|essa atuacao politica das operarias nos estados ": {"tituloCurto":"Origem do 8 de março e a Revolução Russa"},
  "03-09|1954|nascimento de bobby sands": {"tituloCurto":"Nasce Bobby Sands, militante irlandês"},
  "03-10|1906|ocorre a catastrofe de courrieres, maior acident": {"tituloCurto":"Catástrofe de Courrières, maior acidente de trabalho da Europa"},
  "03-11|1975|e frustrada em portugal a tentativa contrarrevol": {"tituloCurto":"Frustrado golpe militar de Spinola em Portugal"},
  "03-11|s/ano|na operacao de despejo, no dia 11 de marco, fora": {"tituloCurto":"Despejo violento com aviões e agrotóxicos no Rio Grande do Sul"},
  "03-12|2011|a geracao a rasca sai as ruas em portugal": {"tituloCurto":"Geração à rasca sai às ruas em Portugal"},
  "03-13|1900|nascido em 13 de marco de 1900 no municipio de p": {"tituloCurto":"Nasce Gregório, trabalhador da cana e escravo doméstico"},
  "03-13|1964|realiza-se o comicio da central do brasil": {"tituloCurto":"Comício da Central do Brasil reúne 200 mil"},
  "03-14|1978|carlo giuliani nasceu em roma no dia 14 de marco": {"tituloCurto":"Assassinato de Carlo Giuliani em Gênova"},
  "03-14|1998|no dia 14 de marco de 1998, cerca de 500 familia": {"tituloCurto":"Massacre de Valentim Serra na fazenda Goiás II"},
  "03-14|2018|o dia que marielle franco virou semente": {"tituloCurto":"Marielle Franco vira semente"},
  "03-14|s/ano|marx, deprimido e muito enfermo, com problemas r": {"tituloCurto":"Morre Karl Marx, o maior pensador vivo"},
  "03-14|s/ano|o 14 de marco e, todos os anos, um dia de atos e": {"tituloCurto":"Dia de luta contra barragens e pelo MAB"},
  "03-15|1789|no dia 15 de marco de 1789, o movimento pela ind": {"tituloCurto":"Tiradentes assume sozinho a Inconfidência"},
  "03-15|1917|parte do exercito decide apoiar os rebeldes, e o": {"tituloCurto":"Derrubada do tsar na Rússia"},
  "03-15|1938|nikolai bukharin e assassinado como consequencia": {"tituloCurto":"Assassinato de Bukharin nos Processos de Moscou"},
  "03-15|1951|como resultado de toda essa luta, no dia 15 de m": {"tituloCurto":"Desapropriação das terras de Porecatu"},
  "03-17|1923|jose carlos mariategui retorna ao peru, apos lon": {"tituloCurto":"Mariátegui retorna ao Peru após exílio"},
  "03-19|1849|inicia-se a insurreicao do queimado": {"tituloCurto":"Insurreição do Queimado"},
  "03-20|1921|conselhos operarios se articulam no ruhr em resp": {"tituloCurto":"Conselhos operários no Ruhr contra o golpe de Kapp"},
  "03-22|1968|constitui-se o germen da insurreicao estudantil ": {"tituloCurto":"Mouvement du 22 Mars, gérmen de 1968"},
  "03-23|1980|dom oscar romero profere discurso em defesa do p": {"tituloCurto":"Dom Oscar Romero defende o povo salvadorenho"},
  "03-24|1980|foi assassinado em 24 de marco de 1980, enquanto": {"tituloCurto":"Assassinato de Dom Oscar Romero durante missa"},
  "03-24|1989|acidente do exxon-valdez": {"tituloCurto":"Acidente do Exxon-Valdez no Alasca"},
  "03-25|1922|no dia 25 de marco de 1922, nove pessoas realiza": {"tituloCurto":"Fundação do Partido Comunista do Brasil"},
  "03-26|1815|independencia do uruguai": {"tituloCurto":"Independência do Uruguai e bandeira de Artigas"},
  "03-27|1944|medico e fundador do movimento esquerda revoluci": {"tituloCurto":"Nasce Miguel Enriquez, fundador do MIR chileno"},
  "03-27|1977|primeiro “mitin” da cnt apos a ditadura franquis": {"tituloCurto":"Primeiro mitin da CNT após a ditadura franquista"},
  "03-28|1968|em 28 de marco de 1968, a policia assassina o es": {"tituloCurto":"Assassinato do estudante Edson Luís no Calabouço"},
  "03-28|1988|massacre do capacete e a politica de morte do ex": {"tituloCurto":"Massacre do Capacete contra os tikuna"},
  "03-29|1947|insurreicao malgaxe": {"tituloCurto":"Insurreição malgaxe contra o jugo colonial francês"},
  "03-29|s/ano|constituiu o ponto culminante de um surto de mob": {"tituloCurto":"Mobilização estudantil após a morte de Edson Luís"},
  "03-29|s/ano|em 29 de marco, uma assembleia constituinte e co": {"tituloCurto":"Assembleia Constituinte aprova liberdade de imprensa e culto"},
  "03-30|1976|greves e levantes irrompem contra o jugo assassi": {"tituloCurto":"Dia da Terra: greves e levantes contra a expropriação israelense"},
  "03-30|s/ano|mas foi em 30 de marco que a anl foi publicament": {"tituloCurto":"Lançamento público da ANL com grande comício popular"},
  "03-31|1843|sob sua direcao, o jornal triplicou o numero de ": {"tituloCurto":"Jornal triplica assinaturas e é fechado pela censura"},
  "03-31|1871|nascimento de alexandra kollontai": {"tituloCurto":"Nasce Alexandra Kollontai, revolucionária russa"},
  "03-31|1964|apesar de o golpe ter sido deflagrado em 1º de a": {"tituloCurto":"Golpe de 31 de março e a repressão aos militantes do PCBR"},
  "03-31|1964|para o padre abdala jorge, paroco de timoteo, o ": {"tituloCurto":"Massacre de Timóteo como preparação para o Golpe de 1964"},
  "04-01|1964|mas, em 1º de abril de 1964, o medo das reformas": {"tituloCurto":"Golpe militar de 1º de abril de 1964 freia avanço das lutas populares"},
  "04-02|1962|constantemente ameacado de morte, joao pedro tei": {"tituloCurto":"Assassinato do líder camponês João Pedro Teixeira"},
  "04-02|2019|assassinato de paul mcauley": {"tituloCurto":"Assassinato do missionário Paul McAuley no Peru"},
  "04-03|1959|levante armado do cerro tute": {"tituloCurto":"Levante armado do Cerro Tute no Panamá"},
  "04-04|1931|revolta da madeira, dia de luta contra a ditadur": {"tituloCurto":"Revolta da Madeira contra a ditadura salazarista"},
  "04-04|1968|em 4 de abril de 1968, martin luther king jr.": {"tituloCurto":"Assassinato de Martin Luther King Jr."},
  "04-05|1945|revolta de texel": {"tituloCurto":"Revolta de Texel dos soldados georgianos"},
  "04-06|2008|germen da revolucao egipcia irrompe com um chama": {"tituloCurto":"Gérmen da Revolução Egípcia com chamado à greve"},
  "04-07|1926|morre giovanni amendola, jornalista e politico e": {"tituloCurto":"Morre Giovanni Amendola, espancado por fascistas"},
  "04-08|1973|faleceu em 8 de abril de 1973 em mougins, franca": {"tituloCurto":"Morre Pablo Picasso, autor do mural Guernica"},
  "04-08|2013|margareth thatcher morre, e com ela se vai sua m": {"tituloCurto":"Morre Margareth Thatcher, ícone da política de morte"},
  "04-09|1952|tem inicio a revolucao nacional boliviana": {"tituloCurto":"Revolução Nacional Boliviana derruba Hugo Ballivián"},
  "04-10|1870|vladimir ilitich ulianov nasceu em 10 de abril d": {"tituloCurto":"Nasce Vladimir Ilitich Ulianov, o Lênin"},
  "04-10|1919|em 10 de abril de 1919, zapata foi ao encontro d": {"tituloCurto":"Assassinato de Emiliano Zapata, líder da Revolução Mexicana"},
  "04-11|1925|em 11 de abril de 1925, a coluna prestes, que vi": {"tituloCurto":"Coluna Prestes e Coluna Miguel Costa se unem em Foz do Iguaçu"},
  "04-13|1885|nasce gyorgy lukacs": {"tituloCurto":"Nasce György Lukács, teórico marxista"},
  "04-14|1976|assassinato de zuzu angel": {"tituloCurto":"Assassinato de Zuzu Angel pela ditadura"},
  "04-16|1917|lenin chega a russia depois de seu exilio na sui": {"tituloCurto":"Lênin chega à Rússia depois do exílio na Suíça"},
  "04-16|1930|as complicacoes causadas pela amputacao de sua p": {"tituloCurto":"Morre Mariátegui, fundador do marxismo latino-americano"},
  "04-17|1961|no dia 17 de abril de 1961, cerca de 1.500 cuban": {"tituloCurto":"Invasão da Baía dos Porcos fracassa em Cuba"},
  "04-17|1996|em homenagem aos trabalhadores assassinados, o d": {"tituloCurto":"Massacre de Eldorado dos Carajás e Dia Internacional de Luta Camponesa"},
  "04-18|1955|tem inicio a conferencia de bandung, marco de ar": {"tituloCurto":"Conferência de Bandung articula países não alinhados"},
  "04-19|1923|nascimento de lygia fagundes telles": {"tituloCurto":"Nasce Lygia Fagundes Telles, socialista e imortal"},
  "04-20|1997|na noite do dia 20 de abril de 1997, depois de p": {"tituloCurto":"Assassinato de Galdino Jesus dos Santos, o índio pataxó"},
  "04-21|1792|joaquim jose da silva xavier, conhecido como tir": {"tituloCurto":"Enforcamento de Tiradentes, mártir da Inconfidência Mineira"},
  "04-22|1500|assim, pedro alvares cabral, a frente de diverso": {"tituloCurto":"Chegada de Cabral ao Brasil e início da exploração colonial"},
  "04-22|1945|como passo importante para o final da segunda gu": {"tituloCurto":"Tomada de Berlim pelo Exército soviético"},
  "04-22|s/ano|por que esta no dia 22 de abril esse verbete?": {"tituloCurto":"Nota editorial sobre data do verbete"},
  "04-23|1942|assassinato de olga benario prestes": {"tituloCurto":"Assassinato de Olga Benário Prestes na Alemanha nazista"},
  "04-24|1916|revolta da pascoa": {"tituloCurto":"Revolta da Páscoa na Irlanda"},
  "04-25|1937|faleceu em 25 de abril de 1937.": {"tituloCurto":"Morre Antonio Gramsci, fundador do Partido Comunista Italiano"},
  "04-25|1974|irrompe a revolucao dos cravos": {"tituloCurto":"Irrompe a Revolução dos Cravos em Portugal"},
  "04-26|1933|nascimento de filiberto ojeda rios, fundador e l": {"tituloCurto":"Nasce Filiberto Ojeda Ríos, fundador dos Macheteros"},
  "04-28|1989|quatro anos depois, em 28 de abril de 1989, morr": {"tituloCurto":"Morre em Paris o líder Tupamaro"},
  "04-30|1975|no dia 30 de abril de 1975, saigon, a capital do": {"tituloCurto":"Queda de Saigon e vitória do povo vietnamita"},
  "04-30|s/ano|no dia 30 de abril, hitler se suicida, e, em 7 d": {"tituloCurto":"Tomada de Berlim e rendição da Alemanha nazista"},
  "05-01|1912|no dia do trabalhador e da trabalhadora, nasceu ": {"tituloCurto":"Nasce Azis Simão, no dia do trabalhador e da trabalhadora"},
  "05-01|s/ano|o acontecimento em chicago tornou-se um fato his": {"tituloCurto":"O 1º de Maio e a luta pela jornada de 8 horas"},
  "05-02|1997|paulo freire faleceu em sao paulo no dia 2 de ma": {"tituloCurto":"Morre Paulo Freire, educador da libertação"},
  "05-02|2009|faleceu em 2 de maio de 2009, deixando um legado": {"tituloCurto":"Morre Augusto Boal, fundador do Teatro do Oprimido"},
  "05-03|1937|comecam as jornadas de maio em barcelona, marco ": {"tituloCurto":"Começam as Jornadas de Maio em Barcelona"},
  "05-03|1995|a greve dos petroleiros comecou no dia 3 de maio": {"tituloCurto":"Greve dos petroleiros contra o neoliberalismo"},
  "05-07|1954|o povo vietnamita derrota os franceses em đien b": {"tituloCurto":"O povo vietnamita derrota os franceses em Điện Biên Phủ"},
  "05-07|2000|paulo em 7 de maio de 2000: ser negro no brasil ": {"tituloCurto":"Paulo em 7 de maio de 2000: ser negro no Brasil"},
  "05-07|s/ano|no dia 30 de abril, hitler se suicida, e, em 7 d": {"tituloCurto":"Tomada de Berlim e rendição da Alemanha nazista"},
  "05-08|1830|em 8 de maio de 1830, depois de assistir ao desm": {"tituloCurto":"Morre Simón Bolívar, o libertador da América Latina"},
  "05-08|1887|alexandre, o mais velho, foi executado em 8 de m": {"tituloCurto":"Executado Alexandre Ulyanov, irmão de Lenin"},
  "05-10|1933|inicia a bucherverbrennung, processo espetacular": {"tituloCurto":"Inicia a Bücherverbrennung, queima de livros pelos nazistas"},
  "05-10|1986|em 10 de maio de 1986, mais um lutador tombava p": {"tituloCurto":"Assassinato de Josimo Morais Tavares, defensor das famílias de trabalhadores rurais"},
  "05-10|s/ano|no ano de 1990, o movimento dos trabalhadores ru": {"tituloCurto":"II Congresso do MST, em Brasília, reúne 5 mil delegados"},
  "05-11|1938|derrota do golpe integralista": {"tituloCurto":"Derrota do golpe integralista de Plínio Salgado"},
  "05-12|1927|sob a lideranca de augusto cesar sandino, o povo": {"tituloCurto":"Sandino lidera o povo nicaraguense contra a ocupação estadunidense"},
  "05-12|1978|no dia 12 de maio de 1978, trabalhadores da scan": {"tituloCurto":"Trabalhadores da Scania cruzam os braços"},
  "05-14|1948|em 14 de maio de 1948 os britanicos deixam a pal": {"tituloCurto":"Britânicos deixam a Palestina e é fundado o Estado de Israel"},
  "05-14|1968|a industria sud-aviation e ocupada": {"tituloCurto":"Trabalhadores da Sud-Aviation ocupam fábrica de Bouguenais"},
  "05-15|2019|greve geral da educacao mostra forcas e contem a": {"tituloCurto":"Greve geral da educação contém a contrarreforma previdenciária de Bolsonaro"},
  "05-16|2001|o povo de salvador se coloca nas ruas contra acm": {"tituloCurto":"Povo de Salvador vai às ruas contra ACM e é duramente reprimido"},
  "05-18|1980|revolta de gwangju": {"tituloCurto":"Revolta de Gwangju contra a ditadura de Chun Doo-hwan"},
  "05-19|1890|nascimento de ho chi minh": {"tituloCurto":"Nascimento de Ho Chi Minh, libertador do povo vietnamita"},
  "05-19|1895|marti foi um articulador da luta e morreu em com": {"tituloCurto":"Martí morre em combate pela independência de Cuba"},
  "05-19|1925|nascido em 19 de maio de 1925, na cidade de omah": {"tituloCurto":"Nascimento de Malcolm X, referência na luta contra o preconceito racial"},
  "05-19|s/ano|em 19 de maio, as tropas portuguesas entraram na": {"tituloCurto":"Tropas portuguesas entram em cidade enfraquecida e abandonada"},
  "05-20|1934|nascimento de pepe mujica": {"tituloCurto":"Nascimento de Pepe Mujica, ex-guerrilheiro Tupamaro"},
  "05-21|1969|inicio do rosariazo": {"tituloCurto":"Início do Rosariazo contra a ditadura de Onganía"},
  "05-22|1959|revolta das barcas": {"tituloCurto":"Revolta das Barcas em Niterói"},
  "05-23|1863|fundada a associacao geral dos trabalhadores ale": {"tituloCurto":"Fundação da Associação Geral dos Trabalhadores Alemães"},
  "05-24|1941|nascimento de bob dylan": {"tituloCurto":"Nascimento de Bob Dylan, inspirado por Woody Guthrie"},
  "05-25|1809|em 6 de agosto, a assembleia do alto peru decide": {"tituloCurto":"Assembleia do Alto Peru decide criar a República da Bolívia"},
  "05-26|1824|greve feminina de pawtucket, a “mae de todas as ": {"tituloCurto":"Greve feminina de Pawtucket, a 'mãe de todas as greves'"},
  "05-27|1797|execucao de gracchus babeuf, nosso igual": {"tituloCurto":"Execução de Gracchus Babeuf, condutor da Conjuração dos Iguais"},
  "05-28|s/ano|em uvero, em 28 de maio, se destaca por sua brav": {"tituloCurto":"Em Uvero, em 28 de maio, se destaca por sua bravura"},
  "05-30|2002|faleceu em 30 de maio de 2002, de enfisema pulmo": {"tituloCurto":"Faleceu em 30 de maio de 2002, de enfisema pulmonar, na cidade do Rio de Janeiro"},
  "06-02|1959|em 2 de junho de 1959 contrai matrimonio com ale": {"tituloCurto":"Em 2 de junho de 1959 contrai matrimônio com Aleida March de la Torre, combatente que conhece na serra de Escambray, com a qual terá quatro filhos: Aleida, Camilo, Célia e Ernesto"},
  "06-03|1995|em 3 de junho de 1995, a greve dos petroleiros t": {"tituloCurto":"Em 3 de junho de 1995, a greve dos petroleiros termina com a saída dos trabalhadores da refinaria de Cubatão, mas entra para a história como a maior paralisação da categoria"},
  "06-04|1940|quando tentava sair clandestinamente da franca, ": {"tituloCurto":"Quando tentava sair clandestinamente da França, ele é atacado por uma septicemia – uma infecção grave –, falecendo no dia 4 de junho de 1940, aos 30 anos de idade"},
  "06-07|1973|jose porfirio e libertado por decisao judicial, ": {"tituloCurto":"José Porfírio é libertado por decisão judicial, mas foi visto pela última vez em 7 de junho de 1973, por sua advogada"},
  "06-12|1989|olivio albani estava entre as 700 familias sem-t": {"tituloCurto":"Olívio Albani estava entre as 700 famílias sem-terra que ocupavam a fazenda Caldato, em Palma Sola (SC), em 12 de junho de 1989"},
  "06-13|2005|faleceu em 13 de junho de 2005, em lisboa.": {"tituloCurto":"Faleceu em 13 de junho de 2005, em Lisboa"},
  "06-14|1928|faleceu em londres no dia 14 de junho de 1928, s": {"tituloCurto":"Morre em Londres a sufragista que conquistou o voto feminino"},
  "06-14|1928|nasce ernesto guevara": {"tituloCurto":"Nasce Ernesto Guevara, o Che"},
  "06-15|s/ano|ocorrido entre os dias 11 e 15 de junho no ginas": {"tituloCurto":"V Congresso Camponês define Reforma Agrária, por Justiça Social e Soberania Popular"},
  "06-16|1822|em 16 de junho de 1822, bolivar entra vitorioso ": {"tituloCurto":"Bolívar entra vitorioso em Quito"},
  "06-18|1954|com o argumento de que era preciso derrubar o pr": {"tituloCurto":"EUA treinam e financiam golpe contra o governo democrático da Guatemala"},
  "06-19|1843|em 19 de junho de 1843 casa-se com jenny von wes": {"tituloCurto":"Marx casa-se com Jenny Von Westphalen"},
  "06-20|s/ano|em 1933, se exila na uniao sovietica, onde falec": {"tituloCurto":"Exila-se na União Soviética e falece perto de Moscou"},
  "06-21|2004|faleceu em 21 de junho de 2004 no rio de janeiro": {"tituloCurto":"Falece no Rio de Janeiro o fundador do PDT"},
  "06-22|2002|faleceu em 22 de junho de 2002.": {"tituloCurto":"É assassinado Evandro Cavalcanti, sindicalista de Surubim/PE"},
  "06-23|s/ano|foi fundador do partido comunista italiano.": {"tituloCurto":"Foi fundador do Partido Comunista Italiano"},
  "06-24|2001|milton santos morreu em 24 de junho de 2001 e de": {"tituloCurto":"Morre Milton Santos, geógrafo que revolucionou a geografia no Brasil"},
  "06-25|1975|a guerra durou quase 11 anos, com a independenci": {"tituloCurto":"Moçambique conquista a independência após quase 11 anos de guerra"},
  "06-26|1968|26 de junho de 1968, ano magico em que era pecad": {"tituloCurto":"Multidão ocupa a Avenida Rio Branco por liberdades democráticas"},
  "06-26|s/ano|ao sairem de bracos dados e com os tracos inconf": {"tituloCurto":"600 soldados atacam a comunidade dos Muckers no morro do Ferrabrás"},
  "06-27|1954|sem o apoio do proprio exercito guatemalteco, ar": {"tituloCurto":"Árbenz Guzmán renuncia após golpe financiado pelos EUA na Guatemala"},
  "06-28|1997|durante 30 anos, seus restos mortais permanecera": {"tituloCurto":"Restos mortais são trasladados a Cuba e depositados em mausoléu"},
  "06-29|s/ano|os trabalhadores e trabalhadoras, tendo a frente": {"tituloCurto":"Trabalhadores bolivianos organizam milícias e derrotam regimentos militares"},
  "06-30|s/ano|1937: morte de antonio gramsci, filosofo marxist": {"tituloCurto":"Morre Antonio Gramsci, filósofo marxista italiano"},
  "07-01|1944|conferencia de bretton woods iniciou-se no dia 1": {"tituloCurto":"Conferência de Bretton Woods reorganiza a economia capitalista"},
  "07-02|1976|vietna foi reunificado em 2 de julho de 1976, so": {"tituloCurto":"Vietnã é reunificado sob o regime socialista"},
  "07-03|s/ano|com o tempo, essa comemoracao foi se perdendo, e": {"tituloCurto":"Dia da Mulher Camponesa: luta e mobilização"},
  "07-04|s/ano|organization (organizacao dos estudantes sul-afr": {"tituloCurto":"Morre Steve Biko, líder estudantil sul-africano"},
  "07-05|1920|em 5 de julho, a anl organiza novos comicios pub": {"tituloCurto":"ANL organiza comícios em memória dos levantes tenentistas"},
  "07-05|1975|cabo verde se tornou independente em 5 de julho ": {"tituloCurto":"Independência de Cabo Verde após o assassinato de Cabral"},
  "07-06|1871|castro alves faleceu em salvador (ba) em 6 de ju": {"tituloCurto":"Morre Castro Alves, poeta dos escravizados"},
  "07-07|1897|virgulino ferreira, mais conhecido como lampiao,": {"tituloCurto":"Nasce Lampião, o rei do cangaço"},
  "07-07|1953|em junho de 1953 se gradua como medico e, em 7 d": {"tituloCurto":"A viagem de Che Guevara pela América Latina"},
  "07-08|2002|morreu em 8 de julho de 2002.": {"tituloCurto":"Morre Patativa do Assaré, poeta do sertão"},
  "07-09|s/ano|1948: realizada a 1ª convencao nacional de defes": {"tituloCurto":"1ª Convenção Nacional de Defesa do Petróleo"},
  "07-10|1999|faleceu em 10 de julho de 1999, aos 84 anos de i": {"tituloCurto":"Morre o escritor e líder camponês"},
  "07-11|s/ano|em 1959, as regioes norte e sul entraram em guer": {"tituloCurto":"EUA entram na Guerra do Vietnã"},
  "07-12|1997|durante 30 anos, seus restos mortais permanecera": {"tituloCurto":"Traslado dos restos mortais de guerrilheiro a Cuba"},
  "07-13|s/ano|quando a abolicao finalmente veio, alguns estado": {"tituloCurto":"A vida dos libertos após a abolição"},
  "07-14|1789|descontentes com a crise economica que o pais at": {"tituloCurto":"Queda da Bastilha e Declaração dos Direitos do Homem"},
  "07-15|s/ano|a minha vida nada vale em vista da morte de tant": {"tituloCurto":"A vida vale pouco diante da morte de lavradores"},
  "07-16|s/ano|enquanto esteve exilado em kokushkino, dedicou-s": {"tituloCurto":"Exílio e estudo de estatística e economia"},
  "07-17|1936|a acao tomou corpo em 17 de julho de 1936, com u": {"tituloCurto":"Levante de Franco e resistência popular na Espanha"},
  "07-18|s/ano|aqui nao ha mais cumplices que tu e eu; tu, por ": {"tituloCurto":"Tortura e morte de Túpac Amaru"},
  "07-19|s/ano|a primeira [ideia] e a de que a arbitrariedade e": {"tituloCurto":"Reflexão sobre o subdesenvolvimento e a dependência"},
  "07-20|s/ano|era governador do rio grande do sul quando janio": {"tituloCurto":"Brizola e a Campanha da Legalidade"},
  "07-21|s/ano|desde sua independencia da espanha, cuba esteve ": {"tituloCurto":"Domínio dos EUA e Emenda Platt em Cuba"},
  "07-22|s/ano|a vitoria brasileira conclui a guerra da indepen": {"tituloCurto":"Vitória na Guerra da Independência da Bahia"},
  "07-23|1811|sua primeira experiencia de guerra foi em 23 de ": {"tituloCurto":"Primeira experiência de guerra de Bolívar"},
  "07-23|1993|anualmente, varias organizacoes promovem no dia ": {"tituloCurto":"Chacina da Candelária: memória e luta"},
  "07-24|1985|por isso, padre ezequiel ramin foi assassinado a": {"tituloCurto":"Assassinato do Padre Ezequiel Ramin"},
  "07-24|2008|somente em 24 de julho de 2008, o governo federa": {"tituloCurto":"Anistia a João Cândido e participantes da Revolta da Chibata"},
  "07-25|s/ano|no dia 25 de julho, comemoramos o dia do trabalh": {"tituloCurto":"Dia do Trabalhador Rural"},
  "07-26|1958|em santiago de cuba, se tornou uma das integrant": {"tituloCurto":"Haydée Santamaría integra a direção do Movimento 26 de Julho","resumo":"Haydée Santamaría se tornou uma das integrantes da direção nacional do Movimento 26 de Julho, que articulou a guerrilha cubana nas montanhas. Em janeiro de 1959, com o triunfo da revolução cubana, Haydée assumiu a coordenação da recém-fundada Casa das Américas. A instituição tornou-se um ponto de referência cultural da América Latina, promovendo a arte e a literatura."},
  "07-26|s/ano|nesse periodo, duas organizacoes politicas estiv": {"tituloCurto":"Fidel Castro funda o Movimento Revolucionário 26 de Julho no exílio"},
  "07-27|1995|entre os dias 24 e 27 de julho de 1995, o movime": {"tituloCurto":"MST realiza III Congresso Nacional em Brasília"},
  "07-28|1938|depois de 18 anos, o bando de lampiao sofre sua ": {"tituloCurto":"Última emboscada do bando de Lampião"},
  "07-29|s/ano|essas politicas neoliberais, principalmente sob ": {"tituloCurto":"Levante armado de camponeses e indígenas em Chiapas"},
  "07-30|s/ano|1991: o mst e a comissao pastoral da terra receb": {"tituloCurto":"MST e CPT recebem o Prêmio Nobel Alternativo na Suécia"},
  "07-31|s/ano|dessa forma, dessalines tornou-se, em 1804, o pr": {"tituloCurto":"Dessalines torna-se o primeiro governante do Haiti independente"},
  "08-01|1902|explode a mina de carvao do monte klemba": {"tituloCurto":"Explosão na mina de carvão do Monte Klemba"},
  "08-02|1953|no marco da revolucao boliviana, tem inicio a re": {"tituloCurto":"Revolução Boliviana inicia reforma agrária e institui o Dia do Índio"},
  "08-03|1977|como resposta a explosao da mina de chipanga 3, ": {"tituloCurto":"Rebelião popular após explosão na mina Chipanga 3 em Moçambique"},
  "08-04|1919|tropas romenas ocupam budapeste e colocam fim a ": {"tituloCurto":"Tropas romenas ocupam Budapeste e põem fim à República dos Conselhos"},
  "08-05|1895|friedrich engels morreu em 5 de agosto de 1895 e": {"tituloCurto":"Morre Friedrich Engels em Londres"},
  "08-06|1826|em 6 de agosto, a assembleia do alto peru decide": {"tituloCurto":"Assembleia do Alto Peru decide a criação da República da Bolívia"},
  "08-06|1945|em 6 de agosto de 1945, a forca aerea estadunide": {"tituloCurto":"EUA lançam bombas atômicas sobre Hiroshima e Nagasaki"},
  "08-06|1960|fidel e raul castro anunciam a lei 851, que naci": {"tituloCurto":"Fidel e Raúl Castro anunciam nacionalização de empresas estadunidenses em Cuba"},
  "08-07|2006|foi promulgada a lei maria da penha": {"tituloCurto":"Promulgada a Lei Maria da Penha"},
  "08-08|1942|inicia-se o movimento quit india": {"tituloCurto":"Inicia-se o movimento Quit India na Índia"},
  "08-09|1925|nascia francisco rene santucho, intelectual e mi": {"tituloCurto":"Nasce Francisco René Santucho, intelectual e militante revolucionário argentino"},
  "08-09|1995|na madrugada de 9 de agosto de 1995, um continge": {"tituloCurto":"Massacre de Corumbiara: policiais atacam famílias sem-terra na fazenda Santa Elina"},
  "08-09|1997|falece em 9 de agosto de 1997, debilitado pela a": {"tituloCurto":"Morre vítima da Aids, irmão de Henfil e Mário","resumo":"Falece em 9 de agosto de 1997, debilitado pela Aids, que havia contraído numa transfusão de sangue, mesma causa da morte de seus irmãos Henfil e Mário, também hemofílicos."},
  "08-10|1792|no bojo da revolucao francesa, uma jornada insur": {"tituloCurto":"Jornada insurrecional do povo parisiense põe fim à monarquia na França"},
  "08-10|1974|em 10 de agosto de 1974, foi encontrado morto, t": {"tituloCurto":"Morre o jornalista e militante político","resumo":"Em 10 de agosto de 1974, foi encontrado morto, tendo se enforcado. Em março de 1983, seus restos mortais foram trazidos de volta ao Brasil."},
  "08-11|1937|em 11 de agosto de 1937, o conselho nacional est": {"tituloCurto":"Fundação da União Nacional dos Estudantes (UNE)"},
  "08-11|1979|o rompimento da barragem de machchu-ii, india, v": {"tituloCurto":"Rompimento da barragem de Machchu-II, Índia, mata mais de 15 mil"},
  "08-11|s/ano|dos debates realizados entre os dias 7 e 11 de a": {"tituloCurto":"Congresso camponês aponta Reforma Agrária, por um Brasil sem Latifúndio"},
  "08-12|s/ano|em sua homenagem, o dia 12 de agosto foi declara": {"tituloCurto":"Dia Nacional de Luta das Mulheres do Campo"},
  "08-13|1961|em 13 de agosto de 1961, o lado sovietico ergueu": {"tituloCurto":"Erguido o Muro de Berlim, símbolo da Guerra Fria"},
  "08-14|1956|faleceu em berlim no dia 14 de agosto de 1956, a": {"tituloCurto":"Falece Bertolt Brecht em Berlim"},
  "08-15|1805|em 15 de agosto de 1805, faz um juramento diante": {"tituloCurto":"Bolívar jura libertar a América no Monte Sacro"},
  "08-16|s/ano|tambem foi coordenador da pastoral da diocese, a": {"tituloCurto":"Coordenador da pastoral sofre atentado no Bico do Papagaio"},
  "08-17|s/ano|1987: inicio da primeira intifada, revolta popul": {"tituloCurto":"Início da Primeira Intifada palestina"},
  "08-18|s/ano|portugal passou a ser governado provisoriamente ": {"tituloCurto":"Junta de Salvação Nacional assume Portugal com lema Democratizar, Descolonizar, Desenvolver"},
  "08-19|1936|sem ter tido qualquer julgamento, foi fuzilado e": {"tituloCurto":"Fuzilado em 1936 por ser homossexual e por sua postura política"},
  "08-19|2009|a fazenda nova alegria foi transformada em assen": {"tituloCurto":"Fazenda Nova Alegria transformada em assentamento"},
  "08-20|1940|no dia 20 de agosto de 1940, leon trotsky e assa": {"tituloCurto":"Leon Trotsky é assassinado no México"},
  "08-21|1940|perdemos o maior dos inquietos e profeta – deuts": {"tituloCurto":"Leon Trotsky, assassinado por Mercader, lacaio de Stálin"},
  "08-21|1971|george jackson morreu tres dias antes de ir a ju": {"tituloCurto":"Morre George Jackson três dias antes do julgamento"},
  "08-22|1978|e conduzida a operacao chanchera, que leva as fo": {"tituloCurto":"Operação Chanchera leva sandinistas a tomarem palácio legislativo nicaraguense"},
  "08-23|1927|sacco e vanzetti sao executados": {"tituloCurto":"Sacco e Vanzetti são executados após farsa processual"},
  "08-24|1882|morreu, vitima de diabetes, em 24 de agosto de 1": {"tituloCurto":"Morre Luiz Gama, o libertador de escravos"},
  "08-25|s/ano|esta chegando ao fim uma greve que paralisou 60 ": {"tituloCurto":"Greve de 60 mil marítimos no Rio de Janeiro conquista aumento de 15%"},
  "08-26|1789|em 26 de agosto de 1789, foi promulgada a declar": {"tituloCurto":"Promulgada a Declaração Universal dos Direitos do Homem e do Cidadão"},
  "08-27|1999|faleceu em recife no dia 27 de agosto de 1999.": {"tituloCurto":"Falece em Recife, reconhecido pela luta pela paz e justiça"},
  "08-28|1963|em 28 de agosto de 1963, mais de 250 mil pessoas": {"tituloCurto":"Marcha em Washington por trabalho e liberdade reúne 250 mil"},
  "08-29|s/ano|foi vendedor, jornalista, prefeito e instrutor d": {"tituloCurto":"Graciliano Ramos publica Caetés e é preso na ditadura Vargas"},
  "08-30|s/ano|em 1844, na alemanha, conhece pessoalmente karl ": {"tituloCurto":"Engels conhece Marx na Alemanha e redige Princípios do comunismo"},
  "08-31|1958|em 31 de agosto de 1958 inicia a invasao a parte": {"tituloCurto":"Coluna 8 Ciro Redondo inicia invasão e Campanha de Las Villas"},
  "09-01|s/ano|nas primeiras decadas do seculo 19, no maranhao,": {"tituloCurto":"Maranhão, palco de tensões que levariam à Balaiada"},
  "09-02|1969|ho chi-minh morre em 2 de setembro de 1969, nao ": {"tituloCurto":"Morre Ho Chi-minh, líder da luta pela reunificação do Vietnã"},
  "09-03|s/ano|pm dispara contra um piquete de cortadores de ca": {"tituloCurto":"Massacre de cortadores de cana em greve em Leme/SP"},
  "09-04|1839|um tribunal reunido em janeiro de 1838 condenou ": {"tituloCurto":"Enforcamento de Manoel Congo, líder do levante de Vassouras"},
  "09-04|1958|em 4 de setembro de 1958, forma, junto com melba": {"tituloCurto":"Formação do pelotão Mariana Grajales, de mulheres guerrilheiras cubanas"},
  "09-05|s/ano|durante a ditadura de batista, seus aliados enri": {"tituloCurto":"Perseguição às forças populares e miséria sob a ditadura de Batista"},
  "09-06|1977|em 6 de setembro de 1977, foi preso em um bloque": {"tituloCurto":"Prisão de fundador do Movimento de Consciência Negra em bloqueio policial"},
  "09-07|s/ano|assim, na madrugada de 7 de setembro, aproveitan": {"tituloCurto":"Ocupação das fazendas Macali e Brilhante por centenas de famílias"},
  "09-08|s/ano|1849 cerca de 1.600 rebeldes praieiros avancas s": {"tituloCurto":"Derrota dos rebeldes praieiros em Recife"},
  "09-09|1976|mao tse-tung faleceu em 9 de setembro de 1976, c": {"tituloCurto":"Morte de Mao Tse-tung, líder da revolução chinesa"},
  "09-09|s/ano|em 9 de setembro, tem seu primeiro encontro com ": {"tituloCurto":"Primeiros combates de guerrilheiro cubano na La Federal e em Cuatro Compañeros"},
  "09-10|1974|a independencia da guine-bissau foi proclamada e": {"tituloCurto":"Independência da Guiné-Bissau e de Cabo Verde"},
  "09-10|1979|agostinho neto falece em 10 de setembro de 1979,": {"tituloCurto":"Morte de Agostinho Neto, líder da independência angolana"},
  "09-11|1973|na manha do dia 11 de setembro, enquanto parte d": {"tituloCurto":"Golpe militar no Chile e resistência de Salvador Allende"},
  "09-11|1977|biko morreu no dia 11 de setembro de 1977, enqua": {"tituloCurto":"Morte de Steve Biko, líder do Movimento de Consciência Negra"},
  "09-12|s/ano|mapa do brasil: o mst e um movimento nacional e ": {"tituloCurto":"Símbolos do MST: mapa do Brasil, mulher e homem, facão"},
  "09-13|s/ano|dom helder pessoa camara nasceu em fortaleza, ce": {"tituloCurto":"Nascimento de Dom Hélder Câmara em Fortaleza"},
  "09-14|s/ano|em 9 de setembro, tem seu primeiro encontro com ": {"tituloCurto":"Combates de guerrilheiro cubano na La Federal e em Cuatro Compañeros"},
  "09-15|s/ano|com esperanca de se livrar dos problemas sociais": {"tituloCurto":"Peregrinação de Antônio Conselheiro e fundação de Canudos"},
  "09-16|1973|em 16 de setembro de 1973, foi assassinado a tir": {"tituloCurto":"Assassinato de preso político no Estádio Chile após o golpe de 1973"},
  "09-16|1989|no dia 16 de setembro, a udr e a policia militar": {"tituloCurto":"Resistência ao despejo de famílias e greve dos canavieiros de Pernambuco"},
  "09-17|1971|em 17 de setembro de 1971, lamarca e assassinado": {"tituloCurto":"Assassinato de Lamarca pela ditadura militar no sertão da Bahia"},
  "09-18|1850|mas, para dificultar o acesso dos pobres e mante": {"tituloCurto":"Lei de Terras de 1850 e a concentração fundiária"},
  "09-19|2002|dom jose faleceu em 19 de setembro de 2002.": {"tituloCurto":"Morte de Dom José Gomes, bispo da luta pela terra"},
  "09-20|s/ano|me mantenho firme na conviccao de que somente a ": {"tituloCurto":"Exílio e retorno de Gregório Bezerra com a anistia"},
  "09-21|s/ano|o 21 de setembro foi escolhido para o combate ao": {"tituloCurto":"Fundação da União Operária em Livramento/RS e o 21 de setembro"},
  "09-22|s/ano|em 1964, henfil trabalha como cartunista na revi": {"tituloCurto":"Henfil, cartunista da esperança, é censurado pela ditadura"},
  "09-23|1973|pablo neruda, grande comunista e poeta, morre em": {"tituloCurto":"Morre Pablo Neruda, poeta comunista e embaixador de Allende"},
  "09-23|2005|na tarde de 23 de setembro de 2005, comeco da pr": {"tituloCurto":"Morre Apolônio de Carvalho, expressão da dignidade do povo brasileiro"},
  "09-24|1973|a independencia da guine-bissau foi proclamada e": {"tituloCurto":"Independência da Guiné-Bissau é proclamada","resumo":"Após a morte de Amílcar Cabral, a luta armada pela independência da Guiné-Bissau se intensificou."},
  "09-24|1973|morou na franca ate sua morte, em 24 de setembro": {"tituloCurto":"Morre no exílio, em 24 de setembro de 1973"},
  "09-25|1828|em 25 de setembro de 1828, bolivar, que insistia": {"tituloCurto":"Bolívar sofre atentado e é salvo por Manuela Sáenz"},
  "09-25|1964|a luta armada iniciou-se em 25 de setembro de 19": {"tituloCurto":"Frelimo inicia luta armada pela independência de Moçambique","resumo":"A luta armada da Frelimo pela independência de Moçambique iniciou-se em 25 de setembro de 1964."},
  "09-26|s/ano|no total as mortes subiram a 100.": {"tituloCurto":"Levante dos malês deixa 100 mortos e inspira Luiz Gama"},
  "09-27|s/ano|tudo comecou com getulio vargas na decada de 30,": {"tituloCurto":"Getúlio Vargas coloniza o interior do Brasil e atrai famílias ao Paraná"},
  "09-28|1932|em chillan, chile, nasceu em 28 de setembro de 1": {"tituloCurto":"Nasce Víctor Jara, cantor e compositor chileno"},
  "09-29|1908|faleceu em 29 de setembro de 1908.": {"tituloCurto":"Morre o escritor que retratou o Brasil entre o Império e a República"},
  "09-30|s/ano|geopolitica da fome – 2 volumes.": {"tituloCurto":"Geopolítica da fome – 2 volumes"},
  "10-01|1949|em 1º de outubro de 1949, e declarada a republic": {"tituloCurto":"É declarada a República Popular da China"},
  "10-02|1992|na manha do dia 2 de outubro de 1992, a tropa de": {"tituloCurto":"Massacre do Carandiru"},
  "10-03|1953|como resultado, em 3 de outubro de 1953, foi cri": {"tituloCurto":"Criação da Petrobras e quebra do monopólio estatal"},
  "10-03|1990|a unificacao da alemanha se completaria em 3 de ": {"tituloCurto":"Unificação da Alemanha"},
  "10-04|2009|faleceu em 4 de outubro de 2009.": {"tituloCurto":"Morre Mercedes Sosa, voz do folclore argentino","resumo":"Gravando canções de Violeta Parra, Ataulpa Yupanqui, Chico Buarque e Leon Gieco, Mercedes Sosa torna-se conhecida também por resgatar canções do folclore argentino e da cultura indígena. Com o golpe militar na Argentina, Mercedes Sosa, que possuía vínculos com o peronismo de esquerda, é presa durante um show em 1979."},
  "10-05|1897|em 05 de outubro de 1897, cessou a resistencia d": {"tituloCurto":"Fim da resistência dos sertanejos em Canudos"},
  "10-05|1974|miguel enriquez e assassinado com dez tiros em 5": {"tituloCurto":"Assassinato de Miguel Enriquez, líder do MIR chileno"},
  "10-06|1963|no dia 06 de outubro de 1963 foi realizada a pri": {"tituloCurto":"Primeira assembleia em Ipatinga e a vistoria nas marmitas"},
  "10-07|1963|para o padre abdala jorge, paroco de timoteo, o ": {"tituloCurto":"Massacre de Timóteo, preparação para o Golpe de 1964"},
  "10-08|1967|no combate de quebrada del yuro, em 8 de outubro": {"tituloCurto":"Che Guevara é capturado e assassinado na Bolívia"},
  "10-08|s/ano|descontente com a vpr, ingressa no movimento rev": {"tituloCurto":"Carlos Lamarca ingressa no MR-8 e parte para o sertão baiano","resumo":"Descontente com a VPR, Carlos Lamarca ingressa no Movimento Revolucionário 8 de Outubro (MR-8) e parte para o sertão baiano em nova tentativa de formar um foco de guerrilha rural. Parte junto com ele Iara Iavelberg, psicóloga e também guerrilheira, que se torna sua companheira na clandestinidade. Iara é morta durante um cerco da polícia em Salvador em agosto de 1971, em circunstâncias até hoje nebulosas."},
  "10-09|s/ano|augustin farabundo marti rodriguez foi um grande": {"tituloCurto":"Nasce Farabundo Martí, dirigente de esquerda de El Salvador"},
  "10-10|1980|em 10 de outubro de 1980, e criada a frente fara": {"tituloCurto":"Criação da Frente Farabundo Martí de Libertação Nacional"},
  "10-11|s/ano|a essa altura, os indigenas se juntavam aos milh": {"tituloCurto":"Insurgência de Túpac Amaru no Peru"},
  "10-12|s/ano|alem disso, o mexico aderiu ao acordo de livre c": {"tituloCurto":"México adere ao Nafta e afunda em dívida e desemprego"},
  "10-13|s/ano|1983: vitoria da encruzilhada natalino, rio gran": {"tituloCurto":"Vitória da Encruzilhada Natalino, símbolo da luta pela terra"},
  "10-14|1813|em 14 de outubro de 1813, depois de uma entrada ": {"tituloCurto":"Bolívar é aclamado Libertador em Caracas"},
  "10-14|1874|no dia 14 de outubro de 1874, em campina grande,": {"tituloCurto":"Revolta do Quebra-Quilos em Campina Grande"},
  "10-15|s/ano|em 1928 participa de uma acao revolucionaria que": {"tituloCurto":"Ação revolucionária resgata Otto Braun em Berlim"},
  "10-16|1823|16 de outubro de 1823) foram os embrioes do movi": {"tituloCurto":"Tortura de pão, água e ar antecede Movimento Cabano"},
  "10-16|s/ano|a coluna chega a regiao montanhosa de las villas": {"tituloCurto":"Campanha de Las Villas e Batalha de Santa Clara"},
  "10-17|1912|no seu primeiro discurso, em 17 de outubro de 19": {"tituloCurto":"Discurso de mulheres contra a propriedade e a prisão"},
  "10-17|s/ano|posteriormente, as provincias de ciudad de la ha": {"tituloCurto":"Homenagem póstuma e traslado de combatentes a Cuba"},
  "10-18|s/ano|os comunistas aliados a uniao sovietica transfor": {"tituloCurto":"Ditadura espanhola assassina 2 milhões em quatro décadas"},
  "10-19|1920|reed morre no hospital em 19 de outubro de 1920.": {"tituloCurto":"Morre John Reed, jornalista da Revolução Russa"},
  "10-19|1986|falece em 19 de outubro de 1986, quando o aviao ": {"tituloCurto":"Morre Samora Machel, presidente de Moçambique"},
  "10-20|s/ano|a quarta expedicao, composta de 10 a 12 mil sold": {"tituloCurto":"Destruição de Canudos e resistência camponesa"},
  "10-21|2007|no dia 21 de outubro de 2007, os camponeses ocup": {"tituloCurto":"Ocupação camponesa da Syngenta em Santa Tereza do Oeste"},
  "10-22|s/ano|aprende a ler e a escrever apenas aos 17 anos e,": {"tituloCurto":"Trajetória de abolicionista que fugiu da escravidão"},
  "10-23|1983|gregorio morreu na cidade de sao paulo em 23 de ": {"tituloCurto":"Morre Gregório, amigo dos pobres e inimigo das ditaduras"},
  "10-23|s/ano|em 1966, por insistencia de fidel, regressa a cu": {"tituloCurto":"Che parte para a Bolívia pela libertação da América Latina"},
  "10-24|1975|na noite do dia 24 de outubro de 1975, o jornali": {"tituloCurto":"Assassinato de Herzog no DOI-Codi e comoção popular"},
  "10-25|1917|com o aumento do descontentamento social, os bol": {"tituloCurto":"Revolução Russa: bolcheviques tomam o poder"},
  "10-26|s/ano|em sua militancia no partido social-democrata al": {"tituloCurto":"Rosa Luxemburgo, dirigente socialista e revolucionária"},
  "10-27|s/ano|a pressao do alto continuou ate com forcas contr": {"tituloCurto":"Resistência e rendição dos cabanos no Pará"},
  "10-28|1959|no dia 28 de outubro de 1959, camilo e um pequen": {"tituloCurto":"Desaparecimento de Camilo Cienfuegos em missão contrarrevolucionária"},
  "10-29|s/ano|a historia da nicaragua foi marcada por intensos": {"tituloCurto":"Sandino expulsa invasores e é assassinado na Nicarágua"},
  "10-30|s/ano|foi em 30 de outubro, em frente da fabrica sylva": {"tituloCurto":"Assassinato de Santo Dias pela PM de Maluf"},
  "10-31|s/ano|mais tarde, consegue um emprego como aprendiz de": {"tituloCurto":"Publica Memórias póstumas de Brás-Cubas, o primeiro romance realista do Brasil"},
  "11-01|1922|morreu em 1º de novembro de 1922 ao sofrer um at": {"tituloCurto":"Morre em 1º de novembro de 1922, após publicar em favor da causa anarquista e da Revolução Russa","resumo":"Publicou diversos materiais em favor da causa anarquista e, posteriormente, em favor da Revolução Russa de 1917. Um ano depois é aposentado do serviço público. Morreu em 1º de novembro de 1922 ao sofrer um ataque cardíaco."},
  "11-01|1954|no dia 1º de novembro de 1954, foi fundada a fre": {"tituloCurto":"Fundação da Frente de Libertação Nacional (FLN) da Argélia"},
  "11-02|s/ano|os progressos do trabalho livre, o crescimento d": {"tituloCurto":"Lei do Ventre Livre emancipa o filho da escrava, mas mantém ingênuos com proprietários até os 21 anos"},
  "11-03|s/ano|dicionario da escravidao negra no brasil: novo.": {"tituloCurto":"Dicionário da Escravidão Negra no Brasil: quilombos, insurreições e guerrilhas"},
  "11-04|1969|em 4 de novembro de 1969, foi preso pelo delegad": {"tituloCurto":"Frei Tito é preso pelo delegado Sérgio Fleury e torturado no DOPS","resumo":"Em 4 de novembro de 1969, Tito foi preso pelo delegado Sérgio Fleury, juntamente com outros freis dominicanos. Tito foi torturado no DOPS por cerca de 30 dias em 1969 e, em 1970, novamente sofreu torturas na Operação Bandeirantes. Em 1971, foi deportado para o Chile, onde é ameaçado e foge para a Itália."},
  "11-04|1969|o 4 de novembro de 1969 incorporou-se a historia": {"tituloCurto":"Assassinato de Carlos Marighella e o fim da interdição expiatória"},
  "11-05|1838|o movimento surgiu com a morte de um escravo, em": {"tituloCurto":"Fuga em massa liderada por Manoel Congo após morte de escravo por capataz"},
  "11-06|s/ano|em homenagem aos cabanos, foi erguido na entrada": {"tituloCurto":"Memorial da Cabanagem em homenagem aos cabanos"},
  "11-07|1917|em 25 de outubro de 1917, no calendario russo (7": {"tituloCurto":"Triunfo da Revolução Russa e estabelecimento do socialismo"},
  "11-07|s/ano|desde o dia 7 de novembro, os metalurgicos da co": {"tituloCurto":"Greve dos metalúrgicos da CSN em Volta Redonda e invasão do exército"},
  "11-08|s/ano|comuna de paris foi a primeira revolucao proleta": {"tituloCurto":"Comuna de Paris: primeira revolução proletária da história"},
  "11-09|1989|depois de 28 anos, em 9 de novembro de 1989, a p": {"tituloCurto":"Reabertura da passagem entre os dois países em 9 de novembro de 1989","resumo":"Depois de 28 anos, em 9 de novembro de 1989, a passagem entre os dois países foi reaberta, dentro do contexto de enfraquecimento da União Soviética e dos protestos de alemães orientais."},
  "11-10|1904|rio de janeiro, capital federal, 10 de novembro ": {"tituloCurto":"Revolta da Vacina: população do Rio reage à vacinação obrigatória"},
  "11-11|s/ano|temendo represalias, eusebio de queiros, ministr": {"tituloCurto":"Eusébio de Queirós apresenta projeto que extingue a importação de escravos"},
  "11-12|s/ano|a primeira das suas muitas prisoes ocorreu em 19": {"tituloCurto":"Operário participa das primeiras greves por direitos trabalhistas e lidera levante no Recife","resumo":"A primeira das suas muitas prisões ocorreu em 1917, quando, como operário da construção civil, participou das primeiras greves por direitos trabalhistas e das manifestações em apoio à Revolução Bolchevique. Foi através da leitura que conheceu o marxismo, ideologia que abraçou durante toda sua vida. Em 1930 filiou-se ao Partido Comunista do Brasil e em 1935, como participante da Aliança Nacional Libertadora (ANL), liderou o levante militar-revolucionário no Recife, com a tomada do Quartel General."},
  "11-13|s/ano|cinquenta anos apos o assassinato de joao pedro ": {"tituloCurto":"Cinquenta anos após o assassinato de João Pedro Teixeira, nada de Reforma Agrária"},
  "11-14|s/ano|quando um marinheiro foi condenado a 250 chibata": {"tituloCurto":"Revolta da Chibata: marinheiros tomam couraçados e exigem fim dos castigos"},
  "11-15|1889|no dia 15 de novembro de 1889, um grupo de milit": {"tituloCurto":"Proclamação da República: golpe militar derruba Dom Pedro II"},
  "11-16|s/ano|em 1750, o tratado de madri entre portugal e a e": {"tituloCurto":"Morte de Sepé Tiaraju às margens da Sanga da Bica","resumo":"Em 1750, o tratado de Madri entre Portugal e a Espanha modificou as fronteiras das terras sob o domínio dos Impérios. Com isso ganharam tempo para buscar reforços e avançar sobre os índios dos Sete Povos das Missões. Em 7 de fevereiro de 1756, às margens da Sanga da Bica (hoje rio São Sepé, que deu nome à cidade de São Sepé), na entrada do atual município de São Gabriel, Sepé foi morto."},
  "11-17|s/ano|no seculo 19, chicago era um dos principais polo": {"tituloCurto":"Chicago, polo industrial e sindical, e a origem do 1º de maio"},
  "11-18|s/ano|o governo de guzman foi marcado por acoes de sob": {"tituloCurto":"Governo de Guzmán propõe reforma agrária contra interesses da United Fruit"},
  "11-19|s/ano|ao retornar para minas gerais, depois de um long": {"tituloCurto":"Agitação em Vila Rica pela independência de Minas Gerais"},
  "11-20|1695|em memoria de zumbi, o dia 20 de novembro foi es": {"tituloCurto":"Dia da Consciência Negra em memória de Zumbi"},
  "11-20|2004|em 20 de novembro de 2004, 18 assassinos encapuz": {"tituloCurto":"Massacre do acampamento Terra Prometida"},
  "11-20|2004|falece em 20 de novembro de 2004, vitima de uma ": {"tituloCurto":"Falece em 20 de novembro de 2004, combatente da doutrina neoliberal","resumo":"Falece em 20 de novembro de 2004, vítima de uma parada cardíaca. Homme com um colóquio internacional sobre sua obra, em 1997. Nos últimos anos de sua vida, dedica-se a combater a doutrina econômica neoliberal e denunciar os riscos da hegemonia do capital financeiro e da desregulamentação da economia."},
  "11-21|s/ano|1973: ataque decisivo do exercito a guerrilha do": {"tituloCurto":"Ataque do Exército à Guerrilha do Araguaia"},
  "11-22|1910|assim, no dia 22 de novembro, os marujos tomaram": {"tituloCurto":"Revolta da Chibata"},
  "11-23|s/ano|nesse congresso, os desafios se voltaram para os": {"tituloCurto":"Desafios do Congresso do MST"},
  "11-24|s/ano|em 1954, foi eleito deputado estadual pelo parti": {"tituloCurto":"Eleito deputado estadual pelo PSB"},
  "11-25|1956|participa dos processos de treinamentos que o gr": {"tituloCurto":"Viagem do Granma e início da guerrilha cubana"},
  "11-26|1997|madre cristina faleceu em sao paulo no dia 26 de": {"tituloCurto":"Morre Madre Cristina, defensora dos direitos humanos"},
  "11-27|1910|o desfecho da revolta so ocorreria cinco dias de": {"tituloCurto":"Novo levante dos marinheiros na Ilha das Cobras"},
  "11-28|s/ano|1980: fundacao da frente farabundo marti de libe": {"tituloCurto":"Fundação da Frente Farabundo Martí de Liberación Nacional"},
  "11-29|s/ano|com a derrota japonesa no final da segunda guerr": {"tituloCurto":"Proclamação da República Popular da China"},
  "11-30|s/ano|iii congresso contou com a participacao de mais ": {"tituloCurto":"III Congresso do MST"},
  "12-01|s/ano|poucos artistas souberam evitar o poder sedutor ": {"tituloCurto":"Artistas e monopólios da mídia"},
  "12-02|s/ano|acaba sendo expulso do partido em 1927 e da unia": {"tituloCurto":"Assassinato de Leon Trotsky"},
  "12-03|s/ano|1971: assassinato de carlos lamarca, militar e l": {"tituloCurto":"Assassinato de Carlos Lamarca, líder da guerrilha"},
  "12-04|s/ano|em 1964 fez forte oposicao ao golpe civil-milita": {"tituloCurto":"Oposição ao golpe de 1964"},
  "12-05|s/ano|che nasceu em rosario, na argentina, sendo o mai": {"tituloCurto":"Nasce Che Guevara em Rosário"},
  "12-06|s/ano|1974: morto em combate miguel enriquez, secretar": {"tituloCurto":"Morto em combate Miguel Enríquez, do MIR chileno"},
  "12-07|s/ano|ao desaparecer do vosso convivio, meu carinho po": {"tituloCurto":"Últimos desejos pela pátria"},
  "12-08|s/ano|quarenta mil pessoas armadas promoveram uma revo": {"tituloCurto":"Revolta pela independência do México"},
  "12-09|1824|no dia 9 de dezembro, o general sucre, seu aliad": {"tituloCurto":"Batalha de Ayacucho e liberdade da América espanhola"},
  "12-10|1830|fazenda de san pedro, em santa maria, em 10 de d": {"tituloCurto":"Fazenda de San Pedro, em Santa Maria"},
  "12-10|1979|so em 10 de dezembro de 1979, quando seus restos": {"tituloCurto":"Fim da interdição expiatória de Carlos Marighella"},
  "12-11|s/ano|o amor e que nao se detem ante nenhum obstaculo,": {"tituloCurto":"O amor e a liberdade"},
  "12-12|1746|joaquim jose da silva xavier, conhecido como tir": {"tituloCurto":"Nasce e morre Tiradentes, mártir da Inconfidência"},
  "12-13|s/ano|resgatar as raizes dessa importante data para a ": {"tituloCurto":"O 1º de Maio, dia de luto e de luta"},
  "12-14|s/ano|2000: assassinato de antonio tavares, lider sem-": {"tituloCurto":"Assassinato de Antônio Tavares, líder sem-terra, no Paraná"},
  "12-15|1944|nascido em 15 de dezembro de 1944, trabalhou des": {"tituloCurto":"Nasce seringueiro que fundou o Sindicato de Xapuri"},
  "12-16|s/ano|um oficio confidencial revela que o estado-maior": {"tituloCurto":"Ofício confidencial revela preparação do Massacre da Lapa"},
  "12-17|1819|em 17 de dezembro de 1819, cria a republica da c": {"tituloCurto":"Bolívar cria a República da Colômbia e é eleito presidente"},
  "12-17|1830|falece em 17 de dezembro de 1830, em santa marta": {"tituloCurto":"Falece Bolívar em Santa Marta, na Colômbia"},
  "12-18|s/ano|valmir motta de oliveira tinha dez anos quando p": {"tituloCurto":"Valmir Motta de Oliveira, o Keno, entra no MST"},
  "12-19|s/ano|escravo fugido em 1828 que chefiou por 10 anos u": {"tituloCurto":"Escravo fugido chefiou bando de Robin Hoods sertanejos"},
  "12-20|s/ano|a criacao da internacional foi fundamental para ": {"tituloCurto":"Criação da Primeira Internacional e suas divergências internas"},
  "12-21|s/ano|as posicoes de dom helder camara frente a ditadu": {"tituloCurto":"Morre Dom Hélder Câmara, voz contra a ditadura"},
  "12-22|1988|foi assassinado na porta de sua casa em 22 de de": {"tituloCurto":"Amazônia em Chamas","resumo":"Foi assassinado na porta de sua casa em 22 de dezembro de 1988. Amazônia em chamas, de John Frankenheimer."},
  "12-23|2004|faleceu em 23 de dezembro de 2004, em sao paulo,": {"tituloCurto":"Falece em São Paulo aos 78 anos, deixando obra fundamental"},
  "12-24|1812|em 24 de dezembro de 1812, bolivar inicia sua ca": {"tituloCurto":"Bolívar inicia campanha militar em Nova Granada"},
  "12-25|1977|faleceu em 25 de dezembro de 1977.": {"tituloCurto":"Falece Charlie Chaplin, o eterno Carlitos"},
  "12-26|s/ano|com a revolucao socialista de outubro de 1917, v": {"tituloCurto":"Maiakovski cria a Revista LEF após a Revolução de 1917"},
  "12-27|s/ano|depois de tres meses de greve, ocupando e sendo ": {"tituloCurto":"Greve dos trabalhadores açucareiros de Artigas, no Uruguai"},
  "12-28|s/ano|quando retorna a russia em 1917, e a primeira mu": {"tituloCurto":"Alexandra Kollontai eleita ao Soviete de Petrogrado"},
  "12-29|s/ano|facao: e uma ferramenta importante para os campo": {"tituloCurto":"Símbolos da luta sem-terra: facão e as cores da bandeira"},
  "12-30|s/ano|desde jovem, chama a atencao pela criatividade d": {"tituloCurto":"Patativa do Assaré e a criatividade de seus repentes"},
  "12-31|s/ano|nascido em sao gabriel (rs) numa fazenda de gado": {"tituloCurto":"Hermenegildo de Assis Brasil, militar e comunista gaúcho"},
};
