/**
 * Correções de curadoria da memória (títulos curtos e resumos revisados).
 *
 * GERADO por `scripts/memoria/gerar-correcoes-mistica.mts` a partir do
 * relatório da revisão assistida. NÃO editar à mão: o dado vive no
 * relatório (`docs/relatorios-automacao/revisao-textos-memoria.json`) e é
 * reaplicado pelo gerador. A chave é `chaveCorrecao()` em `correcoes.ts`.
 *
 *   tituloCurto — nome de acontecimento (estilo "Revolta da Balaiada");
 *   resumo      — texto revisado, só quando o relatório propôs.
 */
export interface Correcao {
  tituloCurto?: string;
  resumo?: string;
}

export const CORRECOES: Record<string, Correcao> = {
  "01-01|1849|os praieiros, assim conhecidos por se reunirem e": {"tituloCurto":"Revolta Praieira"},
  "01-01|1959|em 1º de janeiro de 1959, fulgencio batista foge": {"tituloCurto":"Triunfo da Revolução Cubana"},
  "01-01|1994|revolucao zapatista em chiapas, mexico": {"tituloCurto":"Revolta Zapatista em Chiapas"},
  "01-02|1975|assassinato sumario de siraj sikder pelo aparelh": {"tituloCurto":"Assassinato de Siraj Sikder"},
  "01-03|1898|3 de janeiro: 1898: nascimento de luiz carlos pr": {"tituloCurto":"Nascimento de Luiz Carlos Prestes"},
  "01-03|1959|chega a frente de sua coluna em 3 de janeiro de ": {"tituloCurto":"Chegada a Havana"},
  "01-03|1961|inicio da revolta camponesa da baixa de cassange": {"tituloCurto":"Revolta da Baixa de Cassange"},
  "01-04|1923|lenin registra que stalin nao deveria ser secret": {"tituloCurto":"Testamento político de Lenin"},
  "01-04|1988|morreu em 4 de janeiro de 1988, vitima da aids, ": {"tituloCurto":"Morte por Aids"},
  "01-05|1968|alexander dubcek chega ao poder na tchecoslovaqu": {"tituloCurto":"Primavera de Praga"},
  "01-06|1835|inicio da revolta dos cabanos": {"tituloCurto":"Revolta dos Cabanos"},
  "01-07|1835|a data de 7 de janeiro de 1835 e considerada pel": {"tituloCurto":"Cabanagem"},
  "01-07|1919|inicio da semana tragica, em buenos aires": {"tituloCurto":"Semana Trágica em Buenos Aires"},
  "01-07|s/ano|queimam canaviais, fogem as centenas, atacam naz": {"tituloCurto":"Revolta dos Escravizados no Recôncavo"},
  "01-08|1959|fidel castro entra em la habana": {"tituloCurto":"Entrada de Fidel em Havana"},
  "01-10|1981|inicio da revolucao salvadorenha": {"tituloCurto":"Revolução Salvadorenha"},
  "01-11|1929|assassinato de julio antonio mella, martir da re": {"tituloCurto":"Assassinato de Julio Antonio Mella"},
  "01-12|1886|apos a morte de alexandre, a familia, tambem ja ": {"tituloCurto":"Mudança para Kazan"},
  "01-12|2010|perdemos daniel bensaid": {"tituloCurto":"Morte de Daniel Bensaïd"},
  "01-12|s/ano|em 12 de janeiro, um cessar-fogo foi declarado e": {"tituloCurto":"Cessar-fogo com o EZLN"},
  "01-13|1898|emile zola publica “j’accuse…!” e abre publicame": {"tituloCurto":"Publicação de J'Accuse"},
  "01-13|1999|faleceu em itu (sp) em 13 de janeiro de 1999.": {"tituloCurto":"Morte de Sodré"},
  "01-14|s/ano|apos mas de 10 horas de batalha, com 300 mortos ": {"tituloCurto":"Derrota dos Praieiros"},
  "01-15|1919|durante o levante operario em berlim, e presa ju": {"tituloCurto":"Assassinato de Rosa Luxemburgo e Liebknecht"},
  "01-16|1976|operario metalurgico e militante de base do part": {"tituloCurto":"Assassinato de Manoel Fiel Filho"},
  "01-16|1997|assassinato de jose alves dos santos e vanderlei": {"tituloCurto":"Massacre da Fazenda Pinhal Ralo"},
  "01-17|1976|assassinato de manoel fiel filho pela ditadura e": {"tituloCurto":"Assassinato de Manoel Fiel Filho"},
  "01-18|1934|greves gerais insurrecionais formam o soviete da": {"tituloCurto":"Soviete da Marinha Grande"},
  "01-18|s/ano|em 1961, o governo de lumumba sofre um golpe mil": {"tituloCurto":"Golpe e assassinato de Lumumba"},
  "01-19|1944|nascimento de helenira resende, a “preta”, marti": {"tituloCurto":"Nascimento de Helenira Resende"},
  "01-20|1973|em 20 de janeiro de 1973, os projetos de cabral ": {"tituloCurto":"Assassinato de Amílcar Cabral"},
  "01-21|1924|suas forcas foram se acabando aos poucos, e, no ": {"tituloCurto":"Morte de Lenin"},
  "01-21|2000|no dia 21 de janeiro de 2000, a rebeliao popular": {"tituloCurto":"Rebelião de Quito"},
  "01-21|2017|chacina deixa 25 mortos e 24 feridos na grande b": {"tituloCurto":"Chacina de Belém"},
  "01-22|1891|nasce antonio gramsci": {"tituloCurto":"Nascimento de Antonio Gramsci"},
  "01-22|s/ano|em 22 de janeiro, o partido comunista salvadoren": {"tituloCurto":"Insurreição e fuzilamento de Farabundo Martí"},
  "01-23|1937|17 militantes comunistas sao condenados no caso ": {"tituloCurto":"Processos de Moscou"},
  "01-24|1835|inicio da revolta dos males": {"tituloCurto":"Revolta dos Malês"},
  "01-24|1969|em 24 de janeiro de 1969, comanda uma das mais o": {"tituloCurto":"Deserção de Quitaúna"},
  "01-24|2006|faleceu em 24 de janeiro de 2006.": {"tituloCurto":"Morte de Schafik Handal"},
  "01-24|s/ano|encontro aconteceu entre 21 e 24 de janeiro e ma": {"tituloCurto":"Fundação do Movimento dos Trabalhadores Rurais Sem Terra"},
  "01-25|2003|o jornal brasil de fato foi lancado no forum soc": {"tituloCurto":"Lançamento do Brasil de Fato"},
  "01-25|2019|praticas predatorias da vale s.a. ensejam no rom": {"tituloCurto":"Rompimento da Barragem de Brumadinho"},
  "01-27|s/ano|os trabalhadores da cana representaram um dos pi": {"tituloCurto":"Lutas dos trabalhadores da cana no Uruguai"},
  "01-28|s/ano|mahuad era vice-presidente de abdala bucaram, de": {"tituloCurto":"Dolarização no Equador"},
  "01-29|1852|revolta do ronco da abelha triunfa": {"tituloCurto":"Revolta do Ronco da Abelha"},
  "01-30|1956|bombardeio da casa de martin luther king jr. por": {"tituloCurto":"Bombardeio da casa de Martin Luther King Jr."},
  "01-31|1891|revolta inaugura as lutas pela instauracao da re": {"tituloCurto":"Revolta do Porto"},
  "02-01|1932|execucao de farabundo marti, lider revolucionari": {"tituloCurto":"Execução de Farabundo Martí"},
  "02-02|1997|morre chico science": {"tituloCurto":"Morte de Chico Science"},
  "02-03|1953|massacre de batepa, em sao tome e principe": {"tituloCurto":"Massacre de Batepá"},
  "02-03|1969|em 3 de fevereiro de 1969, foi assassinado por u": {"tituloCurto":"Assassinato de Eduardo Mondlane"},
  "02-04|1794|abolida a escravidao nas colonias francesas": {"tituloCurto":"Abolição da escravidão nas colônias francesas"},
  "02-05|1944|nasce henfil, cartunista da esperanca": {"tituloCurto":"Nascimento de Henfil"},
  "02-06|1694|diante da resistencia, o bandeirante domingos jo": {"tituloCurto":"Destruição do Quilombo dos Palmares"},
  "02-07|1756|em 7 de fevereiro de 1756, as margens da sanga d": {"tituloCurto":"Morte de Sepé Tiaraju"},
  "02-08|1911|nascimento de lelia abramo, artista revolucionar": {"tituloCurto":"Nascimento de Lélia Abramo"},
  "02-09|1600|giordano bruno e condenado pelo tribunal da sant": {"tituloCurto":"Condenação de Giordano Bruno"},
  "02-09|1953|padre ezequiel ramin nasceu em padua, italia, em": {"tituloCurto":"Nascimento de Padre Ezequiel Ramin"},
  "02-10|1898|nasce bertold brecht": {"tituloCurto":"Nascimento de Bertolt Brecht"},
  "02-11|1948|faleceu em 11 de fevereiro de 1948, em moscou.": {"tituloCurto":"Morte de Sergei Eisenstein"},
  "02-12|s/ano|ultima expedicao repressiva contra os escravos, ": {"tituloCurto":"Repressão ao quilombo do engenho Santana"},
  "02-13|s/ano|mostrou para a classe trabalhadora que o teatro ": {"tituloCurto":"Teatro como arma revolucionária"},
  "02-14|s/ano|1997: morte de salete strozake, educadora e diri": {"tituloCurto":"Morte de Salete Strozake"},
  "02-15|1966|no dia 15 de fevereiro de 1966, o revolucionario": {"tituloCurto":"Morte de Camilo Torres Restrepo"},
  "02-16|s/ano|outras terras do mundo reclamam a colaboracao de": {"tituloCurto":"Chegada de Che Guevara ao Congo"},
  "02-17|1997|foi eleito senador pelo rio de janeiro, cargo qu": {"tituloCurto":"Morte de Darcy Ribeiro"},
  "02-18|1922|entre 11 e 18 de fevereiro de 1922, diversos esc": {"tituloCurto":"Semana de Arte Moderna"},
  "02-19|s/ano|vendo que a derrota era inevitavel, somoza fugiu": {"tituloCurto":"Fuga de Somoza para Miami"},
  "02-20|s/ano|em 1936, com a eclosao da guerra civil espanhola": {"tituloCurto":"Destituição de Pablo Neruda"},
  "02-21|1934|logo apos um encontro, foi sequestrado com algun": {"tituloCurto":"Assassinato de Sandino"},
  "02-21|1965|em 21 de fevereiro de 1965, aos 39 anos de idade": {"tituloCurto":"Assassinato de Malcolm X"},
  "02-21|2008|trechos da palestra proferida por emilia viotti ": {"tituloCurto":"Palestra de Emília Viotti da Costa na ENFF"},
  "02-22|s/ano|1989: morte de olivio albani, lider sem-terra ol": {"tituloCurto":"Morte de Olívio Albani, líder sem-terra"},
  "02-23|1917|em 8 de marco de 1917 (dia 23 de fevereiro no ca": {"tituloCurto":"Greve das tecelãs de São Petersburgo"},
  "02-24|1965|em 1965 participa da conferencia de argel, em 24": {"tituloCurto":"Participação na Conferência de Argel"},
  "02-25|s/ano|o assassinato de keno ganhou notoriedade interna": {"tituloCurto":"Assassinato de Keno"},
  "02-26|s/ano|1984: greve de peoes da construcao civil – belo ": {"tituloCurto":"Greve dos peões da construção civil"},
  "02-27|1917|1917 (27 de fevereiro no calendario russo): grev": {"tituloCurto":"Greve das tecelãs de São Petersburgo"},
  "02-28|s/ano|depois que tudo terminou, as autoridades difundi": {"tituloCurto":"Desqualificação da guerrilha de Porecatu"},
  "02-29|s/ano|o que o proletariado combativo europeu e america": {"tituloCurto":"Morte de Marx e sua contribuição"},
  "03-01|s/ano|um dos mais importantes dirigentes comunistas po": {"tituloCurto":"Nascimento de Álvaro Cunhal"},
  "03-02|s/ano|o maior conflito armado da historia da america d": {"tituloCurto":"Guerra do Paraguai"},
  "03-03|s/ano|em 1905, enquanto o pais estava em guerra com o ": {"tituloCurto":"Revolta do Couraçado Potemkin"},
  "03-04|s/ano|deixou obras interessantes, como cachaca (contos": {"tituloCurto":"Obras de autor não identificado"},
  "03-06|1817|no dia 6 de marco, foram tomados fortes militare": {"tituloCurto":"Revolução Pernambucana de 1817"},
  "03-06|1996|perseu abramo morreu em 6 de marco de 1996, aos ": {"tituloCurto":"Morte de Perseu Abramo"},
  "03-07|1990|luiz carlos prestes nasceu em porto alegre, no r": {"tituloCurto":"Nascimento e morte de Luiz Carlos Prestes"},
  "03-08|1911|maria bonita nasceu no sitio malhada da caicara,": {"tituloCurto":"Nascimento de Maria Bonita"},
  "03-08|1917|essa atuacao politica das operarias nos estados ": {"tituloCurto":"Origem do Dia Internacional da Mulher"},
  "03-10|1906|ocorre a catastrofe de courrieres, maior acident": {"tituloCurto":"Catástrofe de Courrières"},
  "03-11|1975|e frustrada em portugal a tentativa contrarrevol": {"tituloCurto":"Tentativa de golpe de Spinola"},
  "03-11|s/ano|na operacao de despejo, no dia 11 de marco, fora": {"tituloCurto":"Despejo violento no Rio Grande do Sul"},
  "03-12|2011|a geracao a rasca sai as ruas em portugal": {"tituloCurto":"Manifestação da Geração à rasca"},
  "03-13|1900|nascido em 13 de marco de 1900 no municipio de p": {"tituloCurto":"Nascimento de Gregório"},
  "03-13|1964|realiza-se o comicio da central do brasil": {"tituloCurto":"Comício da Central do Brasil"},
  "03-14|1978|carlo giuliani nasceu em roma no dia 14 de marco": {"tituloCurto":"Assassinato de Carlo Giuliani"},
  "03-14|1998|no dia 14 de marco de 1998, cerca de 500 familia": {"tituloCurto":"Massacre de Parauapebas"},
  "03-14|2018|o dia que marielle franco virou semente": {"tituloCurto":"Assassinato de Marielle Franco"},
  "03-14|s/ano|marx, deprimido e muito enfermo, com problemas r": {"tituloCurto":"Morte de Karl Marx"},
  "03-14|s/ano|o 14 de marco e, todos os anos, um dia de atos e": {"tituloCurto":"Dia de Luta contra Barragens"},
  "03-15|1789|no dia 15 de marco de 1789, o movimento pela ind": {"tituloCurto":"Delatação da Inconfidência Mineira"},
  "03-15|1917|parte do exercito decide apoiar os rebeldes, e o": {"tituloCurto":"Revolução Russa de 1917"},
  "03-15|1938|nikolai bukharin e assassinado como consequencia": {"tituloCurto":"Assassinato de Nikolai Bukharin"},
  "03-15|1951|como resultado de toda essa luta, no dia 15 de m": {"tituloCurto":"Desapropriação de Terras em Porecatu"},
  "03-16|1931|nasce augusto boal, criador do teatro do oprimid": {"tituloCurto":"Nascimento de Augusto Boal"},
  "03-17|1923|jose carlos mariategui retorna ao peru, apos lon": {"tituloCurto":"Retorno de Mariátegui ao Peru"},
  "03-19|1849|inicia-se a insurreicao do queimado": {"tituloCurto":"Insurreição do Queimado"},
  "03-20|1921|conselhos operarios se articulam no ruhr em resp": {"tituloCurto":"Conselhos Operários no Ruhr"},
  "03-22|1968|constitui-se o germen da insurreicao estudantil ": {"tituloCurto":"Mouvement du 22 Mars"},
  "03-23|1980|dom oscar romero profere discurso em defesa do p": {"tituloCurto":"Discurso de Dom Oscar Romero"},
  "03-24|1980|foi assassinado em 24 de marco de 1980, enquanto": {"tituloCurto":"Assassinato de Dom Oscar Romero"},
  "03-25|1922|no dia 25 de marco de 1922, nove pessoas realiza": {"tituloCurto":"Fundação do PCB"},
  "03-25|1931|prisao dos meninos de scottsboro": {"tituloCurto":"Prisão dos Meninos de Scottsboro"},
  "03-27|1944|medico e fundador do movimento esquerda revoluci": {"tituloCurto":"Nascimento de Miguel Enriquez"},
  "03-27|1977|primeiro “mitin” da cnt apos a ditadura franquis": {"tituloCurto":"Primeiro mitin da CNT pós-franquismo"},
  "03-28|1968|em 28 de marco de 1968, a policia assassina o es": {"tituloCurto":"Assassinato de Edson Luís"},
  "03-28|1988|massacre do capacete e a politica de morte do ex": {"tituloCurto":"Massacre do Capacete"},
  "03-29|s/ano|constituiu o ponto culminante de um surto de mob": {"tituloCurto":"Morte de Edson Luís e mobilização estudantil"},
  "03-29|s/ano|em 29 de marco, uma assembleia constituinte e co": {"tituloCurto":"Assembleia Constituinte e liberdade de imprensa"},
  "03-30|1976|greves e levantes irrompem contra o jugo assassi": {"tituloCurto":"Dia da Terra"},
  "03-30|s/ano|mas foi em 30 de marco que a anl foi publicament": {"tituloCurto":"Lançamento da ANL"},
  "03-31|1843|sob sua direcao, o jornal triplicou o numero de ": {"tituloCurto":"Censura a jornal e casamento de Marx"},
  "03-31|1964|apesar de o golpe ter sido deflagrado em 1º de a": {"tituloCurto":"Golpe de 1964 e prisões"},
  "03-31|1964|para o padre abdala jorge, paroco de timoteo, o ": {"tituloCurto":"Massacre de Timóteo"},
  "04-01|1964|mas, em 1º de abril de 1964, o medo das reformas": {"tituloCurto":"Golpe de 1964"},
  "04-02|1962|constantemente ameacado de morte, joao pedro tei": {"tituloCurto":"Assassinato de João Pedro Teixeira"},
  "04-04|1931|revolta da madeira, dia de luta contra a ditadur": {"tituloCurto":"Revolta da Madeira"},
  "04-04|1968|em 4 de abril de 1968, martin luther king jr.": {"tituloCurto":"Martin Luther King Jr."},
  "04-06|2008|germen da revolucao egipcia irrompe com um chama": {"tituloCurto":"Primavera Árabe no Egito"},
  "04-07|1926|morre giovanni amendola, jornalista e politico e": {"tituloCurto":"Morte de Giovanni Amendola"},
  "04-08|1973|faleceu em 8 de abril de 1973 em mougins, franca": {"tituloCurto":"Morte de Pablo Picasso"},
  "04-08|2013|margareth thatcher morre, e com ela se vai sua m": {"tituloCurto":"Morte de Margareth Thatcher"},
  "04-09|1952|tem inicio a revolucao nacional boliviana": {"tituloCurto":"Revolução Nacional Boliviana"},
  "04-10|1870|vladimir ilitich ulianov nasceu em 10 de abril d": {"tituloCurto":"Nascimento de Lenin"},
  "04-10|1919|em 10 de abril de 1919, zapata foi ao encontro d": {"tituloCurto":"Assassinato de Emiliano Zapata"},
  "04-11|1919|e criada a organizacao internacional do trabalho": {"tituloCurto":"Criação da Organização Internacional do Trabalho"},
  "04-11|1925|em 11 de abril de 1925, a coluna prestes, que vi": {"tituloCurto":"Formação da Coluna Prestes"},
  "04-13|1885|nasce gyorgy lukacs": {"tituloCurto":"Nascimento de György Lukács"},
  "04-15|1920|inicia-se o periplo de sacco e vanzetti": {"tituloCurto":"Prisão de Sacco e Vanzetti"},
  "04-16|1917|lenin chega a russia depois de seu exilio na sui": {"tituloCurto":"Chegada de Lênin à Rússia"},
  "04-16|1930|as complicacoes causadas pela amputacao de sua p": {"tituloCurto":"Morte de Mariátegui"},
  "04-17|1961|no dia 17 de abril de 1961, cerca de 1.500 cuban": {"tituloCurto":"Invasão da Baía dos Porcos"},
  "04-17|1996|em homenagem aos trabalhadores assassinados, o d": {"tituloCurto":"Massacre de Eldorado dos Carajás"},
  "04-18|1955|tem inicio a conferencia de bandung, marco de ar": {"tituloCurto":"Conferência de Bandung"},
  "04-20|1961|fracassa a invasao a baia dos porcos": {"tituloCurto":"Fracasso da Invasão da Baía dos Porcos"},
  "04-20|1997|na noite do dia 20 de abril de 1997, depois de p": {"tituloCurto":"Assassinato de Galdino"},
  "04-21|1792|joaquim jose da silva xavier, conhecido como tir": {"tituloCurto":"Enforcamento de Tiradentes"},
  "04-22|1500|assim, pedro alvares cabral, a frente de diverso": {"tituloCurto":"Chegada de Cabral ao Brasil"},
  "04-22|1945|como passo importante para o final da segunda gu": {"tituloCurto":"Tomada de Berlim pelo Exército Soviético"},
  "04-22|2016|e assinado o acordo de paris": {"tituloCurto":"Assinatura do Acordo de Paris"},
  "04-22|s/ano|por que esta no dia 22 de abril esse verbete?": {"tituloCurto":"Nota sobre data de 22 de abril"},
  "04-25|1937|faleceu em 25 de abril de 1937.": {"tituloCurto":"Morte de Antonio Gramsci","resumo":"Faleceu em 25 de abril de 1937. Foi fundador do Partido Comunista Italiano. Na prisão, escreveu os Cadernos do Cárcere, importante contribuição teórica para os movimentos sociais do mundo."},
  "04-25|1974|irrompe a revolucao dos cravos": {"tituloCurto":"Revolução dos Cravos"},
  "04-26|1933|nascimento de filiberto ojeda rios, fundador e l": {"tituloCurto":"Nascimento de Filiberto Ojeda Ríos"},
  "04-27|1972|morte de kwame nkrumah, artifice da libertacao d": {"tituloCurto":"Morte de Kwame Nkrumah"},
  "04-28|1945|benito mussolini e assassinado": {"tituloCurto":"Assassinato de Mussolini"},
  "04-28|1989|quatro anos depois, em 28 de abril de 1989, morr": {"tituloCurto":"Morte de Raúl Sendic"},
  "04-29|1992|rebeliao do povo oprimido de los angeles": {"tituloCurto":"Rebelião de Los Angeles"},
  "04-30|1975|no dia 30 de abril de 1975, saigon, a capital do": {"tituloCurto":"Queda de Saigon"},
  "04-30|1977|as madres de la plaza de mayo fazem sua primeira": {"tituloCurto":"Primeira marcha das Madres de Plaza de Mayo"},
  "04-30|s/ano|no dia 30 de abril, hitler se suicida, e, em 7 d": {"tituloCurto":"Suicídio de Hitler e rendição alemã"},
  "05-01|1912|no dia do trabalhador e da trabalhadora, nasceu ": {"tituloCurto":"Nascimento de Azis Simão"},
  "05-01|s/ano|o acontecimento em chicago tornou-se um fato his": {"tituloCurto":"Primeiro de Maio em Santos"},
  "05-02|1968|irrompe o maio frances": {"tituloCurto":"Maio de 1968 na França"},
  "05-02|1997|paulo freire faleceu em sao paulo no dia 2 de ma": {"tituloCurto":"Morte de Paulo Freire"},
  "05-02|2009|faleceu em 2 de maio de 2009, deixando um legado": {"tituloCurto":"Morte de Augusto Boal"},
  "05-03|1937|comecam as jornadas de maio em barcelona, marco ": {"tituloCurto":"Jornadas de Maio em Barcelona"},
  "05-03|1995|a greve dos petroleiros comecou no dia 3 de maio": {"tituloCurto":"Greve dos petroleiros"},
  "05-05|2010|inflamam-se as lutas contra a austeridade na gre": {"tituloCurto":"Lutas contra a austeridade na Grécia"},
  "05-06|1967|o povo de hong kong se coloca contra o jugo impe": {"tituloCurto":"Levante de Hong Kong"},
  "05-07|1954|o povo vietnamita derrota os franceses em đien b": {"tituloCurto":"Batalha de Điện Biên Phủ"},
  "05-07|2000|paulo em 7 de maio de 2000: ser negro no brasil ": {"tituloCurto":"Reflexão sobre o racismo no Brasil"},
  "05-07|s/ano|no dia 30 de abril, hitler se suicida, e, em 7 d": {"tituloCurto":"Suicídio de Hitler e rendição alemã"},
  "05-08|1830|em 8 de maio de 1830, depois de assistir ao desm": {"tituloCurto":"Exílio e morte de Simón Bolívar"},
  "05-08|1887|alexandre, o mais velho, foi executado em 8 de m": {"tituloCurto":"Execução de Alexandre Ulyanov"},
  "05-08|1945|termina triunfante o levante de praga": {"tituloCurto":"Levante de Praga"},
  "05-09|1969|primeira acao de luta armada de carlos lamarca": {"tituloCurto":"Primeira ação de Carlos Lamarca"},
  "05-10|1933|inicia a bucherverbrennung, processo espetacular": {"tituloCurto":"Queima de livros pelos nazistas"},
  "05-10|1986|em 10 de maio de 1986, mais um lutador tombava p": {"tituloCurto":"Assassinato de Josimo Morais Tavares"},
  "05-10|s/ano|no ano de 1990, o movimento dos trabalhadores ru": {"tituloCurto":"II Congresso do MST"},
  "05-12|1927|sob a lideranca de augusto cesar sandino, o povo": {"tituloCurto":"Levante de Sandino na Nicarágua"},
  "05-12|1978|no dia 12 de maio de 1978, trabalhadores da scan": {"tituloCurto":"Greve na Scania"},
  "05-13|1888|abolicao da escravatura legal no brasil": {"tituloCurto":"Abolição da escravatura no Brasil"},
  "05-14|1948|em 14 de maio de 1948 os britanicos deixam a pal": {"tituloCurto":"Fundação do Estado de Israel"},
  "05-14|1968|a industria sud-aviation e ocupada": {"tituloCurto":"Ocupação da Sud-Aviation"},
  "05-15|2019|greve geral da educacao mostra forcas e contem a": {"tituloCurto":"Greve geral da educação"},
  "05-16|2001|o povo de salvador se coloca nas ruas contra acm": {"tituloCurto":"Repressão ao protesto contra ACM"},
  "05-17|2008|perdemos zelia gattai": {"tituloCurto":"Morte de Zélia Gattai"},
  "05-19|1895|marti foi um articulador da luta e morreu em com": {"tituloCurto":"Morte de José Martí"},
  "05-19|1925|nascido em 19 de maio de 1925, na cidade de omah": {"tituloCurto":"Nascimento de Malcolm X"},
  "05-19|s/ano|em 19 de maio, as tropas portuguesas entraram na": {"tituloCurto":"Revolução Pernambucana de 1817"},
  "05-21|1969|inicio do rosariazo": {"tituloCurto":"Rosariazo"},
  "05-23|1863|fundada a associacao geral dos trabalhadores ale": {"tituloCurto":"Fundação da Associação Geral dos Trabalhadores Alemães"},
  "05-25|1809|em 6 de agosto, a assembleia do alto peru decide": {"tituloCurto":"Independência da Bolívia"},
  "05-26|1824|greve feminina de pawtucket, a “mae de todas as ": {"tituloCurto":"Greve feminina de Pawtucket"},
  "05-27|1797|execucao de gracchus babeuf, nosso igual": {"tituloCurto":"Execução de Gracchus Babeuf"},
  "05-28|1871|147 communards sao fuzilados no mur des federes": {"tituloCurto":"Fuzilamento no Mur des Fédérés"},
  "05-28|s/ano|em uvero, em 28 de maio, se destaca por sua brav": {"tituloCurto":"Ataque ao quartel de Uvero"},
  "05-29|1969|inicia-se o cordobazo": {"tituloCurto":"Cordobazo"},
  "05-30|2002|faleceu em 30 de maio de 2002, de enfisema pulmo": {"tituloCurto":"Morte de líder sindical"},
  "05-31|1968|trabalhadorxs de daccar, senegal, iniciam uma gr": {"tituloCurto":"Greve geral de Daccar"},
  "05-31|s/ano|atos dos sindicatos, movimentos sociais e estuda": {"tituloCurto":"Dia Nacional de Solidariedade"},
  "06-01|1649|agustin sumuroy inicia a insurreicao filipina co": {"tituloCurto":"Insurreição de Sumuroy"},
  "06-02|1843|nos engenhos de acana e concepcion, levantam-se ": {"tituloCurto":"Levante dos engenhos de Ácana e Concepción"},
  "06-02|1959|em 2 de junho de 1959 contrai matrimonio com ale": {"tituloCurto":"Casamento de Che Guevara"},
  "06-03|1896|nascimento de isaac puente amestoy, medico revol": {"tituloCurto":"Nascimento de Isaac Puente Amestoy"},
  "06-03|1995|em 3 de junho de 1995, a greve dos petroleiros t": {"tituloCurto":"Fim da greve dos petroleiros"},
  "06-04|1940|quando tentava sair clandestinamente da franca, ": {"tituloCurto":"Morte de revolucionário"},
  "06-06|1832|finda derrotada a rebeliao de junho": {"tituloCurto":"Rebelião de Junho de 1832"},
  "06-07|1896|nasce imre nagy, martir da revolucao hungara": {"tituloCurto":"Nascimento de Imre Nagy"},
  "06-07|1973|jose porfirio e libertado por decisao judicial, ": {"tituloCurto":"Desaparecimento de José Porfírio"},
  "06-09|2019|com mais de um milhao de pessoas nas ruas, o pov": {"tituloCurto":"Protesto contra lei de extradição em Hong Kong"},
  "06-10|1971|halconazo": {"tituloCurto":"Massacre de Halconazo"},
  "06-11|1963|negras e negros estadunidenses arrancam o civil ": {"tituloCurto":"Aprovação do Civil Rights Act"},
  "06-12|1989|olivio albani estava entre as 700 familias sem-t": {"tituloCurto":"Assassinato de Olívio Albani"},
  "06-12|2014|inicia-se a copa do mundo de 2014, no brasil, so": {"tituloCurto":"Início da Copa do Mundo de 2014"},
  "06-13|1381|liderados por wat tyler, camponeses em revolta q": {"tituloCurto":"Revolta camponesa de 1381"},
  "06-13|2005|faleceu em 13 de junho de 2005, em lisboa.": {"tituloCurto":"Morte de revolucionário português"},
  "06-14|1928|faleceu em londres no dia 14 de junho de 1928, s": {"tituloCurto":"Morte de sufragista inglesa"},
  "06-14|1928|nasce ernesto guevara": {"tituloCurto":"Nascimento de Ernesto Che Guevara"},
  "06-15|1918|inicia-se o movimento que ensejou a reforma univ": {"tituloCurto":"Reforma Universitária de Córdoba"},
  "06-15|s/ano|ocorrido entre os dias 11 e 15 de junho no ginas": {"tituloCurto":"V Congresso do MST"},
  "06-16|1822|em 16 de junho de 1822, bolivar entra vitorioso ": {"tituloCurto":"Entrada de Bolívar em Quito"},
  "06-17|2013|as jornadas de junho tornam-se massivas": {"tituloCurto":"Jornadas de Junho de 2013"},
  "06-18|1953|com o triunfo da luta revolucionaria, e proclama": {"tituloCurto":"Proclamação da República do Egito"},
  "06-18|1954|com o argumento de que era preciso derrubar o pr": {"tituloCurto":"Golpe dos EUA na Guatemala"},
  "06-19|1764|nasce jose gervasio artigas, heroi uruguaio, lib": {"tituloCurto":"Nascimento de José Gervasio Artigas"},
  "06-19|1843|em 19 de junho de 1843 casa-se com jenny von wes": {"tituloCurto":"Casamento de Marx com Jenny Von Westphalen"},
  "06-20|s/ano|em 1933, se exila na uniao sovietica, onde falec": {"tituloCurto":"Exílio e morte na União Soviética"},
  "06-21|2004|faleceu em 21 de junho de 2004 no rio de janeiro": {"tituloCurto":"Morte de Leonel Brizola"},
  "06-22|2002|faleceu em 22 de junho de 2002.": {"tituloCurto":"Assassinato de Evandro Cavalcanti"},
  "06-23|s/ano|foi fundador do partido comunista italiano.": {"tituloCurto":"Fundação do Partido Comunista Italiano"},
  "06-24|2001|milton santos morreu em 24 de junho de 2001 e de": {"tituloCurto":"Morte de Milton Santos"},
  "06-25|1975|a guerra durou quase 11 anos, com a independenci": {"tituloCurto":"Independência de Moçambique"},
  "06-26|1968|26 de junho de 1968, ano magico em que era pecad": {"tituloCurto":"Passeata dos Cem Mil"},
  "06-26|s/ano|ao sairem de bracos dados e com os tracos inconf": {"tituloCurto":"Ataque aos Muckers no Ferrabrás"},
  "06-27|1954|sem o apoio do proprio exercito guatemalteco, ar": {"tituloCurto":"Queda de Árbenz na Guatemala"},
  "06-28|1997|durante 30 anos, seus restos mortais permanecera": {"tituloCurto":"Descoberta dos restos de Che Guevara"},
  "06-29|s/ano|os trabalhadores e trabalhadoras, tendo a frente": {"tituloCurto":"Revolução Boliviana de 1952"},
  "06-30|s/ano|1937: morte de antonio gramsci, filosofo marxist": {"tituloCurto":"Morte de Antonio Gramsci"},
  "07-01|1944|conferencia de bretton woods iniciou-se no dia 1": {"tituloCurto":"Conferência de Bretton Woods"},
  "07-02|1976|vietna foi reunificado em 2 de julho de 1976, so": {"tituloCurto":"Reunificação do Vietnã"},
  "07-03|s/ano|com o tempo, essa comemoracao foi se perdendo, e": {"tituloCurto":"Resgate do Dia Internacional da Mulher"},
  "07-04|s/ano|organization (organizacao dos estudantes sul-afr": {"tituloCurto":"Morte de Steve Biko"},
  "07-05|1920|em 5 de julho, a anl organiza novos comicios pub": {"tituloCurto":"Intentona Comunista de 1935"},
  "07-05|1975|cabo verde se tornou independente em 5 de julho ": {"tituloCurto":"Independência de Cabo Verde"},
  "07-06|1871|castro alves faleceu em salvador (ba) em 6 de ju": {"tituloCurto":"Morte de Castro Alves"},
  "07-07|1897|virgulino ferreira, mais conhecido como lampiao,": {"tituloCurto":"Nascimento de Lampião"},
  "07-07|1953|em junho de 1953 se gradua como medico e, em 7 d": {"tituloCurto":"Viagem de Che Guevara pela América Latina"},
  "07-08|2002|morreu em 8 de julho de 2002.": {"tituloCurto":"Morte de Patativa do Assaré"},
  "07-09|s/ano|1948: realizada a 1ª convencao nacional de defes": {"tituloCurto":"Campanha Nacional do Petróleo"},
  "07-10|1999|faleceu em 10 de julho de 1999, aos 84 anos de i": {"tituloCurto":"Morte de Francisco Julião"},
  "07-11|s/ano|em 1959, as regioes norte e sul entraram em guer": {"tituloCurto":"Guerra do Vietnã"},
  "07-12|1997|durante 30 anos, seus restos mortais permanecera": {"tituloCurto":"Traslado dos restos mortais de um guerrilheiro"},
  "07-13|s/ano|quando a abolicao finalmente veio, alguns estado": {"tituloCurto":"Abolição e o destino dos libertos"},
  "07-14|1789|descontentes com a crise economica que o pais at": {"tituloCurto":"Queda da Bastilha"},
  "07-15|s/ano|a minha vida nada vale em vista da morte de tant": {"tituloCurto":"A vida que nada vale diante da morte de lavradores"},
  "07-16|s/ano|enquanto esteve exilado em kokushkino, dedicou-s": {"tituloCurto":"Exílio e estudo em Kokushkino"},
  "07-17|1936|a acao tomou corpo em 17 de julho de 1936, com u": {"tituloCurto":"Levante militar de Franco na Espanha"},
  "07-18|s/ano|aqui nao ha mais cumplices que tu e eu; tu, por ": {"tituloCurto":"Tortura e execução de Túpac Amaru"},
  "07-19|s/ano|a primeira [ideia] e a de que a arbitrariedade e": {"tituloCurto":"Reflexão sobre o subdesenvolvimento"},
  "07-20|s/ano|era governador do rio grande do sul quando janio": {"tituloCurto":"Campanha da Legalidade"},
  "07-21|s/ano|desde sua independencia da espanha, cuba esteve ": {"tituloCurto":"Emenda Platt e o domínio dos EUA sobre Cuba"},
  "07-22|s/ano|a vitoria brasileira conclui a guerra da indepen": {"tituloCurto":"Tomada de Salvador na Guerra da Independência da Bahia"},
  "07-23|1811|sua primeira experiencia de guerra foi em 23 de ": {"tituloCurto":"Primeira experiência de guerra sob Francisco Miranda"},
  "07-23|1993|anualmente, varias organizacoes promovem no dia ": {"tituloCurto":"Chacina da Candelária"},
  "07-24|1985|por isso, padre ezequiel ramin foi assassinado a": {"tituloCurto":"Assassinato do Padre Ezequiel Ramin"},
  "07-24|2008|somente em 24 de julho de 2008, o governo federa": {"tituloCurto":"Anistia a João Cândido e Marinheiros"},
  "07-25|s/ano|no dia 25 de julho, comemoramos o dia do trabalh": {"tituloCurto":"Dia do Trabalhador Rural"},
  "07-26|1958|em santiago de cuba, se tornou uma das integrant": {"tituloCurto":"Haydée Santamaría e o Movimento 26 de Julho","resumo":"Haydée Santamaría, em Santiago de Cuba, tornou-se integrante da direção nacional do Movimento 26 de Julho, que articulou a guerrilha cubana nas montanhas. Em janeiro de 1959, com o triunfo da revolução cubana, Haydée assumiu a coordenação da recém-fundada Casa das Américas. A instituição tornou-se um ponto de referência cultural da América Latina, promovendo a arte e a literatura."},
  "07-26|s/ano|nesse periodo, duas organizacoes politicas estiv": {"tituloCurto":"Revolução Cubana e o Movimento 26 de Julho"},
  "07-27|1995|entre os dias 24 e 27 de julho de 1995, o movime": {"tituloCurto":"III Congresso Nacional do MST"},
  "07-28|1938|depois de 18 anos, o bando de lampiao sofre sua ": {"tituloCurto":"Última Emboscada do Bando de Lampião"},
  "07-29|s/ano|essas politicas neoliberais, principalmente sob ": {"tituloCurto":"Levante Zapatista em Chiapas"},
  "07-30|s/ano|1991: o mst e a comissao pastoral da terra receb": {"tituloCurto":"Prêmio Nobel Alternativo para MST e CPT"},
  "07-31|s/ano|dessa forma, dessalines tornou-se, em 1804, o pr": {"tituloCurto":"Independência do Haiti e Governo de Dessalines"},
  "08-01|1902|explode a mina de carvao do monte klemba": {"tituloCurto":"Explosão na Mina de Monte Klemba"},
  "08-02|1953|no marco da revolucao boliviana, tem inicio a re": {"tituloCurto":"Reforma Agrária e Dia do Índio na Bolívia"},
  "08-03|1977|como resposta a explosao da mina de chipanga 3, ": {"tituloCurto":"Rebelião Popular após Explosão na Mina Chipanga 3"},
  "08-04|1919|tropas romenas ocupam budapeste e colocam fim a ": {"tituloCurto":"Fim da República dos Conselhos na Hungria"},
  "08-05|1895|friedrich engels morreu em 5 de agosto de 1895 e": {"tituloCurto":"Morte de Friedrich Engels"},
  "08-06|1826|em 6 de agosto, a assembleia do alto peru decide": {"tituloCurto":"Criação da República da Bolívia"},
  "08-06|1945|em 6 de agosto de 1945, a forca aerea estadunide": {"tituloCurto":"Bombardeio de Hiroshima e Nagasaki"},
  "08-06|1960|fidel e raul castro anunciam a lei 851, que naci": {"tituloCurto":"Nacionalização de Empresas Estadunidenses em Cuba"},
  "08-07|2006|foi promulgada a lei maria da penha": {"tituloCurto":"Promulgação da Lei Maria da Penha"},
  "08-08|1942|inicia-se o movimento quit india": {"tituloCurto":"Movimento Quit India"},
  "08-09|1925|nascia francisco rene santucho, intelectual e mi": {"tituloCurto":"Nascimento de Francisco René Santucho"},
  "08-09|1995|na madrugada de 9 de agosto de 1995, um continge": {"tituloCurto":"Massacre de Corumbiara"},
  "08-09|1997|falece em 9 de agosto de 1997, debilitado pela a": {"tituloCurto":"Morte de Henfil","resumo":"Falece em 9 de agosto de 1997, debilitado pela Aids, que havia contraído numa transfusão de sangue, mesma causa da morte de seus irmãos Henfil e Mário, também hemofílicos."},
  "08-10|1792|no bojo da revolucao francesa, uma jornada insur": {"tituloCurto":"Queda da Monarquia na Revolução Francesa"},
  "08-10|1974|em 10 de agosto de 1974, foi encontrado morto, t": {"tituloCurto":"Morte de Vladimir Herzog","resumo":"Em 10 de agosto de 1974, foi encontrado morto, tendo se enforcado. Em março de 1983, seus restos mortais foram trazidos de volta ao Brasil."},
  "08-11|1937|em 11 de agosto de 1937, o conselho nacional est": {"tituloCurto":"Fundação da União Nacional dos Estudantes"},
  "08-11|1979|o rompimento da barragem de machchu-ii, india, v": {"tituloCurto":"Rompimento da barragem de Machchu-II"},
  "08-11|s/ano|dos debates realizados entre os dias 7 e 11 de a": {"tituloCurto":"Congresso camponês e a palavra de ordem Reforma Agrária"},
  "08-12|s/ano|em sua homenagem, o dia 12 de agosto foi declara": {"tituloCurto":"Dia Nacional de Luta das Mulheres do Campo"},
  "08-13|1961|em 13 de agosto de 1961, o lado sovietico ergueu": {"tituloCurto":"Construção do Muro de Berlim"},
  "08-14|1956|faleceu em berlim no dia 14 de agosto de 1956, a": {"tituloCurto":"Morte de Bertolt Brecht"},
  "08-15|1805|em 15 de agosto de 1805, faz um juramento diante": {"tituloCurto":"Juramento de Bolívar no Monte Sacro"},
  "08-16|s/ano|tambem foi coordenador da pastoral da diocese, a": {"tituloCurto":"Atentado contra coordenador da pastoral no Bico do Papagaio"},
  "08-17|s/ano|1987: inicio da primeira intifada, revolta popul": {"tituloCurto":"Início da Primeira Intifada"},
  "08-18|s/ano|portugal passou a ser governado provisoriamente ": {"tituloCurto":"Junta de Salvação Nacional em Portugal"},
  "08-19|1936|sem ter tido qualquer julgamento, foi fuzilado e": {"tituloCurto":"Fuzilamento de Federico García Lorca"},
  "08-19|2009|a fazenda nova alegria foi transformada em assen": {"tituloCurto":"Assentamento da fazenda Nova Alegria"},
  "08-20|1940|no dia 20 de agosto de 1940, leon trotsky e assa": {"tituloCurto":"Assassinato de Leon Trotsky"},
  "08-21|1940|perdemos o maior dos inquietos e profeta – deuts": {"tituloCurto":"Assassinato de Trotsky por Mercader"},
  "08-21|1971|george jackson morreu tres dias antes de ir a ju": {"tituloCurto":"Morte de George Jackson"},
  "08-22|1978|e conduzida a operacao chanchera, que leva as fo": {"tituloCurto":"Operação Chanchera na Nicarágua"},
  "08-23|1927|sacco e vanzetti sao executados": {"tituloCurto":"Execução de Sacco e Vanzetti"},
  "08-24|1882|morreu, vitima de diabetes, em 24 de agosto de 1": {"tituloCurto":"Morte de Luiz Gama"},
  "08-25|s/ano|esta chegando ao fim uma greve que paralisou 60 ": {"tituloCurto":"Greve dos marítimos no Rio de Janeiro"},
  "08-26|1789|em 26 de agosto de 1789, foi promulgada a declar": {"tituloCurto":"Declaração dos Direitos do Homem e do Cidadão"},
  "08-27|1999|faleceu em recife no dia 27 de agosto de 1999.": {"tituloCurto":"Morte de Dom Hélder Câmara"},
  "08-28|1963|em 28 de agosto de 1963, mais de 250 mil pessoas": {"tituloCurto":"Marcha sobre Washington por Trabalho e Liberdade"},
  "08-29|s/ano|foi vendedor, jornalista, prefeito e instrutor d": {"tituloCurto":"Trajetória de Graciliano Ramos"},
  "08-30|s/ano|em 1844, na alemanha, conhece pessoalmente karl ": {"tituloCurto":"Encontro de Engels com Karl Marx"},
  "08-31|1958|em 31 de agosto de 1958 inicia a invasao a parte": {"tituloCurto":"Campanha de Las Villas"},
  "09-01|s/ano|nas primeiras decadas do seculo 19, no maranhao,": {"tituloCurto":"Revolta da Balaiada"},
  "09-02|1969|ho chi-minh morre em 2 de setembro de 1969, nao ": {"tituloCurto":"Morte de Ho Chi-minh"},
  "09-03|s/ano|pm dispara contra um piquete de cortadores de ca": {"tituloCurto":"Massacre de Leme"},
  "09-04|1839|um tribunal reunido em janeiro de 1838 condenou ": {"tituloCurto":"Enforcamento de Manoel Congo"},
  "09-04|1958|em 4 de setembro de 1958, forma, junto com melba": {"tituloCurto":"Formação do Pelotão Mariana Grajales"},
  "09-05|s/ano|durante a ditadura de batista, seus aliados enri": {"tituloCurto":"Ditadura de Batista"},
  "09-06|1977|em 6 de setembro de 1977, foi preso em um bloque": {"tituloCurto":"Prisão de Biko"},
  "09-07|s/ano|assim, na madrugada de 7 de setembro, aproveitan": {"tituloCurto":"Ocupação das Fazendas Macali e Brilhante"},
  "09-08|s/ano|1849 cerca de 1.600 rebeldes praieiros avancas s": {"tituloCurto":"Batalha dos Praieiros"},
  "09-09|1976|mao tse-tung faleceu em 9 de setembro de 1976, c": {"tituloCurto":"Morte de Mao Tse-tung"},
  "09-09|s/ano|em 9 de setembro, tem seu primeiro encontro com ": {"tituloCurto":"Combates de La Federal e Cuatro Compañeros"},
  "09-10|1974|a independencia da guine-bissau foi proclamada e": {"tituloCurto":"Independência da Guiné-Bissau"},
  "09-10|1979|agostinho neto falece em 10 de setembro de 1979,": {"tituloCurto":"Morte de Agostinho Neto"},
  "09-11|1973|na manha do dia 11 de setembro, enquanto parte d": {"tituloCurto":"Golpe Militar no Chile"},
  "09-11|1977|biko morreu no dia 11 de setembro de 1977, enqua": {"tituloCurto":"Morte de Steve Biko"},
  "09-12|s/ano|mapa do brasil: o mst e um movimento nacional e ": {"tituloCurto":"Símbolos do MST"},
  "09-13|s/ano|dom helder pessoa camara nasceu em fortaleza, ce": {"tituloCurto":"Nascimento de Dom Hélder Câmara"},
  "09-14|s/ano|em 9 de setembro, tem seu primeiro encontro com ": {"tituloCurto":"Combates de La Federal e Cuatro Compañeros"},
  "09-15|s/ano|com esperanca de se livrar dos problemas sociais": {"tituloCurto":"Peregrinação de Antônio Conselheiro"},
  "09-16|1973|em 16 de setembro de 1973, foi assassinado a tir": {"tituloCurto":"Assassinato de Victor Jara"},
  "09-16|1989|no dia 16 de setembro, a udr e a policia militar": {"tituloCurto":"Despejo em Santa Catarina"},
  "09-17|1971|em 17 de setembro de 1971, lamarca e assassinado": {"tituloCurto":"Morte de Lamarca"},
  "09-18|1850|mas, para dificultar o acesso dos pobres e mante": {"tituloCurto":"Lei de Terras de 1850"},
  "09-19|2002|dom jose faleceu em 19 de setembro de 2002.": {"tituloCurto":"Morte de Dom José Gomes"},
  "09-20|s/ano|me mantenho firme na conviccao de que somente a ": {"tituloCurto":"Exílio de Gregório Bezerra"},
  "09-21|s/ano|o 21 de setembro foi escolhido para o combate ao": {"tituloCurto":"Dia de Combate aos Monocultivos"},
  "09-22|s/ano|em 1964, henfil trabalha como cartunista na revi": {"tituloCurto":"Henfil e a Revista Alterosa"},
  "09-23|1973|pablo neruda, grande comunista e poeta, morre em": {"tituloCurto":"Morte de Pablo Neruda"},
  "09-23|2005|na tarde de 23 de setembro de 2005, comeco da pr": {"tituloCurto":"Morte de Apolônio de Carvalho"},
  "09-24|1973|a independencia da guine-bissau foi proclamada e": {"tituloCurto":"Independência da Guiné-Bissau"},
  "09-24|1973|morou na franca ate sua morte, em 24 de setembro": {"tituloCurto":"Exílio e morte na França"},
  "09-25|1828|em 25 de setembro de 1828, bolivar, que insistia": {"tituloCurto":"Atentado contra Bolívar"},
  "09-25|1964|a luta armada iniciou-se em 25 de setembro de 19": {"tituloCurto":"Início da Luta Armada em Moçambique"},
  "09-26|s/ano|no total as mortes subiram a 100.": {"tituloCurto":"Revolta dos Malês"},
  "09-27|s/ano|tudo comecou com getulio vargas na decada de 30,": {"tituloCurto":"Colonização do Norte do Paraná"},
  "09-28|1932|em chillan, chile, nasceu em 28 de setembro de 1": {"tituloCurto":"Nascimento de Víctor Jara"},
  "09-29|1908|faleceu em 29 de setembro de 1908.": {"tituloCurto":"Morte de Escritor Brasileiro"},
  "09-30|s/ano|geopolitica da fome – 2 volumes.": {"tituloCurto":"Geopolítica da Fome"},
  "10-01|1949|em 1º de outubro de 1949, e declarada a republic": {"tituloCurto":"Proclamação da República Popular da China"},
  "10-02|1992|na manha do dia 2 de outubro de 1992, a tropa de": {"tituloCurto":"Massacre do Carandiru"},
  "10-03|1953|como resultado, em 3 de outubro de 1953, foi cri": {"tituloCurto":"Criação da Petrobras"},
  "10-03|1990|a unificacao da alemanha se completaria em 3 de ": {"tituloCurto":"Unificação da Alemanha"},
  "10-04|2009|faleceu em 4 de outubro de 2009.": {"tituloCurto":"Morte de Mercedes Sosa"},
  "10-05|1897|em 05 de outubro de 1897, cessou a resistencia d": {"tituloCurto":"Fim da Resistência de Canudos"},
  "10-05|1974|miguel enriquez e assassinado com dez tiros em 5": {"tituloCurto":"Assassinato de Miguel Enriquez"},
  "10-06|1963|no dia 06 de outubro de 1963 foi realizada a pri": {"tituloCurto":"Assembleia em Ipatinga"},
  "10-07|1963|para o padre abdala jorge, paroco de timoteo, o ": {"tituloCurto":"Massacre de Timóteo"},
  "10-08|1967|no combate de quebrada del yuro, em 8 de outubro": {"tituloCurto":"Captura e Morte de Che Guevara"},
  "10-08|s/ano|descontente com a vpr, ingressa no movimento rev": {"tituloCurto":"Guerrilha no Sertão Baiano"},
  "10-09|s/ano|augustin farabundo marti rodriguez foi um grande": {"tituloCurto":"Nascimento de Farabundo Martí"},
  "10-10|1980|em 10 de outubro de 1980, e criada a frente fara": {"tituloCurto":"Criação da FMLN"},
  "10-11|s/ano|a essa altura, os indigenas se juntavam aos milh": {"tituloCurto":"Insurgência de Túpac Amaru"},
  "10-12|s/ano|alem disso, o mexico aderiu ao acordo de livre c": {"tituloCurto":"México e o Nafta"},
  "10-13|s/ano|1983: vitoria da encruzilhada natalino, rio gran": {"tituloCurto":"Vitória da Encruzilhada Natalino"},
  "10-14|1813|em 14 de outubro de 1813, depois de uma entrada ": {"tituloCurto":"Aclamação de Bolívar como Libertador"},
  "10-14|1874|no dia 14 de outubro de 1874, em campina grande,": {"tituloCurto":"Revolta do Imposto do Chão"},
  "10-15|s/ano|em 1928 participa de uma acao revolucionaria que": {"tituloCurto":"Resgate de Otto Braun"},
  "10-16|1823|16 de outubro de 1823) foram os embrioes do movi": {"tituloCurto":"Embriões do Movimento Cabano"},
  "10-16|s/ano|a coluna chega a regiao montanhosa de las villas": {"tituloCurto":"Campanha de Las Villas"},
  "10-17|1912|no seu primeiro discurso, em 17 de outubro de 19": {"tituloCurto":"Discurso de Mulher Anarquista"},
  "10-17|s/ano|posteriormente, as provincias de ciudad de la ha": {"tituloCurto":"Homenagem Póstuma a Combatente Cubano"},
  "10-18|s/ano|os comunistas aliados a uniao sovietica transfor": {"tituloCurto":"Ditadura Franquista na Espanha"},
  "10-19|1920|reed morre no hospital em 19 de outubro de 1920.": {"tituloCurto":"Morte de John Reed"},
  "10-19|1986|falece em 19 de outubro de 1986, quando o aviao ": {"tituloCurto":"Morte de Samora Machel"},
  "10-20|s/ano|a quarta expedicao, composta de 10 a 12 mil sold": {"tituloCurto":"Destruição de Canudos"},
  "10-21|2007|no dia 21 de outubro de 2007, os camponeses ocup": {"tituloCurto":"Ocupação da Syngenta"},
  "10-22|s/ano|aprende a ler e a escrever apenas aos 17 anos e,": {"tituloCurto":"Trajetória de Abolicionista"},
  "10-23|1983|gregorio morreu na cidade de sao paulo em 23 de ": {"tituloCurto":"Morte de Gregório e Ocupação da Syngenta"},
  "10-23|s/ano|em 1966, por insistencia de fidel, regressa a cu": {"tituloCurto":"Che Guevara na Bolívia"},
  "10-24|1975|na noite do dia 24 de outubro de 1975, o jornali": {"tituloCurto":"Assassinato de Vladimir Herzog"},
  "10-25|1917|com o aumento do descontentamento social, os bol": {"tituloCurto":"Revolução Russa de 1917"},
  "10-26|s/ano|em sua militancia no partido social-democrata al": {"tituloCurto":"Rosa Luxemburgo no Partido Social-Democrata"},
  "10-27|s/ano|a pressao do alto continuou ate com forcas contr": {"tituloCurto":"Resistência Cabanagem"},
  "10-28|1959|no dia 28 de outubro de 1959, camilo e um pequen": {"tituloCurto":"Desaparecimento de Camilo Cienfuegos"},
  "10-29|s/ano|a historia da nicaragua foi marcada por intensos": {"tituloCurto":"Luta de Sandino na Nicarágua"},
  "10-30|s/ano|foi em 30 de outubro, em frente da fabrica sylva": {"tituloCurto":"Assassinato de Santo Dias"},
  "10-31|s/ano|mais tarde, consegue um emprego como aprendiz de": {"tituloCurto":"Ingresso no serviço público e obra realista"},
  "11-01|1922|morreu em 1º de novembro de 1922 ao sofrer um at": {"tituloCurto":"Morte de anarquista e apoiador da Revolução Russa"},
  "11-01|1954|no dia 1º de novembro de 1954, foi fundada a fre": {"tituloCurto":"Fundação da Frente de Libertação Nacional da Argélia"},
  "11-02|s/ano|os progressos do trabalho livre, o crescimento d": {"tituloCurto":"Lei do Ventre Livre"},
  "11-03|s/ano|dicionario da escravidao negra no brasil: novo.": {"tituloCurto":"Referências sobre escravidão negra no Brasil"},
  "11-04|1969|em 4 de novembro de 1969, foi preso pelo delegad": {"tituloCurto":"Prisão e tortura de frei dominicano"},
  "11-04|1969|o 4 de novembro de 1969 incorporou-se a historia": {"tituloCurto":"Assassinato de Carlos Marighella"},
  "11-05|1838|o movimento surgiu com a morte de um escravo, em": {"tituloCurto":"Revolta de Manoel Congo"},
  "11-06|s/ano|em homenagem aos cabanos, foi erguido na entrada": {"tituloCurto":"Cabanagem"},
  "11-07|1917|em 25 de outubro de 1917, no calendario russo (7": {"tituloCurto":"Revolução Russa de 1917"},
  "11-07|s/ano|desde o dia 7 de novembro, os metalurgicos da co": {"tituloCurto":"Greve e Massacre de Volta Redonda"},
  "11-08|s/ano|comuna de paris foi a primeira revolucao proleta": {"tituloCurto":"Comuna de Paris"},
  "11-09|1989|depois de 28 anos, em 9 de novembro de 1989, a p": {"tituloCurto":"Queda do Muro de Berlim"},
  "11-10|1904|rio de janeiro, capital federal, 10 de novembro ": {"tituloCurto":"Revolta da Vacina"},
  "11-11|s/ano|temendo represalias, eusebio de queiros, ministr": {"tituloCurto":"Lei Eusébio de Queirós"},
  "11-12|s/ano|a primeira das suas muitas prisoes ocorreu em 19": {"tituloCurto":"Prisões e militância de operário comunista"},
  "11-13|s/ano|cinquenta anos apos o assassinato de joao pedro ": {"tituloCurto":"Assassinato de João Pedro Teixeira"},
  "11-14|s/ano|quando um marinheiro foi condenado a 250 chibata": {"tituloCurto":"Revolta da Chibata"},
  "11-15|1889|no dia 15 de novembro de 1889, um grupo de milit": {"tituloCurto":"Proclamação da República"},
  "11-16|s/ano|em 1750, o tratado de madri entre portugal e a e": {"tituloCurto":"Morte de Sepé Tiaraju"},
  "11-17|s/ano|no seculo 19, chicago era um dos principais polo": {"tituloCurto":"Dia Internacional dos Trabalhadores"},
  "11-18|s/ano|o governo de guzman foi marcado por acoes de sob": {"tituloCurto":"Governo de Guzmán e reforma agrária"},
  "11-19|s/ano|ao retornar para minas gerais, depois de um long": {"tituloCurto":"Inconfidência Mineira"},
  "11-20|1695|em memoria de zumbi, o dia 20 de novembro foi es": {"tituloCurto":"Dia da Consciência Negra"},
  "11-20|2004|em 20 de novembro de 2004, 18 assassinos encapuz": {"tituloCurto":"Massacre do Acampamento Terra Prometida"},
  "11-20|2004|falece em 20 de novembro de 2004, vitima de uma ": {"tituloCurto":"Morte de intelectual crítico do neoliberalismo"},
  "11-21|s/ano|1973: ataque decisivo do exercito a guerrilha do": {"tituloCurto":"Ataque à Guerrilha do Araguaia"},
  "11-22|1910|assim, no dia 22 de novembro, os marujos tomaram": {"tituloCurto":"Revolta da Chibata"},
  "11-23|s/ano|nesse congresso, os desafios se voltaram para os": {"tituloCurto":"Congresso do MST"},
  "11-24|s/ano|em 1954, foi eleito deputado estadual pelo parti": {"tituloCurto":"Eleição de deputado estadual pelo PSB"},
  "11-25|1956|participa dos processos de treinamentos que o gr": {"tituloCurto":"Viagem do Granma"},
  "11-26|1997|madre cristina faleceu em sao paulo no dia 26 de": {"tituloCurto":"Morte de Madre Cristina"},
  "11-27|1910|o desfecho da revolta so ocorreria cinco dias de": {"tituloCurto":"Revolta da Chibata"},
  "11-28|s/ano|1980: fundacao da frente farabundo marti de libe": {"tituloCurto":"Fundação da FMLN"},
  "11-29|s/ano|com a derrota japonesa no final da segunda guerr": {"tituloCurto":"Revolução Chinesa"},
  "11-30|s/ano|iii congresso contou com a participacao de mais ": {"tituloCurto":"III Congresso do MST"},
  "12-01|s/ano|poucos artistas souberam evitar o poder sedutor ": {"tituloCurto":"Artistas e monopólios da mídia"},
  "12-02|s/ano|acaba sendo expulso do partido em 1927 e da unia": {"tituloCurto":"Assassinato de Trotsky"},
  "12-03|s/ano|1971: assassinato de carlos lamarca, militar e l": {"tituloCurto":"Assassinato de Carlos Lamarca"},
  "12-04|s/ano|em 1964 fez forte oposicao ao golpe civil-milita": {"tituloCurto":"Oposição ao golpe de 1964"},
  "12-05|s/ano|che nasceu em rosario, na argentina, sendo o mai": {"tituloCurto":"Nascimento de Che Guevara"},
  "12-06|s/ano|1974: morto em combate miguel enriquez, secretar": {"tituloCurto":"Morte de Miguel Enríquez"},
  "12-07|s/ano|ao desaparecer do vosso convivio, meu carinho po": {"tituloCurto":"Últimos desejos"},
  "12-08|s/ano|quarenta mil pessoas armadas promoveram uma revo": {"tituloCurto":"Revolta pela independência do México"},
  "12-09|1824|no dia 9 de dezembro, o general sucre, seu aliad": {"tituloCurto":"Batalha de Ayacucho"},
  "12-10|1830|fazenda de san pedro, em santa maria, em 10 de d": {"tituloCurto":"Fazenda de San Pedro"},
  "12-10|1979|so em 10 de dezembro de 1979, quando seus restos": {"tituloCurto":"Fim da interdição de Carlos Marighella"},
  "12-11|s/ano|o amor e que nao se detem ante nenhum obstaculo,": {"tituloCurto":"Reflexão sobre o amor"},
  "12-12|1746|joaquim jose da silva xavier, conhecido como tir": {"tituloCurto":"Tiradentes"},
  "12-13|s/ano|resgatar as raizes dessa importante data para a ": {"tituloCurto":"1º de Maio"},
  "12-14|s/ano|2000: assassinato de antonio tavares, lider sem-": {"tituloCurto":"Assassinato de Antônio Tavares, líder sem-terra"},
  "12-15|1944|nascido em 15 de dezembro de 1944, trabalhou des": {"tituloCurto":"Seringueiro fundador do Sindicato de Xapuri","resumo":"Nascido em 15 de dezembro de 1944, trabalhou desde criança como seringueiro e aprendeu a ler apenas aos 20 anos. Desde o final da década de 1970, esteve envolvido na organização de sua categoria, os seringueiros. Foi fundador do Sindicato dos Trabalhadores Rurais de Xapuri e, mais tarde, do Partido dos Trabalhadores (PT) e da CUT."},
  "12-16|s/ano|um oficio confidencial revela que o estado-maior": {"tituloCurto":"Massacre da Lapa","resumo":"Um ofício confidencial revela que o Estado-maior do II Exército pediu à Secretaria de Segurança Pública, com 48 horas de antecedência, que bloqueasse a rua Pio XI na manhã de 16 de dezembro. O Massacre da Lapa foi possível por uma traição de Jover Telles, membro do próprio Comitê Central do PCdoB."},
  "12-17|1819|em 17 de dezembro de 1819, cria a republica da c": {"tituloCurto":"Criação da República da Colômbia por Bolívar","resumo":"Em 17 de dezembro de 1819, Bolívar cria a República da Colômbia, da qual é eleito presidente. Em 16 de junho de 1822, entra vitorioso em Quito. Nessa cidade, conheceria Manuela Sáenz, sua grande companheira."},
  "12-17|1830|falece em 17 de dezembro de 1830, em santa marta": {"tituloCurto":"Morte de Bolívar em Santa Marta","resumo":"Bolívar falece em 17 de dezembro de 1830, em Santa Marta, capital da República da Colômbia. Hoje, os processos populares em curso na América Latina retomaram as ideias e práticas desse grande lutador, na perspectiva de trazer presente a proposta de libertação e integração latino-americana."},
  "12-18|s/ano|valmir motta de oliveira tinha dez anos quando p": {"tituloCurto":"Ocupação de terras em Juvenópolis","resumo":"Valmir Motta de Oliveira, o Keno, tinha dez anos quando participou com os pais de uma ocupação de terras em Juvenópolis, no Paraná. Hoje, seus pais são assentados em Diamante do Oeste (PR). Desde a juventude, Keno sentia-se parte do Movimento dos Trabalhadores Rurais Sem Terra e com 17 anos intensificou sua participação na organização."},
  "12-19|s/ano|escravo fugido em 1828 que chefiou por 10 anos u": {"tituloCurto":"Bando de Robin Hoods sertanejos"},
  "12-20|s/ano|a criacao da internacional foi fundamental para ": {"tituloCurto":"Criação e fim da Primeira Internacional"},
  "12-21|s/ano|as posicoes de dom helder camara frente a ditadu": {"tituloCurto":"Morte de Dom Hélder Câmara","resumo":"As posições de Dom Hélder Câmara frente à ditadura militar no Brasil eram claras. Faleceu em Recife no dia 27 de agosto de 1999."},
  "12-22|1988|foi assassinado na porta de sua casa em 22 de de": {"tituloCurto":"Assassinato na porta de casa"},
  "12-23|2004|faleceu em 23 de dezembro de 2004, em sao paulo,": {"tituloCurto":"Morte em São Paulo aos 78 anos"},
  "12-24|1812|em 24 de dezembro de 1812, bolivar inicia sua ca": {"tituloCurto":"Campanha de Bolívar em Nova Granada"},
  "12-25|1977|faleceu em 25 de dezembro de 1977.": {"tituloCurto":"Morte de Charles Chaplin","resumo":"Charles Chaplin faleceu em 25 de dezembro de 1977. Seus filmes foram proibidos na Alemanha nazista, considerados subversivos. O personagem mais conhecido é Carlitos, um andarilho educado e de maneiras refinadas que enverga, cheio de dignidade, um fraque roto e maior que seu número, com sapatos esgarçados, chapéu coco e uma bengala de bambu."},
  "12-26|s/ano|com a revolucao socialista de outubro de 1917, v": {"tituloCurto":"Maiakovski e a Revista LEF"},
  "12-27|s/ano|depois de tres meses de greve, ocupando e sendo ": {"tituloCurto":"Greve dos açucareiros de Artigas"},
  "12-28|s/ano|quando retorna a russia em 1917, e a primeira mu": {"tituloCurto":"Alexandra Kollontai no Soviete de Petrogrado"},
  "12-29|s/ano|facao: e uma ferramenta importante para os campo": {"tituloCurto":"Símbolos da luta sem-terra","resumo":"Facão: é uma ferramenta importante para os camponeses e camponesas. A cor branca é a paz que os sem-terra buscam, com alimento, saúde, educação, moradia, trabalho para todas as pessoas. Representa a justiça social buscada através das lutas. A cor vermelha é o sangue das trabalhadoras e trabalhadores, é a vida dos povos. A cor preta é a reverência aos lutadores e lutadoras que deram suas vidas por uma sociedade diferente e justa."},
  "12-30|s/ano|desde jovem, chama a atencao pela criatividade d": {"tituloCurto":"Patativa do Assaré, poeta repentista","resumo":"Patativa do Assaré, desde jovem, chama a atenção pela criatividade de seus repentes, cantados em festas e feiras da região. Frequentou a escola apenas por alguns meses, quando tinha 12 anos, e por isso seus versos são marcados pela oralidade. Quando elaborava um novo poema, primeiro memorizava um verso para depois escrever outro."},
  "12-31|s/ano|nascido em sao gabriel (rs) numa fazenda de gado": {"tituloCurto":"Hermenegildo de Assis Brasil"},
};
